### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by SvenVanPoucke** [MIT-LCP/mimic-code#10]
Which exp_flg are available without calculation.
Cheers
Sven

**Comment by tompollard** [comment]
By "exp_flg" my understanding is that you are looking for columns in the data that indicate a patient's survival status. To answer questions such as this, I recommend reviewing the documentation at:
http://mimic.physionet.org/about/mimic/ (select "Tables in MIMIC" from the left hand menu). 

The patients table includes a flag titled "HOSPITAL_EXPIRE_FLAG" which indicates whether or not a patient died during a hospital stay: http://mimic.physionet.org/mimictables/patients/. Additional flags may be added over time.
