### ISSUE TITLE
charevents table: difference between column "error" in MIMICIII and column "warning" in MIMICIV

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-code#1002]
In some scripts for MIMICIII dataset, the error column is used to exclude certain rows using the following statement
" (error IS NULL OR error = 0)"
However, this column does not exist in MIMIVIV dataset, shall we just ignore such statement moving forward?
Or shall we use the "warning" column instead?
Thanks

**Comment by Nintorac** [comment]
Hi,

What sort of issues will lead to an event being tagged with a warning?

I'm currently filtering such that `warning=0` and I'm getting data that seems to be errors eg 1e6 heart rate maximum  

Values seem more sensible when `warning!=0` strangely

**Comment by alistairewj** [comment]
`warning` is exceedingly rare, I think less than 1% of the rows have it if that. We never learned what the meaning of the column is. The best guess is it's a human input "warning" annotation, likely there for any number of clinical reasons (i.e. not one consistent reason).

**Comment by Nintorac** [comment]
Woah, fast response!  :100: 

Ok thanks, makes sense
