### ISSUE TITLE
Question: Is the MIMC-CXR data related to MIMIC-III clinical database?

### ISSUE THREAD

**Issue by vasudev-sharma** [MIT-LCP/mimic-code#1009]
I've a question in regards to the MIMIC-CXR data. I've been wondering is the MIMIC-III clinical database anyway related to the MIMIC-CXR? If it is, then how? 

Actually, I'm interested in knowing whether vital signs, laboratory reports, and other information of the patients of the MIMIC-CXR could be retrieved or not. So, I was just curious is there a relation between MIMIC-CXR and MIMIC-III because MIMIC-III has that information, but MIMIC-CXR doesn't. That's why I opened this issue to better understand if this information could be obtained using MIMIC-III.

If there is no relation between the two datasets, then is it possible to get access to BIDMC EHR which was used to collect the x-ray images of MIMIC-CXR data?

Thanks in advance!!

**Comment by alistairewj** [comment]
Hrm, I don't get the same numbers. I only find ~100 patients who aren't in both datasets (which I'd expect just from things being approximate). I also found those two subjects (12427812, 14029832) in the mimic_core.patients table. What did you use as the source for the MIMIC-CXR `patient_id` (aka `subject_id`)?
