### ISSUE TITLE
wget command retrieves index.html of all study directories before downloading study images

### ISSUE THREAD

**Issue by ayhyap** [MIT-LCP/mimic-code#1012]
The command listed on the dataset page is only downloading the index.html of each study directory, and not the dicom files.
`wget -r -N -c -np --user <PHYSIONETUSERNAME> --ask-password https://alpha.physionet.org/files/mimic-cxr/2.0.0/`

That is, the command is downloading
`/physionet.org/files/mimic-cxr/2.0.0/files/p**/p******/s*******/index.html`

instead of the two dicom files under that directory
`/physionet.org/files/mimic-cxr/2.0.0/files/p**/p******/s*******/*****.dcm`

MIMIC-CXR-JPG has the same problem.

Am I missing something obvious?
(I interrupted the wget command after seeing all of the 200+ downloaded studies lacking image files)

**Comment by meghalD** [comment]
I started with physionet url to download but it gives index.html files as mentioned in the issue. As per the suggested solution, I used GCP for download but it always add ._gstmp extension for all the files. Is there a method to read these files or avoid this  extension ?

**Comment by alistairewj** [comment]
gstmp means the download is incomplete. it's a new feature of gsutil allowing download resume I believe
