### ISSUE TITLE
What is the total disk space required to download the dataset

### ISSUE THREAD

**Issue by munachisonwadike** [MIT-LCP/mimic-code#1025]
It is unclear from the website and Physionet paper, what the exact size of the files in MIMIC-CXR-JPG is. I would greatly appreciate the help in understanding this space requirement?

**Comment by alistairewj** [comment]
I appreciate the positive sentiment! :)

We kept the full resolution as it could be useful for a number of analyses. You lose a lot of resolution going from 3k to 512. Of course, having a resized version would be beneficial in a number of ways. Not sure any of us will have the time to do it in the near future, however.

**Comment by tompollard** [comment]
> I appreciate the positive sentiment! :)

lol, always great to hear from people who appreciate the effort that goes into data sharing!  Perhaps @njan-creative could create the dataset for us and submit to PhysioNet?

**Comment by njan-creative** [comment]
If I had the bandwidth and memory to download and preprocess.. I would not crib. :)

**Comment by tompollard** [comment]
@njan-creative instead of downloading the data, why not analyze in the cloud? This is how we generally work with PhysioNet datasets. e.g. here is an example of a notebook using MIMIC-CXR-JPG: https://github.com/MIT-LCP/2019_aarhus_critical_data/blob/master/tutorials/mimic-cxr/mimic-cxr-train-aarhus.ipynb

**Comment by njan-creative** [comment]
I do not have the google cloud account.

I am working on report generation. One link of resized data of size 512, I found shared by one of the authors, but unfortunately it is only partial data. The estimate of 6 GB came from the below.

> [MIMIC-CXR](https://drive.google.com/file/d/1aVamW2kBkcVUxhq2lOi38mKHEQ33FhQZ/view?usp=sharing) (2.27 GB): Unique study of 91,685 AP view image and associated report pairs.

**Comment by alistairewj** [comment]
I've edited your post to remove the link - thanks for highlighting it. Please contact us in the future if you find MIMIC-CXR shared outside of PhysioNet.

**Comment by Nithin1729S** [comment]
> Hi, is there anyother way I can access the complete dataset without actually downloading and I don't have cloud access to store it on cloud of that big storage requirement.
> 
> I'm actually participating in [BioNLP shared task](https://stanford-aimi.github.io/RRG24/) so it requires MIMIC-CXR dataset as part of it. Can I get some help on this

Hello....Did you find any solution for this ?

**Comment by harshavardhanpinnapureddy** [comment]
@Nithin1729S you require the disk space on device I think there is no other way for MIMIC-CXR, although you can access MIMIC-III, IV on Google cloud for rent directly.

**Comment by Nithin1729S** [comment]
> @Nithin1729S you require the disk space on device I think there is no other way for MIMIC-CXR, although you can access MIMIC-III, IV on Google cloud for rent directly.

Ohh okay and did you complete the shared task..I needed some help with it.

**Comment by harshavardhanpinnapureddy** [comment]
Nope we failed to get good results although the entire pipeline was built. You can email me if you want to discuss

**Comment by Nithin1729S** [comment]
> @Nithin1729S Nope we failed to get good results although the entire pipeline was built. You can email me if you want to discuss

Oh Thanks a lot .I have emailed my queries to you

**Comment by Yuanyuan-Wu** [comment]
> I appreciate the positive sentiment! :)
> 
> We kept the full resolution as it could be useful for a number of analyses. You lose a lot of resolution going from 3k to 512. Of course, having a resized version would be beneficial in a number of ways. Not sure any of us will have the time to do it in the near future, however.

May I have a question, is each image size is same or varied per scan? is the image pixel value 3000 * 3000?
