### ISSUE TITLE
Information about the model for missing specimen labels

### ISSUE THREAD

**Issue by hhau** [MIT-LCP/mimic-code#1033]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, thanks for all the hard work y'all do on MIMIC! 

Is there a paper/blog post/more information about the [logistic regression model](https://github.com/MIT-LCP/mimic-code/blob/main/concepts/firstday/blood_gas_first_day_arterial.sql#L72-L87) that is used to label blood samples as venous or arterial when the label is missing? The only mention of this model I can find is in #488. If not, I would be very grateful if anyone can answer the following:

- What data were used to compute the coefficients (The non-missing MIMIC data? Something external?)
- What method of imputation was employed? It looks like some kind of regression imputation?
- What was the validation procedure / performance of the fitted model?

Thanks again!

**Comment by briangow** [comment]
Unfortunately, there isn't any documentation for this.  This model was implemented by a former lab member quite a while ago.
