### ISSUE TITLE
to psql

### ISSUE THREAD

**Issue by zouzhiye** [MIT-LCP/mimic-code#1042]
DATETIME_DIFF(ad.admittime, DATETIME(pa.anchor_year, 1, 1, 0, 0, 0), YEAR) + pa.anchor_age AS age
how can I change this to psql

### Labels
* Please add one or more of these labels to your issue after creating it: 
  * mimic-iv
  * mimic-iii
  * mimic-cxr
* If your issue applies to more than one of these please feel free to select multiple labels as appropriate.

**Comment by briangow** [comment]
If you are asking how to enter commands on the psql command line please see the Entering SQL Commands section here: https://www.postghtmlresql.org/docs/13/app-psql .
