### ISSUE TITLE
In the pivoted_bg table, where can I find the `physionet-data.mimiciii_derived` table or is this a bug  ? 

### ISSUE THREAD

**Issue by chendazhang** [MIT-LCP/mimic-code#1043]
, stg2 as
(
select bg.*
  , row_number() OVER (partition by bg.hadm_id, bg.charttime order by s1.charttime DESC) as lastrowspo2
  , s1.spo2
from `physionet-data.mimiciii_derived` bg                                          --this table........... 
left join stg_spo2 s1

thank you.

**Comment by tompollard** [comment]
It looks like you are referring to the following chunk of code in  https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iii/concepts/pivot/pivoted_bg.sql: 

https://github.com/MIT-LCP/mimic-code/blob/327569039c257a5c8b0e265f3f4658116f088b06/mimic-iii/concepts/pivot/pivoted_bg.sql#L201-L213

You are right that the line below is missing a table name (a bug):

```sql
from `physionet-data.mimiciii_derived` bg
```

I've not explored, but perhaps it is referring to the table that is created in the earlier step (i.e. the chunk prior to line 148)?: 

https://github.com/MIT-LCP/mimic-code/blob/327569039c257a5c8b0e265f3f4658116f088b06/mimic-iii/concepts/pivot/pivoted_bg.sql#L148-L151)

**Comment by chendazhang** [comment]
thank you for your reply ,as you said ,I also found the table later .
