### ISSUE TITLE
Questions about the calculation results of sepsis3.sql

### ISSUE THREAD

**Issue by jixiaojing** [MIT-LCP/mimic-code#1046]
### Description
thank you for your great job with mimic-iv! i build mimic-iv database by quoting the code from the site,and want to analyze information about  sepsis patients,then encountered a problem with the defination of sepsis3.By executing sepsis3.sql, I calculated 27139 patients, and my colleague’s calculation result was 11263.
the calculating Statement is : SELECT count(distinct subject_id)  FROM "physionet-data.mimic_derived.sepsis3"  .
here 's the question ,which number is closer to the result of your calculations while coding sepsis3.sql,thank you and it's really important to me !

### Labels
  * mimic-iv

**Comment by briangow** [comment]
Please provide more detail (w/ relevant code) for each of the calculations you refer to.  If you want the number of unique patients you should use `DISTINCT`.

**Comment by jixiaojing** [comment]
Thank you for your reply ,i used almost all the sql text from the mimic-code, and the The file path is  mimic-code/mimic-iv/concepts/,i used the keyword distinct，Unfortunately the results are too far apart, so here i am .

**Comment by SichengH** [comment]
I assume you and your colleague are running the query locally, could you please providede the database version? Thanks!
