### ISSUE TITLE
Neonatal ICU sample within MIMICIII or IV?

### ISSUE THREAD

**Issue by ujsanghvi** [MIT-LCP/mimic-code#1049]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, I have submitted my credentialing application. However, I do not know if the MIMIC datasets have the population I am seeking. Does anyone know sample size/characteristics of the extremely premature infant population (neonatal ICU) accessible within the database?

**Comment by briangow** [comment]
There are at least 7870 neonates in MIMIC III : https://www.nature.com/articles/sdata201635 .
