### ISSUE TITLE
The naming rules of 'Label' in the table of d_items

### ISSUE THREAD

**Issue by lcy-0408** [MIT-LCP/mimic-code#1050]
I am working on a review about several medical databases. So I'm trying to figure out the naming rules of 'label' in the table of d_items like 'Heat Sounds'. Whether these label are named by the hospital and not by a standard, and i can't find them in all of Medical standard library (SNOMED, LOINC, ULMS....)like 'Heat Sounds'
 I desperately want someone to answer my questions! Thanks!

**Comment by tompollard** [comment]
The concept IDs (`itemid`) do not follow a standard library as far as I am aware, so in many cases they not map directly to SNOMED; LOINC etc codes (though there are ongoing efforts to create a set of mappings). Looking at the concept that you mention in your example:

```
SELECT *
FROM `physionet-data.mimiciii_clinical.d_items`
WHERE LOWER(label) LIKE "%heat sounds%"
```

Returns:
```
Row, ROW_ID, ITEMID, LABEL, ABBREVIATION, DBSOURCE, LINKSTO, CATEGORY, UNITNAME, PARAM_TYPE, CONCEPTID
1,12849,223933,Heat Sounds,Heat Sounds,metavision,chartevents,Cardiovascular (Pulses),null,Text,null
```

It's likely a typographical error that somehow made it into the system! You'll see that there are no observations in the `chartevents` table for this concept:

```
SELECT COUNT(*)
FROM `physionet-data.mimiciii_clinical.chartevents`
WHERE itemid = 223933;

-- Returns 0 observations
```

Perhaps someone intended to add "Heart sounds" instead:

```
SELECT *
FROM `physionet-data.mimiciii_clinical.d_items`
WHERE LOWER(label) LIKE "%heart sounds%"
```

returns:

```
Row, ROW_ID, ITEMID, LABEL, ABBREVIATION, DBSOURCE, LINKSTO, CATEGORY, UNITNAME, PARAM_TYPE, CONCEPTID
1,214,213,Heart Sounds,null,carevue,chartevents,null,null,null,null
2,13322,224389,Heart Sounds,Heart Sounds,metavision,chartevents,Cardiovascular,null,Text,null
```

Some examples of "heart sound" observations are shown below:

```
SELECT DISTINCT(value)
FROM `physionet-data.mimiciii_clinical.chartevents`
WHERE itemid = 224389;

-- returns "Diastolic murmur"; "Systolic murmur", ...
```

**Comment by lcy-0408** [comment]
Thank you very much for your reply ! I see what you mean.thanks again!
