### ISSUE TITLE
IRB approval (MIMIC-IV)

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#1051]
Hello,
I am required to submit IRB approval with my thesis.
I found an old issue #267, but I'm not sure if this is still the right contact to ask for it and what is the address.

Thank you,
Ariel

**Comment by tompollard** [comment]
Hi @arielhasidim, does the following statement meet your needs?:

> The project was approved by the Institutional Review Boards of Beth Israel Deaconess Medical Center, Boston, MA and the Massachusetts Institute of Technology, Cambridge, MA (#2001P001699). 

If you need additional detail, please use the "Corresponding author" information on the relevant PhysioNet project (e.g. in this case, see: https://doi.org/10.13026/s6n6-xd98)

**Comment by arielhasidim** [comment]
Thank you @tompollard, this is excellent.
