### ISSUE TITLE
Cannot find HDL lab test results - MIMIC-iii

### ISSUE THREAD

**Issue by phantom153** [MIT-LCP/mimic-code#1053]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

I have pulled from Mimic lab test results.
However, could not find any HDL results (ITEMID=50904).
Did you encounter such an issue?

Thanks
 #834

**Comment by pszolovits** [comment]
I’m assuming you were looking in MIMIC-III.

mysql> select count(*) from labevents where itemid=50904;
+----------+
| count(*) |
+----------+
|    18260 |
+----------+
1 row in set (0.01 sec)

In MIMIC-IV:
mysql> select count(*) from labevents where itemid=50904;
+----------+
| count(*) |
+----------+
|   254290 |
+----------+
1 row in set (0.04 sec)

**Comment by SichengH** [comment]
Issue solved.
