### ISSUE TITLE
Estimating costs or charges per hospitalisation

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#1054]
Hello,
I intend to estimate hospitalisation costs or charge. I can see that CPT is not relevant for hospitalisation, its more about DRGs and procedural-ICDs, while hospitalisation had 1/2 main DRGs and ICDs is richer per hospitalisation (as stated at the docs, and by my sampling).

**Is there any proper way to address this issue?
Maybe a published article that already done that with MIMIC?**

Best Regards,
Ariel

**Comment by alistairewj** [comment]
I can't say I have an exact answer, but that act of congress a few years ago forced more price transparency from all US hospitals. You can `wget` the costs associated with DRG codes here: https://www.bidmc.org/-/media/rich-text-images/beth-israel-org/patient-and-visitor-information/patient-information/beth_israel_deaconess_medical_center_standard_charges_02242021.xml

Those apply for 2020 (I think).. but maybe it's a good start?

**Comment by arielhasidim** [comment]
> I can't say I have an exact answer, but that act of congress a few years ago forced more price transparency from all US hospitals. You can `wget` the costs associated with DRG codes here: https://www.bidmc.org/-/media/rich-text-images/beth-israel-org/patient-and-visitor-information/patient-information/beth_israel_deaconess_medical_center_standard_charges_02242021.xml
> 
> Those apply for 2020 (I think).. but maybe it's a good start?

It's a very good start compare to what I had until now,
Thank you!

When I checked the data I noticed that every hospitalisation had like 2 DRG's that has the same meaning, but it had much more reacher procedural-ICD codes, 

Maybe there is a way to estimate costs by ICD's (procedural)?
or maybe my approach is wrong and the billing is not thorough and include every procedure, just a fixed price according to the main DRG?

ICDs:
| hospitalization_id | icd_version | icd_code | long_title                                                                                     | 
|--------------------|-------------|----------|------------------------------------------------------------------------------------------------| 
| 20107452           | 10          | 021209W  | Bypass Coronary Artery, Three Arteries from Aorta with Autologous Venous Tissue, Open Approach | 
| 20107452           | 10          | B211YZZ  | Fluoroscopy of Multiple Coronary Arteries using Other Contrast                                 | 
| 20107452           | 10          | 02100Z9  | Bypass Coronary Artery, One Artery from Left Internal Mammary, Open Approach                   | 
| 20107452           | 10          | 06BQ4ZZ  | Excision of Left Saphenous Vein, Percutaneous Endoscopic Approach                              | 
| 20107452           | 10          | 5A1221Z  | Performance of Cardiac Output, Continuous                                                      | 


compare to:
| hospitalization_id | drg_type | drg_code | description                            | 
|--------------------|----------|----------|----------------------------------------| 
| 20107452           | HCFA     | 234      | CORONARY BYPASS W CARDIAC CATH W/O MCC | 
| 20107452           | APR      | 166      | CORONARY BYPASS W/O AMI OR COMPLEX PDX |

**Comment by alistairewj** [comment]
Yes I'd only pick one type of DRG. They just report the two equivalent versions. One of them has more information regarding severity/mortality for more precise estimate of patient severity. From the few health economics papers I've seen most use DRG as a proxy for total cost and don't go further than that, though including the ICDs will give you a more complete picture. I don't know exactly how the total cost is calculated but ICDs must be used as if they didn't affect the total bill they wouldn't bother to create them!

**Comment by arielhasidim** [comment]
Thank you very much John!
