### ISSUE TITLE
psql: error: FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by CalendulaED** [MIT-LCP/mimic-code#1060]
The version that I am currently using is Postgres 13.3

I believe I use the default way of implementing the make file:
`make create-user mimic datadir="/home/edmundwuyuxuan/physionet.org/files/mimiciii/1.4"`
I believe in this case, the user is `postgres` and the password is also `postgres`

I have also edit the pg_hba.conf file from peer to md5

However, when it asks me for the password, and when I enter the `postgres`, it shows `psql: error: FATAL:  password authentication failed for user "postgres"`
Isn't that by the default make file, the password is `postgres`?

![image](https://user-images.githubusercontent.com/68514251/121106701-1c64ef00-c839-11eb-98e4-50397c8f85fa.png)

**Comment by lmz123321** [comment]
Hi, I met the same problem, how did you solve it ?

**Comment by lmz123321** [comment]
For those meet the same problem, I solve it by reset the password to user 'postgres'.
Instructions are here: https://stackoverflow.com/a/68174538
