### ISSUE TITLE
MIMIC-IV ED Patient Demographics

### ISSUE THREAD

**Issue by divyashan** [MIT-LCP/mimic-code#1062]
### Prerequisites

    * [X] Checked the online documentation: https://mimic.mit.edu/
    * [X]  Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I'm interested in finding the `ethnicity` variable for patients in the ED data and I'm not sure I'm doing this correctly. 

I merged the admissions table (from MIMIC-IV) with the diagnoses table (from MIMIC-IV ED) on `subject_id`. I did this based on this line in the [documentation](https://physionet.org/content/mimic-iv-ed/1.0/): "Note that subject_id can be linked with MIMIC-IV to obtain patient demographics". I find that ~half the patients in the diagnoses table exist in the admissions table.

It seems natural that since not all patients in the ED are hospitalized, their demographic information may not be in the admissions table. Is there anywhere else I could find patient demographic info for patients who were not hospitalized?

**Comment by alistairewj** [comment]
Hrm, didn't anticipate that. There's no other source of it. We'll probably need to add it to the ED database somewhere.

**Comment by divyashan** [comment]
Do you have a sense for when these variables would be available? Totally okay if not, was just curious.

**Comment by divyashan** [comment]
(Closing this issue since the ED admission demographics are included in the edstays table in the new release of MIMIC-IV. Thanks @alistairewj!)
