### ISSUE TITLE
charttime before admittime

### ISSUE THREAD

**Issue by amirdol** [MIT-LCP/mimic-code#1066]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I'm using the admissions and lab events tables, joining them by the hadm_id field
When comparing charttime and admittime, I'm getting a lot of lab events that happen way before the admission. Is this expected? I was under the impression that all lab events with a specific hadm_id will happen after the admittime

**Comment by briangow** [comment]
Could you provide an example of the issue along with your code?  There are are small number of subjects who may have issues with their admittime due to clerical errors: https://github.com/MIT-LCP/mimic-code/issues/209 .

**Comment by briangow** [comment]
You could also check #245 to see if it helps explain what you are observing.

**Comment by EdwardMoseley** [comment]
This is a problem I've bumped into several times before, but with past versions (MIMIC-III and before) of the database.

Things to keep in mind are:
1. Checking both `ICUSTAYS.INTIME` and `ADMISSIONS.ADMITTIME` to ensure you're using the right admission data
2. An **ICU admission** can be emergent, with the patient going *immediately* to the ICU. This may lead to an `ICUSTAYS.INTIME` that is identical to, or appears to precede, an `ADMISSIONS.ADMITTIME`.
3. There can be a **hospital admission** first, and then *later* be admitted to the ICU.
4. It's important to ensure that we're dealing with the right admission (hospital or ICU) time when we are calculating differences between timepoints

Sometimes, though, I can't explain the problem with INTIME vs. ADMITTIME, so I attribute it to data batching and lag. In this case, I will remove any admission observations that are impossible (for example, a `NOTEEVENTS.CHARTTIME` observation which precedes an `ADMISSIONS.ADMITTIME` for a single `HADM_ID`.
