### ISSUE TITLE
Years of eMAR availability in MIMIC-IV

### ISSUE THREAD

**Issue by ctryan** [MIT-LCP/mimic-code#1069]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
For the newly added eMAR table in MIMIC-IV, it is noted in the documentation that the eMAR system was recently implemented for use in the hospital. Does this mean that only a subset of patients in the MIMIC-IV dataset will have this data availability?
Do you know the exact year(s) when eMAR use began?

**Comment by alistairewj** [comment]
Correct. Filtering to patients admitted 2014 - 2016 / 2017-2019 should mostly work, or filter to patients with at least 1 eMAR observation.

**Comment by ctryan** [comment]
Great, thank you very much for your prompt response. I will look back to MIMIC-III literature/code to see how the pharmacy/prescription tables were handled to produce medication data prior to eMAR implementation. 

Christopher T. Ryan, MD
Baylor College of Medicine
