### ISSUE TITLE
No d_micro table in MIMIC-IV project page?

### ISSUE THREAD

**Issue by wyyyzw** [MIT-LCP/mimic-code#1070]
I can't find the d_micro table in MIMIC-IV project page, but i can find  the d_micro table in the tables introduction on the official website.

**Comment by alistairewj** [comment]
Looks like the website is out of date as *d_micro* no longer exists. We had it in an earlier version of MIMIC-IV, but it's a pointless table as all the information is already in *microbiologyevents*. We also decided it was better to keep backward compatibility with MIMIC-III here. We'll try to update the documentation shortly (or feel free to make a PR removing mentions of *d_micro*).

**Comment by briangow** [comment]
I've updated a working branch already to remove mention of _d_micro_.  It will be released along with the restructured website.
