### ISSUE TITLE
Electrolyte Lab Values: Incorrect "abnormal" flag and reference range values 

### ISSUE THREAD

**Issue by MousaGhannam** [MIT-LCP/mimic-code#1073]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi Mimic Team! 
I'm just reaching out about lab values pertaining to electrolyte lab draws in the database. It seems there are many (on the order of thousands) lab draws that are incorrectly flagged as "abnormal" when they should not be, and vice versa. My main question is can the actual `valuenum` of these labs still be trusted, regardless if it's flagged or not? 

I am mainly determining the normal limits of the reference ranges by comparing the amount of "flagged" lab values at each lab value increment. If the same `valuenum` has both flagged and non-flagged values (as often is the case), I just choose if it's flagged based on which has has the highest amount at that increment (e.g for potassium, if the `valuenum` is 3.8 and there are 200 lab values flagged and 500 `N/A`, I would assume 3.8 is supposed within the normal range). I am not really sure how sound this strategy is, and I was wondering if there are a formal list of reference ranges for common lab value draws. 

Thank you for your guidance, and again for this wonderful resource. :) 
Mousa

**Comment by alistairewj** [comment]
> ### Description
> Hi Mimic Team! I'm just reaching out about lab values pertaining to electrolyte lab draws in the database. It seems there are many (on the order of thousands) lab draws that are incorrectly flagged as "abnormal" when they should not be, and vice versa. My main question is can the actual `valuenum` of these labs still be trusted, regardless if it's flagged or not?

Can you be more specific? And is this in MIMIC-III or MIMIC-IV? MIMIC-IV has reference range columns... so maybe this is MIMIC-III.

> I am mainly determining the normal limits of the reference ranges by comparing the amount of "flagged" lab values at each lab value increment. If the same `valuenum` has both flagged and non-flagged values (as often is the case), I just choose if it's flagged based on which has has the highest amount at that increment (e.g for potassium, if the `valuenum` is 3.8 and there are 200 lab values flagged and 500 `N/A`, I would assume 3.8 is supposed within the normal range). I am not really sure how sound this strategy is, and I was wondering if there are a formal list of reference ranges for common lab value draws.
> 
> Thank you for your guidance, and again for this wonderful resource. :) Mousa

Which labs will be `abnormal` will vary as reference ranges will change over the years. So you may find an value of 4.0 for one patient, and a normal value of 4.0 for another, and it's because the reference range for the laboratory value has changed. This is actually why the reference ranges in MIMIC-IV are available for every individual lab measurement, rather than in *d_labitems*.
