### ISSUE TITLE
Sepsis3 patients in MIMIC-IV

### ISSUE THREAD

**Issue by SichengH** [MIT-LCP/mimic-code#1074]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    [X]  Checked the online documentation: https://mimic.mit.edu/
    [X]  Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Sepsis3 cohort in mimic-v0.4 has 19k+ unique stays and in the current version has 35k+ unique stays. Which is almost half of the patients. Probably need to check the derived script or the database itself. 

Description of the issue, including:
* what you have tried

From previous publications. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5851804/. Sepsis3 patients have a mortality of 14.5%, but in the sepsis3 cohort, 30day mortality is 11.5%. 

* references to similar issues
#1046, very likely the same issue here. 

* queries demonstrating your question (if applicable)

**Comment by tompollard** [comment]
@SichengH I'm unclear what question is being asked here. Please could you give a more descriptive title and clearly outline the issue that needs to be resolved?

**Comment by SichengH** [comment]
MIMIC-IV-v0.4 is an intermediate version of the database. All research should be run with the most recent version of MIMIC-IV.
