### ISSUE TITLE
Question about (1) building sql db for MIMIC-ED (2) body temperature in TRIAGE

### ISSUE THREAD

**Issue by juhha1** [MIT-LCP/mimic-code#1079]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    [ x ] Checked the online documentation: https://mimic.mit.edu/
    [ x ] Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

(1) The data structure from raw csv files and it from table description on the official website (https://mimic.mit.edu/iv/datasets/ed/) is different. 
I believe there are data processing from raw csv file, but I couldn't find any sql code to construct the database for ED tables on github website (https://github.com/MIT-LCP/mimic-code).
Is this still on the process for publishing or should researchers make the data processing themselves?

(2) On the Triage table from MIMIC-ED, I believe there are 2 units used to collect body temperature.
I think most of them are in F and only small number of records are in C (But the table description from the official website says it is in C).
And there is no indication which unit is used.
Can we extract which unit is used for body temperature for each record? Or is it possible to convert the number with a same unit?
Here is the result that I have.
Most of the records for body temperature (BT) are between 86-122 (in C, it is between 30-50).
![image](https://user-images.githubusercontent.com/63571852/123203105-cb1f5580-d4f0-11eb-81e5-4ec5cd9f5b40.png)
Thanks.

**Comment by briangow** [comment]
Regarding (1), we are in the process of updating the MIMIC website to contain updated information on MIMIC-ED.  We will also be releasing code relevant to MIMIC-ED to the mimic-code repository on Github. 

Regarding (2), I don't know the answer.  However, we appreciate you pointing this out and we'll look into it further.

**Comment by alistairewj** [comment]
The documentation is rebuilt so let us know if there are any other inconsistencies.

> (2) On the Triage table from MIMIC-ED, I believe there are 2 units used to collect body temperature.
I think most of them are in F and only small number of records are in C (But the table description from the official website says it is in C).
And there is no indication which unit is used.
Can we extract which unit is used for body temperature for each record? Or is it possible to convert the number with a same unit?

This is the data as it was stored at the bedside. It was originally text. As a result, there are inconsistencies, so best bet is to clean the data. My typical approach is to decide on a unit of measure (temperature will typically be documented in F in BIDMC so it's a reasonable choice), then convert reasonable values in the other range (so 35-42 or so).
