### ISSUE TITLE
Question about the medical system MIMIC III data are from and question about CHARTTIME

### ISSUE THREAD

**Issue by kara4141** [MIT-LCP/mimic-code#1082]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
* Read all the papers and documents
* references to similar issues: NONE
* 
I am wondering which system Beth Israel Deaconess Medical Center used to record their 50000 ICU stay? Is it Epic?

Also, in NOTESEVENTS.csv file, how I should interrupt CHARTTIME and STORETIME, which one comes first?

Thanks!

**Comment by pszolovits** [comment]
BIDMC mostly used their home-developed OMR system for recording hospital-wide data and commercial systems to record ICU-specific data: CareVue from Philips until ~2008, and then MetaVision from iMDsoft.

In MIMIC-III, storetime usually comes after chart time, but I'm not sure what the meaning of the difference is.
```
mysql> select sign(storetime - charttime), count(*) c from noteevents group by sign(storetime - charttime);
+-----------------------------+---------+
| sign(storetime - charttime) | c       |
+-----------------------------+---------+
|                        NULL |  838845 |
|                           1 | 1231609 |
|                          -1 |    1916 |
|                           0 |   10810 |
+-----------------------------+---------+
```
And sometimes one or the other is NULL:
```
mysql> select storetime is null, charttime is null, count(*) from noteevents group by storetime is null, charttime is null;
+-------------------+-------------------+----------+
| storetime is null | charttime is null | count(*) |
+-------------------+-------------------+----------+
|                 1 |                 1 |   314497 |
|                 0 |                 0 |  1244335 |
|                 0 |                 1 |     2069 |
|                 1 |                 0 |   522279 |
+-------------------+-------------------+----------+
```

**Comment by briangow** [comment]
The difference between CHARTTIME and STORETIME has also been discussed here:
#373 
#375

**Comment by kara4141** [comment]
> BIDMC mostly used their home-developed OMR system for recording hospital-wide data and commercial systems to record ICU-specific data: CareVue from Philips until ~2008, and then MetaVision from iMDsoft.
> 
> In MIMIC-III, storetime usually comes after chart time, but I'm not sure what the meaning of the difference is.
> 
> ```
> mysql> select sign(storetime - charttime), count(*) c from noteevents group by sign(storetime - charttime);
> +-----------------------------+---------+
> | sign(storetime - charttime) | c       |
> +-----------------------------+---------+
> |                        NULL |  838845 |
> |                           1 | 1231609 |
> |                          -1 |    1916 |
> |                           0 |   10810 |
> +-----------------------------+---------+
> ```
> 
> And sometimes one or the other is NULL:
> 
> ```
> mysql> select storetime is null, charttime is null, count(*) from noteevents group by storetime is null, charttime is null;
> +-------------------+-------------------+----------+
> | storetime is null | charttime is null | count(*) |
> +-------------------+-------------------+----------+
> |                 1 |                 1 |   314497 |
> |                 0 |                 0 |  1244335 |
> |                 0 |                 1 |     2069 |
> |                 1 |                 0 |   522279 |
> +-------------------+-------------------+----------+
> ```

Thanks for the detailed reply!
