### ISSUE TITLE
Question about  DATETIME function for scripts

### ISSUE THREAD

**Issue by wyyyzw** [MIT-LCP/mimic-code#1096]
Thanks for the scripts provided on GitHub. But the Postgresql 10 cannot read DATETIME series functions. How to solve this problem quickly？

**Comment by briangow** [comment]
Please be more specific.  Please point to information about Postgres 10 not being able to read DATETIME series functions.  Please indicate exactly which script (and the line number in the script) that this is causing a problem with.

**Comment by wyyyzw** [comment]
> Please be more specific. Please point to information about Postgres 10 not being able to read DATETIME series functions. Please indicate exactly which script (and the line number in the script) that this is causing a problem with.
![QQ图片20210722222344](https://user-images.githubusercontent.com/45260270/126655813-9825ad0f-054e-40d8-9a8f-c01ce982fc17.png)

**Comment by wyyyzw** [comment]
> Please be more specific. Please point to information about Postgres 10 not being able to read DATETIME series functions. Please indicate exactly which script (and the line number in the script) that this is causing a problem with.

![image](https://user-images.githubusercontent.com/45260270/126657596-04cbe3e7-75d4-44e7-b424-5eac1c490829.png)

**Comment by briangow** [comment]
I don't mean to be difficult but could you please provide the following: 

1. A link or more details around your statement that "Postgresql 10 cannot read DATETIME series functions"
2. The filename (and full path to the file in the repo) along with the associated line number for each line of code that is causing problems for you
3. The command you are using to run the code and all associated error messages

**Comment by wyyyzw** [comment]
> I don't mean to be difficult but could you please provide the following:
> 
> 1. A link or more details around your statement that "Postgresql 10 cannot read DATETIME series functions"
> 2. The filename (and full path to the file in the repo) along with the associated line number for each line of code that is causing problems for you
> 3. The command you are using to run the code and all associated error messages

icustay_detail codes provided in GitHub are as follows:
SELECT ie.subject_id, ie.hadm_id, ie.stay_id
-- patient level factors
, pat.gender, pat.dod

-- hospital level factors
, adm.admittime, adm.dischtime
, DATETIME_DIFF(adm.dischtime, adm.admittime, DAY) as los_hospital
, DATETIME_DIFF(adm.admittime, DATETIME(pat.anchor_year, 1, 1, 0, 0, 0), YEAR) + pat.anchor_age as admission_age
, adm.ethnicity
, adm.hospital_expire_flag
, DENSE_RANK() OVER (PARTITION BY adm.subject_id ORDER BY adm.admittime) AS hospstay_seq
, CASE
    WHEN DENSE_RANK() OVER (PARTITION BY adm.subject_id ORDER BY adm.admittime) = 1 THEN True
    ELSE False END AS first_hosp_stay

-- icu level factors
, ie.intime as icu_intime, ie.outtime as icu_outtime
, ROUND(DATETIME_DIFF(ie.outtime, ie.intime, HOUR)/24.0, 2) as los_icu
, DENSE_RANK() OVER (PARTITION BY ie.hadm_id ORDER BY ie.intime) AS icustay_seq

-- first ICU stay *for the current hospitalization*
, CASE
    WHEN DENSE_RANK() OVER (PARTITION BY ie.hadm_id ORDER BY ie.intime) = 1 THEN True
    ELSE False END AS first_icu_stay

FROM `physionet-data.mimic_icu.icustays` ie
INNER JOIN `physionet-data.mimic_core.admissions` adm
    ON ie.hadm_id = adm.hadm_id
INNER JOIN `physionet-data.mimic_core.patients` pat
    ON ie.subject_id = pat.subject_id;

DATETIME_DIFF() codes error.
![image](https://user-images.githubusercontent.com/45260270/126727388-ba510cdf-7093-4910-b6b2-60ce29dc6fef.png)
![image](https://user-images.githubusercontent.com/45260270/126727406-b6eeda92-a52e-4deb-b956-3b252c6d465a.png)

**Comment by wyyyzw** [comment]
> I don't mean to be difficult but could you please provide the following:
> 
> 1. A link or more details around your statement that "Postgresql 10 cannot read DATETIME series functions"
> 2. The filename (and full path to the file in the repo) along with the associated line number for each line of code that is causing problems for you
> 3. The command you are using to run the code and all associated error messages

![image](https://user-images.githubusercontent.com/45260270/126727751-dd5dd3dd-7b36-41c5-a15a-2e9cb074f931.png)
Only the DATETIME series codes shown in the above figure can be searched in postgresql 10.

**Comment by briangow** [comment]
It seems like the code you are running is in BigQuery SQL not Postgres SQL.  You would need to translate it to run it in Postgres.  If you require more assistance with this issue please provide the path within the Github repo to the code you are using.  Also please post the text for the error message not an image - since I can't read the characters in the error image it is not informative.

**Comment by sunrimii** [comment]
你參考的應該是BigQuery的代碼，而不是PostgreSQL的，要先把所有函數都轉換過去；或者用像psycopg2套件，把查詢的值取出來後，預設就是`datatime`格式，就可以直接相減了。
