### ISSUE TITLE
How to make concepts for MIMIC-IV in WIN10 postgres?

### ISSUE THREAD

**Issue by thodison** [MIT-LCP/mimic-code#1099]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
How to make concepts for MIMIC-IV in WIN10 postgres?

Here is the code for MIMIC-IV:
https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/concepts
I have tried in WIN10, I run the make_concepts.sh in WSL2, but it did not work at all. 

Any help?

Description of the issue, including:
* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Please try the newest merged branch! https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/concepts/postgres
