### ISSUE TITLE
Platelets, RBC

### ISSUE THREAD

**Issue by SvenVanPoucke** [MIT-LCP/mimic-code#11]
Looking for transfusion with platelets and or RBC. Which approach is best? ICD code or IO ITEMID?
Cheers
Sven

**Comment by alistairewj** [comment]
Almost certainly the appropriate choice is to use the IOEVENTS table. This will tell you when the blood was given (to the hour) and the amount. You can search the D_ITEMS table for the `ITEMID` associated with transfusions, such as "FFP", "RBC", etc. If you come up with a list of these `ITEMID` values we would welcome it as a contribution to the documentation.

**Comment by vjm261** [comment]
The most common by total volume (in my analyses) ITEMID codes for platelets or RBC are:
String description: ITEMID
Packed Red Blood Cells: 225168
Packed RBC's: 30001 or just 1 in the IOEVENTS table (see my currently open issue #9 )
Platelets: 225170
OR Packed RBC Intake: 226368
Platelets: 30006 or just 6
OR Platelet Intake: 226369
OR Packed RBC's: 30104 or just 104

This is far from a complete list but appear to be the most common from my subgroup.

**Comment by SvenVanPoucke** [comment]
Thanks for the answer!
Sven

Op wo 21 okt. 2015 17:52 schreef vjm261 <notifications@github.com>:
