### ISSUE TITLE
MIMIC-IV Database Demo 

### ISSUE THREAD

**Issue by hannesUlrich** [MIT-LCP/mimic-code#1100]
First of all: thanks for the great project ! 

Is there a plan to release a database demo for the MIMIC-IV as well? There is already one for the [MIMIC-III](https://physionet.org/content/mimiciii-demo/1.4/).

Thanks !

**Comment by tompollard** [comment]
Thanks @hannesUlrich. Yes, the MIMIC-IV demo will be released shortly!

**Comment by masilenccee** [comment]
uh, where is the database demo for the MIMIC-iii ? Questions from a rookie,3Q

**Comment by sunrimii** [comment]
> First of all: thanks for the great project !
> 
> Is there a plan to release a database demo for the MIMIC-IV as well? There is already one for the [MIMIC-III](https://physionet.org/content/mimiciii-demo/1.4/).
> 
> Thanks !

@masilenccee It's those csv files in the link, you can build your own database from the files.

**Comment by tompollard** [comment]
For MIMIC-III the demo should be the first hit if you Google "MIMIC-III demo": https://www.google.com/search?q=mimic-iii+demo&oq=mimic-iii+demo&aqs=chrome..69i57j0i22i30l2j69i60l2.3709j0j7&sourceid=chrome&ie=UTF-8

**Comment by hannesUlrich** [comment]
New year 🎉, new try: were you (@tompollard) able to take a look at the demo set?

**Comment by beanformer** [comment]
@hannesUlrich : Maybe you can live with hte OMOP version: https://physionet.org/content/mimic-iv-demo-omop/0.9/

**Comment by hannesUlrich** [comment]
@beanformer I know the project and have already looked into it. The problem is that our [project](https://github.com/itcr-uni-luebeck/mimic4fhir) uses the schemas of the MIMIC-IV database and  data in OMOP format needs a lot of refactoring.  So, a demo set from MIMIC IV would be extremely desirable to provide the test data to the MII.

**Comment by tompollard** [comment]
@hannesUlrich I'm sorry, I know this has taken longer than it should have done. It is high on our to do list.

**Comment by hannesUlrich** [comment]
Thanks for the update @tompollard !

**Comment by tompollard** [comment]
The MIMIC-IV demo is available at: https://www.physionet.org/content/mimic-iv-demo/

**Comment by hannesUlrich** [comment]
Excellent! Thanks for making the demo possible @tompollard and @alistairewj !

**Comment by alistairewj** [comment]
No worries! Just note it's v1.0 right now, but hoping to update it to v2.0 very shortly.
