### ISSUE TITLE
How to map mimic cxr and mimic iv based on study_id?

### ISSUE THREAD

**Issue by qingerVT** [MIT-LCP/mimic-code#1101]
It's clear that we are able to map mimic cxr and mimic iv based on `patient_id`. Any way we can go a bit further to use`study_id`? For example, how to align `study_id` and `icustay_id,` `charttime`?

**Comment by briangow** [comment]
@ qingerVT I'm converting this to a discussion as we now prefer that issues are only used for problems with the code.
