### ISSUE TITLE
error loading mimic-iv-1.0 data with mimic-iv/buildmimic/postgres/load_gz.sql v1.2.1 code

### ISSUE THREAD

**Issue by JackieMium** [MIT-LCP/mimic-code#1112]
I am using mimic-iv-1.0 data to build mimic-iv postgres database locally. All data `xx.csv.gz` files passed `SHA256SUMS` check, mimic-iv code was downloaded from [MIT-LCP/mimic-iv/releases/tag/v1.2.1](https://github.com/MIT-LCP/mimic-iv/releases/tag/v1.2.1) as I am working with my colleagues so we decided to stick with release code rather than an arbitrary or latest commit. But the following error stopped the building process:

```
COPY 523740
COPY 382278
COPY 2189535
COPY 89200
COPY 5280351
COPY 109775
COPY 85257
COPY 1630
COPY 769622
COPY 55947921
COPY 27464367
psql:load_gz.sql:58: ERROR:  extra data after last expected column
CONTEXT:  COPY hcpcsevents, line 2: "12350009,25467647,2155-02-10,99219,1,Hospital observation services"
```

Is it a bug in the release code? Do I have to use latest commit instead of latest release? Thanks!

**Comment by briangow** [comment]
@JackieMium , in v1.0 a new column `chartdate` was added to the `hcpcsevents` table. The official repo for MIMIC-IV code has been moved under the mimic-code repository ( https://github.com/MIT-LCP/mimic-code ). The [create.sql](https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iv/buildmimic/postgres/create.sql) file there includes that new column but the old create.sql version did not. This should be the source of your error. 

Sorry for the confusion here, we'll disable public access to the old MIT-LCP/mimic-iv repo so this kind of issue doesn't happen to others.

**Comment by JackieMium** [comment]
> The official repo for MIMIC-IV code has been moved under the mimic-code repository ( https://github.com/MIT-LCP/mimic-code ). The [create.sql](https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iv/buildmimic/postgres/create.sql) file there includes that new column but the old create.sql version did not. This should be the source of your error.

Thanks for your help, I didn't realize mimic-code and mimic-iv were totally separate, I always thought  mimic-ivwas submodule to mimic-code repo, my bad. Thanks again!

**Comment by briangow** [comment]
We have archived the old MIT-LCP/mimic-iv repo since all of the up to date code is now at [MIT-LCP/mimic-code](https://github.com/MIT-LCP/mimic-code) .
