### ISSUE TITLE
postgres_make_concepts.sh

### ISSUE THREAD

**Issue by zhangyongheng78** [MIT-LCP/mimic-code#1125]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I tried to run postgres_make_concepts.sh 
however, I encountered issues like (just like the follow-up in the website above)

NOTICE:  table "ventilation_durations" does not exist, skipping
DROP TABLE
ERROR:  column "minute" does not exist
LINE 47: ...          DATETIME_DIFF(CHARTTIME, charttime_lag, MINUTE)/60
the other similar one is like

NOTICE:  table "crrt_durations" does not exist, skipping
DROP TABLE
ERROR:  column "hour" does not exist
LINE 153: ...when DATETIME_DIFF(charttime, charttime_prev_row, HOUR) <= 2

**Comment by JackieMium** [comment]
Go through `README` in the folder first. Now it should work. Remember to run `postgres-funtions.sql` first.

**Comment by zhangyongheng78** [comment]
Hi @JackieMium, thank you for your time in helping me.

Does my error mean that I did not successfully build up the functions by running ```postgres-functions.sql```?

I tried ```psql -d mimic -U postgres -W -f postgres-functions.sql```. However, when I try to log in using ```psql -d mimic -U postgres``` and then do ```\df``` to check the list of functions, it returns empty.

**Comment by JackieMium** [comment]
Go into the folder `mimic-code/mimic-iv/concepts/postgres/`, start `psql` there. Or start `psql` anywhere you want and use `\cd` command to change working directory to the folder aforementioned. Then: 

1. `set search_path to mimic_derived, mimic_core, mimic_hosp, mimic_icu, mimic_ed;`
2. `\i postgres-functions.sql`
3.  `\i postgres-make-concepts.sql`

This should work. Anyway, I just copied from `mimic-iv/concepts/postgres/README.md` as I said followed the instructions there it'll all just work.

**Comment by zhangyongheng78** [comment]
Hi @JackieMium sorry for my mistake that did not describe the problem source. I tried to follow the ```README.md``` file in the 
```mimic-iii```folder: https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iii/concepts

I tried the way mentioned in my previous comment, as well as 
1. ```\i postgres-functions.sql```
2. quit ```psql```
3. ```bash postgres_make_concepts.sh```

The same error still appears.

**Comment by JackieMium** [comment]
Sorry are you talking about `mimic-iii` concepts? I thought you were talking about `mimic-iv`.  

You error message indicate `DATETIME_DIFF` function failed due to `MINUTE` and `HOUR` not surrounded in quotes. But as you can see from https://github.com/MIT-LCP/mimic-code/blob/189ded0dbb3a4f37c611fe803533de7c27d1e33f/mimic-iii/concepts/postgres_make_concepts.sh#L6 and https://github.com/MIT-LCP/mimic-code/blob/189ded0dbb3a4f37c611fe803533de7c27d1e33f/mimic-iii/concepts/postgres_make_concepts.sh#L30-L31

The script should've taken care of that. Make sure `\i postgres-functions.sql` successfully ran and all the functions are there, the script should work flawlessly.

**Comment by zhangyongheng78** [comment]
Hi @JackieMium , thank you very much for your reply. 

I did successfully created functions for MIMIC-III. However, when I try to run the .sh file after quit the psql, same error appears (the functions created disappeared after log back in psql again)

**Comment by JackieMium** [comment]
Are you sure you cannot find any of the functions and tables in your `search_path`? The functions should be stored in `mimiciii` schema and generated tables in `public`. And these functions won't disappear unless you drop them. Are you using the same `psql` account all the way?

**Comment by zhangyongheng78** [comment]
Hi @JackieMium, I double-checked and found out that the functions do exist and I need to use ```\df mimiciii.``` to display them after logging back in.

Now I am trying to run ```bash postgres_make_concepts.sh```, the same error still appears. 

I suspect and changed [https://github.com/MIT-LCP/mimic-code/blob/189ded0dbb3a4f37c611fe803533de7c27d1e33f/mimic-iii/concepts/postgres_make_concepts.sh#L13](url) to ```export PSQL_PREAMBLE='SET search_path TO mimiciii'``` but it does not change anything.

Are there any other place that may cause the ```.sh```file calling functions from the public schema? Thank you very much!

**Comment by JackieMium** [comment]
I really cannot figure out what's the matter here. I suggest you do the following:

- Make sure you have the latest code from this repo and that you didn't modify anything in it, a fresh `git clone` is the best way to ensure.
- Change working dir to `mimic-code/mimic-iii/concepts`
- Connect to PostgreSQL and `set search_path to public, mimiciii;`
- `\i postgres-functions.sql` to create all the functions
- Make a copy of the `postgres_make_concepts.sh` script and comment out all other lines to generate table except the `durations/ventilation_durations.sql` line and see if it works.

Also, I think you can modify `durations/ventilation_durations.sql` manually according to `postgres_make_concepts.sh` too to try generating the table yourself. If it works, `postgres_make_concepts.sh` is not the evil to blame here.

**Comment by zhangyongheng78** [comment]
@JackieMium Thank you so very much for your advice. The issue is resolved. Here is what I did:
1- Replace ```(.+?)``` with  ```([^,]+)``` in the ```REGEX_DATETIME_DIFF``` variable in ```postgres_make_concepts.sh```
2- Add Quotation Mark for the third argument of the ```DATETIME_DIFF``` function. For example, I change ```DATETIME_DIFF(CHARTTIME, charttime_lag, MINUTE)```  to ```DATETIME_DIFF(CHARTTIME, charttime_lag, 'MINUTE')```
