### ISSUE TITLE
subject_id/hadm_id ratio over anchor_year_group

### ISSUE THREAD

**Issue by piercaru** [MIT-LCP/mimic-code#1129]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hello everyone,
I started analyzing the new anchor_year_group feature added in MIMICIV.
From my very first analysis, it seems that the ratio between hadm_id and subject_id decreases dramatically over the anchor_year_group (up to half in the last years!)
This datum surprised me, and I wanted to be sure that is correct.
Do anyone else got the same result?
Thanks!

P

**Comment by briangow** [comment]
On some level this makes sense as patients whose first admission was more recent are less likely to have follow-up admissions. Feel free to share your relevant code and results here.

**Comment by piercaru** [comment]
Thanks for the answer.
If I understood correctly then the anchor_year_group just relates to the first admission of the patient.
So for example if a patient got hospitalized in 2011, 2015 and 2019 he will belong to the 2011 anchor_year_group, is it?
Does this holds true for every patient? Or it might be possible that due to anonymization processes some patients are located in different anchor_year_groups?
Thank you for the answer once again!

**Comment by briangow** [comment]
Actually I think the `anchor_year_group` is tied to each admission for the patient. This is the example from the website:

- Example: a patient has an `anchor_year` of 2153, `anchor_year_group` of 2008 - 2010, and an `anchor_age` of 60.
- The year 2153 for the patient corresponds to 2008, 2009, or 2010.
- The patient was 60 in the shifted year of 2153, i.e. they were 60 in 2008, 2009, or 2010.
- A patient admission in 2154 will occur in 2009-2011, an admission in 2155 will occur in 2010-2012, and so on.

In my previous post, I was simply saying that if their first admission was on the latter side of the admissions tracked in MIMIC-IV then there wouldn't be much opportunity for follow-up admissions.  Therefore, there would be less hadm_id's per subject_id for patients whose first admission is towards the end date for the data included in MIMIC-IV.

**Comment by piercaru** [comment]
Thank you very much for your answer.
I have an additional question concerning your last point: 
"A patient admission in 2154 will occur in 2009-2011, an admission in 2155 will occur in 2010-2012, and so on."
Does the relationship between the first hadm_id time and the following one belonging to other anchor_year_group is lost in this example?

One last question as you are so clear in your answers, if I calculate the number of unique subject_id in every anchor_year_group, I should be able to avoid the reduction of the ratio between subject_id and hadm_id as a patient that appears in more than one single category is counted once per every anchor_year_group, is it correct?

**Comment by briangow** [comment]
> Does the relationship between the first hadm_id time and the following one belonging to other anchor_year_group is lost in this example?

I'm not sure I understand your question here. Each `hadm_id` is unique for each visit. 

> One last question as you are so clear in your answers, if I calculate the number of unique subject_id in every anchor_year_group, I should be able to avoid the reduction of the ratio between subject_id and hadm_id as a patient that appears in more than one single category is counted once per every anchor_year_group, is it correct?

You could take a look to see what happens but you may still observe a lower number of `hadm_id's` per `subject_id` in the latter years, as discussed above.

**Comment by piercaru** [comment]
Sorry that my question was not clear. 
I will make an example to clarify my reasoning:
admission 1 = 2154 -- real year 2009
admission 2 = 2155 -- real year 2012

Is this something that might happen or the relational time between the first hadm_id and the following ones are maintained?
I might understand that is not maintained for the anonymization process, and that this relationship could be lost but I would like to know if it was performed or not.
Because if it is maintained in this other example
admission 1 = 2154 -- anchor_year_group 2009-2011
admission 2 = 2154 -- anchor_year_group 2010-2012
I can assume that probably both the hadmid belongs to 2010-2011

On the second question:
I will go further in the analysis so that I might explain myself better.

**Comment by alistairewj** [comment]
> Sorry that my question was not clear. 
> I will make an example to clarify my reasoning:
> admission 1 = 2154 -- real year 2009
> admission 2 = 2155 -- real year 2012
> 
> Is this something that might happen or the relational time between the first hadm_id and the following ones are maintained?
> I might understand that is not maintained for the anonymization process, and that this relationship could be lost but I would like to know if it was performed or not.
> Because if it is maintained in this other example
> admission 1 = 2154 -- anchor_year_group 2009-2011
> admission 2 = 2154 -- anchor_year_group 2010-2012
> I can assume that probably both the hadmid belongs to 2010-2011

The time between two events is retained. So to fix your latter case and give an example:

> admission 1 = 2154 -- anchor_year_group 2009-2011
> admission 2 = 2155 -- anchor_year_group 2010-2012

This is exactly how the anchor_year_group should be interpreted.
