### ISSUE TITLE
Issue with `postgres-make-concepts.sql`: accessing `mimic_derived` tables via Postgres

### ISSUE THREAD

**Issue by tchainzzz** [MIT-LCP/mimic-code#1144]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I'm trying to use the Postgres scripts in `mimic-code/mimic-iv/concepts/postgres` to extract the concepts from MIMIC-IV. However, when I run `\i postgres-functions.sql`, I'm running into errors of the following form:
```
psql:organfailure/kdigo_uo.sql:76: ERROR:  relation "mimic_derived.urine_output" does not exist
```

In summary, errors of the form `relation mimic_derived.<TABLE_NAME> does not exist` seem to appear each time the SQL query for a concept file contains a reference to `mimic_derived` table.

I believe that these tables are accessible via BigQuery, but I'm currently limited to using Postgres. Is there a way for me to access/download the `mimic_derived` tables still?

**Edit:** Looking more closely, it appears that these tables *are* generated by the `postgres-make-concepts.sql` script at some point, but there might be some ordering/dependency issues causing this?

**Related issues:** #981.

### What I've done

* I've downloaded and unzipped the MIMIC-IV v1.0 dataset in local storage, and can access all the data tables there.
* I've completed the instructions in the `mimic-code/mimic-iv/buildmimic/` folder and I can access all the tables prefixed with `mimic_core`, `mimic_hosp`, and `mimic_icu` successfully. 
* Then, from `mimic-code/mimic-iv/concepts/postgres`, I run in Postgres `set search_path to mimic_derived, mimic_core, mimic_hosp, mimic_icu, mimic_ed;` with no issues.
* Still in the same directory, I can run `\i postgres-functions.sql` with no problem.
* The errors start to appear when I run `\i postgres-make-concepts.sql`.

Thanks for the help, and for creating this resource!

**Comment by briangow** [comment]
From `psql` does `\dn` show a `mimic_derived` schema? If not, this is probably the problem since it is looking for the `urine_output` table there but it may have been created elsewhere.

**Comment by tchainzzz** [comment]
I see -- yes, that's the issue. I needed to first run
```
DROP SCHEMA IF EXISTS mimic_derived CASCADE;
CREATE SCHEMA mimic_derived;
```
in Postgres to create the relevant schema. Sorry, I'm pretty inexperienced with Postgres and didn't realize I had to do this.

Would it make sense to update the scripts in `buildmimic/` with this? Or document this in the `concepts/` folder `README`?

**Comment by briangow** [comment]
Yes, if you are comfortable submitting a pull request which makes the necessary updates to the scripts that would be great! I don't think the concepts code for Postgres has been tested extensively in MIMIC-IV, so it's possible that there are a few issues like this that need to be cleaned up.

**Comment by tchainzzz** [comment]
Thanks! Done in #1145 .
