### ISSUE TITLE
Add a `callout` table to MIMIC-IV ICU

### ISSUE THREAD

**Issue by briangow** [MIT-LCP/mimic-code#1152]
There is interest in having `callout` in MIMIC-IV: https://github.com/MIT-LCP/mimic-code/discussions/1147 . A `callout` table was released in MIMIC-III as part of a specific project which needed this information. We should look into creating a `callout` table in the MIMIC-IV ICU module in a future release.

**Comment by SichengH** [comment]
The callout table stopped updating since 2018.
