### ISSUE TITLE
Unable to Connect MIMIC III to Python Environment 

### ISSUE THREAD

**Issue by shivank-mistry** [MIT-LCP/mimic-code#1153]
Hello, I am currently trying to connect the MIMIC-III database to a python environment. 
I have followed [these](https://jingsblog.com/2018/11/27/connect-your-jupyter-notebook-to-the-bigquery/) steps to connect to a jupyter notebook, but I always get the error message of....
`ModuleNotFoundError: No module named 'google.cloud'`
after importing...
`from google.cloud import bigquery`

I have tried setting up a virtual environment and still did not have any success. I have gone through the process of setting a JSON key and install all of the relevant packages (see link above). 

I am not really sure what to do now, I understand this might be a problem with the google.cloud services and not MIMIC-III but I was hoping other people ran into a similar problem. 

Let me know if you have any questions!

Thanks

**Comment by tompollard** [comment]
@shivank-mistry Please see the following discussion for more information: https://github.com/MIT-LCP/mimic-code/discussions/1154
