### ISSUE TITLE
MIMIC-IV : ICU stays table does not include icu stay at admission.

### ISSUE THREAD

**Issue by cheneeheng** [MIT-LCP/mimic-code#1165]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I noticed that the icustays table does not include ICU entries from the transfers table where "eventtype = admit". (see below)
Is this intended ? I could not find and info on this in the documentation.

Thanks !

---

**transfers** : Here the 2 CCU entries are the ICU stays.
<html>
<body>

 subject_id | hadm_id | transfer_id | eventtype | careunit | intime | outtime
 -- | -- | -- | -- | -- | -- | --
17374121 | 27667114 | 33588312 | admit | Coronary Care Unit (CCU) | 2115-07-22 09:50:09 | 2115-07-22 14:42:22
17374121 | 27667114 | 35428124 | transfer | PACU | 2115-07-22 14:42:22 | 2115-07-23 10:32:48
17374121 | 27667114 | 37739556 | transfer | Medicine/Cardiology | 2115-07-23 10:32:48 | 2115-07-24 14:00:36
17374121 | 27667114 | 37912371 | transfer | Coronary Care Unit (CCU) | 2115-07-24 14:00:36 | 2115-07-24 14:50:33
17374121 | 27667114 | 32783367 | transfer | Medicine/Cardiology | 2115-07-24 14:50:33 | 2115-07-24 17:57:17
17374121 | 27667114 | 32973608 | discharge | None | 2115-07-24 17:57:17 | NaT

</body>
</html>

**icustays** : But only "eventtype = admit" is included...
<html>
<body>

subject_id | hadm_id | stay_id | first_careunit | last_careunit | intime | outtime | los
-- | -- | -- | -- | -- | -- | -- | --
17374121 | 27667114 | 37912371 | Coronary Care Unit (CCU) | Coronary Care Unit (CCU) | 2115-07-24 14:00:36 | 2115-07-24 14:50:33 | 0.034688

</body>
</html>

**Comment by alistairewj** [comment]
Hrm. The ICU information system lists this patient as admitted from 07-22 to 07-24 but the hospital database lists them as admitted 07-22, then moving around, then back in at 07-24 (and out again very shortly after). Our matching logic makes use of heart rate measurements made in the ICU (with the idea being if they don't have heart rate measurements, they aren't actively in the ICU). For this patient they only have heart rate measurements on 07-24 at 13:46, 14:00, 14:29, and 14:30, which lines up with their ICU stay `intime` / `outtime`. So maybe patients "admitted" to the CCU don't actually visit the ICU? which sounds too odd for it to occur more than once or twice... Do you have other examples?

**Comment by cheneeheng** [comment]
Hi @alistairewj ,

I did some more digging this morning and I found:

- There are 73707 out of 523740 hadm entries where at least an ICU entry is present.
- 3930 out of 73707 (~5.3%) hadm entries where at least an ICU entry with `eventtype = admit` in `transfers` is not present in the `icustays`. (`outtime - intime` ranges from 9-86375s )
- 4203 out of 73707 (~5.7%) hadm entries where at least an ICU entry with `eventtype = transfer` in `transfers` is not present in the `icustays`.  (`outtime - intime` ranges from 7-86390s )
- The merging of consecutive ICU entries are correct (validated using the `intime`/`outtime`).

I would say 5% is quite a few. It might cause some problems if one is not aware of this when querying. (which is how I found out about this in the first place =D)

The matching logic (using HR) is not mentioned in the documentation, or at least I couldn't find it anywhere. Will it be put into the documentation in the future?

Thanks!

**Comment by alistairewj** [comment]
> The matching logic (using HR) is not mentioned in the documentation, or at least I couldn't find it anywhere. Will it be put into the documentation in the future?

Well, it should be! I'll try to add it later (or feel free yourself with a PR to https://github.com/MIT-LCP/mimic-website/)

We're building an update at the moment so we'll dig into this issue while preparing that release.

**Comment by cheneeheng** [comment]
1. Just to summarize the findings above, 4496 out of 73707 (~6%) hadm entries in transfers table is not present in the icustays table. 4496 includes both the 3930 and the 4203 hadm mentioned above.
2. Opened a pull request for the website.

**Comment by SichengH** [comment]
The ```transfers``` table contains hospital administrative records about a patient’s clinical unit visit. For example, row 1 - 6 from the first table represents a patient's hospital-level administrative records throughout a hospital stay. In the build process, consecutive ICU unit visits in the ```transfers``` table are considered as ICU stay. For example in the first table, row 1 and 2 appears to be the first ICU stay and row 4 appears to be the second ICU stay for that hospital admission. However, sometimes hospital-level administrative transfer records can be misleading. Patients sometimes have records about an ICU unit stay in the ```transfers``` table but they are never actually admitted to the ICU.  We address this problem during the conversion from ```transfers``` table to ```icustays``` table by removing ICU unit stays where there are no heart rate measurements. We would expect heart rate to be available for all ICU stays. For example, in the table below(copy table), row 1 and 2 are two ICU unit visit but due to they don’t have recorded heart rate present. We removed the ICU stay from the ```icustays``` table entirely.

**Comment by tompollard** [comment]
@cheneeheng does this answer your question? If so, please close the issue. @SichengH please could you add the missing tables that you intended to post?

**Comment by cheneeheng** [comment]
@tompollard yes it does. It can be closed.
