### ISSUE TITLE
Microbiologyevents.csv.gz corrupted?

### ISSUE THREAD

**Issue by konrad3** [MIT-LCP/mimic-code#117]
Hi all,

first of all thanks for this great work! 

When I downloaded the csv.gz files from the server to unzip them, everything went fine except for microbiologyevents.csv.gz. Here it created a .cpgz file (unzipping this again results in a cpgz file). Might this file be corrupted?

I use MacOS 10.11 and the standard archive utility tool.

Thanks,
Konrad

**Comment by tompollard** [comment]
Thanks Konrad. 

First you should confirm that the file has not become corrupted during download. The checksums provided on PhysioNet should match the checksums of your local files. Looking at the "`checksum_md5_zipped.txt`" file on PhysioNet, the checksum for `MICROBIOLOGYEVENTS.csv.gz` should be `85c3b880a1bedf46e809b40360897e47`. 

Test this by opening Terminal, navigating to the folder containing `MICROBIOLOGYEVENTS.csv.gz`, then running "`md5sum MICROBIOLOGYEVENTS.csv.gz`" (if that doesn't work, try "`md5 MICROBIOLOGYEVENTS.csv.gz`" instead). The output from this command should match the checksum on PhysioNet.

For example:

```bash
> md5sum MICROBIOLOGYEVENTS.csv.gz 
85c3b880a1bedf46e809b40360897e47  MICROBIOLOGYEVENTS.csv.gz
```

Assuming the file is fine, you should try using an alternative tool for unzipping the file. The tool that ships with Mac OSX has some known issues: http://superuser.com/questions/114011/extract-large-zip-file-50-gb-on-mac-os-x, so you could try gzip from the command line instead. Open a shell in Terminal and then navigate to `MICROBIOLOGYEVENTS.csv.gz`. Next run `gzip -d MICROBIOLOGYEVENTS.csv.gz` to decompress the file:

For example:

```bash
> ls
MICROBIOLOGYEVENTS.csv.gz

> gzip -d MICROBIOLOGYEVENTS.csv.gz 
> ls
MICROBIOLOGYEVENTS.csv
```

**Comment by alistairewj** [comment]
Going to assume this is fixed - feel free to re-open the issue if you are still having trouble.
