### ISSUE TITLE
Calculating Sofa concept: Several provided scripts can't find several data. MIMIC III

### ISSUE THREAD

**Issue by Philippmuench92** [MIT-LCP/mimic-code#1179]
### Prerequisites

* [X] 
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Also tried so resolve the issue following https://sql.info/d/bigquery-error-not-found-dataset-xyz-was-not-found-in-location-us and https://stackoverflow.com/questions/51395256/error-not-found-dataset-my-project-namedomain-public-was-not-found-in-locatio

### Description

Im trying to calculate the SOFA score in MIMIC 3 using the provided concepts from github.
To do so you have to run the 9 subordinate queries from which the following 6 worked without any issues:
-pivoted_uo
-pivoted_lab
-pivoted_gcs
-ventilation_duration
-dopamine_dose
-dobutamine_dose

1. Issue: Running pivoted_bg BigQuery returns me: 

"Not found: Dataset physionet-data-330409:physionet-data was not found in location US at [148:1]"

pointing to line 148. But looking at the directory the table is there as you can see here.

![grafik](https://user-images.githubusercontent.com/92937536/139230964-75693cf9-efbf-4d30-9f0f-a6139b29dd81.png)

2. Issue: Running norepinephrine_dose BigQuery returns me: 

"Not found: Table physionet-data:mimiciii_clinical.weight_durations was not found in location US"

Checking the directory manually the table was indeed not there as you can see here:

![grafik](https://user-images.githubusercontent.com/92937536/139232547-a590c191-1b75-49c3-8c26-d79515ceb513.png)

To resolve this I also tried to run the weight_durations query before and save it into the directory but the system said I dont have permission to do so.

![grafik](https://user-images.githubusercontent.com/92937536/139233063-715d051a-7b94-4ec5-a251-c82688056c87.png)

3. Issue: Running epinephrine_dose BigQuery returns me the same error as for Issue no. 2

"Not found: Table physionet-data:mimiciii_clinical.weight_durations was not found in location US"

This scripts tells me it needs the weight_first_day table which requires echodata view, generated by concepts/echo-data.sql.

Unfortunately trying this also did not help.

I'm really confused since some scripts work just fine and others do not.

My workspace/explorer looks like this:

![grafik](https://user-images.githubusercontent.com/92937536/139234731-dfec2329-6b1d-4b27-a9c6-75762a25cb6b.png)

Not sure if there is an issue here.

Thank you for all the replies in advance. I'm new to BigQuery and SQL in general so I hope this issue isnt just a trivial one.

Best regards Phil

**Comment by alistairewj** [comment]
> 1. Issue: Running pivoted_bg BigQuery returns me:
> "Not found: Dataset physionet-data-330409:physionet-data was not found in location US at [148:1]"

This is telling you: "Not found: Dataset <google_project_name>:<google_dataset_name> was not found". Which is correct; the *project* for MIMIC data is `physionet-data`, not `physionet-data330409`. The latter is probably a custom project you created and only you have access to. The dataset on the `physionet-data` project (for derived concepts from MIMIC-III) is `mimiciii_derived`. You have permission to read data from `physionet-data.mimiciii_derived`, but you can't write anything to it.

For the blood gas query, it looks like there is a bug is here:
https://github.com/MIT-LCP/mimic-code/blob/10613e72b2faf5a449f2a241cca1bdc86b413b05/mimic-iii/concepts/pivot/pivoted_bg.sql#L206

which is an incomplete table reference. It should read `physionet-data.mimiciii_derived.pivoted_bg` bg. This query was awkwardly carried over from postgres to be honest - we shouldn't create a view in the middle of a query as there's a convention in the repository to generate one table per query. I'll move pivoted_bg_art to its own query.

However, in general the table references are something to keep in mind with the derived scripts: they all assume the tables are generated on the `mimiciii_derived` dataset on BigQuery. If you are re-running them to recreate concepts in your own dataset on BigQuery, you'll need to update all the references to `physionet-data.mimiciii_derived` across all the queries.

> 2. Issue: Running norepinephrine_dose BigQuery returns me:
> "Not found: Table physionet-data:mimiciii_clinical.weight_durations was not found in location US"

This is an incorrect table reference - should be `physionet-data:mimiciii_derived.weight_durations` (note the change mimiciii_clinical -> mimiciii_derived).

> 3. Issue: Running epinephrine_dose BigQuery returns me the same error as for Issue no. 2

Yep, it had the same bug.

Thanks for raising!

**Comment by Philippmuench92** [comment]
Thank you for your help. The solutions you provided actually worked out and I could run the scripts after applying the fixes.





> 
> 
> > 1. Issue: Running pivoted_bg BigQuery returns me:
> >    "Not found: Dataset physionet-data-330409:physionet-data was not found in location US at [148:1]"
> 
> This is telling you: "Not found: Dataset <google_project_name>:<google_dataset_name> was not found". Which is correct; the _project_ for MIMIC data is `physionet-data`, not `physionet-data330409`. The latter is probably a custom project you created and only you have access to. The dataset on the `physionet-data` project (for derived concepts from MIMIC-III) is `mimiciii_derived`. You have permission to read data from `physionet-data.mimiciii_derived`, but you can't write anything to it.
> 
> For the blood gas query, it looks like there is a bug is here:
> 
> https://github.com/MIT-LCP/mimic-code/blob/10613e72b2faf5a449f2a241cca1bdc86b413b05/mimic-iii/concepts/pivot/pivoted_bg.sql#L206
> 
> which is an incomplete table reference. It should read `physionet-data.mimiciii_derived.pivoted_bg` bg. This query was awkwardly carried over from postgres to be honest - we shouldn't create a view in the middle of a query as there's a convention in the repository to generate one table per query. I'll move pivoted_bg_art to its own query.
> 
> However, in general the table references are something to keep in mind with the derived scripts: they all assume the tables are generated on the `mimiciii_derived` dataset on BigQuery. If you are re-running them to recreate concepts in your own dataset on BigQuery, you'll need to update all the references to `physionet-data.mimiciii_derived` across all the queries.
> 
> > 1. Issue: Running norepinephrine_dose BigQuery returns me:
> >    "Not found: Table physionet-data:mimiciii_clinical.weight_durations was not found in location US"
> 
> This is an incorrect table reference - should be `physionet-data:mimiciii_derived.weight_durations` (note the change mimiciii_clinical -> mimiciii_derived).
> 
> > 1. Issue: Running epinephrine_dose BigQuery returns me the same error as for Issue no. 2
> 
> Yep, it had the same bug.
> 
> Thanks for raising!
