### ISSUE TITLE
a slight inconsistency in `physionet-data.mimic_derived.oxygen_delivery`

### ISSUE THREAD

**Issue by zqr2008** [MIT-LCP/mimic-code#1180]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/ 
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
* what you have tried
I am a medical doctor from emergency department, who are using mimic-iv on bigquery.

I notice a slight inconsistency in `physionet-data.mimic_derived.oxygen_delivery` .  The variable o2_flow's meaning is slightly different in clinical setting. The flow of O2 is usually 2L/min to 10L/min when we are using nasal cannula. 
Moreover,when ventilator are used, the concept of O2 changes when the patient is ventilated. However, the o2 flow in derived oxygen delivery table is so variable with number to decimals. It can not be what the doctor set in real clinical setting.

* references to similar issues
* no refernces.
* 
* queries demonstrating your question (if applicable)
 SELECT  o2_flow,o2_flow_additional,o2_delivery_device_1 FROM `physionet-data.mimic_derived.oxygen_delivery`

**Comment by alistairewj** [comment]
In general the data hasn't been cleaned in that view (yet! pending contribution from anyone with the requesite expertise), so you do see fractional delivery e.g.

```sql
select * from `physionet-data.mimic_icu.chartevents`
where subject_id = 14964949
and itemid = 223834
order by charttime
```

has a value of 4.5 which is then propagated to the oxygen_delivery view:

```sql
select * from `physionet-data.mimic_derived.oxygen_delivery`
where subject_id = 14964949
order by charttime
```

However, there may be a related error in the code here:
https://github.com/MIT-LCP/mimic-code/blob/10613e72b2faf5a449f2a241cca1bdc86b413b05/mimic-iv/concepts/measurement/oxygen_delivery.sql#L21

There, I include itemid 224691 "Flow Rate (L)" as an O2 flow, but perhaps that is actually a flow rate from a different device.. That would explain the existence of odd flow rates when patients are ventilated, such as for this patient:

```sql
select * from `physionet-data.mimic_derived.oxygen_delivery`
where subject_id = 11542052
order by charttime
```

```sql
select * from `physionet-data.mimic_icu.chartevents`
where subject_id = 11542052
and itemid in (223834, 224691)
order by charttime
```




row | subject_id | time  | itemid | valuenum | valueuom
-- | -- | -- | -- | -- | --
13 | 11542052 | 06:00:00 | 223834 | 6.0 | L/min
14 | 11542052 | 20:00:00 | 224691 | 46.7 | L/min
15 | 11542052 | 23:00:00 | 224691 | 46.3 | L/min

.. where they have flow rates which go into fractional decimals between 35-45. Anyone have any thoughts on what the second flow rate could be?

**Comment by zqr2008** [comment]
After your remind, I checked the code along with ventilator knowledge.
**The derived oxygen_delivery indeed has its inconsistency in its original code,it merge o2 flows from different devices into a single row **:

`
 WHEN itemid IN (223834, 227582, 224691) THEN 223834
 ELSE itemid END AS itemid
 `


From my personal point of view(may not be very precise), The parameters we doctors set in ventilator is usually about fio2, volume(or pressure), rate. ( it only applies to some ventilator, I know some ventilator have very fancy mode with different settings  ).   when we are using nasal cannula, it is usually a fixed integer.

However, the ventilator can have flow rate very precise to fractional decimals. Why is that? It is because this number of flow rate is produced by interactions between ventilator and the patient.  The flow rate itself is always changing during each breath(from inhale to exhale), which can be detected precisely by sensor in the tube. It is a reflect of mixture of respiratory dynamics.




> ```sql
> select * from `physionet-data.mimic_icu.chartevents`
> where subject_id = 11542052
> and itemid in (223834, 224691)
> order by charttime
> ```
> 
> row	subject_id	time	itemid	valuenum	valueuom
> 13	11542052	06:00:00	223834	6.0	L/min
> 14	11542052	20:00:00	224691	46.7	L/min
> 15	11542052	23:00:00	224691	46.3	L/min

Judging by your code and output, I guess that the ventilator automatically grasp the flow rate of the patient at that particular second.  It is what the sensor recorded at that moment, always changing.

Regretfully, it does not solve my problem. As I mentioned, the concept of O2 flow rate changes when the patient is ventilated. In clinical settings, those two can not be analyzed together.  I think I need to come up with a way to process it.  But you kindest explanation help me a lot. Thank you very much.
