### ISSUE TITLE
Documentation in Prescriptions Table

### ISSUE THREAD

**Issue by esherma** [MIT-LCP/mimic-code#119]
The Prescriptions table in the version I have (MIMIC-III downloaded about a month ago) has tables: Row_ID, Subject_ID, HADM_ID, etc.
The documentation on the MIMIC website (https://mimic.physionet.org/mimictables/prescriptions/) only does not have the Row_ID field listed.  This can cause serious issues with array indexing in non-SQL programming languages.

**Comment by tompollard** [comment]
Well spotted @esherma. The MIMIC website and documentation are developed by the community and hosted in GitHub. For more information see: http://mimic.physionet.org/community/contributing/. 

Please could you navigate to the relevant page on GitHub (direct link here: https://github.com/MIT-LCP/mimic-website/edit/master/content/mimictables/prescriptions.md), update the table, and then submit a pull request?
