### ISSUE TITLE
Annotation on CXR

### ISSUE THREAD

**Issue by ayhyap** [MIT-LCP/mimic-code#1198]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I came across an image in MIMIC-CXR [an unexpected] annotation. Please provide a means for me to share the details.

**Comment by briangow** [comment]
@ayhyap , thank you for alerting us to this! Could you please email contact@physionet.org with the relevant details.
