### ISSUE TITLE
MIMIC IV：blood_differential.sql has an error

### ISSUE THREAD

**Issue by duanxiangjie** [MIT-LCP/mimic-code#1208]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

The materialized view (blood_differential.sql) has an error, as follows:  

----------------------------------------
, ROUND(CASE
    WHEN basophils_abs IS NULL AND basophils IS NOT NULL AND impute_abs = 1
        THEN basophils * wbc   ----   basophils * wbc / 100
    ELSE basophils_abs
END, 4) AS basophils_abs
, ROUND(CASE
    WHEN eosinophils_abs IS NULL AND eosinophils IS NOT NULL AND impute_abs = 1
        THEN eosinophils * wbc  ----- eosinophils * wbc / 100
    ELSE eosinophils_abs
END, 4) AS eosinophils_abs
, ROUND(CASE
    WHEN lymphocytes_abs IS NULL AND lymphocytes IS NOT NULL AND impute_abs = 1
        THEN lymphocytes * wbc  ----  lymphocytes * wbc / 100
    ELSE lymphocytes_abs
END, 4) AS lymphocytes_abs
, ROUND(CASE
    WHEN monocytes_abs IS NULL AND monocytes IS NOT NULL AND impute_abs = 1
        THEN monocytes * wbc  ---- monocytes * wbc / 100
    ELSE monocytes_abs
END, 4) AS monocytes_abs
, ROUND(CASE
    WHEN neutrophils_abs IS NULL AND neutrophils IS NOT NULL AND impute_abs = 1
        THEN neutrophils * wbc  ---- neutrophils * wbc / 100
    ELSE neutrophils_abs
END, 4) AS neutrophils_abs

---------------

**Comment by alistairewj** [comment]
thanks! will be fixed on bigquery when we next push a release (soon-ish, likely within the week).
