### ISSUE TITLE
Wrong filenames in mysql dump

### ISSUE THREAD

**Issue by Aleyasen** [MIT-LCP/mimic-code#121]
The name of files in the mysql dump (mimic-code/buildmimic/mysql/1-define.sql) is not correct. The new files (except NOTEEVENT.csv) have "_DATA_TABLE" suffix, so they are not compatible with the dump file.

**Comment by alistairewj** [comment]
Thanks for the report. We're about to release a new version of MIMIC and when we do that we will review and fix the import scripts for the other database systems - they're clearly a little out of date! If you have fixed the MySQL scripts for your own purpose we'd welcome a pull request.

**Comment by alistairewj** [comment]
Oh wait - had it backwards - this is related to #43 - shouldn't be an issue after the new release which is imminent.

**Comment by Aleyasen** [comment]
oh, I see. thank for the clarification.

**Comment by alistairewj** [comment]
Fixed in the new release.
