### ISSUE TITLE
MIMIC-IV

### ISSUE THREAD

**Issue by Edakksm** [MIT-LCP/mimic-code#1229]
Is there a way to know if an admission is related to surgery? For those admissions that result in ICU stays, we can get that from FIRST_CAREUNIT/LAST. But those admissions which do not need ICU, how do we know that?

**Comment by alistairewj** [comment]
The closest method I've found is to use mapping from the AHRQ which maps procedure ICD codes into surgical/non-surgical.

**Comment by alistairewj** [comment]
Also, the care unit is not a good method, as medical patients will often stay in surgical units ("boarders").

**Comment by alistairewj** [comment]
Those groups are more or less equivalent to the categories on the wiki page: https://en.m.wikipedia.org/wiki/Current_Procedural_Terminology

**Comment by aegis301** [comment]
Hello, I came across this discussion and was wondering if there is a concept in place for AHRQ for MIMIC IV. So far I only could find one in the MIMIC III repo? I need to identify post-surgical patients for a study I am conducting.

**Comment by thomasjoyce7** [comment]
Hello. I am trying to identify ICU surgery patients in MIMIC-IV (i.e., ICU patients who underwent a surgical procedure). Now that the AHQR has released ICD-10 code mappings for major/minor diagnostic and major/minor therapeutic procedures, would that be the best method? I realized that using the ICU care units would not be a good method for the reasons discussed above.
