### ISSUE TITLE
Admission note?

### ISSUE THREAD

**Issue by 2533245542** [MIT-LCP/mimic-code#1230]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
* what you have tried
I tried querying the NOTEEVENT and ADMISSION tables and couldn't find an admission note. What's similar is the DISGNOSIS in the ADMISSION table but it was too short. Physicians usually write an admission note when a patient is admitted. The note describes the general situation of the patient. Is this piece of information included in MIMIC or I was just overlooking?

* references to similar issues

* queries demonstrating your question (if applicable)

**Comment by AINIVERSHERRY** [comment]
![image](https://user-images.githubusercontent.com/49436429/149739400-6084dd19-0033-4330-a5dd-a28632d8cb1c.png)

**Comment by alistairewj** [comment]
> I tried querying the NOTEEVENT and ADMISSION tables and couldn't find an admission note. What's similar is the DISGNOSIS in the ADMISSION table but it was too short. Physicians usually write an admission note when a patient is admitted. The note describes the general situation of the patient. Is this piece of information included in MIMIC or I was just overlooking?

Regrettably we do not have admission notes; but the discharge summaries are available: https://physionet.org/content/mimic-iv-note/

Usually the discharge summaries begin with the history of present illness and some admission information, though parsing them can be tricky.
