### ISSUE TITLE
Document deidentification of `anchor_age`

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/mimic-code#1231]
`anchor_age` is set to 91 for all patients over 89 as a part of the deidentification. The only difference between our approach between MIMIC-III and MIMIC-IV is that we use 91 rather than 300.

However this isn't explicitly documented online, I think? Didn't see it here https://mimic.mit.edu/docs/iv/modules/core/patients/

It probably should be!

**Comment by briangow** [comment]
Agreed! We were providing the information on the /iv/modules/core page but I think it should also be next to the definition for `anchor_age`. I have created a PR to add this.
