### ISSUE TITLE
Meropenem infusion duration

### ISSUE THREAD

**Issue by FeifanXie** [MIT-LCP/mimic-code#1246]
Hi,

As previously pointed out ([vanco administration #372](https://github.com/MIT-LCP/mimic-code/issues/372)),  the documented infusion time in MIMIC III for antibiotics like vancomycin is always 1 minute duration (endtime - start time) , which is not the ground truth. It seems that the same issue applies for the MIMIC IV. 

We recently work on the pharmacokinetics/pharmacodynamics of meropenem treatment in ICU patients from the MIMIC IV, and the actual infusion duration is important for the pharmacokinetic modeling. We were wondering if it is possible to get the actual infusion duration of meropenem in MIMIC IV?

Thanks in advanced!

**Comment by alistairewj** [comment]
You could try looking at the eMAR data for the subset of patients who have it. I haven't investigated the data in detail but it may have more duration information.

**Comment by alistairewj** [comment]
Hrm, unfortunately don't have good suggestions at this time. I can give you the dosing guidelines at the hospital though:

> Standard dosing recommendations of meropenem dosing are 1000mg Q8H for patients with adequate renal function (CrCl > 50mL/min). The BIDMC meropenem preferred dose and schedule for selected patients is 500mg Q6H based on pharmacodynamic models and clinical data.

Pharmacodynamic dosing | Dose/schedule adjustment
--- | ---
Recommended dose for patients with CrCl > 50 mL/min | 500 mg IV Q6H (including Pseudomonas aeruginosa)
CrCl 25-49 mL/min | 500mg IV Q8H 
CrCl 10-24 mL/min | 500mg IV Q12H
CrCl < 10 mL/min | 500 mg IV Q24H
HD | 500mg Q24H administered post-HD
PD | Not recommended
CRRT | 500mg IV Q8H

Traditional dosing | Dose/schedule adjustment
--- | ---
Recommended dose for patients with CrCl > 50 mL/min | 1000 mg IV Q8H (for patients with special dosing recommendations excluded from the protocol)
CrCl 25-49 mL/min | 1000mg IV Q12H
CrCl 10-24 mL/min | 500mg IV Q12H
CrCl < 10 mL/min | 500 mg IV Q24H
HD | 500mg Q24H administered post-HD
PD | Not recommended
CRRT | 1g IV Q12H

**Comment by FeifanXie** [comment]
Thank you very much! The provided information makes sense for me.
