### ISSUE TITLE
edregtime and edouttime 

### ISSUE THREAD

**Issue by MEladawi** [MIT-LCP/mimic-code#1247]
Hi, 

I just wanted to report some issue (or at least this how it appears to me) re: the **edregtime** and **edouttime** columns in the **mimic_core.admissions** table. 

What I noticed is that some admissions have the edregtime and edouttime as NULL while intime and outtime columns have values in **mimic_ed.edstays**

Example:
**hadm_id = 28347829** has a corresponding **stay_id = 33108480** (in mimic_ed.edstays)

![image](https://user-images.githubusercontent.com/16545437/152877427-f9a479a8-895b-4b34-9a23-cfbff6137927.png)
![image](https://user-images.githubusercontent.com/16545437/152877514-660163d4-7b4a-407a-afed-b92dbbf77000.png)

Thanks for all the hard work and support.

**Comment by alistairewj** [comment]
Will take a look, thanks!

**Comment by alistairewj** [comment]
I forgot to close this - but this was fixed in MIMIC-IV v2.0.

> Fixed an issue where hospitalizations were missing edregtime and edouttime when the patient was admitted via the ED (reported in [#1247](https://github.com/MIT-LCP/mimic-code/issues/1247), thanks [@MEladawi](https://github.com/MEladawi)).

Thanks!
