### ISSUE TITLE
Issue on norepinephrine_equivalent_dose.sql

### ISSUE THREAD

**Issue by Meicheng-SEU** [MIT-LCP/mimic-code#1279]
Hi, I found an issue with calculating norepinephrine equivalent dose for vasopressors.

The unit of the vasopressin should be units/minute rather than units/hour. The modified code in line 11 was as below.

**+ COALESCE(vasopressin*2.5/60, 0)**

**Comment by ShivGehlot** [comment]
@Meicheng-SEU , this script is not getting generated for me. How did you generate it?

**Comment by alistairewj** [comment]
Fixed in #1497 - thanks!
