### ISSUE TITLE
Getting error after login to query builder 

### ISSUE THREAD

**Issue by sonal051** [MIT-LCP/mimic-code#128]
![error](https://cloud.githubusercontent.com/assets/18608197/18526264/d8267e06-7a8d-11e6-9fd4-154e03c62421.png)

I am Getting above error after login to mimic DB . Please help!

**Comment by jeblundell** [comment]
Does it work for a test database? Or is it limited to specifically MIMIC? What steps have you taken to install? And what database engine are you using? I'm guessing from ORA-12505 that this is via Oracle?  Are you able to connect to the database when using something other than query builder, e.g. command line utilities?

**Comment by jeblundell** [comment]
See http://stackoverflow.com/a/18196876 for potential resolution - I suspect this isn't an issue with MIMIC itself.

**Comment by tompollard** [comment]
@sonal051 it looks like you are using an old version of the querybuilder which is no longer supported. Please login to the new querybuilder available at: http://mimic.physionet.org/gettingstarted/querybuilder/

**Comment by sonal051** [comment]
New link is working.
Thanks!
