### ISSUE TITLE
HADM_ID is null for many patients in LABEVENTS.csv

### ISSUE THREAD

**Issue by Edakksm** [MIT-LCP/mimic-code#1294]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I am trying to group the labevents based on HADM_ID to get the min/max of lab value for each patient visit. But there are missing HADM_IDs.

**Comment by Baytars** [comment]
@Edakksm Hey, what did you find that led you to closing the issue? Please share your insights. Thanks!
