### ISSUE TITLE
MIMIC IV：vitalsign.sql has an error

### ISSUE THREAD

**Issue by duanxiangjie** [MIT-LCP/mimic-code#1297]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

![Snipaste_2022-04-28_16-51-29](https://user-images.githubusercontent.com/51899535/165716047-bc478ab6-7a5b-4560-8199-98e24a488133.jpg)

**Comment by alistairewj** [comment]
fixed in #1477 thanks all
