### ISSUE TITLE
Tool for downloading MIMIC data from physionet

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#130]
To simplify the process of downloading the MIMIC dataset, it might be helpful to provide a command line tool. e.g. a download function could be added to the [makefile](https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/Makefile). 

The function would just need to run a command along the lines of:

```
wget --user PHYSIONETUSERNAME --ask-password -A csv.gz -m -p -E -k -K -np https://physionet.org/works/MIMICIIIClinicalDatabase/files/
```

**Comment by alistairewj** [comment]
Duplicate of #108?

**Comment by tompollard** [comment]
Well spotted. I'll close this and will try to update the makefile later today.
