### ISSUE TITLE
SQL changes for MIMIC-IV v2.0

### ISSUE THREAD

**Issue by epabarker** [MIT-LCP/mimic-code#1325]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello!

I wanted to have a look at MIMIC-IV v2.0 in Postgres, but noticed there wasn't currently sql code to take the latest changes into account. I've modified the `create.sql` and `load_gz.sql` files to reflect these changes and managed to populate the database, but wondered if you'd like me to submit a pull request for these changes to benefit everyone? Presumably people will be using v1.0 for some time, so perhaps there is benefit in separate sub-directories for v1.0 and v2.0? 

As for `index.sql` and `constraint.sql`, I guess a little more info on how the `ingredients` and `omr` tables relate to other tables would be beneficial. 

Thanks very much for your fantastic database and continued work, it's of enormous benefit!

**Comment by alistairewj** [comment]
Thanks for the offer! I know @alexmbennett2 already has a version that's working: https://github.com/alexmbennett2/mimic-code/tree/mimic_iv_postgres_create_updatev2

@alexmbennett2 do you mind making a PR? And if you see any omissions there feel free to point them out.

**Comment by aegis301** [comment]
Hello, thank you so much for this update! I was wondering, is there also already and update available for the [concepts folder](https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/concepts/postgres) or can these be used without adjustments to V2.0?

Thank you so much for your work!

**Comment by alistairewj** [comment]
I've actually rerun them almost as-is - maybe one change in the age table? If you resign the DUA on PhysioNet and request access to BigQuery again, you'll see *new* schemas: mimiciv_hosp, mimiciv_icu, and mimiciv_derived. Plan to make a PR relatively soon and release a new version.

**Comment by alistairewj** [comment]
Closed by #1336, and the new releases (v2.2.1 onward) have MIMIC-IV v2.0 compatible build/concepts.
