### ISSUE TITLE
Trouble accessing physionet

### ISSUE THREAD

**Issue by sleelam** [MIT-LCP/mimic-code#1342]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
Access to data
I am a doctor based in England helping with database query. I am unable to create a physionet account despite multiple attempts (no activation email, likely due to server being down), and believe this issue is recurring for physionet. I have a Good Clinical Practice certificate, and was wondering if I would be able to access the database by directly signing the data sharing agreement with the team or some other way?

**Comment by tompollard** [comment]
@[sleelam](https://github.com/sleelam) Our servers are currently undergoing maintenance (as of yesterday) and this is affecting our mailservers, which may explain why you haven't received the emails. 

Short answer is that it is not possible to sign a data use agreement outside the system. We are a small research team supporting ~30k of users, so setting up individual agreements isn't manageable. Please drop us an email at contact [at] physionet.org and we can look into why you you've been unable to create an account.

**Comment by tompollard** [comment]
(You can also email me at tpollard@mit.edu - might be quickest)

**Comment by tompollard** [comment]
The issue with the mail server is now resolved and most queued emails should have been resent. If you do not receive the emails, please get in contact us with us and we will get your account activated.
