### ISSUE TITLE
Confusion over expire_flags

### ISSUE THREAD

**Issue by rustyBilges** [MIT-LCP/mimic-code#135]
I believe this is just an issue with the documentation at. 

In the table description for PATIENTS it states that expire_flag indicates in hospital death.
It appears instead to show whether a dod is recorded at all (either in hospital or after discharge).
So it is different from hospital_expire_flag in the ADMISSIONS table.

Sorry if everyone knows this already! Just thought I'd bring it up since the documentation was confusing.

**Comment by alistairewj** [comment]
That's a good catch - thanks. I've fixed it now. You might also be interested to know that the website is open source and you can make issues or PRs related to the website on that repo: https://github.com/MIT-LCP/mimic-website
