### ISSUE TITLE
Pnuemonia

### ISSUE THREAD

**Issue by Edakksm** [MIT-LCP/mimic-code#1351]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I am looking for patients who had Pnuemonia. But when I run the following query, I dont get anything back:
d_diag[d_diag['ICD9_CODE'].isin([480,481,482,483,484,485,486,487])]

I searched for Pnuemonia in Issues, but I didn't get anything back

Description of the issue, including:
* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by marymlucas** [comment]
I've run into this before both when writing SQL queries against the database and reading the CSV files into Pandas.  Those diagnosis codes are likely in string format, not numerical.  So maybe try:   
`d_diag[d_diag['ICD9_CODE'].isin(["480","481","482","483","484","485","486","487"])]`

**Comment by Edakksm** [comment]
Thanks a lot @marymlucas ! It works now
