### ISSUE TITLE
Duplicate Diagnoses in MIMIC-IV and MIMIC-IV-ED

### ISSUE THREAD

**Issue by VoyagerWSH** [MIT-LCP/mimic-code#1352]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, I noticed that there are some stays in MIMIC-IV-ED had duplicate diagnoses. For example, in the ed_diagnoses dataset, `stay_id` 31336201 had 8 ICD codes associated with it, and 7 of them are exactly the same. This result can be reproduced as follow:
```
ed_diagnoses = pandas.read_csv(mimic_iv_ed_v2_path + 'diagnosis.csv.gz')
ed_diagnoses[ed_diagnoses['stay_id'] == 31336201]
```
There are 249 `stay_id` in MIMIC-IV-ED that have duplicate diagnoses like this. Such behavior is also found in the `hosp` module of MIMIC-IV dataset, and there are 321 `hadm_id` with duplicate diagnoses. 
Is there a reason to include the same diagnoses multiple times? Can we just drop the duplicated ones for analysis? Thanks a lot!

**Comment by alistairewj** [comment]
I verified that these duplicate codes exist in the raw data, so given the infrequency, it is probably just coding error that you would expect in real world data (<0.1%! not bad!). Dropping the duplicates make sense.

**Comment by VoyagerWSH** [comment]
Got it. Thanks!
