### ISSUE TITLE
Missing subject_id in the omr module

### ISSUE THREAD

**Issue by VoyagerWSH** [MIT-LCP/mimic-code#1355]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

In MIMIC-IV v2.0, an `omr` module is included that has miscellaneous information about an individual's health. We found that there are 32,282 `subject_id` in the MIMIC-IV dataset that does not appear in the `omr` module, and similarly, 57,658 `subject_id` in the MIMIC-IV-ED dataset that does not exist in the `omr` module. 
We have two questions: 
- Is there a reason that some patients have miscellaneous information recorded for their visits and some don't? 
- What are the differences between these two groups of patients? 

Here are some code to reproduce the numbers in python. Thanks in advance!
```
from matplotlib_venn import venn3
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure
import pandas as pd

# read the datasets 
omr = pd.read_csv(omr_path)
ed_stays = pd.read_csv(ed_stays_path)
ed_diagnoses = pd.read_csv(ed_diagnoses_path)
admissions = pd.read_csv(admissions_path)

# get the unique subject_id in each dataset
omr_pts = set(omr['subject_id'])
adm_pts = set(admissions['subject_id'])
ed_pts = set(ed_stays['subject_id']) | set(ed_diagnoses['subject_id'])

# plot a venn diagram for visualization
figure(figsize=(8, 8), dpi=600)
venn3([omr_pts, adm_pts, ed_pts], ('OMR', 'MIMIC-IV', 'MIMIC-IV-ED'))
plt.show()
```

**Comment by alistairewj** [comment]
Only around ~5 concepts exist in the *omr* table at this time. More than likely, those subjects simply do not have any height/weight/BMI/blood pressure/eGFR measurements within 1 year of their hospitalization.

**Comment by VoyagerWSH** [comment]
I see. Thanks!

Do you have any suggestion on how to link a `hadm_id` or `stay_id` to the appropriate height/weight/BMI/blood pressure/eGFR measurements? These are time-varying measurements but the `omr` table does not have any identifier other than `subject_id`, and the `chartdate` variable in `omr` does not occur during their admission in many cases.

**Comment by alistairewj** [comment]
Typically, you'd take the latest value that occurred before the hospitalization. That is the way the measurements would be used clinically, anyway.

**Comment by VoyagerWSH** [comment]
I see. Thank you!

**Comment by justinrporter** [comment]
Can you clarify--does the `omr` table include _only_ outpatient measurements? If so, where might one find inpatient heights, weights, BPs, etc?

If not, this seems like a pretty unrealistically large number of people who were admitted to the hospital but who never got vital signs, height, weight, or a BMP obtained... (ie perhaps there is some other issue?)
