### ISSUE TITLE
MIMIC-III: Multiple ICD-9 versions used for the assigned diagnosis codes

### ISSUE THREAD

**Issue by JoakimEdin** [MIT-LCP/mimic-code#1359]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

During 2001 and 2012, there have been annually released ICD-9 versions adding, editing and deleting codes. An overview of the addends can be found in [this document](https://www.cdc.gov/nchs/data/icd/ICD-9-CM_FY14_CNVTBL_Final.pdf). I work with automatic medical coding and multiple ICD-9 versions in the same data will increase the errors in machine learning models. I was curious whether the ICD-9 codes had been updated during the 2001-2012 period in the MIMIC III data. 

A medical coder should never assign codes that are not leaves in the ICD-9 ontology tree. In 2005, 276.50 - 276.52 were added to ICD-9. Before that, 276.5 was a leaf in the ICD-9 tree. In MIMIC III, 276.5 occurs 1,294 times, 276.50 occurs 326 times, 276.51 occurs 1,347 times and 276.52 occurs 1,348 times. The fact that both 276.5 and 276.50 - 276.52 occurs so often in the dataset indicates that the coding rules were changed at the Israel Deaconess Medical Center in the time period 2001-2012.

Is it correct that there have been multiple ICD-9 versions used for MIMIC-III codes? Is it possible to find the ICD-9 code versioning for each coded note?

**Comment by alistairewj** [comment]
Yes, it is correct that multiple versions of ICD were in use at the BIDMC. Unfortunately, for MIMIC-III, we cannot tell you the version as it correlates with the admission year.

In MIMIC-IV, you can roughly approximate the version as you know the admission year +- 1. Similarly, MIMIC-IV contains all ICD codes which were valid at any time during the data collection period. If an ICD code was updated, MIMIC-IV contains the latest version. I believe MIMIC-III is the same, though MIMIC-III did not include the expired codes IIRC.
