### ISSUE TITLE
Possibly wrong data dir in instructions

### ISSUE THREAD

**Issue by mmcdermott** [MIT-LCP/mimic-code#1376]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

When running the quickstart here: https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/buildmimic/postgres
I had to make the data directory mimiciv/2.0 (e.g. `psql -d mimiciv -v ON_ERROR_STOP=1 -v mimic_data_dir=mimiciv/2.0 -f mimic-iv/buildmimic/postgres/load_gz.sql`

**Comment by alistairewj** [comment]
yep that looks like a good catch - thanks!
