### ISSUE TITLE
Add Postgres version requirement to README

### ISSUE THREAD

**Issue by tnaumann** [MIT-LCP/mimic-code#138]
The addition of queries that use `percentile_cont` move the minimum Postgres version to 9.4. Adding this to the README would result in less confusion during.

**Comment by alistairewj** [comment]
Materialized views require 9.4 too.. it might be worth adding a unit test
in the build for the version.

**Comment by tnaumann** [comment]
I think materialized view exists in Postgres 9.3 (https://www.postgresql.org/docs/9.3/static/sql-creatematerializedview.html).

A unit test would be even better. Overall idea is to give the user warning that the build is failing because of an insufficient Postgres version rather than discovering this from a slew syntax errors.

**Comment by tnaumann** [comment]
Have you tested on 9.5+? If so, we can use something like:

```
ifndef MAJORVERSION
    MAJORVERSION := $(basename $(VERSION))
endif

PG94_OR_LATER := $(shell expr $(value MAJORVERSION) \>= 9.4)
ifeq ($(PG94_OR_LATER), 0)
    $(error PostgreSQL 9.4 or later is required to build MIMIC)
endif
```

Otherwise, if it has to be exactly 9.4, we can use something like:

```
ifndef MAJORVERSION
    MAJORVERSION := $(basename $(VERSION))
endif

ifeq (,$(findstring $(MAJORVERSION), 9.4))
    $(error PostgreSQL 9.4 is required to build MIMIC)
endif
```

**Comment by alistairewj** [comment]
Yeah I use 9.5 and everything works smoothly. We can probably require>=9.4
and be fine... I think Nicolas ( @parisni ) may have even built it on 9.6.
