### ISSUE TITLE
suggest to add time to the rrt materialized view

### ISSUE THREAD

**Issue by zh-zhang1984** [MIT-LCP/mimic-code#139]
the rrt materialized view only gives information on whether the patient is on RRT or not, I also would like to know the time of first initiation of rrt, is that possible? I'm looking forward to this revised version.

**Comment by alistairewj** [comment]
A new CRRT view is in the process of being built. I'll close this when it's uploaded. It will only be CRRT, not general dialysis.

**Comment by alistairewj** [comment]
There is an RRT view with time now in the [treatment folder](https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/concepts/treatment) - https://github.com/MIT-LCP/mimic-code/blob/61ae77e1e803255ba56782b14699f0415dcae9f9/mimic-iv/concepts/treatment/rrt.sql
