### ISSUE TITLE
Negative (and excessive) quantities in IOEVENTS table

### ISSUE THREAD

**Issue by vjm261** [MIT-LCP/mimic-code#14]
I have found instances (> 5,500 in a subgroup of ~1 million rows) of negative `VOLUME` fields within the IOEVENTS table. An example is 250 mL of free water being ordered (`ORDERID` = 1757275) and the actual volume is -7250 mL - I cannot think of any reason for such a difference in volume or the different sign.

![image](https://cloud.githubusercontent.com/assets/14168103/10671398/55c42e54-78b8-11e5-9f7e-d1a209cac686.png)

A very common `ITEMID` is 225183 which represents the current goal of dialysis which makes up 1000s of cases by itself. 

I think that every in or out should be positive and distinguishable, as IN or OUT, in some other manner. I've been using the existence of an `ORDERID` to represent INs. Perhaps the negative values can be corrected in the next release.

**Comment by rgmark** [comment]
Are we sure they were not dialysis patients?
R

Roger G. Mark, M.D., Ph.D.
Professor of Health Sciences and Technology
   and of Electrical Engineering
Room E25-505
MIT
Cambridge, MA 02139
Tel 617-253-7818
Fax 617-258-7859

**Comment by vjm261** [comment]
They probably are but is there a reason for the item to have a negative volume?

**Comment by rgmark** [comment]
During dialysis it is necessary to remove volume.
R

On 10/22/2015 3:53 PM, vjm261 wrote:
>
> They probably are but is there a reason for the item to have a 
> negative volume?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MIT-LCP/mimic-code/issues/14#issuecomment-150337825>.
>

-- 
Roger G. Mark, M.D., Ph.D.
Professor of HST and EECS
Massachusetts Institute of Technology
Room E25-505
Tel - 617-253-7818
Fax - 617-258-7859

**Comment by alistairewj** [comment]
As Roger has eluded to, this seems to be what the raw data looks like. We are not in the business of modifying the raw data, though I agree with you that it's a bit confusing to have a negative volume input instead of a positive volume output (which is used elsewhere). Dialysis was a bit of a tricky case in the new version, where we have INPUTEVENTS_MV and OUTPUTEVENTS, and I'd be interested if you find anything unusual about this data in the future. For now I'll close this though.

**Comment by vjm261** [comment]
I have been looking into the fluids in and out for dialysis patients (without an infection) using ICD-9 codes and I have found that the negative fluids in do not correspond to anything that might resemble dialysis. 
The `ITEMID`s of negative fluid values (with unit of mL) I have found in a subgroup are:

>
225158,"NaCl 0.9%",
220949,"Dextrose 5%"
225943,"Solution",
225828,"LR",
220970,"Fresh Frozen Plasma"
225944,"Sterile Water"
226089,"Piggyback"
225159,"NaCl 0.45%"
225936,"Replete with Fiber (Full)"
227522,"KCL (Bolus)"
226361,"Pre-Admission Intake"
>

I suggest for each user to take the absolute value of the column to remove the negative signs.

**Comment by rgmark** [comment]
Sounds right to me!

Roger

Roger G. Mark, M.D., Ph.D.
Professor of Health Sciences and Technology
   and of Electrical Engineering
Room E25-505
MIT
Cambridge, MA 02139
Tel 617-253-7818
Fax 617-258-7859

**Comment by tompollard** [comment]
@vjm261 where possible please could you post your query as part of the issues to help us when looking into them? I have taken a very brief look at negative volumes in the inputevent tables in MIMIC-III v1.3. Most appear to be associated with cancelled orders.

1. There are no negative amounts in the inputevents_cv (carevue) table:

``` sql
select count(*) 
from inputevents_cv 
where amount < 0;
-- count = 0 rows
```

2. There are 5582 negative amounts in inputevents_mv (out of a total of 3618991 amounts). Almost all of these appear to be associated with cancelled orders:

``` sql
SELECT count(*) 
FROM inputevents_mv 
WHERE amount < 0;
-- count = 5582 rows 

SELECT count(*) 
FROM inputevents_mv 
WHERE amount < 0 
AND CANCELREASON < 1;
-- count = 20 rows
```
