### ISSUE TITLE
the code-status returned no rows

### ISSUE THREAD

**Issue by zh-zhang1984** [MIT-LCP/mimic-code#140]
the code_status materialized view returned no row in its current version. 
It reports as follows: 
"Query returned successfully: 0 rows affected, 121 msec execution time."

**Comment by tompollard** [comment]
@zh-zhang1984 please could you add a little more detail to your issue? It would helpful to:
- have a link to the script that you are trying to run
- details of your MIMIC version (e.g. MIMIC-III v1.4)
- details of the your database system (e.g. Postgres v9.3)

**Comment by alistairewj** [comment]
It sounds like your materialized view is created. The query creates a view,
but does not return any output. Try to select from the resulting view:
`select * from code_status`

**Comment by zh-zhang1984** [comment]
yes, I use the select from code, but it returned no row, it's an empty table. 
I'm using MIMIC-III V1.4
THE DATAbase system is pgadmin 1.22.1

**Comment by alistairewj** [comment]
There was a typo in the drop statement, but I don't know if that will fix the issue. Try run it again. If you still have no data, could you try executing the query in psql using `\i`?

**Comment by zh-zhang1984** [comment]
I can manage to extract these information. Many thanks for your confirmation.
