### ISSUE TITLE
hospital_expire_flag = 1, BUT deathtime = null (MIMIC-IV 2.0)

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#1406]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Before everything I want to say I am very happy that you managed to implement out-of-hospital mortality in version 2.0, thank you.

One strange behavior is the existence of admission with a hospitalization mortality flag and no deathtime, I think this is a mistake.

In BigQuery, this result with 13 rows:
```
SELECT hadm_id, deathtime, hospital_expire_flag  
FROM `physionet-data.mimiciv_hosp.admissions` 
WHERE hospital_expire_flag = 1 AND deathtime IS NULL
```

**Comment by alistairewj** [comment]
The source of `hospital_expire_flag` and `deathtime` are two distinct columns. `hospital_expire_flag` is from a yes/no field, whereas `deathtime` requires the time of death to be recorded. Looks like they are inconsistent for a very small number of patients. No way for us to tell you which one is correct, sorry! Probably this will be obvious when the notes are released and you can check the discharge summaries for those patients.
