### ISSUE TITLE
No 'mimic_core' project on BigQuery

### ISSUE THREAD

**Issue by shi-ang** [MIT-LCP/mimic-code#1410]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I‘ve been granted access to both MIMIC-III and MIMIC-IV via BigQuery following the instructions ([here](https://mimic.mit.edu/docs/gettingstarted/cloud/bigquery/)). As your instruction said:

> You should now see a number of projects (MIMIC-III: `eicu_crd_demo`, `mimiciii_clinical`, `mimiciii_demo`, `mimiciii_notes`, `mimiciii_derived`, MIMIC-IV: `mimic_core`, `mimic_icu`, and `mimic_hosp`). 

I can see all the projects except `mimic_core`. Here is a snapshot of my BigQuery. 
![Screenshot from 2022-10-26 15-32-51](https://user-images.githubusercontent.com/43018499/198144100-c6f75f7a-6ebc-43bf-980a-d2dd8eb214de.png)

Could you please guide me on which step I was missing to get the "mimic_core" item? 

Alternatively, if that project no longer exists, is there a SQL script for me to build the project?

**Comment by tompollard** [comment]
@shi-ang Please see the MIMIC-IV release notes at: 
https://physionet.org/content/mimiciv/2.0/#release-notes

> # Major changes
- The core module has been removed to simplify the schema. The admissions, patients, and transfers tables are now in the hosp module.
- Neonates have been removed from the dataset. Neonatal data will be released in a separate project with data from the neonatal intensive care unit.

We'll update the documentation at: https://mimic.mit.edu/docs/gettingstarted/cloud/bigquery/ (@SichengH please could you have a go at this?)

**Comment by shi-ang** [comment]
Thanks!
