### ISSUE TITLE
MIMIC-III inaccessible - no one is verifying CITI training

### ISSUE THREAD

**Issue by adib2149** [MIT-LCP/mimic-code#1416]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

---
 
I am trying to regain access to the MIMIC-III dataset, for which I completed and submitted “CITI Data or Specimens Only Research Training” on Oct 18, 2022. 

1. Till now, it has been saying “under review,” for the last 16 days ago, and I cannot get access to the dataset. 
2. I also opened a ticket titled “Delay in checking CITI certifications 217 - Created on Mon, 24 Oct 2022 at 03:26 PM - via Portal” in PhysioNet Support Desk, which hasn’t been addressed. 
3. I emailed "contact@physionet.org," but the email bounced back; no one is receiving emails at that address.

I am unsure whom to reach out to if the support desk is not helping. **_Is there anyone who can help in resolving this issue?_** It’d be a great help since I am unsure where to reach out next. Thanks in advance.

**Comment by adib2149** [comment]
Closing the issue, for now, they had lots of requests for data access, and it was just pending for a long time. Thank you.

**Comment by Junelin2333** [comment]
Hello, I have the same problem with you. Have you gotten access to the dataset? How long have you been waiting?
I see there are somebody waiting for more than a month (include myself). This is really quite anxious for me...

Thank you!

**Comment by adib2149** [comment]
Yeah, as I replied above, they had lots of requests for data access, and they just cleared my one later. Sorry but I guess you have to wait a bit. I can open the ticket for now for visibility.

**Comment by tompollard** [comment]
I think the credentialing team are mostly caught up now, so I'll close this issue. If an application is sitting around for more than a couple of weeks, most likely the credentialing team are waiting to hear from a reference. We are working to streamline the credentialing process.
