### ISSUE TITLE
The numer of rows affected by MIMIC IV 2.1 update are not correct

### ISSUE THREAD

**Issue by hlblade** [MIT-LCP/mimic-code#1426]
Hi,
As mentioned from Physionet web

1. patients - Removed 15,748 subject_id from the table
2. admissions - Removed 23,093 hadm_id from the table.
3. icustays - Removed 3,762 stay_id from the table.

But what we can get from the previous and current validate.sql:

- SELECT 'admissions' AS tbl, 431088 AS row_count UNION ALL
- SELECT 'patients' AS tbl, 299777 AS row_count UNION ALL
- SELECT 'icustays' AS tbl, 73141 AS row_count UNION ALL

- SELECT 'admissions' AS tbl, 454324 AS row_count UNION ALL
- SELECT 'patients' AS tbl, 315460 AS row_count UNION ALL
- SELECT 'icustays' AS tbl, 76943 AS row_count UNION ALL

315460-299777=15683
454324-431088=23236
76943-73141=3802

Anything wrong?

**Comment by alistairewj** [comment]
Yes, I think I made a mistake :) There will be a 2.2 shortly. Nothing fundamentally wrong with the data, I just filtered out the wrong set of `subject_id`.

**Comment by alistairewj** [comment]
New release of v2.2 so this is now fixed/no longer an issue.
