### ISSUE TITLE
Negative death time for some patients

### ISSUE THREAD

**Issue by shi-ang** [MIT-LCP/mimic-code#1427]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hi,

I found that there are very few patients associated with negative death time from ICU recruitment. This death time from ICU recruitment is calculated by using `icu_intime` minus the `dod` from the `mimic_derived.icustay` file on BigQuerry. I'm wondering if it is the correct way to calculate such a value or if I've made a mistake by assuming the `icu_intime` should always happen earlier than the `dod` time.

The SQL code (for MIMIC-IV v2.0) to reproduce some patients with negative death time on BigQuerry: 
```
SELECT
TIMESTAMP_DIFF(icu_detail.dod, icu_detail.icu_intime, HOUR) / 24 as time_to_death,
icu_detail.dod,
icu_detail.icu_intime
from `physionet-data.mimiciv_derived.icustay_detail` icu_detail
where
icu_detail.subject_id = 14150625 or icu_detail.subject_id = 10590985 or icu_detail.subject_id = 13260040
```

**Comment by alistairewj** [comment]
This might be because you are comparing a date (`dod`) with a timestamp (`icu_intime`). If someone dies on the same day they are admitted, then it would appear as if they died before being admitted. You could try truncating `icu_intime` to the day, and only calculating integer days of death.

**Comment by shi-ang** [comment]
I appreciate you reply very much.

However, it is not necessary the case. If you run the SQL code above, you will get the following query results:
![Screenshot from 2022-12-21 16-19-38](https://user-images.githubusercontent.com/43018499/209021872-3c5bec7b-fd85-446d-a2cf-03def47e577a.png)
For these three patients, the `dod` is ahead of `icu_intime` by a few years. 

And there are more of them in the database...

**Comment by alistairewj** [comment]
How many more? We don't "fix" data as a policy, so if it's a few cases, then it's just bad data, but if it's many cases, then it may be a systematic error in a data source or our process.

**Comment by shi-ang** [comment]
In total there are 5 cases. So I just dropped them from the dataset.

**Comment by alistairewj** [comment]
Got it, yep, good to keep an eye out for these inconsistencies!

**Comment by KimballCai** [comment]
but I found 25 cases. The subject ids are [10554954, 11042406, 11660628, 12207593, 12376923, 12393516, 12921133, 13078944, 15018122, 15190414, 15246174, 15831207, 15834858, 16467939, 16533974, 17536748, 17631949, 17906419, 17955142, 18839671, 19107535, 19379644, 19547124, 19752788, 19914761].

The intime in their ICU records are later than their deathtime.
