### ISSUE TITLE
what is the different between concepts folder and concepts_postgres folder

### ISSUE THREAD

**Issue by huangzhuohua** [MIT-LCP/mimic-code#1430]
as we can see two concepts relevant folders in this path /mimic-code)/mimic-iv/
what is the different between **_concepts_** folder and **_concepts_postgres_** folder?
if i use postgresql as my database, which is my choice to make concepts ?

**Comment by alistairewj** [comment]
If you are using postgresql, then use the concepts_postgres folder. The concepts_postgres folder is automatically generated from the scripts in the concepts folder. They are identical in logic, just some syntax differences between BigQuery SQL (concepts) and PostgreSQL (concepts_postgres).
