### ISSUE TITLE
Is there a way to access to procedural ICD codes ?

### ISSUE THREAD

**Issue by snowgato** [MIT-LCP/mimic-code#1451]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hi,
I'd like to determine wether patients had or not cerebral aneurysm coiling.
For ICD9, the code would be 39.75 or 39.76 and for ICD10 it would be 03VG3DZ.
Actually, these codes don't belong to mimic IV.
Is there some way to establish if someone had cerebral aneurysm  coiling ?
Thanks !

sting the titles and ICD codes held within 
Description of the issue, including:
* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by marymlucas** [comment]
@snowgato try the procedures_icd table in the mimiciv_hosp module?  For example on BigQuery:

select * from `physionet-data.mimiciv_hosp.procedures_icd` where icd_version = 9 and icd_code like '%3975%' limit 100;

**Comment by snowgato** [comment]
That works perfect,
Thanks very much for your help !
RTFM :-)
