### ISSUE TITLE
Load data error with MIMIC-IV v2.2

### ISSUE THREAD

**Issue by XinghaoZhuang** [MIT-LCP/mimic-code#1466]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hi, MIMIC-IV v2.2 was released in Jan. 6 2023. However, the MIMIC Code Repository hasn‘t updated for this version. So I went with the following error: 
![img_v2_4ccbc708-9d5f-4d1d-a9cf-80f966e8357g](https://user-images.githubusercontent.com/20808210/211744573-5b4556b3-43b4-412c-a925-25d018976249.jpg)
![image](https://user-images.githubusercontent.com/20808210/211744684-dadfebcd-b527-41c7-b7bb-2410e61f41a8.png)
When will MIMIC-Code update for MIMIC-IV v2.2?

Thanks

**Comment by schu** [comment]
The branch `mimiciv_v2.2_updates` (https://github.com/MIT-LCP/mimic-code/tree/mimiciv_v2.2_updates) contains the necessary updates and worked for me (PostgreSQL 14.3 on Fedora).

**Comment by XinghaoZhuang** [comment]
@schu  Thanks a lot!

**Comment by schu** [comment]
> ... worked for me

Addendum: to make the Postgres concepts, I used #1468
