### ISSUE TITLE
Bug in Elixhauser query / depression?

### ISSUE THREAD

**Issue by matthieukomorowski** [MIT-LCP/mimic-code#147]
Hi there,
When running the **elixhauser-quan** SQL query, I get 30 records with erroneous values in the column 'depression'. Instead of being 0 or 1, these values are all above 200,000 and located on rows 2000, 3999, 5998, 7997, 9996, etc (in regular increments of 1999 rows).
Any idea why this is happening?
Thanks,
Matthieu

**Comment by tompollard** [comment]
Hey Matthieu, I just built a elixhauser-quan view with the following script in MIMIC-III v1.4:
https://github.com/MIT-LCP/mimic-code/blob/master/comorbidity/postgres/elixhauser-quan.sql, but I'm not able to replicate this issue:

```
SELECT DISTINCT(depression) 
FROM elixhauser_quan;

depression 
------------
          1
          0
```

Could you try rebuilding the view?

**Comment by matthieukomorowski** [comment]
Thanks Tom, I figured it out. It's a bug that occurs when opening the csv file in Excel, related I believe to NaNs. It's fine if I don't use Excel.

**Comment by tompollard** [comment]
Thanks, glad you solved it.
