### ISSUE TITLE
Port and build path in Docker instructions

### ISSUE THREAD

**Issue by florinb** [MIT-LCP/mimic-code#148]
In both Step 1 and 2 the `cd /mimic_code/buildmimic/postgres` is used when instead it should be, imho, `cd /mimic_code/buildmimic/docker`.

Also, shouldn't the second example from Step 3 use port **5432** instead **5455**? I assume the example is based on a custom configuration that doesn't match the current db config.

**Comment by tompollard** [comment]
This issue refers to: https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/docker

**Comment by alistairewj** [comment]
Little slow but I fixed it. My memory is hazy but I'm pretty sure the docker port has to be 5432, but the host port is whatever you decide (e.g. in that config it was 5455). So the 5455:5455 is wrong, but 5455:5432 would be correct. I'm sure 5432:5432 would work as well, but might prevent you from connecting to any local postgres databases you might have so I wouldn't recommend it.
