### ISSUE TITLE
Deriving Charlson Comorbidity

### ISSUE THREAD

**Issue by RayRuizhiLiao** [MIT-LCP/mimic-code#1491]
Is "E10l" a typo as an ICD-10 code for diabetes without chronic complication?

https://github.com/MIT-LCP/mimic-code/blob/81deb222071cd25f861fdb817fec3adda3c43c21/mimic-iv/concepts/comorbidity/charlson.sql#L178

Should it be E101? https://www.icd10data.com/ICD10CM/Codes/E00-E89/E08-E13/E10-

**Comment by alistairewj** [comment]
Looks that way! Good catch.
