### ISSUE TITLE
Encoding issue for CHARTEVENTS_DATA_TABLE.csv's uom column?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [MIT-LCP/mimic-code#15]
When I open `CHARTEVENTS_DATA_TABLE.csv`  I see from lines 520 to 524:

```
327,23,124321,234044,220179,21-OCT-2157 21:40:00,21-OCT-2157 21:43:00,19050,"100",100,"mmHg",0,0,"",""
1,23,124321,234044,223761,21-OCT-2157 12:05:00,21-OCT-2157 12:05:00,16978,"95.8",95.8,"Â¿F",0,0,"",""
2,23,124321,234044,223761,21-OCT-2157 12:05:00,21-OCT-2157 12:05:00,16978,"95.8",95.8,"Â¿F",0,0,"",""
3,23,124321,234044,223761,21-OCT-2157 12:05:00,21-OCT-2157 12:05:00,16978,"95.8",95.8,"Â¿F",0,0,"",""
4,23,124321,234044,220045,21-OCT-2157 12:06:00,21-OCT-2157 12:08:00,16978,"77",77,"bpm",0,0,"",""
```

`Â¿F` looks like some encoding issues.

In Postgresql, in which I imported MIMIC using the tutorial, I see `¿F`: 

![image](https://cloud.githubusercontent.com/assets/15331/10681955/52c47476-78fd-11e5-979e-42dbb715d8b0.png)

**Comment by tompollard** [comment]
Hey Franck, thanks for highlighting this. This is an issue that exists in the raw data provided to us by the hospital. 

There are a small number of non-ascii characters that were lost when the data exported. In your example, "°F" has become "¿F". 

For more detail, see: https://github.com/MIT-LCP/mimic-iii-building/issues/78 

```
select *
from d_units
where unitname like '%¿%'

56  ¿mol   0.000001
59  ¿C 1.8
60  ¿F 1
157 ¿mol/24hr  1
212 ¿L 0.001
246 ¿m 0.000099999997
302 Cells/¿L   0.001
372 ¿g/L   0.0000099999997
377 ¿mol/L 0.000001
387 ¿g/dl  1000
394 ¿U/ml  0.000001
404 ¿M^3   1
407 ¿g/L/hr    1
```

**Comment by Franck-Dernoncourt** [comment]
Thanks!
