### ISSUE TITLE
add NOTEEVENTS placeholder in the demo mimic 3 clinical database

### ISSUE THREAD

**Issue by florinb** [MIT-LCP/mimic-code#150]
I recently downloaded the mimic 3 demo dataset and worked with it to create a sample database using the instructions from https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/docker

The problem I’ve encountered with the above instructions for that set is related to the missing NOTEEVENTS table. I am aware that the table is explicitly excluded from dataset but I’d like to suggest to include an empty file with just the header row as a placeholder for it. This way the checks for correctly creating the database put in place for the docker version (and postgres) will pass.

**Comment by tompollard** [comment]
thanks @florinb, we have added an empty placeholder as suggested.
