### ISSUE TITLE
MIMIC-III database set up issues

### ISSUE THREAD

**Issue by aditya-joshi-hl7** [MIT-LCP/mimic-code#151]
Hello,

I am setting up MIMIC-III database by uploading all 26 csv files in MySql database. After uploading few of the tables, we realize that it is huge data and probably storing in local system won’t be feasible. Also, simple queries like count(*) taking around an hour for big tables (with csv size greater than 500MB). It seems that roughly there are 300+ million records in entire MIMIC-III tables. 

Could you please help in letting us know what is _minimum or sufficient system requirements_ in order to upload and play with MIMIC data. We want to know about **_hardware requirements to hold this data and to query efficiently_**. It would be great help as we would be then able to setup things quickly and it will help us in our research work. As of now we are using MySql db to store and query this data. 

Regards,
Aditya Joshi
Senior Team Lead- Digital Health

**Comment by tompollard** [comment]
Hi Aditya, you shouldn't need a super high performance computer to install MIMIC. A system with a recent CPU, 8GB RAM, and 80GB free disk space (preferably solid state) should be fine. I run MIMIC in Postgres 9.5 on a 2 year old MacBook Pro, which has I5 CPU, 8GB of RAM, solid state drive.

**Comment by aditya-joshi-hl7** [comment]
Thanks, I am able to setup MIMIC-III db at my local system, i have used Postgres as db.
