### ISSUE TITLE
Cause of Death in MIMIC-IV

### ISSUE THREAD

**Issue by JBarsotti** [MIT-LCP/mimic-code#1543]
### Description

I apologize greatly if this question has already been answered somewhere, and feel free to chastize me if it has. Is there any data on the cause of death for patients who died outside the hospital (i.e., they have a date of death but not a hospital expiration)?

**Comment by alistairewj** [comment]
No worries! There isn't currently any cause of death data available. The source for that data would be the CDC, which charges for data access (a charge that adds up when multiplied by 60,000 patients). We source out of hospital death from a state database which only has the date of death.

**Comment by JBarsotti** [comment]
Thank you so much for your reply! That makes sense!
