### ISSUE TITLE
How to download the MIMIC-II dataset?

### ISSUE THREAD

**Issue by Zkx199800** [MIT-LCP/mimic-code#1547]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
* What are the specific steps to download the MIMIC-II dataset

**Comment by alistairewj** [comment]
The instructions are here: https://mimic.mit.edu/docs/gettingstarted/

Please re-open if there is a specific step you are having difficulty with.

**Comment by Zkx199800** [comment]
> The instructions are here: https://mimic.mit.edu/docs/gettingstarted/
> 
> Please re-open if there is a specific step you are having difficulty with.
Thank you very much. That means it must login the website.
