### ISSUE TITLE
Patient Counts not matching between mimiciv_hosp.patients and mimiciv_hosp.admissions (and some other tables)

### ISSUE THREAD

**Issue by sourasen1011** [MIT-LCP/mimic-code#1564]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hello,

I am not sure if this is worth raising an issue for, so please feel free to mark it closed if this is the wrong channel. However, I found that of the 299,712 patients in the mimiciv_hosp.patients table, ~180,000 are present in the mimiciv_hosp.admissions table.

I tried checking the overlapping counts against a few other tables. Here are the results. So far, I have not found any other issues addressing this and I could not find anything regarding this in the documentation (_my apologies if there actually IS something present and I missed it_).

### **QUERIES**

<pre><code>	
def check_overlap(t2 , t1 = 'mimiciv_hosp.patients'):
	q_left = f'''
	select count(*) from (
	(select distinct subject_id from {t2}) hosp
	left join (select distinct subject_id from {t1}) pat
	on hosp.subject_id = pat.subject_id
		)
	'''
	q_left_res = pd.read_sql_query(q_left , engine)

	q_right = f'''
	select count(*) from (
	(select distinct subject_id from {t2}) hosp
	right join (select distinct subject_id from {t1}) pat
	on hosp.subject_id = pat.subject_id
		)
	'''
	q_right_res = pd.read_sql_query(q_right , engine)

	q_inner = f'''
	select count(*) from (
	(select distinct subject_id from {t2}) hosp
	inner join (select distinct subject_id from {t1}) pat
	on hosp.subject_id = pat.subject_id
		)
	'''
	q_inner_res = pd.read_sql_query(q_inner , engine)

	res = pd.concat([q_left_res , q_inner_res , q_right_res]).T
	res.columns = [f'left({t2})' , 'inner' , 'right(mimiciv_hosp.patients)']

	return res
</pre></code>

### **RESULTS**

<pre><code>check_overlap(t2 = 'mimiciv_hosp.labevents')</pre></code>

| left(mimiciv_hosp.labevents) | inner | right(mimiciv_hosp.patients)|
|---|----|----|
255876 | 255876 | 299712

<pre><code>check_overlap(t2 = 'mimiciv_hosp.admissions')</pre></code>
|left(mimiciv_hosp.admissions)|inner|right(mimiciv_hosp.patients)|
|---|---|---|
|180733|180733|299712|

<pre><code>check_overlap(t2 = 'mimiciv_hosp.diagnoses_icd')</pre></code>
|left(mimiciv_hosp.diagnoses_icd)|inner|right(mimiciv_hosp.patients)|
|---|---|---|
|180640|180640|299712|

<pre><code>check_overlap(t2 = 'mimiciv_hosp.procedures_icd')</pre></code>
|left(mimiciv_hosp.procedures_icd)|inner|right(mimiciv_hosp.patients)|
|---|---|---|
|121891|121891|299712|

**Comment by mlbernauer** [comment]
Not 100% sure but I suspect this may be because not all patients get admitted so they may exist in the `hosp.patients` table but _not_ in `hosp.admissions`
