### ISSUE TITLE
Is the code that performs date shifting available?

### ISSUE THREAD

**Issue by sloboy** [MIT-LCP/mimic-code#1572]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I am trying to deidentify healthcare data similar to how MIMIC prepared its data.  Is the algorithm that randomly shifts dates and deidentifies DOB of those aged 89 or greater available?

**Comment by alistairewj** [comment]
No it's not available, but it's not complicated. It's a random offset from a fixed point of time in the patient's stay.

We no longer deidentify DOB per se (it was confusing for a lot of past users). Instead, we provide the age at their first hospital admission (roughly) and if an age is > 89, we set it to 90.

**Comment by sloboy** [comment]
TY for the quick response.  I was looking to borrow a shortcut, but I will implement my own.  You are right it is not complicated.

**Comment by alistairewj** [comment]
Just be sure to use a cryptographically secure shift, and don't roll your own! Good luck!
