### ISSUE TITLE
admittime less than edouttime?

### ISSUE THREAD

**Issue by aditya-joshi-hl7** [MIT-LCP/mimic-code#159]
Hello,

I have one doubt regarding edouttime and admittime in Admissions table. 

subject_id | hadm_id | admittime| dischtime | edregtime | edouttime
------------ | -------------| -------------| -------------| -------------| -------------
22 | 165315 | (day 0) ~ 12:26:00 | (day 1) ~ 15:54:00| (day 0) ~ 10:06:00| (day 0) ~ 13:24:00

Patient first admitted to Emergency department at 10:06 and discharge or out from ED at 13:24.
But admission time (I suppose this is the time when patient got admitted in ward/ICU or simply in inpatient department) is 12:26 pm. So, admit time in inpatient department is less that out time of emergency department, how? Please explain. Kindly help in understanding this. I have seen few more records where admittime is less than eduouttime. 

Regards,
Aditya Joshi

**Comment by tompollard** [comment]
The order of the date/times in this case is:

1. edregtime: patient registered in emergency department system
2. admittime: patient registered in hospital system
3. edouttime: patient discharged in emergency department system
4. dischtime: patient discharged in hospital system

This seems reasonable. The patient (1) arrived in the emergency department, (2) was added to the hospital system a little later, (3) was discharged from the emergency department, presumably being transferred to intensive care (4) was later discharged from the hospital.
