### ISSUE TITLE
Question about dialysis

### ISSUE THREAD

**Issue by heisenbug-1** [MIT-LCP/mimic-code#1601]
Hello. I have a question regarding the dialysis table in mimiciv_derived.rrt

I'm using the following query to extract stay_ids of patients that got a continuous heparin treatment  and  some kind of dialysis
`SELECT DISTINCT r.*
FROM mimiciv_derived.rrt as r, mimiciv_icu.inputevents as i
WHERE i.itemid = 225152 
AND i.ordercategorydescription = 'Continuous Med'
AND r.stay_id = i.stay_id
ORDER BY stay_id`

What do dialysis_present and dialysis_active mean? 
The first stay_id returned by this query has CRRT at 11 o'clock with dialysis_active=0 and dialysis_active=1. Isn't this contradictive?
Best regards

**Comment by alistairewj** [comment]
It could be they are transitioning from inactive to active at that charted
hour. If that's the case, then it's technically true.. albeit confusing. I
recall something like this happening when I was doing data exploration.

The goal of the present vs. active distinction is to identify when dialysis
is actually ongoing versus when dialysis equipment is in place. So for
example, a dialysis line could be in place (dialysis_present = 1), but the
patient is not currently being dialyzed (dialysis_active = 0). There were a
few items which indicated past dialysis / presence of lines so I thought it
useful to capture both. For all intents and purposes I think you can
subselect to dialysis_active = 1
