### ISSUE TITLE
Link to google account but cannot find  mimiciii_clinical, mimiciii_notes, and mimiciii_derived in bigquery

### ISSUE THREAD

**Issue by ccartermices** [MIT-LCP/mimic-code#1612]
I have accessed  to MIMIC-III and link to my google account but cannot find  mimiciii_clinical, mimiciii_notes, and mimiciii_derived in bigquery

![image](https://github.com/MIT-LCP/mimic-code/assets/39996331/cf52d7b9-8aa7-4ae7-96d0-bf7aae748fba)
![image](https://github.com/MIT-LCP/mimic-code/assets/39996331/d27c47fe-84b9-4cfe-bb00-83ba6fdd32d7)
![image](https://github.com/MIT-LCP/mimic-code/assets/39996331/3f48dbd7-dc2a-499c-b929-b64a6918b691)
![image](https://github.com/MIT-LCP/mimic-code/assets/39996331/1a287f01-4ede-42bf-a81c-252c897f79ae)

**Comment by alistairewj** [comment]
Did a refresh fix it?
