### ISSUE TITLE
I need a dataset containing each original component of SOFA score.

### ISSUE THREAD

**Issue by zh-zhang1984** [MIT-LCP/mimic-code#162]
I need a dataset containing each original component of SOFA score. How can I modify the Sofa SQL code to extract original component of the score, without "scorecomp" and "scorecalc". For example, the cardiovascular component contains the MeanBP_Min, vasopressors and the rate. for respiratory component, it should contain the PaO2 and FiO2. 
Many thanks for your help!

**Comment by aruberutou** [comment]
Hi, Zhongheng,

I think you might find what you are looking for under:

[https://github.com/MIT-LCP/mimic-code/tree/master/etc/firstday 
](https://github.com/MIT-LCP/mimic-code/tree/master/etc/firstday 
)
For example, [~/blood-gas-first-day.sql](https://github.com/MIT-LCP/mimic-code/blob/master/etc/firstday/blood-gas-first-day.sql) extracts/pivots-out PaO2, FiO2, and many more.

To adjust the time window (to get more than day 1 values), edit/remove the following line:

      and le.charttime between (ie.intime - interval '6' hour) and (ie.intime + interval '1' day)

Hope that helps!

**Comment by zh-zhang1984** [comment]
Thank you so much for your reply.
I also need the vasopressor use and its infusion rate on the first day. How can I extract such information? 
I find there is such information for SOFA score, but I can only get the calculated score.

**Comment by zh-zhang1984** [comment]
I can find it in the vasopressor-durations folder.

**Comment by aruberutou** [comment]
No problem at all. 

The source info in contained in the comments of the SOFA file:

```
-- Variables used in SOFA:
--  GCS, MAP, FiO2, Ventilation status (sourced from CHARTEVENTS)
--  Creatinine, Bilirubin, FiO2, PaO2, Platelets (sourced from LABEVENTS)
--  Dobutamine, Epinephrine, Norepinephrine (sourced from INPUTEVENTS_MV and INPUTEVENTS_CV)
--  Urine output (sourced from OUTPUTEVENTS)

-- The following views required to run this query:
--  1) uofirstday - generated by urine-output-first-day.sql
--  2) ventfirstday - generated by ventilated-first-day.sql
--  3) vitalsfirstday - generated by vitals-first-day.sql
--  4) gcsfirstday - generated by gcs-first-day.sql
--  5) labsfirstday - generated by labs-first-day.sql
--  6) bloodgasfirstdayarterial - generated by blood-gas-first-day-arterial.sql
--  7) echodata - generated by echo-data.sql
--  8) ventdurations - generated by ventilation-durations.sql
```

To your specific request, that's referred to in the following reference

`--  Dobutamine, Epinephrine, Norepinephrine (sourced from INPUTEVENTS_MV and INPUTEVENTS_CV)`

and calculated using the following section of code:

```
vaso_cv as
(
  select ie.icustay_id
    -- case statement determining whether the ITEMID is an instance of vasopressor usage
    , max(case
            when itemid = 30047 then rate / coalesce(wt.weight,ec.weight) -- measured in mcgmin
            when itemid = 30120 then rate -- measured in mcgkgmin ** there are clear errors, perhaps actually mcgmin
            else null
          end) as rate_norepinephrine

    , max(case
            when itemid =  30044 then rate / coalesce(wt.weight,ec.weight) -- measured in mcgmin
            when itemid in (30119,30309) then rate -- measured in mcgkgmin
            else null
          end) as rate_epinephrine

    , max(case when itemid in (30043,30307) then rate end) as rate_dopamine
    , max(case when itemid in (30042,30306) then rate end) as rate_dobutamine

  from icustays ie
```

**Comment by aruberutou** [comment]
...or that too. :) 
Glad you were able to find it!

**Comment by zh-zhang1984** [comment]
@aruberutou 
I see your codes are really helpful to me. I am now preparing a research work using this database. Can I also add you to the author list if it can be published as a journal paper. Without your contribution, I can never make this research done.

**Comment by aruberutou** [comment]
@zh-zhang1984 
I am happy to contribute. Please email me if you need further help with coding, analysis, or the manuscript itself. Looking forward to it.

**Comment by zh-zhang1984** [comment]
@aruberutou 
what is your email address? I can send you some of my proposal.

**Comment by aruberutou** [comment]
I just sent an email to address on file with github.

**Comment by tompollard** [comment]
@zh-zhang1984, just to clarify, the code copied into this conversation by @aruberutou was largely developed by the Laboratory for Computational Physiology, and in particular @alistairewj. For the commit history for the SOFA code, see: https://github.com/MIT-LCP/mimic-code/commits/401132f256aff1e67161ce94cf0714ac1d344f5c/severityscores/sofa.sql

**Comment by zh-zhang1984** [comment]
@tompollard Many thanks for your clarification.

**Comment by zh-zhang1984** [comment]
@tompollard ， how can I contact with him @alistairewj  ? I have a email address (aewj@mit.edu), but don't know whether it is his.

**Comment by tompollard** [comment]
@zh-zhang1984 it's probably best to email us at the support address listed at the bottom of http://mimic.physionet.org/help/
