### ISSUE TITLE
question about expire flag update  / being updated and past medical history

### ISSUE THREAD

**Issue by lkiljanek** [MIT-LCP/mimic-code#163]
Is expire flag updated as of "now" ? Or, when ? how many years after 2013 ? 2014 ? 2012 ? has it been most recently updated ?
Is it updated now for all patients ?

How about the social security deaths, is it safe to assume they are all updated at least 3 years after the MIMIC III database data migration was closed ?

**Comment by alistairewj** [comment]
The expire flag can be assumed to be valid up to 90 days after hospital admission. See here: http://mimic.physionet.org/mimicdata/datatypes/
