### ISSUE TITLE
SOFA score MIMIC-III vs MIMIC-IV

### ISSUE THREAD

**Issue by heisenbug-1** [MIT-LCP/mimic-code#1633]
Hello!
In my my understanding, the SOFA score is calculated for every hours in MIMIC-IV, however in MIMIC-III it is only calculated of the first day. Is there a reason for this?

**Comment by alistairewj** [comment]
Not really a strong reason but it's nicer to calculate SOFA on a rolling basis and then subselect it to the first 24 hours to get the first day SOFA. It makes it easy to get day 1, day 2, day 3, etc, without repeating code.
