### ISSUE TITLE
Clarify MIMIC-II deprecation and upcoming MIMIC-III deprecation on physionet.org

### ISSUE THREAD

**Issue by st--** [MIT-LCP/mimic-code#1634]
Hi, it took me a while to find #898 - would it be possible for you to add a notification box to the top and/or bottom of https://physionet.org/content/mimic-ii/2.6.0/ (where it currently just says "When using this resource, please cite ..." and "The files for this project are no longer available.") to clarify that MIMIC-II is no longer supported, and how to access the MIMIC-II subset of MIMIC-III?

**Comment by st--** [comment]
...and I just saw that MIMIC-III is also getting phased out :sweat_smile:  I'm working on reproducing some pre-existing baselines that reported results on MIMIC-II and MIMIC-III, that's why I was looking for the 'outdated' versions (rather than starting from scratch on a completely new project where looking for the latest would have made sense).

**Comment by tompollard** [comment]
> would it be possible for you to add a notification box to the top and/or bottom of https://physionet.org/content/mimic-ii/2.6.0/ (where it currently just says "When using this resource, please cite ..." and "The files for this project are no longer available.") to clarify that MIMIC-II is no longer supported, and how to access the MIMIC-II subset of MIMIC-III?

@st-- thanks for your suggestion. Now done! 

Please see: https://physionet.org/content/mimic-ii/ for the notice.
