### ISSUE TITLE
Loading into Postgre

### ISSUE THREAD

**Issue by andrewl786** [MIT-LCP/mimic-code#165]
I am building the database on my local machine (Win8 x64) and am having issues when loading CHARTEVENTS using the [postgresql instructions](https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/README-windows.md). My computer becomes non-responsive after ~2 hours, probably due to the large file size. (Smaller tables have loaded fine.) How would you recommend dealing with this issue?

**Comment by tompollard** [comment]
If the other tables are loading without issue and you have enough disk space, then a short term solution is to build the database overnight. Loading chartevents may put your system out of action for a few hours, but it should eventually complete.

**Comment by andrewl786** [comment]
I let it run for 7 hours before I had to restart my computer to regain control, but i'll let it run longer next time. Just wanted to confirm. Thanks!

**Comment by tompollard** [comment]
Ouch...that is a long time :/ If you can get hold of a solid state drive, it should significantly reduce the amount of time it takes to build and query MIMIC.

**Comment by andrewl786** [comment]
I have a SSD and 16gb RAM. Does this mean that 7 hours is abnormal and something else could be an issue?

**Comment by tompollard** [comment]
Not wildly abnormal, so I think you should stick with it. Chartevents is a big table and it can take several hours to build, so try leaving for a longer period and let us know how it goes.

**Comment by lianatascau** [comment]
Hello, I have a question. After running <make mimic> sql file, the report said that some tables failed 
tbl                      | expected_count | observed_count | row_count_check 
chartevents        |      330712483 |      263201375         | FAILED
datetimeevents     |        4485937 |        4486049 | FAILED

and other tables as well. I don't mind a faillure such in the case of datetimeevents (only a few rows)
but chartevents lost 20% of the rows (67 millions).
It is something I should expect, or there something wrong with my csv files?
Thank you. Liana

**Comment by alistairewj** [comment]
Hi @lianatascau - that's likely a separate issue deserving it's own thread - just to give you a headstart, what version of MIMIC-III did you download? Version 1.3 had ~260 million rows in CHARTEVENTS, but version 1.4 has ~330 million - that may be why your check is failing. If so I would re-download the latest version of the data.

**Comment by lianatascau** [comment]
wc -l CHARTEVENTS.csv 
263201376 CHARTEVENTS.csv
so now I am downloading 1.4
Thank you.
