### ISSUE TITLE
MIMIC III Waveform Data

### ISSUE THREAD

**Issue by jgenk** [MIT-LCP/mimic-code#166]
Apologies if this is not the right place to ask this question.

The MIMIC III Documentation points to "A separate, complementary resource named the “MIMIC-III Waveform Database” contains high resolution waveforms and numerics..." https://mimic.physionet.org/mimicdata/waveforms/

I have been able to find the MIMIC II, version 3 waveform DB.
https://www.physionet.org/physiobank/database/mimic2wdb/

After searching extensively for a MIMIC **_III_** waveform database, I am not having any luck. Does anyone know if this exists yet? Or is the most recent publicly accessible version of waveform data the MIMIC II, version 3 waveform DB?

Thank you!

**Comment by tompollard** [comment]
Hi @jgenk, thanks for posting here. The waveform database for MIMIC-III has not yet been released, but we are working on it. 

Estimating timelines is tricky because the work is being carried out alongside our research activities, so for updates please keep an eye on https://mimic.physionet.org/mimicdata/waveforms/

We will also post progress updates in this issue.

**Comment by jgenk** [comment]
@tompollard thanks so much for the quick response. I will keep an eye on the website.

And also thank you for all of the awesome work you folks do!

**Comment by tompollard** [comment]
Thanks @jgenk :) I have reopened the issue for now, so that anyone interested in the MIMIC-III waveforms can subscribe to the thread and get pinged when the data is released.

**Comment by tompollard** [comment]
Just a note that there is a related thread at: https://github.com/MIT-LCP/mimic-code/issues/86

**Comment by tompollard** [comment]
For anyone looking to match previously released waveforms to the MIMIC-III Clinical Dataset, see: https://physionet.org/physiobank/database/mimic3wdb/matched/matched_waveform_info.csv. Note that no additional waveforms have been released (we are still working on this process).

**Comment by tompollard** [comment]
Just a quick update: we are pleased to say that a new batch of matched waveforms are being uploaded to PhysioNet right now (~10k patients in total). Once the waveforms are uploaded and checked, they will be made available for analysis.

**Comment by RezaSadeghiWSU** [comment]
Dear Dr. Tom Pollard,

I am so appreciative of your great work and information. I want to work on MIMIC III Waveform Database Matched Subset. As I need (p....nm.mat, p....nm.info, p....nm.hea) files to analysis waves in MATLAB, I download these waveform information for each patient individually from PhysioBank ATM, right now. I wonder is there any possibility to download all p....nm.mat, p....nm.info, p....nm.hea simultaneously?
Also, could you please give me some information about how can I take advantage of WFDB toolbox.

Best regards,
Reza Sadeghi

**Comment by alistairewj** [comment]
The following two FAQ questions explain how to download data (should you need to! Many people do not need to download the entire database): https://www.physionet.org/faq.shtml#downloading-binaries

There is also a tutorial on how to obtain data in text form: https://www.physionet.org/tutorials/physiobank-text.shtml

Finally, it's worth noting that the matched subset symbolically links to the mimic3wdb (https://physionet.org/physiobank/database/mimic3wdb/) - so if you have downloaded the mimic3wdb you only need to download symlinks.

Since the updated MIMIC-III matched waveform database has been released, I'll close this issue.

**Comment by sarwa** [comment]
dear all

for the last 5 days i try to download (MIMIC-III Clinical Database ) for my project in WBAN
but im confuse, i can not find the link, i don't know which types of data must donload.
my project in wireless body area network , programming in OMNET++ , i need direction to how use this data in OMNET++ , how can analysis.

please friends any tips , comments i need
if there is programmer can help me also i need
hope get reply
reagrds
israa
israa44444@gmail.com

israa44444@gmail.com
--




israa44444@gmail.com
--

**Comment by sarwa** [comment]
dear freinds

i find this link
https://physionet.org/physiobank/database/mimicdb/037/

but how i can download ? individually ?
then how can use in OMNET++ ??
can somebody help me please ??
israa44444@gmail.com

**Comment by sarwa** [comment]
**hello tompollard**
please dont delete my message i need help
im phd student and need analysis the MIMIC database, i try to find your email address to contact u but can not find in your profile.
please help me
if u know good programmer can help , hope told me please

hope get reply

-------------------------------------------------
dear freinds

i find this link
https://physionet.org/physiobank/database/mimicdb/037/

but how i can download ? individually ?
then how can use in OMNET++ ??
can somebody help me please ??
israa44444@gmail.com

**Comment by alistairewj** [comment]
You're unlikely to receive help if you ask very general questions with little evidence of what you have tried and what specific issues you are having. Since you mention you are a PhD student, I highly recommend you consult your supervisor and ask them for a local contact in your institution who can help you use the data.

**Comment by sarwa** [comment]
Dear sir

 

My supervisor don’t have any idea about my topic , for that im look like lost

I try to find any programmer can help me

I design scheme WBAN , to decrease the value of data loss

I have the scenario , but now need to analysis MIMIC database , any help I hope can get it

I find many Indian programmer but asking lot money (not easy trust person on web)

I extend my semester, not have much time to submit 

I please u to help me

 

please

**Comment by alistairewj** [comment]
Sorry, we can't help you, but you should pursue this further with your supervisor.

**Comment by sarwa** [comment]
i build the simulation environment in OMNET++
Im ready to send any details you asking
please send your email

**Comment by sarwa** [comment]
i build the simulation environment in OMNET++
Im ready to send any details you asking
please send your email

**Comment by ktzim** [comment]
Dear all, 

Does anybody know whether MIMIC III database comprises data from patients with COPD ? How can I find out? 

Thanks in advance. -Katerina

**Comment by alistairewj** [comment]
Hi Katerina - undoubtedly it does as COPD is not an ultra-rare condition, but defining these things retrospectively can take some work.

P.S. In the future you should raise a new issue for new questions and your issue ideally should have some of the work you've done in trying to solve your question.
