### ISSUE TITLE
Unable to extract D_ICD_PROCEDURES.csv

### ISSUE THREAD

**Issue by weronikazak** [MIT-LCP/mimic-code#1662]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I was trying to get the csv file for `D_ICD_PROCEDURES.csv` from the [PhysioNet](https://physionet.org/content/mimiciii), but upon the extraction I get the following error:

![image](https://github.com/MIT-LCP/mimic-code/assets/34200460/be20d486-36e1-4b52-96f1-322538261f51)

Any idea how to resolve this?

**Comment by alistairewj** [comment]
Can you verify the file is downloaded correctly by comparing the checksum hash (SHA) with the ones provided on the website?

**Comment by alistairewj** [comment]
Going to close this. Feel free to reopen if you still have the issue.

I will say that there is a bug in libarchive where plain text files are misinterpreted as mtree files, and the archive agent fails to extract the data. https://github.com/libarchive/libarchive/issues/1051

I don't have a good workaround for this aside from using a different program like gzip.
