### ISSUE TITLE
Does open-source code exist to extract sepsis patients based on Sepsis-3 criteria from the MIMIC-IV Version. 2.2?

### ISSUE THREAD

**Issue by rishabh297** [MIT-LCP/mimic-code#1664]
As the title suggests, is there any published open-source SQL code to extract sepsis patients based on Sepsis-3 criteria from the new MIMIC-IV Version. 2.2?

**Comment by alistairewj** [comment]
Not sure if you found it and therefore closed the issue but for everyone else it does exist and it is here: https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iv/concepts/sepsis/sepsis3.sql

**Comment by rishabh297** [comment]
Yes, I found it and closed the issue. Thank you. I appreciate your efforts in creating this!
