### ISSUE TITLE
Disk space needed

### ISSUE THREAD

**Issue by adcobb** [MIT-LCP/mimic-code#167]
Hi. I'm building the MIMIC III database in Postgres and continue to get an error message indicating that there is not enough available disc space after about 7 tables have been added. I have approx. 2 terabytes of space available, so this seems strange to me. Does anyone know how much space the build should take? Thanks. 

AC

**Comment by tompollard** [comment]
Hi @adcobb, my installation of MIMIC-III (plus several custom tables) is around 80GB, so disk space shouldn't be a problem for you:

```
SELECT pg_size_pretty(pg_database_size('mimic')) As fulldbsize;

 fulldbsize 
------------
 78 GB
```

**Comment by alistairewj** [comment]
Might be worth checking where the postgres database is located. You may be
installing it on a disk other than the one with 2TB. It has happened to me!

**Comment by alistairewj** [comment]
Let us know if you have any other issues.

**Comment by hagerrady13** [comment]
I am also having a similar problem, how do I change where the postgres database is located?
@alistairewj

**Comment by briangow** [comment]
Based on a [Google search](https://www.google.com/search?q=change+postgres+install+directory), you should be able to change the location of where you store your data for Postgres.  The process for doing that appears to vary by operating system though.
