### ISSUE TITLE
Meaning of note_seq in MIMIC-IV Notes Discharge

### ISSUE THREAD

**Issue by prabaey** [MIT-LCP/mimic-code#1679]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

According to the documentation, note_seq in the MIMIC-IV Notes Discharge table has the following meaning: "A monotonically increasing integer which chronologically sorts the notes within note_type categories. That is, notes can be ordered sequentially by note_seq."

Why do we need this attribute? Is it not possible to chronologically sort notes according to the chartdate? Does note_seq indicate within-patient ordering, or general ordering? I feel like I'm missing something. Thanks for the clarification!

**Comment by tompollard** [comment]
> Why do we need this attribute? Is it not possible to chronologically sort notes according to the chartdate? Does note_seq indicate within-patient ordering, or general ordering? I feel like I'm missing something. Thanks for the clarification!

I don't think you are missing anything. Sometimes there is redundancy in information, and sometimes fields such as these make it easier for us to build and maintain the dataset.
