### ISSUE TITLE
Help with using the Data (new to programming)

### ISSUE THREAD

**Issue by jalemanrios** [MIT-LCP/mimic-code#168]
Hi everyone:

Originally, I wrote my question directly to Mimic support, but was asked to post subsequent questions or issues here.

My problem is that I'm new to programming so I'm not familiar at all with the SQL language.

Is there a way of accessing and working with the data without the need of using SQL?

If not, what's the easiest way of accessing and using the data for my analyses?

**Comment by alistairewj** [comment]
You can absolutely use any software package you would like. The data files
are provided in a well standardized CSV format which should be importable
by Python, r, etc. I myself have loaded it using pandas in Python. If you
have sufficient RAM, you could load files into memory and work with them
within whatever software you are comfortable with. Chartevents, the biggest
table, is something like 40gb though so this can be a challenge. Also, the
main disadvantage of this is that you can't take advantage of the most of
the code in this repository - but don't let that stop you!

I'd also recommend, if you go down this route, to preprocess the files,
splitting them into smaller chunks based off ITEMID, etc. That will make
loading in only the necessary data easier.

**Comment by tompollard** [comment]
A colleague at the University of Waterloo has developed a visualization tool for MIMIC, which you may find helpful for browsing the data: http://hdsl.uwaterloo.ca/visualization-tool/

If you'd like to learn some SQL, there is a tutorial on the MIMIC website at: https://mimic.physionet.org/tutorials/intro-to-mimic-iii/

**Comment by jalemanrios** [comment]
@alistairewj @tompollard Thank you for your answers.  

I've been working with the database, and at least now I have a vague idea of how to "surf" through the data.  In time, I believe I'll get better.

Now I'm at a point where I'm querying the database for the values of 4 different itemids just from 1 patient (for now). With the result of this query I want to import the data into R and do my analyses. This is the code I'm using:

`copy (select subject_id, charttime, value from mimiciii.chartevents where subject_id = ‘#’ and itemid = ‘#’, ‘#’, ‘#’, ‘#’ order by row_id) to ‘path_to_folder’ with csv delimiter ‘,’ header;`

It's not working.  I'm assuming it has something to do with the way I wrote the 'itemid = ' part, but I'm not sure how to fix it.  The other thing I'm thinking of is running the code for each itemid independently and then binding the tables in R.  The problem is this will take very long when dealing with more patients.

Thank you.

PS: Should I open a new issue?

**Comment by tompollard** [comment]
@jalemanrios you're almost there, it's just your `WHERE` clause is slightly off. The `itemid = ‘#’, ‘#’, ‘#’, ‘#’` syntax is incorrect.

Try this:
```sql
-- no need to wrap numerical fields in quotation marks
-- use IN instead of = to compare a list
SELECT subject_id, charttime, value 
FROM mimiciii.chartevents 
WHERE subject_id = x1 
AND itemid IN (x2, x3, x4, x5)
ORDER BY row_id;
```

**Comment by jalemanrios** [comment]
@tompollard That runs, but I'm only getting the values for itemid x2

**Comment by tompollard** [comment]
Hmmm...the syntax is correct, so I'm not immediately clear what the problem is. A full example that will return a list of results for `subject_id = 3` and any of `itemids` `128, 159, 161` is:

```sql
SELECT subject_id, hadm_id, itemid, charttime, value 
FROM mimiciii.chartevents 
WHERE subject_id = 3
AND itemid IN (128, 159, 161)
ORDER BY subject_id, hadm_id, charttime;
```

Perhaps double check (1) that you're using the correct itemids (2) that these itemids are actually present for the `subject_id` that you're looking at.

**Comment by jalemanrios** [comment]
@tompollard Was just about to comment.  Error on my part.  I forgot to make sure that the itemids were present for the subject_id I was trying to work with.

Thank you!

**Comment by tompollard** [comment]
Great, glad you solved it!
