### ISSUE TITLE
Is there any overlap between MIMIC IV and eICU-CRD?

### ISSUE THREAD

**Issue by isears** [MIT-LCP/mimic-code#1692]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

The eICU-CRD paper states "The source hospital of MIMIC-III does not participate in the eICU program, so eICU-CRD is a completely independent set of data". Can we assume the same independence for MIMIC IV?

Thank you,
Isaac

**Comment by tompollard** [comment]
> Can we assume the same independence for MIMIC IV?

While we haven't explicitly confirmed independence, I would say yes it is safe to make this assumption. The chances of the same patient appearing in both datasets is extremely small.
