### ISSUE TITLE
Patients Urine Output - questions

### ISSUE THREAD

**Issue by vanessacunha** [MIT-LCP/mimic-code#17]
Dear all,
I have some doubts regarding the codes that should be used to analyse the urine output of the patient. I am interested in study patients with kidney injuries and I need to verify the level of the urine output volume. I need in the mL/kg/hr units. Can I use 51108/51109 from LABEVENTS or should be use another code from IOEVENTS?
Another question, what is the difference between the codes 51108 and 51109? They seem equal, in the value, date and units.
If we have to use the LABEVENTS code, how can we have the urine output in mL/kg/hr? To have in mL/kg it is just needed to divide by the weight of the patient, but what is the sample time rate of the measurements from 51108 and 51109?
Thank you!
Sincerely,
Vanessa Cunha

**Comment by alistairewj** [comment]
All data in the LABEVENTS table relate to laboratory measurements.

51108 and 51109 are "URINE VOLUME" and "URINE VOLUME, TOTAL", and likely represent the volume of urine taken in a urine sample which is processed by the lab. You will not get urine output from that table. Instead, look at IOEVENTS.

**Comment by vanessacunha** [comment]
Thank you!
However I can not understand what is the best code for the urine outuput.
There are several codes, but I do not know what should be applied. I think
that the code 55 - at least in MIMIC II could be applied, however I need in
the cc/kg/hr.
Sincerely,


2015-10-29 2:52 GMT+00:00 Alistair Johnson <notifications@github.com>:

**Comment by alistairewj** [comment]
Urine output can be captured like most other variables:

1. Searching for corresponding entries using a free text search in D_ITEMS
2. Filtering these entries down using domain knowledge (e.g. "Foley catheter" represents urine output, "Jackson-Pratt drain" does not)
3. Once you have a set of `ITEMID` which represent urine output, select only rows in the IOEVENTS table which correspond to these `ITEMID`

Urine output will not be stored in cc/hr/kg. It will be stored as mL. You will have to then derive cc/hr/kg from the mL measurements by summing over some time period, then dividing by the length of the time period in hours, then dividing by the patient's weight.

**Comment by vanessacunha** [comment]
Thank you so much for your help!
For what I saw, there are some codes that could be applied, such as:
6304,"urine cath";
43431,"Urine cc/k/hr"
41857,"urine out in er"
40428,"Urine Out Straight Cath"
40026,"Urine Out Total"
40094,"Urine Out Condom Cath"
40096,"Urine Out Ureteral Stent #1"
42362,"CATH LAB URINE OUTPT"
44706,"urine output"
43633,"Urine,cc/kg/day"
43348,"urine output/kg"
41510,"TOTAL OUT FOLEY BAG"
44204,"Foley Catheter"
40055,"Urine Out Foley"
among others
For what I observed some codes (just as e.g 43431,"Urine cc/k/hr" do not
present measurements) which make hard to select the right codes to analyse.
Do you think there are any code that could be applied to that patients?
Or you have suggestions for which codes to have try first to observe if
there are patient measurements?
Thank you so much for your collaboration!
Sincerely,
Vanessa Cunha






2015-10-29 16:00 GMT+00:00 Alistair Johnson <notifications@github.com>:

**Comment by alistairewj** [comment]
These codes are free text entries by the nurse. You have to go through each
and check if they have data, and if that data is valid. 80% of the data
will be contained in one code and easily extracted. The other 20% will be
harder. If you do manage to extract this information, we would welcome
contribution of your code to the repository. My suggestion to start would
be to join the IOEVENTS table with your list of ITEMID and count the number
of observations.

**Comment by vanessacunha** [comment]
Thank you for your help!
However now I have a problem, once there is no information related with
patient weight. In the table IOEVENTS there is this variable but does not
present any data.
Do you have any idea about to solve this?
Thank you so much
Sincerely,

2015-10-31 17:33 GMT+00:00 Alistair Johnson <notifications@github.com>:

> These codes are free text entries by the nurse. You have to go through each
> and check if they have data, and if that data is valid. 80% of the data
> will be contained in one code and easily extracted. The other 20% will be
> harder. If you do manage to extract this information, we would welcome
> contribution of your code to the repository. My suggestion to start would
> be to join the IOEVENTS table with your list of ITEMID and count the number
> of observations.
>

**Comment by alistairewj** [comment]
This will be clearer in the new release of the data. Essentially the
patient's weight only exists for half the patients in that column. For the
other half, you will have to extract the weight from chartevents and merge
it for the patient.

**Comment by vanessacunha** [comment]
Thank you so much for your help.
Now I have a new question, could i use the codes in the chartevents, e.g.:

1058,"foley cath. care"

6200,"foley changed"

1501,"FOLEY CLAMPED"

To have the interval of during which the urine was "measured"? Because I
need to divide by the length of the time period in hours, so I need a
reference what time the foley was changed.
Thank you one more time!
Sincerely,

2015-11-03 18:18 GMT+00:00 Alistair Johnson <notifications@github.com>:

> This will be clearer in the new release of the data. Essentially the
> patient's weight only exists for half the patients in that column. For the
> other half, you will have to extract the weight from chartevents and merge
> it for the patient.
>

**Comment by vanessacunha** [comment]
Sorry for reply again, but I 've tried these codes regarding foley changed,
foley care, and others but there is no data.
Do you have any suggestions to have the time period about that urine
collection?
Sincerely,


2015-11-09 16:49 GMT+00:00 Vanessa Cunha <v.cunha@campus.fct.unl.pt>:

> Thank you so much for your help.
> Now I have a new question, could i use the codes in the chartevents, e.g.:
>
> 1058,"foley cath. care"
>
> 6200,"foley changed"
>
> 1501,"FOLEY CLAMPED"
>
> To have the interval of during which the urine was "measured"? Because I
> need to divide by the length of the time period in hours, so I need a
> reference what time the foley was changed.
> Thank you one more time!
> Sincerely,
>
> 2015-11-03 18:18 GMT+00:00 Alistair Johnson <notifications@github.com>:
>
>> This will be clearer in the new release of the data. Essentially the
>> patient's weight only exists for half the patients in that column. For the
>> other half, you will have to extract the weight from chartevents and merge
>> it for the patient.
>>

**Comment by alistairewj** [comment]
Only use codes which link to IOEVENTS (soon to be OUTPUTEVENTS). Look in
the LINKSTO column. The first and last charted times are your best guess
for start and stop times.

**Comment by vanessacunha** [comment]
Thank you!
Can you explain me the difference between these codes:
40055,"Urine Out Foley"-- and 226559,"Foley"? Are both possible to use in
calculations of urine output?
Sincerely,

2015-11-09 19:14 GMT+00:00 Alistair Johnson <notifications@github.com>:

> Only use codes which link to IOEVENTS (soon to be OUTPUTEVENTS). Look in
> the LINKSTO column. The first and last charted times are your best guess
> for start and stop times.
>

**Comment by alistairewj** [comment]
Yes, both would contain information about urine output.

**Comment by alistairewj** [comment]
The names of fields were free-text and entered by caregivers. As a result, they tend to be similar, but not identical.

**Comment by vanessacunha** [comment]
Thank you so much!
I do not know if your aware of this, but in the icustayevents table there
is missing some data of patients. In fact, some patients ( I can give the
subject_id=736, 3004, 6132,6411,6503,7132, among others) are not present in
icustayevents, but there is data from their in labevents and chartevents,
for instance.
Thank you!


2015-11-12 23:18 GMT+00:00 Alistair Johnson <notifications@github.com>:

**Comment by alistairewj** [comment]
No problem. Yes, we are aware of these. These are patients which we couldn't link to the hospital database. In the future we hope to link them. Once that occurs they will have an associated `HADM_ID` and `ICUSTAY_ID`. For now, I'd recommend starting your queries from the ICUSTAYS table, that way when you left join you never encounter this data. 

Also, as a side note, I just wanted to let you know that there the new version of MIMIC-III, v1.2, has been released. In this version the table is called ICUSTAYS (whereas you refer to it as ICUSTAYEVENTS). If you haven't upgraded yet I recommend you do so as many improvements were made!
