### ISSUE TITLE
Age computation in icustay_detail

### ISSUE THREAD

**Issue by mghassem** [MIT-LCP/mimic-code#170]
In the data from mimic-code/concepts/demographics/icustay_detail.sql, we seem to be getting a reasonable number of people with very high ages (over 250). 

> mimic=# select count(1) from icustay_detail where age > 250;
>  count 
> -------
>   2703
> (1 row)

I know that DOB was shifted for patients older than 89, but I had thought that these were all shifted to a consistent age (I think this was 200 originally). 

Is it still correct to say that anyone with an age > 89 should have their age set to the median (91.4)?

**Comment by tompollard** [comment]
Hi @mghassem, if a patient is older than 89 on first admission their age is fixed to 300. 

Ages were shifted to 200 in the past, but as a result of changes to date shifts introduced in MIMIC-III this gave some researchers the mistaken belief that the data contained real dates.

> Is it still correct to say that anyone with an age > 89 should have their age set to the median (91.4)?

I believe that the median age of patients >89 is still 91.4, but will double check this tomorrow.
