### ISSUE TITLE
patient diet

### ISSUE THREAD

**Issue by zyt33333** [MIT-LCP/mimic-code#1705]
How to find diets of icu patients in the database, especially enteral nutrition, transoral diets

**Comment by alistairewj** [comment]
Check the ingredientevents table. This contains caloric intake and other information related to patient diet. However, this table only exists for those receiving some kind of input, i.e. it likely doesn't track oral intake. I say this as every row in the *ingredientevents* table is associated with an entry in the *inputevents* table, so it will only have diet information if there is an entry in *inputevents* (which is typically enteral nutrition, etc).
