### ISSUE TITLE
Identifying extubation in mimic patients.

### ISSUE THREAD

**Issue by theonesp** [MIT-LCP/mimic-code#172]
Dear mimic support team,

After reading the documentation I found two ways of identifying extubation:

A) mimiciii.chartevents.itemid = 640  And  lower(mimiciii.chartevents.value) = 'extubated'
I get 7512 unique patients
B) mimiciii.procedureevents_mv.itemid = 227194 
I get 6761 unique patients
C) Join A) and B)
I get 14090 unique patients 

The physician I am working with thinks there should be more than 14090 out of 46467

Am I missing something? Is there any other way of finding them?

Thanks for the help!

**Comment by alistairewj** [comment]
Check out https://github.com/MIT-LCP/mimic-code/blob/master/concepts/ventilation-durations.sql#L56-L70

It adds in a rule that transition from mechanical ventilation to non-invasive ventilation indicates extubation. You might be interested in it.

**Comment by theonesp** [comment]
Thank you @alistairewj , I got a better result including that subset:

a) mimiciii.chartevents.itemid = 640  And  lower(mimiciii.chartevents.value) = 'extubated'
7512 unique patients.
b) mimiciii.procedureevents_mv.itemid = 227194 
6761 unique patients.
c) itemid = 226732 and value in
      ('Nasal cannula','Face tent','Aerosol-cool','Trach mask ','High flow neb','Non-rebreather','Venti mask ','Medium conc mask ','T-piece','High flow nasal cannula','Ultrasonic neb','Vapomist')
14883 unique patients
d) Join A) and B)
14090 unique patients, overlaping 183
e) Join A) and B) and C)
**22344** unique patients, overlaping 6629

**Comment by alistairewj** [comment]
As we discussed the other day, I'd recommend using the `endtime` from the ventdurations query. That's currently our best guess at extubation time.

**Comment by theonesp** [comment]
Great, yeah, this is what I was considering in my previous query, but now I
have a slightly bigger result.

Thanks!


'High flow neb', -- 10785 observations
'Non-rebreather', -- 5182 observations
'Venti mask ', -- 1947 observations
'Medium conc mask ', -- 1888 observations
'T-piece', -- 1135 observations
'High flow nasal cannula', -- 925 observations
'Ultrasonic neb', -- 9 observations
'Vapomist' -- 3 observations
) then 1
when itemid = 467 and value in
(
'Cannula', -- 278252 observations
'Nasal Cannula', -- 248299 observations
'None', -- 95498 observations
'Face Tent', -- 35766 observations

Miguel

------------------------------

  [image: MIT][image: imes]

*Miguel Ángel Armengol de la Hoz **✉* <maarmeng@mit.edu> / Sponsored Research
Fellow
*MIT - Institute for Medical Engineering and Science *
*Laboratory for Computational Physiology*
MIT, E25-505 - 77 Massachusetts Ave.
Cambridge, MA 02139

2017-05-16 18:18 GMT-04:00 Alistair Johnson <notifications@github.com>:
