### ISSUE TITLE
Release of deidentification code

### ISSUE THREAD

**Issue by dgolden1** [MIT-LCP/mimic-code#173]
The MIMIC Paper [1] describes its free text field deidentification process as follows:

> Protected health information was removed from free text fields, such as diagnostic reports and physician notes, using a rigorously evaluated deidentification system based on extensive dictionary look-ups and pattern-matching with regular expressions [2]. The components of this deidentification system are continually expanded as new data is acquired.

The referenced paper [2] describes a Perl script created in 2008, so it seems likely that MIMIC is using a more modern implementation. Is it possible to open source the MIMIC free text deidentification code?

[1] Johnson, A. E. W., Pollard, T. J., Shen, L., Lehman, L.-W. H., Feng, M., Ghassemi, M., et al. (2016). MIMIC-III, a freely accessible critical care database. Scientific Data, 3, 160035. http://doi.org/10.1038/sdata.2016.35
[2] Neamatullah, I. et al. Automated de-identification of free-text medical records. BMC Medical Informatics and Decision Making 8, 1–32 (2008).

**Comment by tompollard** [comment]
Hi Daniel, thanks for the message. We plan to release a new version of the deidentification package (rewritten in Python, with a structure that should be more generalisable to other datasets) sometime this year. If you drop me an email (tpollard mit edu) then I'll see what we can do to help in the meantime. Tom

**Comment by tompollard** [comment]
@jisikoff no, sorry, but it is on our list of things to do.

**Comment by ngsalmon** [comment]
Any update on this?
