### ISSUE TITLE
MIMIC CXR JPG dataset missing/down

### ISSUE THREAD

**Issue by ARichKat** [MIT-LCP/mimic-code#1737]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, 
The dataset for MIMIC CXR JPG seems to be down/missing. When I attempt to download the zip I get an invalid response error. Also directory view is missing (see below).

Is this part of the network issues in the April 9th notice on physionet? If so, when do you expect the dataset to be available again?

<img width="393" alt="image" src="https://github.com/MIT-LCP/mimic-code/assets/23104402/32633429-8b47-448c-ba40-57d2153f643b">

**Comment by NMontanaBrown** [comment]
Hi team, I'm also having the same issues.

**Comment by tompollard** [comment]
Hi @NMontanaBrown. We are aware of the issue and are working on it. We've had some major issues with the MIT network over the past couple of weeks, and as a result are in the process of migrating all of our content/services to a new location.

**Comment by NMontanaBrown** [comment]
@tompollard Seems resolved for me! Thanks for your quick response and contribution :smiley:
