### ISSUE TITLE
Radiology reports truncated in MIMIC III.

### ISSUE THREAD

**Issue by Sandv** [MIT-LCP/mimic-code#174]
Hi,
I have switched to MIMIC III relatively smoothly - great to have access to much more data!

I noticed that (I believe all) the radiology reports in notevents are severely truncated.
eg: frontoparietal region.  There is\n a curvilinear area of lucency noted adjacent to the h... **truncated**

I verified this in the notevents.csv using data.table fread and in postrgresql so I believe the data is actually not there.

Are you aware of this issue? Mimic II had full reports. 

Thank you very much for your help

Veit

**Comment by alistairewj** [comment]
Thanks - haven't noticed anything like this before. Could you give us a ROW_ID for the note that you believe is truncated?

**Comment by alistairewj** [comment]
@tompollard just found that note (`ROW_ID` = 739687), and both of us have verified that it is not truncated and has all the text. I think your method of displaying the note or reading in the data may be truncating the text.

**Comment by Sandv** [comment]
Thank you very much for your very quick responses. You are indeed right, this turned out to be a display issue in RStudio. The fix is described here http://stackoverflow.com/questions/36800475/avoid-string-printed-to-console-getting-truncated-in-rstudio 

I am so sorry to have bothered you with this non-mimic issue. The data in the database is all there. Consider this issue closed. 

Thank you very much for your work on this amazing database resource!

Best
Veit

**Comment by alistairewj** [comment]
No worries, glad all is well. Good luck in your research!

**Comment by tompollard** [comment]
@Sandv glad to hear you got to the bottom of this and thanks for posting your fix.
