### ISSUE TITLE
Usage of demo dataset

### ISSUE THREAD

**Issue by mattinjersey** [MIT-LCP/mimic-code#1746]
Hello I know that I have read that the mimic data shall not be released. Instead we could release data from the demo dataset, specifically citing the demo dataset, and explaining the policy.

Anyways could you point me to where this policy is.

Thanks Matt

**Comment by alistairewj** [comment]
Datasets are distributed according to licenses and DUAs via PhysioNet. For open data, the license link is accessible from the right side of the [PhysioNet project page](https://physionet.org/content/mimic-iv-demo/2.2/). The license for the MIMIC-IV Demo is available here: https://physionet.org/content/mimic-iv-demo/view-license/2.2/

This is the ODbL license, and there is a plain language summary here: https://opendatacommons.org/licenses/odbl/summary/
