### ISSUE TITLE
MIMIC III: How to get Injury Severity Score and Abbreviated Injury Scale for Trauma Patients

### ISSUE THREAD

**Issue by mnumankhan21** [MIT-LCP/mimic-code#175]
Hey guys,
How can we select trauma patients and their injury severity score (ISS) and Abbreviated Injury Scale score(AIS)
Also how to get external trauma cause code ? Whether its blunt or Penetrating injury ?

Thank you.

**Comment by alistairewj** [comment]
I do not think that it is routine practice to document the ISS or AIS in the data. Are these scores derivable from charted data? Or do they non-numeric answers, e.g. "where is the site of the injury?"

**Comment by alistairewj** [comment]
Closing for now, feel free to re-open if you feel these are derivable scores that would be useful for the community.
