### ISSUE TITLE
urine output

### ISSUE THREAD

**Issue by alexandreliborio** [MIT-LCP/mimic-code#1754]
Hi,
How can I obtain hourly urineoutput and not a mean of previous 6,12 or 24h?
if a lag time of three hours is present, how can I obtain the mean just like
12-15h. 300ml
obtain this
12-13 100ml
13-14 100ml
14-15 100ml
Many thanks

**Comment by alistairewj** [comment]
We can only provide what is documented, and hourly UO is not always documented. Your closest proxy is the pivoted UO query: https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iv/concepts/measurement/urine_output.sql
