### ISSUE TITLE
Number of rows for MIMIC III v1.4

### ISSUE THREAD

**Issue by cheryltan** [MIT-LCP/mimic-code#176]
I found these checks for MIMIC III v1.4 (https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/postgres_checks.sql). 

Is this more accurate than what is listed in Physionet? 

For example, number of rows listed in Physionet for microbiology events is 328,446 but the file I have downloaded is consistent with the checks in github (n=631726). 

Other discrepancies are d_items, d_labitems, datetimeevents, inputevents_cv, labevents, outputevents, prescriptions.

Thank you

**Comment by alistairewj** [comment]
Hi @cheryltan - I would definitely use the postgres_checks.sql file, as I'm sure we updated that and forgot to update PhysioNet. I can confirm that microbiologyevents should have 631726 rows as is listed in postgres_checks. When you say PhysioNet, do you mean the row counts on table pages at mimic.physionet.org ? I just want to confirm that they are not listed elsewhere.

**Comment by tompollard** [comment]
@cheryltan, the Postgres script is accurate. We'll update the website!

**Comment by tompollard** [comment]
The website has been updated (https://github.com/MIT-LCP/mimic-code/issues/176).

**Comment by cheryltan** [comment]
Hi Alistair and Tom, 

Yes, I did mean the MIMIC tables at mimic.physionet.org. Thanks for the clarification and for updating the website. Apart from the tables I listed above, I think noteevents also has missing number of rows in the website. Thanks again

**Comment by tompollard** [comment]
Thanks again @cheryltan. The noteevents table was updated too, so the rows should appear when you refresh your cache.
