### ISSUE TITLE
MIMIC-Echo Folder "p14076415" is missing at Google cloud storage

### ISSUE THREAD

**Issue by lfb-1** [MIT-LCP/mimic-code#1769]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I noticed that folder "p14076415" from MIMIC-Echo is missing at Google cloud storage, but shown in [website](https://physionet.org/content/mimic-iv-echo/0.1/files/p14/p14076415/#files-panel). 
Could you fix this issue on google cloud? I have attached a screen shot for comparsion, left is MIMIC-echo website file panel, right is google cloud storage.
<img width="1615" alt="Screenshot 2024-07-27 at 12 20 18" src="https://github.com/user-attachments/assets/80f4cf9a-bf87-44c2-96e4-7d78fa342f10">

**Comment by lfb-1** [comment]
I checked again, there are multiple missing only in p14 folder, other folders seem intact.

**Comment by briangow** [comment]
@lfb-1 , thanks for pointing this out! We have added the missing data to the Google Cloud Bucket. I'll close this issue since I think this is resolved, but please let us know if you notice any other issues.
