### ISSUE TITLE
Distinguishing on-pump vs off-pump CABG patients

### ISSUE THREAD

**Issue by ErikWDoty** [MIT-LCP/mimic-code#179]
Hi Everyone,

I am working on a project dealing with patients who underwent a CABG procedure. Is there a way to distinguish between on-pump vs off-pump procedures? I was hoping to use CPT codes, but it appears CPT codes only look at arterial vs venous graft and number of vessels grafted.

Thanks

**Comment by alistairewj** [comment]
Have you considered using an ICD-9 procedure code to differentiate the two groups? Specifically 3961 "Extracorporeal circulation auxiliary to open heart surgery"? I think facilities use that to bill for pump use during CABG but I've never investigated it myself.

**Comment by ErikWDoty** [comment]
I think that will work, thank you! I was looking at the icd-9 procedure codes, but I was using the wrong terminology and could not find that code.

**Comment by alistairewj** [comment]
Great, glad there was a solution!
