### ISSUE TITLE
Age Extraction for MIMIC-III Subjects in MIMIC-III Clinical Database

### ISSUE THREAD

**Issue by Zjamil4-c** [MIT-LCP/mimic-code#1809]
Hello I am working on MIMIC-III Clinical Database and MIMIC-III waveform match subset. I would like to know about age of subjects in the MIMIC-III Clinical Database. I understand that the age of subjects>89 years is marked as 300. However, I need to extract the age of other subjects as 58, 21 years, Can you tell me how can I get that from the database?

**Comment by alistairewj** [comment]
Subtract the time of the measurement from the `DOB` in the *patients* table to get age, e.g. as is done in this query: https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iii/concepts/demographics/icustay_detail.sql
