### ISSUE TITLE
Charttime and Storetime in Notes

### ISSUE THREAD

**Issue by KevinKloiber** [MIT-LCP/mimic-code#1817]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I have two questions related to ``charttime`` and ``storetime``:

1. In a sample of ~ 240,000 patients, I observe that the ``charttime`` (which is a chartdate) is always equal to the discharge day. Is this just common practice or did something go wrong when creating the table? When reading through the description of ``charttime`` I expected it to be <= discharge day with frequent values prior to the discharge day but I find 0 notes that were charted prior to the discharge day. 

2. There are also 2,905 observations with a ``storetime`` < ``charttime``:
`SELECT COUNT(*) 
FROM `physionet-data.mimiciv_note.discharge` 
WHERE charttime > storetime`
Is there a possible explanation for this or are these 2,905 observations just data errors?

Thanks for the time and resources you've spent on this!

**Comment by alistairewj** [comment]
> 1. In a sample of ~ 240,000 patients, I observe that the `charttime` (which is a chartdate) is always equal to the discharge day. Is this just common practice or did something go wrong when creating the table? When reading through the description of `charttime` I expected it to be <= discharge day with frequent values prior to the discharge day but I find 0 notes that were charted prior to the discharge day.

The `chartdate` is a truncated version of `charttime`. My understanding is that discharge summaries are always charted on the date of discharge, which is consistent with what you've found. Kind of bad nomenclature to call it a `charttime` but we used to have all the notes in the same table and I guess the name stuck.

> 2. There are also 2,905 observations with a `storetime` < `charttime`:
>    `SELECT COUNT(*)  FROM `physionet-data.mimiciv_note.discharge`  WHERE charttime > storetime`
>    Is there a possible explanation for this or are these 2,905 observations just data errors?

Probably data errors. The `storetime` is actually parsed from the discharge summary itself - there is a line at the bottom of the note indicating the date/time the note was signed. That's what we use for `storetime`.

**Comment by KevinKloiber** [comment]
Thanks! So to summarize, the ````charttime```` variable is derived from ````chartdate````. Entries with ``storetime < charttime`` are data errors, whereas entries with ``charttime < storetime`` are working as intended, and ``storetimes`` that are far away from the ``charttime`` might either be data entries (if very far off) or just someone opening the note and storing it after a delay. Very helpful!
