### ISSUE TITLE
MIMIC-III database loaded without the CHARTEVENTS table

### ISSUE THREAD

**Issue by postgres-newbie** [MIT-LCP/mimic-code#182]
Hi ! 

When downloading the MIMIC-III dataset, my internet connection was interrupted during this command: 

wget --user username@domain.com --ask-password -A csv.gz -m -p -E -k -K -np -nd https://physionet.org/works/MIMICIIIClinicalDatabase/files/

As a result of this the CHARTEVENTS.csv.gz file was not downloaded. I resumed the download using the same command:

wget --user username@domain.com --ask-password -A csv.gz -m -p -E -k -K -np -nd https://physionet.org/works/MIMICIIIClinicalDatabase/files/

But it did not download CHARTEVENTS.csv.gz, so I manually downloaded this file.

When loading the MIMIC III data loaded without the CHARTEVENTS table and gave no error during processing:

$ psql -f postgres_load_data.sql -U mimic -v mimic_data_dir='/Documents/MIMIC_III/'

SET
COPY 58976
COPY 34499
COPY 7567
COPY 0                                  <---  CHARTEVENTS
COPY 573146
COPY 4485937
COPY 651047
COPY 125557
COPY 134
COPY 14567
COPY 3882
COPY 12487
COPY 753
COPY 61532
COPY 17527935
COPY 3618991
COPY 27854055
COPY 631726
COPY 2083180
COPY 4349218
COPY 46520
COPY 4156450
COPY 258066
COPY 240095
COPY 73343
COPY 261897

Here's the configuration of my machine:
MacBook Air (13-inch, Early 2014)
Processor: 1.7 GHz Intel Core i7
Memory: 8 GB 1600 MHz DDR3
Mac OS: Sierra, version 10.12.3
MIMIC-III version 1.4

The CHARTEVENTS.csv file was located along with all the other .csv files in the mimic_data_dir location. Has anyone else had this issue?

**Comment by tompollard** [comment]
@postgres-newbie the `chartevents` table is distributed across several partitions, resulting in a 0 value being reported here. If you try querying the table, you'll find that it returns the expected data. 

```
SELECT COUNT(*)
FROM chartevents;

   count   
-----------
 330712483
(1 row)
```

**Comment by postgres-newbie** [comment]
Thanks so much for your help Dr. Pollard!

**Comment by tompollard** [comment]
Thanks Krupa - glad we could help!

**Comment by huangmozhilv** [comment]
@postgres-newbie Hi, how long did it take to copy all the files? Actually I have spent more than 10 hours getting stuck with
COPY 58976
COPY 34499
COPY 7567.

My OS:
MacBook Pro (13-inch, 2016)
Processor: 2.9 GHz Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3
Set up disk: Macintosh HD

Data:
MIMIC-III version 1.4

**Comment by jbains223** [comment]
Hi @tompollard. If the result is not 0 and rather the number 330712483 does that mean that the make was not performed successfully?

**Comment by alistairewj** [comment]
Run the [checks script](https://github.com/MIT-LCP/mimic-code/blob/db27aab8707879ea3c03337c946f02d78f560cd2/buildmimic/postgres/postgres_checks.sql) - whether it's printed as `COPY 0` or `COPY 330712483` likely depends on the postgres version - so the row count is the best check.

**Comment by jbains223** [comment]
Thank you @alistairewj. I ran the make file which did the check at the end and all the tables PASSED.
