### ISSUE TITLE
How can this be converted to the qualitative assessment of urine ketones?

### ISSUE THREAD

**Issue by HYJ-HUB** [MIT-LCP/mimic-code#1820]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, everyone.
I am using MIMIC Ⅳ 2.0 database query urine ketone body found itemid '51484' is in the hematology test mode, the measurement of the specific value, I would like to ask this can be converted to common “negative”, “+”, “++”, “+++”, “+++”? ”, “++”, “+++”?
Thanks for the time and resources you've spent on this!

**Comment by alistairewj** [comment]
You would have to define those values, e.g. you could define + as 5-15 mg/dL, ++ as 15-40, etc.
