### ISSUE TITLE
Why are the values ​​of some hadm_id in the labevents table null in MIMIC-IV

### ISSUE THREAD

**Issue by huangzhuohua** [MIT-LCP/mimic-code#1823]
MIMIC IV 3.1

why there are some **hadm_id is null** in the labevents table？Isn't the patient tested after being hospitalized? If so, why is the hadm_id not recorded?

![image](https://github.com/user-attachments/assets/2ed9eed6-855c-458a-8bef-20cdcff29f69)

**Comment by alistairewj** [comment]
`hadm_id` is present if the lab result was measured *during* the hospitalization. If it is null, then the patient is not currently hospitalized, and/or the lab measurement is taken just before/after the hospitalization. For example, many patients present to the emergency department, have a lab value taken, and are then admitted to the hospital a few hours later. These lab measurements would have a NULL `hadm_id` as the patient was not admitted to the hospital when they were taken.
