### ISSUE TITLE
Cannot receive emails from physionet.org 

### ISSUE THREAD

**Issue by huangzhuohua** [MIT-LCP/mimic-code#1826]
Hello, I forgot my password on Physionet.org.
When I tried to retrieve my password through the "Forgot Password" function on the website, I couldn't receive any emails.
I also couldn't receive any email links when I re-registered.
Is there something wrong with the website? Or is there any limitation?

**Comment by gcgbarbosa** [comment]
Same here.

**Comment by alistairewj** [comment]
Looks like there is a network outage at MIT. Sorry! Will certainly be fixed soon.
