### ISSUE TITLE
Still coulldn't see mimiciv_icu and mimiciv_hosp in Google Bigquery

### ISSUE THREAD

**Issue by cute149q** [MIT-LCP/mimic-code#1827]
Hi,
After granting access for mimiciv-3.1 in physionet for google bigquery, I still can't see mimiciv_icu and mimiciv_hosp in google bigquery. Already retried to get the project by name. Could you please help me with this issue?

Thanks

Physionet:  Access to the GCP BigQuery was previously awarded to mymail@gmail.com for project: MIMIC-IV v3.1

**Comment by alistairewj** [comment]
Can you see the `mimiciv_3_1_hosp` and `mimiciv_3_1_icu` datasets? Currently v3. 1 is there. We intend to copy the data over to the generic dataset names soon, just want to give people a bit of  warning before we change the data.

**Comment by cute149q** [comment]
@alistairewj Hi, I can't see these two datasets. I also tried other datasets. Other datasets appear immediately. 
<img width="296" alt="image" src="https://github.com/user-attachments/assets/261bb156-4271-4d8d-8414-0ba071ce61f7">

**Comment by alistairewj** [comment]
OK I will take a look. I must have set it up wrong!

**Comment by alistairewj** [comment]
OK oddly the access group wasn't there. @cute149q Can you check again? You may need to do a hard refresh with Ctrl+Shift+R.

**Comment by SichengH** [comment]
After signing the DUA for v3.1, the dataset iv_2_2 showed up. Also, @alistairewj, could you please specify which version of the MIMIC  "derived" dataset it is based on?

**Comment by SichengH** [comment]
<img width="496" alt="Screenshot 2024-11-14 at 10 05 53 AM" src="https://github.com/user-attachments/assets/8c263632-7253-4dba-bac0-c65c118dce01">

Seems good now.

**Comment by alistairewj** [comment]
> After signing the DUA for v3.1, the dataset iv_2_2 showed up. Also, @alistairewj, could you please specify which version of the MIMIC "derived" dataset it is based on?

Currently it is for MIMIC-IV v2.2 but it will also be updated in a week or so.



> <img alt="Screenshot 2024-11-14 at 10 05 53 AM" width="496" src="https://private-user-images.githubusercontent.com/16839385/386012777-8c263632-7253-4dba-bac0-c65c118dce01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTI0MDQsIm5iZiI6MTczMTU1MjEwNCwicGF0aCI6Ii8xNjgzOTM4NS8zODYwMTI3NzctOGMyNjM2MzItNzI1My00ZGJhLWJhYzAtYzY1YzExOGRjZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAyNDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjMzOGIwYjhmZTQyYmY2YmFmMTljZDJhZDEwZDEwMzE3MDE2ZjNhOGVhMmNlZmY1ZWIwNjBkNzA4YTIxY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nlOmuMDAbc3qH2OFT47q2OFUhbfZPrsRCiUVY9NZ5hQ">
> Seems good now.

Great! I'll wait for @cute149q just in case there are other permissions which grant you access which external users may not have.

**Comment by cute149q** [comment]
I checked just now and it is working! Thanks @alistairewj! I will close the issue.
