### ISSUE TITLE
Calculate QSOFA and SIRS scores in intervals of 6 hours

### ISSUE THREAD

**Issue by shrey94** [MIT-LCP/mimic-code#186]
For QSOFA and SIRS scores, is it possible to compute the scores after every 6 hours instead of just on the first day on ICU admit?
Any change in the SQL code that can be made to incorporate this change?

Any help is appreciated.
Thanks

**Comment by alistairewj** [comment]
There's no code at the moment for something like this - though the current code could be adapted to recalculating the scores every 6 hours. Right now it generates a bunch of subtables based off of your data window (e.g. one day, in the firstday subdirectory) and then extracts the scores using that. You'd have to redefine the subtables to extract data off the new data window (i.e. multiple rows, each row representing a 6 hour block), and then you could run the qSOFA/SIRS scripts on that.

**Comment by postgres-newbie** [comment]
Hi ! Alistair, Based on your instructions above, I modified the vitals-first-day.sql script to change the line: 

--and ce.charttime between ie.intime and ie.intime + interval '1' day
  and ce.charttime between ie.intime and ie.intime + interval '1' hour

This now returns for every patient an hourly estimate of vitals when available. How do I include the ie.intime and specially the ce.charttime to be able to sort by ce.charttime per patient?

**Comment by alistairewj** [comment]
Modifying the script in that way will make it run on the first hour of the ICU stay. The script needs to be modified to retain a time series of values - which probably involves grouping by charttime and not filtering using the between condition.
