### ISSUE TITLE
Is patients.dod_hosp != null <=> admission.hospital_expire_flag == 1 ?

### ISSUE THREAD

**Issue by Dubrzr** [MIT-LCP/mimic-code#190]
Hi,

It seems to me that the patients.dod_hosp is not always linked to an admission.hospital_expire_flag.

```
SELECT COUNT(*) FROM mimic3.admissions WHERE hospital_expire_flag = 1; -> 5854
SELECT COUNT(*) FROM mimic3.patients WHERE dod_hosp IS NOT NULL; -> 9974
```

How could the number of admissions ending with a death be less than the number of patients dead in the hospital?
Does it means that some admissions were not registered in the database?
Or maybe I am missing something?

Thanks!

**Comment by tompollard** [comment]
Thanks @Dubrzr, this does seem a little odd. I think the basic answer is that presence of a hospital date of death does not imply that the patient died in hospital, but we'll look into it. 

Just for reference, the following query extracts the list of patients who have a `dod_hosp` but whose `hospital_expire_flag` = 1. From a quick glance at the results, most `dod_hosp` are some time after the `dischtime`

```sql
WITH pat_ad AS (
SELECT p.subject_id, a.hadm_id, p.dob, p.dod, 
       p.dod_hosp, p.dod_ssn, p.expire_flag,
       a.admittime, a.dischtime, a.deathtime,
       a.admission_location, a.discharge_location,
       a.hospital_expire_flag
FROM patients p
LEFT JOIN admissions a
ON p.subject_id = a.subject_id
WHERE p.dod_hosp IS NOT NULL
AND a.hospital_expire_flag != 1
ORDER BY p.subject_id, a.admittime
)
SELECT *
FROM pat_ad;
```

**Comment by alistairewj** [comment]
Just to follow this up, looking at the raw data, we have two columns: hospital date of death, `deathdate`, and hospital time of death. `deathtime` combines `deathdate` with the time of death.

* `dod_hosp` is directly from the raw hospital data (with a date shift), and is the date of death they record
* `deathtime` is directly from the raw hospital data (with a date shift), and only exists when a time of death is recorded
* There are patients who have a date of death but no time of death recorded

The conclusion is, as Tom says, that `dod_hosp` does not necessarily correspond to the last `hadm_id` we have in the database. Indeed for many patients it's more than a year or two after their last hospitalization. Perhaps it is from a future hospitalization or from an admission to an associated hospital. We don't know right now but we will be following this up in the future and will aim to clarify the documentation when we find out. Thanks for the report!

**Comment by Dubrzr** [comment]
Hi, 

I explored a little more the problem, so here are the results when I compute the dod_hosp - dischtime difference:
![image](https://user-images.githubusercontent.com/3718838/27735484-27523164-5da0-11e7-99cd-fabb93f1f90a.png)
So it seems to be happening at least some days after the admission, so yes it probably is as you say "Perhaps it is from a future hospitalization or from an admission to an associated hospital.".

I also found that 2 patients have dod_hosp before their dischtime:

```
WITH pat_ad AS (
SELECT p.subject_id, a.hadm_id, p.dob, p.dod, 
       p.dod_hosp, p.dod_ssn, p.expire_flag,
       a.admittime, a.dischtime, a.deathtime,
       a.admission_location, a.discharge_location,
       a.hospital_expire_flag,
       unix_timestamp(p.dod_hosp)-unix_timestamp(a.dischtime) as difftime
FROM mimic3.orc_patients p
RIGHT JOIN mimic3.orc_admissions a
ON p.subject_id = a.subject_id
WHERE p.dod_hosp IS NOT NULL
AND a.hospital_expire_flag != 1
ORDER BY p.subject_id, a.admittime
)
SELECT *
FROM pat_ad
WHERE pat_ad.difftime < -86400;
```

Returns: 

```
11782	106845	2055-03-30 00:00:00	2131-08-29 00:00:00	2131-08-29 00:00:00	2131-09-01 00:00:00	1	2131-08-21 23:18:00	2131-08-31 12:27:00		EMERGENCY ROOM ADMIT	SNF	0	-217620
99102	176648	2109-05-09 00:00:00	2194-04-20 00:00:00	2194-03-19 00:00:00	2194-04-20 00:00:00	1	2194-04-02 16:56:00	2194-04-08 14:40:00		PHYS REFERRAL/NORMAL DELI	HOME HEALTH CARE	0	-1777200
```
