### ISSUE TITLE
About the procedure events

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#192]
I wonder what's the differences between PROCEDURE_ICD table and PROCEDUREEVENTS_MV table. Both tables contain Mechanical Ventilation items, and I wonder if they are duplicated between the two tables.

**Comment by mylanhong** [comment]
The procedures in PROCEDURE_ICD table happened outside (before entering) ICU since they don't have a ICUSTAY_ID, and the procedures in PROCEDUREEVENTS_MV table happened in ICU since they have a ICUSTAY_ID, right?

**Comment by alistairewj** [comment]
The PROCEDURES_ICD table contains *billed* procedures from the hospital.

The PROCEDUREEVENTS_MV table contains documented procedures from the MetaVision clinical information system, which is used at the bedside in the ICU.

**Comment by tompollard** [comment]
> PROCEDURE_ICD table happened outside (before entering) ICU

The coding is carried out *at the end* of the hospital stay.

**Comment by mylanhong** [comment]
@alistairewj  @tompollard  So, if I need the information about ventilation, both tables should be searched in order to get complete ventilation-related information, right? One more question, I want to get the PCT (procalcitonin) value, but neither of LABEVENTS or CHARTEVENTS table contains it, why? Does it mean that the hospital dosen't have PCT tested?

**Comment by tompollard** [comment]
@mylanhong Identifying which patients are ventilated is not straightforward. For more detail on ventilation, I suggest reviewing the ventilation durations code: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/ventilation-durations.sql

The second part of your question is unrelated to procedures - please could you raise it as a separate issue if necessary?
