### ISSUE TITLE
About PCT

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#193]
I want to get the PCT (procalcitonin) value, but neither of LABEVENTS or CHARTEVENTS table contains it, why? Does it mean that the hospital dosen't have PCT tested?

**Comment by tompollard** [comment]
Yes, that's possible. Please could you explain how you've tried searching and post your queries?

**Comment by mylanhong** [comment]
@tompollard  I just searched for "PCT" and "procalcitonin" in D_ITEMS table and D_LABITEMS table.

**Comment by alistairewj** [comment]
Procalcitonin is not measured for ICU patients at the hospital where MIMIC is sourced.
