### ISSUE TITLE
The duplicating key value problem

### ISSUE THREAD

**Issue by badshihi** [MIT-LCP/mimic-code#194]
When I followed the instructions from https://mimic.physionet.org/tutorials/install-mimic-locally-windows/ the shell always called error as follow :"duplicate key value violates unique constrain 'd_icd_diag_code_unique'." while I have checked the raw source CSV files but they're OK. So I am wondering what's wrong with this step?

**Comment by tompollard** [comment]
@badshihi It sounds like you are trying to load the data into the same table twice. If the table already contains data, then loading it again will raise a "duplicate key" error.

**Comment by badshihi** [comment]
@tompollard I had the same thought like you, but I'd checked those tables and there're all unique, I mean the raw_id maybe the same but the other contants are different.

**Comment by tompollard** [comment]
> @tompollard I had the same thought like you, but I'd checked those tables and there're all unique, I mean the raw_id maybe the same but the other contants are different.

@badshihi I think you have misunderstood my comment. Yes, the rows are unique in the CSV files. If you get a duplicate key error when you try loading the data into your database, then it is likely you are loading the data into a table that already contains the same data. 

The constraint is intentionally preventing you from doing this. I'll close this issue for now, but you can reopen it if you discover that this isn't the problem.
