### ISSUE TITLE
ER Diagram and List of tables decription PDF

### ISSUE THREAD

**Issue by MayukhaC** [MIT-LCP/mimic-code#197]
For MIMIC-iii, it would be great if there is a PDF that can be downloaded with the description of all the tables. Also, having an ER diagram on the website would be more user-friendly instead of going through all the tables to get the relations between the tables.

**Comment by alistairewj** [comment]
See #183 for a diagram, there were a few issues before we planned to put it on the website.

I've raised these as issues at the website repo: https://github.com/MIT-LCP/mimic-website/issues/68 and https://github.com/MIT-LCP/mimic-website/issues/69

Cheers!
