### ISSUE TITLE
Filtering the patients who had Tracheostomies

### ISSUE THREAD

**Issue by shoyone** [MIT-LCP/mimic-code#198]
Hello Support team,

We analysis team want to filter the patients who had Tracheostomies within 5 days of intubation.
(we actually want to exclude those patients as exception)

We use "ventilation-durations.sql" to define intubation durations (ventilation-duration).
I saw all columns in MIMIC - III tables but it seems there is no related column.
In addition, when I saw d_icd_procedures table, it seemed there is some related cells in long_title column but looked difficult to connect d_icd_procedures table to procedureevents_mv table and procedures_icd table because of the reasons below.

procedureevents_mv table --> no icd9_code
procedures_icd table --> no time column to filter the right patients

We would really appreciate it if you would advise us how to pull the data regarding Tracheostomies

Thank you for your support in advance.

**Comment by alistairewj** [comment]
The best method of identifying exactly when a tracheostomy occurred would be to use charted data available in CHARTEVENTS. A quick query of D_ITEMS shows there are quite a few `itemid` used! If you do determine onset of tracheostomy we welcome pull requests :)

`select itemid, label, linksto, dbsource from d_items where lower(label) like '%trach%';`

 itemid |               label                |      linksto       |  dbsource  
------- | ---------------------------------- | ------------------ | -----------
    940 | trach care                         | chartevents        | carevue
    970 | TRACH CARE                         | chartevents        | carevue
    977 | TRACHE CARE                        | chartevents        | carevue
   1022 | Trach care                         | chartevents        | carevue
   1091 | Trach Insert Date                  | chartevents        | carevue
   1120 | trach                              | chartevents        | carevue
   4588 | trach aspirate                     | chartevents        | carevue
   4603 | Trach/Size                         | chartevents        | carevue
   4441 | trach care/site                    | chartevents        | carevue
   4459 | trach collar                       | chartevents        | carevue
    647 | Spare Trach Present                | chartevents        | carevue
    687 | Trach Care                         | chartevents        | carevue
    688 | Trach [Cuff]                       | chartevents        | carevue
    689 | Trach Date                         | chartevents        | carevue
    690 | Trach Size                         | chartevents        | carevue
    691 | Tracheostomy Cuff                  | chartevents        | carevue
    692 | Tracheostomy Type                  | chartevents        | carevue
   1832 | Trach care.                        | chartevents        | carevue
   1855 | TRACH care                         | chartevents        | carevue
   1948 | Trache Care                        | chartevents        | carevue
   8138 | Trach Sx Color                     | chartevents        | carevue
   8139 | Trach Sx Quantity                  | chartevents        | carevue
   8140 | Trach Sx Quality                   | chartevents        | carevue
   6032 | TRACH CUFF TAKENDOWN               | chartevents        | carevue
   6084 | TRACH SITE                         | chartevents        | carevue
   5646 | trach ties                         | chartevents        | carevue
   5767 | trach button                       | chartevents        | carevue
   1489 | Transtracheal                      | chartevents        | carevue
   2877 | trach collar trial                 | chartevents        | carevue
   2993 | trache care                        | chartevents        | carevue
   6151 | TRACHEOSTOMY CARE                  | chartevents        | carevue
   8170 | trach postion/stoma                | chartevents        | carevue
   8183 | trach mark location                | chartevents        | carevue
   8287 | trach press                        | chartevents        | carevue
   6375 | Trache care                        | chartevents        | carevue
   7118 | Trache                             | chartevents        | carevue
   7286 | trache                             | chartevents        | carevue
   7385 | bivona trach measure               | chartevents        | carevue
   7474 | trach mark                         | chartevents        | carevue
   7528 | TRACH MARK                         | chartevents        | carevue
   7689 | trach tube mark                    | chartevents        | carevue
   8479 | Trach [Fenestra]                   | chartevents        | carevue
   6898 | TRACHEA DSG                        | chartevents        | carevue
 227130 | Trach Care                         | chartevents        | metavision
 225590 | Tracheal Confirmation (Intubation) | chartevents        | metavision
 225448 | Percutaneous Tracheostomy          | procedureevents_mv | metavision
  70072 | TRACHEAL ASPIRATE                  | microbiologyevents | hospital
  80147 | CHLAMYDIA TRACHOMATIS              | microbiologyevents | hospital
 224864 | ZTrach Care                        | chartevents        | metavision
 224829 | Trach Tube Type                    | chartevents        | metavision
 224830 | Trach Tube Manufacturer            | chartevents        | metavision
 224831 | Trach Tube Size (I.D.)             | chartevents        | metavision
 226237 | Open Tracheostomy                  | procedureevents_mv | metavision

**Comment by shoyone** [comment]
@alistairewj Thanks for your reply. I will try to filter Tracheostomies referring to your answer.
