### ISSUE TITLE
Sequence in diagnoses_icd table

### ISSUE THREAD

**Issue by ZexCeedd** [MIT-LCP/mimic-code#199]
Hi Support Team,

It is mentioned that the SEQ_NUM provides the order in which the ICD diagnoses relates to the patient and is ordered by priority, such that the below HADM_ID subset holds true.

![image](https://cloud.githubusercontent.com/assets/23617509/25185745/c09c652a-2550-11e7-8fcb-ec043bdf2003.png)

If the above is correct, could you kindly **elaborate on what is meant by "Priority" and "Relevance"?**
Is this the severity of the medical diagnosis as determined by the doctor?
Also, how is this **sequence derived**, the **logic utilized** and the **person** or actor involved?

Is this also applied for the SEQ_NUM in procedures_icd table?

Would also like to confirm that each set of ICD diagnoses are derived or **based on each admission** (i.e. HADM_ID) and **not** the SUBJECT_ID.

Lastly,  it is mentioned that the sequence relates to **billing and reimbursement.**
Does this mean that the sequence is based on **cost** instead of priority, given that the most expensive diagnosis would be at the top priority?

I am unclear on how billing is related to this sequence if it is by priority as the most relevant diagnosis does not mean that it is the most expensive.

Appreciate the advice.

Thanks!

**Comment by alistairewj** [comment]
The truth is the exact mechanism by which these codes are assigned is extremely complicated, and any answer we give you would be incorrect to some degree. All of these codes are assigned by trained professional coders reviewing physician signed notes. These coders carefully assign codes as appropriate, contacting a physician who took care of the patient if any clarification is needed.

Commonly, people treat SEQ_NUM = 1 as the primary diagnosis. Of course this is not entirely correct, for example in the new ICD-10 coding rules cases of severe sepsis should have the underlying infectious process be coded first, followed by a code for severe sepsis. I'm sure similar cases occur with ICD-9 coding. Largely, SEQ_NUM will correlate with the primacy of a diagnosis: a diagnosis with SEQ_NUM = 1 will be more relevant to the patient stay than a diagnosis with SEQ_NUM = 9, but it gets a bit more fuzzy with less obviously difference sequence numbers.

At the very least I can confirm that these codes are based on each admission, and each HADM_ID will have its own set of ICD-9 codes!

**Comment by ZexCeedd** [comment]
Thanks for the reply.

My main concern is the integrity and truthfulness of this SEQ_NUM to justify its usages. Just for ICD 9 alone, it should be a fact that across all admissions, SEQ_NUM 2 will always be less relevant than SEQ_NUM 1, similarly for SEQ_NUM 3 and 2 respectively and so on. Can I check if this is confirmed for ICD 9 alone, as provided in dataset?

Also, in procedures_icd table, _"PROC_SEQ_NUM provides the order in which the procedures were performed"_. Can I similarly check if the integrity of this sequence is confirmed such that it can potentially be used for research purposes?

**Comment by tompollard** [comment]
@ZexCeedd does the word 'relevance' appear in the documentation somewhere? If so, it should probably be changed, because the word is misleading without clear context. 

> Just for ICD 9 alone, it should be a fact that across all admissions, SEQ_NUM 2 will always be less relevant than SEQ_NUM 1, similarly for SEQ_NUM 3 and 2 respectively and so on.

My understanding is that this statement is *not* correct (or at least we don't have enough information to make this assumption). From conversations with hospital staff, seq_num = 1 typically indicates the primary reason for admission, but for seq_num > 1 the order is less meaningful and does not directly link to a concept of 'relevance'.

> Essentially, how accurate are these two sequence numbers? I would believe that the procedures sequence numbers are highly accurate as it seems to me that it is easier and less subjective for the human coders to annotate the sequencing as the procedures involved in an admission should be explicit and obvious.

We will ask for more detail from the coding team when we have the opportunity.

**Comment by ZexCeedd** [comment]
> SEQ_NUM provides the order in which the ICD diagnoses **relate** to the patient. ICD diagnoses are **ordered by priority** - and the order does have an impact on the reimbursement for treatment.

@tompollard Perhaps it is clearer to say that the order is "ordered by priority". Specifically, SEQ_NUM 1 has more priority than SEQ_NUM 2, similarly for SEQ_NUM 2 and SEQ_NUM 3 respectively and so on, where the entire sequence is ordered in decreasing priority since SEQ_NUM 1 is the main diagnosis.

> My understanding is that this statement is not correct (or at least we don't have enough information to make this assumption). From conversations with hospital staff, seq_num = 1 typically indicates the primary reason for admission, but for seq_num > 1 the order is less meaningful and does not directly link to a concept of 'relevance'.

Does it link to the concept of 'priority' then, as stated? As it is stated that the order is indeed by priority, intuitively, I would assume that for each admission, the sequence numbers informs me the decreasing priority, starting from SEQ_NUM 1. 

This means that for each admission, SEQ_NUM 5 is always of lesser priority than SEQ_NUM 4, applies similarly for SEQ_NUM 4 of lesser priority than SEQ_NUM 3, and so on. If the fact is that these sequence numbers are not ordered by priority (i.e. not even an ordered sequence at all). Then this is not an ordered sequence in the first place.

**Comment by tompollard** [comment]
@ZexCeedd 'Priority' suffers the same problem as 'relevance', in that the word needs context (e.g. prioritised by cost, time of occurrence, severity, ... ?).  Without the context, it is meaningless to put weight on the importance of the ordering. 

The data that you see is the data that is recorded. I agree that clarification is needed on how seq_num is assigned, and we will try to get more detail.

**Comment by ZexCeedd** [comment]
@tompollard Thanks, appreciate the help.
