### ISSUE TITLE
MIMIC III Waveform dates

### ISSUE THREAD

**Issue by ZexCeedd** [MIT-LCP/mimic-code#201]
Hi,

In the noteevents table, for the notes category of "ECG", are there actual Waveforms or other indicators provided that the physicians or nurses have used to derive the ECG notes? I had tried looking at MIMIC III matched Waveforms but the dates does not correspond with the ECG notes of those specific subjects.

Is there an available specific set of waveforms that is used by the physician to derive these ECG notes?

Thanks

**Comment by alistairewj** [comment]
The ECG waveforms used for interpretation in the notes are currently unavailable.
