### ISSUE TITLE
urine-output-first-day : input of GU irrigant as a negative volume

### ISSUE THREAD

**Issue by shoyone** [MIT-LCP/mimic-code#204]
Hi Support team,

I just would like to verify your comment in urine-output-first-day.sql.
In line 13, there is a comment, "we consider input of GU irrigant as a negative volume" and ID 227489 is used but when I see the line 53 and 54 in the SQL file, it seemed we should use ID 227488 as negative value.

227488, -- GU Irrigant Volume In
227489 -- GU Irrigant/Urine Volume Out

I would appreciate it if you would give me your thoughts.

**Comment by alistairewj** [comment]
I double checked the hospital formulas and it turns out they simply add `GU Irrigant out` when calculating total urine output, and they don't take into consideration `GU irrigant in`. I adopted your suggestion to swap the signs and kept `GU irrigant in`, since it seems appropriate.

**Comment by shoyone** [comment]
@alistairewj 
Thank you for fixing this issue.

Accoding to your comments, Could we just ignore GU irrigant in?
I used our new first day SQL with changing only data period and some patients' results were minus values. This is because we changed 'GU irrigant in' numbers to minus values intently.

In addition, I checked outputevents table filtered itemids related to urine-output and then I found minus numbers in itemid= 226560 (Void). Are those records errors/outliers?
(I refered to urine-output-first-day.sql in terms of urine-output)

<img width="1087" alt="2017-05-22 17 27 36" src="https://cloud.githubusercontent.com/assets/25365228/26298996/2edbbc3e-3f14-11e7-9d85-a1ee6ca95a2a.png">

Thank you in advance.

**Comment by alistairewj** [comment]
Yes, I suppose you could ignore GU irrigant. The effect is probably small.

I'm not sure exactly why there are negative void values - but my hunch is
it's a transcription error. Either they accidentally added the minus sign,
or the staff may have wanted to incorporate fluid administration to the
patient, but instead of documenting it in a "past fluids received" section
they documented it under void.

**Comment by alistairewj** [comment]
I should mention, I always like to check the notes for any hints when I'm
not sure about situations like these - you should try the same!

**Comment by shoyone** [comment]
Thanks, appreciate the help!

**Comment by alistairewj** [comment]
No problem.
