### ISSUE TITLE
Medications in PRESCRIPTIONS and INPUTEVENTS tables

### ISSUE THREAD

**Issue by jakeykj** [MIT-LCP/mimic-code#205]
Hi there,

Thanks for providing such a great data set! I am particularly interested in extracting medication information from the data set, namely extracting what drugs have been used and how much the drugs been used for a particular hadm_id. But I notice that the 'PRESCRIPTIONS' and 'INPUTEVENTS' tables both contain medication information. So I am confused about the following questions:

1. What are the differences between the medication information in these two tables?
2. Is it possible to extract exactly how much the drugs been used during a hospital admission?

Thank you in advance!

**Comment by alistairewj** [comment]
Glad you find the dataset useful. The prescriptions table is just that: prescribed medications. It does not guarantee any form of administration. On the other hand, the inputevents tables contain information on intravenously administered medication, and will tell you the exact amount administered. There is an obvious gap for oral drugs, where you will know that it was prescribed but not if it was given. So the answers to your questions depend on which medications you are interested in.

**Comment by jakeykj** [comment]
Thanks for your reply which is really helpful, I would also like to know more about the 'FORMULARY_DRUG_CD' in table 'PRESCRIPTIONS': what is formulary_durg_cd? Is it a widely-used code system? Can I use it as an identifier of drugs? Thank you.

**Comment by alistairewj** [comment]
You can use it as an identifier, though I'm not sure how widely used it is.
It may be specific to the hospital.

**Comment by jakeykj** [comment]
It's very helpful, thanks!
