### ISSUE TITLE
Data source: hospital vs. ICU

### ISSUE THREAD

**Issue by chris20881** [MIT-LCP/mimic-code#206]
Hi,
Thank you for the fantastic data!
Can I check please? on page https://mimic.physionet.org/mimicdata/datatypes/ it is noted that some tables  are sourced from hospital data and don't necessarily relate to ICU stays.
I am interested in the prescriptions and microbiologyevents tables - the question is, are these known to contain all prescriptions and microbiology results from entire hospital stays, or is it more that they may contain information that are not from ICU stays?
Thank you, Chris

**Comment by alistairewj** [comment]
The microbiology table does indeed have all fluid cultures from the patients' hospital stays. I am not sure about prescriptions but I will ask - I think it does.

**Comment by yuziGuo** [comment]
Hi, thanks for you data, and I have the question too. And I am wondering, does data in prescriptions corresponds to records in the input tables?
For example there are many lines corresponding to ICUSTAY_ID '283359' in table inputevents_cv, and we can see what was prescripted to the patient, but we can find nothing in the prescription table.

**Comment by alistairewj** [comment]
See https://github.com/MIT-LCP/mimic-code/issues/345 for some potential ambiguity when using `icustay_id` with prescriptions - it's likely better to use that table by joining to `hadm_id`, taking care not to duplicate rows.

 In general, yes, if they have an intravenous medication (recorded in inputevents_cv), then they should have prescription information recorded in prescriptions. But, all the usual caveats apply: system outages, emergency administrations, paper prescriptions, etc. Don't expect perfect correspondence. You may also find this thread helpful https://github.com/MIT-LCP/mimic-code/issues/347 as they are investigating a specific medication and the correspondence between prescriptions/inputevents.

**Comment by alistairewj** [comment]
Also, to answer the original question (sorry for the delay!), a query gives us some confidence:

```sql
select hadm_id, icustay_id, startdate, enddate, drug from prescriptions where hadm_id = 100262 order by hadm_id, startdate;
```

We can see that there are frequently prescriptions outside of the ICU stay so likely prescriptions are available.
