### ISSUE TITLE
Identify postoperative ICU admissions?

### ISSUE THREAD

**Issue by fkork** [MIT-LCP/mimic-code#207]
Is there a way to identify postoperative ICU admissions? I tried to identify the date of surgery from the CPTEVENTS table, but for surgery CPT codes there are no CHARTTIME stamps available. In the ICD table there is no date or time stamp at all. 

Can anyone think of another way?

Many thanks in advance, 
Felix

**Comment by alistairewj** [comment]
HCUP with AHRQ provide code for identifying surgical admissions using ICD-9 procedure codes - which is my best suggestion. I'm not sure how you would identify the timing of the surgery (i.e. whether it's before or after the ICU admission).
