### ISSUE TITLE
about  DOD_SNN.

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#208]
Since the current version of the MIMIC-III Clinical Database is 1.4 (4 September 2016), is that mean, those patients with a null DOD_SNN were alive before 4 September 2016. If so, how can I calculate the time difference between the admission time and 4 September 2016, since the admission time is not true time.

**Comment by alistairewj** [comment]
The censor time between a patient's ICU discharge and their death is 90
days. Most patients have more (e.g. since MIMIC lasts 10 years, 9/10ths of
the patients have censor times over a year), but 90 days is the minimum.
