### ISSUE TITLE
Discharge before admission?

### ISSUE THREAD

**Issue by pszolovits** [MIT-LCP/mimic-code#209]
In MIMIC-III v1.4, the query
select * from admissions where admittime > dischtime;
finds 98 rows. Any ideas on why?

**Comment by alistairewj** [comment]
They're pretty much all administrative errors.

```
select * from admissions where admittime > dischtime and extract(day from admittime) != extract(day from dischtime);
```

.. returns 0 rows, which means that every time `admittime > dischtime`, both the admission and discharge were on the same day. The exact nature of the error varies: maybe they swapped the admission/discharge time, or typed "12:00:00" when they meant midnight "00:00:00", etc. A very small number are for patients who were organ donors. Sometimes they readmit the patient to the hospital under a new `hadm_id`, in which case the patient's discharge time is the time of their actual death, before the "readmission". But that's only a handful: most of these are just errors.
