### ISSUE TITLE
MIMIC website has wrong information about diagnoses_icd 

### ISSUE THREAD

**Issue by key2imagination** [MIT-LCP/mimic-code#21]
On this page, https://mimic.physionet.org/mimictables/diagnoses_icd/, it is said that table diagnoses_icd has a column "description" of type VARCHAR(30); it is missing from the actual csv file, but still referred to by the indexing script posted here: https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/postgres_add_indexes.sql 

When running the indexing script, the error message shown by Postgres is as follows:
psql:postgres_add_indexes.sql:29: ERROR: column description does not exist

Since d_icd_diagnoses includes both short and long title of each icd-9 code used in the diagnoses_icd table, I recommend that modifying the MIMIC website page to remove the description entry.

**Comment by alistairewj** [comment]
You are correct, thank you for reporting this.

The description column was originally erroneously included in this table. It's inclusion implies that the column is collected with the raw data: *it is not*. As a result, we removed the column from the raw data. However, some scripts were not updated, as you have dutifully noticed.

I have updated the website to reflect the change (side note: we also have a repository for the website here https://github.com/MIT-LCP/mimic-website if you are interested) - if you have updated the scripts in this repository to reflect this change we would more than welcome a pull request!
