### ISSUE TITLE
mimic-iii Database  about D_ITEMS (itemid=190 label=FiO2 SET) unit is torr,but what is torr  

### ISSUE THREAD

**Issue by ypc8272805** [MIT-LCP/mimic-code#211]
PLEASE HELP
sorry,everyone 
Now, I find a problem about FiO2 
FiO2 is Fraction of inspiration O2, FiO2 's unit is %
torr is a pressure unit ,1torr=133.322Pa=1mmHg
but in table D_ITEMS ,itemid=190  label="FiO2 SET" ，use this itemid to find in table chartevents ,
FiO2 SET  unit is torr ,I do not how to use this variable(itemid=190 label='FiO2 SET') or how to conversion between torr and %.
![123_](https://cloud.githubusercontent.com/assets/28589340/25888318/412fec00-3598-11e7-8090-cfa40f449a27.jpg)

**Comment by alistairewj** [comment]
The actual unit is not torr. The unit is a proportion (0-1) as you correctly observe. This is a flaw in the underlying data: for some reason they stored the incorrect unit name. As a policy we limit the amount of preprocessing we perform, so you may find cases like this from time to time.
