### ISSUE TITLE
Missing Antenatal Corticosteroids Information

### ISSUE THREAD

**Issue by SuneynaB** [MIT-LCP/mimic-code#212]
Hi,

Introduction of Antenatal Corticosteroids to the pregnant women is an essential medical procedure in case of preterm deliveries and generally given before few days of delivery. 

However, we are not able to find this information in any of the MIMIC III tables (items, diagnosis or procedures).

If anyone knows the keyword(s) and/or the ID(s) to fetch this information from MIMIC III data, Please let us know.

Thanks and Regards
Suneyna

**Comment by tompollard** [comment]
The [prescriptions table](https://mimic.physionet.org/mimictables/prescriptions/) is a record of medications that were ordered (though not necessarily administered), so this would be a good starting point. As a crude example, searching for for 'dexamethasone' returns ~3100 unique subject_ids:

```
SELECT COUNT(DISTINCT subject_id) 
FROM prescriptions 
WHERE LOWER(drug) LIKE '%dexamethasone%';

 count 
-------
  3159
```
