### ISSUE TITLE
Mapping Mother SUBJECT_ID to Newborn SUBJECT_ID

### ISSUE THREAD

**Issue by SuneynaB** [MIT-LCP/mimic-code#213]
Hi,

I am wondering if there is a mapping between the mother subject id to the 'NEWBORN' subject id in 
MIMIC III. e.g. In case of preterm births, newborns will always shifted to the ICU after delivery.

If someone guide us from which table and column header of MIMIC III are capturing this information.

Thanks and Regards
Suneyna

**Comment by tompollard** [comment]
Hi @SuneynaB, there is no mapping between mother and child in MIMIC-III. Attempting to infer these relationships would be very difficult at best, because the data needed for linking has largely been scrubbed (patient ids, dates, locations, etc).
