### ISSUE TITLE
NEONATES DATA SEPARATE

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#214]
Dear sir
how can we separate neonates data and convert it into a csv file?

**Comment by tompollard** [comment]
You haven’t explained what data should be included in the CSV, but starting point would be to identify the cohort by:

- loading the icustay_detail view using the code at: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/demographics/icustay_detail.sql
- selecting the neonates with: `SELECT * FROM icustay_detail WHERE LOWER(admission_type) LIKE '%newborn%’;`
- exporting from Postgres to CSV using the copy statement (e.g. `COPY (SELECT * FROM icustay_detail WHERE LOWER(admission_type) LIKE '%newborn%’) TO ’neonates.csv`;
