### ISSUE TITLE
Data takes a long time to load

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#215]
Respected sir
after creating the able we were trying to load the data. We waited for almost three hours and the data loading did not completed?
i am sending you the screen shot
![12](https://cloud.githubusercontent.com/assets/27729999/26025935/9a9e7be8-380f-11e7-8204-393e3b260805.png)

**Comment by tompollard** [comment]
From the screenshot everything seems fine, but you will need to be patient. The chartevents table in particular can take a long time to load (several hours), so I would suggest leaving the database to build overnight (ps. Not everyone here is male @erjthakur!).
