### ISSUE TITLE
Extracting Neonates data for sepsis

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#216]
Respected Sir/Mam,

I have two questions:-

1) Has Thomas Desautels et. al shared the code for their published paper "Prediction of sepsis in the intensive care unit with minimal electronic health record data: a machine learning approach" as they have used MIMIC III database for research?

2) How can i extract the data for neonatal sepsis in one CSV FILE which contains the following parameters of neonate:-
1) subect id
2) gender
3) date and time at which blood was taken for blood culture.
4) date and time the blood culture report was available
5) whether neonate has sepsis
5) blood pressure, temperature, crp, heart rate, breath rate at a window 10hours before and after the blood was taken for blood culture.

Regards

**Comment by alistairewj** [comment]
The authors of that paper have not posted their code here, though they would be welcome to and you are welcome to inquire with them about it!

In regards to your other questions, unfortunately you are not likely to receive a response to such a general data extraction request. While the tools and resources provided here will help you significantly, you will still have to make your own data extraction decisions for your study.

Some starting advice:

* you can find subject_id/gender in the `patients` table https://mimic.physionet.org/mimictables/patients/
* all blood cultures are present in `microbiologyevents`, so simply select from this table https://mimic.physionet.org/mimictables/microbiologyevents/
* the time the blood culture report was available is not in the database
* you will need to define sepsis for neonates as you see fit
* there is code to extracts vital signs for the first day ( https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/vitals-first-day.sql ) and laboratory measurements ( https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/labs-first-day.sql ) for the first day - you could adapt this to the before/after a blood culture with some work
