### ISSUE TITLE
Regarding an diagnosis 'apnea'?

### ISSUE THREAD

**Issue by SuneynaB** [MIT-LCP/mimic-code#219]
From which table, we can extract the information that whether the patient was responsive to stimulation, unresponsive to stimulation or had complete apnea?

**Comment by alistairewj** [comment]
For diagnoses (like apnea), your best bet for hospital diagnoses is the diagnoses_icd table: https://mimic.physionet.org/mimictables/diagnoses_icd/

Otherwise, you'll need to go through the d_items tables and find if there is any suitable charted data about the concept you're interested in.
