### ISSUE TITLE
Update build scripts for updated v1.2 schema

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#22]
The scripts for building MIMIC will need to be updated to account for the changes between version 1.1 and version 1.2. These include:

- the icustayevents table has been renamed to icustays
- ioevents has been replaced with inputevents_mv, inputevents_cv, outputevents
- renamed columns in DIAGNOSES_ICD and PROCEDURES_ICD tables

**Comment by alistairewj** [comment]
All the PostgreSQL scripts have been updated for v1.3. Worth checking if MySQL is.
