### ISSUE TITLE
Immature total ratio?

### ISSUE THREAD

**Issue by SuneynaB** [MIT-LCP/mimic-code#220]
Hi All,

Does mimic3 capture for Immature total ratio? If yes where to find this information?
It is not present in lab_items and chart_items.

Regards
Suneyna

**Comment by alistairewj** [comment]
All laboratory measurements available are described in d_labitems and stored in labevents. If you didn't find it, it's likely not available. Make sure you look for synonyms - e.g. white blood cell count is sometimes called WBC, leukocytes, etc.
