### ISSUE TITLE
Serum pH?

### ISSUE THREAD

**Issue by SuneynaB** [MIT-LCP/mimic-code#221]
Hi All,

Mimic3 data doesn’t have serum as fluid type in lab_items label. It has blood and other fluid as types of fluids. 

So for example in place of serum pH, should we use blood pH or other fluid pH or none of these?

Regards
Suneyna

**Comment by alistairewj** [comment]
Typically I use blood pH to get an idea of acid/base status of the systemic circulation - but it depends on the context of your question. Other fluid pH will vary wildly, because the fluid could be anything.
