### ISSUE TITLE
postgres_create_tables.sql

### ISSUE THREAD

**Issue by mzhao94** [MIT-LCP/mimic-code#224]
I am trying to run the postgres_create_tables.sql file as per step 6 in this tutorial https://mimic.physionet.org/tutorials/install-mimic-locally-ubuntu/. I have completed steps 1-4, but the output for this command: psql 'dbname=mimic user=mimic options=--search_path=mimiciii' -f postgres_create_tables.sql does not match the output in step 6 of the tutorial. 

Output:
psql:postgres_create_tables.sql:31: NOTICE:  table "admissions" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:postgres_create_tables.sql:61: NOTICE:  table "callout" does not exist, skipping
DROP TABLE
CREATE TABLE

I know that in the actual sql files it states that I should "Set the mimic_data_dir variable to point to directory containing all .csv files," but where do I set this variable? Are there any additional things I need to do in order to successfully run the postgres_create_tables.sql file?

**Comment by EdwardMoseley** [comment]
I believe "postgres_create_tables.sql" clears a number of tables from your Postgres environment first as a precaution-- whether they exist or not-- so you can expect those notices from Postgres.

At the 6th step in the tutorial, here is the command where you define the directory with the MIMIC .csv files (specifically: mimic_data_dir='<path/to/data>'):

psql 'dbname=mimic user=mimic options=--search_path=mimiciii' -f postgres_load_data.sql -v mimic_data_dir='<path_to_data>'

**Comment by alistairewj** [comment]
Yep, @EdwardMoseley is correct! The notices are just there to scare you :)
