### ISSUE TITLE
ITEMID in chartevents table

### ISSUE THREAD

**Issue by satyanshukla** [MIT-LCP/mimic-code#225]
I am trying to extract vitals such as heart rate, respiratory rate, blood pressure etc. from the chartevents table but there is no description available for linking the ITEMID mentioned in the chartevents table to the vitals.

**Comment by tompollard** [comment]
@satyanshukla You'll need to first identify the relevant itemids in the [d_items table](https://mimic.physionet.org/mimictables/d_items/). 

If you are interested in vital signs, then take a look at the following "first day vitals" query as a starting point: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/vitals-first-day.sql

**Comment by momih** [comment]
Sorry for commenting on an old issue, I didn't want to open a new one for this small question.

I've extracted a subset of CHARTEVENTS where 742 is one of the most frequent ITEMIDs. Looking it up in D_ITEMS I get 'calprevflg'. What is calprevflg exactly? I've tried googling but I don't get any definition

**Comment by alistairewj** [comment]
I've never really figured it out - none of the nursing staff ever used it. I think it's a system flag to do with importing data from the monitor. I would ignore it as it's always the same value.

**Comment by alistairewj** [comment]
P.S. it would have been fine to open a new issue for this - even if it's a simple question!

**Comment by momih** [comment]
Haha thanks for answering so quickly.
