### ISSUE TITLE
NEONATES TEMPERATURE AND OTHER INFORMATION NOT AVAILABLE

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#228]
"please help"

Using the following query i tries to extracted vitals of neonates.
but this query returned only heart rate related information, whereas other information was null.
even parameters like temperature, sp02, Blood Pressure etc are null.

Can you please tell us that is there a problem with our query or mimiciii data set does not contain these information.

The query that i used to Extract information was:-

DROP MATERIALIZED VIEW IF EXISTS vitalsfirstday CASCADE;
create materialized view vitalsfirstday as
SELECT pvt.subject_id,pvt.isolate_num

-- Easier names
, min(case when VitalID = 1 then valuenum else null end) as HeartRate_Min
, max(case when VitalID = 1 then valuenum else null end) as HeartRate_Max
, avg(case when VitalID = 1 then valuenum else null end) as HeartRate_Mean
, min(case when VitalID = 2 then valuenum else null end) as SysBP_Min
, max(case when VitalID = 2 then valuenum else null end) as SysBP_Max
, avg(case when VitalID = 2 then valuenum else null end) as SysBP_Mean
, min(case when VitalID = 3 then valuenum else null end) as DiasBP_Min
, max(case when VitalID = 3 then valuenum else null end) as DiasBP_Max
, avg(case when VitalID = 3 then valuenum else null end) as DiasBP_Mean
, min(case when VitalID = 4 then valuenum else null end) as MeanBP_Min
, max(case when VitalID = 4 then valuenum else null end) as MeanBP_Max
, avg(case when VitalID = 4 then valuenum else null end) as MeanBP_Mean
, min(case when VitalID = 5 then valuenum else null end) as RespRate_Min
, max(case when VitalID = 5 then valuenum else null end) as RespRate_Max
, avg(case when VitalID = 5 then valuenum else null end) as RespRate_Mean
, min(case when VitalID = 6 then valuenum else null end) as TempC_Min
, max(case when VitalID = 6 then valuenum else null end) as TempC_Max
, avg(case when VitalID = 6 then valuenum else null end) as TempC_Mean
, min(case when VitalID = 7 then valuenum else null end) as SpO2_Min
, max(case when VitalID = 7 then valuenum else null end) as SpO2_Max
, avg(case when VitalID = 7 then valuenum else null end) as SpO2_Mean
, min(case when VitalID = 8 then valuenum else null end) as Glucose_Min
, max(case when VitalID = 8 then valuenum else null end) as Glucose_Max
, avg(case when VitalID = 8 then valuenum else null end) as Glucose_Mean

FROM  (
  select ce.subject_id,mi.isolate_num
  , case
    when itemid in (211,220045) and valuenum > 0 and valuenum < 300 then 1 -- HeartRate
    when itemid in (51,442,455,6701,220179,220050) and valuenum > 0 and valuenum < 400 then 2 -- SysBP
    when itemid in (8368,8440,8441,8555,220180,220051) and valuenum > 0 and valuenum < 300 then 3 -- DiasBP
    when itemid in (456,52,6702,443,220052,220181,225312) and valuenum > 0 and valuenum < 300 then 4 -- MeanBP
    when itemid in (615,618,220210,224690) and valuenum > 0 and valuenum < 70 then 5 -- RespRate
    when itemid in (223761,678) and valuenum > 70 and valuenum < 120  then 6 -- TempF, converted to degC in valuenum call
    when itemid in (223762,676) and valuenum > 10 and valuenum < 50  then 6 -- TempC
    when itemid in (646,220277) and valuenum > 0 and valuenum <= 100 then 7 -- SpO2
    when itemid in (807,811,1529,3745,3744,225664,220621,226537) and valuenum > 0 then 8 -- Glucose

    else null end as VitalID
      -- convert F to C
  , case when itemid in (223761,678) then (valuenum-32)/1.8 else valuenum end as valuenum

  from (SELECT SUBJECT_ID, ISOLATE_NUM, CHARTTIME FROM MICROBIOLOGYEVENTS WHERE SPEC_TYPE_DESC='BLOOD CULTURE - NEONATE') mi
    -- chartevents ce
  left join (SELECT SUBJECT_ID, CHARTTIME, VALUENUM, VALUEUOM,ITEMID FROM CHARTEVENTS 
             WHERE CHARTEVENTS.SUBJECT_ID IN (SELECT MICROBIOLOGYEVENTS.SUBJECT_ID from MICROBIOLOGYEVENTS WHERE SPEC_TYPE_DESC = 'BLOOD CULTURE - NEONATE')
             AND 
             CHARTEVENTS.itemid in
  (
  -- HEART RATE
  211, --"Heart Rate"
  220045, --"Heart Rate"

  -- Systolic/diastolic

  51, --	Arterial BP [Systolic]
  442, --	Manual BP [Systolic]
  455, --	NBP [Systolic]
  6701, --	Arterial BP #2 [Systolic]
  220179, --	Non Invasive Blood Pressure systolic
  220050, --	Arterial Blood Pressure systolic

  8368, --	Arterial BP [Diastolic]
  8440, --	Manual BP [Diastolic]
  8441, --	NBP [Diastolic]
  8555, --	Arterial BP #2 [Diastolic]
  220180, --	Non Invasive Blood Pressure diastolic
  220051, --	Arterial Blood Pressure diastolic

  -- MEAN ARTERIAL PRESSURE
  456, --"NBP Mean"
  52, --"Arterial BP Mean"
  6702, --	Arterial BP Mean #2
  443, --	Manual BP Mean(calc)
  220052, --"Arterial Blood Pressure mean"
  220181, --"Non Invasive Blood Pressure mean"
  225312, --"ART BP mean"

  -- RESPIRATORY RATE
  618,--	Respiratory Rate
  615,--	Resp Rate (Total)
  220210,--	Respiratory Rate
  224690, --	Respiratory Rate (Total)

  -- SPO2, peripheral
  646, 220277,

  -- GLUCOSE, both lab and fingerstick
  807,--	Fingerstick Glucose
  811,--	Glucose (70-105)
  1529,--	Glucose
  3745,--	BloodGlucose
  3744,--	Blood Glucose
  225664,--	Glucose finger stick
  220621,--	Glucose (serum)
  226537,--	Glucose (whole blood)
  -- TEMPERATURE
  223762, -- "Temperature Celsius"
  676,	-- "Temperature C"
  223761, -- "Temperature Fahrenheit"
  678 --	"Temperature F"
  )
and chartevents.error IS DISTINCT FROM 1

)ce
  -- WHERE   ce
  on ce.subject_id = mi.subject_id 
  and ce.charttime between mi.charttime - interval '12 hour' and mi.charttime + interval '12' hour
  
 
) pvt
group by pvt.subject_id,pvt.isolate_num
order by pvt.subject_id,pvt.isolate_num;
commit;

And does mimiciii dataset contains birthweight of neonates or weight at any other time.

Regards.

**Comment by alistairewj** [comment]
Unfortunately we don't have the bandwidth to provide first level support on your querying. My suggestions are (1) look for other `itemid` values for the other vital signs as neonates frequently have data stored in a separate `itemid` to adults and (2) look for `itemid` related to weight in d_items linking to chartevents as I have certainly seen neonatal weights charted.

**Comment by erjthakur** [comment]
@alistairewj  Can you please confirm that
Was temperature and respiratory rate of neonates also charted?

**Comment by tompollard** [comment]
@erjthakur 

> Can you please confirm that Was temperature and respiratory rate of neonates also charted?

As Alistair has mentioned, we don't have the bandwidth to provide support for individual projects. If you spend some time looking over the data, you'll find your answer! I think it is likely that there will be temperature and respiratory rate for at least a subset of the patients.
