### ISSUE TITLE
MIMIC-II from MIMIC-III

### ISSUE THREAD

**Issue by visionnoob** [MIT-LCP/mimic-code#229]
Hi 

Is it possible to extract MIMIC-II patients/admission episodes from MIMIC-III. Pre-2015 papers used MIMIC-II and built their models on them. For benchmarking we would still like to have access to that cohort.

Since Metavision system was introduced in MIMIC-III, we thought of separating based on the datasource but there are inconsistences: 

There is a column in “icustays” table called “dbsource”, where 3 values are possible:
carevue, metavision, both.

The number of patients/admission for each value you can see in the following table: 

| dbsource   | Number of admissions | Number of patients |
|------------|----------------------|--------------------|
| both       |                  108 |                107 |
| carevue    |                35632 |              30328 |
| metavision |                22046 |              17710 |

However, there were 25549 patients in MIMIC-II database (carevue). Can you please help us?  

Another solution can be to install MIMIC 2 database but that won't allow us to seamlessly exchange code/sql scripts over MIMIC-II and MIMIC-III.

**Comment by pszolovits** [comment]
I suspect the numbers depend on exactly which version of which database you are using. For example, I have an older copy of the MIMIC-II data, version 2.6, in which d_patients has 32535 entries and admissions has 36094. Where did your number of 25549 come from?

**Comment by alistairewj** [comment]
There is a lot of info on the various differences between MIMIC-II and MIMIC-III here: https://mimic.physionet.org/mimicdata/whatsnew/

Specifically, we note that we replaced censusevents in MIMIC-II with transfers in MIMIC-III: https://mimic.physionet.org/mimicdata/whatsnew/#censusevents-replaced-by-transfers
We also note that `icustay_id` is not backward compatible: https://mimic.physionet.org/mimicdata/whatsnew/#subject-id-hadm-id-and-icustay-id

Basically, MIMIC-II used the ICU information system to define ICU admissions. MIMIC-III uses a hospital wide patient tracking database to define ICU admissions. As a result, you get some inconsistencies, mainly revolving around administrative differences. An absolute mapping between the two is not possible. Essentially though, the patients who satisfy `dbsource='carevue'` are a pretty good approximation to patients in MIMIC-II. Given @pszolovits numbers, you can see it's pretty close (32,535 patients in MIMIC-II vs. 30,328 patients in MIMIC-III). I'm not also sure where you got the 25,549 number - maybe from an earlier version as @pszolovits suggests?

**Comment by alistairewj** [comment]
Closing as it seems we provided sufficient insight!
