### ISSUE TITLE
27883 ioevents.hadm_id are null. Why?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [MIT-LCP/mimic-code#23]
I see 27883 ioevents.hadm_id are null:

```sql
SELECT count(*) FROM  mimiciii.ioevents WHERE ioevents.hadm_id is null;
```

Bug or intended?

**Comment by alistairewj** [comment]
Intended. These are probably "floating" admissions: those which we couldn't
map to the hospital database but probably exist as they have ICU data.
