### ISSUE TITLE
OMOP CDM view of mimic III data

### ISSUE THREAD

**Issue by vojtechhuser** [MIT-LCP/mimic-code#230]
I would like to contribute to concept folder a view of the data that emulates some of the tables in the OMOP CDM.

Do all concept folder contribution get build automatically?

Is the syntax for any contributed view Postgres SQL flavor?

Do I just submit PR to the repo with concept/OMOP/person.sql code?
(if I want to start with person table?)

per readme file
>A Makefile build system has been created to facilitate the building of the MIMIC database, and >optionally contributed views from the community. Please refer to the Makefile guide for more details.

related link : http://forums.ohdsi.org/t/mimic2-and-possibly-mimic3-data-in-ohdsi-cdm-format/860

**Comment by alistairewj** [comment]
Yes - the makefile is quite simple though. It calls a single SQL script: `make-concepts.sql`. This script creates all the subsequent tables by calling all the various SQL files.

PostgreSQL (or "standard" SQL if you prefer) is the desired syntax. I think creating an individual folder like you suggest (OMOP) would work well.

**Comment by alistairewj** [comment]
We have another colleague looking into OMOP and its suitability for MIMIC-III. @parisni any comment?

**Comment by vojtechhuser** [comment]
Thanks for the comment. It would be great to have more people in the mimic-omop team. awaiting @parisni reply.....

**Comment by parisni** [comment]
Hi @vojtechhuser I plan to work on that topic too. I would be glad to collaborate. My goal is to have something working before 2018

**Comment by vojtechhuser** [comment]
Just an update - I just drafted PERSON table ETL. I am working with @parisni on this.  Anyone is welcome to chip in.

**Comment by vojtechhuser** [comment]
at OMOP symposium, number of other folks with mimicIII data in OMOP format were consulted. Please use this thread to report any outcomes.

**Comment by vojtechhuser** [comment]
This group from Georgia Tech also has m3 mapping - See here: https://github.com/gt-health/omop_etl_public/blob/master/dataset_mappings/mimic3/mimic_stage_insert.sql

**Comment by alistairewj** [comment]
The mapping of MIMIC to OMOP is being carried out in a separate repository: https://github.com/MIT-LCP/mimic-omop/

Contributions welcome!

**Comment by malcolmm83** [comment]
Looks good.  Any ideas on sizing?  The mimic-code project says I should give my Postgres about 100G providing room for the mimic tables, indexes and etc.  I guess I need to add to that for the OMOP tables.  Are they going to be bigger or smaller than the raw mimic tables?
