### ISSUE TITLE
BIRTHWEIGHT OF NEONATES IN cm

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#231]
After writing the following query we found that some of the unit of measurements of birth weight of neonates are given in cm. 
1) What does this signifies?
2 )Some of them has 0.66 Kg birth weight is this possible?
3) And out of 6580 neonates who had blood culture only 4080 has their birth weight charted?
4) Can you please confirm that Was temperature and respiratory rate of neonates also charted?

Regards
![weight](https://user-images.githubusercontent.com/27729999/26875210-7160fdf8-4b9e-11e7-9a11-c1e14218d55f.png)

**Comment by alistairewj** [comment]
Ultra low birthweight (<1000g) is possible but rare. Also be sure to use common sense for the value unit of measurement - this is raw data and don't expect it to always reflect the truth (e.g. I've seen some incorrect UOMs in the past).

Birth weights tend to only be in the ICU database if something prescribed requires dosing by body weight.

No idea about the temperature/resp rate for neonates - but it should be fairly easy to find out by querying D_ITEMS for `itemid` associated with respiratory rate and temperature.
