### ISSUE TITLE
Duration Of Crrt

### ISSUE THREAD

**Issue by will4906** [MIT-LCP/mimic-code#234]
Hello, We would like to calculate the the duration of crrt.But we couldn't find a exactly parameter of it.So, According to the itemid in [rrt.sql](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/rrt.sql), we decide to get the length by search the itemid in charevents and use the time difference of the first charttime and the last one to generate the duration of the Crrt.Is it right?
Here is someone's example, just like 2193-12-26 15:00:00 - 2193-12-16 10:00:00
```
+--------+---------------------+------------------+
| itemid | charttime           | value            |
+--------+---------------------+------------------+
|    582 | 2193-12-26 15:00:00 | EEG              |
|    582 | 2193-12-27 15:00:00 | NULL             |
|    582 | 2193-12-22 08:00:00 | MRI              |
|    582 | 2193-12-21 13:00:00 | Hemodialysis st  |
|    582 | 2193-12-18 11:00:00 | EEG              |
|    582 | 2193-12-16 11:00:00 | Cardiac Echo     |
|    582 | 2193-12-17 17:00:00 | MRI              |
|    582 | 2193-12-20 16:00:00 | Hemodialysis st  |
|    582 | 2193-12-21 18:00:00 | Hemodialysis end |
|    582 | 2193-12-16 10:00:00 | Urinalysis       |
|    582 | 2193-12-16 13:00:00 | Ultrasound       |
+--------+---------------------+------------------+
```
Could someone give us some advice of the duration of Crrt?

**Comment by alistairewj** [comment]
I had meant to post some queries related to CRRT much earlier but somehow time got away from me. I've just added two new files to the repository:

* [crrt-notebook.ipynb (commit c73e...)](https://github.com/MIT-LCP/mimic-code/blob/c73e51d8fb29dea7ccc60915ce0fe88406d61916/notebooks/crrt-notebook.ipynb) - This overviews the process that was done to extract CRRT. It's a good introduction to how data extraction is done in the MIMIC-III database.
* [crrt-durations.sql (commit c73e...)](https://github.com/MIT-LCP/mimic-code/blob/c73e51d8fb29dea7ccc60915ce0fe88406d61916/concepts/durations/crrt-durations.sql) - This query extracts the duration of all CRRT events for MIMIC-III patients

I hope you find this useful!
