### ISSUE TITLE
Existing conditions upon admission

### ISSUE THREAD

**Issue by yuanluo** [MIT-LCP/mimic-code#235]
Hi,
I want to find if a patient is admitted with Heart Failure. In particular, I do NOT want to include patients who developed Heart Failure during ICU admission. What is a reliable way of doing this? 

Best,
Yuan

**Comment by alistairewj** [comment]
I would recommend the comorbidities using algorithms from the AHRQ (based on a publication by Elixhauser et al.) or an algorithm by Quan et al.

Roughly, these use (i) ICD-9 billing codes to identify the condition and (ii) DRG codes to ensure the condition was a comorbidity and not the primary reason for hospitalization. These comorbidities are determined on hospital discharge.

See below:
https://github.com/MIT-LCP/mimic-code/tree/master/concepts/comorbidity

**Comment by yuanluo** [comment]
Changing the scenario a little bit (during -> before), but the answer may be different, please let me know if I should open another issue.
I want to find if a patient is admitted with Heart Failure. In particular, I do NOT want to include patients who developed Heart Failure **before** ICU admission. What is a reliable way of doing this?

Thanks,
Yuan

**Comment by alistairewj** [comment]
Our best way is using comorbidities. See #290 for some discussion.
