### ISSUE TITLE
Antibiotics in inputevents_cv

### ISSUE THREAD

**Issue by khamidova** [MIT-LCP/mimic-code#236]
Hi,
I would like to calculate for each patient the time when he/she first received antibiotics.

For "metavision" patients I select this information from the table "inputevents_mv" with itemids that have category "Antibiotics" in the "d_items" table:
`SELECT
	hadm_id,
	min(starttime) as first_antibiotics
FROM
	inputevents_mv
WHERE
	itemid IN (
		SELECT
			itemid
		FROM
			d_items
		WHERE
			category = 'Antibiotics'
	) AND statusdescription != 'Rewritten'
GROUP BY hadm_id
`

But for "carevue" patients I cannot find relevant items in the "d_items" table to filter "inputevents_cv" records.
Are there antibiotics in the "d_items" table sourced from carevue database?
Is there a way to calculate the time when the patient first received antibiotics for "carevue" patients? Could be the "prescriptions" table useful?

Thanks!

**Comment by alistairewj** [comment]
In fact I have been looking into this. I could not find any antibiotic documentation for CareVue patients. I think they simply didn't document it in the ICU clinical information system.

I believe the prescription table can be used as a surrogate. As I have access to the year, I've been able to make a useful plot over time which elucidates things:

![image](https://user-images.githubusercontent.com/1282676/27446936-23ab38ca-574d-11e7-9734-ddf70adf3295.png)

Here I am replicating the Sepsis-3 "suspicion of infection" algorithm: blood culture + anitbiotics. Focus on the middle of the graph: there are three methods presented. The top one is using the prescriptions table, the middle one is using the prescriptions table but *only* those with the route specified as IV, and finally the bottom line is using INPUTEVENTS_MV. As you can see, the bottom line is only available for MetaVision patients, which starts throughout 2008. However, for years after 2008, there is an excellent match between the the IV administration (which we 100% know was delivered to the patient) and the prescription methods (which indicate the antibiotic was ordered but can't guarantee it was administered). From this, I'd pretty confidently conclude that we can use the prescriptions table for determining onset of antibiotics.

I have been told by the pharmacy that the prescriptions data was not perfect until around 2007 - but looking at the data I can't see why they state that. It may be that antibiotics were well incorporated but other drugs were not. As always, caveat emptor.

**Comment by khamidova** [comment]
Dear Alistair,

Thank you for your answer!
Prescriptions table can be used to see which patients received antibiotics, but it has no information about charttime.
I have found in chartevents table rows with antibiotics as itemids (for example, itemid 4451 - Acyclovir) and value 'given'. I would use it for calculation of the "time since first antibiotics", maybe it would be useful for your tasks too.

**Comment by alistairewj** [comment]
Have you checked if these `itemid` are comprehensive? Or do they only occur for handfuls of patients?

**Comment by khamidova** [comment]
I think neither these `itemid` are comprehensive nor they occur for handfuls of patients.
There are 6872 "carevue" admissions with antibiotics charted in the "chartevents" table. At the same time I found 19919 distinct admissions with antibiotics (drug from the list and route "IV") in the "prescriptions" table. But there is no charttime which I need for my tasks.

You can check these `itemid` using a query from attached file.
[chartevents_abx_carevue.txt](https://github.com/MIT-LCP/mimic-code/files/1141747/chartevents_abx_carevue.txt)

**Comment by vrajaram** [comment]
@alistairewj  Thanks for that insightful plot.

Do you mind sharing the code which you used to generate that? specifically, I'm interested in how you generated the orange line - that is, what was the criteria used for determining blood culture + antibiotics?

**Comment by alistairewj** [comment]
Blood culture + antibiotics within 48-72 hours of each other. It's from the supplemental material of the Sepsis-3 guidelines. All my code around that is in a repo dedicated to a paper we wrote on identifying sepsis in MIMIC-III, you can find that here: https://github.com/alistairewj/sepsis3-mimic

**Comment by vrajaram** [comment]
@alistairewj  Thanks so much! Can you point to a PDF of the paper? Is it: http://journals.lww.com/ccmjournal/Citation/2016/12001/18___EXTERNAL_VALIDATION_OF_THE_SEPSIS_3.21.aspx ?

**Comment by alistairewj** [comment]
No worries - the paper is going through minor revisions, should turn up in
CCM in the next few months. I'll update that repo when it's out.
