### ISSUE TITLE
How can I find death cause?

### ISSUE THREAD

**Issue by RUOK90** [MIT-LCP/mimic-code#237]
Hi,

I would like to find death causes for dead patients, but I couldn't find the information.

Does the MIMIC-iii contain the information?

Is there any way that I can find the information?

Thanks in advance!

**Comment by tompollard** [comment]
Hi @RUOK90, you should be able to find cause of death for a large proportion of patients in the (unstructured) `noteevents` table. As a starting point, try:

```sql
set search_path to mimiciii;
select n.*
from noteevents n
inner join admissions a
on n.hadm_id = a.hadm_id
where a.hospital_expire_flag = 1
and lower(n.text) like '%cause of death%'
and category like 'Discharge summary%';
```

...which returns results containing text like: `cause of death was cardiac arrest secondary to sepsis`.

You may need to play around with the `lower(n.text) like '%cause of death%'` clause to pull out the  details you are looking for. e.g: to captures "causes" as well as "cause".

**Comment by RUOK90** [comment]
Thanks!
