### ISSUE TITLE
Clinical symptoms of neonates

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#238]
Hi
are clinical symptoms of neonates available in the MIMICIII dataset?
If yes where?
Clinical parameters like:-
1) cry weak or stopped
2) sucking reduced or stopped
3) limbs loose
4) vomiting
5) abdominal distension
6) chest indrawing etc

**Comment by tompollard** [comment]
Sorry @erjthakur, I'm not sure any of us know the answer to this question without looking at the data. You'll need to do some research to see what is there. Let us know what you find.

**Comment by alistairewj** [comment]
These are all concepts which we have not extracted. While we try to provide a large amount of concepts in this repository we don't have everything - at the very least the code in this repository will give you a good start - and if you do manage to extract any of these concepts we would welcome pull requests!
