### ISSUE TITLE
Is ICD 9 code assignment based solely on discharge summary (NOTEEVENTS)?

### ISSUE THREAD

**Issue by lsy3** [MIT-LCP/mimic-code#239]
Given "The ICD codes are generated for billing purposes at the end of the hospital stay.", is this a strong guarantee that the coder only used "discharge summaries" (from NOTEEVENTS) in assigning the said ICD9 code?

Although looking at your recommendation in another issue (quoted below), I think the answer is most likely no (my guess is the coder is looking at many sources + doctor clarification if needed, of course the coder may primarily use discharge summaries, but not limited to it). I am asking anyway because I may be wrong.
>In general, when searching for diagnoses or conditions, the most robust definition will cross-reference multiple possible definitions (e.g. structured data in CHARTEVENTS, ICD-9 codes, free-text searches in discharge summaries). Any statistical analysis done later on may benefit from sensitivity analyses around the definition of the cohort.

Thank you.

**Comment by alistairewj** [comment]
No problem about the clarification. They definitely use more than just the discharge summary - and unfortunately there are notes which they use which aren't in MIMIC-III, e.g. operating notes. A lot of this information is summarized in the discharge summary however, so it's a good place to look, in spite of this limitation.
