### ISSUE TITLE
NEONATE SEPSIS

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#240]
Hi 
there are many cases of neonatal sepsis in mimiciii where there is no organism found in the blood culture but still that neonate is diagnosed with sepsis in diagnoses_icd table.
Can you please tell us how the sepsis is defined in this case?

**Comment by MissClarinha** [comment]
C

Em 23/06/2017 17:38, "erjthakur" <notifications@github.com> escreveu:

**Comment by alistairewj** [comment]
Diagnoses can be made based on the notes, and do not require microbiology data to concur. That is, if there is a signed physician note which specifies a diagnosis of sepsis, then the diagnoses_icd table will contain a diagnosis of sepsis.
