### ISSUE TITLE
Gestational age 

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#241]
Hi 
is the gestational age of neonates not charted in mimiciii databsae?
we searched chartevents data for itemid '3446' but fond none?

although in note events text column gestational age has been mentioned in almost every neonate?
is there some other itemid for this?

**Comment by alistairewj** [comment]
Not sure myself - have you found anything related to age for neonates in chartevents?

**Comment by alistairewj** [comment]
Feel free to re-open if you are still looking around and have some new information.
