### ISSUE TITLE
ITEMID of the score index for the APACHE II score,SOFA score,SAPS II score 

### ISSUE THREAD

**Issue by daiyafei2013** [MIT-LCP/mimic-code#242]
Hi!
I want to calculate the score of APACHE II, one of the score index is patient surgery: there are five points for non-surgery or emergency surgery, two points for elective surgery. What's the ITEMID of patient surgery? For SAPS II, In DIAGNOSIS of ADMISSIONS, how can i find Hematoplastic tumor? For SOFA,if i can't find the ITEMID of dobutamine of some patients, representative did not enter this reagent  or it was not recorded?

**Comment by alistairewj** [comment]
Please review the scripts available in the repository, in particular:

SAPS II: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/severityscores/sapsii.sql
SOFA: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/severityscores/sofa.sql
APS III: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/severityscores/apsiii.sql

These will give hints on how these can be derived. Please note in some cases that we do not have the truth available, and a surrogate variable has been used.

**Comment by daiyafei2013** [comment]
thank you !

At 2017-06-28 16:36:48, "Alistair Johnson" <notifications@github.com> wrote:


Please review the scripts available in the repository, in particular:

SAPS II: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/severityscores/sapsii.sql
SOFA: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/severityscores/sofa.sql
APS III: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/severityscores/apsiii.sql

These will give hints on how these can be derived. Please note in some cases that we do not have the truth available, and a surrogate variable has been used.

**Comment by jiewang1991** [comment]
How to use this script？

**Comment by alistairewj** [comment]
The above are SQL scripts which assume that MIMIC-III is available in a PostgreSQL database. You can execute the scripts in a number of ways - through a GUI, the command line, etc. If you are unfamiliar with PostgreSQL I recommend looking online for educational materials.

Note that the scripts I link above do have prerequisites - an easy way to build all prerequisites is to use the command line tool `psql` with [make-concepts.sql](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/make-concepts.sql) script.

**Comment by jiewang1991** [comment]
Thank  you very much. I will try my  best to learn sql.
