### ISSUE TITLE
ICUSTAY_ID from transfers does not exist in chartevents table?

### ISSUE THREAD

**Issue by benbastaki** [MIT-LCP/mimic-code#243]
Hi,

I am working with mimicIII database, trying to link transfers table with chartevents to collect the readings of vital signs for icustays_id. I use icustays  in tarnsfers table to know when a patient is transfered from one unit to another.

However, I can see now the icustays_id that are in tarnsfers table and are from "db source = CAREVUE"  do not exist in chartevents. only ICUSTAYS_ID that are from "db source = metavision" exist in chartevents!??
Can you please confirm this is correct and provide me with a explanation why this is the case.

Many Thanks.
Regards,
Ben

**Comment by alistairewj** [comment]
Certainly `dbsource = 'carevue'` stays will exist in chartevents. Can you post the query which you believe indicates otherwise?

**Comment by benbastaki** [comment]
code is wrote in matlab and it is a bit long one, not sure if I can paste it here. but could you check\filter  chartevents (chartevents table) for Subject = 34 , hadm_id = 115799 and icustays_id = 263086. I don't see any record in chartevents! in Transfer table when I check same subject_id, hadm_id and icuystays_id , it's data source is carevue (this is only 1 example). I also found that some records in transfer table are duplicated( 1-copy is from 'carevue', and 1 copy from 'metavision')

Thanks for your help.

Ben.

**Comment by tompollard** [comment]
@benbastaki it seems that there are 1108 rows that match your search criteria:

```
SELECT COUNT(*) 
FROM chartevents 
WHERE subject_id = 34 
AND hadm_id = 115799 
AND icustay_id = 263086;

 count 
-------
  1108
```
