### ISSUE TITLE
postgres_load_data.sql: extra data after last expected column

### ISSUE THREAD

**Issue by herroannekim** [MIT-LCP/mimic-code#244]
I was following the installing mimic tutorial and got to the step 
` psql 'dbname=mimic user=mimic options=--search_path=mimiciii' -f postgres_load_data.sql -v mimic_data_dir='../../../mimic-data/'`

I received the following output:
`psql:postgres_load_data.sql:33: ERROR:  extra data after last expected column
CONTEXT:  COPY admissions, line 2: "90,87,190659,2191-02-25 20:30:00,2191-04-25 15:18:00,,"NEWBORN","PHYS REFERRAL/NORMAL DELI","SHORT T..."`

Should I go into the admissions csv and delete a column?

**Comment by alistairewj** [comment]
The ADMISSIONS table had a column dropped between MIMIC-III v1.3 and v1.4. Are you using the most up to date data?

**Comment by alistairewj** [comment]
I'll assume this was the issue.
