### ISSUE TITLE
Postgres Backwards Compatibility

### ISSUE THREAD

**Issue by jraffa** [MIT-LCP/mimic-code#246]
Not sure how we want to deal with it, but in https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/height-first-day.sql

`percentile_cont(0.5) WITHIN GROUP (ORDER BY height)`

(gets the median within in each patient)

won't work with oldish version of postgres.  Was using server version 9.3x

**Comment by tompollard** [comment]
Thanks @jraffa, good point. This duplicates https://github.com/MIT-LCP/mimic-code/issues/138, raised by @tnaumann a while back. I think the solution is just to add a requirement for Postgres >= 9.4 to the readme.
