### ISSUE TITLE
Severity Code DROP MATERIALIZED VIEWS fail

### ISSUE THREAD

**Issue by jraffa** [MIT-LCP/mimic-code#247]
Been bug testing something I've been working on in R.  If you try to rerun the code, you run into an issue, a possible issue and a suggested fix:

`DETAIL:  materialized view elixhauser_quan_score depends on materialized view elixhauser_quan
HINT:  Use DROP ... CASCADE to drop the dependent objects too.`

This might be dangerous, so I would suggest discussing it before implementing.

https://github.com/MIT-LCP/mimic-code/pull/248

**Comment by alistairewj** [comment]
Ah good catch. DROP CASCADE is fine to do - it's actually the desired behavior to have these drops cascade to dependent views because then you can't update a table without also having to regenerate all the dependent views.
