### ISSUE TITLE
negative culture reports

### ISSUE THREAD

**Issue by drpajama** [MIT-LCP/mimic-code#249]
Hello. 

It looks like microbiologyevents table only contains positive culture reports- is there any way to check whether there was negative culture reports? Thank you!

**Comment by alistairewj** [comment]
Rows with `NULL` for the organism, antibiotic, etc, columns are negative culture reports. How many rows does your microbiology table have?

**Comment by alistairewj** [comment]
Reopen if you have any updates!

**Comment by drpajama** [comment]
Thank you for your attention! There are rows with empty ‘ab_name’ column (I guess it is positive culture without sensitity) but I cannot find any row with empty org_name (e.g. Citrobacter, S. Aureus...)
