### ISSUE TITLE
Trouble adding indexes

### ISSUE THREAD

**Issue by jefftienchow** [MIT-LCP/mimic-code#251]
During the MIMIC database setup, I tried adding indexes using:
psql 'dbname=mimic user=mimic options=--search_path=mimiciii' -f postgres_add_indexes.sql
and I get this error: 
psql:postgres_add_indexes.sql:19: NOTICE:  index "admissions_idx01" does not exist, skipping
DROP INDEX
psql:postgres_add_indexes.sql:21: ERROR:  relation "admissions" does not exist

How do I fix  this so I can add indexes? Thanks.

**Comment by alistairewj** [comment]
Hm two issues about this so maybe there is a subtle bug in the build scripts.

I presume you're using the terminal based approach. Can you login to the database and do run the following:

```
\dn
set search_path to mimiciii;
\dt
```

And paste the output here?

**Comment by jefftienchow** [comment]
The output is: 
No relations found.

**Comment by alistairewj** [comment]
Which schemas were listed from `\dn`? It sounds like you have built MIMIC on a schema other than `mimiciii`. Check the other schemas for data.

**Comment by jefftienchow** [comment]
This was fixed by creating a database with superuser privileges and granting superuser privileges to postgres. @tompollard
