### ISSUE TITLE
How to obtain the history of a given patient

### ISSUE THREAD

**Issue by zhidehu** [MIT-LCP/mimic-code#253]
Hi

Thank you for the fantastic data!

In some of my works, I need to obtain the history of a given patient. For example: 1) Whether the given patient has received blood transfusion 4 months prior to admission? 2) Whether the patients has infectious events 2 weeks prior to admission? 
Besides, how to obtain the information regarding blood transfusion during hospitalization. I have searched INPUTEVENTS_CV and D_ITEMS, and found that there seems no data regarding this issue.

**Comment by alistairewj** [comment]
Patient history is difficult, and you'll likely need to parse through free-text notes to get at that information.

For blood transfusions, don't look for the phrase "blood transfusion", but rather the compounds, e.g. red blood cells (RBC), packed red blood cells (PRBC), etc.
