### ISSUE TITLE
How to find the medicines patients took?

### ISSUE THREAD

**Issue by freestylezhy** [MIT-LCP/mimic-code#256]
Hi,

I am doing a study about the side-effects and interaction of medicines, so I want to find the medicines patients took. So far, I found that D_ITEM table contains all the descriptions of items that should include the medicine information. 

In the D_ITEM table, the LABEL under the category of Medications are:

_['ADA-A (500ml)' 'Keppra' 'Meperidine (Demerol)' 'Hydromorphone (Dilaudid)'
 'Hydralazine' 'Alteplase (TPA)' 'Nicardipine' 'Procainamide'
 'Morphine Sulfate' 'Dexmedetomidine (Precedex)' 'Fentanyl' 'Fondaparinux'
 'Labetalol' 'Thiamine' 'Calcium Gluconate' 'Metoprolol' 'Adenosine'
 'Lidocaine' 'Amiodarone 600/500' 'Potassium Chloride'
 'Insulin - Humalog 75/25' 'K Phos' 'Atropine' 'Omeprazole (Prilosec)'
 'Midazolam (Versed)' 'Enoxaparin (Lovenox)' 'KCL (Bolus)' 'Vasopressin'
 'Eptifibatide (Integrilin)' 'Hydrochloric Acid - HCL' 'Epinephrine'
 'ACD-A Citrate (1000ml)' 'Nesiritide' 'Mannitol' 'Citrate'
 'Tirofiban (Aggrastat)' 'Insulin - Glargine' 'Naloxone (Narcan)'
 'Abciximab (Reopro)' 'Carafate (Sucralfate)' 'Nitroprusside'
 'Pantoprazole (Protonix)' 'Cisatracurium' 'Octreotide'
 'Furosemide (Lasix)' 'KCL Bolus)' 'Magnesium Sulfate (Bolus)'
 'Lansoprazole (Prevacid)' 'Diazepam (Valium)' 'Isuprel' 'KCl (CRRT)'
 'Calcium Gluconate (Bolus)' 'Fentanyl (Concentrate)'
 'Bivalirudin (Angiomax)' 'Heparin Sodium (Prophylaxis)'
 'Magnesium Sulfate (OB-GYN)' 'Famotidine (Pepcid)'
 'Ranitidine (Prophylaxis)' 'Heparin Sodium' 'Pentobarbital'
 'Fentanyl (Push)' 'Insulin - NPH' 'Calcium Gluconate (CRRT)' 'Vecuronium'
 'Norepinephrine' 'Propofol' 'ACD-A Citrate (500ml)' 'Milrinone'
 'Drotrecogin (Xigris)' 'Insulin - Regular' 'Vitamin K (Phytonadione)'
 'Cyclosporine' 'Aminophylline' 'Insulin - 70/30'
 'Furosemide (Lasix) 500/100' 'Diltiazem' 'Insulin - Humalog' 'Dilantin'
 'Fosphenytoin' 'Sodium Bicarbonate 8.4%' 'Lorazepam (Ativan)'
 'Coumadin (Warfarin)' 'Ketamine' 'Esmolol' 'Dobutamine' 'Dopamine'
 'Nitroglycerin' 'Lepirudin' 'Haloperidol (Haldol)' 'Amiodarone' 'Na Phos'
 'Phenylephrine' 'Methadone Hydrochloride' 'Acetaminophen-IV' 'Argatroban'
 'Magnesium Sulfate' 'Folic Acid' 'Verapamil']_

I am wondering if these are all the medicines/drugs patients took during the stay in the hospital? Those seem only a few to me.

**Comment by freestylezhy** [comment]
There are some medications information in the **noteevents** table, in the form of text. For example,
running:
`query = '''
SELECT text
FROM noteevents
limit 5
'''
med_notes = pd.read_sql_query(query,con)
print(med_notes.loc[1, 'text'])`

These lines are printed:
MEDICATIONS ON ADMISSION:
1. Hydrochlorothiazide 25 q.d.
2. Prednisone 60 mg, 50 mg, 40 mg, 20 mg.
3. Levofloxacin 500 mg q.d.
4. Imdur 60 mg q.d.
5. Synthroid 75 mcg q.d.
6. Pulmicort nebulizer b.i.d.
7. Albuterol nebulizer q.4. prn.
8. Lexapro 10 mg q.d.
9. Protonix 40 mg q.d.
10. Aspirin 81 mg q.d.

and 

DISCHARGE MEDICATIONS:
1. Levothyroxine 75 mcg p.o. q.d.
2. Citalopram 10 mg p.o. q.d.
3. Aspirin 81 mg p.o. q.d.
4. Fluticasone 110 mcg two puffs inhaled b.i.d.
5. Salmeterol Diskus one inhalation b.i.d.
6. Acetaminophen 325-650 mg p.o. q.4-6h. prn.
7. Ipratropium bromide MDI two puffs inhaled q.2h. prn.
8. Albuterol 1-2 puffs inhaled q.2h. prn.
9. Zolpidem tartrate 5 mg p.o. q.h.s. prn.
10. Isosorbide dinitrate 10 mg p.o. t.i.d.
11. Diltiazem 60 mg p.o. q.i.d.
12. Pantoprazole 40 mg p.o. q.24h.
13. Trazodone 25 mg p.o. q.h.s. prn.
14. SubQ Heparin 5000 units subcutaneous b.i.d. until such
time that the patient is able to get out of bed twice a day.
15. Cepacol lozenges q.2h. prn.
16. Levofloxacin 500 mg p.o. q.d. for a seven day course to
be completed on [**2118-6-21**].
17. Kaopectate/Benadryl/lidocaine 5 mL p.o. b.i.d. prn, not
to be given around mealtimes for concern of dysphagia induced
by lidocaine.
18. Lorazepam 0.5-2 mg IV q.6h. prn.

I am wondering if the medications are present in the database as structured data? Thanks a lot!

**Comment by alistairewj** [comment]
The issue is that not all medications have `category = 'Medication'`. There are other categories such as `'Antibiotics'`, `'Fluids/Intake'`, etc. Furthermore, many medications have category as null. I think a better approach is to look for items which have `linksto = 'inputevents_cv`' or `linksto = 'inputevents_mv'`. These are items which were intravenously infused at some point. That's most medications that people are interested in. You can read about why there is a `_cv` and `_mv` table here (https://mimic.physionet.org/mimicdata/metavision/) and here (https://mimic.physionet.org/mimicdata/carevue/).

The other alternative is to use the prescriptions table: for that table you just search the drug column for the drugs you are interested in. Note these would be prescriptions and thus not necessarily administered.

Finally, admission and discharge medications are best captured by the free-text notes, as you have found.

**Comment by arielhasidim** [comment]
About `prescriptions` table: does it includes prescriptions from all around the hospital admission? 
(e.g. wards other then ICU)
