### ISSUE TITLE
Contribute Drug Matching Code

### ISSUE THREAD

**Issue by SamuelGabriel** [MIT-LCP/mimic-code#257]
I wrote, as part of my Bachelors thesis, Python scripts that can quite reliably match agent names from MIMIC to entries in the drugbank.ca database, if one exists. This can help to find indication, ATC-Code etc. for drugs in MIMIC. Am I right to make a pull request for such an data analysis code in this repo?

**Comment by alistairewj** [comment]
Absolutely, we would very much welcome this type of code. What tables do the script(s) primarily operate on? And what is the output? Just thinking about where best to fit it in with the other concepts.

**Comment by SamuelGabriel** [comment]
It only uses the PRESCRIPTIONS table. The output is an entry in the DrugBank given in form of the drug's DrugBank ID. Or None if there was no good Match.

**Comment by alistairewj** [comment]
Okay, why don't you organize it in a new folder: `concepts/ontology`. Make a pull request and we can go from there!
