### ISSUE TITLE
Error message when attempting to run ventilation-durations.sql

### ISSUE THREAD

**Issue by lylemp** [MIT-LCP/mimic-code#258]
ventilation-durations.sql is required to run ventilation-first-day.sql, which is required to run oasis.sql. However, I keep getting this error message (both when calling the script in psql and in R)

ERROR:  cannot drop materialized view ventsettings because other objects depend on it
DETAIL:  materialized view ventdurations depends on materialized view ventsettings
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

It seems this is the problem statement: "DROP MATERIALIZED VIEW ventsettings;" the last line of the script.

Any help is greatly appreciated.

**Comment by alistairewj** [comment]
Try a git pull. The latest version of the code has `DROP MATERIALIZED VIEW ventsettings CASCADE;`, which fixes this issue.

**Comment by lylemp** [comment]
Thanks, the ventilation-durations.sql script now runs correctly. However, subsequently calling ventilation-first-day.sql results in this error:

NOTICE:  materialized view "ventfirstday" does not exist, skipping
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : **ERROR:  relation "ventdurations" does not exist**

"ventdurations" apparently does not exist, even though it was created by the previous script ventilation-durations.sql.

**Comment by alistairewj** [comment]
It's probably on a different schema - are you using both `public` and `mimiciii`? I always start my queries with `set search_path to public,mimiciii;`, that way tables/views are created on `public` but I can still read raw data from `mimiciii`.

**Comment by lylemp** [comment]
I started using both public and mimiciii, but the issue remains. It seems the final statement that reads "DROP MATERIALIZED VIEW VENTSETTINGS CASCADE" not only gets rid of ventsettings, but ventdurations as well. Therefore, ventdurations will not exist when I call ventilation-first-day.sql. 

As a test, here's the output when called in R when using the function dbExecute():
**NOTICE:  drop cascades to materialized view ventdurations
[1] 0**

Where 0 tells me the number of rows affected.

**Comment by alistairewj** [comment]
Ah! It still drops it at the end of the script! Good catch, that's very much an error. We only recently changed these to materialized views so this must have been accidentally leftover. Fixed in commit https://github.com/MIT-LCP/mimic-code/commit/9e05ab27b947b664f7ddbc5dcfe0c3e573c69fcc - try again!

**Comment by lylemp** [comment]
Works! Was finally able to successfully call ventilation-durations.sql, ventilation-first-day.sql, and eventually oasis.sql. Thanks!
