### ISSUE TITLE
about ethics

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#260]
Hello, we submitted a study based MIMIC III. The editor replied like this “Please clearly confirm whether or not your study needed ethical approval, and which bodies gave that approval or waived the need where appropriate.  Please include the specific name of the ethics committee.  Any experimental research on humans must be in compliance with the Helsinki Declaration”. So I am wondering how can I get the information on the ethics committee ?  Where can I get the ethical approval ? Or which bodies can waive the need?

**Comment by alistairewj** [comment]
Any study using MIMIC-III did require ethical approval, and the Institutional Review Boards (IRBs) at both MIT and the Beth Israel Deaconess Medical Center (BIDMC) approved the use of the data for research.

**Comment by guangyongjin** [comment]
Hello, we submitted a study based MIMIC IV.  The collection of patient information and creation of the research resource was reviewed by the Institutional Review Board at the Beth Israel Deaconess Medical Center, who granted a waiver of informed consent and approved the data sharing initiative. The editor replied like this “Please write the institutional ethical approval decision number”. So I am wondering how can I get this information in detail.

**Comment by tompollard** [comment]
@guangyongjin @mylanhong please the discussion at: https://github.com/MIT-LCP/mimic-website/issues/198

> The creation of the de-identified database was approved by the Massachusetts Institute of Technology (Protocol No. 0403000206) and the institutional review boards of the Beth Israel Deaconess Medical Center (Protocol No. 2001-P-001699/14).
