### ISSUE TITLE
Daily or Hourly Fluid Balance?

### ISSUE THREAD

**Issue by mornin** [MIT-LCP/mimic-code#261]
Hi All,

We used to have a FLUID_BALANCE table in MIMIC II. Noticed that this table was removed for MIMIC III. Has anyone or other teams tried to calculate patients' daily or hourly fluid balance during their ICU stay? 

Or is there a agreed list of item ids for all the input and output fluids? I have seen the codes on urine output. Any other works beyong UO?

Many thanks :)

**Comment by liuxiaoliXRZS** [comment]
I found the itemids of fluid intake. This may be helpful to you. @mornin 
[https://github.com/liuxiaoliXRZS/sepsis](url)

**Comment by mornin** [comment]
Thanks a lot for sharing @liuxiaoliXRZS . but the provided link seems to be broken?

**Comment by ihalari** [comment]
Hello, I am doing some research into fluid balance in MIMIC and was wondering if there was any further insight that was identified based on these questions. 

Specifically, I am trying to understand the following:
1)	Are there any specific variables to track fluid balance of patients (daily or hourly) in ICU in MIMIC III?
2)	If there is no specific variable, what is a good approach find variables to estimate fluid intake (oral, IV and etc.) so that we can estimate fluid balance based on fluid intake and urine output?

Any help and insight is much appreciated, thanks much in advance!

**Comment by liuxiaoliXRZS** [comment]
There is no good way to accurately calculate the amount of fluid intake per hour. The inputevents_cv might not suitable for computing intake per hour and inputevents_mv could approximately calculate them. You can see the[ Inputs and outputs ](https://mimic.physionet.org/mimicdata/io/)to find reason. I hope that would be useful for you. @ihalari

**Comment by mylanhong** [comment]
@liuxiaoliXRZS Hello, after running "itemid_fluid_intake_mv.sql", l found there was no itemid. Is that true ?

**Comment by liuxiaoliXRZS** [comment]
You can refer to [urine-output-first-day.sql](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/urine-output-first-day.sql) to get the first day of liquid intake. @mylanhong

**Comment by alfredoncs** [comment]
@liuxiaoliXRZS
I think refering to urine-output-first-day.sql
<https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/urine-output-first-day.sql>
 , it is not possible to get the first day of liquid intake.
I think  it is possible only to get  'input of GU irrigant'.
How do we do to get   the liquid intake during the   first  day ?
Best,

*Alfredo N C Santana, MD, PhD, FCCP*
*Professor Permanente - Mestrado ESCS*
*Professor Adjunto - Medicina ESCS*
*Pneumologista - HRAN SES DF*

2018-05-07 7:26 GMT-03:00 liuxiaoliXRZS <notifications@github.com>:

**Comment by liuxiaoliXRZS** [comment]
For me, I only use the cohort of 'metavision' and the table of inputevents_mv has the column of rate. So when I find all of itemids I need, I can use rate and durations (endtime - starttime) to calculate the daily amount of liquid intake. [Inputs and [outputs]](https://mimic.mit.edu/mimicdata/io/) may be helpful for you.  @alfredoncs

**Comment by alfredoncs** [comment]
@liuxiaoliXRZS and other members of MIMIC GITHUB,

Thank you for your attention.

Could you send the exact code that you use to calculate the input of all
types of fluids in the first day of ICU stay ?

Best,

*Alfredo N C Santana, MD, PhD, FCCP*
*Professor Permanente - Mestrado ESCS*
*Professor Adjunto - Medicina ESCS*
*Pneumologista - HRAN SES DF*

2018-05-13 1:56 GMT-03:00 liuxiaoliXRZS <notifications@github.com>:
