### ISSUE TITLE
Miss data of some patient from ventilation duration

### ISSUE THREAD

**Issue by batfire73** [MIT-LCP/mimic-code#262]
Hi,
Thanks for the fantastic data!
We have a small problem when running script of ventilation duration .Paitient with hadm_id182834 receive the intubation and ventilation ,but have 0 ventilation days according to the script of ventilation duration .Could you help us solve this issue?

**Comment by alistairewj** [comment]
`hadm_id` 182834 only has one `icustay_id` - 260476. According to

```sql
SELECT icustay_id, ventnum, duration_hours
FROM ventdurations
WHERE icustay_id = 260476;
```

They were ventilated:

 icustay_id | ventnum   |  duration_hours  
------------ | --------- | ------------------
260476 |       1 |               236
260476 |       2 | 7.41666666666667 

You may want to double check your query!
