### ISSUE TITLE
Time data 

### ISSUE THREAD

**Issue by batfire73** [MIT-LCP/mimic-code#263]
Hi,thanks for this resourse . 
Accorting the introduction, all dates in the database have been shifted to protect patient confidentiality
But "Trends in severity of illness on ICU admission and mortality among the elderly" published in PLOS ONE with pubid 24699251 analysis the time trend of admission with your system .How could we got this kind information?

**Comment by alistairewj** [comment]
For select projects, we allow researchers to apply for access for the true year of admission for patients. We treat this data with extreme care and are very restrictive about its use. Researchers requesting this data must submit a research proposal which details the project and includes a very strong argument justifying the need of the actual year. There is an additional data use agreement and after a certain time period we must receive written confirmation that the data has been destroyed. You may contact mimic-support@physionet.org for more details.
