### ISSUE TITLE
Confidentiality/legal issue

### ISSUE THREAD

**Issue by vivetriv** [MIT-LCP/mimic-code#265]
Hi,
Hope everyone is doing well!

I was just wondering if I can use some of the MIMIC data to train a model on the IBM Watson Knowledge Studio. I am just concerned as I think it uploads the data to the cloud.

Thanks!

Yours sincerely
Vivek.

**Comment by rgmark** [comment]
How do you guarantee that all MIMIC data is under your control and that 
no-one but you has access to it?
R Mark

Roger G. Mark, M.D., Ph.D.
Professor of Health Sciences and Technology
   and of Electrical Engineering
Room E25-505
MIT
Cambridge, MA 02139
Tel 617-253-7818
Fax 617-258-7859

**Comment by vivetriv** [comment]
I am the admin and the sole participant of my project. I would have to invite users to view/modify/use any parts of the MIMIC data or my model (which I won't be doing). 

My main reason for asking this question was that I had heard that healthcare providers here in Australia can't use certain cloud-based products as they can't guarantee the data stays tightly controlled and on Australian soil. Just thought to ask if MIMIC had similar security requirements that would be breached by my use of the Knowledge Studio.

Thanks!
Vivek

**Comment by vivetriv** [comment]
I am really sorry to be impatient, but I would like to get a concrete answer regarding this fairly quickly as I am working against a deadline. If there is anything more I need to do, or someone I need to contact at, say, IBM about this, please let me know.

Once again, thanks, and sorry for your troubles! I wish I knew more about this stuff.

Vivek.

**Comment by alistairewj** [comment]
We have discussed this and unfortunately we cannot give a generic answer. The use of cloud services requires signing of an agreement, and there are cases where the terms of use for the cloud service violate the data use agreement you have signed to gain access to MIMIC. Use of cloud services will have to be judged on a case by case basis. Please contact us for more detail on the matter at mimic-support@physionet.org
