### ISSUE TITLE
About institutional review board statement

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#267]
Dear Sir,
We are submitting a manuscript based on MIMIC III to World Journal of Gastroentrology. We are required to also submit a institutional review board statement and informed consent statement. How can we get the doucument about  institutional review board statement. Thanks !

**Comment by rgmark** [comment]
I have attached the most recent IRB approval. Notice that informed 
consent has been waived.

Roger Mark

Roger G. Mark, M.D., Ph.D.
Professor of Health Sciences and Technology
   and of Electrical Engineering
Room E25-505
MIT
Cambridge, MA 02139
Tel 617-253-7818
Fax 617-258-7859

**Comment by mylanhong** [comment]
@rgmark I am sorry, Sir. I cannot found the IRB approval you attached. Could you please provide a link ?

**Comment by alistairewj** [comment]
Please contact Roger directly via e-mail and he will send you the IRB approval.
