### ISSUE TITLE
Initial SAPS score. 

### ISSUE THREAD

**Issue by Sandv** [MIT-LCP/mimic-code#27]
Thank you very much for this database!

I use mimic III (haven't used Mimic II before). One thing that makes understanding the data difficult for me is that I don't see an accessible  indicator of disease severity.  It looks like mimic ii had the Saps score precalculated.  

Is this possible with mimic III too (any other score,  sofa, Apache would also work). 

Thank you very much for your help. 
Veit

**Comment by alistairewj** [comment]
In time we will make code for calculating severity of illness scores available. Due to their wide utility among MIMIC users, we need to take time to ensure the scores are accurately derived.
