### ISSUE TITLE
APACHE score or similar

### ISSUE THREAD

**Issue by vjm261** [MIT-LCP/mimic-code#28]
I'm looking to estimate disease severity using some kind of mortality prediction or comorbidity score. The trouble that I've run into is that there are very few recorded APACHE II, IV or SOFA scores or even the defined component items that constitute the scores. 

Before I try to write something to search through chartevents, labevents and discharge summaries for the APACHE components, I was wondering if there is any other kind of comorbidity score that is widely prevalent in the database. I would assume that the contributing hospital would use some kind of score but I can't find it.

**Comment by alistairewj** [comment]
There's no real incentive to deriving a comorbidity score for hospital staff, so they in general don't create one. However, the Elixhauser comorbidity score has been calculated and code is available in this repository. This score uses DRGs and ICD-9 diagnostic codes (which are created upon patient discharge) to define comorbidities. Would this work for your project?

**Comment by vjm261** [comment]
Thanks Alistair. We were hoping to have a score on admission but that isn't as easy as I was hoping. I'll attempt to adapt your Elixhauser code (for implementation in R) and write some for APACHE II and I'll share anything successful.

**Comment by alistairewj** [comment]
Great, good luck! I'll leave this issue open so you can update on your progress.

**Comment by Sandv** [comment]
FYI: There is an R package "icd9" which calculates the Elixhauser (and similar) scores from ICD codes. Simple to use. The issue with apache or sofa scores seems more difficult to me - but really important...

**Comment by lceli** [comment]
Our group at LCP has started using OASIS to adjust for severity of illness. It performs better than the other scores including APACHE, SAPS, SOFA, etc.
http://www.ncbi.nlm.nih.gov/pubmed/23660729

**Comment by Sandv** [comment]
Thank you very much Iceli! That looks great - I think the necessary variables are easier to get compared to other scores...

**Comment by vjm261** [comment]
Great, thank you for the tips Sandv and lceli. This saves me some time and gives some extra legitimacy to exclude the difficult-to-extract elements of APACHE II such as the Glasgow Coma Score that was giving me headaches.

**Comment by alistairewj** [comment]
Worth mentioning that we plan to release code for calculating severity
scores as soon as we have time to! On the list are SAPS, SOFA, APS III, and
SAPS II. All in good time...

**Comment by pszolovits** [comment]
In Caleb Hug's 2009 doctoral thesis (http://groups.csail.mit.edu/medg/ftp/hug/HugPhD2009.pdf), he computes an approximation to SAPS-II from MIMIC data. See page 61. He needed to approximate the specific "chronic diseases" and "type of admission" components of SAPS-II by using ICD-9 codes for diseases and a heuristic for admission type (medical/scheduled surgical/unscheduled surgical).

**Comment by alistairewj** [comment]
With the new data in MIMIC we can likely refine that approach. Chronic
diseases would be defined in the same way since that is likely to be an
accurate estimate. For admission urgency, there is actually an admission
type column in the admissions table which states if the admission is
elective or not. The only challenge is defining surgery - right now I'm
experimenting with using CPT codes which define major surgery but I'm not
sure if they are comprehensive.

**Comment by tompollard** [comment]
Note the related question posted on Stack Exchange: 
http://opendata.stackexchange.com/questions/6748/mimic-iii-severity-score

**Comment by mhkane** [comment]
Hey everyone, 
I need to have the SOFA scores for my project on sedation and I wanted to check whether you have been able to write the code to compute it.

**Comment by alistairewj** [comment]
OASIS, SAPS, and SOFA are now available in the severityscores subfolder. Please give it a go and raise any issues you may have. All the scripts should work on PostgreSQL. SAPS II in the works, along with some others, but for now I'll close this issue!
