### ISSUE TITLE
Judge hypotension of septic shock according to the itemids of sbp and map 

### ISSUE THREAD

**Issue by liuxiaoliXRZS** [MIT-LCP/mimic-code#280]
I want to find the **time of happening septic shock** which needs to judge the period of hypotension persisting with the definition of Sepsis 1.0. Should I use **both conditions** of **sbp < 90mmHg** or **map < 65mmHg**? While I found  that the results obtained by the two conditions are quite different.
thanks :)

**Comment by alistairewj** [comment]
I believe the condition is SBP < 90 *or* MAP < 65, though the timing (e.g. for how long) is always a bit vague with these studies. You may also be interested in this recent comparison between the sepsis 1 and sepsis 3 definitions: https://www.ncbi.nlm.nih.gov/pubmed/28542029
