### ISSUE TITLE
The time at which a special diagnosis is made

### ISSUE THREAD

**Issue by zhidehu** [MIT-LCP/mimic-code#287]
Hi,

Thank you for the fantastic data!

One of my research interest is to explore factors associated with acute kidney injury (acute renal/kidney failure) in patients admitted to ICU.

I noted that some of patients had a diagnosis of acute kidney failure (icd9_code: 5845, 5846, 5847, 5848 and 5849); however, the time at which this diagnosis was made is unclear. 

I guess that some of the patients may have acute renal failure before ICU admission and some of them may progress to acute renal failure during their admission. My question is: how can I get the exact time at which acute renal failure is made?

Besides, there are some diagnostic criteria for acute renal failure (ADQI, AKIN and KDIGO), which is used in MIMIC III?

Best wishes.

**Comment by tompollard** [comment]
Thanks for the positive feedback @zhidehu :) The ICD-9 codes that you see in MIMIC are coded at the end of the patient stay, based on information available at hospital discharge. The codes can not be used to identify a time of diagnosis, as you note.

> My question is: how can I get the exact time at which acute renal failure is made?

I don't think it is possible to identify the exact time of diagnosis, if this is what you need, though for some patients you might be able to get an indication of the approximate time with a search of the patient notes.

> Besides, there are some diagnostic criteria for acute renal failure (ADQI, AKIN and KDIGO), which is used in MIMIC III?

It is possible to use criteria like this to create a patient cohort, but they would first need to be derived (unless someone is willing to share pre-written code). I recommend searching the MIMIC Code Repository for related issues (for example, some of the severity scores include renal components).

**Comment by alistairewj** [comment]
Recently added KDIGO criteria here: https://github.com/MIT-LCP/mimic-code/tree/master/concepts/organfailure

Feedback welcome!
