### ISSUE TITLE
Multiple hadm_ids for some icustay_ids in chartevents table

### ISSUE THREAD

**Issue by JohannesNE** [MIT-LCP/mimic-code#288]
Some icustay_ids are associated with 2 different hadm_ids (in one case 3) in the chartevents table. 
As I understand this is not intended. What is the cause of this?

Example:
``` sql
with temp as(select distinct icustay_id, hadm_id
    from mimiciii.chartevents)

select icustay_id, count(hadm_id)
from temp
group by icustay_id
order by count(hadm_id) desc
limit 100
```

icustay_id | count
-- | --
None | 1661
242061 | 3
242606 | 2
266567 | 2
276635 | 2

**Comment by tompollard** [comment]
A related issue (now fixed) is: https://github.com/MIT-LCP/mimic-code/issues/120. The `icustay_id` is a generated identifier that typically requires a patient to leave the ICU for >24h for a new value to be assigned (a rule inherited from MIMIC-II for ease of analysis). 

Most likely these cases are patients who were discharged from both the ICU and hospital and readmitted to the ICU within 24h. We will look into the issue and may be able to include a fix in the next release of the data.

**Comment by alistairewj** [comment]
Yep we had a slight regression - it's as @tompollard says: readmitted to the hospital within 24 hours. In fact most of these are not true readmissions but administrative "readmissions" as they would like to reclassify the patient as an organ donor. It will be fixed in the next version.

**Comment by JohannesNE** [comment]
Thanks for the replies. I can probably work around it using subject_id.
