### ISSUE TITLE
Itemid for End Tidal CO2?

### ISSUE THREAD

**Issue by jgenk** [MIT-LCP/mimic-code#289]
Hello,

Have been digging around D_ITEMS and D_LABITEMS for an itemid that might correspond to end tidal CO2  (EtCO2, https://en.wikipedia.org/wiki/Capnography).

The best I can find are:
1817 - "EtCO2"
228640 - "ETCO2"

However, between the two of these there are only 6 total observations
`SELECT * FROM mimiciii.chartevents WHERE itemid IN (1817,228640);`

 => 6 rows

I have done what I think is a fairly exhaustive search of synonyms - etco2, end tidal carbon dioxide, various version of the word capnography, etc.

Any ideas if I am missing a good itemid in MIMIC III that contains the concept of EtCO2?

Thanks for any help,
Julian

**Comment by alistairewj** [comment]
I too have looked for this and also came up short. I think it's just not charted in the clinical information system. I'll ask someone from the hospital.

**Comment by jgenk** [comment]
Okay great, thank you! That makes sense based on my experience at my medical center (Vanderbilt) -  EtCO2 monitors are used more frequently in the OR than in the ICUs

Just kind of wanted a sanity check from someone with more experience in the database - this is not critical to my project so not a big deal if this is the final answer.

**Comment by alistairewj** [comment]
I've confirmed with hospital staff - EtCO2 monitoring began after the end of MIMIC so you won't find it in the database as of v1.4, but when we add more data in later versions it will certainly turn up!
