### ISSUE TITLE
Is there a way to find pre ICU admission disease?

### ISSUE THREAD

**Issue by yun-li** [MIT-LCP/mimic-code#290]
Hi,
I would like to know the existing conditions that a patient already have before ICU admission, is there a way to do that?

Thanks,
Yun

**Comment by alistairewj** [comment]
The approaches that we have are based upon using billed ICD-9 codes on hospital discharge. Non-primary diagnoses are extracted, and depending on the diagnosis related group (DRG), some of these are further filtered. Finally, the diagnoses are grouped into general categories such as diabetes, congestive heart failure, etc. You can find the code here: https://github.com/MIT-LCP/mimic-code/tree/master/concepts/comorbidity (note we have more than one algorithm for doing this process).

Other than that, you could use free-text searches of the discharge summary for the "Past Medical History" section. However we don't have any code presently to do this - would be a great project! :)

**Comment by yun-li** [comment]
Thanks for your reply. I have a question about your answer.

By saying "Non-primary diagnoses", do you mean the diagnoses that are not the reason for ICU admission? If it is, is there a way to obtain the reason for ICU admission?

Thanks,
Yun

**Comment by alistairewj** [comment]
No, unfortunately "non-primary diagnosis" refers to the sequence that the diagnoses are coded on discharge. You can see more info at #199. For ICU admission diagnoses you would have to parse the notes.
