### ISSUE TITLE
Stroke Outcome Score?

### ISSUE THREAD

**Issue by mvanva** [MIT-LCP/mimic-code#291]
Has anyone been able to find a systematic coding for any stroke outcome score, such as modified Rankin Score, Mathew Stroke Scale, or Functional Independence Measure? At least, has anyone come across a mention of these scores in a chart note?
Thank you!

**Comment by alistairewj** [comment]
I don't believe we have any concepts related to that at the moment - though it would be great to find out if they exist. If you look in this notebook - https://github.com/MIT-LCP/mimic-code/blob/master/notebooks/crrt-notebook.ipynb - it overviews the process of searching the `d_` tables for concepts. Perhaps you could take a look for the stroke outcome scores?
