### ISSUE TITLE
Medication administration record (MAR) data availability

### ISSUE THREAD

**Issue by skaneRFUMS** [MIT-LCP/mimic-code#292]
Are there any plans to eventually include MAR-level data into MIMIC III?  Currently all IV drips (such as vasopressors) and some intermittent IV medications are documented in the inputevents table, but inputevents does not contain most IV push and contains no oral medications being administered.  The prescriptions table contains all medication orders, but this table does not describe whether the patient actually received a medication and what time it was actually received.

For research purposes, knowledge of the MAR (especially the time a medication was given) would be extremely helpful.

**Comment by alistairewj** [comment]
The electronic medication administration record (eMAR) went online only a few years ago and so is not in MIMIC-III v1.4. We plan to add on something similar for a subset of patients in a future update. Stay tuned! :)
