### ISSUE TITLE
Error for Timestamp Syntax while building MIMIC data

### ISSUE THREAD

**Issue by gsk1692** [MIT-LCP/mimic-code#293]
psql:postgres_load_data.sql:139: ERROR:  invalid input syntax for type timestamp: "2141"
CONTEXT:  COPY noteevents, line 66923623, column chartdate: "2141"
Makefile:106: recipe for target 'mimic-build' failed
make: *** [mimic-build] Error 3

Any ideas on how to overcome this?

**Comment by alistairewj** [comment]
I have checked that line in my copy of noteevents and it is fine. This may indicate that your download was corrupted - can you check the md5 sum of your local copy of `NOTEEVENTS.csv` matches that posted on https://physionet.org/works/MIMICIIIClinicalDatabase/files/ ?

**Comment by gsk1692** [comment]
Hello, thanks for the response.
I checked the md5 check sum and it matches !
Any other tips?

**Comment by gsk1692** [comment]
Hello, I was checking in the wrong system altogether, in my current location, the checksum for NOTEVENTS.csv doesn't match! I will download that and try again.

Thank you for your time and sorry for the trouble. I am closing the issue.
