### ISSUE TITLE
Repository Contribution Workflow

### ISSUE THREAD

**Issue by herroannekim** [MIT-LCP/mimic-code#300]
If a student works on analysis tools on the mimic database and wishes to contribute this code to the repository, what's the workflow?  Should a new branch and then pull request be made?  Thanks

**Comment by zhidehu** [comment]
I advise you to cooperate with researchers. Actually, majority of researchers are not good at SQL and they need your help.

**Comment by alistairewj** [comment]
Thanks for the inquiry - unfortunately we haven't really established a workflow for contributing to the repository. If it fits into the current bulk of code in the repository (concepts derived with SQL or fully encapsulated executable documents), then the best way is to make a pull request from the master branch. However if it is slightly different, then I would just raise an issue about it so we can discuss whether the code is useful in this repository or whether it makes more sense for us to link to another repository containing it.

**Comment by alistairewj** [comment]
Looks like your team made a pull request - feel free to reopen this issue if you'd like to further discuss.
