### ISSUE TITLE
Severity  Scores for Neonates

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#308]
In the mimic-code/concepts/severityscores.sirs sql
or for SOFA and qSOFA scores it has been mentioned that
"The score is calculated for *all* ICU patients, with the assumption that the user will subselect appropriate ICUSTAY_IDs.
For example, the score is calculated for neonates, but it is likely inappropriate to actually use the score values for these patients."

We want to know why these scores cannot be used for neonates?

Is this because of the cutoff values or some other reason?

**Comment by alistairewj** [comment]
These scores were created for use on an adult critical care population. The values that they use for cut-offs are all based around normal physiology for an adult human. Neonatal patients have markedly different physiology (e.g. neonatal heart rates are much higher than adult heart rates), and so the scores are likely inappropriate for these patients.
