### ISSUE TITLE
where are the information about cardiac massage and defibrilation ?

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#309]
hello, I'm wondering where can I find the information about cardiac massage and defibrilation among 26 files ?

**Comment by alistairewj** [comment]
You'll need to look for this data using the d_items table (a definition of `itemid`) and the corresponding data table (usually chartevents). See [this tutorial](http://nbviewer.jupyter.org/github/MIT-LCP/mimic-code/blob/860eaec3dfa3e106a79871ceee868e5dcdd97c9f/notebooks/crrt-notebook.ipynb) for a good example of doing this for parameters associated with continuous renal replacement therapy.
