### ISSUE TITLE
LOINC Code mismatch for Neutrophils in blood urine

### ISSUE THREAD

**Issue by daisy647lsq** [MIT-LCP/mimic-code#311]
I was trying to pullout ICU records for Neutrophils in blood. I found a label named 'Neutrophils' in table D_LABITEMS, however the LOINC code represents Neutrophils in urine. Please advice on where to find the Neutrophils in blood value.

Another problem, I checked the itemid for Neutrophils in table labevents, the unit of the value is a percentage. But by right the unit should be a count.

**Comment by tompollard** [comment]
> I was trying to pullout ICU records for Neutrophils in blood. I found a label named 'Neutrophils' in table D_LABITEMS, however the LOINC code represents Neutrophils in urine. Please advice on where to find the Neutrophils in blood value.

Try searching the label column in `d_labitems` for the term that you're interested in. For example, the following query:

```
select * 
from d_labitems 
where lower(label) like '%neut%';
```

...returns some rows that might be relevant:

```
 row_id | itemid |                label                 |           fluid           |  category  | loinc_code 
--------+--------+--------------------------------------+---------------------------+------------+------------
    549 |  51349 | Hypersegmented Neutrophils           | Cerebrospinal Fluid (CSF) | Hematology | 26506-6
     73 |  50872 | Anti-Neutrophil Cytoplasmic Antibody | Blood                     | Chemistry  | 35279-9
    432 |  51232 | Hypersegmented Neutrophils           | Blood                     | Hematology | 766-6
    456 |  51256 | Neutrophils                          | Blood                     | Hematology | 761-7
```

**Comment by daisy647lsq** [comment]
For itemid 51256 Neutrophiils, the fluid column shows 'Blood', but I have checked the loinc_code 761-7 actually represents 'Neutrophiils in Urine'. 
While loinc_code 751-8  represents 'Neutrophiils in blood',  but I'm not able to find it in the d_labitems table. Please advice

**Comment by tompollard** [comment]
Interesting, thanks for highlighting the mismatch. My guess would be that the fluid column is correct and LOINC has been incorrectly mapped, but we'll look into this.

**Comment by alistairewj** [comment]
Going to track this in the broader issue about incorrect LOINC in d_labitems: https://github.com/MIT-LCP/mimic-code/issues/938
