### ISSUE TITLE
How to find the placement of central venous catheter?

### ISSUE THREAD

**Issue by peiyaoli** [MIT-LCP/mimic-code#312]
Can I find the placement time of central venous catheter in MIMIC-III?
And which tables and keyword should I use?
Thanks
@tompollard @alistairewj

**Comment by peiyaoli** [comment]
Currently, I could only locate the implementation of *Central Venous Catheter* through *Central Venous Pressure* and its itemid is 220072. However, this is only for metavision system. For the carevue, what is corresponding itemid?

**Comment by alistairewj** [comment]
I had a look - and had an attempt on the dev branch - see here: https://github.com/MIT-LCP/mimic-code/blob/afcd18d6d5763a7a445001b4274a5d7bc38f1687/concepts/durations/central-line-durations.sql

Looks like it's documented in a bit of an unusual way. Essentially it's:

* `locationcategory` from procedureevents_mv for metavision for invasive line `itemid`
* `INV #1-#8 Type` and `INV #1-#8 Site` in chartevents for carevue - ensure the `value` for the site and type is consistent with a central line

But this code is *not* ready - I haven't exhaustively figured out the combination of type+site that guarantees it's a central line (e.g. triple lumen + right subclavian = central line?). Also made up a rule that if there's no documentation for 16 hours in CareVue the line was removed - haven't run that by nursing staff to get a sense of if that's reasonable. Feel free to do a pull request with improvements!

**Comment by alistairewj** [comment]
Whoops, small typo in that last query, see here for fixed version: https://github.com/MIT-LCP/mimic-code/blob/cec160918db9f36abcc6e60b3d483178d1caced0/concepts/durations/central-line-durations.sql

**Comment by peiyaoli** [comment]
Can we find the insertion of catheter site？ @alistairewj

**Comment by alistairewj** [comment]
Yes you can definitely get that information, I collapsed the site of insertion in that query.

**Comment by alistairewj** [comment]
added query to master branch but has issues, can discuss in #371
