### ISSUE TITLE
12 lead ecg data in mimic waveforms

### ISSUE THREAD

**Issue by TheShadow29** [MIT-LCP/mimic-code#314]
I am sorry if this isn't the correct place to post this.
I have downloaded some mimic3 waveforms from the matched subset. I would be using ecg data for my project and I would need data from all 12 leads measured at the same time. But most data doesn't seem to contain all the 12 leads and moreover not all are taken at the same time. Is there a way I can identify this from the database of the csv files? Als is there an identifier for a person with no disease? I would need to get this information to get the normal waveforms.
Any help would be appreciated.

**Comment by alistairewj** [comment]
We currently do not have 12 lead ECG waveforms in the database.

**Comment by TheShadow29** [comment]
Is there any multi-channel ecg data? At most I could find only single channel ecg data for some cases.

**Comment by alistairewj** [comment]
There are multiple channels available in the matched waveform database -
whatever is used during routine care. Usually 2, sometimes more.
