### ISSUE TITLE
Large gaps (days) in CHARTTIME table for some patients

### ISSUE THREAD

**Issue by dareneiri** [MIT-LCP/mimic-code#315]
I noticed that some patients have very large intervals between each subsequent charttime in MIMICIII. 
Is there some clinical background as to why this happens? Or was charting not captured during this time? 

For example, subject_id 16445 -- this patient has only one admission, but was transferred from CSRU to CCU, and back again. Maybe there was no charting done in CCU?

```sql
MariaDB [mimiciii]
     > select subject_id, icustay_id, itemid, charttime from CHARTEVENTS
    -> where subject_id = 16445
    -> and charttime between  '2180-07-02 19:30:00' and  '2180-07-11 05:00:00'
    -> order by charttime;
+------------+------------+--------+---------------------+
| subject_id | icustay_id | itemid | charttime           |
+------------+------------+--------+---------------------+
|      16445 |     212575 |     52 | 2180-07-02 19:30:00 |
|      16445 |     212575 |   8368 | 2180-07-02 19:30:00 |
|      16445 |     212575 |     51 | 2180-07-02 19:30:00 |
|      16445 |     212575 |   1337 | 2180-07-10 23:00:00 |
|      16445 |     212575 |    470 | 2180-07-10 23:00:00 |
|      16445 |     212575 |    467 | 2180-07-10 23:00:00 |
```

**Comment by alistairewj** [comment]
It's very odd and after investigating that patient I don't really have a good explanation for the gap in charting. Documentation definitely continues through a CCU stay. I would say large gaps like this are should be a rare event - how frequently have you observed them to occur?

**Comment by dareneiri** [comment]
I did a quick analysis on gap time (in minutes) between each subsequent charttime, which is how I found the large gap for subject_id 16445. There are 365 patients that have a charttime gap of at least 720 minutes (12 hours). 

However, note that I am using a subset of the MIMIC-III data (I selected a subset of the patient population and did not select all itemids in CHARTEVENTS). So this list of patients is an overestimate. I verified some of these patients below in the raw MIMICIII database; the CHARTEVENTS table as having some sort of gab between charting events

```
       subject_id chartingInterval           charttime
1        16445            11910 2180-07-02 19:30:00
2         1891             9720 2192-10-22 09:00:00
4        15892             8340 2127-07-05 06:00:00
5         2686             7500 2179-08-05 18:00:00
8         1509             5400 2121-10-02 09:00:00
9          946             5340 2120-04-25 08:00:00
10       23503             5220 2136-10-01 11:00:00
11       25037             2970 2190-12-10 02:00:00
12       29799             2923 2200-08-13 02:51:00
13        1719             2518 2142-11-09 11:00:00
14       16221             2430 2195-11-13 12:00:00
15        4944             2306 2151-08-16 17:00:00
16       21046             2220 2142-08-13 10:00:00
17       25487             2090 2139-12-11 16:40:00
18       25037             2010 2190-12-12 03:30:00
19        6889             1965 2182-12-27 11:00:00
20       16221             1890 2195-11-15 04:30:00
```

- For example, subject_id 1891: It looks like it's missing data once it got transferred from MICU to CSRU, based on the intime/outime in the TRANSFERS table. 
- subject_id 15892, also missing data once transferred from TSICU to MICU. 
- subject_id 2686 is a bit different, with a 3 day gap between  2179-08-07 20:00:00 and 2179-08-10 21:00:00. But no transfer was recorded. 
- subject_id 1509 also with a 3 day gap between 2121-10-02 09:00:00 and 2121-10-05 19:00:00

I hope that helps. Let me know if you would like me to do any more digging on my end to verify anything.

**Comment by alistairewj** [comment]
I dug through these patients and there is no single reason for these gaps. I think these are the inevitable inconsistencies that occur when you have a database spanning over a decade. I hope you have managed to account for it in your study appropriately. Thanks for raising the issue.

**Comment by dareneiri** [comment]
Thanks for reviewing this. For anyone else curious, to resolve this I remove patients who have a charting gap larger than X hours.
