### ISSUE TITLE
Procedures (dates and non ICD procedures)

### ISSUE THREAD

**Issue by vojtechhuser** [MIT-LCP/mimic-code#317]
The ```procedures_icd``` table lists what procedures are recorded for a given patient.

1. **Can someone please confirm that we don't know the exact date (or time; not that important) when the procedure was done during the hospital stay?** E.g., admission from Mon - Fri and endoscopy was done on Wed.

2. Also, a second source for OMOP procedure table would be ```procedureevents_mv```
For those - we know the time. I guess. Did someone map the item_id s in that table to SNOMED Procedure concepts? (by any chance)

(my join to the admission table)
```
select e.subject_id, e.icd9_code, a.dischtime  from mimic.procedures_icd e join mimic.admissions a  on e.hadm_id=a.hadm_id limit 100;
select e.subject_id, e.icd9_code, a.dischtime  from mimic.diagnoses_icd e join mimic.admissions a  on e.hadm_id=a.hadm_id limit 10;

```

**Comment by alistairewj** [comment]
1. At the moment we can't, will check if it's possible in the future when we next update MIMIC-III.
2. Nobody has done this to my knowledge.
