### ISSUE TITLE
Are there dentistry clinical case notes within this resource?

### ISSUE THREAD

**Issue by drprc80** [MIT-LCP/mimic-code#318]
Hi everyone,

I'm a corpus linguist working out of the University of Queensland, Australia. 

I'm doing a monograph on English for specific purposes writing, focusing on the language of dentistry.  I am looking to access a corpus of clinical case notes specific to dentistry.  These are paper or electronic records of in/out patient treatment as written by dentists/trainees, including diagnosis, treatment performed and any follow-up plan.  I'm looking for professional ones in a repository such as this one, and/or access to undergraduate attempts at these.  

I was wondering whether these MIMIC resources contained this kind of data for dentistry?

If not, if anyone knows of a link to a general medical corpus of clinical notes that also includes dentistry cases, or might have access to professional/novice reports from their institute, I'd be grateful to hear about them.

Best,
Dr. Peter Crosthwaite
University of Queensland

**Comment by alistairewj** [comment]
It's unlikely. There are 5 ICU admissions under the dental service. The notes for these patients are written by residents or attending physicians in the ICU and likely aren't sufficiently related enough to your domain.
