### ISSUE TITLE
In DIAGNOSES_ICD table, what is the significance of SEQ_NUM?

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#319]
Hello,
In DIAGNOSES_ICD table, SEQ_NUM provides the order in which the ICD diagnoses relate to the patient and ICD diagnoses are ordered by priority. Can I presume the first diagnosis is the primary diagnosis and the last one is less important?
I want to extract those patients with cancer. For a patient diagnosed with cancer, how can I tell an active cancer from a cancer in remission for some time?

**Comment by tompollard** [comment]
Please take a look at some of the other issues on this subject (e.g. #199 and #188). We typically consider the first code as the primary diagnosis, and all other codes as secondary (i.e. the sequence beyond the first code is not meaningful).
