### ISSUE TITLE
The quantity of the heights is too small

### ISSUE THREAD

**Issue by will4906** [MIT-LCP/mimic-code#320]
Hello, I want to run the sql ---- HeightWeightQuery.sql to get the bmi. But i found that the quantity of the heights is too small.
I count it as `SELECT "count"(*) FROM heightweight WHERE height_first IS NULL;`
and get the result of it is 20612.
I count the weight `SELECT "count"(*) FROM heightweight WHERE weight_first IS NULL;`and get the result of it is only 122.
Why the gap between the count of height and weight is so big?
Can anyone help me?Thanks.

**Comment by tompollard** [comment]
Height is not recorded as consistently as weight, so there are more null values for height. Weight is used for dosing, so it tends to be well documented. You could try looking at some of the related queries (e.g. https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/height-first-day.sql) which look for the values in additional different sources so may be more complete.
