### ISSUE TITLE
antibiotics

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#324]
how to find the name, start time and end time of antibiotics given to neonates.

**Comment by alistairewj** [comment]
You are unlikely to receive much help with your question. I would highly recommend putting more information into your issue, at a minimum: what approaches you have tried, what you would expect from these approaches and why these approaches aren't giving you what you expect. 

I'll close this for now - if you would like to put more detail in feel free to re-open it afterward.
