### ISSUE TITLE
Antibiotics prescribed to neonates

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#325]
Hi,
Out of 6580 distinct neonates who had Blood Culture, only 49 neonates were prescribed antibiotics.
We want to know what are we missing something because the above-mentioned numbers don't make sense
We used the following queries:-

**Neonates Prescribed antibiotics**
SELECT distinct on (subject_id) 
subject_id, min(startdate) as first_antibiotics 
FROM prescriptions 
WHERE drug IN ( SELECT label FROM d_items WHERE category = 'Antibiotics' ) 
and subject_id in (select subject_id from microbiologyevents where spec_type_desc='BLOOD CULTURE - NEONATE')
group by subject_id;

**Number of neonates who had blood culture**
SELECT distinct on (subject_id) 
subject_id
FROM microbiologyevents 
WHERE spec_type_desc='BLOOD CULTURE - NEONATE'
group by subject_id;

**Comment by alistairewj** [comment]
The drug column of prescriptions does not link to d_items. It is free text. See the documentation page: https://mimic.physionet.org/mimictables/prescriptions/
Also see the schema: https://mit-lcp.github.io/mimic-schema-spy/relationships.html

**Comment by erjthakur** [comment]
Even the following query returned only 5 rows? 

SELECT distinct on (subject_id) 
subject_id, min(starttime) as first_antibiotics 
FROM inputevents_mv
WHERE itemid IN ( SELECT itemid FROM d_items WHERE category = 'Antibiotics' ) 
and subject_id in (select subject_id from microbiologyevents where spec_type_desc='BLOOD CULTURE - NEONATE')
group by subject_id;

**Comment by alistairewj** [comment]
Have you thoroughly investigated the d_items table? Perhaps antibiotics are
primarily stored under a different category.

**Comment by erjthakur** [comment]
Hi,
I used the following query and got 3043 rows.
Is there other ways with which we can optimize the results? 

SELECT distinct on (subject_id) 
subject_id, min(startdate) as first_antibiotics 
FROM prescriptions 
WHERE subject_id in (select subject_id from microbiologyevents where spec_type_desc='BLOOD CULTURE - NEONATE')
and ( drug ~* 'Caspofungin'
     or drug ~* 'Cefazolin'
     or drug ~* 'Cefepime'
    or drug ~* 'Ceftazidime'
	 or drug ~* 'Ceftriaxone'
	 or drug ~* 'Chloroquine'
	or drug ~* 'Ciprofloxacin'
	or drug ~* 'Clindamycin'
	or drug ~* 'Colistin'
	or drug ~* 'Daptomycin'
	or drug ~* 'Doxycycline'
	or drug ~* 'Erythromycin'
	or drug ~* 'Ethambutol'
	or drug ~* 'Fluconazole'
	or drug ~* 'Foscarnet'
	or drug ~* 'Gancyclovir'
	or drug ~* 'Gentamicin'
	or drug ~* 'Imipenem/Cilastatin'
	or drug ~* 'Isoniazid'
	or drug ~* 'Levofloxacin'
	or drug ~* 'Linezolid'
	or drug ~* 'Mefloquine'
	or drug ~* 'Meropenem'
	or drug ~* 'Metronidazole'
	or drug ~* 'Micafungin'
	or drug ~* 'Moxifloxacin'
	or drug ~* 'Nafcillin'
	or drug ~* 'Oxacillin'
	or drug ~* 'Penicillin G potassium'
	or drug ~* 'Piperacillin'
	or drug ~* 'Piperacillin/Tazobactam (Zosyn)'
	or drug ~* 'Pyrazinamide'
	or drug ~* 'Quinine'
	or drug ~* 'Ribavirin'
	or drug ~* 'Rifampin'
	or drug ~* 'Bactrim (SMX/TMP)'
	or drug ~* 'Dalfopristin/Quinupristin (Synercid)'
	or drug ~* 'Tobramycin'
	or drug ~* 'Valgancyclovir'
	or drug ~* 'Voriconazole'
	or drug ~*	'Vancomycin'
	or drug ~* 'Acyclovir'
	or drug ~* 'Ambisome'
	or drug ~* 'Amikacin'
	or drug ~* 'Ampicillin'
	or drug ~* 'Ampicillin/Sulbactam (Unasyn)'
	or drug ~* 'Atovaquone'
	or drug ~* 'Azithromycin'
	or drug ~* 'Aztreonam'
	or drug ~* 'Tamiflu'
    or drug ~* 'Keflex'
    )

group by subject_id;

**Comment by alistairewj** [comment]
Usually manually going through the list of drugs to ensure you have captured them all is the most robust way to ensure data capture. You may also want to investigate whether the specimen type can be something other than `BLOOD CULTURE - NEONATE`.
