### ISSUE TITLE
Resources utilization scores

### ISSUE THREAD

**Issue by sacht12** [MIT-LCP/mimic-code#328]
I am trying to estimate the level of resources utilization. I was able to see that the codes for APACHE-II and other scores which measure the severity of illness. I was wondering if someone has calculated either the TISS, NEMS score or something similar using the MIMIC-III data.

http://www.enferpro.com/documentos/ComocumplimentarNEMS.pdf

**Comment by alistairewj** [comment]
These scores are currently not available. I think retrospectively identifying something like TISS 28 will be challenging as it uses concepts not routinely captured (e.g. pacemaker on standby, phlebotomies, etc). There might be a score routinely documented already, or maybe there is a simpler workload score which can be derived. Worth investigation!
