### ISSUE TITLE
What do the alarm chartevents exactly mean?

### ISSUE THREAD

**Issue by Benziner** [MIT-LCP/mimic-code#329]
An example:

- row_id 24288398, 24288390 and 24288389 in table chartevents are all for the same patient.
- Itemid 224687 (row_id 24288398) shows the minute volume at charttime 2101-09-12 17:00:00
- Itemid 220293 (row_id 24288390) shows the Minute Volume Alarm - High at charttime 2101-09-12 
  17:00:00 (same charttime)
- Itemid 220292 (row_id 24288389) shows the Minute Volume Alarm - Low at charttime (2101-09-12 
  17:00:00) (same charttime).

I thought that the alarm events occur then the special item values (here minute volume) undergoes or overgoes some threshold but how could it be that all three events (minute volume, Minute volume alarm - high and minute volume alarm - low) could appear at the same time?

Maybe my understanding of how the alarm events work is just wrong. So what is the interpretation of the alarm events (here for example Minute volume alarm - high and minute volume alarm - low)?

Is it possible that these "events" are no real alarms of patient parameters going under or over some threshold but these events are "setting events" at which some doctor or nurse adjusted the threshold to some value?

**Comment by alistairewj** [comment]
Your last suggestion is exactly right: these are alarm settings, not the actual alarms.

**Comment by Benziner** [comment]
oh ok, this is of course not, what I wanted to hear.. But thank you very much! Do you know if there are any real alarm events, which occur as soon as the thresholds are exceeded ? Or do I have to extract them out of the combination of the setted threshold and the measured value at time point x?

**Comment by alistairewj** [comment]
You probably wouldn't have much luck with that because only the nurse validated vital signs are saved in the ICU database, and there's no guarantee they validate those measures.

The MIMIC-III waveform database has minute by minute numerics but only for vital signs. If you are interested in alarms specifically for ventilation it is likely not feasible at this time.

**Comment by Benziner** [comment]
Actually I would like to have as much different events as possible. The idea is to identify normal and abnormal (chart-)events. This should work of course as much automatically as possible. This is of course no problem for the labevents because of their flag column, which identifies normal and abnormal events but for the chartevents this is very difficult because of their heterogenous appearance. 

Do you see any solution for that?

**Comment by alistairewj** [comment]
Those flags are based on reference ranges of "normal" values. You could definitely use domain knowledge to define similar rules for other measurements - I don't think the alarm settings are the right way to go here. I also remember another group being interested in a similar problem, discussion here: https://github.com/YerevaNN/mimic3-benchmarks/issues/12
