### ISSUE TITLE
Error about adding indexes

### ISSUE THREAD

**Issue by GalaChen** [MIT-LCP/mimic-code#331]
During the MIMIC database setup, I added indexes using:
\i postgres_add_indexes.sql
However, from the "chartevents" to "transfers", I get error:
index "..." does not exist, skipping
it seems like that only "admissions", "callout", "caregivers" get indexes.

Before using postgres_add_indexes.sql, I have used "set search_path to mimiciii" and \dt showed all the tables.

My OS is Windows 10 and I use PosgreSQL 9.6

How do I fix this so I can add indexes? Thanks!!!

**Comment by alistairewj** [comment]
That doesn't sound like an error, it's only a warning that it's not
deleting an index that doesn't exist yet. Is there another error message
later on?

**Comment by GalaChen** [comment]
There had no other error message later.
What does your mean about "deleting an index that doesn't exist yet"?  For me, I want to add index to my table in database.
Thanks! @alistairewj

**Comment by alistairewj** [comment]
The script builds indices using the same pattern:

```sql
DROP INDEX IF EXISTS ....
CREATE INDEX ...
```
The idea is you (1) delete old indexes, if they exist, and then (2) create new ones. If there is no index to drop, then it prints a warning `index "..." does not exist, skipping`. It's a bit misleading that it looks like an error. All this means is that you had a fresh install, so there were no indexes to drop.

**Comment by GalaChen** [comment]
Got it！
Thank you very much!
 @alistairewj
