### ISSUE TITLE
Building a query to calculate qsofa off a subset of patients with sepsis or severe sepsis.

### ISSUE THREAD

**Issue by Ataxia123** [MIT-LCP/mimic-code#336]
The query selects about 13k patients, after which I run vitalsfirstday and gcsfirstday obtaining 9k and 13k results (vitals filters some missing data).

My problem is when I run qsofa.sql I get back over 100k results even though im using icustay_id from the materialized view I used to get my cohort. Im going to run qsofa.sql in chunks to find what goes wrong but im at a loss atm

**Comment by Ataxia123** [comment]
I ran an extra query to select first day events (like its supposed to happen on firstday queries) but it only increased the number of results I got to over a million...

**Comment by alistairewj** [comment]
I just re-ran the qsofa.sql query and I get the correct number of rows (61532, one for each ICUSTAY_ID). What exactly are you joining together and how?

**Comment by Ataxia123** [comment]
DROP MATERIALIZED VIEW IF EXISTS septic_pt CASCADE;
create materialized view septic_pt as
WITH table_1 AS
(
  SELECT icd.subject_id, ICD9_CODE, ie.hadm_id, ie.icustay_id, ie.intime,
ie.outtime
  FROM diagnoses_icd icd
  INNER JOIN icustays ie
  ON icd.subject_id = ie.subject_id
)
,  septic_icu AS
(
  SELECT subject_id, ICD9_CODE, hadm_id, icustay_id, intime, outtime
  FROM table_1
  WHERE ICD9_CODE = '99591'
  OR ICD9_CODE = '99592'
 )
SELECT ie.subject_id, ie.hadm_id, ie.icustay_id,
    ie.intime, ie.outtime, adm.deathtime,
    ROUND((cast(ie.intime as date) - cast(pat.dob as date))/365.242, 2) AS
age,
    ROUND((cast(ie.intime as date) - cast(adm.admittime as date))/365.242,
2) AS preiculos,
    CASE
        WHEN ROUND((cast(ie.intime as date) - cast(pat.dob as
date))/365.242, 2) <= 1
            THEN 'neonate'
        WHEN ROUND((cast(ie.intime as date) - cast(pat.dob as
date))/365.242, 2) <= 14
            THEN 'middle'
        -- all ages > 89 in the database were replaced with 300
        WHEN ROUND((cast(ie.intime as date) - cast(pat.dob as
date))/365.242, 2) > 100
            THEN '>89'
        ELSE 'adult'
        END AS ICUSTAY_AGE_GROUP,
    -- note that there is already a "hospital_expire_flag" field in the
admissions table which you could use
    CASE
        WHEN adm.hospital_expire_flag = 1 then 'Y'
    ELSE 'N'
    END AS hospital_expire_flag,
    -- note also that hospital_expire_flag is equivalent to "Is
adm.deathtime not null?"
    CASE
        WHEN adm.deathtime BETWEEN ie.intime and ie.outtime
            THEN 'Y'
        -- sometimes there are typographical errors in the death date, so
check before intime
        WHEN adm.deathtime <= ie.intime
            THEN 'Y'
        WHEN adm.dischtime <= ie.outtime
            AND adm.discharge_location = 'DEAD/EXPIRED'
            THEN 'Y'
        ELSE 'N'
        END AS ICUSTAY_EXPIRE_FLAG
FROM septic_icu ie
INNER JOIN patients pat
ON ie.subject_id = pat.subject_id
INNER JOIN admissions adm
ON ie.hadm_id = adm.hadm_id;

gives back

the selection goes on on the first part, where it should select the hadm_id
where ICD_CODE = sepsis or severe sepsis. This works for the selection (13k
patients/

for vitalsfirstday and gcsfirst day I replaced icustays with septic_pt ie
and it works fine... gcs selects the same amount of pts and vitalsfirstday
selects a smaller subset because it drops some of the entries with missing
data.

When I replace icustays on the qsofa code I get many more entries, most of
which are repeated I guess...

DROP MATERIALIZED VIEW IF EXISTS QSOFA CASCADE;
CREATE MATERIALIZED VIEW QSOFA AS
with scorecomp as
(
select ie.icustay_id
  , v.SysBP_Min
  , v.RespRate_max
  , gcs.MinGCS
from septic_pt ie
left join vitalsfirstday v
  on ie.icustay_id = v.icustay_id
left join gcsfirstday gcs
  on ie.icustay_id = gcs.icustay_id
)
, scorecalc as
(
  select icustay_id
  , case
      when SysBP_Min is null then null
      when SysBP_Min   <= 100 then 1
      else 0 end
    as SysBP_score
  , case
      when MinGCS is null then null
      when MinGCS   <= 13 then 1
      else 0 end
    as GCS_score
  , case
      when RespRate_max is null then null
      when RespRate_max   >= 22 then 1
      else 0 end
    as RespRate_score
  from scorecomp
)
select ie.subject_id, ie.hadm_id, ie.icustay_id
, coalesce(SysBP_score,0)
 + coalesce(GCS_score,0)
 + coalesce(RespRate_score,0)
 as qSOFA
, SysBP_score
, GCS_score
, RespRate_score
from septic_pt ie
left join scorecalc s
  on ie.icustay_id = s.icustay_id
order by ie.icustay_id;

i just ran this again with 104k results

>

**Comment by alistairewj** [comment]
You are duplicating rows when you call ` FROM diagnoses_icd icd INNER JOIN icustays ie ON icd.subject_id = ie.subject_id` for two reasons: (1) because diagnoses_icd is based on hospitalizations and each patient can have multiple hospitalizations (i.e. diagnoses_icd will have multiple rows for `subject_id`), and (2) because icustays is based on ICU stays and each patient can have multiple ICU stays (i.e. icustays will have multiple rows for `subject_id`). You should try to make at least one side of a join unique for the column you plan on joining, otherwise you're in for a headache.
