### ISSUE TITLE
Some questions about the number of adults in sepsis patients

### ISSUE THREAD

**Issue by yixuenaqi** [MIT-LCP/mimic-code#338]
Recently,I have met some problems about the  number of adults in sepsis patients.Firstly,I recoded the angus.sql(mimic-code/concepts/sepsis/angus.sql) for the infected adult patients,These are the codes:
  WITH agetbl AS
(
  SELECT DISTINCT adm.subject_id,ROUND( (CAST(EXTRACT(epoch FROM adm.admittime - p.dob)/(60*60*24*365.242) AS numeric)), 0) AS age
  FROM admissions adm
  INNER JOIN patients p
  ON adm.subject_id = p.subject_id
) ,
infection_group AS 
(
	SELECT subject_id, hadm_id,
	CASE
		WHEN substring(icd9_code,1,3) IN ('001','002','003','004','005','008',
			   '009','010','011','012','013','014','015','016','017','018',
			   '020','021','022','023','024','025','026','027','030','031',
			   '032','033','034','035','036','037','038','039','040','041',
			   '090','091','092','093','094','095','096','097','098','100',
			   '101','102','103','104','110','111','112','114','115','116',
			   '117','118','320','322','324','325','420','421','451','461',
			   '462','463','464','465','481','482','485','486','494','510',
			   '513','540','541','542','566','567','590','597','601','614',
			   '615','616','681','682','683','686','730') THEN 1
		WHEN substring(icd9_code,1,4) IN ('5695','5720','5721','5750','5990','7110',
				'7907','9966','9985','9993') THEN 1
		WHEN substring(icd9_code,1,5) IN ('49121','56201','56203','56211','56213',
				'56983') THEN 1
		ELSE 0 END AS infection
	FROM diagnoses_icd
),
organ_diag_group as
(
	SELECT subject_id, hadm_id,
		CASE
		-- Acute Organ Dysfunction Diagnosis Codes
		WHEN substring(icd9_code,1,3) IN ('458','293','570','584') THEN 1
		WHEN substring(icd9_code,1,4) IN ('7855','3483','3481',
				'2874','2875','2869','2866','5734')  THEN 1
		ELSE 0 END AS organ_dysfunction,
		-- Explicit diagnosis of severe sepsis or septic shock
		CASE
		WHEN substring(icd9_code,1,5) IN ('99592','78552')  THEN 1
		ELSE 0 END AS explicit_sepsis
	FROM diagnoses_icd
),
-- Mechanical ventilation
organ_proc_group as
(
	SELECT subject_id, hadm_id,
		CASE
		WHEN substring(icd9_code,1,4) IN ('9670','9671','9672') THEN 1
		ELSE 0 END AS mech_vent
	FROM procedures_icd
),
aggregate as
(
	SELECT subject_id, hadm_id,
		CASE
			WHEN hadm_id in
					(SELECT DISTINCT hadm_id
					FROM infection_group
					WHERE infection = 1)
				THEN 1
			ELSE 0 END AS infection,
		CASE
			WHEN hadm_id in
					(SELECT DISTINCT hadm_id
					FROM organ_diag_group
					WHERE explicit_sepsis = 1)
				THEN 1
			ELSE 0 END AS explicit_sepsis,
		CASE
			WHEN hadm_id in
					(SELECT DISTINCT hadm_id
					FROM organ_diag_group
					WHERE organ_dysfunction = 1)
				THEN 1
			ELSE 0 END AS organ_dysfunction,
		CASE
		WHEN hadm_id in
				(SELECT DISTINCT hadm_id
				FROM organ_proc_group
				WHERE mech_vent = 1)
			THEN 1
		ELSE 0 END AS mech_vent
	FROM admissions
)
SELECT DISTINCT aggregate.subject_id, aggregate.hadm_id, aggregate.infection,
case 
    when agetbl.age >= 18 then 1
    ELSE 0 END
AS adult
FROM aggregate
left JOIN agetbl
  ON aggregate.subject_id = agetbl.subject_id
By the codes,I have 58976 rows,with 21948 infected patients,but only 237 patients who are less than 18 years old.
However,the right number of infected patients less than 18 years old are 457 .I have checked many times,and I do not know where I am wrong.So I come here for help.
Thanks!

**Comment by alistairewj** [comment]
Instead of using `DISTINCT`, I would recommend ensuring your joins aren't duplicating rows. It's much easier to follow the process. For example, `FROM aggregate LEFT JOIN agetbl ON aggregate.subject_id = agetbl.subject_id` will duplicate rows because `agetbl` has multiple rows for each `subject_id` (one for each `admittime`). I would instead write `agetbl` using group by.

Alternatively, why don't you simplify this and join to the `angus_sepsis` view using a fixed version of `agetbl`?
