### ISSUE TITLE
information on Adverse Effects of Medical Care and Drugs

### ISSUE THREAD

**Issue by freestylezhy** [MIT-LCP/mimic-code#339]
Hi, 

I am trying to find information on Adverse Effects of Medical Care and Drugs **during** the ICU stays. The diagnoses table contains ICD9 codes, and there are ICD 9 E-codes (External Cause Codes) that corresponds to Adverse Effects of Medical Care and Adverse Effects of Medical Drugs. However, according to the this [webpage](http://journal.ahima.org/2014/08/13/monthly-code-cracker-transitioning-from-e-codes-in-icd-9-cm-to-v-w-x-y-codes-in-icd-10-cm/), "In ICD-9-CM, E codes are only assigned on the initial encounter, whereas in ICD-10-CM, the external cause codes are used for the length of the treatment". 

I am wondering where I can find the information on Adverse Effects of Medical Care and Drugs **during** the ICU stays. For example, are the ICD-9 E-codes really assigned upon encounter? Are there ICD-10 codes? Are the Adverse Effects noted somewhere else?

Thanks a lot!

**Comment by alistairewj** [comment]
ICD-9 codes are assigned to hospital encounters at the end of the hospital stay. There are currently no ICD-10 codes as ICD-10 were not used at the time of the data collection.

I am not sure how reliably adverse events would be documented in the ICU information system. It will likely vary for the particular type of event.

**Comment by freestylezhy** [comment]
Thanks a lot the answer! May I rephrase the question more specifically? there are two very common ICD 9 E codes in the database, namely:
ICD 9  | CCS Name
E8798 | E Codes: Adverse effects of medical care
E9320 | E Codes: Adverse effects of medical drugs

Do they reflect the adverse effects in the current hospital admission or ICU stay? Or, they happened before the encounter, and may even be the *reason* of the hospital admission or ICU stay? 

Thanks a lot!

**Comment by alistairewj** [comment]
Ah, we are quickly stepping out of my realm of expertise. However, I can confidently say that the ICD-9 codes are all assigned for hospital stays, so they would *not* be specific to the ICU stay. Depending on the patient, it may or may not be the actual reason for hospital admission/ICU stay.
