### ISSUE TITLE
Finding subjects with specific waveforms in MIMIC3mached dataset!

### ISSUE THREAD

**Issue by rabbani89** [MIT-LCP/mimic-code#340]
Hi!

I'm sorry in advance if my question is not related to this place! 
I'm working on analyzing the Intracranial pressure (ICP) in brain-injured patients. I use MIMIC3 matched dataset (last version, v1.4), and I need to find patients with ICP waveform in this dataset. I'm wondering if there is any solution for this problem.

Thanks a lot!

**Comment by alistairewj** [comment]
It's fine to talk about the matched waveform dataset here. You should be able to find ICP records by searching through the headers. One tutorial that may be helpful is [Finding records in PhysioNet](https://physionet.org/physiobank/database/pbi/).  There you will find a link to the [PhysioNet search tool](https://physionet.org/cgi-bin/pbsearch?help_on=on). I did an example search looking for "ICP":

![image](https://user-images.githubusercontent.com/1282676/33444462-6148bd48-d5c8-11e7-9601-dc440c0d2f27.png)

As you can see that returned 772 records across all of PhysioNet. Scrolling down to the bottom, I got this list of matched records:

```
mimic2wdb/matched/s04904/s04904-3344-04-20-03-04
mimic2wdb/matched/s04904/s04904-3344-04-20-03-04n
mimic2wdb/matched/s17875/s17875-3026-11-08-15-43
mimic2wdb/matched/s17875/s17875-3026-11-08-15-43n
mimic2wdb/matched/s27338/s27338-2703-01-02-23-04
mimic2wdb/matched/s27338/s27338-2703-01-02-23-04n
mimic2wdb/matched/s27833/s27833-2511-01-30-17-29
mimic2wdb/matched/s27833/s27833-2511-01-30-17-29n
mimic2wdb/matched/s27845/s27845-3347-01-04-22-12
mimic2wdb/matched/s27845/s27845-3347-01-04-22-12n
mimic2wdb/matched/s28075/s28075-3395-05-18-16-21
mimic2wdb/matched/s28075/s28075-3395-05-18-16-21n
mimic2wdb/matched/s28075/s28075-3395-05-19-11-41
mimic2wdb/matched/s28075/s28075-3395-05-19-11-41n
mimic2wdb/matched/s29527/s29527-2757-03-08-17-54
mimic2wdb/matched/s29527/s29527-2757-03-08-17-54n
mimic2wdb/matched/s29569/s29569-3484-05-05-17-47
mimic2wdb/matched/s29569/s29569-3484-05-05-17-47n
mimic2wdb/matched/s30640/s30640-3495-02-04-02-49
mimic2wdb/matched/s30640/s30640-3495-02-04-02-49n
```

Looking at https://physionet.org/physiobank/database/mimic2wdb/matched/s04904/3068585_layout.hea confirmed I found a record with the ICP label. No guarantee there is any data recorded though!

I don't think the index that is searched has been updated for the MIMIC-III matched waveform database yet though. In the meantime, you could do a search using command line utilities such as `grep`.
