### ISSUE TITLE
How to get information about past medical history?

### ISSUE THREAD

**Issue by yixuenaqi** [MIT-LCP/mimic-code#343]
I need to get some information about the past medical history and the usage of PPI。However this issue concerns how to extract strings from Noteevents.
SELECT subject_id,hadm_id,text
FROM noteevents
WHERE text LIKE '%Losec%'or text LIKE'%omepramzole%'or text LIKE'%lansoprazole%'or text LIKE'%Takepron%'or text LIKE'%pantoprazole%'
                 or text LIKE'%Pantotoc%'or text LIKE'%rabeprazole%'or text LIKE'%Pariet%'or text LIKE'%esomprazole%'or text LIKE'%Nexium%'or text LIKE'%Revaprazan%'or text LIKE'%Rebanex%'or text LIKE'%Ilaprazole%'or text LIKE'%Dexlansoprazole%'
                 or text LIKE'%Kapidex%'or text LIKE'%Leminorazole%'or text LIKE'%Leminon%'
I have got 9874 rows by the code.Now I am not sure wheather mg codes right or not ? And how to simplify the codes?

**Comment by alistairewj** [comment]
This will capture text strings, but note:

1. You are doing a case sensitive match, so you will fine `lansoprazole` but you will *not* find `Lansoprazole`. You can use `ilike` to do case insensitive matching.
2. You are searching all notes (including radiology reports, ECGs, echos, and so on). Focusing on the discharge summary, which is the primary location for documentation of admission information/past medical history, is probably a good idea (use the `category` and `description` columns to do this).
3. Finally, following on from before, your query will search the entire note, but you likely want to identify a specific subsection of the discharge summary and only look in that subsection (e.g. only look in the past medical history subsection). This again has to be done with free text and you can try to do it via SQL or using a different language such as Python. See https://github.com/mghassem/medicationCategories

**Comment by yixuenaqi** [comment]
Thank you very much for your advice!.But can you provide some examples about how to extract past medical history by Postgresql?

**Comment by alistairewj** [comment]
I do not have any postgres code which does what you ask unfortunately. I can try to give some advice. I would do this in three stages, (1) identify the section start using a substring statement like the one you have, (2) identify the section end by looking for either the start of a new section (words followed by a colon) or two sequential newline characters, (3) extract out only the text from (1) to (2). 

In terms of your substring, it's likely an issue with the regular expression. Some suggestions would be to check case sensitivity and maybe remove the space after the colon (the section header is probably immediately followed by `\n`, not by ` \n`. Also keep in mind, there will be more than one way to write the section header: `Medications on Admission`, `Admission Medications`, etc.
