### ISSUE TITLE
what Item_ID for Alarm (LOW) or Alram (high) mean in chartevent

### ISSUE THREAD

**Issue by benbastaki** [MIT-LCP/mimic-code#346]
Hi,

In chartevents table, where for e.g. we have Item ID = "220046" which is for 'HR alarm High'. or different one for 'HR alarm low', 'spo2 alarm low', 'spo2 alarm high'.
what these alarm id (low) and (high) mean for each vital sign including HR, BP and SpO2. I need to know what is the purpose of these data in icu. what is there correlation with each other? how they are used in icu?
I am using them with HR, BPs,BPd and SpO2 readings in date stream for a prediction. 

Thanks for your support in advance.

**Comment by alistairewj** [comment]
They are alarm settings for the monitor. Nurses at the bedside have the capability of changing the threshold at which an alarm goes off (e.g. bradycardia and tachycardia alarms for heart rate), and they document these settings in chartevents.

**Comment by benbastaki** [comment]
So if in chartevent table, Spo2 alarm (high) is 100 at time 12:00, is that mean alarms has gone off? or is that mean this value will be used for when spo2 reading value at time 12:50 match to the value of Spo2 alarm (high) 100 then an alarm goes off?

what is NBPmean? how is calculated? and what is useful for?

**Comment by alistairewj** [comment]
If the alarm value is 100 then any SpO2 values above 100 will trigger the alarm. It does not necessarily mean the alarm has triggered.

NBPmean is Mean non-invasive blood pressure, usually measured by an arm-cuff, and useful for patient monitoring.

**Comment by benbastaki** [comment]
Thanks.
Are NBPs,NBPd, SpO2, and HR are useful fields for monitoring patients. do you think these values would have different pattern for the patient who having a different service? (e.g. MED to CMED. SURG to MED )? 

When I check  the chartevent table. there are spo2 and HR reading almost every 30 minutes or 1 hour. but for NBPs and NBPd, for some patients, there is every 5 hours or more or less. 
Do you know what is best way of filling these 0 values, when there is no reading for nbps and nbpd? or if  there is different type of (item_id) I should collect for BPs and BPd? I am using metavision.

Thanks for your help!

**Comment by alistairewj** [comment]
Yes, patients on different services will on average look different. SpO2/HR are measured continuously (from the pulse oximiter and ECG), while NBP is measured aperiodically (requires the arm cuff to inflate/deflate). The best way to impute missing data is an entire field of research so I probably can't give you a satisfactory answer here - but it's definitely worth also incorporating invasive blood pressure measurements when getting data. See the first day vital sign queries to learn more about that.

**Comment by benbastaki** [comment]
Thanks. My last question, by invasive blood pressure, do you mean arterial blood pressure, those are in dItem table ? item ids = 220050, 220051? if not could you please kindly tell me what is their name in the dItem table or their item_ID so I can collect the value.


"See the first day vital sign queries to learn more about that", do you mean I check the 24 hours reading of vital signs in chartevent table?

**Comment by alistairewj** [comment]
1) Yes, I mean those ones.

2) I meant you could look at this query for inspiration: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/vitals-first-day.sql
