### ISSUE TITLE
What are the risk level of each services?

### ISSUE THREAD

**Issue by benbastaki** [MIT-LCP/mimic-code#349]
I would like to know risk level of the below services.
CMED, CSURG , MED, NMED, NSURG, ORTHO, OMED, PSYCH, SURG, TRAUM, TSURG, VSURG

e.g. CMED has a higher risk level than MED or SURG?

I also like to know, Can we detect if a patient will move to an another service by reading their HR,BPs,BPs and SPO2?

**Comment by alistairewj** [comment]
I don't think there is a fixed risk level difference. It will depend on the patient population you study. For example, you could argue surgical admissions are "less risky" than medical admissions, but then that would depend if it was an elective surgery or an emergency surgery. I don't think this question is a useful one devoid of any clinical context.
