### ISSUE TITLE
About SOFA score

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#351]
Hello,
Is that possible to extract SOFA score from day 1 to day 7 form MIMIC III ? or each day during ICU stay ? How to realize it ?

**Comment by alistairewj** [comment]
Yes, certainly this is possible. You could adapt the queries we have now which calculate SOFA on day 1 - primarily by changing the time period over which the query searches.

**Comment by mylanhong** [comment]
@alistairewj  Thank you very much !
