### ISSUE TITLE
error building labevents and chartevents tables in pgAdmin4

### ISSUE THREAD

**Issue by evanjones57** [MIT-LCP/mimic-code#353]
Hello.  I'm just learning postgres and don't have a programming background so please be gentle.  

I'm building the database in pgAdmin4 and everything is mostly working and I'm able to load the majority of tables with only some minor issues that I've worked through.   I'm getting an error when trying to load the labevents and chartevents tables.  The error is as follows,

ERROR: out of memory
DETAIL: cannot enlarge string buffer containing 1073741769 bytes by 76 more bytes
CONTEXT: COPY labevents, line 22664230

The error is similar for chartevents other than the numbers being slightly different.  I'm using an iMac with (I think) plenty of memory (32GB) and HD (3T fusion).  I've optimized the postgres settings using PgTune so I don't think it's an issue with that.

From what I can gather online, this is likely an issue with pgAdmin4 and it just not being set-up to handle string buffers >1 GB.  Is this correct?  Anyone have an ideas for a fix or work around?

Thanks in advance.  And thanks for all the tutorials, etc that everyone provides that allow for a super newb like me to potentially use this incredible database.  Cheers!

**Comment by alistairewj** [comment]
Hrm, not particularly familiar, but my experience with pgadmin4 is that it's not the most efficient platform for data loading. I've had data imports crash with the GUI that work flawlessly by command line. I'd recommend trying the command line data import, hopefully the tutorial gives a good idea on how to do it: https://mimic.physionet.org/tutorials/install-mimic-locally-ubuntu/

**Comment by evanjones57** [comment]
Thanks for the reply!  I actually ended up downgrading` to postgres 9.6 and pgAdmin3 and was able to load the database without issue.
