### ISSUE TITLE
CHARTDATE timestamp ambiguity

### ISSUE THREAD

**Issue by peterjliu** [MIT-LCP/mimic-code#354]
Certain events (e.g. NOTEEVENTS) have timestamps with day-level granularity (e.g. CHARTDATE). I wanted to clarify if these events were consistently brought back to the beginning of the day in which they occurred?

This is important in making sure data from the future is not leaked when making predictions at a certain time. If the CHARTDATE timestamps are brought to the beginning of the day, it's probably safer to assume they happen on the next day when building predictive models.

**Comment by alistairewj** [comment]
Chart date is the date the note was charted, and so it's the date that it would appear in the medical record. It's safe to assume that the note was made on that day, and so as you suggest, the safest approach for predictive models is to only use the note on the next day. It's worth noting that most notes have a charttime which gives more precise timing. Finally, I don't think we can guarantee that notes are fixed once they are charted, i.e. they may be updated after the chart time.

**Comment by peterjliu** [comment]
Thanks for the clarification!
