### ISSUE TITLE
Relation between diagnosis and billing

### ISSUE THREAD

**Issue by filipencosta** [MIT-LCP/mimic-code#355]
Hi.

Is it possible to know for each diagnosis the treatment that was applied? To do this my first approach was to join the procedures_icd table and the diagnoses_icd table given the admission id and the seq_num of both tables. Soon i realized that the seq_num of both table is not the same, for instante, the patient with the hadm_id 101182 has five diagnosis but only one entry on the the procedures_icd table.
Thanks.

**Comment by tompollard** [comment]
@filipencosta `procedures_icd` and  `diagnoses_icd` are created for billing purposes at the end of the hospital stay, and as you have found, `seq_num` cannot be used to join between tables. Many treatments will be given over a patient stay. As a start, try exploring the events tables (e.g. `chartevents`, `cptevents`, `datetimeevents`, `inputevents`, etc).
