### ISSUE TITLE
Why did you use GCSVerbal(723), GCSMotor(454), GCSEyes(184) rather than total GCS(198) in gcs-first-day?

### ISSUE THREAD

**Issue by Yuyoo** [MIT-LCP/mimic-code#356]
I found that separate GCSVerbal, GCSMotor, GCSEyes are used to calculate GCS rather than total gcs in gcs-first-day, and their value are different.  Why did you choose the method?  Is total gcs Inaccurate？

**Comment by alistairewj** [comment]
I've never systematically examined the difference. How frequently to they disagree?

Only CareVue actually has a GCS total - MetaVision just stored the components. Based on that, it made sense to just use the components.
