### ISSUE TITLE
How to install concepts folder?

### ISSUE THREAD

**Issue by yixuenaqi** [MIT-LCP/mimic-code#357]
Thanks for this database,I am leaining SQL language now.But I met some problems.
1.How to install concepts folder? I use the codes as the followings:
\c mimic;            
set search_path to mimiciii;   
\i E:/make-concepts.sql
But unfortunately the application prompts \i code-status.sql:no such file or directory.
And I try to run sql one by one such as echo-data.sql,curiously，it only shows "select 43987" and my hard drive space has not changed,and I do not know wheather the sql are insalled successfully.
2. Because my computer did not install gzip software,I delete the codes of  CCS folder from make-concepts.sql. Is it good?

**Comment by alistairewj** [comment]
The make concepts script simply calls all other scripts in the same folder and in subfolders. You have to download the entire repository for it to work - have you done so?

The "select 43987" indicates that the table was successfully created. You can then try to select from it to verify: `select * from echodata;`

**Comment by alistairewj** [comment]
Feel free to reopen - assuming you resolved the issue.
