### ISSUE TITLE
Total Disk Space Needed for calculating SOFA score

### ISSUE THREAD

**Issue by wonderange** [MIT-LCP/mimic-code#358]
Hi,

I am trying to run the code in this repository up until calculating SOFA score, including loading all the data and index, as well as generating several materialized views, as instructed in the README file in the concepts folder. From previous discussions I noticed that the disk space needed for the data + index is ~80GB. However, I am wondering what is the disk space needed for the several materialized views that are required for calculating SOFA score? My laptop has ~120GB available. Will that be enough?

Thanks!

**Comment by alistairewj** [comment]
Yes, that sounds plenty. Most of the materialized views are very small.

**Comment by wonderange** [comment]
Thanks for the reply!
