### ISSUE TITLE
syntax error in postgres_create_tables_pg10.sql

### ISSUE THREAD

**Issue by kswang** [MIT-LCP/mimic-code#359]
Using 10.1 v of postgres on Mac and running into 

> psql:postgres_create_tables_pg10.sql:126: ERROR:  42601: syntax error at or near "PARTITION"
> LINE 18: ) PARTITION BY RANGE (itemid);
>            ^
> LOCATION:  scanner_yyerror, scan.l:1086
> make: *** [mimic-build-gz] Error 3

Also generally running into performance issues, stopped after overnight running (12 hours) to see that only 19M rows of chartevents had been copied using `mimic-gz`. help appreciated.

**Comment by alistairewj** [comment]
I execute the file perfectly on psql v10.1, but when I run it on my Mac (which has psql 9.6.1) I run into the exact same error that you have. Are you sure you are running both psql v10.1 and postgres v10.1?

**Comment by alistairewj** [comment]
Going to assume you somehow ran this with psql v9! Re-open if you still have issues. Note we are working on the build time (see #362 ).
