### ISSUE TITLE
Fix Docker image after restructuring directory

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#36]
The scripts used to build a MIMIC Docker image have been moved to a new directory to fix some issues with the merged code (https://github.com/MIT-LCP/mimic-code/pull/18): https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/docker. I haven't checked, but I expect some updates will be needed to get it working again...

**Comment by alistairewj** [comment]
Rewrote the scripts - they do a sparse checkout of the git repo to pull scripts from the postgres subdirectory (since docker doesn't like symlinks or working in parent directories). Just tested and it's working on my local PC.
