### ISSUE TITLE
About rate of dopamine

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#360]
In INPUTEVENTS_CV table, the RATE columns are null for some patients when I extract vassopressors, but the AMOUNT columns are available. For those patients without RATE value, how can I calculate these rates for vassopressors since there are no starttime and endtime.

**Comment by alistairewj** [comment]
See https://mimic.physionet.org/mimicdata/io/ under the "Inputs" header for information on the table.
