### ISSUE TITLE
umbilical venous catheterization in neonates

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#361]
Hi there

 We want to know whether the number of days for umbilical venous catheterization for neonates has been recorded in the mimic database. 

Kind Regards

**Comment by alistairewj** [comment]
Check the `d_items` table for a concept that matches what you are looking for.

**Comment by erjthakur** [comment]
There are 6580 (with 123 positive cases) neonates who have undergone blood culture and were suspected of sepsis. 
There are only two item id's in the d_items table that are showing some results.
item id  3670 for UAC tubing change has data for 78 distinct neonates whereas
item id  3671 for UVC tubing change has data for 112 distinct neonates.

The above-mentioned item ids tell us that there was catheter inserted in these neonates.
**But the duration for which the catheter was inserted has not been mentioned.**

Other items ids for catheter insertion dates have 0 rows.
We are interested in calculating the duration for which the catheter was inserted in neonates.
Is there any other solution (or code ) that you can point us to which can help us in extracting this information.

**Comment by alistairewj** [comment]
There is no code available, but this sounds like something you could develop. Similar code was developed for creating CRRT durations, and there is a notebook overviewing that process here: https://github.com/MIT-LCP/mimic-code/blob/master/notebooks/crrt-notebook.ipynb
