### ISSUE TITLE
Difficulty copying chartevents

### ISSUE THREAD

**Issue by EmmaRocheteau** [MIT-LCP/mimic-code#362]
I have been trying for over a week to make a local copy of the database on my machine. I'm running ubuntu 16.04. I get this:

mimic=# \i /home/Downloads/mimic-code-master/buildmimic/postgres/postgres_load_data.sql
psql:/home/Downloads/mimic-code-master/buildmimic/postgres/postgres_load_data.sql: 
COPY 58976
COPY 34499
COPY 7567
psql:/home/Downloads/mimic-code-master/buildmimic/postgres/postgres_load_data.sql: ERROR:  out of memory
DETAIL:  Cannot enlarge string buffer containing 1073733732 bytes by 65536 more bytes.
CONTEXT:  COPY chartevents, line 242707759
COPY 573146
COPY 4485937
COPY 651047
COPY 125557
COPY 134
COPY 14567
COPY 3882
COPY 12487
COPY 753
COPY 61532
COPY 17527935
COPY 3618991
COPY 27854055
COPY 631726
COPY 2083180
COPY 4349218
COPY 46520
COPY 4156450
COPY 258066
COPY 240095
COPY 73343
COPY 261897

I split up chartevents into several csvs and then tried again with a new script which copies each csv to chartevents (I read that the default behaviour is to append to the table).  Each csv has 20,000,000 lines in it.

mimic=# \i /home/ecr38/Downloads/mimic-code-master/buildmimic/postgres/postgres_load_chartevents.sql
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
COPY 0
psql:/home/Downloads/mimic-code-master/buildmimic/postgres/postgres_load_chartevents.sql:33: ERROR:  out of memory
DETAIL:  Cannot enlarge string buffer containing 1073687854 bytes by 65536 more bytes.
CONTEXT:  COPY chartevents, line 2707759
psql:/home/Downloads/mimic-code-master/buildmimic/postgres/postgres_load_chartevents.sql:35: ERROR:  invalid byte sequence for encoding "UTF8": 0x00
CONTEXT:  COPY chartevents, line 6596313

The first error corresponds to the same line in the file. Has anyone else had problems with line 242707759?

I have printed the problem lines to the terminal:

ecr38@dart:/local/scratch/ecr38/MIMIC$ sed -n '2707758,2707760p;2707761q' CHARTEVENTSam
251097263,27342,184641,237360,8518,2149-02-01 14:00:00,2149-02-01 15:21:00,20713,"200",200,"bpm",,,,"NotStopd"
251097264,27342,184641,237360,8532,2149-02-7,49068,105351,279856,223988,2190-11-16 00:00:00,2190-11-16 00:10:00,19838,"Rhonchi",,,0,0,,
279405518,49068,105351,279856,223989,2190-11-16 00:00:00,2190-11-16 00:11:00,19838,"Diminished",,,0,0,,

ecr38@dart:/local/scratch/ecr38/MIMIC$ sed -n '6596312,6596314p;6596315q' CHARTEVENTSan
302600823,71369,125230,273729,224086,2188-12-06 20:30:00,2188-12-06 21:53:00,15928,"Good",,,0,0,,
302600824,71369,1252301619870,80523,147471,284535,224026,2183-06-17 20:48:00,2183-06-17 22:48:00,20622,"Impaired",,,0,0,,
311619871,80523,147471,284535,224027,2183-06-17 20:48:00,2183-06-17 22:48:00,20622,"Warm",,,0,0,,

Can anyone help? I'd really appreciate it as I have no experience in databases.

**Comment by tompollard** [comment]
It sounds like a recent change has broken builds for some people. I'm unclear whether is related to an update in Postgres or new partitioning rules. We'll take a look when time permits (or would welcome pull requests from the community in the meantime!).

**Comment by alistairewj** [comment]
Yeah definitely. @EmmaRocheteau seems like you are doing everything right and some recent changes have made the build infeasible for a lot of users. My best guess is it's the change from 14 partitions on chartevents to over 200. I like this change because my queries on chartevents are 5-10x faster but clearly the build is no longer feasible on all machines...  Just started a build for psql 9.6 on a mac, let's see how it fares. If it fails then best option is to (1) only have 14 or so partitions on chartevents and (2) have some logic in the makefile that checks for postgres 10, and if so uses the postgres 10 build script.

**Comment by alistairewj** [comment]
So I tried to run the new build on a mid 2012 mac and after 24 hours it's still now done loading!

I updated the make file and the associated `postgres_create_tables.sql` to use fewer partitions. It should run faster now - though not fast, still probably overnight. If you can please try again.

**Comment by alistairewj** [comment]
So I tried to run the new build on a mid 2012 mac and after 24 hours it's still now done loading!

I updated the make file and the associated `postgres_create_tables.sql` to use fewer partitions. It should run faster now - though not fast, still probably overnight. If you can please try again.

**Comment by EmmaRocheteau** [comment]
Thank you for your help. I really appreciate this. I have started again from scratch

**Comment by alistairewj** [comment]
Great, let us know how you fare and how long the build takes. If it's longer than 24 hours we may have to go back to the drawing board. I'm testing it on my laptop now as well.

**Comment by alistairewj** [comment]
Data finished copying in <6 hours for me - now just building indices. Pretty good sign that this fix will work.

**Comment by EmmaRocheteau** [comment]
Build took around 8 hours. Seems to have worked! Although I forgot to set the mimiciii schema..

Thanks for your help

**Comment by alistairewj** [comment]
Great! You can always rename the schema if you like: https://www.postgresql.org/docs/8.3/static/sql-alterschema.html

**Comment by alistairewj** [comment]
Just to wrap up: a complete build using PostgreSQL 10.1 on a mid 2012 MacBook pro (8gb RAM, and a mechanical hard drive) took around 3 hours - while the same build on postgres 9.6 took almost 9 hours - so if you want to build it even faster, switch to v10+! :)
