### ISSUE TITLE
Drugs route in inputevents_cv

### ISSUE THREAD

**Issue by aparrot89** [MIT-LCP/mimic-code#364]
Most of the time, the ORIGINALAMOUNT column is not the effective amount.
There is not any ROUTE column. Is the ORIGINALROUTE column the good and effective  route of medication?
Thanks

**Comment by alistairewj** [comment]
I am not sure what you mean by "ORIGINALAMOUNT is not the effective amount."

The original route could be used as the route - I think that would be reasonable in most cases. Just note that the distinction between IV, IV drip, IV push, etc, is probably not consistent.
