### ISSUE TITLE
Vitalsign data points

### ISSUE THREAD

**Issue by steph409** [MIT-LCP/mimic-code#366]
Hey, 

often the vital signs are stored once an hour, sometimes every minute. 
Is there a rule when this data was saved? And is it possible somehow to extract more of this data?
I am particularly looking for the mean arterial pressure and the heartrate, using chartevents extracting the following itemids: 
systolic: 220050,220179, 225309
diastolic: 220180,220051
map: 220052, 220181
heartrate: 220045

Is it possible to use the waveforms for this?

Thanks in advance :)

**Comment by alistairewj** [comment]
All measurements in the database are nurse validated; that is, a nurse as taken the time to check the observation and in the front end click a button that says "validate". The usual view of the data is every hour, and so usually they only validate measurements every hour. Sometimes they choose to validate more frequently, or less frequently. There's no fixed rule but as you found, most validate data hourly.

For high resolution data, you can link the clinical data to the waveform data. See here: https://physionet.org/physiobank/database/mimic3wdb/matched/

It's worth noting that the waveform data contains both high resolution waveforms (75-125 Hz) and "numerics"; which are minute-by-minute vital signs extracted from the monitor and may be easier to use out of the box for your purpose.

**Comment by steph409** [comment]
hey :) 
I just started to extract the numerics, thats perfect for my use! thank you so much :)
