### ISSUE TITLE
vanco administration before prescription is entered

### ISSUE THREAD

**Issue by lmockus** [MIT-LCP/mimic-code#368]
Just a comment - not really an issue.

There are instances when vanco is administered before actual prescription is entered. For example patients 6279,7533,21093. There are about 40 of such patients. Any idea how it occurred? In above cases vanco is administered late at night and prescription is entered next day or day after. Perhaps some rush?

L

**Comment by lmockus** [comment]
It is possible that they are related to the fact that vanco administrations are reflected by inputevents_mv only when patient is in icu.

L

**Comment by alistairewj** [comment]
It's possible to give medication to a patient before it's prescribed in emergency situations - very possible that happened here especially since you say all administrations are late at night.
