### ISSUE TITLE
correct itemid for PEEP?

### ISSUE THREAD

**Issue by peiyaoli** [MIT-LCP/mimic-code#369]
Hi, I want to find the correct itemid for PEEP.
In the labevents, there is one.
But in the chartevents. there are a alots.:
1243	1096	Auto-PEEP level		carevue	chartevents				
465	505	PEEP		carevue	chartevents				
466	506	PEEP Set		carevue	chartevents				
66	60	Auto-PEEP Level		carevue	chartevents				
403	437	Low Peep		carevue	chartevents				
1122	3555	PEEP Alarm		carevue	chartevents				
2369	8053	SIGH PEEP LEVEL		carevue	chartevents				
1319	1227	autopeep		carevue	chartevents				
636	686	Total PEEP Level		carevue	chartevents				
2056	5964	Autopeep		carevue	chartevents				
4069	8345	Sigh peep level		carevue	chartevents				
4072	8357	Sigh Peep		carevue	chartevents				
4159	6349	AUTOPeeP		carevue	chartevents				
4160	6350	total PeeP		carevue	chartevents				
4465	6985	Sigh PEEP level		carevue	chartevents				
4688	7534	Intrinsic peep		carevue	chartevents				
4798	7802	high peep		carevue	chartevents				
4799	7803	low peep		carevue	chartevents				
4232	6489	auto-peep		carevue	chartevents				
4273	6601	Auto PeeP		carevue	chartevents				
4406	6859	Insp press mius PEEP		carevue	chartevents				
4418	6889	PEEP Sigh level		carevue	chartevents				
4432	6924	MEASURED PEEP		carevue	chartevents				
4446	6943	LOW PEEP		carevue	chartevents				
13252	224699	ZAuto Peep Level	ZAuto Peep Level	metavision	chartevents	Respiratory	cmH2O	Numeric	
13253	224700	Total PEEP Level	Total PEEP Level	metavision	chartevents	Respiratory	cmH2O	Numeric	
12750	220339	PEEP set	PEEP set	metavision	chartevents	Respiratory	cmH2O	Numeric	

Which ones should I use?
Thanks!

**Comment by alistairewj** [comment]
For the most part you can use the two ITEMIDs with the highest row counts (for MetaVision/CareVue), but you could also include more depending on what type of ventilation you want to study (e.g. auto PEEP, sigh peep, etc).

**Comment by peiyaoli** [comment]
good idea
