### ISSUE TITLE
Choosing a favoured database system for the public version of MIMIC

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#37]
Trying to support multiple flavours of database system creates a fair amount of extra work, mostly unnecessarily. Up until now we have favoured PostgreSQL as our public database system. Switching to MySQL may be worth considering, mainly because it would move us in line with @pszolovits's group.

Some things to consider:
- how much does the syntax differ from PostgreSQL? e.g. `with` clauses are not supported?
- which syntax is most similar to Oracle: PostgreSQL or MySQL? Relevant while we continue to use Oracle internally.
- are there any important features that would justify choosing one system over another?
- which system is preferred by the research community?

**Comment by pszolovits** [comment]
I suspect that generally Postgres is preferred, so my group may be out of the majority.  I’m not sure I would switch just because of us.  —Pete

**Comment by Franck-Dernoncourt** [comment]
I was reading some SQL tricks a while ago, and I remember this footnote:

> It is 100% standard compliant. I.e it only works with Postgres.

**Comment by jeblundell** [comment]
I'll just drop this here: https://www.wikivs.com/wiki/MySQL_vs_PostgreSQL

**Comment by alistairewj** [comment]
Considering 90%+ of the code in this repository is written for Postgres I'd say we know the answer to this question.
