### ISSUE TITLE
How much disk space will be used if I run mimic-code/concepts/make-concepts.sql?

### ISSUE THREAD

**Issue by EmmaRocheteau** [MIT-LCP/mimic-code#370]
I have 15GB left on my /local/scratch directory and I'd like to how much space will be used if I run this script. I'm most interested in looking at the ventilator data and a few respiratory parameters, so there's a good chance that I wouldn't need all these views

**Comment by alistairewj** [comment]
I ran this the other day, and it didn't even take up 1 GB. I am sure reasonably small but don't know the exact number.

**Comment by EmmaRocheteau** [comment]
Thank you! That's helpful :-)
