### ISSUE TITLE
vanco administration

### ISSUE THREAD

**Issue by lmockus** [MIT-LCP/mimic-code#372]
Hi,

Is vanco administration performed as bolus? Info on internet is pretty consistent:
"The concentration of vancomycin in Solution for infusion should not exceed 5 mg/ml. The desired dose should be administered slowly by intravenous use at a rate of no more than 10 mg/minute, for at least 60 minutes or even longer". Is it possible that inputevents_mv provides just the starting time and actual rate=10mg/min?

L

**Comment by alistairewj** [comment]
For bolus doses you shouldn't actually use the 1 minute duration (endtime - start time) as ground truth. For a short duration infusion like the one you mention you may be right in that it only documents start time.

**Comment by lmockus** [comment]
Since inputevents_mv for vanco is ENDTIME = STARTTIME + 1 minute and there is a note that "A bolus will be listed as ending one minute after it started, i.e. ENDTIME = STARTTIME + 1 minute" I have understood that vanco is administered as bolus. But since all guidelines on internet are contradicting vanco administration as bolus would you please explain how to get actual rates.

L

**Comment by lmockus** [comment]
Is it possible to find out if vanco is administered as bolus since note for inputevents_mv states "A bolus will be listed as ending one minute after it started, i.e. ENDTIME = STARTTIME + 1 minute" while all guidelines on internet suggest administering it otherwise. If it is indeed not bolus is it possible to find out what is the duration of IV?

L

**Comment by alistairewj** [comment]
I checked with nursing staff and indeed it is never given as a bolus as that is contraindicated. The ENDTIME = STARTTIME + 1 is a rule of thumb for boluses and does not imply that the duration is exactly one minute. I'm not sure how you could determine the duration - perhaps cross-referencing with the prescribed does in some way?

**Comment by lmockus** [comment]
I understand that each hospital has drug administration guidelines such as
in "NHS Grampian Staff Guidance for the Administration of
Intravenous Vancomycin in Adults via Intermittent (pulsed) Infusion"
appendix 1. It specifies the duration/rate of administration. It is not
necessary to be absolutely precise but I wonder if such are available.

L

**Comment by alistairewj** [comment]
I can ask!

**Comment by lmockus** [comment]
Vanco is usually dissolved in some solution such as dextrose 5%. In inputevents_mv next to vanco administration there entries for this solution. Unfortunately those entries specify rate=0 and endtime-starttime=1min. Evidently there is some protocol which nurses follow. Maybe it means that solution is administered at max rate possible? Knowing the max rate and amount it is easy to figure out the duration. Usually there is knob on IV pump to adjust the rate. Or maybe there is some internal guideline such as:
![image](https://user-images.githubusercontent.com/33552166/35392118-cf57e1a8-01ae-11e8-9257-63f015030136.png)

Many thanks for your help,
L

**Comment by lmockus** [comment]
Just curious if you had a chance to talk with nursing staff or have some
other suggestions. I doesn't have to be absolutely accurate but at least
knowing that so IV duration should be 1h for 1000mg dose and 1.5h for
2000mg dose would help.

I an curious why they recorded ENDTIME at all since it is confusing.

On related matter, the team might be increasing. Do all of them have to
take training? In reality they will never have access to SQL database. I
will extract  the data for vanco ICU stays only (since we already found
that data outside ICU stays is not complete - we have labs but
administration time/dose outside ICU is not recorded) and provide them with
some summary in the NONMEM format - see the example below. All subjects ids
are deidentified as well as event times (PMA stands for postmenstrual age).

TIME SUBJ EVID AMT RATE DV WT SCR SEX PMA
1 658661.6 1 2 0 0 0 77 2.3 1 3956.605
2 658669.4 1 2 0 0 0 77 2.5 1 3956.651
3 658680.9 1 2 0 0 0 77 2.5 1 3956.72
4 658689 1 1 1000 0 0 77 2.5 1 3956.768
5 658706.5 1 2 0 0 0 77 2.5 1 3956.872
6 658730.1 1 2 0 0 0 77 2.6 1 3957.012
7 658741.3 1 2 0 0 0 77 2.8 1 3957.079
8 658749.2 1 1 1000 0 0 77 2.8 1 3957.126
9 658750 1 2 0 0 0 77 3 1 3957.131
10 658754 1 2 0 0 0 77 3 1 3957.155
11 658779.2 1 2 0 0 0 77 2.8 1 3957.305
12 658783.8 1 1 1000 0 0 77 2.8 1 3957.332
13 658802 1 2 0 0 0 77 2.5 1 3957.44
14 658827.2 1 2 0 0 0 77 2.4 1 3957.59
15 658832.8 1 1 1000 0 0 77 2.4 1 3957.624
16 658838.5 1 2 0 0 0 77 2.3 1 3957.658
17 658850.2 1 2 0 0 0 77 2.2 1 3957.728
18 658857 1 0 0 0 26 77 2.2 1 3957.768
19 658875.7 1 2 0 0 0 77 2.2 1 3957.879
20 658878 1 0 0 0 23.8 77 2.2 1 3957.893
21 658887.5 1 2 0 0 0 77 2.1 1 3957.949
22 658897.8 1 2 0 0 0 77 2.1 1 3958.011
23 658923.3 1 2 0 0 0 77 1.9 1 3958.162
24 658927.5 1 0 0 0 17.6 77 1.9 1 3958.187
25 658930.3 1 1 750 0 0 77 1.9 1 3958.204
26 658933.2 1 2 0 0 0 77 1.8 1 3958.222
27 658946.8 1 2 0 0 0 77 1.8 1 3958.303
28 658971.5 1 2 0 0 0 77 1.8 1 3958.449
29 658984 1 2 0 0 0 77 1.7 1 3958.524
30 658995.9 1 2 0 0 0 77 1.8 1 3958.595
31 659019 1 2 0 0 0 77 1.9 1 3958.732
32 659042.1 1 2 0 0 0 77 1.9 1 3958.87
33 659060.5 1 2 0 0 0 77 2 1 3958.979
34 659067.6 1 2 0 0 0 77 2 1 3959.021
35 659091.1 1 2 0 0 0 77 2.1 1 3959.161
36 659113 1 2 0 0 0 77 2.1 1 3959.292
37 659138.7 1 2 0 0 0 77 2.1 1 3959.445
L

**Comment by alistairewj** [comment]
I did have some success, thanks to a colleague. Below are the dosing guidelines.

![image](https://user-images.githubusercontent.com/1282676/36555586-cedd7eba-1845-11e8-982c-1dca2644475a.png)

As we discussed, for "bolus" doses, the concept of an endtime is not meaningful, and is really just to satisfy a NOT NULL constraint on the column in the database.

If your colleagues are also interested in accessing in MIMIC data, then they will also have to complete the training and acquire access.

**Comment by lmockus** [comment]
Thanks a bunch.

**Comment by lmockus** [comment]
I am sorry, the above were dosing guidelines. I am very interested in guidelines for the duration of IV. Most probably the duration is dependent upon dose but every institution may use different guidelines for IV duration.

**Comment by alistairewj** [comment]
I heard back, here are the guidelines:

Administration depends on the dose of vancomycin:
* Doses up to 1000 mg ...............at least 60 minutes
* Doses of 1250 and 1500 mg .......at least 90 minutes
* Doses of 1750 and 2000 mg.......at least 120 minutes

**Comment by lmockus** [comment]
Thanks a bunch.
