### ISSUE TITLE
How to understand charttime / storetime in outputevents

### ISSUE THREAD

**Issue by patfol** [MIT-LCP/mimic-code#373]
Hi, 
sorry but I haven't found the answer to this question.

If a patient has an output urine volume of 200mL, with a charttime at 10h, and a storetime at 12h.
Does it mean he outputs 200mL between 10h and 12h?
Does it mean he outputs 200mL at 10h but we don't know  how long it lasted?

Thanks

**Comment by tompollard** [comment]
@patfol you can find the answer to this in the documentation:
https://mimic.physionet.org/mimictables/outputevents/

> "CHARTTIME is the time of an output event."
> "STORETIME records the time at which an observation was manually input or manually validated by a member of the clinical staff."

So in your example, a measurement of 200mL was made at 10. The value was inputted or validated at 12.
