### ISSUE TITLE
Diagnosis Time

### ISSUE THREAD

**Issue by cyustcer** [MIT-LCP/mimic-code#374]
Hi,

We are trying to extract the diagnosis time of each patient. Currently we are using the D_ICD_DIAGNOSIS table to get the admission time of the patients and trace back the admission time of the patients. Is this the right way to get the diagnosis time? Or is there other time in the table could be a better reference of the diagnosis time? 

Thanks

**Comment by alistairewj** [comment]
No, these diagnoses are not available on admission. These diagnoses are only available on discharge. If you want to assign a time to them, assign their discharge time from the hospital stay (`dischtime` from admissions table).

**Comment by tompollard** [comment]
> Currently we are using the D_ICD_DIAGNOSIS table to get the admission time of the patients and trace back the admission time of the patients.

As noted in the documentation (https://mimic.physionet.org/mimictables/diagnoses_icd), diagnosis codes are inputted at the end of the hospital admission for billing purposes. It is not correct to assume that time of diagnosis is equal to time of admission time.

**Comment by adibzaman** [comment]
Is there any way to better approximate the diagnoses time, instead of using
the discharge time? e.g., using chartevents for certain clinical conditions?

Best,
Adib

**Comment by alistairewj** [comment]
No not really - it's done by coders after a patient's hospital admission is over.
