### ISSUE TITLE
storetime / charttime in chartevents

### ISSUE THREAD

**Issue by aparrot89** [MIT-LCP/mimic-code#375]
Hi,
For the laboratory exams in chartevents.
I want to have the timestamp of the values when it's possible to see it (i don't want to know the timestamp of prelevement)
So I can't use charttime! Am I right?
Should I use storetime?
The documentation is : STORETIME records the time at which an observation was **manually** input or **manually** validated by a member of the clinical staff

**Comment by alistairewj** [comment]
I'll explain the general case then focus on labs.

Store time can be treated as an upper limit on when the data was visible. For example, vital signs such as heart rate are continuously integrated into the medical record, and are available at the chart time. While a nurse may only validate these observations a few hours later (and thus the store time is a few hours later), almost certainly it was available at the chart time.

For labs specifically, these are fed into the ICU system from the lab database continually. The chart time is the time the blood was drawn, and so often it is a few hours before the data is really available. These observations are automatically validated in the ICU system, so it may be that the store time is when the data is available in the ICU. I've never actually checked!

**Comment by aparrot89** [comment]
Thanks a lot
For **labs in chartevents**
- Even if its written ... '**manually input or manually validated**'... in the charteevents documentation?
It's a issue for real time predictive models...
When you will have some extra time is it possible to check for some measurements?
Sorry to bother you
Thanks

**Comment by alistairewj** [comment]
```sql
with t1 as 
(
select round(round(extract(epoch from storetime-charttime)::NUMERIC/60/60*4,0)/4,2) as tm from chartevents
where itemid in (825, 227466)
)
select tm, count(*)
from t1
group by tm
order by tm;
```

Gives the guessed "in the lab time" (`storetime` - `charttime`) in hours for PTT, which on average seems to be ~1-2 hours.

```sql
with t1 as 
(
select round(round(extract(epoch from storetime-charttime)::NUMERIC/60/60*4,0)/4,2) as tm from chartevents
where itemid in (220624)
)
select tm, count(*)
from t1
group by tm
order by tm;
```

Gives the guessed lab time in hours for LDL, which seems to be around 8-12 hours.

This data implies that `storetime` is when the lab data was available.

I dug into some of the raw data - this is from the HL7 message which is used by the ICU to record the lab data. First, the observation in MIMIC:

```sql
select * from chartevents where itemid = 227466 and row_id = 19430203 limit 1;
```

* `charttime`: 2126-08-11 00:02:00 - corresponds to observation_timestamp
* specimen received time: 2126-08-11 00:14:00 - not in MIMIC-III v1.4, but seems to be the time the lab received the specimen
* `storetime`: 2126-08-11 00:57:00
* timestamp of HL7 message: 2126-08-11 00:57:39

Pretty happy to conclude that `storetime` is the time the lab was available.
