### ISSUE TITLE
repeat data in diagnoses_icd

### ISSUE THREAD

**Issue by GalaChen** [MIT-LCP/mimic-code#376]
when I select data in table 'diagnoses_icd', I get some repeat data in my results. even I use code distinct, it didn't work. 

```
with intra_hemorrhage_patients as
(
  select d.subject_id as d_subject_id, d.icd9_code, d.seq_num,
         p.subject_id as p_subject_id, p.gender,p.dob,p.dod,p.dod_hosp,p.dod_ssn,p.expire_flag
  from diagnoses_icd d
  inner join patients p
  on d.subject_id = p.subject_id
  where d.icd9_code = '431' 
)

, d_p_a as 
(
select i.d_subject_id, i.seq_num, i.gender,i.dob,i.dod,i.dod_hosp,i.dod_ssn,i.expire_flag, i.icd9_code,
       a.subject_id, a.hadm_id, a.admittime, a.dischtime, a.deathtime, a.admission_type, a.diagnosis, a.has_chartevents_data
from intra_hemorrhage_patients i
inner join admissions a
on i.d_subject_id = a.subject_id
order by d_subject_id
)
-- select * from d_p_a

select dpa.* from d_p_a dpa
where dpa.admittime = (select min(admittime) from d_p_a where d_subject_id = dpa.d_subject_id) order by dpa.d_subject_id
;
```

The repeat data are completely same. They have two kinds of repeat data:
one like this\

seq_num | gender | dob                     | dod                   | expire_flag | icd9_code | subject_id | hadm_id
             2 |          F | 2084/4/14 00:00 | 2144/9/1 00:00 |                1 |            431 |           103 | 130744
             1 |          F | 2084/4/14 00:00 | 2144/9/1 00:00 |                 1 |           431 |           103 | 130744

Except seq_num, all rest part are same data. However, it indicated that it is admit hospital in the same time.
 
Another one like this:

seq_num | gender |                       dob |                   dod | expire_flag | icd9_code | subject_id | hadm_id
             1 |         M | 2131/11/10 00:00 | 2193/4/9 00:00 |                1 |            431 |        5820 | 138521
             1 |         M | 2131/11/10 00:00 | 2193/4/9 00:00 |                1 |            431 |        5820 | 138521

all of the data are same.

So, I want to know, why do I get these repeat data? How can I exclude them?

**Comment by tompollard** [comment]
Please post a query demonstrating this issue and someone will look into it.

Sent from my iPhone

On 16 Jan 2018, at 19:58, GalaChen <notifications@github.com<mailto:notifications@github.com>> wrote:


when I select data in table 'diagnoses_icd', I get some repeat data in my results. even I use code distinct, it didn't work. The repeat data are completely same.
So, I want to know, why do I get these repeat data? How can I exclude them?
