### ISSUE TITLE
Repeat data in my result 

### ISSUE THREAD

**Issue by GalaChen** [MIT-LCP/mimic-code#377]
```sql
with ICH_diagnose as
(
select subject_id, hadm_id, seq_num, icd9_code from diagnoses_icd
where icd9_code = '431'
)
-- find definitly patients

, ICH_diagnose_admission as
(
select i.subject_id as d_subject_id,i.seq_num,
       a.subject_id as a_subject_id, a.hadm_id, a.admittime, a.dischtime, a.deathtime, a.admission_type, a.diagnosis, a.has_chartevents_data
from ICH_diagnose i
left join admissions a
on i.subject_id = a.subject_id 
order by i.subject_id
)
-- cross data between table 'diagnoses_icd' and 'admissions'


, ICH_first_admission as
(
select dpa.* from ICH_diagnose_admission dpa
where dpa.admittime = (select min(admittime) from ICH_diagnose_admission where d_subject_id = dpa.d_subject_id) order by dpa.d_subject_id
)
-- find the definitly patients who are first admitted in hospital 

, ICH_diagnoses_admission_seq as
(
select ida.d_subject_id, ida.hadm_id, ida.hadm_id, ida.admittime, ida.dischtime, ida.deathtime, ida.admission_type, ida.diagnosis, ida.has_chartevents_data,
       d.hadm_id, d.seq_num
from ICH_first_admission ida
inner join ICH_diagnose d
on ida.hadm_id = d.hadm_id
order by ida.d_subject_id
)

-- exclude the patients whose icd9_code  is not contain 431 

select * from ICH_diagnoses_admission_seq
```

I want to find definitly patients who are first admitted in hospital. However, my result showed same data like this:

d_subject_id | hadm_id | hadm_id | admittime | dischtime | hadm_id | seq_num
103 | 130744 | 130744 | 2144/8/12 17:37 | 2144/8/20 11:15 | 130744 | 2
103 | 130744 | 130744 | 2144/8/12 17:37 | 2144/8/20 11:15 | 130744 | 2

so, why do I get the same data?

Thank you very much!

**Comment by alistairewj** [comment]
```sql
from ICH_diagnose i
left join admissions a
on i.subject_id = a.subject_id 
order by i.subject_id
```

You are joining icd9_diagnoses (multiple rows per `subject_id`) to admissions (multiple rows per `subject_id`) on `subject_id`. This duplicates rows.

**Comment by GalaChen** [comment]
So, How can I get the distinct results?

**Comment by alistairewj** [comment]
Most of the time when you want to do a join, you'll want the join condition to be unique/distinct for one table. SQL takes some getting used to, perhaps this post will help give you an idea on your problem: http://blog.grio.com/2013/02/an-intro-to-resolving-duplicate-results-in-sql-queries.html

**Comment by GalaChen** [comment]
@alistairewj 
Thank you for your help. 
I read my code again, I found that in table of ICH_diagnose_admission, subject_id = 103 and subject_id = 5820 has the similar data structure, that means both of them have different hadm_id in same subject_id. But, the final results get only one o row data in subject_id =103, but the same data in subject_id = 5820. Even I read the page you give me I can't understand this problem. 
Could you explain it? Thanks again!

**Comment by GalaChen** [comment]
may be I have found the answer, thank you very much for your recommdation @alistairewj
