### ISSUE TITLE
time of data in CHARTEVENTs

### ISSUE THREAD

**Issue by GalaChen** [MIT-LCP/mimic-code#379]
When I extract heart rate in CHARTEVENTS, I get the data like this:

subject_id | hadm_id | admittime | dischtime | storetime | charttime | valuenum
-- | -- | -- | -- | -- | -- | --
9 | 150750 | '2149-11-09 13:06:00' | '2149-11-14 10:15:00' | '2149-11-14 10:56:00' | '2149-11-14 10:00:00' | '86'
9 | 150750 | '2149-11-09 13:06:00' | '2149-11-14 10:15:00' | '2149-11-14 11:14:00' | '2149-11-14 11:00:00' | '84'
9 | 150750 | '2149-11-09 13:06:00' | '2149-11-14 10:15:00' | '2149-11-14 12:01:00' | '2149-11-14 12:00:00' | '86'
9 | 150750 | '2149-11-09 13:06:00' | '2149-11-14 10:15:00' | '2149-11-14 14:07:00' | '2149-11-14 13:00:00' | '82'
9 | 150750 | '2149-11-09 13:06:00' | '2149-11-14 10:15:00' | '2149-11-14 14:07:00' | '2149-11-14 14:00:00' | '82'

Even the ADMISSIONS table has indicate that patient has discharged or death, but the patient still recorded about heart rate. 
Why I get data like above?

PS:
My code
`with first_admission as
(
select adm.* from admissions adm
where adm.admittime = (select min(admittime) from admissions where subject_id = adm.subject_id) order by adm.subject_id
)

,ICH_diagnoses_admission as
(
select d.subject_id, d.seq_num,
       fa.hadm_id, admittime, dischtime, deathtime,religion
from diagnoses_icd d
inner join first_admission fa
on d.subject_id = fa.subject_id and d.hadm_id = fa.hadm_id
where d.icd9_code = '431' and seq_num = 1
order by d.subject_id
)

, ICH_HR_AVG as
(
select da.subject_id, da.hadm_id,da.admittime, da.dischtime,da.deathtime,
       c.storetime, c.charttime,c.value, c.valuenum, c.valueuom, c.resultstatus
from ICH_diagnoses_admission da
inner join chartevents c
on da.subject_id = c.subject_id and da.hadm_id = c.hadm_id
where itemid = 211 or itemid = 220045

order by da.subject_id, c.storetime
)

select * from ICH_HR_AVG`

**Comment by alistairewj** [comment]
The patient was, unfortunately, brain dead, and often patients are kept stable until discussion with family can occur in regards to preferences for organ donation. Often in confusing situations like these it is best to search the patient's notes for more information, which is what I did to determine my conclusion.

**Comment by GalaChen** [comment]
Thank you very much
