### ISSUE TITLE
ERROR loading the postgres_load_data_pg10.sql

### ISSUE THREAD

**Issue by OluOrojo** [MIT-LCP/mimic-code#380]
I got an error loading postgres_load_data_pg10.sql. 

I got COPY 58976
COPY 34499
COPY 7567
COPY 1048575
COPY 573146
COPY 1048575
COPY 651047
COPY 125557
COPY 134

then

ERROR: duplicate key value violates unique constraint "d_icd_diag_code_unique"
DETAIL: Key (icd9_code) = (844) already exists.
CONTEXT: COPY d_icd_diagnoses,line 307

[ERROR loading postgres_load_data_pg10.sql.docx](https://github.com/MIT-LCP/mimic-code/files/1663727/ERROR.loading.postgres_load_data_pg10.sql.docx)
![image](https://user-images.githubusercontent.com/34347070/35385909-ee33665c-01c1-11e8-8ae5-bc8ebbb85714.png)

How can I fix it please?

**Comment by alistairewj** [comment]
This error indicates you are violating a unique constraint, that is the database expects the column to always have unique values, but you're attempting to insert a duplicate.

The most likely explanation is you have tried to copy the same data twice. I would double check that - you could run the checks SQL script provided in the same folder to verify the row counts.

**Comment by OluOrojo** [comment]
Hi alistairewj,

I am unable to run the checks SQL script as the database didn't load fully.

I used the SQL scripts online so it's strange that it has the errors.

**Comment by alistairewj** [comment]
You can still run the checks script, just ignore everything except d_icd_diagnoses. The main thing you're trying to find out is if you already have data in the table.

**Comment by tompollard** [comment]
@OluOrojo the simplest approach would be to drop the schema and start again from fresh.

**Comment by OluOrojo** [comment]
I ran the check script and 3 tables failed
![screen shot 2018-01-31 at 10 04 08](https://user-images.githubusercontent.com/34347070/35616839-5564e796-066e-11e8-9888-7dee564e3fdf.png)

**Comment by OluOrojo** [comment]
@tompollard I did start again yet 3 tables failed it appears the issue is from the create table code.
![screen shot 2018-01-31 at 10 04 08](https://user-images.githubusercontent.com/34347070/35616882-7f111934-066e-11e8-96db-64360496d475.png)

**Comment by alistairewj** [comment]
I note that both chartevents, datetimeevents, and inputevents_mv which have failed have the same row count (1048575). There is likely something wrong with your local configuration preventing loading all the rows. Perhaps you should try verifying the integrity of your data files using the md5 sums provided on PhysioNet?

**Comment by OluOrojo** [comment]
@alistairewj Could you kindly paste the link to find the md5 sums provided on Physionet? I am unsure what section to look in.

**Comment by alistairewj** [comment]
https://physionet.org/works/MIMICIIIClinicalDatabase/files/

Scroll down and look for the checksum md5 files.

**Comment by OluOrojo** [comment]
@alistairewj I have found the files, ran it but no outcome. The same tables failed. 
![image](https://user-images.githubusercontent.com/34347070/35644343-9bed258c-06c0-11e8-843e-68965cd25b6f.png)

**Comment by alistairewj** [comment]
md5sum is not an SQL shell command - you need to run it from something like command prompt or Windows Powershell. I would search the internet for how to check the md5sum of a file on Windows.

**Comment by OluOrojo** [comment]
@alistairewj  ALright thanks a lot. I would check online.

**Comment by OluOrojo** [comment]
@alistairewj md5sum of my files seem to be different from what is online. I'd re-download the files, any ideas why this might have occurred?

**Comment by tompollard** [comment]
@OluOrojo There are many possible reasons (e.g. perhaps files were corrupted during download; you had an old copy of the files, etc). Glad you found the issue.
