### ISSUE TITLE
MIMIC in the classroom

### ISSUE THREAD

**Issue by beamandrew** [MIT-LCP/mimic-code#381]
This may be the wrong place to ask, but if we would like to use MIMIC for the purposes of a class, will each student need to complete the CITI training and apply individually or is there a more centralized way we can get them access to the data?

**Comment by tompollard** [comment]
Thanks @beamandrew. We are regularly asked the question by email, so I think it is good to have a record here. The answer is that all users of MIMIC need to complete the formal process described at: https://mimic.physionet.org/gettingstarted/access/, which includes CITI training.

In the Data Use Agreement, users state that they "will not share access to PhysioNet restricted data with anyone else”. The statement applies regardless of whether the user is an instructor or student. 

To facilitate the approval process, it can be helpful if the instructor sends a list of names and email addresses of the students to the laboratory in advance of the data access requests.

Note also that there is a demo version of MIMIC that is more straightforward to access and is often useful in a classroom setting. For more detail, see: https://mimic.physionet.org/gettingstarted/demo/

**Comment by beamandrew** [comment]
Thanks @tompollard! Very helpful. It's actually good practice for the students to get acquainted with CITI training because it reflects real-world practice.

I'll get a list of addresses together and send them to you before the course begins.
