### ISSUE TITLE
About antibiotics infomations in table inputevents_cv 

### ISSUE THREAD

**Issue by ewanlee** [MIT-LCP/mimic-code#382]
Hi MIMIC Team,

Thank you for providing such a useful data set and I've been using it in recent months. I am currently studying the use of antibiotics for severe pneumonia. 

The following list is my concern of some antibiotics.

- Cefepime 
- Levofloxacin 
- Moxifloxacin 
- Ciprofloxacin 
- Ceftazidime 
- Vancomycin 
- Ampicillin/Sulbactam
- Meropenem 
- Ceftriaxone

I have found all of them in table inputevents_mv but they were hardly found in table inputevents_cv. So are these antibiotics have some alias or recorded in other tables?

**Comment by alistairewj** [comment]
Antibiotics aren't really recorded for carevue (inputevents_cv). You can use the prescriptions table to get prescribed antibiotics.

**Comment by ewanlee** [comment]
@alistairewj Thanks ! Very helpful !
