### ISSUE TITLE
Error in sum of GCS score

### ISSUE THREAD

**Issue by GalaChen** [MIT-LCP/mimic-code#385]
`with first_admission as
(
select adm.* from admissions adm
where adm.admittime = (select min(admittime) from admissions where subject_id = adm.subject_id) order by adm.subject_id
)

,ICH_diagnoses_admission as
(
select d.subject_id, d.seq_num,
       fa.hadm_id, admittime, dischtime, deathtime,religion
from diagnoses_icd d
inner join first_admission fa
on d.subject_id = fa.subject_id and d.hadm_id = fa.hadm_id
where d.icd9_code = '431' and seq_num = 1
order by d.subject_id
)

,ICH_GCS as
(
select da.subject_id, da.hadm_id,da.admittime,da.dischtime,da.deathtime,
       c.itemid, c.charttime, c.value,c.valuenum,  c.valueuom,
       width_bucket(valuenum, 1, 30, 30) AS bucket
from ICH_diagnoses_admission da
inner join chartevents c
on da.subject_id = c.subject_id and da.hadm_id = c.hadm_id
where c.itemid in (184,723,454,223901,223900,220739)
order by da.subject_id
)

select subject_id, hadm_id, admittime, dischtime, deathtime, itemid, charttime, value, valuenum, sum(bucket) over (partition by charttime) as GCS_Score_Total
from ICH_GCS ig
where charttime < deathtime or charttime < dischtime
order by subject_id,charttime`

I use these codes to calculate the total score of GCS. However, some results aren't right, such as:

subject_id | hadm_id | admittime | dischtime | deathtime | itemid | charttime | value | valuenum | GCS_Score_Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
9 | 150750 | 2149/11/9 13:06 | 2149/11/14 10:15 | 2149/11/14 10:15 | 723 | 2149/11/9 17:00 | 1.0 ET/Trach | 1 | 17
9 | 150750 | 2149/11/9 13:06 | 2149/11/14 10:15 | 2149/11/14 10:15 | 454 | 2149/11/9 17:00 | 5 Localizes Pain | 5 | 17
9 | 150750 | 2149/11/9 13:06 | 2149/11/14 10:15 | 2149/11/14 10:15 | 184 | 2149/11/9 17:00 | 1 No Response | 1 | 17
9 | 150750 | 2149/11/9 13:06 | 2149/11/14 10:15 | 2149/11/14 10:15 | 723 | 2149/11/9 20:00 | 1.0 ET/Trach | 1 | 13
9 | 150750 | 2149/11/9 13:06 | 2149/11/14 10:15 | 2149/11/14 10:15 | 184 | 2149/11/9 20:00 | 1 No Response | 1 | 13
9 | 150750 | 2149/11/9 13:06 | 2149/11/14 10:15 | 2149/11/14 10:15 | 454 | 2149/11/9 20:00 | 1 No Response | 1 | 13

Why I get result like this? How can I fix this problem?

**Comment by alistairewj** [comment]
I don't know the exact reason why you are using `width_bucket` but it seems like that is the issue.

There is code for extracting GCS in the repo - either [the lowest in the first day](https://github.com/MIT-LCP/mimic-code/blob/da593343d367d630b3c59ca6123bb0027e2c5d80/concepts/firstday/gcs-first-day.sql) or [pivoted based on chart time](https://github.com/MIT-LCP/mimic-code/blob/da593343d367d630b3c59ca6123bb0027e2c5d80/concepts/pivot/pivoted-gcs.sql).

Perhaps starting with that will be easier.

**Comment by GalaChen** [comment]
OK, Thank you very much!

2018-01-30 3:30 GMT+08:00 Alistair Johnson <notifications@github.com>:
