### ISSUE TITLE
Verification of Numeric/Trend Definitions in SQL and AFL Databases

### ISSUE THREAD

**Issue by bcollar** [MIT-LCP/mimic-code#386]
Hello,

I am currently trying to rematch vital signs between patients recorded under the chartevents table of the SQL database and the numerics files of the AFL database. Looking at the MIMIC resources, the time series data (1 sample/minute) is defined as “in some cases, the samples recorded once per second or per minute are the most recent calculated values. Other numerics, such as heart rate and systolic/mean/diastolic blood pressure, are recalculated for each recorded sample; these are typically short-term averages of raw measurements that are made each cardiac cycle.”

Is there a list of which numerics fall under the first definition, and which fall under the second? Additionally, what is meant by “short-term averages?” For example, is heart rate calculated as the average of the entire previous minute of data recorded, or only a few seconds prior to the time collection?

Getting back to the overall task, I ran into some curious findings when using some patient data from the MIMIC Matched Subset. For example, searching through the SQL database for information pertaining to patient s00124, I found records within the chartevents table with dates regarding at least three different hospital stays: 07/2160, 12/2161, and 05/2165. However, when searching for that same patient under the AFL database, the only records showing up were associated with the 07/2160 hospital stay. Is there a reason for these additional numeric records not to be included with the patient in the matched subset other than them not existing?

Appreciate the help with this.

Thanks,
Brett

**Comment by alistairewj** [comment]
Which AFL database are you referring to? I'm not familiar with the acronym.

For the signals, I don't know the truth, but intuitively I would say heart rate, pulse, blood pressure, SpO2, and respiratory rate will all be rederived minute by minute. Anything else is likely to be carried forward. It's probably very obvious when you look at the signals.

In terms of how the averages are calculated, unfortunately we can't tell you, because it is done by a proprietary algorithm.

Finally, you have found that we don't have matched waveform records for all patients. This is indeed true, as the process for collecting the waveforms is completely independent of the process for collecting the clinical data, and unfortunately it is difficult to match them again. You can read more lower on the page here: https://physionet.org/physiobank/database/mimic3wdb/

> The MIMIC-III Clinical Database contains detailed clinical information about most of the subjects represented in the MIMIC-III Waveform Database. Since the contents of each database were collected independently, in partially deidentified form, matching the clinical data with the waveform data is a non-trivial task, and only a subset of MIMIC-III Waveform Database records, located in the [MIMIC-III Waveform Database Matched Subset](https://physionet.org/physiobank/database/mimic3wdb/matched/), has been matched with MIMIC-III Clinical Database records.
>
> In these cases, the matches provide additional information about the subjects, including age, gender, and detailed clinical information collected during (and in some cases before and after) the periods that have been recorded in the Waveform Database records. For more information, apply for access to the MIMIC-III Clinical Database (a data use agreement is required).
>
> Multiple recordings of a given patient, which may exist (for example) if that patient was admitted more than once to any of the study ICUs during the study period, do not have related MIMIC-III Waveform Database record names; it will be necessary to refer to the Matched Subset to discover any such cases.

**Comment by bcollar** [comment]
Thanks again for the help!

I apologize about the unfamiliar acronym, AFL is a language I am currently using on an internal iquery client to search the MIMIC numeric/waveform records.

Going back to querying the SQL database, I've found under the d_items table that ITEMID is defined as a numeric representation of a measurement in the database, where measurements of the same type have the same ITEMID. It also mentions that ITEMID is sourced from two different ICU databases, and as such there are multiple ITEMIDs that correspond to the same concept.

Is there any documentation that lists all of the different concepts and the multiple ITEMIDs corresponding to each concept? The description in the d_items table gives values for heart rate (211, 220045) but I haven't found any other values as of yet.

Again, appreciate the help with this.

Brett

**Comment by alistairewj** [comment]
Many people have created many concept mappings - it's a big task to do it in the most general case, and most people prefer to build mappings which make sense for their project (for example, some people merge non-invasive blood pressure measurements with invasive measurements, but there are projects where this would be inappropriate).

The ideal approach is to map the MIMIC concepts to a standardized ontology and let the ontology handle all the relationships, etc. #107 has some discussion on this. We've also began mapping MIMIC to a common data model ( https://github.com/MIT-LCP/mimic-omop/ ) - so some concepts have been harmonized there as well (check the https://github.com/MIT-LCP/mimic-omop/tree/master/extras/concept folder). Worth checking out.

**Comment by adibzaman** [comment]
Thanks Alistair. Just wanted to mention here that Brett is working on a project for a validation study on the numeric dataset by comparing that with the clinical data. He is using the SciDB waveform database engine that we created at Purdue.

**Comment by alistairewj** [comment]
Heart rate, SpO2, and invasive blood pressure are a good start. Those interface directly into the monitor, so the values should correlate well and there will only be two `itemid` for each.

**Comment by adibzaman** [comment]
Thanks Alistair!
