### ISSUE TITLE
Time synchronization of ECG and resp signals

### ISSUE THREAD

**Issue by marethabester** [MIT-LCP/mimic-code#387]
From the information on the MIMIC site I see that the ECG signal is not usually perfectly time synchronized with the other waveforms. I would like to know the following: 
1. Are there any records were it is known that these waveforms are in fact time synchronized?
2. Are there any records were the respiratory waveform is chest inductance in stead of chest impedance?

Thank you in advance for any help!

Maretha

**Comment by alistairewj** [comment]
The ECGs are all synchronized - past that I don't think you can make any assumptions.

For the respiratory waveform, I'm really not sure, but I think it would be rare to find chest inductance. It's fairly impractical in the ICU setting.
