### ISSUE TITLE
Why are the heights and weights missing when subject_id > 32810?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [MIT-LCP/mimic-code#39]
I use https://github.com/MIT-LCP/mimic-code/blob/master/demographics/postgres/HeightWeightQuery.sql to get heights and weights in MIMIC-III v1.1.

Why are the heights and weights missing for all patients when subject_id > 32810? 

`SELECT MAX(subject_id) FROM  mimiciii.heightweight;` returns 32810.

**Comment by alistairewj** [comment]
Just checked, looks like the code is missing the appropriate Metavision ITEMIDs. Feel free to add them and do a pull request, otherwise I'll take a look with @erinhong on Monday.

**Comment by Franck-Dernoncourt** [comment]
Thanks, sounds good, I'll wait for the fix!

**Comment by alistairewj** [comment]
Give it a go now - I think the fix I uploaded should work.

**Comment by Franck-Dernoncourt** [comment]
Thanks, it looks like the fix works:

```sql
SELECT MAX(subject_id) FROM franck.heightweight2; -- result: 9999

SELECT COUNT(DISTINCT(subject_id)) FROM franck.heightweight2 
WHERE height_first IS NULL; -- result: 19177

SELECT COUNT(DISTINCT(subject_id)) FROM franck.heightweight2
WHERE weight_first IS NULL; -- result: 17665
```

**Comment by Franck-Dernoncourt** [comment]
Sorry, actually the weights are still missing for patients who subject_id is over 32810:

```sql
SELECT MAX(subject_id) FROM mimiciii.heightweight
WHERE height_first IS NOT NULL; -- result: 99999

SELECT MAX(subject_id) FROM mimiciii.heightweight
WHERE weight_first IS NOT NULL; -- result: 32810
```

**Comment by alistairewj** [comment]
Whoops - left the ITEMID out - should work now.

**Comment by Franck-Dernoncourt** [comment]
Thanks, that fixed the issue.

**Comment by BJWiley233** [comment]
The database in Physionet is also not updated.  Do I need to reach out to physionet directly?

```sql
SELECT max(ce.subject_id)
FROM `physionet-data.mimiciii_clinical.chartevents` ce
INNER JOIN `physionet-data.mimiciii_clinical.d_items` d
  ON d.ITEMID = ce.ITEMID
INNER JOIN `physionet-data.mimiciii_clinical.icustays` icu
  ON ce.ICUSTAY_ID = icu.ICUSTAY_ID
INNER JOIN `physionet-data.mimiciii_clinical.diagnoses_icd` icd
  ON icu.subject_id = icd.subject_id
INNER JOIN `physionet-data.mimiciii_clinical.d_icd_diagnoses` icd_long
  ON icd.ICD9_CODE = icd_long.ICD9_CODE
WHERE d.ITEMID in (762, 763, 3580, 3581, 3582, 3583)
```
result is 32810

**Comment by alistairewj** [comment]
You need to include itemids for MetaVision. You can look at the code in this repository for some guidance.
