### ISSUE TITLE
Does date shifting level same for unique patient ?

### ISSUE THREAD

**Issue by bbardakk** [MIT-LCP/mimic-code#391]
I have a question about the visit time of same patient.

For example,

Patient1 have two visit and the real dates of visit are 01.01.2012 and 01.02.2012 respectively. So there are 1 month difference between two visit. After the date shifting, this 1 month difference is still valid or does it change ?

Thanks in advance

**Comment by alistairewj** [comment]
Yes, the date shifting preserves relative intervals, so the 1 month interval is retained.
