### ISSUE TITLE
how were the indices were chosen in ventilation-durations.sql?

### ISSUE THREAD

**Issue by EmmaRocheteau** [MIT-LCP/mimic-code#392]
I'm looking at ventilation-durations.sql in the concepts folder:

'''
select
  icustay_id, charttime
  -- case statement determining whether it is an instance of mech vent
  , max(
    case
      when itemid is null or value is null then 0 -- can't have null values
      when itemid = 720 and value != 'Other/Remarks' THEN 1  -- VentTypeRecorded
      when itemid = 223848 and value != 'Other' THEN 1
      when itemid = 223849 then 1 -- ventilator mode
      when itemid = 467 and value = 'Ventilator' THEN 1 -- O2 delivery device == ventilator
      when itemid in
        (
        445, 448, 449, 450, 1340, 1486, 1600, 224687 -- minute volume
        , 639, 654, 681, 682, 683, 684,224685,224684,224686 -- tidal volume
        , 218,436,535,444,459,224697,224695,224696,224746,224747 -- High/Low/Peak/Mean/Neg insp force ("RespPressure")
        , 221,1,1211,1655,2000,226873,224738,224419,224750,227187 -- Insp pressure
        , 543 -- PlateauPressure
        , 5865,5866,224707,224709,224705,224706 -- APRV pressure
        , 60,437,505,506,686,220339,224700 -- PEEP
        , 3459 -- high pressure relief
        , 501,502,503,224702 -- PCV
        , 223,667,668,669,670,671,672 -- TCPCV
        , 224701 -- PSVlevel
        )
        THEN 1
      else 0
    end

'''

I have run some sanity checks before continuing, taking the tidal volume items as an example:

mimic=> select label from d_items where itemid in (639, 654, 681, 682, 683, 684, 224685, 224684, 224686);
           label            
----------------------------
 Sigh Tidal Volume
 Spont. Tidal Volume
 Tidal Volume
 Tidal Volume (Obser)
 Tidal Volume (Set)
 Tidal Volume (Spont)
 Tidal Volume (set)
 Tidal Volume (observed)
 Tidal Volume (spontaneous)
(9 rows)

mimic=> select label from d_items where lower(label) like '%tidal volume%';
           label            
----------------------------
 MMV tidal volume
 Sigh Tidal Volume
 Spont. Tidal Volume
 Tidal Volume
 Tidal Volume (Obser)
 Tidal Volume (Set)
 Tidal Volume (Spont)
 spont Tidal volumes
 High Tidal Volume
 High Tidal volume
 HI TIDAL VOLUME
 HIGH TIDAL VOLUME
 hi tidal volume
 tidal volumes
 sp tidal volumes
 TIDAL VOLUME
 tidal volume
 SPNIOT TIDAL VOLUMES
 spont tidal volumes
 Tidal Volume (set)
 Tidal Volume (observed)
 Tidal Volume (spontaneous)
(22 rows)

I was wondering why instances such as 'TIDAL VOLUME', 'tidal volume' and 'tidal volumes' haven't been included as tidal volumes?

**Comment by alistairewj** [comment]
I tried to limit it to settings which were consistently documented and certainly indicated ventilation. Those extra settings that you see are (1) manually input by staff in the ICU information system (rather than being populated from the ventilator and validated by the staff) and so are usually infrequent (e.g. the variation in spelling), or (2) indicate an alarm setting (such as "High Tidal Volume") and the presence of an alarm doesn't necessarily indicate the patient is ventilated. I think it's unlikely that the addition of these settings would change the ultimate result of the query, but investigation never hurts!

**Comment by EmmaRocheteau** [comment]
Thanks for your reply! That's very helpful. I noticed some unexpected things in the indices for insp pressure as well:

mimic=> select label from d_items where itemid in (221,1,1211,1655,2000,226873,224738,224419,224750,227187);
           label            
----------------------------
 % Inspir. Time
 I:E Ratio
 Insp Time %
 Insp. Time
 Inspiratory Time
 Negative Insp. Force
 Inspiratory Time
 Nitric Oxide Tank Pressure
 Inspiratory Ratio
 Pinsp (Draeger only)
(10 rows)

Why is Nitric Oxide Tank Pressure in this, and what does (Draeger only) mean?

I want to collect a cohort of patients who are exclusively on mechanical ventilation/are intubated. From memory is there an easy way of doing this? Forgive me for asking questions that can be solved by exploring the database, I'm a first year PhD student and there isn't anyone here that I can ask.

**Comment by EmmaRocheteau** [comment]
Also, is there any way of obtaining height data from carevue? I could only find itemids for height in metavue:

mimic=> select label, itemid from d_items where lower(label) like '%height%';     
label     | itemid 
---------------+--------
 Height of Bed |    216
 Height Inches |   1394
 Height        | 226707
 Height (cm)   | 226730
(4 rows)

**Comment by tompollard** [comment]
@EmmaRocheteau height seems off topic for this thread. please could you move the question to a new issue?

**Comment by alistairewj** [comment]
Hmmm. Draeger is a ventilator brand and sometimes ITEMIDs are charted with the brand. It's likely the tank pressure shouldn't be there.

**Comment by EmmaRocheteau** [comment]
Okay, that's helpful to know, thank you

**Comment by chris20881** [comment]
This is a bit of a guess about one of those points, but I believe Draeger vents measure inspiratory pressure from zero, whereas many others measure inspiratory pressure above PEEP. More of a guess, but maybe the ICUs usually use a vent that measures above PEEP, and for some reason occasionally have a Draeger and wish to differentiate the different use of inspiratory pressure?

**Comment by chris20881** [comment]
Hello, minor point here, and a bit of a guess, but Draeger set inspiratory pressures in a rather different way to most (?all) other ventilator manufacturers. So possibly, the ICUs contributing to mimic mostly use other vents, but occasionally a Draeger, and wish to differentiate the different use of inspiratory pressure?

**Comment by alistairewj** [comment]
Yeah it's possible - could investigate the distributions to find out - I also have a sneaking suspicion the draegers were trialed once or twice but not used that frequently. Either way it wasn't too big of a deal for the query, since the absolute value isn't important for determining mech vent, so I didn't dig into it that much.
