### ISSUE TITLE
ablolute lymphocyte count and absolute neutrophil count

### ISSUE THREAD

**Issue by GalaChen** [MIT-LCP/mimic-code#396]
I want to extract data about ablolute lymphocyte count and absolute neutrophil count. I find the itemid in d_labitems, Although I found absolute lymphocyte count, only a little part of patients have this data in my interested group. Besides, I didn't find absolute neutrophil count in MIMICIII. 
On the other hand, I got percentage of lymphocyte and percentage of neutrophil in my interested patiems. I try to use granulocyte count and percentage of to calculate ablolute lymphocyte count and absolute neutrophil count, but it is also only a little part of patients in my interested group have  granulocyte count data. 
So, I have two question: 
1.  How can I get the ablolute lymphocyte count and absolute neutrophil count?
2.  Whether the percentage of lymphocyte and percentage of neutrophil  data get only in first 24 hours 
     when the patients admitted in ICU
Thank you very much!
1.

**Comment by GalaChen** [comment]
@alistairewj

**Comment by tompollard** [comment]
@GalaChen We see your posts but we have our own projects to work on too, so please be patient.

**Comment by GalaChen** [comment]
OK, I'm Sorry!

2018-02-09 23:57 GMT+02:00 Tom Pollard <notifications@github.com>:

**Comment by lceli** [comment]
Have you looked at this study?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4344736/
I suggest you contact the corresponding author as their group has the query for the variables you are interested in.Leo

**Comment by GalaChen** [comment]
Thank you very much! @lceli

**Comment by YesheKway** [comment]
HI @GalaChen did you manage to get the neutrophil count data from mimic III ? If yes do you mind sharing how. Thank you.
