### ISSUE TITLE
New releases of MIMIC data will be announced here

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#397]
New releases of MIMIC data will be announced here. To keep up to date on the latest releases, click the 'subscribe' button to receive notifications.

![screen shot 2018-02-08 at 11 07 11](https://user-images.githubusercontent.com/822601/35983788-dd13f74c-0cc0-11e8-897c-07b21d7d84a8.png)

Please do not use this thread to ask for updates on the status of data releases.

**Comment by alistairewj** [comment]
MIMIC-IV v0.4 has been published: https://mimic-iv.mit.edu/
