### ISSUE TITLE
ECG limitation about resolution

### ISSUE THREAD

**Issue by cyustcer** [MIT-LCP/mimic-code#399]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
It mentioned in ECG limitation on the website: https://physionet.org/physiobank/database/mimic3wdb/.
The scaling reduced the effective amplitude resolution from 12 bits to 9 or 10 bits in typical cases, and as little as 7 bits in some cases.

Can you help explain why the scaling reduced the amplitude resolution?

Thank you very much!

**Comment by alistairewj** [comment]
We can't give much more detail as the signal decimation was done using proprietary software.
