### ISSUE TITLE
Remove the MIMIC-II v3.0 repo at https://github.com/mimic2/v3.0

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#4]
We initially created a MIMIC-II v3.0 repository at: https://github.com/mimic2/v3.0 to hold documentation and web content for the latest version of MIMIC. This repository has been superseded by https://github.com/MIT-LCP/mimic-website

We should:
1. ensure all of the issues posted at: https://github.com/mimic2/v3.0/issues?utf8=%E2%9C%93&q= are archived
2. remove the content at https://github.com/mimic2/v3.0 and point people to the new website at http://mimic.physionet.org/

**Comment by tompollard** [comment]
Note from @Franck-Dernoncourt on how to archive GitHub issues:

> fyi: https://www.quora.com/How-can-I-export-backup-GitHub-issues

**Comment by tompollard** [comment]
So perhaps the simplest method for archiving content is:

``` bash
curl https://api.github.com/repos/mimic2/v3.0/issues?state=all > archive.txt
```

**Comment by tompollard** [comment]
I've made the repository private and moved it to:
https://github.com/MIT-LCP/v3.0

**Comment by Franck-Dernoncourt** [comment]
Thanks! Has the repo moved somewhere else?

**Comment by tompollard** [comment]
@Franck-Dernoncourt nope, it's just been made private to avoid confusion. I've added you as a collaborator with write access.

**Comment by Franck-Dernoncourt** [comment]
Thanks!
