### ISSUE TITLE
Unable to run dbGetQuery( ) from explore-items.Rmd

### ISSUE THREAD

**Issue by mldorr** [MIT-LCP/mimic-code#400]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
I am having trouble with the line: `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(label separator ', ') from d_items where category is not null group by category")` from mimic-code/tutorials/explore-items.Rmd. 
When running the code, I receive this error:
`Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near "separator"
LINE 1: select category, count(*) c, group_concat(label separator ',...
                                                        ^
)
Could not create execute: select category, count(*) c, group_concat(label separator ', ') from d_items where category is not null group by category` 
every time I run it. (Note: the carrot always points to the 's' in separator)  
  
Other code modifications I have tried (all with the same result):
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(label separator ', ') from mimiciii.d_items where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(label separator ', ') from mimiciii.D_ITEMS where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(label sep ', ') from mimiciii.d_items where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(sep ', ') from mimiciii.d_items where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(label sep ', ') from mimiciii.d_items where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(label sep = ', ') from mimiciii.d_items where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(label separator = ', ') from mimiciii.d_items where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(separator = ', ') from mimiciii.d_items where category is not null group by category")`
- `item.summary <- dbGetQuery(con, "select category, count(*) c, group_concat(separator = ', ') from d_items where category is not null group by category")`

I am connecting to my local MIMIC-III database and have been able to run the code from using_r_with_jupyter.ipynb, with the only modification being the addition of `mimiciii.` to `iculos <- dbGetQuery(con, "select los from mimiciii.icustays where los >= 0 and los <=20")` (hence the addition of `mimiciii.` to many of my attempts above). I also tried running `dbSendQuery(con, 'set search_path to mimiciii')` before my code,  but that also did not change results.

**Comment by tompollard** [comment]
Hi @mldorr, the [demo that you are looking at](https://github.com/MIT-LCP/mimic-code/blob/master/tutorials/explore-items.Rmd) appears to be configured to run on a MySQL database (`library(RMySQL)`). It looks like `group_concat` is not available in `postgresql`, which explains your error.

Most of the code in the repository is written for Postgres, but this notebook was written by @pszolovits who prefers MySQL. Take a look at: https://stackoverflow.com/questions/2560946/postgresql-group-concat-equivalent for an approach that works in PostgreSQL.
