### ISSUE TITLE
Error when running the create tables script (screen shot attached), please help!

### ISSUE THREAD

**Issue by ShiyaYi** [MIT-LCP/mimic-code#402]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii
I am using PostgreSQL 10 and the postgres_create_tables_pg10.sql script; however, the error kept occuring. Any advice?
![screenshot 2](https://user-images.githubusercontent.com/34217467/36317417-0b455e94-130b-11e8-841b-481012e9a0ef.png)

**Comment by alistairewj** [comment]
Looks like you have downloaded the HTML for the GitHub page that hosts the script, and not the script itself. When navigating GitHub, click the "raw" button at the top right before you download the script.
