### ISSUE TITLE
Mimic access problem

### ISSUE THREAD

**Issue by filipencosta** [MIT-LCP/mimic-code#404]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

Hi I have access to mimic, but I needed to change my physionet password account and when i did that i lost the access to mimic. What can i do?

**Comment by alistairewj** [comment]
You can reset your PhysioNetWorks password here: https://physionet.org/users/login.shtml

**Comment by filipencosta** [comment]
I reseted my password and now I do not have access to mimic.
