### ISSUE TITLE
Subject-ids related to MIMIC-III Waveform Database Matched Subset

### ISSUE THREAD

**Issue by Mehdifasihi** [MIT-LCP/mimic-code#405]
Hi
I have a full access to Mimic data base ,But I just need to subject -ids related to MIMIC-III Waveform Database Matched Subset .It is not possible for me to download all of data base just for subject -ids.
IF it is possible ,please provide for me just subject-ids related to MIMIC-III Waveform Database Matched Subset.
Thanks.

**Comment by RezaSadeghiWSU** [comment]
Hi Mehdifasihi,

If you have access to whole MIMIC-III database, then based on following information provided in the ("The MIMIC-III Waveform Database Matched Subset" webpage) you can reach ids that you want.

The name of each mimic3wdb/matched waveform record is of the form

pXX/pXXNNNN/pXXNNNN-YYYY-MM-DD-hh-mm
where XXNNNN is the matching MIMIC-III Clinical Database Subject_ID, and YYYY, MM, DD, hh, and mm are the surrogate year, month (01-12), and day (01-31), and the real hour (00-23) and minute (00-59), derived from the starting date and time of day of the mimic3wdb/matched record. The surrogate dates match those of the corresponding MIMIC-III Clinical Database records.

Best regards,
Reza Sadeghi

**Comment by waqaraziz123** [comment]
Hi Mehdifasihi,

You don't need to download the whole database for `subject_id`. You can download the `RECORDS-waveform` file only that contains all the `subject_id` matched with clinical database.

Thanks

**Comment by Mehdifasihi** [comment]
Hi Reza
Thanks for your help.It was very helpful.

**Comment by anand1729-lab** [comment]
I have a doubt regarding this question. 
Assume I need to locate the clinical database of the subject p00/p000020. As per the matched waveform database .hea file, this subject was admitted on 2183-04-28 ( YYYY-MM-DD). Now, if we look for the subject_ID = 00020 in admissions.csv (downloaded from the clinical database), admission time was 5/10/2134 at 11:30:00 AM.
I am not able to understand why there is a mismatch in information. I am def. missing some information, and if you can help me, this will be very useful.

**Comment by vinay-hebb** [comment]
> I have a doubt regarding this question.
> 
> Let's say, we need to locate the clinical database of the subject p00/p000020 in the MIMIC-III Waveform Database Matched Subset. As per the .hea file, this subject was admitted on 2183-04-28 ( YYYY-MM-DD). Now, if we look for the subject_ID = 000020 in admissions.csv, downloaded from the clinical database, admission time was 5/10/2134 at 11:30:00 AM. I am not able to understand why there is a mismatch in information. I am def. missing some information, and if you can help me, this will be very useful.

you are looking at wrong subject_id? I can see that admittime in admissions.csv matches with the file name

**Comment by GayathriJyothis** [comment]
Hello All,

How many days it will take to get approval of MIMIC III database?
