### ISSUE TITLE
Is there any heart echocardiogram data or thyroid data in MIMIC?

### ISSUE THREAD

**Issue by cyustcer** [MIT-LCP/mimic-code#406]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

Is there any heart echocardiogram data (ejection fraction, size of left atrium, etc.) or thyroid data in MIMIC database?

**Comment by tompollard** [comment]
@cyustcer Please provide more detail when asking questions and show that you have looked into the issue yourself before asking others to help. 

The `noteevents` table contains echo reports, which might contain the heart-related details you are looking for. The following script extracts structured data from the reports: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/echo-data.sql. 

What do you mean by "thyroid data"?

**Comment by cyustcer** [comment]
Many thanks to the references. We might current ignore the data about thyroid. Thanks!

Best,
Yao

**Comment by tompollard** [comment]
Glad this helped, thanks Yao.
