### ISSUE TITLE
Error when I try to run create tables script

### ISSUE THREAD

**Issue by akilino** [MIT-LCP/mimic-code#408]
I'm following the steps as mentioned in https://mimic.physionet.org/tutorials/install-mimic-locally-windows/ .
When I reach the part where I need to run script responsible for creating the tables "postgres_create_tables.sql", it gives me errors:

```
postgres_create_tables.sql:916: ERROR:  syntax error at or near "</"
LINE 1: </td>
```
This error goes through all the lines that have the </td>.

I have the latest version of postgres (psql 10.3).

**Comment by tompollard** [comment]
Have you looked at the file that you are trying to run? It sounds like it contains HTML, not SQL. This is the same issue as: https://github.com/MIT-LCP/mimic-code/issues/402
