### ISSUE TITLE
pO2 instead of PaO2 in blood-gas-first-day-arterial.sql?

### ISSUE THREAD

**Issue by corcra** [MIT-LCP/mimic-code#409]
It looks like the PaO2/FiO2 calculation in the ABGA analysis is using pO2 (lab item id 50821) in its numerator: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/blood-gas-first-day-arterial.sql#L126. 

Is there some reason (arterial) PaO2 (seems to be in chartevents, id 779) is not used instead? Are they equivalent?

**Comment by alistairewj** [comment]
The lab data (from LABEVENTS) is the ground truth as per BIDMC policy. The charted data in chartevents is copied over from labevents, so we prefer to use the lab data. You'll find that for arterial samples, the pO2 (50821) and PaO2 (779) values are 99% identical.

**Comment by corcra** [comment]
Awesome, thanks for the quick reply!

**Comment by iCOOlhu** [comment]
hello Corcra，There are some troubles with me when I got the value of  PaO2/FiO2. Could you help me?thanks.

**Comment by santinon** [comment]
_"for arterial samples, the pO2 (50821) and PaO2 (779) values are 99% identical."_
and we agree that this is the case for mimic 3 and mimic 4, right ?
