### ISSUE TITLE
D_ITEMS contains entries without any corresponding instances in the database

### ISSUE THREAD

**Issue by rjstretch** [MIT-LCP/mimic-code#41]
There are many itemids in D_ITEMS that supposedly link to the chartevents table, yet there are no corresponding entries in chartevents with those itemids.

select distinct(d.label)
from mimiciii.d_items d
where linksto like 'chartevents'
and itemid not in (select distinct itemid from mimiciii.chartevents);

Per discussion with @tompollard, some of these itemids are not yet in chartevents because their raw data contains PHI that has not yet been deidentified. However, there are many others that are simply 'junk' entries.

Two options for resolving this:
- remove both PHI and 'junk' entries for now, re-introducing the PHI entries as we clean the data
- remove only the 'junk' entries, and add some sort of flag to the PHI entries to indicate these may be available at some point in the future

**Comment by alistairewj** [comment]
Almost entirely fixed in version v1.4.
