### ISSUE TITLE
Create an account on PhysioNet 

### ISSUE THREAD

**Issue by layaSharifi** [MIT-LCP/mimic-code#414]
### Create an account on PhysioNet Issue

* I am having issue to create an account through the given link but its returning the page with this error message "Secure Connection Failed", after i type in my username and password for authentication . Please assist me in to get through the process for getting data. 
 
Regards,

**Comment by alistairewj** [comment]
This is not really an appropriate place for raising PhysioNet issues - try again and if you are still having issues raise them at https://github.com/MIT-LCP/physionet
