### ISSUE TITLE
Inconsistent naming of input and output fluids 'amount' and 'value'

### ISSUE THREAD

**Issue by vjm261** [MIT-LCP/mimic-code#42]
It appears that both INPUTEVENTS tables have `AMOUNT` and `AMOUNTUOM` columns whereas the OUTPUTEVENTS table uses `VALUE` and `VALUEUOM`. 

I propose the use of a consistent name, probably `VALUE` to also be consistent with CHARTEVENTS, LABEVENTS and DATETIMEEVENTS.

**Comment by alistairewj** [comment]
I suppose it could be changed - but I don't think it's necessary to have the INPUTEVENTS columns be the same as the OUTPUTEVENTS columns.
