### ISSUE TITLE
Inpatient rehabilitation hospital

### ISSUE THREAD

**Issue by thaiswalter10** [MIT-LCP/mimic-code#420]
Hello, 

I am looking for patients in the MIMIC database that where discharged directly after their ICU stay in an inpatient rehabilitation ward / hospital.
Do we agree that this specific information is not recorded in the MIMIC database ? 
And that probably most of the 6000 patients that are recorded as directly discharge after their ICU stay where probably transfered in another hospital which might have be an inpatient rehabilitation hospital ? 

Thank you very much,

**Comment by alistairewj** [comment]
I guessed at 3789 hospital admissions who were directly discharged from the ICU (7167 if you include neonates).

Grouping by hospital discharge location:

```sql
select adm.discharge_location, count(*) as numobs
from transfers tr
inner join admissions adm
on tr.hadm_id = adm.hadm_id
where adm.deathtime is null
and eventtype = 'discharge'
and prev_careunit ilike '%icu%' and prev_careunit <> 'NICU'
group by adm.discharge_location
having count(*) > 10
order by numobs desc;
```

discharge_location     | numobs 
-------------------------- | --------
 HOME                      |   1267
 REHAB/DISTINCT PART HOSP  |    747
 LONG TERM CARE HOSPITAL   |    583
 SNF                       |    416
 HOME HEALTH CARE          |    205
 SHORT TERM HOSPITAL       |    169
 LEFT AGAINST MEDICAL ADVI |    141
 HOSPICE-HOME              |     89
 DISC-TRAN CANCER/CHLDRN H |     83
 DISCH-TRAN TO PSYCH HOSP  |     50
 HOSPICE-MEDICAL FACILITY  |     23


Not sure - does this answer your question?

**Comment by alistairewj** [comment]
Excluding CCU is an oversight, good catch.

I'm not sure what I would consider high, ~1500 out of ~30,000 doesn't seem that much, but maybe it still is more than expected and "HOME" doesn't tell  the full story. The above table was *only* patients discharged directly from the ICU. Best way to figure this out is to read a few discharge summaries to get an idea of why patients are discharged to home, and whether there are additional relevant details.

**Comment by mifine** [comment]
Thanks for your answer. For CCU, I now have another issue: it is seen as an output unit in the CALLOUT Table, so it's a bit confusing. Would you know why it appears like that in this table ? 

Thanks for the comment on the "home" discharge, i'll investigate that.

**Comment by alistairewj** [comment]
Nope not sure - perhaps an inter ICU transfer!
