### ISSUE TITLE
SQL Query for ICU patients with vital signs and drugs and outcome

### ISSUE THREAD

**Issue by OluOrojo** [MIT-LCP/mimic-code#421]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/ 
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q= 
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
Are there any queries for ICU patients that include vital signs and lab records at the timestamps.

Description of the issue, including:

* what you have tried: Identified the query here:https://mimic.physionet.org/tutorials/intro-to-mimic-iii/
Which I can build on..

Is it possible to merge it with this: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted-vital.sql

* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
The pivoted queries will do what you want. If you're unfamiliar with SQL we can't really help you - you can always try exporting the views as is and working with them in a programming language that you're more familiar with.
