### ISSUE TITLE
Time shift questions.

### ISSUE THREAD

**Issue by kondor12** [MIT-LCP/mimic-code#423]
Hello!

I have some questions about timeshifting in mimic-III database.
On the site it is written that dates are internally consistent for the same patient, what does it mean?
Have been mixed only yers of admissions or even the whole dates?

For example, if in reality the person first admitted on December 31, 2010, and the second time on January 1, 2011, the data will be recorded on December 31 [year_number_1] and January 1 [year_number_1 + 1]
or something like June 6 [year_number_1] and June 7 [year_number_1]?

In the second case, if the other patient admitted on December 31, 2010, the data wil be recorded June 6 [year_nimber_1] or something else?

Thanks for the answer.

**Comment by tompollard** [comment]
I think the following paragraph (taken from the [MIMIC-III paper](https://www.nature.com/articles/sdata201635)) answers your question:

> In particular, dates were shifted into the future by a random offset for each individual patient in a consistent manner to preserve intervals, resulting in stays which occur sometime between the years 2100 and 2200. Time of day, day of the week, and approximate seasonality were conserved during date shifting. Dates of birth for patients aged over 89 were shifted to obscure their true age and comply with HIPAA regulations: these patients appear in the database with ages of over 300 years.

"Approximate seasonality" is conserved, and "dates were shifted into the future by a random offset for each individual patient", so two patients admitted on the same day probably do not have the same shift.
