### ISSUE TITLE
There is something wrong with my databse

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#424]
Hello, sorry for disturbing you. When i ran the code of "aline_vaso_flag", the following error emrged:
[Err] ERROR:  relation "inputevents_cv" does not exist
LINE 17:   from inputevents_cv
But i am sure the inputevents_cv table exists. It seemed all the tables in the database cannot be identified, why ?
Thank you, and i look forward to hearing from you.

**Comment by young310** [comment]
Hi, have you tried to set search_path?
e.g. set search_path = mimiciii, public;

or add the schema name in front of your table name.
e.g. from mimiciii.inputevents_cv
