### ISSUE TITLE
Error loading postgres_load_data.sql

### ISSUE THREAD

**Issue by jckarthic** [MIT-LCP/mimic-code#425]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description

Description of the issue, including:
I am trying to install MIMIC III on Windows 10 x64 using psql from Enterprise DB.
While trying to run the postgres_load_data.sql i am receiving a syntax error:
psql:D:/ANZICSDatathon/Postgres/postgres_load_data.sql:475: ERROR:  syntax error at or near "<!"
LINE 1: <!DOCTYPE html>
        ^
I could not find a similar issue on the forum or anywhere else.

Kindly assist whether it is an issue with the version of psql? Or with the file?

**Comment by jckarthic** [comment]
> psql:D:/ANZICSDatathon/Postgres/postgres_load_data_7zip.sql:475: ERROR:  syntax error at or near "<!"
LINE 1: <!DOCTYPE html>
        ^

**Comment by tompollard** [comment]
Have you tried looking at the contents of the file you are trying to run? It sounds like a duplicate of the following issues:

- https://github.com/MIT-LCP/mimic-code/issues/408
- https://github.com/MIT-LCP/mimic-code/issues/402
- https://github.com/MIT-LCP/mimic-code/issues/210

**Comment by jckarthic** [comment]
Thank you. That solved it.
