### ISSUE TITLE
About ITEM_ID 50889

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#428]
Dear Sir, 
       I am soory for my lastest unclear question about CRP and now I will clearly pose my question. When I searched for CRP (ITEM_ID = 50889) in LABEVENTS table, I find there were only 899 patients in MIMIC III with CRP measured for the first day in ICU. Was it practical ?

**Comment by alistairewj** [comment]
Yes, I don't think CRP was commonly measured at the BI between 2001-2012.
