### ISSUE TITLE
How can I plot the synchronized ECG and PPG signal from MIMIC III database?

### ISSUE THREAD

**Issue by isolde1982** [MIT-LCP/mimic-code#429]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Please follow the issue template when asking questions.
