### ISSUE TITLE
About patients aged over 89

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#430]
Hello,
On the sites, "Dates of birth for patients aged over 89 were shifted to obscure their true age and comply with HIPAA regulations: these patients appear in the database with ages of over 300 years". 
But i am wondering how to get these true ages for patients "over 300" ?

**Comment by alistairewj** [comment]
You can't. We are not legally allowed to share them.

**Comment by jaredleitner** [comment]
I understand you cannot share the DOB for patients over 89, but is it possible to know the DOB for patients younger than 89? If so, where I can I find that information?

**Comment by alistairewj** [comment]
The DOB and the admission times are both in the future, but the patient's age is maintained as the dates are shifted using a constant offset. That is if a patient is born in `2100`, and admitted to the ICU in `2150`, then they are 50 years old. An example script calculating age is available here: https://github.com/MIT-LCP/mimic-code/blob/240823295650c5933260aa7d37665a7caa2c55df/concepts/demographics/icustay-detail.sql#L24

**Comment by ngmyy** [comment]
how can I know the average age of the person who are older than 89 ?
