### ISSUE TITLE
Very few matched waveform in neonates?

### ISSUE THREAD

**Issue by nsanchezpinto** [MIT-LCP/mimic-code#432]
Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
Checked the online documentation: https://mimic.physionet.org/about/mimic/
Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

Description

I have cross-referenced the subject IDs in the matched subset of waveform/numeric data with the subject ID corresponding to patients in the NICU and it a appears that very few neonates have had their waveforms matched. Is this correct? Are the vast majority of the 10K subjects with matched waveforms adults?

Thanks!

**Comment by alistairewj** [comment]
Yes, this is correct, almost all of the matched waveforms are for adults.
