### ISSUE TITLE
How is Ferritin measured and why is time not available for prescriptions?

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#436]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
Hello,
I had the following questions about LABEVENTS and PRESCRIPTIONS:
1) I wished to extract "Ferritin (ITEM_ID=50924)" from LABEVENTS, but I am wondering is this ferritin measured by ELISA or by typical biochemical platforms? In the latter case, high ferritin values are not well separated and this may cause confounding. 
2) When I wanted to calculate the  time to start of antimicrobials, I found the STARTTIMEs in PRESCRIPTIONS were only accurate to date, but no hours, minutes or seconds, why?

**Comment by alistairewj** [comment]
1. Best to check with the LOINC code and see if that exists, and if it does whether it can give you more information - we're not intimately familiar with all lab procedures.
2. Prescriptions are often only made for a given date. The provider doesn't have to specify a time of day.

**Comment by mylanhong** [comment]
@alistairewj Thank you very much for you answer !
