### ISSUE TITLE
How is Compliance measured?

### ISSUE THREAD

**Issue by EmmaRocheteau** [MIT-LCP/mimic-code#437]
This question relates to the data itself. How is 'Compliance (40-60ml)' measured? Does it relate to static lung compliance or dynamic lung compliance?

**Comment by alistairewj** [comment]
@lceli ideas?

**Comment by lceli** [comment]
We don’t trust any compliance measurement unless the patient is paralyzed. This is the reason we don’t even look at this variable.

**Comment by EmmaRocheteau** [comment]
I have since noticed that the variable is equal to (Peak Inspiratory Pressure - PEEP) / Tidal Volume

**Comment by EmmaRocheteau** [comment]
![pip_constant](https://user-images.githubusercontent.com/15163739/40808189-489e976e-651e-11e8-9720-11d0c4cce3ca.png)

**Comment by tompollard** [comment]
Not `Tidal Volume / (Peak Inspiratory Pressure - PEEP)`?

**Comment by EmmaRocheteau** [comment]
^ Yes sorry!

**Comment by tompollard** [comment]
Thanks Emma, are you happy if we now close this issue or are you still looking for more detail?

**Comment by EmmaRocheteau** [comment]
Yes I'm happy. Sorry I asked something that I could figure out myself

**Comment by tompollard** [comment]
No apologies needed! Thanks for posting the solution :)
