### ISSUE TITLE
MIMIC3 Waveforms to Hospital Admissions (HADM_ID)

### ISSUE THREAD

**Issue by Saqibm128** [MIT-LCP/mimic-code#438]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description

I am currently trying to match specific waveforms from the Matched Waveform subset to hospital admission ids (HADM_ID) in the admissions table. Currently, I am iterating through and comparing admission times and discharge times of a subject with the time that the waveform began recording (extracted from the filename).

When using a strict approach, I find that I can only match 17884 records to a hospital admission id, out of 22241 total. When using a semistrict approach (i.e. allow records to start 6 hours before the actual admission time), I can get 18606 records matched to a hospital admission id. Is this a valid approach? If so, is the admission time in the database correct, and is the data before the admission time in the waveform record usable for these specific records?

**Comment by alistairewj** [comment]
The semi-strict approach is reasonable as the admission/discharge times are entered administratively - there's no guarantee they are precise down to the minute. It's worthwhile to correlate clinical data with waveform data (e.g. numerics blood pressure with charted blood pressure) just to verify that the data is sensibly matched, as the matching process was non-trivial. You can read more about the waveform matching process [in this CinC article available on DSpace](https://dspace.mit.edu/openaccess-disseminate/1721.1/66228).

**Comment by Saqibm128** [comment]
Has the code used to do the matching process ever made public? I do not see it either inside this repo or any of the other repos associated with MIT-LCP group. Thank you!

**Comment by alistairewj** [comment]
No, I do not believe it has.

**Comment by Saqibm128** [comment]
Thank you!
