### ISSUE TITLE
.alarm and .alM files in MIMIC III?

### ISSUE THREAD

**Issue by xorb22** [MIT-LCP/mimic-code#439]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
I am trying to find annotation of the alarms in MIMIC III. I see that for MIMIC II version 2.0 there is ".alarm" and ".alM" files. However i donot find them for MIMIC II. Could you please let me know how to access alarms in MIMIC III. I saw that the table CHARTEVENTS contains a field "alarm". However, this alarm is just a binary value of 0/1 for that record (there is no temporal annotation along with the waveform or numeric form).

**Comment by wantai01** [comment]
I have a similar issue. I am interested in analyzing the waveform before the occurrences of the arrhythmic alarms. Is MIMIC 2 or MIMIC 3 more suitable for this analysis? Does MIMIC 3 explicitly tell us when the alarms occur?

**Comment by alistairewj** [comment]
I discussed this with a colleague. They had the following to say:

> The alarm labels that were released previously were all from version 1 of the (waveform) database. Some of the red alarms from that subset were reviewed and annotated as true/false.
> There may be some time alignment issues with those labels (I'm not sure.)  Not all records from that time period were included.

Essentially; it's possible to map these labels to the MIMIC-III Waveform Database, but we haven't undertaken that work yet as it is not high priority for our lab.

**Comment by xorb22** [comment]
Thanks for your reply. If I were to try to map the alarm from MIMIC-II to the waveform/numeric-form of MIMIC-III, could you please let me know how can I go about doing that. I would like to try to do that so that I can have a matched dataset that has (a) clinical outcomes, (b) waveform/numeric-forms, and (c) temporal alarm information. I would like to use these three information to see possibility of patient deterioration. If you have any alternative suggestion on accessing temporal location of patient deterioration, please kindly let me know.

**Comment by alistairewj** [comment]
Why do you need the alarm at all? Couldn't you just define the event yourself, e.g. look for prolonged periods of hypotension?

In terms of adverse events, these are not systematically documented in the dataset, though there are always clever ways to define them. One option is to trust the care provider, and use increased intensity of treatment as a surrogate for deterioration (e.g. initiation of vasopressors would indicate patient decompensation). The durations views would be useful for this.

**Comment by xorb22** [comment]
Thanks for following up on this Alistair. I think if I tell you what I am trying to do, you may be better able to direct me on how to use the MIMIC III dataset. 

I am trying to test patient deterioration prediction algorithm using MIMIC-III dataset. To start with and for simplicity, I am just trying to look at the numeric-form (lets say just heart rate and breathing rate). I want to see how predictive are abnormality in these two numeric-form to predict patient deterioration. It is better if I have an annotation of alarm or anything that indicates patient deterioration. What information from the database can be used as ground truth for patient deterioration. It is the best if these patient deterioration information are time stamped so I can know exactly when these deterioration occurred, and how early did vitals show abnormality. 

Thanks for your helpful feedback.

**Comment by alistairewj** [comment]
Sorry I never really got back to you in a timely manner. This is a pretty open ended question and there are a lot of ways you could define patient deterioration (increasing intensity of treatment, significant events, increasing levels of organ failure via lab values). Hope you figured something out!

**Comment by teddywest32** [comment]
@alistairewj  I am trying to work on cardiac arrest prediction in the patient about 30 minutes before the arrest but, I am not able to find any ground truth that says the arrest was caused at a certain time in the clinical dataset. Is there any way to identify the condition in the dataset?
