### ISSUE TITLE
Issue with "Data or specimens only research" course, prior to access MIMIC III

### ISSUE THREAD

**Issue by csartini** [MIT-LCP/mimic-code#440]
Hi there, 

I am trying to register for the "Data or specimens only research" course, which seems mandatory prior to access the MIMIC III data base. 

Instructions reported that: First register on the CITI program website, selecting “Massachusetts Institute of Technology Affiliates” as your organization affiliation (not “independent learner”): https://www.citiprogram.org/index.cfm?pageID=154&icat=0&ac=0

Barriers:
1) I am not a MIT affiliate and
2) The “Data or Specimens Only Research” course does not exist for independent learners. 
3) The CITI program support team said that the "biomedical basic" course available for independent learners covers the same modules of the “Data or Specimens Only Research”. Is it accepted by the MIMIC research group?

Has anyone experienced the same situation ?

Thanks in advance for your time and help!!

Claudio

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

**Comment by tompollard** [comment]
Hi @csartini, as noted in the instructions at: https://mimic.physionet.org/gettingstarted/access/ you should select "Massachusetts Institute of Technology Affiliates” as your organization. The steps are outlined below in more detail:

- go to https://www.citiprogram.org/ .  Click on the "register" link under "create an account" (right side of screen)
- under "Select Your Organization Affiliation", type in the form field to select "Massachusetts Institute of Technology Affiliates", check the "I agree" box, and submit.
- continue through the screens, filling in the requested information.

![screen shot 2018-06-26 at 17 54 03](https://user-images.githubusercontent.com/822601/41941538-4e35bc10-796a-11e8-98b2-57073abfe665.png)

The “Data or Specimens Only Research” will be available to you after registering.

**Comment by tholu** [comment]
This is exactly how it works, this issue can be closed.

**Comment by alistairewj** [comment]
Please register as an MIT affiliate -- since the data are hosted at MIT, such affiliation is expected for the purpose of this training course.

**Comment by JohannesWiesner** [comment]
> Please register as an MIT affiliate -- since the data are hosted at MIT, such affiliation is expected for the purpose of this training course.

I am having the same issue. How do I register as an MIT affiliate?

**Comment by priyankamsingh** [comment]
I am facing the same issue. I need to have access to databse for my thesis. But It seems it is only for MIT.
I am not an MIT student or MIT affilate ?
Can someonegive some guidance here

**Comment by csartini** [comment]
See instructions in the thread above from MIT colleagues. Please register as an MIT affiliate -- since the data are hosted at MIT, such affiliation is expected for the purpose of this training course.

**Comment by priyankamsingh** [comment]
This is my question, how can someone register as MIT affiliate. I do not need to do any courses or anything there.

**Comment by csartini** [comment]
Please register as an MIT affiliate (even if you are not, it does not matter) following the instructions provided by Tom Pollard in the thread above. And yes, following the instructions you have to do a course which you do on line and it takes 30 minutes

**Comment by priyankamsingh** [comment]
Thank you

**Comment by maelmahdy86** [comment]
@csartini Can you please tell me how did you register however you're not in MIT because i'm facing the same issue now and it asks me about some MIT-related info
![image](https://user-images.githubusercontent.com/76489448/154839721-6d58588f-24bd-4c8a-b3b9-300e5c585a66.png)
****
> Please register as an MIT affiliate (even if you are not, it does not matter) following the instructions provided by Tom Pollard in the thread above. And yes, following the instructions you have to do a course which you do on line and it takes 30 minutes

**Comment by Sameedism1995** [comment]
> @csartini Can you please tell me how did you register however you're not in MIT because i'm facing the same issue now and it asks me about some MIT-related info ![image](https://user-images.githubusercontent.com/76489448/154839721-6d58588f-24bd-4c8a-b3b9-300e5c585a66.png)
> 
> > Please register as an MIT affiliate (even if you are not, it does not matter) following the instructions provided by Tom Pollard in the thread above. And yes, following the instructions you have to do a course which you do on line and it takes 30 minutes

@tompollard Hi, kindly help

**Comment by mscanlan-git** [comment]
@Sameedism1995 employee number is not required to submit. For department/role, you can select your current department/role at your institution (if applicable). What you actually input doesn't really matter - we do not see this information when reviewing CITI training applications, this is more on CITI's end.

**Comment by Raid2024m** [comment]
السلام عليكم اتمني لكم دوام العافيه اريد الوصول للبيانات لدي بحث للرساله الماجستير حول البيانات الذي قد نزل البيانات اتمني اعطائي واتعهد بعدم استخدامها لاي غرض اخر غير البحث العلمي وشكرا
