### ISSUE TITLE
couldn't create MIMIC-III in a local Postgres

### ISSUE THREAD

**Issue by mostafaalishahi** [MIT-LCP/mimic-code#445]
### Description

Description of the issue, including:

* I have tried the https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/postgres tutorial in order  to create the mimic locally, but executing the following line in ubuntu  
sudo make create-user postgres datadir="/data/dir" DBNAME="mimic" DBPASS="postgres"
returns 

-------------------------------------
-- Creating user, database, schema --
-------------------------------------

MIMIC_USER="postgres" MIMIC_DB="mimic" MIMIC_PASSWORD="postgres" MIMIC_SCHEMA="mimiciii" DBHOST="" DBPORT="" ./create_mimic_user.sh
MIMIC_PASSWORD is set
MIMIC_DB is set to 'mimic'
User is set to 'postgres'
Not logged in as postgres user. Script will require sudo.
*** Ignore any warnings of the form: 'could not change directory to...' ***
These indicate you are running the script in a folder that the postgres user does not have access to.
The script will still work - so these warnings can be safely ignored.
DROP DATABASE
CREATE DATABASE
CREATE SCHEMA
make: *** No rule to make target 'postgres'.  Stop.

is there anything wrong in here? if yes please let me know.

then executing to be sure that make file works fine 
psql -U postgres -h localhost -d mimic

and this
\dt
No relations found.

I got confused how to be sure if the make file executed correctly, and how to get access to my tables.

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

**Comment by tholu** [comment]
Try `make create-user mimic-gz datadir="/data/dir" DBNAME="mimic" DBPASS="postgres"` - `postgres` is not a valid goal for the make command.

**Comment by alistairewj** [comment]
Yep - your `make` call was malformed as pointed out by @tholu. Going to assume your issue is resolved.
