### ISSUE TITLE
Interpreting zeroes and blanks

### ISSUE THREAD

**Issue by schatlani** [MIT-LCP/mimic-code#447]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello,

We are conducting some analysis on AKI and are staging patients based on urine output and serum creatinine levels. Could you advise what zero and blank values for urine output-related fields imply? Presumably, zero means it was an observation that the patient had no urine output at the time but how could we interpret blanks? I do not see this called out in the SQL code since it essentially sums all output over 24 hours.

Would you statement about blank values apply to all fields that have them?

Thanks in advance.

**Comment by alistairewj** [comment]
There's no easy way to define what a blank is in every situation. Often blanks occur when the caregiver would like to make a note in a comment field, but doesn't want to document a value for that field (e.g. a blank may indicate that they have added a comment regarding the appearance of the urine). We've assumed it as 0 urine output as we believe that's a reasonable assumption.
