### ISSUE TITLE
Definition of BRADY and TACHY in MIMIC-II

### ISSUE THREAD

**Issue by wantai01** [MIT-LCP/mimic-code#450]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

For the alarms in MIMIC-II, the definition for bradycardia is HR<40BPM. But I cannot find over how many heartbeats this HR is calculated. Also, for tachycardia, the definition is above HR > n BPM. For tachycardia, over how many beats is the HR calculated and is n set differently for every alarm?

**Comment by alistairewj** [comment]
The heart rate will be calculated by the bedside monitor which uses a proprietary algorithm. Unfortunately we have no way of giving you this information, but there are standard definitions of bradycardia and tachycardia which you could apply. The 2015 challenge page on reducing false arrhythmia alarms in the ICU has some useful info/data: https://physionet.org/challenge/2015/
