### ISSUE TITLE
Problem with query builder login

### ISSUE THREAD

**Issue by edballest** [MIT-LCP/mimic-code#451]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I am getting an error when trying to log into the query builder. I've successfully done it several times in the past with these credentials, but these time it just says "There was a problem with the login. Please try again".

**Comment by tompollard** [comment]
Thanks for highlighting this issue. It looks like there is a problem with authentication, which may be a result of some recent changes to our server. The person in the lab who maintains the tool is away right now, so the fix may have to wait a few days. Sorry for the inconvenience. @elfeto

**Comment by edballest** [comment]
Thanks for the quick response! Please let me know when this issue gets
resolved.

Best,
Eduardo

**Comment by tompollard** [comment]
Thanks Eduardo, we'll let you know here when it is fixed.

**Comment by elfeto** [comment]
Hi Eduardo, 

I apologize for the inconvenience. I am doing a upgrade in the script and forgot to do a change in the login.  
There might be a problem with the queries that return a error, but I am working on that. (If the query sintax is fine, it will work.)

**Comment by NadavLankin** [comment]
Guys, does anyone experience login problems? for some reasone, I cannot log in

**Comment by tompollard** [comment]
@NadavLankin the physionet servers were down this morning, but I believe they are back up now.

**Comment by vipinakk** [comment]
Anyone experiencing log in issues still? I can log in to Physionet but unable to login to query builder.

**Comment by elfeto** [comment]
Can you log in and see the files in here: https://physionet.org/content/mimiciii/1.4/ ?

**Comment by vipinakk** [comment]
Yes, but I am not able to login to https://querybuilder-lcp.mit.edu/
