### ISSUE TITLE
Over deidentify of gestational age descriptions

### ISSUE THREAD

**Issue by young310** [MIT-LCP/mimic-code#452]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

While I look into newborn babies, there exists some over deidentify issues.
For example, 

> Baby Girl [**Known lastname **] was a 24 [**___**] week gestation female

The original text could be something like 24 2/7, which means 24 weeks and two days.
I would suggest to revise the deidentify algorithm and keep the important information, thank you.

**Comment by tompollard** [comment]
Thanks for the pointer @young310.
