### ISSUE TITLE
Starttime bigger than endtime at inputevent_mv table 

### ISSUE THREAD

**Issue by schvetz1** [MIT-LCP/mimic-code#457]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

Hi,
Way at inputevent_mv table, there are 100 rows were their starttime is bigger than endtime?

select * FROM mimiciii.inputevents_mv where (starttime-endtime)> interval '1 minute'

![start bigger than end time](https://user-images.githubusercontent.com/33550773/43576612-6b2735d8-9652-11e8-9bdb-e49d960c5088.PNG)

**Comment by tholu** [comment]
@schvetz1 Check the columns `AMOUNT` (all negative) and `CANCELREASON` (are probably all `1`) as well as `STATUSDESCRIPTION` (`Rewritten` for those I checked).

https://mimic.physionet.org/mimictables/inputevents_mv/#statusdescription

> Rewritten - Incorrect information was input, and so the information in this row was rewritten (these rows are primarily useful for auditing purposes - the rates/amounts described were not delivered and so should not be used if determining what compounds a patient has received).

**Comment by schvetz1** [comment]
Thanks
