### ISSUE TITLE
"None" used to code oxygentherapy event. 

### ISSUE THREAD

**Issue by geickelb** [MIT-LCP/mimic-code#463]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

In digging through the ventilation-durations.sql file my group and I may have found an issue with one of the criteria used to code OxygenTherapy =1. One of the criteria to code a ventilation event as an OxygenTherapy =1 event is that itemid (in chartevent) =467 and the value = 'None' (95498 observations). Upon some further digging, it appears that the 'None' category is assigned to patients who had previously been given OxygenTherapy but, at the time of the ventilation event, were not being given OxygenTherapy. After consulting with my team of ICU clinicians and data scientists, we believe that coding a "not on oxygen therapy anymore" variable as an event signifying a patient received oxygen therapy is potentially erroneous. We wanted to bring this to your attention as it is either: (1) an unintentional oversight in the .sql coding or (2) we are missing some context as to why this makes sense. 

the code is as follows:
max(
      case
        -- initiation of oxygen therapy indicates the ventilation has ended
        when itemid = 226732 and value in
        (
          'Nasal cannula', -- 153714 observations
          'Face tent', -- 24601 observations
          'Aerosol-cool', -- 24560 observations
          'Trach mask ', -- 16435 observations
          'High flow neb', -- 10785 observations
          'Non-rebreather', -- 5182 observations
          'Venti mask ', -- 1947 observations
          'Medium conc mask ', -- 1888 observations
          'T-piece', -- 1135 observations
          'High flow nasal cannula', -- 925 observations
          'Ultrasonic neb', -- 9 observations
          'Vapomist' -- 3 observations
        ) then 1
        when itemid = 467 and value in
        (
          'Cannula', -- 278252 observations
          'Nasal Cannula', -- 248299 observations
          **'None', -- 95498 observations**
          'Face Tent', -- 35766 observations
          'Aerosol-Cool', -- 33919 observations
          'Trach Mask', -- 32655 observations
          'Hi Flow Neb', -- 14070 observations
          'Non-Rebreather', -- 10856 observations
          'Venti Mask', -- 4279 observations
          'Medium Conc Mask', -- 2114 observations
          'Vapotherm', -- 1655 observations
          'T-Piece', -- 779 observations
          'Hood', -- 670 observations
          'Hut', -- 150 observations
          'TranstrachealCat', -- 78 observations
          'Heated Neb', -- 37 observations
          'Ultrasonic Neb' -- 2 observations
        ) then 1
      else 0
      end
    ) as OxygenTherapy

**Comment by alistairewj** [comment]
Yes I would agree. Just for context - it's perhaps not very intuitive - the ultimate purpose of that flag is to indicate that the patient is off the vent. The standard procedure is to move them from vent to some form of oxygen therapy or NIV. This `OxygenTherapy` flag is analogous to the `Extubated` flag in that way: if they are on oxygen therapy, then set the field to 1, and this is later used to end the duration of mechanical ventilation. However in my review of some patients, it looks like they will use this field in conjunction with breathing trials to indicate that the breathing trial was not successful. Overall, it's probably better not to use 'None' as an indicator of no ventilator, as "not on oxygen therapy" is not equivalent to "not on a ventilator". Thanks for the catch!
