### ISSUE TITLE
'Amount' field is equal to 0 on tables inputsevents_cv\mv

### ISSUE THREAD

**Issue by schvetz1** [MIT-LCP/mimic-code#464]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Why there are rows with 'amount' field equal to zero on tables inputeven_cv and inputevents_mv?

SELECT * from mimiciii.inputevents_mv where amount=0 and statusdescription <> 'Rewritten' limit 100

SELECT * from mimiciii.inputevents_cv where amount=0  limit 100

Thanks

**Comment by alistairewj** [comment]
No amount was administered!

For CareVue, it was common to use `amount = 0` as a "pause", that way you could later enter amounts and not have to retype all the drug information.

For MetaVision, I'm not sure really - might be the same as above. Worth noting that it is exceedingly rare in inputevents_mv (5,059 rows out of 2,923,470 have an amount of 0).
