### ISSUE TITLE
missing values in heightweight table

### ISSUE THREAD

**Issue by cvalluru6** [MIT-LCP/mimic-code#465]
Hi everyone,

I would like to know if anyone of you has imputed missing values in the heightweight table.

**Comment by alistairewj** [comment]
Looks like there weren't many suggestions (unfortunately). Likely you'll need to decide for yourself what's appropriate for your work! Note that weight is a required measurement for certain medications dosed by weight, and height is a required measurement for certain medications dosed by body surface area, so depending on your study the data may not be missing at random.
