### ISSUE TITLE
Questions about patients' language recorded in ADMISSIONS

### ISSUE THREAD

**Issue by liumiaoshiqi** [MIT-LCP/mimic-code#467]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

I notice that some patients' language were recorded as 'AMER'. Does it mean 'American English' or something completely different from English? 

Besides, does the language refer to 'mother tongue'?

Thank you!

**Comment by alistairewj** [comment]
Yes, that column intends to describe the native language of the patient.

`AMER` does not mean American English, rather it refers to American Sign Language, so the patient is likely deaf.
