### ISSUE TITLE
Rewritten/Changed/Stopped differences in INPUTEVENTS_MV

### ISSUE THREAD

**Issue by vincentmajor** [MIT-LCP/mimic-code#47]
Can someone please clarify the roles of `CANCELREASON` and `STATUSDESCRIPTION` in the INPUTEVENTS_MV table. 
From what I have seen `CANCELREASON` can be 0, 1 or 2 - what is the difference between 1 and 2?
And `STATUSDESCRIPTION` can be Rewrtten, Changed or Stopped - what is the difference and why does the `AMOUNT` field sometimes match the `ORIGINALAMOUNT` even though the order was rewritten/changed/stopped? 

I've also noticed that `CANCELREASON` and `STATUSSDESCRIPTION` don't always match. That is rewritten orders can have `CANCELREASON` of 0, 1 or 2.

**Comment by alistairewj** [comment]
The documentation is limited on this topic so empirical observations are very welcome here.

I do know that `STATUSDESCRIPTION` provides some information on cancellations - that is, if an order was "Rewritten" then I don't think it was every administered to the patient. You can see this for individual drugs: the `STARTTIME` of the current order will perfectly match the `ENDTIME` of the previous order *after* you remove all the rows with `STATUSDESCRIPTION` = 'Rewritten'.

I really don't know about the rest - do you have any notable observations?

**Comment by ilana-intensix** [comment]
Does anyone have any further insight on these ambiguities? I'm trying to understand which rows can be safely filtered out and whether a I can assume that a "Changed" order has run from the `STARTTIME` to the `ENDTIME`. Alistair, were you able to verify that a status of "Rewritten" indicates that a medicine wasn't administered?

**Comment by alistairewj** [comment]
For `STATUSDESCRIPTION`, we have the following possibilities:

* Changed - the dose was modified, as a result the current rate ends now, and a new rate begins.
* Paused - drug delivery has been paused
* Stopped - the drug is no longer being delivered
* Finished Running - the bag/container which the drug was in has been emptied, and so the drug is no longer being delivered
* Rewritten - the order was changed before the drug was delivered

As far as we know, all rewritten rows should only be used for audit purposes, i.e. these rows correspond to drug doses never being given to patients. We are considering removing this audit trail in the future as its use in research seems limited and it only acts to create a confusing table.

(N.B. strictly speaking, there are a two other order status, 'Reported' and 'Bolus', but they seem to be used extremely rarely if at all).

I haven't investigated `CANCELREASON` further so I can't comment on that!

**Comment by ilana-intensix** [comment]
Thanks very much!

In the cases where a medicine was Paused or Stopped, can we understand that the medicine was administered through the `ENDTIME`? That is, the time of pausing/stopping was the value in the `ENDTIME` column?

**Comment by alistairewj** [comment]
No problem. That is exactly what you should assume. Stopping/pausing a drug generates the `ENDTIME`. In the case of changing a drug, a new row will be created with the new drug dose which has a `STARTTIME` the same as the previous `ENDTIME`. It ends up working very nicely as you can select all administrations of the solution using the `LINKORDERID` and they will overlap perfectly. There's a toy example here: https://mimic.physionet.org/mimicdata/io/#metavision

**Comment by ilana-intensix** [comment]
Excellent, thanks again.

**Comment by schvetz1** [comment]
In the following example after I discarded from rows that were "Rewritten" I still have rows (for the same drug at the same ICU admission) that their time period is overlapping. In that example, does the patient received several different rates of the same drug at the same time or it is an error at the data:

SELECT icustay_id,itemid,starttime, endtime,amount,rate,ordercategorydescription,statusdescription  FROM mimiciii.inputevents_mv 
where icustay_id=200001 and itemid=220949 and statusdescription <> 'Rewritten' 
ORDER BY starttime


<img width="473" alt="input_mv" src="https://user-images.githubusercontent.com/33550773/43248137-8b7e4e0e-90bf-11e8-9870-926c905c3d92.PNG">
