### ISSUE TITLE
What was the monitoring site of echocardiogarphy ?

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#470]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

Thanks for the contributions. When I see the sql code of echo-data
https://github.com/MIT-LCP/mimic-code/blob/master/concepts/echo-data.sql
I am wondering what was the monitoring site of echocardiogarphy ? Transthoracic or Transoesophageal ?

**Comment by alistairewj** [comment]
The `test` column in echodata specifies the test name: TTE, TEE, portable, etc. It is free-text but there are only 37 unique values so it should be fairly easy to group.
