### ISSUE TITLE
What does WARNING mean in chartevents table?

### ISSUE THREAD

**Issue by ydc223** [MIT-LCP/mimic-code#472]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

In chartevents table there is a column called WARNING.  [The documentation says](https://mimic.physionet.org/mimictables/chartevents/#warning-error) that 
WARNING is a Metavision specific column which specify if a warning for the value was raised. Does this warning mean that test result might indicate a problem with patient's health or does warning refer to a possible error with the test?

**Comment by alistairewj** [comment]
I *believe* warning is something a nurse can add to a recorded data element (imagine a spreadsheet program where you can right click a cell and click "add warning"). Past that, it is entirely dependent on what was going through the nurse's mind, so it could be a health issue, an error in the test, or anything in between. Often there will be a free-text comment which gives some context, but unfortunately any comments associated with a row are not publicly available as they often contained PHI (something we do hope to improve in the future).
