### ISSUE TITLE
Determining mechanical ventilation periods and free of mechanical ventilation periods!

### ISSUE THREAD

**Issue by LuckySpy** [MIT-LCP/mimic-code#473]
At the query that you define the mechanical ventilation duration, you start by creating the ventsettings materialized view. Wouldn't be better if we take as duration the beginning of the mechanical ventilation event until the beginning of an oxygen therapy.
E.g.   charttime                       mechvent   Oxygentherapy   ......
	"2116-07-10 15:00:00"	  1	              0                         0     0
	"2116-07-10 18:30:00"	  1	              0	                 0	0
	"2116-07-10 23:00:00"	  1	              0	                 0	0
	"2116-07-11 02:00:00"	  0	              1	                 0	0

The current query ventdurations.sql  is calculating:  mechanical ventilation from "2116-07-10 15:00:00" to "2116-07-10 23:00:00". The question is in what state is the patient until oxygentherapy starts ( "2116-07-11 02:00:00")? I suppose he/she should be still connected on the mechanical ventilation. Isn't it more correct to have the result of the duration:  mechanical ventilation from "2116-07-10 15:00:00" to "2116-07-11 02:00:00" where the oxygen therapy starts.

If we want to calculate the duration that patients is not connected to mechanical ventilation we could do the same, meaning:  starting counting the time from the initiation of oxygentherapy until the next incident of mechvent that follows?

**Comment by alistairewj** [comment]
Yes, this is a reasonable change! Do you feel up to a PR?

**Comment by LuckySpy** [comment]
Thank you for the response. After using the ventsettings materialized view I have created the mechanical ventilation duration table in R.  By "Do you feel up to a PR?",  do you mean if I could write some SQL query that gives the aforementioned results? If yes I will try to do it otherwise, please clarify.

**Comment by alistairewj** [comment]
Yes and specifically I mean creating a pull request via GitHub's interface so that we can do a code review. Ultimately the aim is to incorporate the code into the repository!

**Comment by SelvaSathappan** [comment]
I have few questions about this table. Is it the right place to ask?
