### ISSUE TITLE
Python Colab error for height_weight

### ISSUE THREAD

**Issue by christinium** [MIT-LCP/mimic-code#482]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I can run a query of _physionet-data.mimiciii_derived.heightweight_ bigquery, but it does not work in colab python notebook.  I think it might be because heights/weights are type "numeric" (vs float).

Description of the issue, including:
* what you have tried
- successful query of physionet-data.mimiciii_derived.heightweight in bigquery
- successful query of other derived tables (like angus_sepsis) in colab
- successful query of physionet-data.mimiciii_derived.heightweight - when I only select integer values of icustay_id or subject_ids.

* references to similar issues
Couldn't find any specific ones.
* queries demonstrating your question (if applicable)
**Works in bigquery:** 
SELECT *
FROM `physionet-data.mimiciii_derived.heightweight` as hw
**Doesn't work in colab:**
df_noteevents_categories = run_query('''
SELECT *
FROM `physionet-data.mimiciii_derived.heightweight`;
''')
df_noteevents_categories = run_query('''
SELECT hw.*
FROM `physionet-data.mimiciii_derived.heightweight ` as hw;
''')
**Works in colab:**
df_noteevents_categories = run_query('''
SELECT icustay_id, subject_id
FROM `physionet-data.mimiciii_derived.heightweight`;
''')

**Comment by tompollard** [comment]
Thanks @christinium, I'll sort this out now. Can you post the error message that you get when running the query in Colab?

**Comment by christinium** [comment]
**This also works in Colab**
df_noteevents_categories = run_query('''
SELECT icustay_id, subject_id, cast(height_first as float64), cast(weight_first as float64)
FROM `physionet-data.mimiciii_derived.heightweight` as hw
where height_first is not null and weight_first is not null
''')

**Comment by christinium** [comment]
**Code in colab:**
df_noteevents_categories = run_query('''
SELECT *
FROM `physionet-data.mimiciii_derived.heightweight`;
''')
**Error:**


ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-41-54e2931e2fde> in <module>()
      2 SELECT *
      3 FROM `physionet-data.mimiciii_derived.heightweight`;
----> 4 ''')

<ipython-input-5-d3bede1b4d52> in run_query(query)
      3 # Read data from BigQuery into pandas dataframes.
      4 def run_query(query):
----> 5   return pd.io.gbq.read_gbq(query, project_id=project_id, verbose=False, configuration={'query':{'useLegacySql': False}})

/usr/local/lib/python3.6/dist-packages/pandas/io/gbq.py in read_gbq(query, project_id, index_col, col_order, reauth, verbose, private_key, dialect, **kwargs)
     97         private_key=private_key,
     98         dialect=dialect,
---> 99         **kwargs)
    100 
    101 

/usr/local/lib/python3.6/dist-packages/pandas_gbq/gbq.py in read_gbq(query, project_id, index_col, col_order, reauth, verbose, private_key, auth_local_webserver, dialect, **kwargs)
    819         project_id, reauth=reauth, private_key=private_key,
    820         dialect=dialect, auth_local_webserver=auth_local_webserver)
--> 821     schema, rows = connector.run_query(query, **kwargs)
    822     final_df = _parse_data(schema, rows)
    823 

/usr/local/lib/python3.6/dist-packages/pandas_gbq/gbq.py in run_query(self, query, **kwargs)
    537         except self.http_error as ex:
    538             self.process_http_error(ex)
--> 539         result_rows = list(rows_iter)
    540         total_rows = rows_iter.total_rows
    541         schema = {

/usr/local/lib/python3.6/dist-packages/google/api_core/page_iterator.py in _items_iter(self)
    198         """Iterator for each item returned."""
    199         for page in self._page_iter(increment=False):
--> 200             for item in page:
    201                 self.num_results += 1
    202                 yield item

/usr/local/lib/python3.6/dist-packages/google/api_core/page_iterator.py in next(self)
    123         """Get the next value in the page."""
    124         item = six.next(self._item_iter)
--> 125         result = self._item_to_value(self._parent, item)
    126         # Since we've successfully got the next value from the
    127         # iterator, we update the number of remaining.

/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/_helpers.py in _item_to_row(iterator, resource)
    335     from google.cloud.bigquery import Row
    336 
--> 337     return Row(_row_tuple_from_json(resource, iterator.schema),
    338                iterator._field_to_index)
    339 

/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/_helpers.py in _row_tuple_from_json(row, schema)
    198     row_data = []
    199     for field, cell in zip(schema, row['f']):
--> 200         converter = _CELLDATA_FROM_JSON[field.field_type]
    201         if field.mode == 'REPEATED':
    202             row_data.append([converter(item['v'], field)

**KeyError: 'NUMERIC'**

**Comment by tompollard** [comment]
Thanks, I have converted numeric columns to floats in the following tables on the mimiciii_derived database: `heightfirstday`, `heightweight`, `meld`, `weightdurations`, `weightfirstday`. Please could you check whether you can run the original query without casting the data type?

**Comment by christinium** [comment]
**Code in colab now works:**
df_noteevents_categories = run_query('''
SELECT *
FROM physionet-data.mimiciii_derived.heightweight;
''')

Thanks!
