### ISSUE TITLE
Error with postgres_checks

### ISSUE THREAD

**Issue by GoodMatthias** [MIT-LCP/mimic-code#483]
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

I have troubles while following the online documentaion for building the database. "postgres_load_data.sql" seems to have succesfully worked since selecting from the icustays didn't gave back any errors. 
To double check, I tried running the "postgres_check.sql" script and got back the following error, which translates to 
"ERROR: invalid page on block 28419 form relation base/16393/16426"

![mimic sql error](https://user-images.githubusercontent.com/44050755/46794932-3167e800-cd49-11e8-84e7-58240b6c751f.png)

I'm running PostgreSQL on a windows 10 64bit machine and didn't find the issue in the forum. 

I'm not sure it's related but I did also get a error message while adding indexes, which stated the following, in my own translation:
"ERROR: MultiXactId 911379 wasn't created yet -- apparent overflow"

Thanks in advance for any help!

**Comment by alistairewj** [comment]
That is a very unusual database error - I don't think it's specific to MIMIC data. Maybe you ran out of hard drive space? It sounds like the database is corrupted in some way. If you open the postgres_checks.sql file you can see it just runs a simple query against known constants. I'd try making sure you have ~100 GB of space free, and reinstalling postgres/reinstalling the data.

**Comment by GoodMatthias** [comment]
Thank you for you answer! I actually did reinstall the postgres and the data which solved the issue. No idea what caused it in the first place since I had enough hard drive space.
