### ISSUE TITLE
Creatinine Stage 3 not exactly as in KDIGO criteria

### ISSUE THREAD

**Issue by steph409** [MIT-LCP/mimic-code#484]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

I found a difference in the implementation of the KDIGO criteria (in my understanding of the guideline). 
For stage 3 creatinine, you say in [mimic-kdigo-code](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/organfailure/kdigo-stages-7day.sql), line 60: 

`when HighCreat7day >= (LowCreat7day*3.0) then 3
    when HighCreat7day >= 4 -- note the criteria specify an INCREASE to >=4
      and LowCreat7day <= (3.7)  then 3 -- therefore we check that adm <= 3.7
-- TODO: initiation of RRT`

[kdigo-guideline](https://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf), page 24: increase of 0.5 (so the above should check for <=3.5. 

Is there a medical reason or implementation error? :)

is there a medical reason you implemented the following threshold for KDIGO

**Comment by JackieMium** [comment]
I think you are looking the the wrong place.  Here is a snapshot of the pdf at page 8:

![screenshot_2018-10-14_21-29-13](https://user-images.githubusercontent.com/12944832/46917331-72395880-cff8-11e8-912f-fe3aeaafd5b2.png)

As you can see, the code you pasted is trying to do the 2 items in the red rectangle in this picture.

**Comment by steph409** [comment]
Hi, 
no I only mean the second part of what you highlighted:

> Increase in serum creatinine to >=4.0. 

In the code I cited you can see that the `LowCreat7day` has to be below 3.7. On page 21 of the document I sent, it says that there has to be an increase of at least 0.5, so the code should check for `LowCreat7day` below 3.5. 

It just depends on how you define `increase`

![image](https://user-images.githubusercontent.com/33083326/46917946-37083c80-cf9a-11e8-90ff-d87d181bd1b3.png)

**Comment by JackieMium** [comment]
OK, my bad. I didn't realize you were refering to the 2nd line. 
Yes, I agree with you, I think it should be 4-0.5=3.5.

Let's just paste it like this foe a clearer look
```sql
 , case
    when HighCreat7day >= (LowCreat7day*3.0) then 3
    when HighCreat7day >= 4 -- note the criteria specify an INCREASE to >=4
      and LowCreat7day <= (3.7)  then 3 -- therefore we check that adm <= 3.7
    -- TODO: initiation of RRT
```

**Comment by chris20881** [comment]
Hi, just having a look at this. I think a change is needed, but a different one.
The AKI criteria above from page 21 of KDIGO are referring to the Acute Kidney Injury Network AKI criteria rather than KDIGO. KDIGO discuss this point lower down the page:

![image](https://user-images.githubusercontent.com/27828900/47319316-3df01880-d646-11e8-9314-f2b021ba8d3b.png)

So I think 3.7 is correct, but it should be over 48 hours rather than 7 days, and needs the 1.5 x criteria adding. Unfortunately my coding is not up to suggesting how to do this ...

**Comment by alistairewj** [comment]
Why is it wrong?

**Comment by hlblade** [comment]
Thanks for you swift reply. But should a patient whose cr decreased from 1.1 to 0.69 in 24h be thought as undergoing kidney function injury?

**Comment by alistairewj** [comment]
That would indicate that they are recovering from kidney injury in my books.

**Comment by hlblade** [comment]
Ok, maybe. But it's not a criteria to diagnosis AKI based on the KIDGO guideline.

**Comment by alistairewj** [comment]
It is! It all depends on how you define the patient's baseline, which is admittedly contentious. We don't have perfect knowledge of the patient's history, and in the case you propose it's reasonable to assert that the patient's baseline is not 1.1 but somewhere closer to 0.7. If you want to make a different assumption regarding the patient's baseline you are welcome to.

**Comment by hlblade** [comment]
Very inspiring idea, thanks. 
By the way, is it possible to find more detail information about the surgery patient underwent, like the cpb time of cardiac surgery?
