### ISSUE TITLE
Question about units of itemid 225947 225948 and 225969

### ISSUE THREAD

**Issue by JackieMium** [MIT-LCP/mimic-code#485]
In the `inputevents_mv`, three items has different units between `amountuom` and `totalamountuom`.

`select * from d_items where itemid in (225947, 225948, 225969);` ouputs:
```
 row_id | itemid |       label       |   abbreviation    |  dbsource  |    linksto     |        category        | unitname | param_type | conceptid 
--------+--------+-------------------+-------------------+------------+----------------+------------------------+----------+------------+-----------
  14378 | 225947 | Dextrose PN       | Dextrose PN       | metavision | inputevents_mv | Nutrition - Parenteral | grams    | Solution   |          
  14379 | 225948 | Amino Acids       | Amino Acids       | metavision | inputevents_mv | Nutrition - Parenteral | grams    | Solution   |          
  14219 | 225969 | Lipids (additive) | Lipids (additive) | metavision | inputevents_mv | Nutrition - Parenteral | grams    | Solution   |
```

And now let's look at entries in `inputevents_mv`:
`select distinct itemid, amountuom, totalamountuom from inputevents_mv where itemid in (225947, 225948, 225969);` outputs this:
```
 itemid | amountuom | totalamountuom 
--------+-----------+----------------
 225948 | dose      | ml
 225948 | grams     | ml
 225947 | grams     | ml
 225969 | grams     | ml
```

Why do the amount and totalamount have different units?

**Comment by alistairewj** [comment]
`totalamountuom` in hind sight has a misleading name - it's the total volume left in the bag which is delivering the compound. I think I renamed it to amount for consistency but then realized later that `volume` would have been a better word. Description is here: https://mimic.physionet.org/mimictables/inputevents_mv/#totalamount-totalamountuom

**Comment by JackieMium** [comment]
thanks for you answer!
