### ISSUE TITLE
Venous blood gas analysis?

### ISSUE THREAD

**Issue by corcra** [MIT-LCP/mimic-code#488]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Is there any way to differentiate between arterial and venous blood samples for blood gas analysis? I'm specifically interested in venous lactate, which I haven't been able to find.

**Comment by alistairewj** [comment]
Might be that it's not routinely measured. The way to identify blood gas type is to look for the `itemid` for specimen (`50800`), pivot the table on `charttime`, and subselect to `charttime` where the specimen column is VEN.

This is already done in the pivoted-bg and the blood-gas-first-day-arterial queries - you'd just need to change `ART` to `VEN`. I've never looked for venous lactate though. Also worth noting there are some blood gases with no label unfortunately (data quality issues!), so the query has a model which estimates whether the sample is arterial or venous. Up to you whether you use that.
