### ISSUE TITLE
What does *NF* stand for in prescription drug name?

### ISSUE THREAD

**Issue by topspinj** [MIT-LCP/mimic-code#490]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

When I query the prescriptions table, there are quite a few drug names prepended with `*NF*`. Does anyone happen to know what this acronym means? 

You can see a list of drugs that have this prefix with the following query:

```
SELECT DISTINCT drug FROM mimiciii.prescriptions WHERE drug LIKE '*NF*%';
```

I was thinking either `National Formulary` or `No Fault`, but would like to confirm.

**Note:**
Same question applies to drugs prepended with `*IND*`. Does this stand for "Investigational New Drug"?

**Comment by alistairewj** [comment]
You're probably right about `National Formulary` but I sent an e-mail to some BIDMC colleagues to check.

For *IND* it only happens for one drug name (`*IND* Pexelizumab/Placebo`). For this drug, another column lists it as `Pexelizumab/Placebo Study Drug`, so you're probably right there too.

**Comment by alistairewj** [comment]
I stand corrected! Quoting a pharmacist at the BIDMC (the source hospital of MIMIC):

> NF means non formulary 
> Aka not approved by P&T as part of our formulary meds. We sometimes have a limited supply of non formulary medications that we dispense depending on the circumstance.

**Comment by topspinj** [comment]
Thank you! This is very helpful.
