### ISSUE TITLE
Could not stat file chartevents.csv unknown error

### ISSUE THREAD

**Issue by Lejla1979** [MIT-LCP/mimic-code#493]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### 
When I run Postgres_load_data script, first three table are loaded and after that I got message: could not stat file CHARTEVENTS.csv: unknown error. Is anyone has this situation and can help.

**Comment by tompollard** [comment]
Have you checked the integrity of your copy of `chartevents.csv` using the checksum files provided on the download page for the project? Perhaps it was corrupted during download or decompression.

**Comment by Lejla1979** [comment]
Yes, I used command md5 checksum_md5_zipped.txt and everything is OK with all tables...

**Comment by alistairewj** [comment]
It sounds as though there is a mismatch between the script you're running and the data you have. I'd make sure:

1. All of the files are in the same directory
2. All of the files have the same file extension; e.g. they are all `.csv.gz`
3. You are running the postgres_load_data_7zip.sql file either (i) from the same folder or (ii) after configuring the mimic_data_dir to point to the data directory.

Past that it's really hard to debug remotely without more info like a screenshot of your folder setup, your system information, the exact commands you ran and the exact error message.

**Comment by Lejla1979** [comment]
Hello,

Thank you for your answer.
1. All files are in the same directory
2. All files have the same file extension csv
3. I am running the posgres_load_data.sql file after configuring the mimic_data_dir to point to the data directory.
Here si my exact commands and error I got. 
![step1](https://user-images.githubusercontent.com/44549848/47797679-10caf680-dd27-11e8-964d-8b9b5f52eb7d.png)
![step2](https://user-images.githubusercontent.com/44549848/47797700-1c1e2200-dd27-11e8-848b-6da536018b11.png)
![system_information](https://user-images.githubusercontent.com/44549848/47797778-466fdf80-dd27-11e8-9d7e-25c5f2b19dde.png)

**Comment by alistairewj** [comment]
Great that's very helpful, thanks for the additional info. I think it's as simple as the file not being in the folder. Can you double check that your folder `C:/Users/Lejla/Desktop/MIMICIII` has the `CHARTEVENTS.csv` file?

It may be that you tried to extract all the compressed files, but it failed for chartevents and so you only have a `.csv.gz` file (reasons could be because the extracted file is 33GB and you ran out of space, or your file system is FAT32 (!), or who knows). In that case, you may want to edit the load script to load it directly from `.csv.gz`. You can do that by replacing:

> `\copy CHARTEVENTS from 'CHARTEVENTS.csv' delimiter ',' csv header NULL ''`

with

> `\copy CHARTEVENTS from PROGRAM '7z e -so CHARTEVENTS.csv.gz' delimiter ',' csv header NULL ''`

**Comment by alistairewj** [comment]
Can you show the contents of the directory?

**Comment by Lejla1979** [comment]
I do not mind.here is content of my folder
![directory](https://user-images.githubusercontent.com/44549848/47816366-438ae400-dd53-11e8-89dc-9918cc37d1a4.png)

**Comment by alistairewj** [comment]
Okay, this is actually a bug in PostgreSQL 11. Under the hood it makes a call to `fstat()` to make sure the file is not a directory, and unfortunately `fstat()` is a 32-bit program which can't handle large files like chartevents. I tested the build on Windows with PostgreSQL 10.5 and I didn't get this error so I think it's fairly new.

The best workaround is to keep the files compressed (i.e. keep them as `.csv.gz` files) and use 7zip to load in the data directly from compressed files. In testing this seemed to still work. There is a pretty detailed tutorial on how to do this here: https://mimic.physionet.org/tutorials/install-mimic-locally-windows/

The brief version of above is that you keep the `.csv.gz` files, you add the 7zip binary to your windows environment path, and then you call the `postgres_load_data_7zip.sql` file to load in the data. You can use the `postgres_checks.sql` file after everything to make sure you loaded in all the data correctly.

**Comment by Lejla1979** [comment]
Hello, 
Thank you for detail explanation. I installed PostgreSQL 10.5 and now process is running. I think it will take a lot of time to load all table but I do not get "Unknown error" anymore. Thank you very much for all help.

**Comment by najam2012** [comment]
> Okay, the `could not stat file "CHARTEVENTS.csv": Unknown error` is actually a bug in PostgreSQL 11. Under the hood it makes a call to `fstat()` to make sure the file is not a directory, and unfortunately `fstat()` is a 32-bit program which can't handle large files like chartevents. I tested the build on Windows with PostgreSQL 10.5 and I didn't get this error so I think it's fairly new.
> 
> The best workaround is to keep the files compressed (i.e. keep them as `.csv.gz` files) and use 7zip to load in the data directly from compressed files. In testing this seemed to still work. There is a pretty detailed tutorial on how to do this here: https://mimic.physionet.org/tutorials/install-mimic-locally-windows/
> 
> The brief version of above is that you keep the `.csv.gz` files, you add the 7zip binary to your windows environment path, and then you call the `postgres_load_data_7zip.sql` file to load in the data. You can use the `postgres_checks.sql` file after everything to make sure you loaded in all the data correctly.
> 
> edit: For your later error, where you are using this 7zip approach, I'm not sure why it's not loading. Try redownloading just the ADMISSIONS.csv.gz file and seeing if it still throws you that same error. Maybe there is a new version of 7zip which requires me to update the script or something!

Using PostgreSQL 10.11 helped me... thanks

**Comment by hmmalafaia** [comment]
> Great that's very helpful, thanks for the additional info. I think it's as simple as the file not being in the folder. Can you double check that your folder `C:/Users/Lejla/Desktop/MIMICIII` has the `CHARTEVENTS.csv` file?
> 
> It may be that you tried to extract all the compressed files, but it failed for chartevents and so you only have a `.csv.gz` file (reasons could be because the extracted file is 33GB and you ran out of space, or your file system is FAT32 (!), or who knows). In that case, you may want to edit the load script to load it directly from `.csv.gz`. You can do that by replacing:
> 
> > `\copy CHARTEVENTS from 'CHARTEVENTS.csv' delimiter ',' csv header NULL ''`
> 
> with
> 
> > `\copy CHARTEVENTS from PROGRAM '7z e -so CHARTEVENTS.csv.gz' delimiter ',' csv header NULL ''`

Thanks, this worked for me:
\copy my_table_name from program 'cmd /c type input_data.csv' delimiter ',' csv header;
input_data.csv like 11GB size.

**Comment by ghYura** [comment]
The issue with "can't copy large files" is up for 11 and 12 versions. But for 10 is ok. How to override it without compressing of a data-files, but maybe to upsert/swap some Postgresql-program files from v.10 to v 11 and 12?

**Comment by alistairewj** [comment]
You could consider using other command line tools to split the file into multiple files, and then loading the individual files one at a time. On unix systems this can be done using `split` and you could install the GNU coreutils for Windows to use it.

**Comment by islandmao** [comment]
I think I have encountered the same problem as you, but I am using the very new version 12. Is there any way to solve it? Use compressed files?

**Comment by alistairewj** [comment]
Yes, if I recall correctly the compressed files are < 4 GB and you avoid this error by using the compressed load scripts (7z or gzip).

**Comment by islandmao** [comment]
OK, I will try this method now, thank you very very much for your reply

**Comment by ghYura** [comment]
So, no workaround WITHOUT using compressing or splitting at all? Usage of 10's version of COPY command of Postgresql for 11, 12 engine?
As I mentioned: 
I need speed of default Copy command
and this is vital for my needs.

**Comment by alistairewj** [comment]
Well, PostgreSQL is open source, so you're welcome to try and contribute a fix yourself :)

Here is the relevant discussion: https://www.postgresql.org/message-id/20181104000405.GA1743%40paquier.xyz

Otherwise you have the three workarounds proposed in this thread (change version, use compressed files, split the file into multiple parts). I'm sure there are other workarounds too.

**Comment by ghYura** [comment]
In't it obvious to migrate working part of the code of v. 10's of COPY functionality into 11 and 12? Or it is so hardcoded, that cause crash for all? :)

**Comment by tompollard** [comment]
@ghYura this is a community maintained resource, so if you have suggestions for improving the codebase then I'd suggest making a pull request.

**Comment by Ashutosh27ind** [comment]
I was getting the error while loading the CSVs into the tables in both the 12.X and 13.X versions but it works like a charm in the PostgreSQL version 10.15. Thanks, everyone for the help :)

**Comment by Dimas17051999** [comment]
Thank u everyone. I face the same problem but it works really great with Postgres 10.5.
