### ISSUE TITLE
Low resolution of creatinine (labevents). Only one decimal available.

### ISSUE THREAD

**Issue by JohannesNE** [MIT-LCP/mimic-code#494]
Creatinine measurements are only available with 1 decimal. This is quite low for a labtest with a normal range of 0.6 to 1.2 mg/dl. Other lab values are also rounded to one decimal, but the problem is of cause most noticeable in tests with low normal values.

I suppose this is due to rounding during the preprocessing of the data. If it is within your control, I suppose increasing the resolution for all or some labevent valuenums. Maybe by number of significant digits instead of decimals.

**Comment by alistairewj** [comment]
Unfortunately, in the original data, creatinine is archived with only one decimal place. I don't think we can do anything to fix this. We very much avoided preprocessing anything for exactly the reasons you state - with medical data you never know when a seemingly innocuous preprocessing step ends up causing downstream issues in a study!

If I recall correctly @pszolovits and his team have done some work in analyzing how the low resolution of creatinine drops useful predictive information, but I'll let him comment on that. With the recent release of eICU-CRD, this might make for an interesting study!

**Comment by pszolovits** [comment]
Yes, the single-digit precision of creatinine is a problem because definitions of things like AKI are quite sensitive to smaller variations. We built some predictive models that did poorly, probably at least in part due to lack of resolution.

**Comment by lceli** [comment]
Given the accuracy of existing assays, clinicians won't complain when a serum creatinine of 1.14 is rounded to 1.1 and a serum creatinine of 1.16 is rounded to 1.2. Trends are more meaningful rather than absolute values.

**Comment by JohannesNE** [comment]
Thanks a lot for the replies. @lceli you are right, that the problem it not that big in practice, specific levels and minimal changes are probably not important. The main problem is probably the KDIGO AKI criterion 'increase in SCr by ≥ 0.3 mg/dl', which with only .1 percesion ends up being ≥ 0.2-0.4 mg/dl.

... also, plots, especially of relative SCr increase, looks quite funky because of the grouping.
