### ISSUE TITLE
Base Excess Itemid 

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#495]
I am trying to figure out how to find "Base Excess" values for a patient . 
In d_labitems , itemid 50802 has been given which links to labevents table . 
Also in d_items itemid : 79 and 4196 are present which link to chartevents table .

Which of these should be considered ?

**Comment by alistairewj** [comment]
For laboratory data, you should always use the labevents table. In the documentation https://mimic.physionet.org/mimictables/labevents/

> Some items are duplicated between the labevents and chartevents tables. In cases where there is disagreement between measurements, labevents should be taken as the ground truth.

Essentially, the database source for labevents pushes its data into chartevents so you should always be using labevents. It's also much easier to work with!

Note this doesn't hold for lab-like values which are measured at the bedside (e.g. fingerstick glucose), as these are only ever documented in chartevents.

**Comment by kumarishikha** [comment]
> Essentially, the database source for labevents pushes its data into chartevents so you should always be using labevents. It's also much easier to work with!

So , for a given concept , if I only pull values from labevents (and not also from chartevents and create a join) , I would not be missing any readings , right ?

**Comment by alistairewj** [comment]
Never say never :)

If you are pulling data which is processed by the laboratory and the results sent back to the ICU, then you should not miss any readings using the labevents table.

**Comment by kumarishikha** [comment]
Just a comment, in case someone checks this issue for a similar confusion :

Running following 2 queries :
select itemid , charttime , storetime ,valuenum , valueuom from chartevents where hadm_id = 100011 and itemid in (1126, 223830, 4753, 780) 
order by charttime

select charttime  , valuenum , valueuom from labevents where itemid = 50820 and hadm_id = 100011 order by charttime

we can observe that the difference between the charttimes in labevents and chartevents is around  1 hour . 

To avoid such discrepancies and get the "true" time for an event , I assume its always a better option to consider the labevents data wherever possible .

**Comment by alistairewj** [comment]
This shouldn't happen and was a bug that I thought we had fixed in a
previous version but maybe not. Will investigate internally and fix for the
next release. Using labevents in the mean time is sensible.
