### ISSUE TITLE
Timing, sites and sizes of tumors and metastases

### ISSUE THREAD

**Issue by MaxFecke** [MIT-LCP/mimic-code#498]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello,

I am trying to train a classifier to predict courses of disease for lung cancer patients. It would therefore be great if I could extract information like for example “WHEN did tumors and metastases show up WHERE and WHAT SIZE were they?”. 
Unfortunately, I have only been able to obtain the WHERE information from the diagnoses_icd table. Is there any way to extract the other information as well? There must be results from MRI scans and CT scans hidden somewhere, right?

Thank you very much!
Max

**Comment by alistairewj** [comment]
There are radiology reports which would have this information if the scan was done in the hospital - but it's free text and may not exhaustively cover all scans the patient had.

**Comment by MaxFecke** [comment]
So the only way to extract these data is to apply NLP to the text fields in the NOTEEVENTS table. Quite frustrating but thank you for your quick answer!
