### ISSUE TITLE
Co2 Data?

### ISSUE THREAD

**Issue by OssamaMahmoud** [MIT-LCP/mimic-code#500]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
I was wondering if the MIMIC dataset contains any waveforms for CO2. 
* what you have tried
It was mentioned in the MIMIC-II waveform documentation that CO2 values are collected 1 sample/min or 1 sample/sec (See attached image).
I tried to go through some of the waveform data to find any CO2 measurements but have failed to do so. 

If possible can someone confirm the availability of the CO2 measurements, and shed some light on how to identify the records with CO2 measurements? 

Thanks,
Ossama

**Comment by alistairewj** [comment]
For questions like these, your best bet is the PhysioNet search tool: https://physionet.org/cgi-bin/pbs/pbsearch

There is a guide here: https://physionet.org/physiobank/database/pbi/

Below you can see an example of me (A) identifying signals with CO2, (B) looking for records with a name similar to mimic3wdb, and finally (C) doing the union of B and A to get records with CO2 in mimic3wdb.

![image](https://user-images.githubusercontent.com/1282676/48221921-54de7c80-e361-11e8-9396-a5f92677b779.png)
