### ISSUE TITLE
Item ids for Plateau Pressure

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#502]
Referring to https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/ventilation-durations.sql
itemid 543 (dbsource carevue) is considered for PlateauPressure .

When I check the database , itemid 224696(dbsource metavision) is also present . There are  75376 non null entries in the chartevents table corresponding to this itemid .

Any specific reason why this was not considered ?

**Comment by alistairewj** [comment]
No specific reason, might be a worthwhile addition though it's unlikely to change the end result.
