### ISSUE TITLE
Height value conversion

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#506]
This is in reference to below mentioned script : 
https://github.com/MIT-LCP/mimic-code/blob/master/concepts/demographics/HeightWeightQuery.sql

> -- note we intentionally ignore the below ITEMIDs in metavision
    -- these are duplicate data in a different unit
    -- , 226531 -- Admission Weight (lbs.)
    -- , 226707 -- Height (inches)

My understanding is that 226707 (in inches) is a duplicate of 226730 (cm). If we want to ignore 226707 , then should we not include 226730 ? Then we wont have to deal with conversion of values obtained from 226707 .

**Comment by alistairewj** [comment]
Yeah the comment has the right idea but mixed up the units. The code ignores 'cm' and only keeps heights in inches. I just fixed the comments (code logic itself is unchanged).
