### ISSUE TITLE
Variable ranges

### ISSUE THREAD

**Issue by OluOrojo** [MIT-LCP/mimic-code#507]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

I am currently working on a subset of the medical data (MIMIC III) and would like to know if you have the average normal ranges for the variables used in the database. For clarity, the ranges I am referring to are the normal ranges (that is for patients not in ICU), for example, the normal range for temperature is 97°F (36.1°C) to 99°F (37.2°C). 
> 
> I am unable to obtain reliable ranges for all the variables from one source and I am hoping to obtain the ranges directly from your team as you are the source of the data and this reduces any discrepancies.

**Comment by tompollard** [comment]
Response posted at: https://github.com/YerevaNN/mimic3-benchmarks/issues/63
