### ISSUE TITLE
Units for central venous pressure

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#508]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
For "Central Venous Pressure" , I understand that the itemid = 113, 220074 should be considered .
For itemid = 113 , I notice that units null, % and mmHg have been reported . 
I understand null an be disregarded since only 6 not null records exist with null as unit .
But for unit '%' , 23386 not null records exits .
Could someone explain if this is a typo ?
Or if '%'is intended to be the unit , then what is this '%' wrt to ? [Or how to convert it to mmHg]

**Comment by alistairewj** [comment]
Not sure, seems like the unit may be stored incorrectly. What's the distribution like?

**Comment by kumarishikha** [comment]
The distribution looks fairly normal (frequency vs value histogram) .

**Comment by kumarishikha** [comment]
![unit_mmhg](https://user-images.githubusercontent.com/41427179/52411015-973b6500-2ada-11e9-838a-916bb63e4b06.png)

seaborn distplot of values with unit mmHg

**Comment by kumarishikha** [comment]
![unitpercent](https://user-images.githubusercontent.com/41427179/52411042-a91d0800-2ada-11e9-9923-03a7611c1326.png)

seaborn distplot of values with unit %

**Comment by kumarishikha** [comment]
x axis is the values (valuenum) and y axis is the relative frequency .

Query run : 
First plot : select valuenum from chartevents where itemid =113 and valuenum is not null and valueuom = 'mmHg' 
second plot : select valuenum from chartevents where itemid =113 and valuenum is not null and valueuom = '%'

**Comment by alistairewj** [comment]
Seems reasonable!

**Comment by cassandra2010** [comment]
> Seems reasonable!

So, I guess I can assume the records with unit '%' are same as unit 'mmHg', and that '%' is a typo? (since the magnitude of values does not seem to vary across the units).

**Comment by kumarishikha** [comment]
> Seems reasonable!

So, I guess I can assume the records with unit '%' are same as unit 'mmHg', and that '%' is a typo? (since the magnitude of values does not seem to vary across the units).

**Comment by alistairewj** [comment]
Yep!
