### ISSUE TITLE
LANGUAGE abbreviations in ADMISSIONS Table

### ISSUE THREAD

**Issue by sleeprchill** [MIT-LCP/mimic-code#509]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello,
I am looking into using demographic data to predict outcomes for different cerebrovascular diseases. One of the categories I'd like to use is the LANGUAGE attribute in the ADMISSIONS table. Is there anywhere that I could get a definitive definition of each language abbreviation?
Thank you

**Comment by alistairewj** [comment]
There's no public list but they are pretty easy to infer (ENGL -> English).
If you make a list we'd be happy to put it on the website/code repository!

**Comment by sleeprchill** [comment]
Thank you! I'll be sure to do so.

Maya Reed McDaniel
Programmer Analyst, Center for Computational Research
University at Buffalo, SUNY
701 Ellicott St.
Buffalo, NY 14203
mayamcda@buffalo.edu
