### ISSUE TITLE
Question about extracting medication data

### ISSUE THREAD

**Issue by JackieMium** [MIT-LCP/mimic-code#510]
I am trying to look more into 1st-day medication administration in mimic iii the data. Some questions haunts me however:

1. Should I only use records from `inputevents_cv` and `inputevents_mv` and ignore those in `chartevents`? Is there some specific reasons for that? I am asking this because when I was reading the `xxxx-durations.sql` files in [`mimic-code/concepts/durations/`](https://github.com/MIT-LCP/mimic-code/tree/master/concepts/durations), most of them used data from  `inputevents_cv` and `inputevents_mv`, though `adenosine-durations.sql` seemed to include data from `chartevents`. I've also found codes written by others that used data from  `inputevents_cv` and `inputevents_mv` only, although there are lots of data records in `chartevents` too.

2. When I am looking for `itemid` for medication administration records in `d_items`, I've found entries like:

```
 row_id | itemid |          label          |      abbreviation       |  dbsource  |    linksto     |     category     | unitname | param_type | conceptid 
--------+--------+-------------------------+-------------------------+------------+----------------+------------------+----------+------------+-----------
   3555 |   2443 | PROTONIX DRIP           |                         | carevue    | chartevents    |                  |          |            |          
   4562 |   7221 | Protonix       mg/hr    |                         | carevue    | chartevents    |                  |          |            |          
   4634 |   7389 | protonix 80mg/250cc     |                         | carevue    | chartevents    |                  |          |            |          
   5721 |  40549 | protonix                |                         | carevue    | inputevents_cv | Free Form Intake |          |            |          
   4804 |   7814 | PROTONIX 80MG/250       |                         | carevue    | chartevents    |                  |          |            |          
   4210 |   6449 | PROTONIX MG/HOUR        |                         | carevue    | chartevents    |                  |          |            |          
   6120 |  41525 | PROTONIX MG/HR          |                         | carevue    | inputevents_cv | Free Form Intake |          |            |          
   6132 |  41537 | iv protonix             |                         | carevue    | inputevents_cv | Free Form Intake |          |            |          
   6845 |  41101 | Protonix                |                         | carevue    | inputevents_cv | Free Form Intake |          |            |       
  11598 |  42285 | PROTONIX DRIP           |                         | carevue    | inputevents_cv | Free Form Intake |          |            |          
  14063 | 225910 | Pantoprazole (Protonix) | Pantoprazole (Protonix) | metavision | inputevents_mv | Medications      | dose     | Solution   |  
```
there are records from both  `chartevents` and  `inputevents_cv`, which was mentoined above. However, I further found that there are entries with `category` as `Free Form Intake`, `Medications` or `null`, for which there are data records accrodingly. So what does `category`  really mean? Do I have to consider this column if I am to pick specific `itemid` for medication administration data? Or more precisely, should I 
take into account entries with `null` and `Free Form Intake` in `category` column?

3. When I am looking at data in `chartevents` with `itemid = 3394` which is 'Diuril' according to `d_items` I found this:

```
  row_id   | subject_id | hadm_id | icustay_id | itemid |      charttime      |      storetime      | cgid  |  value  | valuenum | valueuom | warning | error | resultstatus | stopped  
-----------+------------+---------+------------+--------+---------------------+---------------------+-------+---------+----------+----------+---------+-------+--------------+----------
  34639979 |         93 |  160481 |     242398 |   3394 | 2128-05-17 21:00:00 | 2128-05-17 20:51:00 | 19296 | Given   |          |          |         |       |              | NotStopd
  34635535 |         93 |  160481 |     242398 |   3394 | 2128-05-09 09:30:00 | 2128-05-09 09:50:00 | 15064 | Given   |          |          |         |       |              | NotStopd
  35155193 |        159 |  156461 |     259440 |   3394 | 2152-08-27 18:00:00 | 2152-08-27 17:37:00 | 17949 |         |          |          |         |       |              | NotStopd
  37547924 |        610 |  130411 |     219847 |   3394 | 2133-01-28 05:00:00 | 2133-01-28 06:05:00 | 18869 | Held    |          |          |         |       |              | NotStopd
  37545679 |        610 |  130411 |     219847 |   3394 | 2133-01-22 05:00:00 | 2133-01-22 05:49:00 | 18869 | Given   |          |          |         |       |              | NotStopd
  45392791 |       2160 |  108050 |     292563 |   3394 | 2128-12-08 16:00:00 | 2128-12-08 16:00:00 | 21570 |   |          |          |         |       |              | D/C'd
```
the `value` column and `stopped` column are really confusing here. As far as I can see, `Given` means the drug was given to the patients, `Held` means is temporarily held for some reason but not stopped, and `D/C'd` in `stopped` column means the medication was stopped. Am I understanding this correctly? I can also see some entries for other drugs with `Given`/`Held` for `value` and `D/C'd` for `stopped`. But then of course, if I don't need to consider data in `chartevents` as mentioned in question 1, maybe question 3 is answered by myself. Because I currently only find `Given`/`Held` in `value`  column in  `chartevents` but not in  `inputevents_cv` or `inputevents_mv`.

**Comment by alistairewj** [comment]
1. As you can see, I've mostly chosen to only use the input tables. These correspond to an input/output tab on the front end and is where IV infusions should be documented. Of course as you see, primarily for CareVue data, it is sometimes documented in chartevents. If you count the number of observations you'll see that most of the time it's rare for drugs to be documented in chartevents rather than an inputevents table. The drugs you are looking at may be different; this is just what I found with vasopressors, etc.
2. Category is very well populated for MetaVision data and almost never populated for CareVue data. I tend to use it to find MetaVision ITEMID and then expand my search to CareVue by looking for the same labels. I would not filter out data because of a null category.
3. The stopped column is a handy way for caregivers to indicate a drug is stopped but its use varies across caregivers. It makes a lot more sense for continuous infusions rather than one off adminostrations. You can see I've used the column in the durations table to indicate a continuous infusion has finished. Up to you whether you need this information. Your interpretation seems valid.

**Comment by JackieMium** [comment]
Great! thanks for you explanation, Alistair.
