### ISSUE TITLE
help getting the database running

### ISSUE THREAD

**Issue by djb218** [MIT-LCP/mimic-code#512]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

Hi guys,

Sorry to bother. I’m a clinician trying to work with this data and so I am a bit of a novice- apologies.

So far I have done all the preliminary steps, installed postgres and downloaded the data using this link: wget --user djb218@stanford.edu --ask-password -A csv.gz -m -p -E -k -K -np -nd https://physionet.org/works/MIMICIIIClinicalDatabase/files/

Now when I try to create a user or connect to the database with psql it asks for a password, and nothing I seem to enter works (steps 3 and 4 here- https://mimic.physionet.org/tutorials/install-mimic-locally-ubuntu/) . Can you guys help?

I’ve also tried the instructions from the following github page (https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/postgres) but no luck either.

I’m pretty stuck, so if anyone could advise that would be great.

Kind regards,

David Bell
![screen shot 2018-12-25 at 8 59 05 am](https://user-images.githubusercontent.com/46113913/50425041-11ae6f00-0824-11e9-8949-4ff4946c39a8.png)

**Comment by djb218** [comment]
I’m also having trouble with the ‘make’ system guys. Does anyone know why I would be getting the message below= ‘no rule to make target ‘mimic’?

https://github.com/MIT-LCP/mimic-code/blob/master/Makefile.md


 
![screen shot 2018-12-26 at 7 46 21 am](https://user-images.githubusercontent.com/46113913/50450452-04a48500-08e3-11e9-9022-cd7835f6c53c.png)

**Comment by mostafaalishahi** [comment]
could you please check if you're in the right directory (the directory
which mimic and mimic-download exist) when you execute make

regards,
Mostafa

**Comment by djb218** [comment]
Thanks a lot Mostafa. I believe I am. 

I have redownloaded Postgres and the data using wget --user djb218@stanford.edu --ask-password -A csv.gz -m -p -E -k -K -np -nd https://physionet.org/works/MIMICIIIClinicalDatabase/files/ (although I am not sure where it lives) so I have also downloaded the files to my desktop.

I still get stuck when I try to create a mimic user (davidbell for me) with createuser -P -s -e -d mimicuser. It asks for a password and I've tried my mimic password and my computer password but get this message with both: createuser: could not connect to database postgres: FATAL:  password authentication failed for user "davidbell"

See below. Any thoughts?

Dave
![screen shot 2018-12-27 at 1 00 30 pm](https://user-images.githubusercontent.com/46113913/50494339-81189000-09d7-11e9-8264-83c023725550.png)

**Comment by xydo1990** [comment]
Like Mostafa said, 
assuming that you cloned the github code as described in https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/README.md: 
The "ls" command should return a list of files of the current folder, including "create_mimic_user.sh" and the "Makefile". 
Sorry for the repost, hope it helps.

**Comment by djb218** [comment]
Thanks a lot for your help Mostafa and xydo1990! One last question...

The tables haven't quite downloaded completely. D_ICD_Diagnoses and noteevents haven't seem to download despite it being in the same directory and I downloaded chart events twice. I've tried redownloading and creating another file to download d_icd_diagnoses, but no luck. Any tips on how to add this in?
![screen shot 2018-12-29 at 8 10 58 am](https://user-images.githubusercontent.com/46113913/50541282-fc548000-0b56-11e9-8489-1489c48aa91e.png)
![screen shot 2018-12-29 at 8 10 44 am](https://user-images.githubusercontent.com/46113913/50541284-08d8d880-0b57-11e9-91fd-9664a7d82a84.png)



Dave.

**Comment by mostafaalishahi** [comment]
You're welcome Dave,
It seems everything goes well, but as you mentioned the reason that you get
failed for CHARTEVENTS table is that you have downloaded it twice and if
you pay attention to the number of observed records for CHARTEVENTS table
is twice as it should be, as well for the D_ICD_DIAGNOSES you have zero
records as you could not download it but in the case of NOTEEVENTS table
you have downloaded it partially and you have a non-zero number of records.

I would recommend you to delete the csv.gz files of the above-mentioned
tables and redownload them using:

wget --user YOURUSERNAME --ask-password -A csv.gz -m -p -E -k -K -np -nd
https://physionet.org/works/MIMICIIIClinicalDatabase/files/version_1_4/D_ICD_DIAGNOSES.csv.gz

replace D_ICD_DIAGNOSES with CHARTEVENTS.csv.gz and NOTEEVENTS.csv.gz for
the other two tables.

Regards,
Mostafa

**Comment by djb218** [comment]
Thanks a lot Mostafa,

Now I'm trying to run the queries and not having much luck.

I'm pretty sure I have an active connection to an instance of MIMIC-III running on PostgreSQL, my search path is set to mimiciii, but when I run \d+ MIMICIII.ADMISSIONS; I just get the following message 'Did not find any relation named "MIMICIII.ADMISSIONS".'

Any thoughts on where I'm going wrong?

Dave

![screen shot 2019-01-01 at 10 59 16 am](https://user-images.githubusercontent.com/46113913/50575634-a1b95f00-0db6-11e9-8332-310acc2b2c82.png)
![screen shot 2019-01-01 at 11 02 02 am](https://user-images.githubusercontent.com/46113913/50575635-a2ea8c00-0db6-11e9-99e5-0fe7a4f6e699.png)
![screen shot 2019-01-01 at 11 01 50 am](https://user-images.githubusercontent.com/46113913/50575636-a54ce600-0db6-11e9-9a22-616ff341126f.png)
![screen shot 2019-01-01 at 11 02 13 am](https://user-images.githubusercontent.com/46113913/50575637-a54ce600-0db6-11e9-9e34-e9d1dcfbb581.png)

**Comment by djb218** [comment]
Brilliant. That works. Thanks again Mostafa. I owe you big time!

Dave

**Comment by tompollard** [comment]
Great, glad that helped. Yep, thanks @mostafaalishahi and @xydo1990 for your support!

**Comment by djb218** [comment]
Thanks a lot Tom!
