### ISSUE TITLE
CHARTEVENTS table timestamp incorrect - years are >2018

### ISSUE THREAD

**Issue by wmbm** [MIT-LCP/mimic-code#516]
The timestamp of the year seems to be incorrect in the CHARTEVENTS tabe, in that the years are all ranged between 2100 and 2209.

for example...
```
charttime										
2100-06-08 00:18:00
2100-06-08 00:18:00
2100-06-08 00:19:00
2100-06-08 01:00:00
2100-06-08 01:00:00
```

**Comment by tompollard** [comment]
From the documentation: https://mimic.physionet.org/mimicdata/time/

> Date shifting
> All dates in the database have been shifted to protect patient confidentiality. Dates will be internally consistent for the same patient, but randomly distributed in the future. Dates of birth which occur in the present time are not true dates of birth. Furthermore, dates of birth which occur before the year 1900 occur if the patient is older than 89. In these cases, the patient’s age at their first admission has been fixed to 300.
