### ISSUE TITLE
Can't access the MedNLi Dataset

### ISSUE THREAD

**Issue by TanikSaikh** [MIT-LCP/mimic-code#519]
1. "You don't have permission to access /users/1821cs08@iitp.ac.in/ on this server.
Server unable to read htaccess file, denying access to be safe"
2. Sometimes when we try to access the dataset after giving user id and password, it shows the issue. I have attached the screenshot, please find the attachment.

**Comment by tompollard** [comment]
The dataset is derived from MIMIC, so to access it you will need to be approved via the process described at: https://mimic.physionet.org/gettingstarted/access/. Currently you do not appear to be an approved MIMIC user.

**Comment by TanikSaikh** [comment]
Sir, 
I have not completed all the courses and quiz. Shall I be in approved MIMIC user's list? please check and let me know.

**Comment by TanikSaikh** [comment]
After giving user id and password, it is not allowing me to enter. I am attaching my screenshot as what I am facing. 
![screenshot from 2019-01-29 17-53-57](https://user-images.githubusercontent.com/13650045/51913743-3be3e580-23fd-11e9-8637-59ae8de0dbdb.png)

**Comment by alistairewj** [comment]
You can't log in because as @tompollard says you have not been approved to access MIMIC. Please follow the instructions on this page carefully: https://mimic.physionet.org/gettingstarted/access/

**Comment by TanikSaikh** [comment]
After giving all the Quiz, the gradebook is sowing like below: 
![screenshot from 2019-01-30 17-20-31](https://user-images.githubusercontent.com/13650045/51979638-a9eae400-24b3-11e9-8ba1-d5e9fdf55743.png)

What to do, please tell.

**Comment by mostafaalishahi** [comment]
Please check the image that you attached as it is clearly mentioned "
achieve an average score of at least 90% on all quizzes"

Regards,
Mostafa
