### ISSUE TITLE
Multiple different admittime under same HADM_ID? 

### ISSUE THREAD

**Issue by HansJung** [MIT-LCP/mimic-code#520]
My teammate has an issue in interpreting a patient with same subject_id, icustay_id, and hadm_id but having multiple different admittime. It doesn't seem to make sense, because a patient is supposed to receive a new hadm_id whenever readmit. In such a case, what would be a reasonable interpretation? 

![pastedimage](https://user-images.githubusercontent.com/5043649/51813477-8e4dc680-2284-11e9-8297-626338fe9388.png)

**Comment by alistairewj** [comment]
What is the query you used to generate this? It's impossible to say what's happening if you just post a table of results!
