### ISSUE TITLE
exporting query result from Query Builder dashboard

### ISSUE THREAD

**Issue by Yanjiayork** [MIT-LCP/mimic-code#521]
Description of the issue, including:
I have tried to download the query result from Query builder dashboard (https://querybuilder-lcp.mit.edu/dashboard.cgi). It says 34000 rows found, but when I downloaded it, it only stored 5000 rows in the downloaded file. 
How I can download the query result with losing the information?
I will really appreciate your advice.

**Comment by Yanjiayork** [comment]
@mostafaalishahi  Thank you very much for the quick reply. I have also installed the local database following the tutorial, but it also has the difficulty to pull all the query result out, I am using pgAdmin as recommended by the tutorial. 

Any advice of how to improve this limitation of Postgres?  

Many thanks, Yan.

**Comment by tompollard** [comment]
Thanks @mostafaalishahi. @Yanjiayork your original question about Querybuilder has been answered (rows are intentionally limited), so I'll close this issue. You should not see this limitation with Postgres.
