### ISSUE TITLE
Range between dob and dod in PATIENTS table is unreasonable.

### ISSUE THREAD

**Issue by mlterryMitre** [MIT-LCP/mimic-code#526]
### Description

Age between dob and dod are unreasonable to a person's life expectancy.
* example: subject_id 56 has a dob of 1804-01-02 and dod of 2104-01-08 which puts this patient at 300 years old.
Example query below:
```
SELECT
PATIENTS.subject_id,
PATIENTS.dob,
PATIENTS.dod
FROM PATIENTS
WHERE PATIENTS.subject_id = '56'
```

**Comment by mostafaalishahi** [comment]
according to documentation https://mimic.physionet.org/mimicdata/time/

"All dates in the database have been shifted to protect patient
confidentiality. Dates will be internally consistent for the same patient,
but randomly distributed in the future. Dates of birth which occur in the
present time are *not* true dates of birth. Furthermore, dates of birth
which occur before the year 1900 occur if the patient is older than 89. In
these cases, the patient’s age at their first admission has been fixed to
300."

regards,
Mostafa
