### ISSUE TITLE
Itemid for stroke volume index

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#529]
I am trying to find readings for Stroke Volume Index .
A basic search on table d_items gives me the following :
**itemid**  --     **label**                  --            **dbsource**  --   **linksto** --     **category**    --**unitname**   
625	     --    SVI	                        --                          carevue--	chartevents	--(null )
228375--	Stroke Volume Index (SVI NICOM) --metavision	-- chartevents	--  NICOM--	                       %	
228377	--SVI Change	      --                            metavision	--  chartevents	--NICOM--	                      %	
228182	--SVI (PiCCO)		--                          metavision--	chartevents	--PiCCO	        --           mL/m2	

Are PiCCO and NICOM the systems(probably brands /tech providers) used to record these values?
If so, then I assume it should be fine to use either of these itemids ?

Also, itemid 625 seems to have more records, and other have way less readings. While itemid 625 is from carevue, there should be another corresponding itemid (with good count of records) from metavision too, right? But I could not find any.

**Comment by alistairewj** [comment]
> Are PiCCO and NICOM the systems(probably brands /tech providers) used to record these values?

Yes, these are devices primarily used to estimate cardiac output but which also estimate some other parameters. They are non-invasive and there are some caveats in interpreting their measurements.

> If so, then I assume it should be fine to use either of these itemids ?

I think so, essentially different patients may have been monitored by different devices, and in this instance you actually know the different devices. There may be some discrepancies between the measurement accuracy of the devices but it's hard to say how you would practically deal with this.

> Also, itemid 625 seems to have more records, and other have way less readings. While itemid 625 is from carevue, there should be another corresponding itemid (with good count of records) from metavision too, right? But I could not find any.

Yes that would be my instinct too, so I'd be interested in finding out why this happens, maybe they changed devices, or now they now document a different measure that correlates with SVI.
