### ISSUE TITLE
Frequencies of Opioid Prescription

### ISSUE THREAD

**Issue by ViriyaK** [MIT-LCP/mimic-code#530]
### Description

There are no dosing frequency information in the prescriptions table. I have tried to work around this by using opioid administrations from the input events table, however, as the input events table only records fluid inputs, I am missing information on other forms of opioid administered such as tablets and syringes. Is there a way to obtain the dosing amount, frequency and duration information for non-fluid opioids?

### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

**Comment by alistairewj** [comment]
Unfortunately this is not available in the structured data in MIMIC-III v1.4. You may have some luck parsing nursing notes, or maybe there is structured data in chartevents which describes pain medication, but the pharmacy data for dose/frequency is not there.

**Comment by ViriyaK** [comment]
Thank you for the reply.
Do you know if there is an update or a fix coming? If so, do you know when it might be released?
Thanks.

**Comment by alistairewj** [comment]
No fixed schedule at the moment, but we will certainly keep in mind this type of data in the update.
