### ISSUE TITLE
Data for automated predictions of the ECG-tracing

### ISSUE THREAD

**Issue by xraycat123** [MIT-LCP/mimic-code#531]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

Some ECG-machine can give computer generated predictions. Can I find them in the MIMIC database? I've tried to look into the charteventtable and can find ITEMID for QT, pr-interval, etc. (not many datapoints). Do you know if i can I these alarms/predictions for the ECG?

**Comment by alistairewj** [comment]
Data in chartevents is only there if a nurse decides to document them. Have you looked in d_items for these labels?

You may also be interested in the [matched waveform database subset](https://physionet.org/physiobank/database/mimic3wdb/matched/) which allows you to link raw monitor output (like waveforms and numerics) to patients in the clinical data.
