### ISSUE TITLE
Where can I find information about blood transfusion history and pregnancy history?

### ISSUE THREAD

**Issue by geneera** [MIT-LCP/mimic-code#533]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Please follow the issue template, particularly:

> Description of the issue, including:
> * what you have tried

**Comment by geneera** [comment]
Description of the issue, including:
what you have tried
I've parsed through text notes in table "noteevents" to get at that information, but I couldn't get anything .

references to similar issues
I've searched all issues posted here, but there's no answer.(How to obtain the history of a given patient #253) 

queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
I would look in the D_ITEMS table for information relating to pregnancy history, though it's not at all clear why you think that would be documented in a critical care setting.

For blood transfusions, as mentioned in #253 past history is in general not documented in the structured data. If you haven't successfully parsed the notes, then you probably won't be able to acquire the data.

**Comment by geneera** [comment]
Tks for ur reply.
