### ISSUE TITLE
When making concepts, No such file or directory

### ISSUE THREAD

**Issue by flypig1213** [MIT-LCP/mimic-code#534]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

When making concepts using the following command, 

psql 'dbname=mimic user= mimicuser options=--search_path=mimiciii' -f /*/*/mimic-code/concepts/make-concepts.sql

I got 

===
Beginning to create materialized views for MIMIC database.
Any notices of the form "NOTICE: materialized view "XXXXXX" does not exist" can be ignored.
The scripts drop views before creating them, and these notices indicate nothing existed prior to creating the view.
===

Top level files..
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:13: code-status.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:14: echo-data.sql: No such file or directory
Directory 1 of 9: durations
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:18: durations/ventilation-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:19: durations/crrt-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:20: durations/adenosine-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:21: durations/dobutamine-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:22: durations/dopamine-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:23: durations/epinephrine-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:24: durations/isuprel-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:25: durations/milrinone-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:26: durations/norepinephrine-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:27: durations/phenylephrine-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:28: durations/vasopressin-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:29: durations/vasopressor-durations.sql: No such file or directory
psql:/Users/ErickYang/mimic-code/concepts/make-concepts.sql:30: durations/weight-durations.sql: No such file or directory
......

**Comment by alistairewj** [comment]
You must run the query from the `concepts` folder. As the README says:

> The make-concepts.sql file can be used to build all concepts in a PostgreSQL database. It uses relative paths to call the other SQL scripts, so you need to execute the script from this folder.

So, try running the command again as `psql 'dbname=mimic user= mimicuser options=--search_path=mimiciii' -f make-concepts.sql` after changing into the `mimic-code/concepts` folder.
