### ISSUE TITLE
Possible to download one large .csv file of the data? 

### ISSUE THREAD

**Issue by ccullip** [MIT-LCP/mimic-code#535]
I'm hoping to use the MIMIC dataset for one of my comp sci courses this semester. The problem is that part of the project is designing a relational database, which is already done for MIMIC. Is there a way to recombine the separate tables into one large .csv file, or download the data as one raw .csv file?

This is more of a question than an issue, but I would appreciate any input!

**Comment by tompollard** [comment]
Hi @ccullip, just a quick reply for now...in theory it is possible to transform MIMIC into one big CSV, but there may be more interesting and useful projects to explore. e.g.: there is ongoing work to transform MIMIC to common data standards, such as OMOP, I2B2, FHIR, etc) that perhaps you could contribute to? We'll have a think about this a little more and will get back to you.

**Comment by xysun** [comment]
@tompollard I'd be interested in helping out on MIMIC III -> FHIR. I did a search on Github and could not find much existing projects that does this. Let me know how I can help :)

**Comment by alistairewj** [comment]
@xysun sure shoot Tom or myself an e-mail and we can chat, we don't have anything for FHIR ourselves but we know of a few initiatives which may be close to completion
