### ISSUE TITLE
Is there any way to determine the patient's hospitalization year?

### ISSUE THREAD

**Issue by lequangbkhn** [MIT-LCP/mimic-code#538]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Please do try to fill out the issue template in the future.

We do not currently make the year of hospitalization available with MIMIC-III.
