### ISSUE TITLE
Note category contains whitespaces

### ISSUE THREAD

**Issue by tnaumann** [MIT-LCP/mimic-code#541]
The `category` field of `mimiciii.noteevents` has trailing whitespaces. E.g.,

```
mimic=> select distinct replace(category, ' ', '_') from mimiciii.noteevents;
      replace
-------------------
 Discharge_summary
 Respiratory_
 ECG
 Pharmacy
 Nursing
 Echo
 Consult
 Case_Management_
 General
 Physician_
 Social_Work
 Nutrition
 Radiology
 Rehab_Services
 Nursing/other
(15 rows)
```

Note that this affects the following categories `Respiratory `, `Case Management `, and `Physician `.

**Comment by alistairewj** [comment]
Definitely something to fix! Have cross-raised this in our building repository and the new version will hopefully avoid such annoyances :)
