### ISSUE TITLE
When will MIMIC CXR Radiology Reports be released?

### ISSUE THREAD

**Issue by dhruvrajan** [MIT-LCP/mimic-code#542]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I was wondering when the MIMIC-CXR radiology reports will be released? I see it mentioned in a few places (https://arxiv.org/pdf/1811.08615, https://arxiv.org/abs/1901.07042) that they will be released in the near future. Thanks!

**Comment by alistairewj** [comment]
They will be released in the near future! :)

>

**Comment by najmehs** [comment]
I have already gotten access to the MIMIC-CXR dataset. The dataset only includes the labels. I am wondering if/when you will release the reports?

**Comment by alistairewj** [comment]
https://www.nature.com/articles/s41597-019-0322-0

https://physionet.org/content/mimic-cxr

**Comment by JyotsanaMehra** [comment]
Is the full labels.csv file containing labels of each X-ray reports has been released? If yes then from where I can get this?

**Comment by alistairewj** [comment]
Your question is a bit vague, but if you mean the NLP derived labels from the radiology reports, then take a look at the other repository and PhysioNet project:

https://github.com/mit-lcp/mimic-cxr

https://physionet.org/content/mimic-cxr-jpg/

**Comment by nnajeh** [comment]
to train my own developed model on MIMIC-CXR, should i use Cloud AI Platform Notebook or is it possible with google colab?

**Comment by alistairewj** [comment]
Please open a new issue if you have a new question!
