### ISSUE TITLE
Calculating time varying SOFA score

### ISSUE THREAD

**Issue by sudarshan85** [MIT-LCP/mimic-code#544]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues/351#issue-281596112

### Description
Hi,
I'm trying to calculate the SOFA score for each patient for a window of 24 hours with the window moving by one hour from admission to discharge or death. For example, consider a patient whose admission time is `t_0` and discharge/death time is `t_d`, I need to calculate the SOFA score for the patient within `t_0 - t_24`, `t_1 - t_25`, `t_2 - t_26`,...`t_d-24 - t_d`.

The script included for SOFA calculation, computes the score for the first 24 hours after admission. I was wondering how I can modify it to calculate the score as I need.

One way I thought I could do it is to manually change the interval of the 1st day to increment it by one hour similar to what was suggested [here](https://github.com/MIT-LCP/mimic-code/issues/351#issue-281596112). I'm referring to the lines in the code where `interval` is present:
```
and charttime between ie.intime - interval '1' day and ie.intime + interval '1' day
and echo.charttime > ie.intime - interval '7' day
and echo.charttime < ie.intime + interval '1' day
on ie.icustay_id = cv.icustay_id and cv.charttime between ie.intime and ie.intime + interval '1' day
on ie.icustay_id = mv.icustay_id and mv.starttime between ie.intime and ie.intime + interval '1' day
```
Obviously doing this is tedious, and I was wondering if anyone could point me in the direction of a more easy method. Essentially, at the end of the day, I'm looking to create a table (dataframe) with patient information, a start and end time (with a difference of 1 hour) and the corresponding SOFA scores for all patients from admission to discharge/death.

Thanks and all help is appreciated.

**Comment by alistairewj** [comment]
https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted-sofa.sql
