### ISSUE TITLE
Causes of NaN in VALUENUM in CHARTEVENTS

### ISSUE THREAD

**Issue by C0NTRIBUTE** [MIT-LCP/mimic-code#545]
When `VALUENUM` is `NaN` in `CHARTEVENTS` what are the possible causes for this? In addition to being curious, my practical case is that I want to eliminate the possibility of introducing a bias as a result of removing rows with `NaN` values from a sample.

**Comment by alistairewj** [comment]
If the row is not a number, `valuenum` will be `NaN`.

**Comment by C0NTRIBUTE** [comment]
Thanks so much for confirming that :)
