### ISSUE TITLE
Discrepancy between ICD9 Codes in D_ICD_PROCEDURES

### ISSUE THREAD

**Issue by VeenitShah** [MIT-LCP/mimic-code#550]
I saw a discrepancy between the ICD9_CODE field in the procedures mapping table where 1 code corresponds to 2 different short and long titles

For e.g. ICD9 code `34` has the following entries - 
Row_ID: `161`
Short Title: `Imageless comp asst surg` 
Long Title: `Imageless computer assisted surgery` 

Row_ID: `190`
Short Title: `Excis spinal cord lesion` 
Long Title: `Excision or destruction of lesion of spinal cord or spinal meninges` 

There are many such other ICD9 codes too. Am I missing any context here? Per my understanding, each ICD9 code uniquely represents something.

**Comment by alistairewj** [comment]
These are different codes: `0034` and `034 `. Do not treat the ICD9 codes as integers or you will run into these headaches. Treat them as character strings. Better yet, convert them into non-variable length character strings: `CHAR(4)` or `CHAR(5)`. We plan to distribute them in this way in the future.
