### ISSUE TITLE
is there abdominal girth data for adult patients in MIMIC III database? noteevents? chartevents?

### ISSUE THREAD

**Issue by wyyyzw** [MIT-LCP/mimic-code#552]
Except for neonatal abdominal girth data, is there abdominal girth data for adult patients in MIMIC database? noteevents? chartevents?

**Comment by alistairewj** [comment]
Not something we would know without checking. I'd ask a colleague who works in the ICU if that type of data is routinely collected and look for it in d_items.

**Comment by wyyyzw** [comment]
> Not something we would know without checking. I'd ask a colleague who works in the ICU if that type of data is routinely collected and look for it in d_items.

there are d_items for abdominal girth, but they are all neonatal data, i can't find abdominal girth data for adult patients.
