### ISSUE TITLE
Calculating ICU Occupancy

### ISSUE THREAD

**Issue by farukakin** [MIT-LCP/mimic-code#553]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

Hi;
First of all thanks for providing such a rich dataset. I want to use ICU occupancies at times of admissions and discharges, but this is not possible with the current dataset, which requires the real time data. A similar issue is raised in #263, in which contacting mimic-support@physionet.org is advised. I wrote a detailed email to this email address, but I doubt it reached, so I am writing here. 

I think that requesting actual time data is a detailed process on both sides. I wonder if it is possible for you to provide ICU occupancies for each admission and discharge, so that dates in the dataset are still randomized?

Thanks is advance,
Faruk

**Comment by alistairewj** [comment]
We will not be releasing bed occupancy data.
