### ISSUE TITLE
Diagnostic test used for C. diff 

### ISSUE THREAD

**Issue by lf2608** [MIT-LCP/mimic-code#554]
What is the diagnostic test for Clostridium difficile used in MIMIC? 
I tried to search "Toxin testing", "Enzyme immunoassay", "Cell cytotoxin assay", "Organism identification Detection of glutamate dehydrogenase", "Polymerase chain reaction in D_ITEMS and D_LABITEMS table. But I couldn't found any one of the tests. 
I only found result for C. diff in MICROBIOLOGYEVENTS table. It looks like stool culture result. 

Is there any other diagnostic tests used for Clostridium difficile used in MIMIC? Thank you!

**Comment by alistairewj** [comment]
The name of the microbiology test is currently not in the database so you won't find that. However you can look for the organism (CLOSTRIDIUM DIFFICILE) which is under `itemid = 80139`. Cross-referencing with the microbiologyevents table gives some hits:

`select * from microbiologyevents where org_itemid = 80139 limit 5;`


spec_itemid | spec_type_desc | org_itemid |       org_name        
------------ | ---------------- | ------------ | -----------------------
70064 | STOOL          |      80139 | CLOSTRIDIUM DIFFICILE
70064 | STOOL          |      80139 | CLOSTRIDIUM DIFFICILE
70064 | STOOL          |      80139 | CLOSTRIDIUM DIFFICILE
70064 | STOOL          |      80139 | CLOSTRIDIUM DIFFICILE
70064 | STOOL          |      80139 | CLOSTRIDIUM DIFFICILE

**Comment by fuzzyman27** [comment]
> What is the diagnostic test for Clostridium difficile used in MIMIC?
> I tried to search "Toxin testing", "Enzyme immunoassay", "Cell cytotoxin assay", "Organism identification Detection of glutamate dehydrogenase", "Polymerase chain reaction in D_ITEMS and D_LABITEMS table. But I couldn't found any one of the tests.
> I only found result for C. diff in MICROBIOLOGYEVENTS table. It looks like stool culture result.
> 
> Is there any other diagnostic tests used for Clostridium difficile used in MIMIC? Thank you!

Did you end up finding any other way to identify non-culture tests for C diff? I iterated through the entire LOINC list of codes for GDH and toxin a/b testing but was unable to identify anything in lab events. This is because it seems immunoassay tests aren't stored in the table (categories include heme, chemistry and blood gas only). I think the bigger question is how we could identify immunoassay lab tests overall. And given none of the C diff immunoassay tests are CLIA waived, they should be tracked somewhere

**Comment by alistairewj** [comment]
I'm pretty sure all the tests for C diff are in microbiologyevents. Are you looking for DNA amplification tests or something like that?

**Comment by fuzzyman27** [comment]
> I'm pretty sure all the tests for C diff are in microbiologyevents. Are you looking for DNA amplification tests or something like that?

Thanks for the quick response!

Couple things would be nice here:

1) It would be great to differentiate between types of tests for C diff (glutamate dehydrogenase vs toxin a/b vs culture vs DNA amplification). Sensitivity for these tests differs significantly and given patients can be colonized but not show signs of infection, it makes for an interesting analysis given isolation/cost implications for a diagnosis.

As of now it does seem like everything is lumped into microbio. Of the ~1444 patients with ICD-9 codes for C Diff (008.45), around 1,000 have a positive microbiology stool test result for C Diff. I imagine this includes more than just stool culture and the 400 discrepancy is for patients who were admitted after being diagnosed (need to do more digging here as I'm really just starting).

2) Would be great to find out when tests are ordered regardless of result without significant mining of note events or chart events tables -  the microbiology table only gives you the organism name once the test is positive, but plenty of tests ordered for patients with diarrhea should come back negative, especially the immunoassay.

This paper seems to have identified exactly when patients were diagnosed:
http://ecmlpkdd2017.ijs.si/papers/paperID487.pdf

**Comment by alistairewj** [comment]
1. Yep, absolutely an improvement we want to include, probably in the next iteration. When I checked there was only toxin A/B tests in MIMIC.
2. Negative cultures are in the micro table but they have a null organism. The charttime is the closest we have (roughly when the specimen was taken) - next version will add a store time.

**Comment by fuzzyman27** [comment]
> 1. Yep, absolutely an improvement we want to include, probably in the next iteration. When I checked there was only toxin A/B tests in MIMIC.
> 2. Negative cultures are in the micro table but they have a null organism. The charttime is the closest we have (roughly when the specimen was taken) - next version will add a store time.

Makes sense thanks! Certainly looking forward to that next iteration. Certain portion of negative stool cultures/toxin tests will be for C Diff, while others will be from actual stool cultures for other acute GI infections (salmonella, e coli, etc). Might try and find a way to differentiate between the two - if you have any thoughts, feel free to pass along!
