### ISSUE TITLE
Error with MIMIC ventilation-durations.sql

### ISSUE THREAD

**Issue by nnick1** [MIT-LCP/mimic-code#558]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Running ventilation-durations.sql
Getting the following error:
NOTICE:  drop cascades to materialized view ventdurations
NOTICE:  materialized view "ventdurations" does not exist, skipping

* references to similar issues
#258

Would greatly appreciate any help

@alistairewj @tompollard

**Comment by alistairewj** [comment]
This is not an error - it's a notice. It is telling you that the view does not exist, so it is skipping the command that instructs it to drop the view. Almost all the queries in the repo drop the view/table before trying to create them.
