### ISSUE TITLE
inputevetents tables - rows with itemids but NULL "amount"

### ISSUE THREAD

**Issue by j2007** [MIT-LCP/mimic-code#560]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

If a record has an entry for a specific itemid  eg. in inputevents_cv : with an itemid = 30001 for Packed Red Blood cells (Packed RBC's or PRBCs), but the amount column is NULL, however there is data for the rest of the columns does it mean:

a. PRBCs was administered and amount was not recorded, or it wasn't administered at all? Note there is charttime and storetime recorded for some of these cases , therefore it implies it was done (run below query as an example)?

​b. If it was administered and amount was simply not recorded, is there an amount that should be assumed based on the itemid (e.g. usually  375 ml of PRBCs for most blood products - but not always that amount, as the rate affects it) ?  

Here is a sample query:
--------------------------------------------------------
select * from mimiciii.inputevents_cv
where subject_id = 11353
order by itemid
--------------------------------------------------------
My goal is to calculate total amount of input products per subject/ per itemid. 
I appreciate the help!

**Comment by alistairewj** [comment]
There are two possibilities: (a) no volume was documented, and we're really not sure retrospectively if anything was given, or more commonly (b) the amount of blood given was documented in a comment field, and in our process of removing PHI we deleted the comments so you can't see this free-text note.

To try to give you an idea of the degree of impact, I've summarized (using the original data) how frequently each occurs:

Number | Description
--- | ---
52,243 | Number of total PRBC instances
45,245 | ... with a volume documented
5,935 | ... with a comment
2,202 | ... with *no* volume, but a comment (comment usually has units given)

Comments will also rarely be used to state that the blood was given elsewhere; e.g. "in ER" or "on the ward".

I just read through a bunch of these cases and I'd say ~90% of the time 1 unit is given and ~5% of the time 2 units are given. So I'd say the best assumption is to say these rows indicate 1 unit of blood is given (for PRBC, I guess the assumption might be different for something like platelets/albumin but I haven't looked).

**Comment by j2007** [comment]
Thank you Alistair. This is helpful!
