### ISSUE TITLE
Should we treat all diagnoses in drg_code and diagnoses_icd as discharge diagnoses?

### ISSUE THREAD

**Issue by JackieMium** [MIT-LCP/mimic-code#563]
From your website [The diagnoses_icd table](https://mimic.physionet.org/mimictables/diagnoses_icd/):

> The ICD codes are generated for billing purposes at the end of the hospital stay.

and [The drgcodes table](https://mimic.physionet.org/mimictables/drgcodes/)

> DRG_CODE contains a code which represents the diagnosis billed for by the hospital.

So do both table contain only diagnoses at discharge? 
If yes, then what if I am to find out admission diagnosis for ICU stays? There is a `diagnosis` field in `admissions`. However, I found it simple and vague. And on you website [The admissions table](https://mimic.physionet.org/mimictables/admissions/):

> Final diagnoses for hospital admissions are coded and can be found in the DIAGNOSES_ICD table.

This is contradictory to the above `diagnoses_icd` quote that diagnoses in the table are generated "at the end of the hospital stay". Does it mean that diagnoses in  `diagnoses_icd` are actually admission diagoses but recorded at the end of the hospital stay? This is somewhat confusing as nothing on your website clearly states when are these different diagnoses in different tables are recorded or whether they are admission or discharge diagnoses.

**Comment by alistairewj** [comment]
Yes, DRGs are also assigned at discharge. I honestly don't fully understand the billing practices, but the general flavor is that DRGs are broad (like cardiovascular surgery) and ICDs are quite specific.

I would not recommend using the `diagnosis` field in the `admissions` table. This is written on the patient admission, but is totally free-text, and can be pretty random (e.g. "syncope" for a septic patient).

> > Final diagnoses for hospital admissions are coded and can be found in the DIAGNOSES_ICD table.
> 
> This is contradictory to the above diagnoses_icd quote that diagnoses in the table are generated "at the end of the hospital stay". Does it mean that diagnoses in diagnoses_icd are actually admission diagoses but recorded at the end of the hospital stay? This is somewhat confusing as nothing on your website clearly states when are these different diagnoses in different tables are recorded or whether they are admission or discharge diagnoses.

I think the wording just isn't clear here. This was meant as a pointer to the DIAGNOSES_ICD table, along the lines of "if you are interested in the final diagnosis for a patient admitted to the hospital, then go to the ICD table". The word "admissions" here is meant as a noun, not as a point in time, as in "a patient's hospital admission".

**Comment by thebeckster** [comment]
If using the diagnosis field in the admissions table is not recommended, is there a way to go about determining the specific diagnosis upon admission using the diagnoses_icd table?

I agree that the wording under the diagnosis field in the admissions table is pretty unclear, and I think using the word "admissions" can be easily mistaken to mean that the diagnoses in the diagnoses_icd table refer to diagnoses upon admission.

**Comment by alistairewj** [comment]
Sure I've updated the wording so it's a bit clearer.

There's no systematic way to get admission diagnosis from the diagnoses_icd table. The best, though challenging, approach is to parse the history of present illness/past medical history sections of the discharge summaries.
