### ISSUE TITLE
PAF Dataset 

### ISSUE THREAD

**Issue by pedrograca** [MIT-LCP/mimic-code#564]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by pedrograca** [comment]
I am currently working on a project where I am trying do predict Atrial Fibrillation on Patients.  I am using the PAF Prediction Challenge Dataset, described in the following link: https://physionet.org/physiobank/database/afpdb/

As a part of this challenge, a big portion of the dataset was unlabeled (the files starting with the letter ''t''). I was wondering if by any chance anyone working with Physionet could give me the labels of these files (AF or Healthy Patient), to help validating my models.

Thanks.

**Comment by alistairewj** [comment]
We do not have plans to make those annotations public.

**Comment by pedrograca** [comment]
Hi, first of all thanks for the reply. 

Do you know if there is any way of validating my model using those files then? 

Maybe by sending the results to someone over there, to compare the results with those annotations, just like you originally did during the challenge? It would mean a lot.

Thank you for your time.

**Comment by alistairewj** [comment]
The challenge page describes how you can have entries scored after the
challenge has ended - but it's clearly been a number of years so let us
know how it goes.

>
