### ISSUE TITLE
Nosocomial and secondary infections

### ISSUE THREAD

**Issue by thebeckster** [MIT-LCP/mimic-code#565]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I am currently doing a study involving septic and critically ill nonseptic patients. Is there a way to determine whether these patients developed nosocomial or secondary infections? Readmission for sepsis or new infection would also qualify as secondary infection.
I have looked at the diagnoses table, but from my understanding, the sequence number is for billing purposes and doesn't necessarily reflect the order of a patient's diagnoses. Is there another way to find this information?

**Comment by alistairewj** [comment]
I'd recommend using the microbiology table to define infection, then coming
up with a rule for determining that it is secondary.
