### ISSUE TITLE
Number of beds in each ICU

### ISSUE THREAD

**Issue by alryce** [MIT-LCP/mimic-code#566]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

How many beds were in each of the ICUs represented in the MIMIC-III database? Additionally, were there any drastic changes in these numbers during the years covered by MIMIC-III (2001-2012)?

**Comment by alistairewj** [comment]
It varies but there's around 8-10 beds per ICU in MIMIC. There were changes over the years but we won't be able to make that information public.
