### ISSUE TITLE
Injury Severity Score/ Trauma admissions

### ISSUE THREAD

**Issue by j2007** [MIT-LCP/mimic-code#567]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

Hello,
1)Is there an injury severity score  (ISS)  for trauma patients (or any patient) in the mimic-iii database? I looked in D_ITEMS and couldn't find an itemid. 
I am defining trauma patients by 'TRAUM' from the services table.
  query :  select * from mimiciii.services where curr_service = 'TRAUM'

2) Also would this be an appropriate way to describe Trauma admissions in the entire database? 
query: select  distinct hadm_id from mimiciii.services where curr_service = 'TRAUM'

The reason I ask is, there are only 3111 distinct Trauma admissions, and I thought there would be more, given the amount of records mimic has. 

Any help will be appreciated!
Thank you!

**Comment by alistairewj** [comment]
1. These aren't routinely documented in the ICU information system.
2. Using services is a good approach - it may be that some trauma patients are admitted under a surgical service.
