### ISSUE TITLE
Error - could not change directory

### ISSUE THREAD

**Issue by nkumarJHHTWH** [MIT-LCP/mimic-code#568]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [x] Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * [x] Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
_As per the documentation I have done the following steps with no issues:_ 

\set mimic_data_dir 'C:\Users\Nikhil\Desktop\MIMIC\Database'

\i C:/Users/Nikhil/Desktop/MIMIC/Database/postgres_create_tables_pg10.sql
_this was a bit of an issue, but I resolved it by downloading the SQL file rather than the html based on previous questions_

\i C:/Users/Nikhil/Desktop/MIMIC/Database/postgres_load_data.sql
_I have confirmed I downloaded the SQL version of the load_data.sql_
_I tried doing the \set mimic_data_dir 'C:\Users\Nikhil\Desktop\MIMIC\Database' again_

_*Regardless of what I have done, I keep getting this error:_ 
mimic=# \i C:/Users/Nikhil/Desktop/MIMIC/Database/postgres_load_data.sql
psql:C:/Users/Nikhil/Desktop/MIMIC/Database/postgres_load_data.sql:12: \cd: could not change directory to "C:UsersNikhilDesktopMIMICDatabase": No such file or directory
mimic=# \set mimic_data_dir 'C:\Users\Nikhil\Desktop\MIMIC\Database'
mimic=# \i C:/Users/Nikhil/Desktop/MIMIC/Database/postgres_load_data.sql
psql:C:/Users/Nikhil/Desktop/MIMIC/Database/postgres_load_data.sql:12: \cd: could not change directory to "C:UsersNikhilDesktopMIMICDatabase": No such file or directory
mimic=# \set mimic_data_dir 'C:\Users\Nikhil\Desktop\MIMIC\Database'

_Not sure what is going on, your help would be appreciated_

**Comment by alistairewj** [comment]
If you are on windows then your slashes need to be the other direction - i.e. instead of `\set mimic_data_dir 'C:\Users\Nikhil\Desktop\MIMIC\Database'` you need to do `\set mimic_data_dir 'C:/Users/Nikhil/Desktop/MIMIC/Database'`
