### ISSUE TITLE
is there exist a code repository for Continuous State-Space Models for Optimal Sepsis Treatment - a Deep Reinforcement Learning Approach" by Raghu et al. MLHC 2017

### ISSUE THREAD

**Issue by paulrich1234** [MIT-LCP/mimic-code#569]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by paulrich1234** [comment]
hello guys ,i am now doing some research about the reinforcement learning on mimicIII data,and  i am refer to this articles "Continuous State-Space Models for Optimal Sepsis Treatment - a Deep Reinforcement Learning Approach" by Raghu et al. ",but i donot have the original preprocessing data .i mean  it is said in the paper that there is some code available for preprocessing original ,i am curious about it .could you guys know something about it .thank you very much ahead

**Comment by alistairewj** [comment]
Please raise any issues with their code on their repo: https://github.com/matthieukomorowski/AI_Clinician
