### ISSUE TITLE
Ventilator modes not found for metavision patients

### ISSUE THREAD

**Issue by ayoung01** [MIT-LCP/mimic-code#57]
I am using MIMIC III v1.1 and was unable to find information regarding ventilator modes from the Metavision data source (specifically, ITEMID== 223849 in CHARTEVENTS). Is this information available elsewhere?

**Comment by alistairewj** [comment]
No, unfortunately it is not. Data in D_ITEMS with a null value in the LINKSTO column are missing, but intended for inclusion in a future release.
