### ISSUE TITLE
[Err] ERROR:  operator does not exist: character varying = integer

### ISSUE THREAD

**Issue by lcyxwrl** [MIT-LCP/mimic-code#570]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
when I do queries，it appears：
[Err] ERROR:  operator does not exist: character varying = integer
LINE ***********
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
what should I do to solve this promble？
* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
You are trying to compare a character varying (string) with an integer (number). This is a postgres syntax error telling you that you should compare a string with a string or a number with a number. I'd check stackoverflow for help with this type of postgres syntax: https://stackoverflow.com/questions/23622993/postgresql-error-operator-does-not-exist-integer-character-varying
