### ISSUE TITLE
Diagnosis in diagnoses_icd table

### ISSUE THREAD

**Issue by lequangbkhn** [MIT-LCP/mimic-code#573]
Hi,
I am working on an association with acute renal failure for patients located at ICU. I am a bit confused in the DIAGNOSES_ICD table as follows: Because these diagnoses are given when the patient leaves the hospital, these diagnoses will be the sum of all diagnoses during the patient's hospital stay (according to HADM_ID) and is there any way I know which diagnosis is given at any time? And are these diagnoses completely correct? The diagnostics with SEQ_NUM> 5 are you confident?
I really need the accuracy to label the data.
Thanks very much.

**Comment by alistairewj** [comment]
There's no way to know what time period a diagnosis in diagnoses_icd corresponds to.

These diagnoses are assigned by trained personnel reviewing signed patient notes.
