### ISSUE TITLE
Discrepancies in total ICU stays

### ISSUE THREAD

**Issue by arnepeine** [MIT-LCP/mimic-code#574]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Dear all,

MIMIC-III has 53,423 distinct ICU stays for adults (>=16 age) according to

https://www.nature.com/articles/sdata201635/tables/1

With the current MIMIC version, we count 61,532 ICU admissions in the SQL data.
Is it a matter of versioning? (MIMIC 1.4)

Thanks for your reply!

**Comment by alistairewj** [comment]
There are neonates. 

https://mimic.physionet.org/gettingstarted/access/

> The latest version of MIMIC is MIMIC-III v1.4, which comprises 61,532 intensive care unit stays: 53,432 stays for adult patients and 8,100 for neonatal patients.
