### ISSUE TITLE
Onset time of septic shock 

### ISSUE THREAD

**Issue by marciofreire** [MIT-LCP/mimic-code#576]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello,

My name is Márcio Cruz. I am a Ph.D. student from Brazil and my research deals with Septic Shock prediction. I've been using the MIMIC-CODE and found it very useful to the researches about sepsis. Congratulations!  

I've been trying to identify the onset time of septic shock of the patients in MIMIC III Database, but I couldn't find a way to do that. Could you help me with that?

Thank you very much.

Best regards,

Márcio Freire Cruz

**Comment by alistairewj** [comment]
Septic shock can be identified using the charted data. This would involve (1) deciding on a definition of septic shock and (2) suitably approximating it with the available retrospective data.

The primary Sepsis-3 publication provides a reasonable set of criteria for septic shock: https://jamanetwork.com/journals/jama/article-abstract/2492881

1. Criteria for sepsis are: organ failure and suspected infection (usually implemented as SOFA >= 2 and proximal antibiotics/cultures).
2. Septic shock is a subset of sepsis
3. Patients with septic shock can be identified with a clinical construct of sepsis with persisting hypotension requiring vasopressors to maintain MAP ≥65 mm Hg and having a serum lactate level >2 mmol/L (18 mg/dL) despite adequate volume resuscitation.

**Comment by marciofreire** [comment]
Thanks. I will have this code done and send it to contribute with this repository if you agree with that later.
