### ISSUE TITLE
2.7x lossless compression from .dat to .flac

### ISSUE THREAD

**Issue by kuprel** [MIT-LCP/mimic-code#578]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Reference to similar issue: https://github.com/MIT-LCP/wfdb-python/issues/57

FLAC is a lossless audio compression format.  I found it achieves about a 2.7x compression ratio on the raw .dat files.  Here is my code: https://github.com/kuprel/flacdb

**Comment by alistairewj** [comment]
Cheers - I'll close this as there's no action point but it will be undoubtedly useful for people using the waveform data.
