### ISSUE TITLE
Unexpected nulls in the derived gcsfirstday table on bigquery

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#579]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

A large number of cells in the `gcsfirstday` table on BigQuery are missing data. Compare the following row counts in Postgres and BigQuery:

Postgres (built with https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/gcs-first-day.sql) 
```
mimic=# SELECT COUNT(*)
mimic-# FROM gcsfirstday
mimic-# WHERE mingcs IS NULL;
 count 
-------
  9389
```

BigQuery (built with https://github.com/MIT-LCP/mimic-code/blob/google-cloud-views/concepts/firstday/gcs-first-day.sql)
```
SELECT COUNT(*)
FROM `physionet-data.mimiciii_derived.gcsfirstday`
WHERE mingcs IS NULL;

 count 
-------
  32594
```

Specific example of a cell that differs:

Postgres
```
mimic=# SELECT *       
FROM gcsfirstday 
WHERE subject_id = 97157

 subject_id | hadm_id | icustay_id | mingcs | gcsmotor | gcsverbal | gcseyes | endotrachflag 
------------+---------+------------+--------+----------+-----------+---------+---------------
      97157 |  181559 |     266697 |     14 |        6 |         4 |       4 |             0
```

BigQuery:
```
SELECT *
FROM `physionet-data.mimiciii_derived.gcsfirstday`
WHERE subject_id = 97157

 subject_id | hadm_id | icustay_id | mingcs | gcsmotor | gcsverbal | gcseyes | endotrachflag 
------------+---------+------------+--------+----------+-----------+---------+---------------
      97157 |  181559 |     266697 |   NULL |     NULL |      NULL |    NULL |          NULL
```

This may be an issue in other tables too.

**Comment by alistairewj** [comment]
fixed in https://github.com/MIT-LCP/mimic-code/commit/b921a5b7845ce8b7b1af33d5b7531ff6b3ae0ad6

**Comment by alistairewj** [comment]
fixed in all other tables here https://github.com/MIT-LCP/mimic-code/commit/18fe5e258ac672a51a1213f96161eef070c9d6e2
regenerated all these tables on gcp
