### ISSUE TITLE
Mistake in 

### ISSUE THREAD

**Issue by RaterBai** [MIT-LCP/mimic-code#582]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by RaterBai** [comment]
The criterion of calculating bun_score in the mimic-code/concepts/severityscores/sapsii.sql, should be >= 83, not 84. Things go wrong with this script.

**Comment by alistairewj** [comment]
discussing in #583
