### ISSUE TITLE
Mistake in mimic-code/concepts/severityscores/sapsii.sql

### ISSUE THREAD

**Issue by RaterBai** [MIT-LCP/mimic-code#583]
The criterion used to calculate bun_score should be ">=83", not ">=84". If so, all the records with bun_max as 83 will be null.

**Comment by alistairewj** [comment]
I just checked the original JAMA publication and it's listed as >= 84.
https://www.ncbi.nlm.nih.gov/pubmed/8254858

If you don't mind me asking - where did you see it listed as >= 83?

**Comment by RaterBai** [comment]
Sorry, I haven't read the paper yet. It just seems unreasonable that all the records with bun_max equal to 83 will be null.

**Comment by alistairewj** [comment]
Oh I see what you mean. Yeah I agree, it should read < 84, not < 83.
