### ISSUE TITLE
The timestamp of matched waveform records does not match the timestamp of the clinical database?

### ISSUE THREAD

**Issue by Lejla1979** [MIT-LCP/mimic-code#585]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, is it possible that the timestamp of matched waveform records does not match the timestamp of the clinical database? For example subject 87953?
…

**Comment by alistairewj** [comment]
It's possible. https://physionet.org/physiobank/database/mimic3wdb/#technical-limitations

**Comment by waqaraziz123** [comment]
Hi,

Yes, it is possible but you can narrow down your criteria to pinpoint your time of interest. I am working with MIMIC waveforms and generated few results.

I am looking for collaboration with people working on MIMIC waveforms. Please let me know if you are interested.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
