### ISSUE TITLE
Stuck on "COPY 7567" for over 9 hours...

### ISSUE THREAD

**Issue by sastani** [MIT-LCP/mimic-code#589]
I realize that its supposed to take awhile to create the fourth table...but its been over 9 hours and its still not completed. 
![Screen Shot 2019-08-10 at 4 42 22 AM](https://user-images.githubusercontent.com/10406106/62821419-70adc380-bb29-11e9-8092-f657da43aa4e.png)

My mac has not slept for almost 10 hours. 
![Screen Shot 2019-08-10 at 4 44 06 AM](https://user-images.githubusercontent.com/10406106/62821424-88854780-bb29-11e9-9331-7437302ce139.png)

**Comment by alistairewj** [comment]
It looks like you're building the database on a remote server - so it has to transfer the data over the internet. I would imagine that will take a long time depending on your internet connection.

**Comment by sastani** [comment]
I tried this locally as well and it is still not making any progress after 10 hours...
