### ISSUE TITLE
Whers are the objective measurements about echocardiography?

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#590]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hello, I have extracted information about "Echo" from NOTEEVENTS. However, I could seldom find objective measurements (such as RVIDd, IVSd, EDV, ESV, SV, EF, LA, PA and so on). Are these measurements stored in somwhere else?

**Comment by alistairewj** [comment]
No unfortunately we haven't been able to bring those measures into MIMIC yet.
