### ISSUE TITLE
Future events and date of birth

### ISSUE THREAD

**Issue by lovebombay** [MIT-LCP/mimic-code#592]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description : I see 95% of date of birth in MIMIC data as in the future. While there was a blurb on mimic data being masked by a date past for HIPAA reasons, I see them as future dates. Are we missing something. We are trying to do a OMOP conversion and we would end up loosing these records for what we are doing. Any advice? Thank You

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
https://mimic.physionet.org/mimicdata/time/
