### ISSUE TITLE
Chemotherapy drugs

### ISSUE THREAD

**Issue by loberste** [MIT-LCP/mimic-code#595]
Dear MIMIC community,

First of all, thanks to the publishers for creating & offering such a great dataset! As part of my master thesis I am investigating _intravenous (IV) chemotherapies_. I hope that I can find corresponding drugs and durations of their inpatient administration in the MIMIC data.  Unfortunately, I'm a little confused and would be very pleased about any help to the following questions and tables, respectively:

- In **PROCEDURES_ICD**, the code `9925` is referenced by 529 admission IDs which indicates that there should be at least correspondingly many IV chemotherapy administrations present in the data
- But when searching **INPUTEVENTS_MV** for commonly, continously (non-bolus) administered items, general fluids (painkillers, volume expanders) were found but almost no chemo drugs:
  - (neglecting the dose change/new dosage distinction)
  - `select count(a.itemid) as ct, a.itemid, b.label from inputevents_mv as a inner join D_ITEMS as b on a.itemid = b.itemid where hadm_id in (select hadm_id from procedures_icd where icd9_code = '9925') and endtime-starttime <> '1 minute' group by a.itemid, b.label order by ct desc`
  - Example: Octreotide (an anti-tumor drug) amounts to only 4 times, which is surprising because in the whole inputevents_mv table, there are 2929 occurences

Excerpt:

| count | itemid | label       |
|-------|--------|-------------|
| 11265 | 225158 | NaCl 0.9%   |
| 4528  | 220949 | Dextrose 5% |
| 2901  | 225943 | Solution    |
|       |        | ...         |

So, ultimatively:
- Would you think that I overlooked certain chemotherapy data in the database?
  - Codes `96401-96549` in **CPTEEVENTS** as well as codes `6931-6934` in **DRGCODES** are only referenced by 100 admission IDs, so thats probably not the main part
- Is there any chance of identifying the particular drugs and start- & endtimes of their administration?

Thanks in advance for any help!

**Comment by alistairewj** [comment]
> In PROCEDURES_ICD, the code 9925 is referenced by 529 admission IDs which indicates that there should be at least correspondingly many IV chemotherapy administrations present in the data

Not necessarily; the treatments may be given outside of the ICU, in which case we wouldn't have them in the ICU information system derived `inputevents_*` tables. But we would expect them in the `prescriptions` table, which covers the entire hospitalization.

**Comment by loberste** [comment]
> Not necessarily; the treatments may be given outside of the ICU, in which case we wouldn't have them in the ICU information system derived `inputevents_*` tables. But we would expect them in the `prescriptions` table, which covers the entire hospitalization.

Dear Alistair,
thanks for the informative and quick answer! Sorry for re-enquiring: It makes me wonder if there is another chance to infer the duration of the treatment (outside the ICU, so probably on a chemotherapy chair or in an inpatient setting)?

If the chemotherapy is administered on a chemotherapy chair, could I identify it using the `TRANSFERS` table? For instance, when a patient is transferred to a non-ICU ward and stays there shortly, in which period the prescription table shows an antitumor drug? But I guess a treatment room would not be listed as a ward? Aparently, there is no oncological service either.

If the chemotherapy is administered to a regular inpatient, there wouldn't be any definite start/end time of administration, would there?

Thanks a million for any thoughts!

**Comment by alistairewj** [comment]
I would see how accurate the start and end dates are in the prescriptions
table. I don't think you can do much linking to transfers. Pretty
challenging to study this in MIMIC unfortunately!

**Comment by loberste** [comment]
@alistairewj Thank you very much, highly appreciated! I will investigate this last option and close the "issue" :)
