### ISSUE TITLE
Hi. I want to use MIMIC III waveform database for ECG, BP and PPG date. Can someone give me pointers.

### ISSUE THREAD

**Issue by satyagupta09** [MIT-LCP/mimic-code#598]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by waqaraziz123** [comment]
Hi,

Can you please be more specific regarding your query? 

Thanks

**Comment by satyagupta09** [comment]
Thx.

We want to study the correlation between ECG data, BP data, Heart Rate,
Pulse waveform and Pulse Transit time.

ECG Waveforms are needed to extract key parameters from them.

Hope it explains.

Regards
Satya

**Comment by waqaraziz123** [comment]
Hi Satya,

You can start by looking at documentation of MIMIC Waveform:

https://archive.physionet.org/physiobank/database/mimic3wdb/

Thanks
