### ISSUE TITLE
Comorbidity query - issue casting to char(5)

### ISSUE THREAD

**Issue by bspiegel27** [MIT-LCP/mimic-code#599]
I am getting a syntax error when trying to use the comorbidity query in the concepts folder. Specifically my error reads: Syntax error: Expected ")" but got "(" at [20:56]

when running the below portion of the query. It seems like it's not recognizing the char(5) function and wants me to close off the CAST piece. I've googled around a bit, and tried using character(5), string(5) as well as the "create cast with function" format decsribed in documentation linked below. Still getting the same error. It passes fine if you just do char without the (5). Wondering if there is just a different/updated query format in postgres/bigQuery? I can't seem to find anything.

reference casting documentation:
https://www.postgresql.org/docs/11/sql-createcast.html

query:
WITH icd as
(
  select hadm_id, seq_num, cast(icd9_code as char(5)) as icd9_code
  from `physionet-data.mimiciii_clinical.diagnoses_icd`
)

**Comment by alistairewj** [comment]
There's no `CHAR` data type in BigQuery. It's all `STRING`. The main reason to use char data types in that query is to allow range comparisons, e.g. if I do `between '500  ' and '501  '` then the ICD code `'5005 '` is also matched. I don't know if this behavior occurs with BigQuery string types, but would be easy to check.

**Comment by fuzzyman27** [comment]
Ahhh I see thanks! I've tested this with strings and it works without utilizing substrings :)
