### ISSUE TITLE
Patient home address

### ISSUE THREAD

**Issue by guylivne12** [MIT-LCP/mimic-code#601]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by guylivne12** [comment]
Hi All,
We had developed an ML model based on Patient home location (Not address but town or neighbourhood), does anyone know if this information existed in MIMIC DB?
I could not find it in the Patient table or other tables.

Thanks,
Guy

**Comment by alistairewj** [comment]
That information is removed as the data has been de-identified.

**Comment by guylivne12** [comment]
Hi Alistair,
Thanks for your fast response.
We have developed an algorithm to anonymize addresses.
Our algorithm has been approved by the Helsinki committee at Hadassah
Medical Center in Israel.

Is there a possibility to use our python script to extract that data?

All the best,
Guy

**Comment by alistairewj** [comment]
Thanks for the offer, but we do not plan to release addresses, even in anonymized form.

**Comment by guylivne12** [comment]
Hi Alistair,
I understand the privacy issue of add addresses to public data sets.

From your knowledge,  Is there an option (here or another place) that I can
request for a specific data set that will include anonymized addresses?

All the best,
Guy
