### ISSUE TITLE
Predicting deterioration

### ISSUE THREAD

**Issue by bluetareqqq** [MIT-LCP/mimic-code#611]
Hello all;
I want to use MIMIC III to predict the deterioration (sudden death) of ICU patients using some predictor variables like age, gender, heart rate, glucose, sodium and many others.
I'm using postgtreSQL.
I want your help to write the code. I want the records for a period of 4 hours from admitting to the ICU for the first ICU admission only.
I will give the label of 1 to the patient who died during the period of 4 hours and 5 hours
I wrote this code but it give many readings for the same variable like heart rate at the same time for the same person, how come? and I made a limit of 5000, the 5000 readings were for only one patient.
Thanks in advance

**Comment by alistairewj** [comment]
Likely you have a bug in your code. We don't have the capacity to provide support for individual studies, but you may be interested in a few projects which create a similar prediction problem:

https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3benchmark
https://github.com/MLforHealth/MIMIC_Extract
https://gitlab.eecs.umich.edu/mld3/FIDDLE

**Comment by bluetareqqq** [comment]
Thanks for your reply. I will read these projects carefully
