### ISSUE TITLE
Oral and ETT suctioning in Mimic database

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#612]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

I am looking to find the Oral suctioning and ETT suctioning in Mimic database. Though I find the below items , I don't think they are related. I might be wrong as well. Can you let me know whether Mimic has it? 

This is the query that I tried which resulted in the below output. 

select distinct label from `physionet-data.mimiciii_clinical`.d_items where lower(label) like '%suct%'

![image](https://user-images.githubusercontent.com/30723825/64517273-91348d80-d322-11e9-8e21-fde72652cffa.png)
![image](https://user-images.githubusercontent.com/30723825/64517310-ac070200-d322-11e9-9495-010578cfbb2f.png)

**Comment by SSMK-wq** [comment]
@alistairewj  - Hi, I have decided to go based on the itemids shown below

![image](https://user-images.githubusercontent.com/30723825/66629765-59787880-ec35-11e9-8e19-bdc2bf48bfd4.png)

However, may I ask what does the `value = 1` and `value=0` mean for these items in the chartevents table as shown below?

![image](https://user-images.githubusercontent.com/30723825/66629930-b5430180-ec35-11e9-8050-a13df07fac08.png)

Does `value = 1` indicates suction is performed and `value=0` indicates otherwise?

If yes, then we shouldn't be seeing the `value=0` records in chartevents table.

I am sure I have got this wrong. Can you please help me understand this?

**Comment by alistairewj** [comment]
For the `itemid` that are >= 220000 you can look at the `param_type` column to get more info:

Row | itemid | label | param_type |  
-- | -- | -- | -- | --
1 | 226169 | Subglottal Suctioning | Checkbox |  
2 | 227807 | In-line Suction Catheter Changed | Checkbox

In this case it absolutely looks like 0 = 'no' and 1 = 'yes'.
