### ISSUE TITLE
mimic code issue

### ISSUE THREAD

**Issue by miffery** [MIT-LCP/mimic-code#614]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Hello，I am using Navicat Premium for postgresql. But when i copy the code to Navicat, it always indicated error. I do not konw how to solve this question.

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Please provide some sort of traceback or error log - can't help you otherwise!
