### ISSUE TITLE
Is there any SAS SQL code for severity scores - example for SOFA?  I am not familiar with postgreSQL.  Any indication/help is appreciated!

### ISSUE THREAD

**Issue by gmilky** [MIT-LCP/mimic-code#617]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Is there any SAS SQL code for severity scores - example for SOFA?  I am not familiar with postgreSQL.  I have tried to change some of the codes, but I failed. Any indication/help is appreciated!

**Comment by alistairewj** [comment]
No SAS code in this repo. There is postgresql by default and GCP BigQuery views in the GCP branch. Not sure what the differences are but since most code is standard SQL I'd hope that it's relatively straightforward to adapt (famous last words).
