### ISSUE TITLE
C-reactive protein (CRP), Troponin, Lactate and BNP missing data

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#620]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

I am trying to find the below items
a) c-reactive protein
b) Troponin
c) Lactate
d) BNP

and extract their values for ventilated patients. However when I use the below itemids, I see that more than 80% of the data is empty.

I am using the below item ids, 

227429    #troponin
851
51002
51003
-------
7294       #BNP
227446
225622 
50963
---------
5455       #Lactate  
1634
2638 
2773
30021
44370
45532
220955
220967
220968
220980
--------
`select subject_id, itemid,value from `physionet-data.mimiciii_clinical`.{chartevents|inputevents_mv|inputevents_cv|labevents} where itemid in (227444,220612,50889)`

Can you help?

**Comment by alistairewj** [comment]
These are all laboratory measurements. You should use the lab tables:

https://mimic.mit.edu/mimictables/labevents/
https://mimic.mit.edu/mimictables/d_labitems/

**Comment by SSMK-wq** [comment]
Yes,  I also checked in labevents(forgot to update in my query)  and found out that most of the records for these items are missing values. Am I right to understand that this is data issue?

**Comment by alistairewj** [comment]
Many labs are not ordered for patients as the care team feel they are not necessary.
