### ISSUE TITLE
A lot of time to execute 1_getItemIdList.ipynb and 4_filterItemId_chart.ipynb ?

### ISSUE THREAD

**Issue by ElAbedHoussem** [MIT-LCP/mimic-code#622]
I'm trying to execute file named **1_getItemIdList.ipynb** and **4_filterItemId_chart.ipynb** from the Benchmarking project 
**https://github.com/USC-Melady/Benchmarking_DL_MIMICIII**
My problem is, that this two scripts take a lot of time , I speek about days, and this is not normal.
For the file **4_filterItemId_chart.ipynb**  I tried to print the sql queries and to make a counter to track the number of the current iteration. I found after 2 days of execution that he is in the iteration number 642 of 6443 itarations this is not normal. 

this is the code of the file  :

`from __future__ import print_function

import psycopg2
import datetime
import sys
from operator import itemgetter, attrgetter, methodcaller
import numpy as np
import itertools
import os.path
import matplotlib.pyplot as plt
import math
from multiprocessing import Pool, cpu_count
import re

from utils import getConnection

conn = getConnection()
    
_adm = np.load('res/admission_ids.npy').tolist()
admission_ids = _adm['admission_ids']
admission_ids_txt = _adm['admission_ids_txt']

db = np.load('res/itemids.npy').tolist()
input_itemid = db['input']
output_itemid = db['output']
chart_itemid = db['chart']
lab_itemid = db['lab']
microbio_itemid = db['microbio']
prescript_itemid = db['prescript']

iiii=0

def stat_chart_unit_task(i, admission_ids_txt):
    global iiii
    print(iiii)
    iiii=iiii+1
    tconn = getConnection()
    # for each itemID select number of rows group by unit of measurement.
    tcur = tconn.cursor()
    tcur.execute('SELECT coalesce(valueuom, \'\'), count(*) FROM mimiciii.chartevents WHERE itemid = '+ str(i) +' and hadm_id in (select * from admission_ids) group by valueuom')
    chartunits = tcur.fetchall()
    chartunits = sorted(chartunits, key=lambda tup: tup[1])
    chartunits.reverse()
    print('SELECT coalesce(valueuom, \'\'), count(*) FROM mimiciii.chartevents WHERE itemid = '+ str(i) +' and hadm_id in (select * from admission_ids) group by valueuom')
    # count number of observation that has non numeric value
    tcur = tconn.cursor()
    tcur.execute('SELECT count(*) FROM mimiciii.chartevents WHERE itemid = '+ str(i) +' and hadm_id in (select * from admission_ids) and valuenum is null')
    notnum = tcur.fetchone()
    notnum = notnum[0]
    print('SELECT count(*) FROM mimiciii.chartevents WHERE itemid = '+ str(i) +' and hadm_id in (select * from admission_ids) and valuenum is null')
    # total number of observation
    tcur = tconn.cursor()
    tcur.execute('SELECT count(*) FROM mimiciii.chartevents WHERE itemid = '+ str(i) +' and hadm_id in (select * from admission_ids)')
    total = tcur.fetchone()
    total = total[0]
    print('SELECT count(*) FROM mimiciii.chartevents WHERE itemid = '+ str(i) +' and hadm_id in (select * from admission_ids)')
    tconn.close()
    return (i, chartunits, notnum, total)

print("before stat_chart_unit_task loop")
p = Pool(cpu_count() * 2)
results = [p.apply_async(stat_chart_unit_task, args=(i, admission_ids_txt)) for i in chart_itemid]
print("after stat_chart_unit_task loop")

p.close()
p.join()
results = [x.get() for x in results]
np.save('res/filtered_chart_raw.npy', {'raw': results})
print('saved!')

print("before filtered_chart_raw.npy")

results = np.load('res/filtered_chart_raw.npy').tolist()['raw']
valid_chart = []
valid_chart_unit = []
valid_chart_cate = []
valid_chart_num = []
dropped = []
multiple_units = []
for x in results:
    i, chartunits, notnum, total = x[0], x[1], x[2], x[3]
    
    # calculate percentage of the top frequent unit compared to all observation.
    total2 = 0
    unitnum = 0
    for c in chartunits:
        total2 += c[1]
        if c[0] != '':
            unitnum += 1
    if total2 == 0:
        continue
    percentage = float(chartunits[0][1]) / total2 * 100.
    if unitnum > 1:
        multiple_units.append((i, chartunits, percentage))
    print("CHART "+str(i) + "\t" + "{:.2f}".format(percentage) +'\t'+ str(chartunits))
    
    # if the percentage of numeric number is less, then dropped it, and make it categorical feature.
    percentage =float(total -notnum)*100 / total
    print("Numeric observation :" + "{:.4f}%".format(percentage)+ " ( NOTNUM= " + str(notnum) + " / ALL= " + str(total) + " ) ")
    if(percentage < 80): 
        print('dropped\n')
        dropped.append(i)
        continue;
    print('')
    valid_chart.append(i)
    valid_chart_unit.append(chartunits[0][0])

print("after filtered_chart_raw.npy")

print("before for")

for i, chartunits, percentage in sorted(multiple_units, key=lambda x: x[2]):
    total2 = sum([t[1] for t in chartunits])
    percentage = float(chartunits[0][1]) / total2 * 100.
    print("CHART "+str(i) + "\t" + "{:.4f}".format(percentage) +'\t'+ str(chartunits))

dropped_id = dropped
print(dropped_id, len(dropped_id))

def numerical_ratio(units):
    res = list(map(lambda unit: re.match(r'(\d+\.\d*)|(\d*\.\d+)|(\d+)', unit), units))
    numerical_ratio = 1.0 * len([1 for r in res if r is not None]) / len(res)
    return numerical_ratio

print("before for d in dropped_id")

dropped_value = []
for d in dropped_id:
    print('LAB : ' + str(d))
    cur = conn.cursor()
    cur.execute('SELECT value, valueuom, count(*) as x FROM mimiciii.chartevents as lb \
                WHERE itemid = '+ str(d) +' and hadm_id in (select * from admission_ids) GROUP BY value, valueuom ORDER BY x DESC')
    droped_outs = cur.fetchall()
    drop_array = []
    ct =0
    total = 0;
    for dx in droped_outs:
        total += dx[2]
    print("Count ",total)
    print([d[0] for d in droped_outs])
    print('Numeric ratio', numerical_ratio([str(d[0]) for d in droped_outs]))
    units = []
    for dx in droped_outs:
        ct+=1
        if(ct>20):
            break
        dx = list(dx)
        print(dx[1],dx[0],"\t",dx[2])
    print('')
    dropped_value.append((d, droped_outs))
    
np.save('res/chart_dropped_value.npy', dropped_value)

print("aftr for d in dropped_id")

print(len(dropped_id))
print(len(valid_chart), len(valid_chart_unit))
print(valid_chart)
print(valid_chart_unit)

np.save('res/filtered_chart.npy',{'id':valid_chart,'unit':valid_chart_unit})
# np.save('res/filtered_chart_cate',{'id':[223758],'unit':None})
print('saved!')

print("before chart_dropped_value.npy")

dropped_value = np.load('res/chart_dropped_value.npy').tolist()
valid_chart_num = []
valid_chart_num_unit = []
valid_chart_cate = []
valid_chart_ratio = []
for d, droped_outs in dropped_value:
    ascnum = 0
    rationum = 0
    for value, valueuom, count in droped_outs:
        value = str(value)
        isasc = re.search(r'(\d+\.\d*)|(\d*\.\d+)|(\d+)', value) is None
        isratio = re.fullmatch(r'{0}\/{0}'.format(r'((\d+\.\d*)|(\d*\.\d+)|(\d+))'), value) is not None
        if isasc:
            ascnum += 1
        if isratio:
            rationum += 1
    if ascnum / len(droped_outs) >= 0.5:
        valid_chart_cate.append(d)
    elif rationum / len(droped_outs) >= 0.5:
        valid_chart_ratio.append(d)
        print(droped_outs)
    else:
        valid_chart_num.append(d)
        if droped_outs[0][1] is None:
            valid_chart_num_unit.append('')
        else:
            valid_chart_num_unit.append(droped_outs[0][1])
#         print(droped_outs)
        
print(len(valid_chart_num), len(valid_chart_cate), len(valid_chart_ratio))
print(valid_chart_num, valid_chart_num_unit, valid_chart_ratio)

print("after chart_dropped_value.npy")

print(len(valid_chart_num), len(valid_chart_num_unit), len(valid_chart_cate))
print(valid_chart_num, valid_chart_num_unit, valid_chart_cate)
np.save('res/filtered_chart_num',{'id':valid_chart_num,'unit':valid_chart_num_unit})
np.save('res/filtered_chart_cate',{'id':valid_chart_cate,'unit':None})
np.save('res/filtered_chart_ratio', {'id': valid_chart_ratio, 'unit': None})

`

**Comment by alistairewj** [comment]
You should post this on their issue tracker: https://github.com/USC-Melady/Benchmarking_DL_MIMICIII
