### ISSUE TITLE
Are discharge medications in the prescriptions table?

### ISSUE THREAD

**Issue by bluewhale65** [MIT-LCP/mimic-code#623]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hi, it looks like the prescriptions table does not contain discharge medications. 
 I'd like to make it sure the way I can get some information on discharge medication is to extract it from discharge summary considering this link: https://github.com/mghassem/medicationCategories

**Comment by alistairewj** [comment]
Yep the best way to get discharge medications is to parse them out from the discharge summary.
