### ISSUE TITLE
Conversion of units for items to Find overall balance

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#624]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

I am trying to find the difference between input and output events of a subject. (overallbalance). 

I see "fluid balance" table in Mimic database but I believe that's only for crystalloid_bolus. 

but I also see "fluid_balance_staging" table. Can I know what does "rate_all" field indicate?

Anyway I also thought of doing it myself and came to know that all the input items should be in unit `ml/hr`. So I used the dosage help website [http://www.dosagehelp.com/iv_rate_ml_adv.html](url) to get the conversion rule. I applied this conversion rule for items with units other than `ml`. Is this correct?

The code that I used was 

`select *,
   (case when amountuom != 'ml' then (SAFE_DIVIDE(originalrate,amount)*originalamount) else amount end) as calc_amount from `mimic-251808.Team01`.ip_events `

But I see that some values are odd. For example, the below screenshot shows the values for certain items for subject_id = 124

![image](https://user-images.githubusercontent.com/30723825/66197932-ef5c5280-e6cd-11e9-9691-80f7c10a7e89.png)

I guess Propofol value is weird. Not sure whether I am making any mistake . This is how the table values looks like

![image](https://user-images.githubusercontent.com/30723825/66198082-3c402900-e6ce-11e9-9b7c-b86345a259af.png)

Has anyone tried doing this conversion before? 

Is there any resource in Mimic repository/can anyone guide on how to calculate this overall balance?

Thank you

**Comment by alistairewj** [comment]
The fluid balance tables are a work in progress!

However I think your calculation is wrong. Have you seen this page: https://mimic.physionet.org/mimicdata/io/

**Comment by SSMK-wq** [comment]
Got it. Thank you
