### ISSUE TITLE
Time for diagnoses

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#625]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

Hello, I'm wondering if the diagnoses in DIAGNOSES_ICD were ultimate ICU discharge diagnoses? What about the time for these diagnoses?

**Comment by alistairewj** [comment]
https://mimic.physionet.org/mimictables/diagnoses_icd/

> The ICD codes are generated for billing purposes at the end of the hospital stay.
