### ISSUE TITLE
Last Dialysis date missing data

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#626]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

I am trying to find the last dialysis date of the patients who had dialysis during their stay.

I see that we have table `RRT` derived table which will help us find out whether subjects had dialysis or not. (I found this through the description of query in GitHub). Am I looking at the right table?

Then I look for their `Last Dialysis` item (225128) and its date value in `DATETIMEEVENTS` table. (Checked for itemid in both d_items and d_labitems table)

But the counts doesn't match. For ex, for our cohort, we have around 456 people who had dialysis. However when I look for their `Last Dialysis` date in Datetimevents table, I only see them for ~120 patients. I was expecting to find records for last date of dialysis for all the subjects who had dialysis 

`SELECT distinct subject_id FROM 
`physionet-data.mimiciii_clinical.datetimeevents` WHERE SUBJECT_ID IN (
select DISTINCT a.subject_id from `mimic.table_1` a left join 
`physionet-data.mimiciii_derived.rrt` b
on a.subject_id = b.subject_id and a.icustay_id = b.icustay_id
WHERE b.RRT = 1)
AND itemid in (225128)
order by subject_id`

Inner query - results in 456 records
Outer query - results only around 120-130 records

**Questions**

1) Is datetimevents is the right table to look for last dialysis date?

2) Is the itemid to check for last dialysis right? I only have this based on the description of itemid (2251280) from d_items table.  Please note that `d_labitems` doesn't have any items related to last dialysis.

3) Doesn't the itemid (225128) which is `last dialysis` indicates the time of last dialysis of the patient? I see that same itemid is repeated for the patient multiple times in the same icu. 

4) if I look at `procedureevents_mv` table, the count is even lower for dialysis. I see only around 292 patients which doesn't tally with rrt (456)
Can you please correct me if I am making any mistakes?

**Comment by alistairewj** [comment]
There is a field documented called "last dialysis" but that does not mean that all dialysis sessions are recorded there. It's also worth noting that the field is only available for MetaVision patients (half the database). I'd read through and adapt the RRT query to fit your needs. It essentially aggregates information related to dialysis from various sources in the data to try to infer when a patient is undergoing dialysis. Of course this will only work for dialysis sessions occurring in the ICU.

**Comment by SSMK-wq** [comment]
Thank you

**Comment by alistairewj** [comment]
All patients are in the query - if you scroll down you'll see queries for metavision patients.

**Comment by SSMK-wq** [comment]
@alistairewj - Sorry, my bad. Actually my question was about the below db source. I see that we have `inputevents_mv` and `input_events_cv` etc

![image](https://user-images.githubusercontent.com/30723825/66480508-72681900-ead1-11e9-97c6-dc9da4ddd4f0.png)

Why do we have to filter by `db.source` here?

**Comment by alistairewj** [comment]
Ah that's just to limit that subquery to carevue patients. But the MetaVision patients are handled later in a different subquery (`mv_ce`).

**Comment by SSMK-wq** [comment]
Thank you for the response. Much appreciated
