### ISSUE TITLE
I'm not able to get access to the MIMIC II Clinical Database

### ISSUE THREAD

**Issue by wenh06** [MIT-LCP/mimic-code#627]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I've got credentialed for the MIMIC III Clinical Database and signed the agreement. It is written in the documents that I would automatically get access to the MIMIC II database if I had access to the MIMIC III database. However, on [this page](https://archive.physionet.org/works/MIMICIIClinicalDatabase/), I'm not able to log into my account following the link in `Authorized users may enter [here](https://archive.physionet.org/works/MIMICIIClinicalDatabase/files/)`.  (I'm sure that my username and password are correct).

**Comment by alistairewj** [comment]
Why do you need access to MIMIC-II? Are you aware that MIMIC-III is essentially a superset?

**Comment by wenh06** [comment]
> Why do you need access to MIMIC-II? Are you aware that MIMIC-III is essentially a superset?

Yes, I'm aware of it. 

The reason why I need access to MIMIC-II is that for both II and III, correspondences between the clinical data and waveform data have been partly established (the matched subsets). But whether there are correspondences between MIMIC-II waveform data and MIMIC-III clinical data is not known to me. At least I'm not able to find any form of document explicitly dealing with this problem. 

I've downloaded and processed the MIMIC-II waveform database previously, which was quite time consuming. If I could have access to the MIMIC-II clinical database, or if I could get some knowledge about the correspondences between MIMIC-II waveform data and MIMIC-III clinical data, then my previous work could be reused.

Thank you very much for your reply!

**Comment by alistairewj** [comment]
The MIMIC-III waveform database is also a superset of the MIMIC-II waveform database (depending on what version you use, but I assume the latest). The matched subset is essentially a set of headers with clinical information and symlinks to the original waveform .dat files.

**Comment by wenh06** [comment]
> The MIMIC-III waveform database is also a superset of the MIMIC-II waveform database (depending on what version you use, but I assume the latest). The matched subset is essentially a set of headers with clinical information and symlinks to the original waveform .dat files.

Got it. Thanks.

**Comment by Quershi** [comment]
@wenh06   Hi,
Now you access completely MIMIC-ii  Clinical data set. and how.  ??????

**Comment by tompollard** [comment]
@Quershi MIMIC-II is no longer available. MIMIC-II is a subset of MIMIC-III, the latest version of the database, so we suggest that you use this version instead. 

For instructions on getting access to MIMIC-III, see: https://mimic.physionet.org/gettingstarted/overview/.

Essentially you just need to follow the steps in the "Files" section of the PhysioNet project to request access: https://physionet.org/content/mimiciii/1.4/
