### ISSUE TITLE
Can't seem to find where PCI and Surgeries are recorded in the database

### ISSUE THREAD

**Issue by eyamga** [MIT-LCP/mimic-code#630]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

*Issue* : I can't seem to identify CABG surgeries nor coronary interventions (PCI) in the MIMIC database.

* what you have tried :
I have opened the ITEMID database and NONE of the codes correspond to such interventions that means that those events were not recorded in the chartevents or inputevents or rhe procedureevents_mtable.

However, I know that those events are coded in the D_ICD_PROCEDURES dictionary.
I could therefore probably identify those events in the procedures_icd table.
But this table does not contain a time column.

Is there a way to get the timing information for those events?

Thank you.

**Comment by alistairewj** [comment]
Currently times are not available for `procedures_icd`. The only information available is the order of the procedures.
