### ISSUE TITLE
I want to use Gephi with MIMICIII database. Any example?

### ISSUE THREAD

**Issue by inigolea** [MIT-LCP/mimic-code#633]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, 

Could someone give me some example of using MIMICIII in the Gephi application?
 
Thanks.

**Comment by alistairewj** [comment]
Perhaps #341 is relevant?
