### ISSUE TITLE
No relationships were detected in the schema with SchemaSpy

### ISSUE THREAD

**Issue by ZhiliangWu** [MIT-LCP/mimic-code#636]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried

I am trying to build locally the ERD like the mimic [SchemaSpy](http://schemaspy.org/) as posted [here](https://mit-lcp.github.io/mimic-schema-spy/). I tried both the old version ([5.0.0](http://schemaspy.sourceforge.net/)) and newer version of SchemaSpy ([6.1.0](https://github.com/schemaspy/schemaspy/releases/tag/v6.1.0)) on both the complete mimic and the mimic-demo databases installed locally. However, things worked good except that there is no relationships were detected after running the code as shown below. 
![image](https://user-images.githubusercontent.com/18686697/67867613-f5a5e900-fb2a-11e9-8da7-f662c955517d.png)
![image](https://user-images.githubusercontent.com/18686697/67866532-61875200-fb29-11e9-857c-df3e51046aba.png)
Are there any tricks we should take so as to make it work?

* queries demonstrating your question (if applicable)
```bash
$ java -jar schemaspy-6.1.0.jar -t pgsql -dp ../postgresql-42.2.8.jar -db mimic_demo -host localhost -port 5432 -s mimiciii -u xxxxxxxx  -p xxxx -o ./results -hq
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on xxxxxxxx with PID 23252 (/home/xxxxxxxx/Downloads/schema/schemaspy-6.1.0.jar started by xxxxxxxx in /home/xxxxxxxx/Downloads/schema)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.362 seconds (JVM running for 1.764)
INFO  - Starting schema analysis
INFO  - Connected to PostgreSQL - 9.6.15
INFO  - Gathering schema details
Gathering schema details...............................................(120sec)
Connecting relationships...............................................(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
INFO  - Graphviz rendered set to ''
........(2sec)
Writing/diagramming detailsINFO  - Completed summary in 2 seconds
INFO  - Writing/diagramming details
............................................(0sec)
Wrote relationship details of 44 tables/views to directory './results' in 123 seconds.
View the results by opening ./results/index.html
INFO  - Wrote table details in 0 seconds
INFO  - Wrote relationship details of 44 tables/views to directory './results' in 123 seconds.
INFO  - View the results by opening ./results/index.html

```

**Comment by alistairewj** [comment]
Yes - the script drops constaints *if* they exist. If they don't exist (as in your case), it warns you that it didn't drop anything. SchemaSpy uses the constraints to infer relationships which is why nothing showed up before you created them.
