### ISSUE TITLE
issue with itemid in d_items table

### ISSUE THREAD

**Issue by yedide** [MIT-LCP/mimic-code#638]
### Prerequisites

[ X] Put an X between the brackets on this line if you have done all of the following:
Checked the online documentation: https://mimic.physionet.org/about/mimic/
Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Dear all,

I have just started to use MIMIC III (in AWS) and I'm trying to link chartevents with d_items tables through 'itemid' key
However I figured out that itemid was not avaible in d_items.
Does someone have the same kind of issue?
Many thanks for your help!

**Comment by alistairewj** [comment]
Could you provide example code and the output?

**Comment by yedide** [comment]
A basic 'select' statement:

select ITEMID from mimiciii.d_items  limit 100

I get this error : 
_SYNTAX_ERROR: line 1:8: Column 'itemid' cannot be resolved_

Do you know if there are some specifities in the MIMIC datasets distributed on AWS ?

**Comment by alistairewj** [comment]
MIMIC on AWS is accessed via AWS Athena. Have you followed the instructions in this blog post?

https://aws.amazon.com/blogs/big-data/perform-biomedical-informatics-without-a-database-using-mimic-iii-data-and-amazon-athena/

**Comment by yedide** [comment]
Sure I worked on this database using these instructions. 
Everything works well. The only issue that I have is that when I explore the **d_items** table, here are the columns available:
- row_id (int)
- icd9_code (int)
- label (string)
- abbreviation (string)
- dbsource (string)
- linksto (string)
- category (string)
- unitname (string)
- param_type (string)
- conceptid (int)

I don't see _itemid_ available.
thanks for your help!

**Comment by alistairewj** [comment]
OK thanks for the quick feedback. I just checked and there was a mistake in the cloud formation template which named the `itemid` column as `icd9_code`. I'll reach out to AWS to get this fixed, but in the meantime you'll need to re-run the glue job with an updated yaml file. if you go back to the blog post and click "Launch Stack", change the template location (Amazon S3 URL box) to: https://raw.githubusercontent.com/MIT-LCP/mimic-code/master/buildmimic/aws-athena/mimic-iii-athena.yaml

Should look something like this:

![image](https://user-images.githubusercontent.com/1282676/67953607-d5773800-fbc5-11e9-9643-b3dfdd5d5f71.png)

After you re-run it the `itemid` column should appear in d_items.

**Comment by yedide** [comment]
I just re-run the Launch Stack with this updated yaml file but I still doesn't get the itemid variable:

![pic](https://user-images.githubusercontent.com/51092008/67956493-7bda3200-fbf4-11e9-8aeb-531fd278b160.png)

**Comment by yedide** [comment]
Thanks for your answer.
I tried to relaunch the stack button with the updated yaml file (after removing the previous version)
I still get the error :
![pic2](https://user-images.githubusercontent.com/51092008/67957382-cc05c400-fbf5-11e9-9dc3-e9067df58ec9.png)

**Comment by alistairewj** [comment]
Changing the yaml should have worked... maybe just rename the `icd9_code` column you have in d_items to `itemid`.

**Comment by alistairewj** [comment]
Ah actually if you check now you should see the column is correctly labeled.

**Comment by yedide** [comment]
Hi Alistair

Thanks a lot for your help on this!!
Also, do you know why CATEGORY variable is not available in the current version of the NOTEEVENTS table (in the AWS version), where it is mentionned in the table description in the [website](https://mimic.physionet.org/mimictables/noteevents/)
