### ISSUE TITLE
the amount of dialysis ultrafiltration in mimic 

### ISSUE THREAD

**Issue by hhchang0210** [MIT-LCP/mimic-code#639]
Hi,
Thanks for your contribution so that I can get dialysis patients from mimic.
But I have a problem about how to get  amount of dialysis ultrafiltration.
I searched mimic database by
```
select *
from mimiciii.D_ITEMS
where lower(label) like '%ultra%'
```
I got resulted and filtered what I look like dialysis ultrafiltration

44349 | ultrafiltrate in |   | carevue | outputevents
44890 | ultrafiltrate |   | carevue | outputevents
43703 | ULTRAFILTRATE |   | carevue | outputevents
226457 | Ultrafiltrate Output | Ultrafiltrate Output | metavision | chartevents | Dialysis
42464 | hemodialysis ultrafe |   | carevue | outputevents
40286 | Ultrafiltrate Ultrafiltrate |   | carevue | outputevents
HD Ultrafiltrate |   | carevue | outputevents
ultrafiltrate out |   | carevue | outputevents
hemo dial ultrafil |   | carevue | inputevents_cv

I get all the data from those columns. But I am not sure it is correct or not.
I can't find detailed explanations for those items. How can I know the explanations for them? Or Is there any way that I can get dialysis ultrafiltration data?

Thanks.

**Comment by alistairewj** [comment]
The best way to understand a concept represented by an itemid is to explore the data collected for it and around it, e.g.:

- how many patients have data for this itemid? is that what I expect?
- what is the distribution of values for this itemid?
- what other itemid are recorded at a the same time?
- are there patients where I expect them to have this data, but they do not?
