### ISSUE TITLE
Interpreting vasopressor dosing from MIMIC

### ISSUE THREAD

**Issue by eyamga** [MIT-LCP/mimic-code#642]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi all,

I have trouble interpreting the dosing in terms of unit from the different MIMIC sql queries from the LCP repository. I am referring to dobutamine-dose.sql,  noreepinephrine-dose.sql, etc.

Does queries return amount and rate but I have trouble understanding the unit.
This is critical because the way the amount of a pressor is described clinically varies from one drug to another.

Thank you for clarifying this in advance,

Eric

**Comment by alistairewj** [comment]
I normalized the rates to roughly what you would expect - most vasopressors are in mcg/kg/min except vasopressin which is in units/hr. Unfortunately for CareVue patients the vasopressin unit is pretty unreliable so some caution is advised when using that data. We could think about applying some sensible rules (e.g. if it's < 0.1 then it's in units/min, or if it's > 1 then it's in units/hr, or something clinically meaningful like that). Or cross-reference with the amount actually received and determine the unit based upon that.
