### ISSUE TITLE
Lymphocytes and monocytes value and units mismatch?

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#643]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

I am trying to find the lymphocyte and monocyte count. I was able to see that we have only `percentage` values of these. So, I decided to calculate the count based on the formula [https://www.omnicalculator.com/health/lymphocyte-count](url)

However, what I wanted to confirm is can the lymphocytes percentages be as low as `1.0,2.7,3.0` etc etc. Can the percentage values of lymphocytes be too low?

itemids used for lymphocyte - 51375,51427,51446,51116,51244,5124

itemids used for monocyte - 51355,51379,51120,51253,51254

I also verified for the units and found that records with the above itemids only has `%` as valueuom.

So, can you confirm whether these are valid values or it could be a mix of Lymphocyte count and Lymphocyte percentage though the unit indicate it is a %? Have you dealt with this before ? Do you have any suggestions on how to handle this? Based on my research online, I find that lymphocyte percentage range is usually 20-40 pc.  My interpretation of value as crude percentage value is incorrect?

`SELECT label FROM `physionet-data.mimiciii_clinical.d_labitems` where itemid in (51355,51379,51120,51253,51254)`

`SELECT label FROM `physionet-data.mimiciii_clinical.d_labitems` where itemid in(51375,51427,51446,51116,51244,5124)`

`select distinct valueuom FROM `physionet-data.mimiciii_clinical.labevents` where itemid in(51375,51427,51446,51116,51244,5124)`

`select distinct valueuom FROM `physionet-data.mimiciii_clinical.labevents` where itemid in(51355,51379,51120,51253,51254)`

**Comment by alistairewj** [comment]
How often does it happen?

**Comment by SSMK-wq** [comment]
In my sample, around 80 pc of the data is less than 20 percent for lymphocytes. My sample only has patients who are MV

**Comment by alistairewj** [comment]
OK - in general you should *not* combine `itemid` for labs and be very careful! Re-read this page: https://mimic.physionet.org/mimictables/d_labitems/

> As the laboratory data is acquired from the hospital database, the data is consistent across all years in the database. Consequently, there is usually only one ITEMID associated with each concept in the database. Furthermore, the data contains information collected in departments outside the ICU. This includes both wards within the hospital and clinics outside the hospital. Most concepts in this table have been mapped to LOINC codes, an openly available ontology which provides a rich amount of information about the laboratory measurement including reference ranges, common units of measurement and other further detail regarding the measurement.

Also note that each itemid is associated with a `label`, *and* a `fluid`/`category`. Take a look at your `itemid` with the full table:

```sql
select * from `physionet-data.mimiciii_clinical.d_labitems`
where itemid in (51375,51427,51446,51116,51244)
```


Row | ROW_ID | ITEMID | LABEL | FLUID | CATEGORY | LOINC_CODE |  
-- | -- | -- | -- | -- | -- | -- | --
1 | 575 | 51375 | Lymphocytes | Joint Fluid | Hematology | 26483-8 |  
2 | 627 | 51427 | Lymphocytes | Other Body Fluid | Hematology | 11031-2 |  
3 | 646 | 51446 | Lymphocytes | Pleural | Hematology | 26481-2 |  
4 | 316 | 51116 | Lymphocytes | Ascites | Hematology | 26482-0 |  
5 | 444 | 51244 | Lymphocytes | Blood | Hematology | 731-0

**Comment by SSMK-wq** [comment]
Yes, I am looking for blood/serum related lymphocytes. Even with this, I find values less than 20 - 40 %

values are in the order that min_lympho,max_lympho,min_mono,max_mono, min_neit, max_neut,min_wbc,max_wbc

![image](https://user-images.githubusercontent.com/30723825/68523113-54b7ea80-02ef-11ea-85b7-b5f9ae7d4714.png)

**Comment by zhidehu** [comment]
I am a laboratory clinician. To my experience, patients with lymphocyte pecentage less than 20% is common in clinical practice and when lymphocyte is extremely low, 0% is the reported value.
