### ISSUE TITLE
Is the exact time shifted in mimic?

### ISSUE THREAD

**Issue by DogarXu** [MIT-LCP/mimic-code#644]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hi, I knew that all date in the mimic database has been shifted to protect patients. I am researching circadian rhythms. So I am wondering whether the exact time (like "CHARTTIME" in "labevents" table) has been shifted? That is to say, for example, "06:31:00" does not mean 06 am but another time? Thank you!

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
The exact time is presserved. From the [MIMIC-III paper](https://www.nature.com/articles/sdata201635):

> In particular, dates were shifted into the future by a random offset for each individual patient in a consistent manner to preserve intervals, resulting in stays which occur sometime between the years 2100 and 2200. Time of day, day of the week, and approximate seasonality were conserved during date shifting. Dates of birth for patients aged over 89 were shifted to obscure their true age and comply with HIPAA regulations: these patients appear in the database with ages of over 300 years.

I have updated the docs to be clearer: https://mimic.physionet.org/mimicdata/time/

**Comment by DogarXu** [comment]
Thank you for your reply!

Xu

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Alistair Johnson <notifications@github.com>
发送时间: Tuesday, November 12, 2019 1:17:24 PM
收件人: MIT-LCP/mimic-code <mimic-code@noreply.github.com>
抄送: DogarXu <zhaoxu109@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [MIT-LCP/mimic-code] Is the exact time shifted in mimic? (#644)


Closed #644<https://github.com/MIT-LCP/mimic-code/issues/644>.

―

**Comment by qomhmd** [comment]
Is this the same in MIMIC-IV?

**Comment by qomhmd** [comment]
Is this the same in MIMIC-IV?
