### ISSUE TITLE
can RRT = 0 still have dialysis date?

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#645]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

I was trying to find the time of the dialysis. For which I was trying to adapt the `RRT` query. I was able to see that some of the patients though they have `RRT` flag as `0`, I was still able to see/get info on their dialysis date based on the chartitems used in RRT query. I believe dialysis is part of RRT (which is the umbrella term). So when RRT = 0, doesn't it mean that there is no dialysis done for the patient during his stay in the hospital as a whole? I am sharing the modified query that I wrote to get the date of dialysis (first/min date of dialysis). Not sure whether my query is incorrect.  Since there are multiple items chosen to set `RRT=1 or RRT=0`, i think we can only choose `max(charttime) or min(charttime)`.  Can you help me with this?

You can also see a sample output at the bottom after query 

with cv_ce as
(
  select ie.icustay_id
    , max(
        case
          when ce.itemid in (152,148,149,146,147,151,150) and value is not null then 1
          when ce.itemid in (229,235,241,247,253,259,265,271) and value = 'Dialysis Line' then 1
          when ce.itemid = 466 and value = 'Dialysis RN' then 1
          when ce.itemid = 927 and value = 'Dialysis Solutions' then 1
          when ce.itemid = 6250 and value = 'dialys' then 1
          when ce.itemid = 917 and value in ('+ INITIATE DIALYSIS','BLEEDING FROM DIALYSIS CATHETER','FAILED DIALYSIS CATH.','FEBRILE SYNDROME;DIALYSIS','HYPOTENSION WITH HEMODIALYSIS','HYPOTENSION.GLOGGED DIALYSIS','INFECTED DIALYSIS CATHETER') then 1
          when ce.itemid = 582 and value in ('CAVH Start','CAVH D/C','CVVHD Start','CVVHD D/C','Hemodialysis st','Hemodialysis end') then 1
        else 0 end
        ) as RRT, max(charttime) as dia_date                                   # this could be min(charttime) as well
  from `physionet-data.mimiciii_clinical.icustays` ie
  inner join `physionet-data.mimiciii_clinical.chartevents` ce
    on ie.icustay_id = ce.icustay_id
    and ce.itemid in
    (
       152 -- "Dialysis Type";61449
      ,148 -- "Dialysis Access Site";60335
      ,149 -- "Dialysis Access Type";60030
      ,146 -- "Dialysate Flow ml/hr";57445
      ,147 -- "Dialysate Infusing";56605
      ,151 -- "Dialysis Site Appear";37345
      ,150 -- "Dialysis Machine";27472
      ,7949 -- "Calcium for CVVH"
      ,229 -- INV Line#1 [Type]
      ,235 -- INV Line#2 [Type]
      ,241 -- INV Line#3 [Type]
      ,247 -- INV Line#4 [Type]
      ,253 -- INV Line#5 [Type]
      ,259 -- INV Line#6 [Type]
      ,265 -- INV Line#7 [Type]
      ,271 -- INV Line#8 [Type]
      ,582 -- Procedures
      ,466 -- Nursing Consultation
      ,917 -- Diagnosis/op
      ,927 -- Allergy 2
      ,6250 -- lt av fistula
    )
   and ce.value is not null
  where ie.dbsource = 'carevue'
  -- exclude rows marked as error
  and (ce.error = 0 or ce.error is null)
  group by ie.icustay_id
)
select * from cv_ce

I am showing a sample output and you can see that `RRT =0`, I was still able to get dialysis date.

![image](https://user-images.githubusercontent.com/30723825/71244157-dc603280-234c-11ea-8241-becb933c220a.png)

**Comment by SSMK-wq** [comment]
Hello @alistairewj  - Do we have any updates on this? Or I am interpreting it incorrectly?

**Comment by SSMK-wq** [comment]
@alistairewj - can you please share your views on this issue? I rewrote my queries few times but still I get the dates... So unable to find where I an making mistake? Is my query incorrect?

**Comment by alistairewj** [comment]
I haven't taken a look at these because I went ahead and tried to re-do the dialysis queries entirely. You can take a look at https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted-rrt.sql

Still a work in progress but I think it's an improvement over the `rrt.sql` query which just looked for anything mentioning the word dialysis, and didn't have any logic to ensure it was currently active and occurring at the associated `charttime`.

**Comment by SSMK-wq** [comment]
Thanks for this SQL query and your help in answering my questions. Will look at this query

**Comment by SSMK-wq** [comment]
@alistairewj  - I understand this is closed based on my comment. But I just have one quick question. I see that we have two columns `dialysis_present` and `dialysis_active`. I also see that we have chartime column as well. Am I right to understand that if I see "dialysis_active = 1", then the dialysis has happened at the corresponding charttime given in that record? But what does "dialysis present=1" and their corresponding charttime indicate?

**Comment by alistairewj** [comment]
I used dialysis present to flag a setting that implied dialysis but did not imply that it was ongoing (`dialysis_present` = 1). For example documentation about a dialysis catheter implies the patient has or will be finalized, but it doesn't mean it is active at that time. However, documentation of a dialysate flow rate implies the dialysis is active (`dialysis_active` = 1).

When I am identifying dialysis administration I just filter to the active rows.
