### ISSUE TITLE
Numerics Data in MIMIC-III Waveforms

### ISSUE THREAD

**Issue by waqaraziz123** [MIT-LCP/mimic-code#646]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi Alistair,

I am working with numerics data (1Hz) within MIMIC-III waveforms and was wondering which devices were used in hospital to record Heart Rate from 2008 to 2012?

Is it the Philips or Metavision?

Thanks

**Comment by alistairewj** [comment]
Numerics are recorded by Philips monitors.
