### ISSUE TITLE
Determine the time of diagnosis

### ISSUE THREAD

**Issue by lequangbkhn** [MIT-LCP/mimic-code#651]
Hi,
I am working on a project to predict the early onset of acute renal failure. But in MIMIC-III all diagnoses are made at the end of each admission. So are there any ways that I can accurately determine the onset of acute renal failure? Is there any calculation to determine it?
Thanks!

**Comment by alistairewj** [comment]
Best bet is KDIGO in the concepts/organfailure folder!

**Comment by lequangbkhn** [comment]
Thanks Alistair.
