### ISSUE TITLE
Indication of need for chronic RRT?

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#652]
First of all, I hope thats the right place for questions that do not relate directly to coding; my apologies if not.

Is there any way to know about the need for chronic-RRT (i.e. more than 3 months) which usually continue after the current hospitalisation?

**Comment by alistairewj** [comment]
Not really unfortunately. The only out of hospital information that we specifically collect is date of death from social security records.

**Comment by arielhasidim** [comment]
Thank you very much!
