### ISSUE TITLE
APS III  severity score VS APACHE

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#653]
Is API-III is meant to be the same as APACHE-III?
(mimic-code/concepts/severityscores/apsiii.sql)

And if so, is "age" also part of the equation?
@etheleon @alistairewj

**Comment by alistairewj** [comment]
APS-III is the physiology score. APACHE-III is the physiology score plus additional points for comorbidities and age.

**Comment by arielhasidim** [comment]
Thank you very much!
