### ISSUE TITLE
Interest in having SQLite files?

### ISSUE THREAD

**Issue by tiagofassoni** [MIT-LCP/mimic-code#654]
Hello.

I am a teacher of data science and students of mine want to use the mimic dataset. However, they do not have the expertise to set up a postgresql database.

I am making a sqlite database for them and want to ask you guys if there is any interest in having another database in the build files

**Comment by tiagofassoni** [comment]
This ended up being all the code needed to create a database in SQLite (using Python):

Of course, it lacks indexes and verification. But could be a good basis for a SQLite file ready to query.

```python
import pandas as pd
from glob import glob

for item in glob('*.csv'): 
    table_name = item.split('.')[0].lower()
    print('Started import of {}'.format(item))
    pd.read_csv(item, low_memory=False).to_sql(table_name, 'sqlite:///mimic.db', if_exists='replace')  
    print('Finished import of {}'.format(item))
```

**Comment by alistairewj** [comment]
Of course! PRs welcome!

**Comment by alistairewj** [comment]
Feel free to open a PR if you make progress.

**Comment by tiagofassoni** [comment]
Sorry about the delay, but it is done #697
