### ISSUE TITLE
How does baseline creatinine is calculated?

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#656]
Hello,
I want to use the KDIGO score for AKI, and also do some of my own manipulation with baseline-sCr. 

1. What is the indication for baseline-sCr in the KDIGO concept code?
2. How does the clinicians in Beth-Israel's ICU get this value for making a decision?

Thanks ahead :)

**Comment by alistairewj** [comment]
Check out #584 for some info on the most recent implementation of KDIGO.

1. Baseline is defined as the lowest value in the last 7 days. This is reasonably consistent with KDIGO, which states baseline "...is known or presumed to have occurred within the prior 7 days"
2. I'm sure it's the usual medical data answer - they use whatever system lets them get it :)

**Comment by arielhasidim** [comment]
Pleasure as always.
Thank's man :)
