### ISSUE TITLE
Fluid balance acceptable range

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#660]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

1) May I know what is the acceptable value range for fluid balance per day?

Currently my fluid balance calculated range from values like `-30000 to +35000 ml`?

Some examples given below

![image](https://user-images.githubusercontent.com/30723825/71796851-be9e0780-3086-11ea-8388-7f43ab6659d5.png)

I encounter this for around 153 patients in my dataset of size 4712. Rest of the observations are within `-10K to +10K` ml. I read online and in some forums that it could be possible due to `diarrohea` etc 

So, would like to know whether these values are valid (possible) ? Or it's data calculation issue? 

2) Which `unit` column should I be referring to in the `inputevents_mv` and `inputevents_cv` table? I currently look at `amountuom` column. Is this the right column to look for `ml` records?

3) All outputevents records are in `ml` and there is nothing that I did to this table

Can you let me know whether this is possible or am I doing any mistake during calculation?

**Comment by alistairewj** [comment]
10-20 litres in a day is extreme, and would only really happen during/after a major surgery. I would check the `itemid` you are using - many of them are documenting past inputs/outputs (e.g. "OR TBL" for total blood loss in the operating room).

**Comment by SSMK-wq** [comment]
Hi @alistairewj ,

If you look at the below screenshot, these are the items that I am using for input fluids. 

![image](https://user-images.githubusercontent.com/30723825/72145244-12855500-33d5-11ea-86c2-bad0f5c3ead0.png)


For output items, I am using the below item ids

![image](https://user-images.githubusercontent.com/30723825/72145293-2af56f80-33d5-11ea-8b94-2200757322cb.png)

**Comment by alistairewj** [comment]
No look at the items labeled "OR" and "PACU". Those are documenting fluid administrations from a past unit (operating room and post anaesthesia).

**Comment by SSMK-wq** [comment]
Hi @alistairewj , Thanks for the response. I will ignore the itemids with labels "OR" and "PACU" then. Appreciate your time and inputs
