### ISSUE TITLE
Where can I find interleukin in database?

### ISSUE THREAD

**Issue by Brandon96-lab** [MIT-LCP/mimic-code#663]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

I want to  look up the value of interleukin(such as IL-1 & IL-10)of the patients, but I couldn't find them as I look over the label in d_labitems table. Did I ignore something important? Wish your help, thanks.

**Comment by alistairewj** [comment]
I don't think interleukin measures were common during the period of time MIMIC-III is collected, so I'm not surprised that you were unable to find them.

**Comment by alistairewj** [comment]
Just checked our most recent dumps (post MIMIC-III) and didn't find it so I don't think it's measured in-house at the BIDMC.
