### ISSUE TITLE
SOFA score calculation for Respiration system

### ISSUE THREAD

**Issue by onlyzdd** [MIT-LCP/mimic-code#664]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, I'm trying to calculate SOFA scores and found your [pivoted-sofa.sql](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted-sofa.sql) helpful. However, I'm concerned about the Respiration part for SOFA calculation. To be specific,

https://github.com/MIT-LCP/mimic-code/blob/dc1ed8ad47a362efccf8c5fa739b6e7dbab16361/concepts/pivot/pivoted-sofa.sql#L195-L202

For example, if `PaO2FiO2Ratio_vent` for a patient is 250, then the `respiration` score is `0` using this formula. Is that what we expect?

I'm not very familiar with this and I'm wondering whether we need to consider `PaO2FiO2Ratio_vent` in Line 198-199. Could you please help? Thanks.

**Comment by alistairewj** [comment]
For myself reading the paper it was unclear whether a PaO2/FiO2 > 200 when a patient was ventilated should be considered as organ failure. It's a bit like GCS when a patient is sedated; you can document it as 3, but it might not actually represent the degree of organ dysfunction. I could definitely see an argument going the other way though. Happy to hear your thoughts!

Here's the original paper for reference: [The_SOFA_Sepsis-related_Organ_Failure_Assessment_s.pdf](https://github.com/MIT-LCP/mimic-code/files/4043092/The_SOFA_Sepsis-related_Organ_Failure_Assessment_s.pdf)

**Comment by onlyzdd** [comment]
Thank you. @alistairewj I totally agree with you. However, it get me confused as I find some online tools are following different calculation logics.
FYI, links for online tools: [SOFA score - MDCalc](https://www.mdcalc.com/sequential-organ-failure-assessment-sofa-score), [SOFA calculator - ClinCalc](https://clincalc.com/IcuMortality/SOFA.aspx), [SOFA Calculator by QxMD](https://qxmd.com/calculate/calculator_268/sequential-organ-failure-assessment-sofa).

**Comment by jsbhat** [comment]
As far as I understood, for PaO2/FiO2 ratio of 250 with mechanical ventilation, the severity score should be 2 and not 0. The lungs haven't fully failed yet but is failing. The basic idea, I believe, for scores 3+ is that adequate oxygenation couldn't be maintained despite ventilation. Both conditions (hypoxemia and ventilation) should be satisfied for scores 3+

Check out some notes from the original author: https://www.mdcalc.com/sequential-organ-failure-assessment-sofa-score#pearls-pitfalls
