### ISSUE TITLE
Availability of operation info in Mimic data

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#665]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

I would like to know whether info about patient's `operation` is available in Mimic?

I mean for examples, patients admitted to `surgery discipline/service` may not have always undergone surgery/operation. So is it possible to find whether `operation` was done for the patient or not?

**Comment by alistairewj** [comment]
To identify surgeries performed I'd look for the procedure in the PROCEDURES_ICD - I think the AHQR have some useful mappings for it: https://www.hcup-us.ahrq.gov/toolssoftware/surgeryflags_svcproc/surgeryflagssvc_proc.jsp
