### ISSUE TITLE
 Time problems in admissions

### ISSUE THREAD

**Issue by Delia5353** [MIT-LCP/mimic-code#666]
I found that several patients' deathtime earlier than the admittime in the admissions table . I would like to ask if this is a recording error or what is the reason?

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
There are a few instances of this, and usually these are organ donor accounts. If you look at the `diagnosis` field in the admission table, it denotes whether the admission was for organ donation.
