### ISSUE TITLE
Bed tilt/Inclination info for patients

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#667]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

Does Mimic have the `Head bed elevation` info? I mean info on ` angle in which the bed is tilted` ?

I see that we have `supine` and `prone`. But is that all? 

Will we be not able to find values like `30 degree tilt, 45 degree tilt, semireincumbent position, Trendelenburg, Antitrendelenburg etc? I guess usually mechanically ventilated patients will have 30-45 degree bed tilt. Right? 

Where can I get this info?  Is there any specific itemid that I should be looking for?

Currently when I execute the below query, I could find `supine` and `prone` as one of the values but do we also get tilt info?

`select distinct value from `physionet-data.mimiciii_clinical.chartevents` where itemid in (SELECT distinct itemid FROM `physionet-data.mimiciii_clinical.d_items` WHERE LABEL LIKE '%bed%')`

With some keyword search like above, I couldn't find them

Can you help in finding the relevant ids if they exist?

**Comment by alistairewj** [comment]
Be careful about case sensitivity in queries. You are looking for `bed`, which excludes the phrase `Bed`. Observe:

```sql
SELECT itemid, label
FROM `physionet-data.mimiciii_clinical.d_items`
WHERE LOWER(label) LIKE '%bed%'
order by 1,2
```

which forces the `label` column to be all lower case using `LOWER(label)`, then compares to `%bed%`. This returns 54 rows, among which you have:

itemid | label
-- | --
216 | Height of Bed
... | ...
224080 | Head of Bed
... | ...

**Comment by SSMK-wq** [comment]
Hi,

My sincere Apologies. It's my bad. Will make sure it doesn't happen again.

Thanks for your time.

**Comment by alistairewj** [comment]
Don't worry! These mistakes are easy to make :)
