### ISSUE TITLE
Oral care info in Mimic

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#668]
Hello Everyone,

Does Mimic have the info on patient's oral care? I was reading ventilator bundle and that's when I came across this term.

Is it possible to find info on the below items?

1) daily assessment of the lips, oral tissue, tongue teeth, and saliva of each patient on a mechanical ventilator.

2) Unit specific protocols implemented that assist patients at risk of VAP in maintaining saliva production, oral tissue health, and minimizing the development of mucositis.

3) Patients oral and subglottic secretions suctioned continuously or intermittently/routinely with the frequency dependent upon secretion production.

4) For item 3, I believe we can look at the itemid for `subglottal suctioning`. Am I right to understand that more number of suctioning per day indicates patient's oral care is maintained well and his/her mouth is hygienic?  

5) For oral care, I have to be looking at only `subglottal suctioning` and `NT suctioning`. Am I right? or event `NT suctioning` should be excluded for oral care?

![image](https://user-images.githubusercontent.com/30723825/72232893-0381eb00-35ff-11ea-9cf6-008d40e8316d.png)

Is there anything that we have for items 1 and 2?

Can you help me with this?

**Comment by SSMK-wq** [comment]
Hi @alistairewj - Can you help me with this?

**Comment by alistairewj** [comment]
I would actually seek a local collaborator who is specialized in intensive care medicine (e.g. a critical care nurse, respiratory therapist, or intensivist). I don't have the requisite expertise to tell you whether or not the data documented is exactly what you are looking for in your study.
