### ISSUE TITLE
Reviewer's Questions

### ISSUE THREAD

**Issue by Zheng7AI310** [MIT-LCP/mimic-code#672]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
During my paper submission process, the reviewer would like to know what instrument is used to measure APTT and INR which were extracted from MIMICIII. Is it accurate? Hope to get everyone's help. Thanks.

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
The measurements are done during clinical care so I am sure they are accurate.. but I guess how accurate depends on the nature of your study. Maybe check the LOINC code associated with the concepts?


Row | ROW_ID | ITEMID | LABEL | FLUID | CATEGORY | LOINC_CODE |  
-- | -- | -- | -- | -- | -- | -- | --
1 | 437 | 51237 | INR(PT) | Blood | Hematology | 5895-7 |  
2 | 475 | 51275 | PTT | Blood | Hematology | 3173-2

**Comment by Zheng7AI310** [comment]
thanks。



            
            
                
                    
                            
                                
                            
                            
                                1499975603
                            
                    
                        
                            
                                    邮箱：1499975603@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 01/24/2020 00:13, Alistair Johnson wrote: The measurements are done during clinical care so I am sure they are accurate.. but I guess how accurate depends on the nature of your study. Maybe check the LOINC code associated with the concepts?







Row

ROW_ID

ITEMID

LABEL

FLUID

CATEGORY

LOINC_CODE

 









1

437

51237

INR(PT)

Blood

Hematology

5895-7

 





2

475

51275

PTT

Blood

Hematology

3173-2











—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/MIT-LCP/mimic-code/issues/672?email_source=notifications\u0026email_token=AKQVR3N4IPQOAHDHYQ6GIDLQ7G62JA5CNFSM4KKEC6N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJX4XBA#issuecomment-577751940",

"url": "https://github.com/MIT-LCP/mimic-code/issues/672?email_source=notifications\u0026email_token=AKQVR3N4IPQOAHDHYQ6GIDLQ7G62JA5CNFSM4KKEC6N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJX4XBA#issuecomment-577751940",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Zheng7AI310** [comment]
Thank you very much for taking the time to answer my question




------------------ Original message ------------------
From: "Alistair Johnson"; 
Sendtime: Friday, Jan 24, 2020 0:13 AM
To: "MIT-LCP/mimic-code"; 
Cc: "郑瑞"<1499975603@qq.com>; "Author"; 
Subject: Re: [MIT-LCP/mimic-code] Reviewer's Questions (#672)




The measurements are done during clinical care so I am sure they are accurate.. but I guess how accurate depends on the nature of your study. Maybe check the LOINC code associated with the concepts?
    Row ROW_ID ITEMID LABEL FLUID CATEGORY LOINC_CODE   
    1 437 51237 INR(PT) Blood Hematology 5895-7   
  2 475 51275 PTT Blood Hematology 3173-2
