### ISSUE TITLE
Time problems in INPUTEVENTS_MV

### ISSUE THREAD

**Issue by wombat95** [MIT-LCP/mimic-code#673]
Hello.

When I execute the SQL Statement

```{SQL}
select starttime, endtime, endtime-starttime from INPUTEVENTS_MV where starttime > endtime;
```

, I obtain results. So this means that there are input events that finished BEFORE started.

Is it an error or there is some meaning? So, how can I sort a set of input events by time?

Thank you.
Regards.

**Comment by alistairewj** [comment]
Sometimes there are documentation errors which are later fixed; you can see these rows as their `statusdescription = 'Rewritten'`. Try filtering those out.

**Comment by wombat95** [comment]
Ok.

Thank you very much.
