### ISSUE TITLE
aline analysis and severity scores/comorbidities 

### ISSUE THREAD

**Issue by jaredhuling** [MIT-LCP/mimic-code#674]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I am interested in using additional information to supplement the aline analysis [aline notebook](https://github.com/MIT-LCP/mimic-code/tree/master/notebooks/aline). In particular, I want to be able to control for more potential confounders when studying the effect of the aline placement. Ideally I would like to control for severity scores such as lods, sofa, mlods, etc (e.g. [pivoted sofa](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted-sofa.sql) ) and additionally comorbidities defined through the elixhauser definitions, but these are potentially calculated using post-treatment information. Is there a way to make an aline specific sql query which constructs these variables purely on pre-treatment information?

**Comment by alistairewj** [comment]
Yes of course, you would define the time of onset (e.g. in the case of aline the first time you observe an invasive blood pressure measurement), and then filter all your measurements to occur before that time. 

I've done something similar with sepsis. I created a table with a "starttime" and an "endtime": https://github.com/alistairewj/sepsis3-mimic/blob/30d0d790211823575a3cb1925d68001592f34bd0/query/tbls/suspicion-of-infection.sql

Then I used these starttime/endtimes in joins to filter data, e.g. here's one for labs:

https://github.com/alistairewj/sepsis3-mimic/blob/30d0d790211823575a3cb1925d68001592f34bd0/query/tbls/labs-infect-time.sql

**Comment by jaredhuling** [comment]
Thanks! It seems the same might not be possible for clinical notes, is that correct? Or is there some time stamp for clinical notes that I'm not seeing?

**Comment by alistairewj** [comment]
I think it's possible with all notes except discharge summaries. For the echo notes you have to extract the time from note itself but there's code to do that already in echo-data.sql

**Comment by jaredhuling** [comment]
Excellent, thanks!
