### ISSUE TITLE
Missing items in labitems table

### ISSUE THREAD

**Issue by phantom153** [MIT-LCP/mimic-code#675]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

I cannot find three lab tests which are quite frequently used in the D_LABITEMS table.
Does someone know if they exist under a different name.
The tests are:
Mean platelet volume (MPV) - LOINC code: 32623-1 or 28542-9
Platelet distribution width (PDW) - LOINC code: 32207-3
Red blood cell distribution width (RDW)

**Comment by alistairewj** [comment]
I had a look and ended up with three answers for the three `itemid`:

* Mean platelet volume (MPV) - This shows up in the raw lab "catalogue", but there's never any data associated with it. The implication is it's never measured. Before releasing MIMIC, we removed `itemid` which were not associated with any data, so it's not in MIMIC-III.
* Platelet distribution width (PDW) - I couldn't find this at all.
* Red blood cell distribution width (RDW) - This is under `RDW` and is available in MIMIC-III; look at `itemid` 51277.

**Comment by phantom153** [comment]
Thanks for the quick reply, Alistair.

RDW - missed that....sorry.
Regarding MPV & PDW - these tests are quite common as part of CBC.
Is there a chance they were mistakenly taken out from the raw data?

**Comment by alistairewj** [comment]
I'm pretty sure we haven't filtered anything.. But maybe there is an in
house step before us that filters it. I'll check with the BI.

>

**Comment by phantom153** [comment]
@alistairewj  - did you manage to check with the BI?
Thanks

**Comment by alistairewj** [comment]
So I looked and the vendor doesn't seem to provide PDW and MPV. The most recent announcement was the addition of RDW standard deviation.

**Comment by smallzccc** [comment]
@alistairewj 
In the  table, the RDW itemid only represents the result in metavision, but can not found any itemid in the carevue. I am doubt that the results of patients in the carevue is deficiency. Or I misunderstood the difference between carevue and metavision.
And I also found there are several itemid when searched BUN.
Thank you in advance!!

**Comment by alistairewj** [comment]
In general you shouldn't pull the labs from chartevents as they are all in labevents. The latter table is consistent for all patients in MIMIC and contains labs from outside the ICU as well. In labevents there is only one `itemid` for RDW: 51277.

```sql
SELECT * FROM `physionet-data.mimiciii_clinical.d_labitems` where lower(label) like '%rdw%'
```

**Comment by smallzccc** [comment]
> In general you shouldn't pull the labs from chartevents as they are all in labevents. The latter table is consistent for all patients in MIMIC and contains labs from outside the ICU as well. In labevents there is only one `itemid` for RDW: 51277.
> 
> ```sql
> SELECT * FROM `physionet-data.mimiciii_clinical.d_labitems` where lower(label) like '%rdw%'
> ```

Thank you for your reply!
