### ISSUE TITLE
How should we determine lab reference range values?

### ISSUE THREAD

**Issue by Zheng7AI310** [MIT-LCP/mimic-code#677]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
 

- IN the ICU of BIDMC,  

- what is the normal value for PT-INR?

- For APTT, what is the locally established reference interval?

- thanks!

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Unfortunately reference ranges weren't available when we released MIMIC-III, but you can fairly easily reverse engineer them:

```sql
SELECT itemid, flag
, min(valuenum) as value_min
, max(valuenum) as value_max
, count(*)
FROM `physionet-data.mimiciii_clinical.labevents`
where itemid IN
(
51274, -- PT
51275 -- PTT
)
group by 1,2
```
Label | itemid | flag | value_min | value_max | Number of observations
-- | -- | -- | -- | -- | --
PT | 51274 | null | 9.4 | 13.6 | 131874  
PT | 51274 | abnormal | 0.0 | 1907.0 | 337209  
PTT | 51275 | null | 22.0 | 150.0 | 239904  
PTT | 51275 | abnormal | 0.0 | 193.3 | 235026

Here we can conclude PT's reference range is 9.4-13.6. Of course this isn't perfect as reference ranges may have changed over the years, but it's reasonable.
