### ISSUE TITLE
Add ventdurations dependency for severity scores

### ISSUE THREAD

**Issue by tnaumann** [MIT-LCP/mimic-code#68]
The `ventdurations` table from [ventilation-durations.sql](https://github.com/MIT-LCP/mimic-code/blob/62102b08040ac5db96af7922db8d7832ce30a813/etc/ventilation-durations.sql) is referenced in [SOFA.sql](https://github.com/MIT-LCP/mimic-code/blob/62102b08040ac5db96af7922db8d7832ce30a813/severityscores/sofa.sql), but not called out in [README.md](https://github.com/MIT-LCP/mimic-code/blob/62102b08040ac5db96af7922db8d7832ce30a813/severityscores/README.md) as a dependency.

**Comment by alistairewj** [comment]
Readme/SOFA query updated with dependency in commit https://github.com/MIT-LCP/mimic-code/commit/3807a908db04d78ebb077ac35f0a5dd471bd1d8c - cheers.
