### ISSUE TITLE
[Unable to extract chartevent.csv.gz]Using makefile in Postgres

### ISSUE THREAD

**Issue by mrdat0194** [MIT-LCP/mimic-code#680]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* 1) I have done "wget" for a week to download : wget -r -N -c -np --user petern --ask-password https://physionet.org/files/mimiciii/1.4/
* 2) Then I use: make create-user mimic-gz datadir='../physionet.org/files/mimiciii/1.4'
* 3) I also try to unzip it but it is not working on Mac Catalina 10.15.2
* Result:
psql "dbname=mimic user=postgres password=postgres options=--search_path=mimiciii" -v ON_ERROR_STOP=1 -f postgres_load_data_gz.sql -v mimic_data_dir=/Users/petern/physionet.org/files/mimiciii/1.4
COPY 58976
COPY 34499
COPY 7567
gzip: data stream error
gzip: CHARTEVENTS.csv.gz: uncompress failed
psql:postgres_load_data_gz.sql:49: ERROR:  invalid input syntax for type integer: "2158-10-20 15:24:00"
CONTEXT:  COPY chartevents, line 26230230, column itemid: "2158-10-20 15:24:00"
psql:postgres_load_data_gz.sql:49: error: gzip -dc CHARTEVENTS.csv.gz: child process exited with exit code 1
make: *** [Makefile:107: mimic-build-gz] Error 3

**Comment by alistairewj** [comment]
1. Check the SHA256 sum of CHARTEVENTS.csv.gz - make sure it matches the ones distributed on PhysioNet
2. Maybe you ran out of disk space?

**Comment by mrdat0194** [comment]
@alistairewj: thank you, because maybe I download different time period, check sum is not correct anymore, or maybe I am too far from the server. Sincerely,
