### ISSUE TITLE
Chartevents: CareVue `resultstatus` values differ from online documentation

### ISSUE THREAD

**Issue by ToucheSir** [MIT-LCP/mimic-code#681]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

https://mimic.physionet.org/mimictables/chartevents/#resultstatus-stopped mentions that 
"RESULTSTATUS is ‘Manual’ or ‘Automatic’" for the CareVue data. However, querying for distinct `resultstatus`es returns the following result:

```
<null>	321182823
Final	8827334
Manual	702326
```

Is there any relation between "Final" and "Automatic"? For context, we're hoping to extract timely automated events for the purpose of rough waveform annotation on the matched subset.

**Comment by alistairewj** [comment]
We really don't have any information about this column and what it means. The CareVue documentation I had didn't describe it at all.

**Comment by ToucheSir** [comment]
Thanks for looking into this! I suppose I'll try it out anyways and see how it goes.
