### ISSUE TITLE
The problem about fasting blood glucose in MIMIC III

### ISSUE THREAD

**Issue by wyyyzw** [MIT-LCP/mimic-code#682]
What is the way to get fasting blood glucose from the database？ I found that blood glucose was measured at random. 
Or What is the way to obtain the patients with impaired fasting glucose from the database?
But I found that few patients have the ICD-9 code of impaired fasting glucose. Has this diagnosis been ignored？

**Comment by alistairewj** [comment]
I don't think fasting glucose is that commonly measured, if measured at all. I did find 111 notes with the term "fasting glucose" in them though - so that might be the best way to get this information.
