### ISSUE TITLE
finding the ITEMID for ´pulse pressure´

### ISSUE THREAD

**Issue by datascience100** [MIT-LCP/mimic-code#683]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I am trying to find the ITEMID(s) for the measurement of ´pulse pressure´. I have tried looking into the d_items table searching for LABEL containing the words ´Pressure´, ´pressure´, ´Pulse´, ´pulse´, ´PP´, ´pp´. Also I have searched for ABBREVIATION = ´pp´, ´PP´. I have not find any ITEMID(s) yet.

Thanks.

**Comment by alistairewj** [comment]
Could you post the exact queries you have tried?

**Comment by datascience100** [comment]
I have tried: 

SELECT itemid, label, abbreviation, CATEGORY FROM d_items WHERE label LIKE '%pressure%';

SELECT itemid, label, abbreviation, CATEGORY FROM d_items WHERE label LIKE '%Pressure%';

SELECT itemid, label, abbreviation, CATEGORY FROM d_items WHERE label LIKE '%Pulse%';

SELECT itemid, label, abbreviation, CATEGORY FROM d_items WHERE label LIKE '%pulse%';

SELECT itemid, label, abbreviation, CATEGORY FROM d_items WHERE abbreviation= 'PP';

**Comment by alistairewj** [comment]
OK - I don't think they document pulse pressure directly, but it's very easy to calculate. If you have the pivoted_vital concept table, you can do:

```sql
select icustay_id, charttime,
sysbp, diasbp, meanbp,
sysbp - diasbp AS pulse_pressure
FROM `physionet-data.mimiciii_derived.pivoted_vital`
WHERE sysbp IS NOT NULL
AND diasbp IS NOT NULL
ORDER BY 1, 2
```

**Comment by datascience100** [comment]
Thank you. I have not found yet the `physionet-data.mimiciii_derived.pivoted_vital` table, but I have found the pivoted-vital.sql file to create the MATERIALIZED VIEW pivoted_vital. Is that the same?

**Comment by alistairewj** [comment]
Yes it is the same.

**Comment by datascience100** [comment]
Thank you. A related question is: I am trying to obtain the icustays with at least 1 observation for several measurements (vital signs, pH, satO2, WBC, etc.). Later on I will apply more filters to the data. I am trying to retrieve them by joining (INNER JOIN) the tables of chartevents, pivoted_lab, pivoted_bg and pivoted_bg_art based on the equal icustay_id. But these queries are very slow or unsuccessful. Is there a way to perform this easily?

**Comment by alistairewj** [comment]
That sounds expected. If you don't ensure that two sides of a join are unique, you'll end up with an NxM cross-join. So in the case of two pivoted tables, if your patient has 10 rows in table 1 and 100 rows in table 2, you'll end up creating a table with 1000 rows. Now add in another join to another table with 100 rows and you're up to 10000, etc. In general try to make sure at least one side of the join is unique. You can try following the pattern I took for the `aline` study code in this repo as I mostly create tables with 1 row per patient, then join them together at the end.

Also keep in mind using inner join will filter out patients missing data, which will probably bias your cohort if you're not careful.
