### ISSUE TITLE
Problem matching specific waveform segment file name and ICU stay

### ISSUE THREAD

**Issue by mtorlaschi** [MIT-LCP/mimic-code#685]
I am trying to link a specific record file name to the patient's corresponding ICU stay. For example, according to the ICUSTAYS table from the Clinical Dataset, the patient with subject ID 188  had 8 ICU stays. Some patient's segment files are named 3285727_xxxx.dat, while others are named 3317157_xxxx.dat, 3641721_xxxx.dat and so on. I would like to know if there is a way of linking these file names (or their prefixes) to the ICU stay in which they were recorded.

**Comment by alistairewj** [comment]
Look at the matched subset header files: https://archive.physionet.org/physiobank/database/mimic3wdb/matched/

Also check out #86 as it has more info.
