### ISSUE TITLE
adding indexes

### ISSUE THREAD

**Issue by datascience100** [MIT-LCP/mimic-code#686]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

When I installed manually the database in a local Postres database on Linux a few of the indexes could not be created (ERROR:  could not write block 8205 of temporary file: there is not enough space in device.....). Then with some queries it is slow. Could I run again safely the script of add_indexes.sql if having now enough free space ??

**Comment by alistairewj** [comment]
Yes, certainly.
