### ISSUE TITLE
The problem about the codes of abdominal girth

### ISSUE THREAD

**Issue by wyyyzw** [MIT-LCP/mimic-code#687]
I want to get the codes of adult abdominal girth. By search in mimiciii.d_items table, I found that itemid in '28', '3294', '6028', '2919', '2563' and '2788' were 'abdominal girth'. However, almost all of the codes were neonatal abdominal girth data. Therefore, is there any other data of adult abdominal girth in MIMIC III database?

**Comment by alistairewj** [comment]
I don't think adult abdominal girth is routinely measured. At best you will be able to get body mass index (BMI) or body surface area (BSA)
