### ISSUE TITLE
Installing MIMIC-III in a local Postgres database isn't working / not enough disk space. 

### ISSUE THREAD

**Issue by etsi123** [MIT-LCP/mimic-code#688]
Hello, 

I'm trying to load the MIMIC-III data into a local Postgres database by following the instructions here : https://mimic.physionet.org/tutorials/install-mimic-locally-ubuntu/ 

It seems to be working fine through step 8 but when I type in the command: 
psql 'dbname=mimic user=mimicuser options=--search_path=mimiciii' -f postgres_load_data.sql -v mimic_data_dir='<path_to_data>' 
the output is : 
COPY 58976
COPY 34499
COPY 7567
before I ultimately get a "no space left on disk" error. This makes sense, I was reading that I would need roughly ~90-100GB of free space to do import the data and I only have about 15GB available. My MAC only has 121GB of free space to begin with and 73GB are used for the operating system so there is no way for me to free up enough space for it. I do have a 2TB portable external hard drive however, Is it possible to use that? If so, how would I augment the steps outlined in the link above? 

I look forward to your guidance on this issue. Thank you.

**Comment by alistairewj** [comment]
You can definitely use an external hard drive, you need to tell postgres to initialize the database on the held out disk. Postgres stores all the data in a subfolder of your choosing (look for help in using `initdb`). Alternatively you could consider using MIMIC on the cloud: https://mimic.physionet.org/gettingstarted/cloud/

**Comment by redsadaf** [comment]
How could we tell Postgres to initialize the database on the external hard drive or from home folder?
