### ISSUE TITLE
Breathing or Spontaneous awakening trials

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#689]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

May I know where can I find info on whether patient had any  **awake trials or spontaneous breathing trials or sedation holiday**?

I understand we can find his sedative drug consumption dates. Is there any data derived based on sedation as an answer to the above terms?

Is it something which we can calculate?

Can someone guide me on this?

**Comment by SSMK-wq** [comment]
@alistairewj - If you have time, will you be able to let me know whether we have data on this?

**Comment by SSMK-wq** [comment]
@alistairewj - May I check with you on whether it is possible to find data for the above items?

**Comment by alistairewj** [comment]
I haven't looked into defining SBTs so I don't have any particular advice here.

**Comment by RotemSap** [comment]
Hi SSMK-wq.
Can you share some notes if you found something about this subject?
Thank you

**Comment by whiskey0504** [comment]
@SSMK-wq @RotemSap Hi, I'm looking to find some SAT/SBT data in MIMIC as well -- did any of you happen to have found anything? Thanks in advance!
