### ISSUE TITLE
Question about date shifting

### ISSUE THREAD

**Issue by wombat95** [MIT-LCP/mimic-code#690]
Hello.

I have a question about date shifting.

According to the mimic-iii documentation, "dates will be internally consistent for the same patient", but "the absolute day of the month is **not preserved**".

So, for example, if I obtain the difference **in days** between two treatments for the same patient (for the same admission or for different admissions) or the difference **in days** between two admissions for the same patient, will the result be correct? Or only the years are reliable (for, for example, the age of the patient)?

Thank you.

**Comment by alistairewj** [comment]
Any difference in times for a single patient (i.e. the same `subject_id`) will be the true difference. In your example, both differences would be correct.

**Comment by wombat95** [comment]
Ok. Thank you.

Regards.
