### ISSUE TITLE
Tobramycin administration

### ISSUE THREAD

**Issue by FeifanXie** [MIT-LCP/mimic-code#691]
Hi,

According to the IV dosing guideline of tobramycin, tobramycin should be administered as a short duration (30 – 60 min) infusion rather than as a bolus. The “ENDTIME = STARTTIME + 1 minute” records for tobramycin in inputevents_mv is probably not true, and this problem is also discussed for another similar drug-Vancomycin ([vanco administration #372](https://github.com/MIT-LCP/mimic-code/issues/372)). 

I was wondering if it is possible to find out the IV duration of tobramycin? Would it be possible to check with the nurse for the guidelines for the IV duration of tobramycin?

Thank you!

**Comment by alistairewj** [comment]
Yep you got it. The guidelines for tobramycin are:

> Recommended route: **INTERMITTENT INFUSION**
> Administer over 30 minutes.
>
> Usual Adult Dose and Schedule:
> Extended Interval Dosing: 5 or 7 mg/kg IV q24h (use dosing body weight in obese patients)
> Traditional Dosing: 1.5-2 mg/kg IV q8h (use dosing body weight in obese patients)

**Comment by FeifanXie** [comment]
Thanks a lot!
