### ISSUE TITLE
I had problems extracting patients diagnosed with vap

### ISSUE THREAD

**Issue by helu072005** [MIT-LCP/mimic-code#694]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I encountered a problem while simulating some operations of other authors. How to extract icd9 code (99731: Ventilator associated pneumonia). And make sure there are VAP related keywords (VAP or “ventilator-associated pneumonia”or “venting-associated pneumonia”)in noteeventsof these cases.Based on the above conditions, the number of patients in the author's paper was 418.I have been thinking for a few days and still cannot get the above results. I hope you can help me.
Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
It's impossible to provide insight into your issue with so little detail! Who are the author's? What keywords did they look for in particular? Where in `noteevents` did they look? What is the query or code that you have tried to replicate their work?
