### ISSUE TITLE
mortality prediction

### ISSUE THREAD

**Issue by jaredhuling** [MIT-LCP/mimic-code#696]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I am interested in constructing the datasets used for mortality prediction, but the mortality prediction repository (https://github.com/alistairewj/mortality-prediction) seems out of date and requires extensions (eg tsexact) of postgresql which are not actively maintained. Is there any updated set of queries that can be run from front to back that result in a dataset suitable for mortality prediction?

**Comment by alistairewj** [comment]
You could check out [MIMIC_Extract](https://arxiv.org/abs/1907.08322)

Code: https://github.com/MLforHealth/MIMIC_Extract


.. or ["FIDDLE" (pdf)](https://static1.squarespace.com/static/59d5ac1780bd5ef9c396eda6/t/5d48330b6a811c00010bbd67/1565012747877/Sjoding.pdf)

Code: https://gitlab.eecs.umich.edu/mld3/FIDDLE

**Comment by jaredhuling** [comment]
Thanks!
