### ISSUE TITLE
Issue about the number of valid discharge summary

### ISSUE THREAD

**Issue by ZilongZhang** [MIT-LCP/mimic-code#698]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

The number of discharge summary is much more than the HADM_ID, I found a large part is due to the existence of “addendum”. Addendums are not valid complete discharge summaries but their “CATEGORY” is still “Discharge Summary”. People used different labels to distinguish between formal discharge summary (report) and supplement (addendum) in the “DESCRIPTION” column.  But the introduction of noteevents table did not cover this information.

https://mimic.physionet.org/mimictables/noteevents/

So far I think it’s fine, as it may be a trivial point that everyone should notice by himself when they get their hand on MIMIC-iii data.

However, even for discharge summaries that have been labeled as “report”, there are still many cases where one HADM_ID corresponds to multiple DSs, some of which are due to the inclusion of "interim discharge summary" (such as the report of HADM_ID 132004). Some addendums are mislabeled as reports, such as 132095. Some are just meaningless, for example, one of three discharge summaries for HADM_ID 131523, only required CC a copy of the discharge summary to the patient's primary care physician. To summarize, there are at least four numbers of discharge summary according to different standards：

Criterion | Quantity
-- | --
Take all text that is labeled as DS in “CATEGORY” | 59652
Take all text labeled as DS in “CATEGORY” and “report” in “DESCRIPTION” | 55177
Concatenate all DS of one HAMD_ID into one | 52726
Concatenate all “report” DS of one HAMD_ID into one | 52691

Here are code:
![ds_problem1](https://user-images.githubusercontent.com/20568420/75645387-ff3b7c80-5c02-11ea-9151-5e124e15b75e.PNG)
![ds_problem2](https://user-images.githubusercontent.com/20568420/75645388-006ca980-5c03-11ea-9bbf-9343c675f7b6.PNG)

I downloaded the dataset in 2019 and checked MD5SUMS. Considering that these DSs are used extensively in the research that uses NLP to automatically assign ICD codes, I would like to know what the mainstream solution is. We can easily find different numbers in publications, I got a handful different number in 10 min google searching:
![confusing_number1](https://user-images.githubusercontent.com/20568420/75645444-25611c80-5c03-11ea-8b84-545628f72ab6.PNG)
![confusing_number2](https://user-images.githubusercontent.com/20568420/75645445-25f9b300-5c03-11ea-8e2a-d84f08a02b35.PNG)
![confusing_number3](https://user-images.githubusercontent.com/20568420/75645446-26924980-5c03-11ea-959c-4b5e7dba1f04.PNG)

As far as I concerned, the fourth number 52691 is the only appropriate number for discharge summary based analysis, the ds that only has addendum for one HADM_ID should also be discarded. If I delete some invalid ds and correct the label in “DESCRIPTION” back to its proper label, can I submit the improved version to the phsionet?

**Comment by alistairewj** [comment]
Regarding the website, please do raise issues as you find them - or even better would be to provide some suggestions via a pull request at https://github.com/mit-lcp/mimic-website
I've just fixed those details about noteevents, thanks.

It's great that you've investigated the reports - unfortunately I do not think there is a mainstream solution as you have already seen. Traditionally we have not processed data in MIMIC to avoid biasing studies, so the data is "raw" and contains inconsistencies like the ones you've found here. That being said, if you have code which you believe improves the text with no downsides, we can definitely consider using it for the next release. Would you be able to share code which appropriately filters the summaries?

**Comment by alistairewj** [comment]
Please do open a PR if you end up with something you think could benefit the community.
