### ISSUE TITLE
'BPM' vs 'insp/min'

### ISSUE THREAD

**Issue by jenishmaharjan** [MIT-LCP/mimic-code#699]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

There are two units in for the chartevent Respiratory Rate in the dataset - 'insp/min' and 'BPM'. Are the two units interchangeable?

**Comment by alistairewj** [comment]
Yes.
