### ISSUE TITLE
The ideal MIMIC-III system

### ISSUE THREAD

**Issue by joel1391** [MIT-LCP/mimic-code#70]
I'm looking for the ideal specs for a system that could be used to run MIMIC-III. The aim is to keep costs down while maximising performance, stability and query speed. As an added bonus I'd like to run various types of analysis software, and to run software on the waveform database.

Specific to the MIMIC-III database, I'm interested in knowing the ideal:
- operating system
- SQL software
- RAM
- CPU 

The main reason I ask is because I've tried importing the dataset in to Postgres on my laptop with windows and it's crashed a few times. I tried installing an Ubuntu virtual system on various computers but have run in to issues with crashing/speed. I'm looking to put together a dedicated system for MIMIC-III and other large datasets, but if something like a macbook is equally as useful I'll even consider purchasing one.

**Comment by parisni** [comment]
Hello,

If you have a minimum of 8GB ram & 4 core on your laptpt, you should try apache-drill. (find it in buildmimic).
I use it on my laptop and it is quite confortable. 
Note that 2 tables cannot be loaded for now, but will be available soon.
