### ISSUE TITLE
Carevue itemid 211 bimodal

### ISSUE THREAD

**Issue by dplecko** [MIT-LCP/mimic-code#701]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

I have done some data loading for various heart rate items for MIMIC. After this, I noticed that the final result of the data loading is strongly bimodal. I analyzed all the included items, all of which except one, were unimodal (as one would expect I guess). 

In particular, `itemid 211` (carevue, links to `chartevents`) is the one which is bimodal. I am attaching a density plot of the item.

![itemid211](https://user-images.githubusercontent.com/43063243/75789224-a63a2880-5d69-11ea-8ff7-7586211ff4e8.png)

The second (sizeable) mode at value 160 might be a systematic error (or there is another explanation -- perhaps this is an alarm). Any thoughts on this?

**Comment by tompollard** [comment]
Pediatric patients have high heart rates! Restricting to adult patients will solve your issue.

**Comment by dplecko** [comment]
Hi,

Many thanks for the swift response. You were exactly right:

![item211_adults](https://user-images.githubusercontent.com/43063243/75801483-7f84ed80-5d7b-11ea-88ac-099fe101e657.png)

So filtering for neonates does resolve the issue; interestingly, the amount of neonates in `metavision` is negligible, so the heart rate data is not bimodal. Not sure if this is mentioned in the documentation - but I am sure it would be interesting to many researchers :-)

Once again thanks a lot for your help!

Best,
Drago
