### ISSUE TITLE
psql:D:/mimic-iii-clinical-database-1.4/mimic-iii-clinical-database-1.4/postgres_load_data_7zip.sql:31: error: could not close pipe to external command: No error

### ISSUE THREAD

**Issue by rpauly** [MIT-LCP/mimic-code#702]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including: I am not sure what this error means.

* I am trying to load the tables
Command: \i D:/mimic-iii-clinical-database-1.4/mimic-iii-clinical-database-1.4/postgres_load_data_7zip.sql
Error: psql:D:/mimic-iii-clinical-database-1.4/mimic-iii-clinical-database-1.4/postgres_load_data_7zip.sql:31: error: could not close pipe to external command: No error

**Comment by alistairewj** [comment]
Not entirely sure - probably need more information about your environment to think of an answer. Do you have 7zip correctly installed and on the Windows path?

**Comment by alistairewj** [comment]
Closing - please feel free to re-open if you have more info to share and are still having trouble.
