### ISSUE TITLE
Technical Limitations : Inter-waveform alignment problems

### ISSUE THREAD

**Issue by AguirreNicolas** [MIT-LCP/mimic-code#703]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I'm working with the matched waveform databases.

One parameter I am interested in is the Pulse Transist Time ( **PTT** ) between the ECG ( II ) and Arterial Blood Pressure ( ABP ).

Based on the following considerations:

1) Technical limitations: ( https://archive.physionet.org/physiobank/database/mimic3wdb/ )
 "Inter-waveform alignment problems: The method used for MIMIC waveform data extraction was not designed for inter-waveform analysis. The waveform data contain unspecified/unknown filtering delays and/or unknown inter-channel delays, which may not be constant in a given record. Therefore, although the ECGs are time-aligned with each other, there may be a (changing) delay of up to 500ms between any of the other waveforms in the data. For example, the pulse transit time measured between different waveforms may be unreliable (either in absolute or relative terms"

2) Comments in ".hea" files:
Inside some of these files I can find the legend " **Final alignment uncertain**" (in my case, 17825 does NOT have that comment, and 5585 does)

3) Article extracting PTT from MIMIC
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4512231/
is this valid?

My question in particular is:

Is it only appropriate to consider the **PTT** of cases where we do **NOT** have the comment "Final alignment uncertain"?
Should I remove the others? Or in neither case is it meaningful?

Thank you

Nicolas

**Comment by alistairewj** [comment]
I don't think you can make that assumption. I believe researchers in our lab may have tried to add some info like "final alignment uncertain", but as far as I know all waveforms were affected by the issue with alignment. Researchers who study PTT have to account for this in some way.
