### ISSUE TITLE
Is `icustay_id` and/or `intime` honest sequence?

### ISSUE THREAD

**Issue by mikkokotila** [MIT-LCP/mimic-code#711]
Can we assume that `icustay_id` and/or `intime` are representing a historical chronology for the patient i.e. the highest value is the last stay?

**Comment by alistairewj** [comment]
Not across patients. But within a single `subject_id`, the `intime` of various `icustay_id` will be chronological.

**Comment by mikkokotila** [comment]
Thanks so much for the speedy response :)
