### ISSUE TITLE
How to extract infection sites from the database

### ISSUE THREAD

**Issue by qinyu-zhao** [MIT-LCP/mimic-code#713]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

My name is Qin-yu Zhao. I am a student from Peking University and have been using the MIMIC-CODE.  My friends and I really appreciate what you have done.

Recently, I read an article [1] on BMJ, in which the authors extracted data on infection sites of septic patients from MIMIC-iii. I am wondering how they did that, because my research deals with sepsis and I also want to get the infection information.  I haven't yet found any supplementary materials or documents that provide access to infection sites.

It would be highly appreciated if you could help me with that.

[1] Shen Y, Huang X, Zhang W. Platelet-to-lymphocyte ratio as a prognostic predictor of mortality for sepsis: interaction effect with disease severity-a retrospective study. BMJ Open. 2019;9(1):e022896. Published 2019 Jan 25. doi:10.1136/bmjopen-2018-022896

**Comment by tompollard** [comment]
@qinyu-zhao Authors of published papers that use MIMIC-III are required to share their code under the data use agreement. I would suggest contacting the authors, reminding them of this, and asking where you can find their code!

**Comment by qinyu-zhao** [comment]
Thank you for your suggestion! I am going to contact them.

**Comment by tompollard** [comment]
Thanks, and please let us know how you get on!

**Comment by SvenVanPoucke** [comment]
I use RapidMiner to access the Mimic database.
Cheers
Sven

Op wo 1 apr. 2020 17:31 schreef Tom Pollard <notifications@github.com>:
