### ISSUE TITLE
Surrogate date differences for patient records in the MIMIC-III Waveform Database Matched Subset

### ISSUE THREAD

**Issue by Hughmac** [MIT-LCP/mimic-code#716]
I've just started working with the mimic-iii-clinical-database-1.4 and the MIMIC-III Waveform Database Matched Subset.

The Matched Waveform page (https://archive.physionet.org/physiobank/database/mimic3wdb/matched/) says "The surrogate dates match those of the corresponding MIMIC-III Clinical Database records", but  for 2 of 6 patients so far when I look at the waveform header file date, then look for CHARTEVENTS related to the same patient/ICU stay, the surrogate dates are different. 

For example patient 145:
The waveform header file:
p000145-2153-08-25-02-13.hea 
CHARTEVENTs seem to range from 04-06/2144:
34965106,145,198161,246376,161,2144-04-23 19:00:00,2144-04-23 19:10:00,15001,"None",,,,,,"NotStopd" 
…
226014675,145,198161,246376,8553,2144-06-07 19:00:00,2144-06-07 19:25:00,17877,"35",35,"BPM",,,,"NotStopd"

For patient 736: 
The top waveform header is:
p000736-2129-03-06-04-55.hea
although there is an extra numerics header
p000736-2118-09-19-00-22n.hea

The CHARTEVENTS are around 09/2118
38146251,736,164142,,742,2118-09-20 15:00:00,2118-09-20 15:02:00,15652,"1",1,"kg",,,,"NotStopd"

Am I doing something wrong? Or am I misunderstanding the process of aligning clinical events and waveforms?

If these are actually errors in propagating clinical dates to waveform headers, is there a workaround I can use? I understand that the time values should be the same across datasets, but where patients have multiple stays in the ICU I don't know which clinical events are relevant.

Thanks for any advice.

**Comment by alistairewj** [comment]
There may actually be errors in matching the waveforms with the clinical records so we would appreciate any reports of this nature. Unfortunately the record matching is a manual process. I'll raise issues about those specific patients internally.

What I've done in the past is only included patients where I could find an `icustay_id` around the same time as the waveform record. If you load the start times for the waveform, you can look for waveform start times that are between ICU admission and discharge time. I usually allow for a bit of leeway in the times (so I subtract a few hours from ICU admission time and add a few to discharge time).
