### ISSUE TITLE
Match Doctor/Surgeon with ICD procedure

### ISSUE THREAD

**Issue by laurenleesc** [MIT-LCP/mimic-code#718]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I am trying to compare the physicians performing gall bladder removals. I have identified the SUBJECT_IDs and HADM_IDs of the PROCEDURES_ICD associated with the list of procedures I want. I see that I can connect the caregivers (CGID) to the HADM_ID through the tables PROCEDUREEVENTS_MV or CHARTEVENTS. When I do this, I see ALL events, including procedures performed by nurses, etc.  I am not able to exactly determine the CGID who performed the PROCEDURES_ICD.  Does anyone have any ideas? Here is a query I've tried:

#####################################################################
CREATE TABLE choley_cohort_performing_physician AS
SELECT *
FROM choley_trigger_cohort A -----A table I created that has patients with gall bladder removals 
LEFT JOIN
(SELECT * FROM procedureevents_mv WHERE ORDERCATEGORYNAME = 'Procedures' AND CGID IN (SELECT DISTINCT CGID FROM CAREGIVERS WHERE UPPER(LABEL) LIKE '%RES%' OR UPPER(LABEL) LIKE '%MD%')) B
ON A.HADM_ID_TRIGGER = B.HADM_ID
####################################################################

I've tried to restrict by 'residents' or 'medical doctors' as well as not restricting by CGID label. When I run this query, I still don't get anything that looks like a surgery, or that I feel can connect the physician to the medical claims code. Thanks in advance.

**Comment by alistairewj** [comment]
The procedure table names are similar but they are from separate systems:

* PROCEDUREEVENTS_MV - Events in here are documented by nursing staff *in the ICU*. They are used to track ventilation, patients going for x-rays, etc.
* PROCEDURES_ICD - Events here are billed procedures from the hospital. For gall bladder removal, this is the table you're interested in.

Unfortunately we do not have information on the provider for PROCEDURES_ICD. We only have provider/care giver information for the ICU data; and in those tables, it's specifically the care giver who *documented* the data. So for example a nurse may document that a patient was intubated at a certain time, but that does not mean the nurse was the one who intubated the patient.

**Comment by laurenleesc** [comment]
Thank you for your very thorough answer. How typical is it for a doctor or nurse to document someone else's work, do you know? I'm sure that would be speculation, but I had to ask.  Thanks again.

**Comment by alistairewj** [comment]
I don't know 100% but I'm fairly sure it doesn't really happen. Providers have to bill for their own work - at least all of the ones I've ever worked with did. However provider billing is separate from the hospital level billing, which is the data present in MIMIC-III. In the hospital level billing, there is a team of trained coders who assign the billing codes based upon signed notes for the patient.
