### ISSUE TITLE
IRB approval for MIMIC III

### ISSUE THREAD

**Issue by studentem11** [MIT-LCP/mimic-code#719]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Not sure if this belongs here, but I'm trying to use the database to create a study. My understanding was that no IRB approval was needed, my school says it's not truly de-identified and I need to submit IRB approval for retrospective patient chart review. I'm having trouble finding anything online about it except other studies that waive the need for IRB approval because the database is de-identified.

Thanks in advance.

**Comment by alistairewj** [comment]
De-identified data generally does not constitute human subjects research, and so IRB approval isn't needed. Your school may have different/stricter rules however.
