### ISSUE TITLE
Difference between Government and Medicare/Medicaid ?

### ISSUE THREAD

**Issue by riarungta** [MIT-LCP/mimic-code#722]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, I am currently using the MIMIC-III data-set for my MPH thesis and was wondering what the difference is between "Government" and "Medicare" and "Medicaid" insurance type for patients? This information is available in the ADMISSIONS table. Thank you!

**Comment by alistairewj** [comment]
Massachusetts has certain health insurance programs and I believe "Government" refers to those. Beyond that I don't know.
