### ISSUE TITLE
Bigquery Access: I can only see eicu_crd_demo and mimiciii_demo

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#723]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I did as the instructions says here:
https://mimic.physionet.org/gettingstarted/cloud/
Also, I read carefully the last paragraph that relates this issue, in the physionet profile: email, cloud and credentials is all set as it should. Also, tried to unpin and pin 'physionet-data'. I already got access in the past successfully for my account, now I'm helping my analyst, and I think because he got the credentials before declaring email.
Help please :)
physionet user: xxx
email: xxx

<img width="297" alt="Screen Shot 2020-04-13 at 12 31 19" src="https://user-images.githubusercontent.com/23483971/79110369-f18d2100-7d82-11ea-867e-91b9c5216e97.png"> 

<img width="1171" alt="79110465-2600dd00-7d83-11ea-88f3-c0e455577aea" src="https://user-images.githubusercontent.com/822601/79124969-5ccaf900-7d6b-11ea-9182-408d087b1fa8.png">

<img width="1154" alt="79110477-2bf6be00-7d83-11ea-9b91-24d6682318c7" src="https://user-images.githubusercontent.com/822601/79125049-7c622180-7d6b-11ea-89d9-24734cddf931.png">

<img width="859" alt="Screen Shot 2020-04-13 at 12 31 14" src="https://user-images.githubusercontent.com/23483971/79110366-ee923080-7d82-11ea-8a05-5f55a5611cda.png">

@alistairewj

**Comment by tompollard** [comment]
@arielhasidim please avoid posting personal details (PhysioNet username/email) publicly here. It looks like the step that you've missed is requesting access for the project via the project page:

e.g. see the "Files" section at: https://physionet.org/content/mimiciii/1.4/

![Screen Shot 2020-04-13 at 09 46 23](https://user-images.githubusercontent.com/822601/79125205-c3e8ad80-7d6b-11ea-9620-ff8e2a4a3a9f.png)

**Comment by arielhasidim** [comment]
> @arielhasidim please avoid posting personal details (PhysioNet username/email) publicly here. It looks like the step that you have missed is requesting access for the project via the project page:
> 
> e.g. see the "Files" section at: https://physionet.org/content/mimiciii/1.4/
> 
> ![Screen Shot 2020-04-13 at 09 46 23](https://user-images.githubusercontent.com/822601/79125205-c3e8ad80-7d6b-11ea-9620-ff8e2a4a3a9f.png)

Much obliged!

**Comment by tompollard** [comment]
Thanks for the clear description of the issue @arielhasidim. It's not the first time we've been asked, so it's useful to have the discussion here for reference. We'll try to make the process clearer on PhysioNet!

**Comment by adityanz** [comment]
Hi, I already did that step and it still shows to me that I cannot run the queries. I have access to the dataset and its pinned but it says the following Access Denied: Project physionet-data: User does not have bigquery.jobs.create permission in project physionet-data 
SELECT *
FROM `REDACTED`

**Comment by alistairewj** [comment]
The error you mention:

> Access Denied: Project physionet-data: User does not have bigquery.jobs.create permission in project physionet-data

... means you are trying to query the data with `physionet-data` as your BigQuery project (at the top of the screen). This is equivalent to billing the `physionet-data` project for your usage, which you do not have permission to do.

Instead, you'll need to create your own google cloud project and use it as your active project. You can still read data from the `physionet-data.mimiciii_clinical` dataset if you have gone through the access steps ([detailed on the cloud page of the documentation](https://mimic.physionet.org/gettingstarted/cloud/)).

**Comment by tompollard** [comment]
@adityanz please could you check that:

1) you are logged into Google with the same email address that you have registered on PhysioNet
2) you have selected a billing project in the top level menu (where it says `sccm-datathon`, it should instead display the name of your personal project).

<img width="548" alt="Screen Shot 2020-09-30 at 20 00 22" src="https://user-images.githubusercontent.com/822601/94752007-01f87e80-0358-11eb-93df-7f1c7c2f900a.png">

**Comment by adityanz** [comment]
<img width="1017" alt="Screen Shot 2020-10-01 at 06 23 18" src="https://user-images.githubusercontent.com/24827643/94754358-a5747e00-03ae-11eb-82a0-3ec2c4fc145e.png">

Okay thank you for the project point, I currently do not have any projects created.  When I access the shared data, do I get access to the project as well or do I create my own personal project? Also, will I make the project until my organization or will I have access to your organization? Thanks.

**Comment by alistairewj** [comment]
You should use your own project - in this case it looks like you should create your own personal project. Create it under your own organization if you like - but I don't think it's required.

**Comment by Debodeep94** [comment]
I am working with the Mimic-CXR dataset. I have already gained access. The problem is with size. Is there any way where we can use a subset of the data in our local machine?

**Comment by alistairewj** [comment]
Please raise a new discussion topic for new questions.
