### ISSUE TITLE
How do I get the start and end times

### ISSUE THREAD

**Issue by helu072005** [MIT-LCP/mimic-code#724]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
   I want to know when the patient has the operation, so that I can do other analysis.However, I searched for procedures in procedureevents_mv, d_items and did not get the results I wanted.How to determine the time of the operation?This is very important to me.
SELECT *
FROM d_items
WHERE linksto='procedureevents_mv'

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
The procedureevents_mv table contains in-ICU procedures, which usually precludes operations. If you want operations performed in the hospital, you can use `procedures_icd`, but start/stop times are not available (see #665, #630)
