### ISSUE TITLE
OMOP shaped data on Physionet

### ISSUE THREAD

**Issue by vojtechhuser** [MIT-LCP/mimic-code#725]
This is re-opening of a closed issue here
https://github.com/MIT-LCP/mimic-code/issues/230

A related forum discussion is here https://forums.ohdsi.org/t/mimic2-and-possibly-mimic3-data-in-ohdsi-cdm-format/860/25

**Comment by tompollard** [comment]
As we have mentioned before, we would be happy to share an OMOP version of MIMIC-III on PhysioNet. The submission should fully describe the dataset and the work to generate it. We suggest including a snapshot of the code, and including a complete list of contributors in the authorship.

**Comment by alistairewj** [comment]
Further discussion can take place in the mimic-omop repo; issue tracked here: https://github.com/MIT-LCP/mimic-omop/issues/52
