### ISSUE TITLE
MIMIC-II Data set

### ISSUE THREAD

**Issue by Quershi** [MIT-LCP/mimic-code#726]
I am a student of MS degree program. and my research in Mortality prediction in ICU through 4000 data of ICU patients.
I can't download MIMIC-II data set. I don't   know how to complete the CITI program. Please any body help me. i want 4000 data of ICU patients.

**Comment by lceli** [comment]
Please use the 2012 PhysioNet Challenge dataset:
Predicting Mortality of ICU Patients - The PhysioNet Computing in Cardiology Challenge 2012 v1.0.0

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Predicting Mortality of ICU Patients - The PhysioNet Computing in Cardio...


 |

 |

 |





    On Saturday, April 18, 2020, 12:50:28 PM EDT, FAWAD <notifications@github.com> wrote:  
 
 


I am a student of MS degree program. and my research in Mortality prediction in ICU through 4000 data of ICU patients.
I can't download MIMIC-II data set. I don't know how to complete the CITI program. Please any body help me. i want 4000 data of ICU patients.

**Comment by Quershi** [comment]
> Please use the 2012 PhysioNet Challenge dataset: Predicting Mortality of ICU Patients - The PhysioNet Computing in Cardiology Challenge 2012 v1.0.0 | | | | | | | | | | | Predicting Mortality of ICU Patients - The PhysioNet Computing in Cardio... | | | On Saturday, April 18, 2020, 12:50:28 PM EDT, FAWAD <notifications@github.com> wrote: I am a student of MS degree program. and my research in Mortality prediction in ICU through 4000 data of ICU patients. I can't download MIMIC-II data set. I don't know how to complete the CITI program. Please any body help me. i want 4000 data of ICU patients. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sir , you know that will help me in Mortality prediction of ICU Patients?

**Comment by alistairewj** [comment]
As Leo pointed out, the 2012 PhysioNet Challenge focused on mortality prediction. See the page for details: https://physionet.org/content/challenge-2012/1.0.0/
