### ISSUE TITLE
Pre-admission medication and diseases

### ISSUE THREAD

**Issue by phantom153** [MIT-LCP/mimic-code#729]
Hi,

How can I find the medications a patient is taking prior to his/her admission and the diseases he was diagnosed with, not including new diagnosis during current admissions?

Thanks

### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by phantom153** [comment]
Thanks.

Does HOME MEDICATIONS appear in Discharge summary?
Is HOME MEDICATIONS a set phrase?
How can I know when does the section of HOME MEDICATIONS ends?

And lastly, is there a similar heading for diseases on admission?

**Comment by alistairewj** [comment]
None of the section titles are set phrases, but there's only a handful that are commonly used (and a long tail of variations used once or twice).

There is a similar section used for diseases on admission - probably `PAST MEDICAL HISTORY` is the best bet. The `HISTORY OF PRESENT ILLNESS` section also has relevant information, but it does usually contain information pertinent to the current diagnosis.
