### ISSUE TITLE
Can't download the big size file in MIMIC III

### ISSUE THREAD

**Issue by wq3004** [MIT-LCP/mimic-code#731]
Hi,
 I had tried to download the CHARTEVENTS.cvs.gz (4.0GB) for many times, but it always failed. The other smaller files can be downloaded. I tried to download it by saved directly from the MIMIC website, or using AWS command line tool. The AWS CLI always remindered Max Retris Exceeded. Is there other way to get it? 
Thanks!

Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by tompollard** [comment]
@wq3004 there are several options listed in the "Files" section of the project. https://physionet.org/content/mimiciii/1.4/#files

If you'd like to download the data, I'd suggest using the Google Cloud (gsutil) option. A better option, though, may be to work with the data in Google Cloud directly. 

See: https://github.com/MIT-LCP/mimic-code/issues/723 for details on working with MIMIC-III in BigQuery. 

You can also analyse the data directly from a Colab Notebook (see the notebooks at https://github.com/MIT-LCP/sccm-datathon for example).
