### ISSUE TITLE
memory space required to calculate scores

### ISSUE THREAD

**Issue by datascience100** [MIT-LCP/mimic-code#732]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, I would like to know how much space I would need approximately in the memory of my Ubuntu where I have already an installation of MIMIC-III in a local PostgreSQL database to be able to calculate the scores of the Severity of illness scores with the scripts of the ´severityscores´ file provided in the MIMIC Code Repository. I would need to calculate the majority of them. Thank you very much.

**Comment by alistairewj** [comment]
Once you have installed the database, it should work with any amount of RAM you have. It will just work faster with more. Anything above 4 GB would work.
