### ISSUE TITLE
Probability of mortality for score 

### ISSUE THREAD

**Issue by datascience100** [MIT-LCP/mimic-code#733]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, I would like to know if from the scores of the Severity of illness scores that can be calculated with the scripts of the ´severityscores´ of the MIMIC Code Repository, I could calculate the probabilities of mortality or survival for each score. Thank you.

**Comment by alistairewj** [comment]
Where possible it is already calculated, e.g.  for SAPS II, APS III, and OASIS. Look for the column with suffix `_prob`.

**Comment by datascience100** [comment]
Thank you very much. A related question is: what is the usual cut-off (threshold) score for the Acute Physiology Score III (APS III) to predict ICU mortality?. I have been reading the literature and I found the cut-off score of 57 in a study but that seems too high.

**Comment by alistairewj** [comment]
There is no cut-off used really. People tend to calculate the value and compare two groups of patients using the average value or something similar. It's rarely dichotomized before use, which is probably why you can't find much information on that practice.
