### ISSUE TITLE
Is there a key for the ADMISSION_LOCATION column?

### ISSUE THREAD

**Issue by wdwightmiller** [MIT-LCP/mimic-code#735]
# Description

Is there a key for the ADMISSION_LOCATION column in the ADMISSIONS table? I can see from the description that 9 values are possible, but I'm confused by what some of the possible values mean: for instance, what is the difference between "TRANSFER FROM HOSP/EXTRAM" and "TRANSFER FROM OTHER HEALT"? What is "PHYS REFERRAL/NORMAL DELI"?

**Comment by alistairewj** [comment]
Not that I'm aware of. Those values are in the database as-is.
