### ISSUE TITLE
Questions about follow-up time in MIMIC-III

### ISSUE THREAD

**Issue by smallzccc** [MIT-LCP/mimic-code#736]
Hi
  In some topic posts, the follow-up time of patients is considered to be 90 days. However, when I searched articles about mimic-iii in PUBMED. I found they used follow-up time more than 90 days. For example: Red blood cell distribution width predicts long-term mortality in critically ill patients with acute kidney injury: a retrospective database study. DOI:10.1038/s41598-020-61516-y.
  I feel puzzled about the correct follow-up time, or is the database follow-up time different in different periods? @alistairewj  @tompollard 
  Thank you in advance!!

**Comment by alistairewj** [comment]
We compiled the database at a specific time, so some patients (e.g. admitted in 2002) will have longer follow up than other patients (e.g. those admitted in 2012). We always tell users that 90 days is the follow up time to be conservative; it's a lower bound.

**Comment by smallzccc** [comment]
Yeah
It is means for a design cohort of more than 90 days. We can not known how many people did not complete the follow-up, it is right? I think it should increase error in research process in such cohort research. At the same time, there is no explanation.
In the end, there no denfense that  MIMIC-III  can give the last follow-up time in the fucture.！

**Comment by alistairewj** [comment]
I don't 100% understand your point, but we can't give any more detail than 90 days due to the de-identification process.

**Comment by tompollard** [comment]
@smallzccc We cannot control how studies use MIMIC-III, but we can help to make sure that you have enough information to decide whether the findings are reliable. With studies published using private datasets, many issues go unseen. 

The benefit of public datasets like MIMIC-III is that conversations can be held in the open. In this case, you've quickly been able to find the answer to your question (as have other people in the past, e.g. https://github.com/MIT-LCP/mimic-code/issues/185).
