### ISSUE TITLE
ICD9 codes being stored as Integers in D_ICD_PROCEDURES for the Bigquery dataset?

### ISSUE THREAD

**Issue by royal10march** [MIT-LCP/mimic-code#737]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I just noticed while going through the dataset that ICD9 codes are being stored as integers inside D_ICD_PROCEDURES when you use the cloud access by importing the physionet-data on bigquery. This results in the ICD9 codes being same for two things when they are not the same because when you use integers 0039 gets converted to 39. Hence, I am seeing a lot of duplicate ICD9 codes on it.

**Comment by royal10march** [comment]
This seems to be the case on procedures_icd as well.

**Comment by tompollard** [comment]
thanks @royal10march, we'll look into this.

**Comment by tompollard** [comment]
Thanks for raising this issue @royal10march and sorry for the delay in getting to it. The icd9_codes in `d_icd_procedures` and `procedures_icd` were stored as integers on bigquery. The tables have now been fixed.
