### ISSUE TITLE
Waveform DB - ABP location

### ISSUE THREAD

**Issue by AguirreNicolas** [MIT-LCP/mimic-code#738]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I had looked about description in ABP channels. As far as I know it is a invasive measurement, right?

I would like to know, if possible, to which segment of the arterial tree the blood pressure measurements should correspond when the subject is in ICU.

Thank you

Nicolas

**Comment by alistairewj** [comment]
Continuously monitored ABP is from an invasive line, yes.

It's possible to derive this from information charted about the ABP. The site is usually documented alongside the presence of the line. I don't think I included the location in the query but here is something to get you started:
https://github.com/MIT-LCP/mimic-code/blob/f13dd19b0d842819ca137887f4ea6273b2493387/concepts/durations/arterial-line-durations.sql

**Comment by AguirreNicolas** [comment]
Hi Alistair,

Sorry for the delay! I'm not an expert in SQL =(

But, should I add to "make-concepts.sql" the line:
_\i durations/arterial-line-durations.sql"_
in the section "'Directory 1 of 9: durations'" to get what I want?

**Comment by AguirreNicolas** [comment]
Hi @alistairewj , sorry again ...

I can't understand the relation between:

https://github.com/MIT-LCP/mimic-code/blob/f13dd19b0d842819ca137887f4ea6273b2493387/concepts/durations/arterial-line-durations.sql#L19-L34
  
and 

https://github.com/MIT-LCP/mimic-code/blob/f13dd19b0d842819ca137887f4ea6273b2493387/concepts/durations/arterial-line-durations.sql#L36-L77

I have a list of icustay_id (and its waveforms) to which i'm interested to join its type/site (which is the different?).

**Comment by alistairewj** [comment]
Type is the type of line or the type of catheter; e.g. triple inducer, multi-lumen, arterial, and so on.

The site is where the line enters the body; e.g. right femoral, right radial, right brachial, etc.

Sounds like you are just interested in the type of line!

If you are unsure how to run the queries, you can [gain access to MIMIC-III on BigQuery](https://mimic.physionet.org/gettingstarted/cloud/), and then look at the `mimiciii_derived` dataset. There's a `pivoted_invasive_lines` table which has the information about the lines. The `arterial_line_durations` is essentially subselecting that table to the rows with the `type` being IABP or Arterial, then creating a starttime/stoptime by merging together rows if they are within 16 hours of each other.
