### ISSUE TITLE
Endoscopy reports

### ISSUE THREAD

**Issue by Aboelsoud** [MIT-LCP/mimic-code#74]
I was wondering if there is any way to find the endoscopy reports. I can see endoscopy done in the procedure ICD9 tables but I can't find notes in the notes events table. Any input?

Thanks

**Comment by lceli** [comment]
They are not available in MIMIC.

**Comment by rgmark** [comment]
I am sorry to say that we do not have endoscopy reports in the database.

Roger Mark

On 2/7/2016 2:00 PM, Aboelsoud wrote:
>
> I was wondering if there is any way to find the endoscopy reports I 
> can see endoscopy done in the procedure ICD9 tables but I can't find 
> notes in the notes events table Any input?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MIT-LCP/mimic-code/issues/74>.
>

-- 
Roger G. Mark, M.D., Ph.D.
Professor of HST and EECS
Massachusetts Institute of Technology
Room E25-505
Tel - 617-253-7818
Fax - 617-258-7859
