### ISSUE TITLE
Cannot find out more results about SOFA score and APACHE II in chartevents

### ISSUE THREAD

**Issue by hobewoos** [MIT-LCP/mimic-code#740]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

For one of my projects, I have to pull data for SOFA score and APACHEII score from the MIMIC-III database，
Variables itemid
sofa score 227428
APACHE ii 226743
THEN I run the following code in the Table Chartevents, there are only 10 results.
(select "hadm_id","itemid","value","valuenum"
from "mimiciii".chartevents
where mimiciii.chartevents.itemid= 227428 )

**Comment by alistairewj** [comment]
The care providers do not directly document SOFA or APACHE, though the field exists.

Instead we have retrospectively calculated these scores: https://github.com/MIT-LCP/mimic-code/tree/master/concepts/severityscores
