### ISSUE TITLE
Negative urine-ouput values in AKI scoring queries

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#745]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hi,
I noticed negative values in [kdigo-uo](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/organfailure/kdigo-uo.sql) which doesn't make sense:
<img width="589" alt="Screen Shot 2020-05-21 at 18 58 58" src="https://user-images.githubusercontent.com/23483971/82579113-033dc180-9b96-11ea-8ba1-3c2a7d6d5087.png">

I kept investigating and found that in [fluid-balance/urine-ouput](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/fluid-balance/urine-output.sql) there is a negative value fix for "GU irrigant" that creates values that does not make sense.

## Reproduce issue in BigQuery:
```
select ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, CHARTTIME, ITEMID 
, SUM(
    -- we consider input of GU irrigant as a negative volume
    case when oe.itemid = 227488 then -1*value
    else value end
  ) as VALUE,
  STORETIME
from `physionet-data.mimiciii_clinical.outputevents`  oe
where oe.itemid in
(
  -- these are the most frequently occurring urine output observations in CareVue
  40055, -- "Urine Out Foley"
  43175, -- "Urine ."
  40069, -- "Urine Out Void"
  40094, -- "Urine Out Condom Cath"
  40715, -- "Urine Out Suprapubic"
  40473, -- "Urine Out IleoConduit"
  40085, -- "Urine Out Incontinent"
  40057, -- "Urine Out Rt Nephrostomy"
  40056, -- "Urine Out Lt Nephrostomy"
  40405, -- "Urine Out Other"
  40428, -- "Urine Out Straight Cath"
  40086,--	Urine Out Incontinent
  40096, -- "Urine Out Ureteral Stent #1"
  40651, -- "Urine Out Ureteral Stent #2"

  -- these are the most frequently occurring urine output observations in MetaVision
  226559, -- "Foley"
  226560, -- "Void"
  226561, -- "Condom Cath"
  226584, -- "Ileoconduit"
  226563, -- "Suprapubic"
  226564, -- "R Nephrostomy"
  226565, -- "L Nephrostomy"
  226567, --	Straight Cath
  226557, -- R Ureteral Stent 
  226558, -- L Ureteral Stent
  227488, -- GU Irrigant Volume In
  227489  -- GU Irrigant/Urine Volume Out
) 
and oe.value < 5000 -- sanity check on urine value
and oe.icustay_id is not null 
and ICUSTAY_ID=290677
group by ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, CHARTTIME, ITEMID, STORETIME
ORDER BY ROW_ID
```

result:
<img width="678" alt="Screen Shot 2020-05-21 at 19 00 47" src="https://user-images.githubusercontent.com/23483971/82579359-59ab0000-9b96-11ea-8a4c-664697bc8cae.png">

## My questions

1. What does output value of 4000 "GU irrigant" means in practice for a clinician?
2. How would you suggest I treat negative urine-output values for research in clinical view?

Related Issue: https://github.com/MIT-LCP/mimic-code/issues/204

Thank you very much :)

**Comment by alistairewj** [comment]
Well, the thought process is that use of a G/U should not contribute to a patient's urine output since they are not actually generating that volume. However the volume used for the irrigant would be included in the total output volume, so subtracting it gives a more physiologically representative urine output. At least in theory :)

Usually what happens is they will document a GU irrigant volume in, and a GU irrigant volume out, and the subtraction of the two gives the true value. This seems to work earlier in that patient's stay:


icustay_id | charttime | itemid | label | value
--- | --- | --- | --- | ---
290677 | 2171-04-17T06:45:00 | 227489 | GU Irrigant/Urine Volume Out | 3860.0
290677 | 2171-04-17T06:45:00 | 227488 | GU Irrigant Volume In | -4000.0

So the raw data makes sense - and I think the kdigo result also makes sense given this context. Happy to hear about any disagreement if there is any!

Note that I haven't updated the BigQuery views to fix #712 yet, so the sums there right now are forward looking, not backward looking. That's why the value at 04:00:00 is negative.

**Comment by arielhasidim** [comment]
Very helpful, thank you very much.
 Also, sorry for the ugly images.

I have some followup questions:

1. What exactly does “GU Irrigant” mean in practice? A simple link will also suffice :)
2. What will I lose if I just drop item ids: 227488, 227489 when I sum urine output by hourly intervals?

BTW, as a part of my research, I wrote a query to sum and correct urine output by hourly interval, and I want to address this issue there ([PR](https://github.com/MIT-LCP/mimic-code/pull/721)).

**Comment by arielhasidim** [comment]
Answering myself:
1. [Continuous Bladder Irrigation and Care of a Foley Catheter](https://www.youtube.com/watch?v=9wGZ7YjuaFA)
2. From that I guess that if a drop the in/out items I will also lose the urine-ouput from that hour. 

Just to get a sense of how many ICU_STAYs had GU Irrigant:
Out of **55,077** ICU_STAYs, there is **287** with ITEMID 227488 ("GU Irrigant Volume In").

```
SELECT ICUSTAY_ID, ITEMID  
FROM `physionet-data.mimiciii_clinical.outputevents`
where ITEMID = 227488
group by ICUSTAY_ID, ITEMID 
```

I still think there is an issue with the code because I cant understand how does "forward looking, not backward looking" explain the negative values. The in/out rows have the same charttime,  the summing direction doesn't suppose to matters.

**Comment by arielhasidim** [comment]
Just leaving it here for further consideration or discussion:

I queried the raw `outputevents` table in bigquery to show all irrigation in/out so we can rethink the use of it. 
```
SELECT ROW_ID, ICUSTAY_ID, CHARTTIME, STORETIME, ITEMID, VALUE, VALUEUOM 
FROM `physionet-data.mimiciii_clinical.outputevents`
where ITEMID = 227488 OR ITEMID = 227489
order by ICUSTAY_ID, CHARTTIME, ITEMID  
limit 100
```
It seems that the in/out is paired with the same `CHARTTIME` for the most part. BUT - sometimes the "in" is bigger than "out", and sometimes it's the opposite. We can also see that the `STORETIME` is different between the paired values but it still doesn't suggest which is bigger (if we assume there was a mixup in coding `ITEMID`, we would expect that the later of the paired values will be bigger - which doesn't work in practice in every pair).

## My suggestion:
**I don't think this situation can be clarified well enough for research purposes.**
Because only 287/55,077 `ICU_STAY`s has `ITEMID`: 227488, I think we will better just exclude them, or better - state a list of `ICUSTAY`s we recommand exluding in urine-output based calculation and researches.


Row | ROW_ID | ICUSTAY_ID | CHARTTIME | STORETIME | ITEMID | VALUE |  
-- | -- | -- | -- | -- | -- | -- | --
1 | 2872810 | 200191 | 2160-11-25T21:00:00 | 2160-11-25T20:15:00 | 227488 | 60.0 |  
2 | 2872811 | 200191 | 2160-11-25T21:00:00 | 2160-11-25T20:16:00 | 227489 | 60.0 |  
3 | 4030286 | 200225 | 2127-09-13T15:00:00 | 2127-09-13T17:28:00 | 227488 | 2000.0 |  
4 | 4030312 | 200225 | 2127-09-13T15:00:00 | 2127-09-13T17:26:00 | 227489 | 1500.0 |  
5 | 4030287 | 200225 | 2127-09-13T16:00:00 | 2127-09-13T17:26:00 | 227488 | 1000.0 |  
6 | 4030313 | 200225 | 2127-09-13T16:00:00 | 2127-09-13T17:26:00 | 227489 | 1500.0 |  
7 | 4030288 | 200225 | 2127-09-13T17:00:00 | 2127-09-13T17:26:00 | 227488 | 3000.0 |  
8 | 4030314 | 200225 | 2127-09-13T17:00:00 | 2127-09-13T17:27:00 | 227489 | 2100.0 |  
9 | 4030289 | 200225 | 2127-09-13T18:00:00 | 2127-09-13T17:28:00 | 227488 | 3000.0 |  
10 | 4030315 | 200225 | 2127-09-13T18:00:00 | 2127-09-13T19:41:00 | 227489 | 2600.0 |  
11 | 4030290 | 200225 | 2127-09-13T19:00:00 | 2127-09-13T19:36:00 | 227488 | 3000.0 |  
12 | 4030316 | 200225 | 2127-09-13T19:00:00 | 2127-09-13T19:41:00 | 227489 | 3200.0 |  
13 | 4030291 | 200225 | 2127-09-13T20:15:00 | 2127-09-13T20:27:00 | 227488 | 3000.0 |  
14 | 4030317 | 200225 | 2127-09-13T20:15:00 | 2127-09-13T20:27:00 | 227489 | 3075.0 |  
15 | 4030292 | 200225 | 2127-09-13T21:00:00 | 2127-09-13T21:18:00 | 227488 | 3000.0 |  
16 | 4030318 | 200225 | 2127-09-13T21:00:00 | 2127-09-13T21:19:00 | 227489 | 3450.0 |  
17 | 4030293 | 200225 | 2127-09-13T22:00:00 | 2127-09-13T22:06:00 | 227488 | 3000.0 |  
18 | 4030319 | 200225 | 2127-09-13T22:00:00 | 2127-09-13T22:06:00 | 227489 | 3475.0 |  
19 | 4030294 | 200225 | 2127-09-13T23:00:00 | 2127-09-13T23:03:00 | 227488 | 3000.0 |  
20 | 4030320 | 200225 | 2127-09-13T23:00:00 | 2127-09-13T23:04:00 | 227489 | 3100.0 |  
21 | 4030295 | 200225 | 2127-09-14T00:00:00 | 2127-09-13T23:55:00 | 227488 | 3000.0 |  
22 | 4030321 | 200225 | 2127-09-14T00:00:00 | 2127-09-13T23:55:00 | 227489 | 3500.0 |  
23 | 4030296 | 200225 | 2127-09-14T00:30:00 | 2127-09-14T00:41:00 | 227488 | 3000.0 |  
24 | 4030322 | 200225 | 2127-09-14T00:30:00 | 2127-09-14T00:41:00 | 227489 | 3400.0 |  
25 | 4030297 | 200225 | 2127-09-14T02:00:00 | 2127-09-14T01:53:00 | 227488 | 3000.0 |  
26 | 4030323 | 200225 | 2127-09-14T02:00:00 | 2127-09-14T01:53:00 | 227489 | 3200.0 |  
27 | 4030298 | 200225 | 2127-09-14T03:30:00 | 2127-09-14T03:39:00 | 227488 | 3000.0 |  
28 | 4030324 | 200225 | 2127-09-14T03:30:00 | 2127-09-14T03:39:00 | 227489 | 3400.0 |  
29 | 4030299 | 200225 | 2127-09-14T06:46:00 | 2127-09-14T06:46:00 | 227488 | 3000.0 |  
30 | 4030325 | 200225 | 2127-09-14T06:46:00 | 2127-09-14T06:46:00 | 227489 | 3200.0 |  
31 | 4030300 | 200225 | 2127-09-14T09:00:00 | 2127-09-14T09:43:00 | 227488 | 3000.0 |  
32 | 4030326 | 200225 | 2127-09-14T09:00:00 | 2127-09-14T09:43:00 | 227489 | 4000.0 |  
33 | 4030301 | 200225 | 2127-09-14T11:00:00 | 2127-09-14T13:49:00 | 227488 | 3000.0 |  
34 | 4030327 | 200225 | 2127-09-14T11:00:00 | 2127-09-14T13:49:00 | 227489 | 3000.0 |  
35 | 4030302 | 200225 | 2127-09-14T13:00:00 | 2127-09-14T13:49:00 | 227488 | 3000.0 |  
36 | 4030328 | 200225 | 2127-09-14T13:00:00 | 2127-09-14T13:49:00 | 227489 | 3000.0 |  
37 | 4030303 | 200225 | 2127-09-14T14:00:00 | 2127-09-14T15:37:00 | 227488 | 3000.0 |  
38 | 4030329 | 200225 | 2127-09-14T14:00:00 | 2127-09-14T15:38:00 | 227489 | 3000.0 |  
39 | 4030304 | 200225 | 2127-09-14T15:00:00 | 2127-09-14T15:37:00 | 227488 | 3000.0 |  
40 | 4030330 | 200225 | 2127-09-14T15:00:00 | 2127-09-14T15:37:00 | 227489 | 3800.0 |  
41 | 4030305 | 200225 | 2127-09-14T17:00:00 | 2127-09-14T17:15:00 | 227488 | 3000.0 |  
42 | 4030331 | 200225 | 2127-09-14T17:00:00 | 2127-09-14T17:15:00 | 227489 | 3800.0 |  
43 | 4030306 | 200225 | 2127-09-14T20:00:00 | 2127-09-14T20:12:00 | 227488 | 3000.0 |  
44 | 4030332 | 200225 | 2127-09-14T20:00:00 | 2127-09-14T20:13:00 | 227489 | 3500.0 |  
45 | 4030307 | 200225 | 2127-09-14T23:00:00 | 2127-09-14T22:59:00 | 227488 | 2000.0 |  
46 | 4030333 | 200225 | 2127-09-14T23:00:00 | 2127-09-14T22:58:00 | 227489 | 3000.0 |  
47 | 4030308 | 200225 | 2127-09-15T02:00:00 | 2127-09-15T01:53:00 | 227488 | 3000.0 |  
48 | 4030334 | 200225 | 2127-09-15T02:00:00 | 2127-09-15T01:53:00 | 227489 | 2800.0 |  
49 | 4030309 | 200225 | 2127-09-15T05:00:00 | 2127-09-15T05:05:00 | 227488 | 3000.0 |  
50 | 4030310 | 200225 | 2127-09-15T06:00:00 | 2127-09-15T05:41:00 | 227488 | 3000.0 |  
51 | 4030335 | 200225 | 2127-09-15T06:00:00 | 2127-09-15T05:41:00 | 227489 | 2900.0 |  
52 | 4030311 | 200225 | 2127-09-15T12:00:00 | 2127-09-15T14:58:00 | 227488 | 2500.0 |  
53 | 4030336 | 200225 | 2127-09-15T12:00:00 | 2127-09-15T14:58:00 | 227489 | 3000.0 |  
54 | 4345743 | 201559 | 2136-10-26T02:00:00 | 2136-10-26T02:41:00 | 227488 | 10.0 |  
55 | 2976058 | 202124 | 2125-01-02T00:00:00 | 2125-01-02T01:25:00 | 227488 | 42.0 |  
56 | 2976131 | 202124 | 2125-01-02T01:00:00 | 2125-01-02T01:23:00 | 227489 | 120.0 |  
57 | 2976059 | 202124 | 2125-01-02T01:23:00 | 2125-01-02T01:25:00 | 227488 | 42.0 |  
58 | 2976060 | 202124 | 2125-01-02T02:00:00 | 2125-01-02T03:41:00 | 227488 | 42.0 |  
59 | 2976061 | 202124 | 2125-01-02T03:00:00 | 2125-01-02T03:41:00 | 227488 | 42.0 |  
60 | 2976132 | 202124 | 2125-01-02T03:00:00 | 2125-01-02T03:41:00 | 227489 | 100.0 |  
61 | 2976062 | 202124 | 2125-01-02T04:00:00 | 2125-01-02T06:30:00 | 227488 | 42.0 |  
62 | 2976063 | 202124 | 2125-01-02T05:00:00 | 2125-01-02T06:30:00 | 227488 | 42.0 |  
63 | 2976064 | 202124 | 2125-01-02T06:00:00 | 2125-01-02T06:30:00 | 227488 | 42.0 |  
64 | 2976065 | 202124 | 2125-01-02T07:00:00 | 2125-01-02T06:30:00 | 227488 | 42.0 |  
65 | 2976133 | 202124 | 2125-01-02T07:00:00 | 2125-01-02T07:13:00 | 227489 | 200.0 |  
66 | 2976066 | 202124 | 2125-01-02T08:00:00 | 2125-01-02T10:26:00 | 227488 | 42.0 |  
67 | 2976067 | 202124 | 2125-01-02T09:00:00 | 2125-01-02T10:26:00 | 227488 | 42.0 |  
68 | 2976068 | 202124 | 2125-01-02T10:00:00 | 2125-01-02T10:26:00 | 227488 | 42.0 |  
69 | 2976069 | 202124 | 2125-01-02T11:00:00 | 2125-01-02T11:04:00 | 227488 | 42.0 |  
70 | 2976070 | 202124 | 2125-01-02T12:00:00 | 2125-01-02T11:53:00 | 227488 | 42.0 |  
71 | 2976071 | 202124 | 2125-01-02T13:00:00 | 2125-01-02T13:22:00 | 227488 | 42.0 |  
72 | 2976072 | 202124 | 2125-01-02T14:00:00 | 2125-01-02T16:30:00 | 227488 | 42.0 |  
73 | 2976073 | 202124 | 2125-01-02T15:00:00 | 2125-01-02T16:30:00 | 227488 | 42.0 |  
74 | 2976074 | 202124 | 2125-01-02T16:00:00 | 2125-01-02T16:30:00 | 227488 | 42.0 |  
75 | 2976075 | 202124 | 2125-01-02T17:00:00 | 2125-01-02T16:30:00 | 227488 | 42.0 |  
76 | 2976076 | 202124 | 2125-01-02T18:00:00 | 2125-01-02T17:17:00 | 227488 | 42.0 |  
77 | 2976077 | 202124 | 2125-01-02T19:00:00 | 2125-01-02T17:17:00 | 227488 | 42.0 |  
78 | 2976078 | 202124 | 2125-01-02T20:00:00 | 2125-01-02T23:02:00 | 227488 | 42.0 |  
79 | 2976079 | 202124 | 2125-01-02T21:00:00 | 2125-01-02T23:02:00 | 227488 | 42.0 |  
80 | 2976080 | 202124 | 2125-01-02T22:00:00 | 2125-01-02T23:02:00 | 227488 | 42.0 |  
81 | 2976081 | 202124 | 2125-01-02T23:00:00 | 2125-01-02T23:02:00 | 227488 | 42.0 |  
82 | 2976082 | 202124 | 2125-01-03T00:00:00 | 2125-01-03T01:26:00 | 227488 | 42.0 |  
83 | 2976083 | 202124 | 2125-01-03T01:00:00 | 2125-01-03T01:26:00 | 227488 | 42.0 |  
84 | 2976084 | 202124 | 2125-01-03T02:00:00 | 2125-01-03T05:06:00 | 227488 | 42.0 |  
85 | 2976085 | 202124 | 2125-01-03T03:00:00 | 2125-01-03T05:06:00 | 227488 | 42.0 |  
86 | 2976086 | 202124 | 2125-01-03T04:00:00 | 2125-01-03T05:06:00 | 227488 | 42.0 |  
87 | 2976087 | 202124 | 2125-01-03T05:00:00 | 2125-01-03T05:06:00 | 227488 | 42.0 |  
88 | 2976088 | 202124 | 2125-01-03T06:00:00 | 2125-01-03T06:38:00 | 227488 | 42.0 |  
89 | 2976089 | 202124 | 2125-01-03T07:00:00 | 2125-01-03T08:55:00 | 227488 | 42.0 |  
90 | 2976090 | 202124 | 2125-01-03T08:00:00 | 2125-01-03T08:55:00 | 227488 | 42.0 |  
91 | 2976091 | 202124 | 2125-01-03T09:00:00 | 2125-01-03T08:55:00 | 227488 | 42.0 |  
92 | 2976092 | 202124 | 2125-01-03T10:00:00 | 2125-01-03T09:58:00 | 227488 | 42.0 |  
93 | 2976093 | 202124 | 2125-01-03T11:00:00 | 2125-01-03T13:14:00 | 227488 | 42.0 |  
94 | 2976094 | 202124 | 2125-01-03T12:00:00 | 2125-01-03T13:14:00 | 227488 | 42.0 |  
95 | 2976095 | 202124 | 2125-01-03T13:00:00 | 2125-01-03T13:14:00 | 227488 | 42.0 |  
96 | 2976096 | 202124 | 2125-01-03T14:00:00 | 2125-01-03T16:03:00 | 227488 | 42.0 |  
97 | 2976097 | 202124 | 2125-01-03T15:00:00 | 2125-01-03T16:03:00 | 227488 | 42.0 |  
98 | 2976098 | 202124 | 2125-01-03T16:00:00 | 2125-01-03T16:03:00 | 227488 | 42.0 |  
99 | 2976099 | 202124 | 2125-01-03T17:00:00 | 2125-01-03T17:35:00 | 227488 | 42.0 |  
100 | 2976100 | 202124 | 2125-01-03T18:00:00 | 2125-01-03T17:35:00 | 227488 | 42.0
