### ISSUE TITLE
Map the ItemIDs into the ICD-9 and/or ICD-10 Codes

### ISSUE THREAD

**Issue by simeonem** [MIT-LCP/mimic-code#746]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

The MIMIC3 has ItemIDs and ICD-9 Codes. To the best of my knowledge, there is no mapping between the 2 sets of codes. I understand they have a different purpose, but mapping ItemIDs into the standard nomenclature used in EHR would be very useful. Of course, it won't be a one-to-one match (there are more ItemIDs than ICD-9 codes), but at least that will supply a way to list the ItemIDs under the general ICD nomenclature.
Hopefully someone can help !!
Thank you very much !!
Simeone Marino (simeonem@umich.edu)

**Comment by alistairewj** [comment]
There is no way to map MIMIC-III `itemid` to ICD-9 / ICD-10 codes. The ICD codes are built for classifying diagnoses and procedures, and they do not cover the same concepts as the `itemid`. There are other ontologies which are more appropriate (SNOMED, LOINC, etc), but to date no one has released a mapping. We would of course welcome any contribution of that sort!
