### ISSUE TITLE
Vent Days

### ISSUE THREAD

**Issue by Iyobosaiyamu** [MIT-LCP/mimic-code#748]
2 questions please:
1)How are intubation days defined?/how are they calculated?
2)How are intubation days calculated when a patient goes off and on the ventilator?

**Comment by alistairewj** [comment]
Please see the published article describing this repository for detail: [The MIMIC Code Repository.](https://doi.org/10.1093/jamia/ocx084)

In particular Figure 3 and the accompanying text.

**Comment by Iyobosaiyamu** [comment]
Thank you for your response, the article was a bit helpful. But i'm still quite confused as to how the intubation day are counted if a patient goes back on the ventilator again. Are the vent days added up? Or counted separately?

**Comment by alistairewj** [comment]
In the ventilation duration query, distinct ventilation events are not aggregated. The code is also written to separate re-intubations as a distinct event, though this doesn't work 100% of the time.
