### ISSUE TITLE
Missing data in the echodata view

### ISSUE THREAD

**Issue by MumuTW** [MIT-LCP/mimic-code#750]
I've found that there are a lots of missing data in the materialized view **'echodata'**.
Approx. 1/3 of the data in column **'hadm_id'** were missing. 
Maybe we could fill up the missing data by querying charttime by using the admissions.cvs.

**Comment by alistairewj** [comment]
Echocardiograms are not necessarily measured in the hospital. The ones missing `hadm_id` are probably outpatient echos and so they won't have an overlapping admission in the admissions table.
