### ISSUE TITLE
Hematocrit itemids

### ISSUE THREAD

**Issue by sindhura97** [MIT-LCP/mimic-code#751]
ITEMID    LABEL
220545	hematocrit (serum)
226540	hematocrit (whole blood - calc)

These itemids and labels are found in MIMIC-III.
But what does **hematocrit (serum)** mean, since hematocrit is not present in serum?

**Comment by pszolovits** [comment]
Not sure I have great insight into your question, but I would look for hematocrit values in lab events, with itemids defined in d_labitems, not in chartevents/d_items, which is the source you are referencing. Note:

mysql> select itemid, count(*) c from labevents where itemid in (50810, 51221) group by itemid;
+--------+--------+
| itemid | c      |
+--------+--------+
|  50810 |  89715 |
|  51221 | 881764 |
+--------+--------+

mysql> select itemid, count(*) c from chartevents where itemid in (220545, 226540) group by itemid;
+--------+--------+
| itemid | c      |
+--------+--------+
| 220545 | 165862 |
| 226540 |  18080 |
+--------+--------+

In my experience, most values noted in chartevents that are actually measured in a laboratory (not at the bedside) are partial copies from the lab data into the chart, perhaps to make retrieval and correlation with other chart data easier for the nurses.  (Just guessing.)

Also note that you have only identified the Metavision version of hematocrit, not the Carevue one:
mysql> select * from d_items where label like '%hematocrit%';
+--------+--------+---------------------------------+---------------------------------+------------+-------------+------------------------+----------+------------+-----------+
| ROW_ID | ITEMID | LABEL                           | ABBREVIATION                    | DBSOURCE   | LINKSTO     | CATEGORY               | UNITNAME | PARAM_TYPE | CONCEPTID |
+--------+--------+---------------------------------+---------------------------------+------------+-------------+------------------------+----------+------------+-----------+
|    732 |    813 | Hematocrit                      | NULL                            | carevue    | chartevents | Hematology             | NULL     | NULL       | NULL      |
|   2878 |   3761 | Hematocrit (35-51)              | NULL                            | carevue    | chartevents | ABG'S                  | NULL     | NULL       | NULL      |
|  12685 | 220545 | Hematocrit (serum)              | Hematocrit (serum)              | metavision | chartevents | Labs                   | None     | Numeric    | NULL      |
|  14407 | 226540 | Hematocrit (whole blood - calc) | Hematocrit (whole blood - calc) | metavision | chartevents | Labs                   | None     | Numeric    | NULL      |
|  14522 | 226761 | HematocritApacheIIScore         | HematocritApacheIIScore         | metavision | chartevents | Scores - APACHE II     | None     | Numeric    | NULL      |
|  14523 | 226762 | HematocritApacheIIValue         | HematocritApacheIIValue         | metavision | chartevents | Scores - APACHE II     | None     | Numeric    | NULL      |
|  14694 | 227017 | Hematocrit_ApacheIV             | Hematocrit_ApacheIV             | metavision | chartevents | Scores - APACHE IV (2) | None     | Numeric    | NULL      |
+--------+--------+---------------------------------+---------------------------------+------------+-------------+------------------------+----------+------------+-----------+

mysql> select * from d_labitems where label like '%hematocrit%';
+--------+--------+-------------------------+---------------------------+------------+------------+
| ROW_ID | ITEMID | LABEL                   | FLUID                     | CATEGORY   | LOINC_CODE |
+--------+--------+-------------------------+---------------------------+------------+------------+
|     11 |  50810 | Hematocrit, Calculated  | Blood                     | Blood Gas  | 20570-8    |
|    315 |  51115 | Hematocrit, Ascites     | Ascites                   | Hematology | NULL       |
|    421 |  51221 | Hematocrit              | Blood                     | Hematology | 4544-3     |
|    548 |  51348 | Hematocrit, CSF         | Cerebrospinal Fluid (CSF) | Hematology | 30398-2    |
|    569 |  51369 | Hematocrit, Joint Fluid | Joint Fluid               | Hematology | NULL       |
|    622 |  51422 | Hematocrit, Other Fluid | Other Body Fluid          | Hematology | 11153-4    |
|    645 |  51445 | Hematocrit, Pleural     | Pleural                   | Hematology | NULL       |
|    680 |  51480 | Hematocrit              | Urine                     | Hematology | 17809-5    |
+--------+--------+-------------------------+---------------------------+------------+------------+

**Comment by alistairewj** [comment]
Yep you should definitely be using labevents to get lab data. Just to add on, I agree that "serum" is a misnomer for hematocrit. They are mainly trying to differentiate measured hematocrit against the estimated value sourced from the blood gas analyzer.

**Comment by sindhura97** [comment]
Thanks for the comments, they were helpful. I noticed many labevents copied into chartevents, so I will make sure to look into labevents for certain features.
