### ISSUE TITLE
Unable to access Vital signs and Raw ECG and PPG signals 

### ISSUE THREAD

**Issue by mittalh** [MIT-LCP/mimic-code#752]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I have tried all the instructions that have been provided to access the data set on AWS. I am having a hard time finding the PPG & ECG signals and Vital Signs for patients, based on their subject_id. I am not able to locate the exact tables and data.

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
PPG & ECG signals are in the matched waveform database. You can read about this database here: https://physionet.org/content/mimic3wdb-matched/1.0/

You will need to link the two using the subject identifier and times.
