### ISSUE TITLE
What is itemid 30140 in inputevents?

### ISSUE THREAD

**Issue by sindhura97** [MIT-LCP/mimic-code#754]
ITEMID 30140 occurs quite often in INPUTEVENTS_CV.csv but is not found in D_ITEMS.csv. What is this item?

**Comment by alistairewj** [comment]
30140 is definitely in d_items:

```sql
SELECT * FROM `physionet-data.mimiciii_clinical.d_items`
where itemid = 30140
```

ITEMID | LABEL | LINKSTO
--- | --- | ---
30140 | N/A | inputevents_cv

Of course the label "N/A" isn't very informative! All I can tell you is that when they were documenting the solution for the infusion, they put `"N/A"`.

**Comment by sindhura97** [comment]
Yeah, my bad, I meant to say the label is N/A.
