### ISSUE TITLE
What is the correct method to find all ITEMIDs for a specific drug?

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#756]
Hello again,
Because of the duplication in ITEMIDs for every drug, that also depends in the generic and brand name, I'm really pondering whats the right approach to do so.

My most devised method yet:
1. Find generic name (there is great indexes around like [ddd](https://www.whocc.no/atc_ddd_index/) and [SNOMED-CT](https://browser.ihtsdotools.org/?perspective=full&conceptId1=404684003&edition=MAIN/2020-03-09&release=&languages=en))
2. Check UPTODATE for the brand **name in the US** (is it enough?)
3. Run the following example query for every brand and generic name (BQ):
```
SELECT label, itemid
FROM `physionet-data.mimiciii_clinical.d_items` 
WHERE lower(label) like '%furosemid%' OR lower(label) like '%lasix%';
```
Exampled output:
Row | label | itemid |  
-- | -- | -- | --
1 | Lasix | 4219 |  
2 | Furosemide/Lasix | 3439 |  
3 | lasix | 4888 |  
4 | IV Lasix | 6120 |  
5 | LASIX | 7780 |  
6 | Lasix | 30123 |  
7 | Furosemide (Lasix) 500/100 | 228340 |  
8 | Furosemide (Lasix) | 221794

Would like to know if you thing its enough or maybe some other tips :)

**Comment by alistairewj** [comment]
Yep that sounds like a great strategy. It's actually not as daunting as a task as it's seems:

1. MetaVision pretty much only has the generic name in one `itemid`, though sometimes they have distinct `itemid` for distinct formulations (as you see above for lasix)
2. CareVue usually has one `itemid` as well but it's either generic or brand name (which ever was colloquially more common, usually the shorter name, in this case it's lasix). Then there are 1-10 extra `itemid` which are sort of one-off instances of documentation. Essentially you could type free-text the concept into the CareVue system, and if it didn't match a prior `itemid` a new one is generated. So you'll find that 99% of the data is documented under 30123, and then maybe 10-50 rows documented under the remaining `itemid`.
3. Note also the `linksto` column: it should be inputevents_*. You'll note the last three `itemid` (30123, 228340, 221794) will likely link to the desired tables, whereas the first 5 link to chartevents as they are one-off administrations. I can infer this from the `itemid` as values in the 30000s link to administrations in CareVue inputevents_cv.

**Comment by arielhasidim** [comment]
Pleasure as always.
Hope this thread will help others in the future.
