### ISSUE TITLE
K phos units in INPUTEVENTS

### ISSUE THREAD

**Issue by sindhura97** [MIT-LCP/mimic-code#758]
Potassium Phosphate occurs with units 'mmol' and also 'mEq'. Is there a way to convert between the two?
There are the ITEMIDs:
225834 k phos
30029   potassium phosphate

**Comment by alistairewj** [comment]
Unit conversions are definitely possible - feel free to search online and post what you find. Converting between mmol and mEq is a nice lesson in chemistry!
