### ISSUE TITLE
Are prescriptions duplicated in inputevents?

### ISSUE THREAD

**Issue by sindhura97** [MIT-LCP/mimic-code#759]
If a prescription medicine is given to a patient, is it entered in inputevents?

**Comment by sindhura97** [comment]
If a prescription medicine is given to a patient, is it entered in inputevents?

**Comment by alistairewj** [comment]
If an intravenous medication is given to a patient they will document it in inputevents. All medications given to a patient in the hospital are associated with an order/prescription.
