### ISSUE TITLE
How to know the ICU stay sequence if the patient had two icustay?

### ISSUE THREAD

**Issue by wq3004** [MIT-LCP/mimic-code#760]
Hi,
    How to know the ICU stay sequence if the patient had two icustay? Does it follow the icustay number? Can I deem the biger of icustay number as the lastest icustay?
    Thanks!

**Comment by alistairewj** [comment]
The sequence of `icustay_id` is random. Do not use it for anything.

You can sort the stays by their `intime`, and that will give you the correct chronological order of their stays. Also check out the icustay detail query which calculates the stay sequence in SQL: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/demographics/icustay_detail.sql
