### ISSUE TITLE
Are there any reference value ranges of clinical notes ('TEXT') in 'NOTEEVENTS' ?

### ISSUE THREAD

**Issue by l3361269** [MIT-LCP/mimic-code#765]
Dear all, 
    I want to ask that whether there are any reference value ranges of reports in clinical notes (`TEXT` column) of table `NOTEEVENTS`? 
For example, in `NOTEEVENTS` and `ROW_ID==374898`, the part of report content of its `TEXT` shows as below:
```
Flowsheet Data as of [**2142-5-20**] 09:10 PM
   Vital Signs
   Hemodynamic monitoring
   Fluid Balance
                                                                  24 hours
                                                               Since 12 AM
   BP: 200/118(139) {200/118(139) - 200/118(139)} mmHg
   RR: 24 (24 - 24) insp/min
   SpO2: 100%
   Heart rhythm: ST (Sinus Tachycardia)
             Total In:
             2 mL
   PO:
             TF:
   IVF:
   2 mL
   Blood products:
   Total out:
                                                                      0 mL
                                                                      0 mL
   Urine:
   NG:
   Stool:
   Drains:
   Balance:
                                                                      0 mL
                                                                      2 mL
   Respiratory
   SpO2: 100%
```
And what I want to do is changing the value number into the terms like 'normal', 'low', 'high', etc.
For example: 
 ```
BP: 200/118 => BP: high/high
RR: 24 => RR: high
SpO2: 100% => normal
``` 
(reference value range: 
BP (blood pressure): 90-140/60-90 mmHg, refer to American Heart Association
RR (respiratory rate): 10-20 insp/min, refer to who
SpO2 (oxygen saturation): 95-100%, refer to who
)

However, there are so many test items in the reports of clinical notes (`TEXT` column in table `NOTEEVENTS`), so it is very difficult to find out every test item and searching for their reference value ranges. 
Furthermore, the reference value ranges vary from every hospital and lab, so it's better if have the reference value ranges from 'Beth Israel Deaconess Medical Center' (where MIMIC data collected from).

As a result, I want to ask whether there are any reference value ranges provided from  'Beth Israel Deaconess Medical Center' (where MIMIC data collected from)?

Thanks a lot!!!

**Comment by alistairewj** [comment]
Unfortunately reference ranges for free-text data don't really exist in the raw database. You can certainly come up with reasonable references though.

**Comment by l3361269** [comment]
I see. Thanks for @alistairewj 's reply :) !
 
I have tried to find out reference ranges from the web of 'Beth Israel Deaconess Medical Center',
however, I failed.
So do you know how to get reference ranges for reports of 'Beth Israel Deaconess Medical Center'? 

Thanks a lot !!!!

**Comment by alistairewj** [comment]
I don't think that the equipment the BIDMC uses to measure SpO2, BP, etc is homogenous, and I don't believe it comes with reference ranges the same way that laboratory values do. Even if they did I don't think there's any way to tell the device provenance of a measurement written in a free-text note. So with that in mind I'd say your reference ranges sourced from the AHA or the WHO are probably the best thing to go with.

**Comment by l3361269** [comment]
Ok, really appreciate your patience for detailed explanation! :)
I will continue looking for reference ranges from WHO, etc.

**Comment by Xushw9** [comment]
> Dear yichun, I wanna ask that how did you deal with these text data in column TEXT of table NOTEEVENTS, to make them convert them into data that can be analyzed?

Looking forward to your reply! Thanks a lot!
