### ISSUE TITLE
eGFR  from labevents

### ISSUE THREAD

**Issue by Iwtmyc** [MIT-LCP/mimic-code#766]
### Description
when I tried to get eGFR from labevents according to itemid. I get an excel doc, which contains charttime and value. But it shows "see comments" in the value.  However, i did not find where the comments are. Could you please help me to figure out where the comments referred to?

**Comment by tompollard** [comment]
The "Comments" refers to an additional column in the raw data that is not available in the public MIMIC-III dataset. 

Side note, but the document you are looking at is a CSV, not an Excel document. If you view the document in Excel, you may find that it mangles details like dates.

**Comment by Iwtmyc** [comment]
right!it is CSV format. So it means that I could not get access to the eGFR?

**Comment by alistairewj** [comment]
Unfortunately the comments are not available in MIMIC-III, and there are no plans to add them. They are available in [MIMIC-IV](https://physionet.org/content/mimiciv/) and we recommend you try there!
