### ISSUE TITLE
procedure date

### ISSUE THREAD

**Issue by Iwtmyc** [MIT-LCP/mimic-code#767]
Could I search procedure date from the the mimic iii? Looking forward to your reply.

**Comment by alistairewj** [comment]
Documentation of the billed ICD procedure codes is here: https://mimic.physionet.org/mimictables/procedures_icd/

**Comment by Iwtmyc** [comment]
Hello Johnson,
&nbsp; &nbsp; &nbsp;I mean could I figure out when the procedure was done. &nbsp;Like procedure was done 06-21-2045. Thank you.
Shengnan.

发自我的iPhone


------------------ Original ------------------

**Comment by alistairewj** [comment]
No, that information is not in the table unfortunately.
