### ISSUE TITLE
units of measurement for creatinine

### ISSUE THREAD

**Issue by datascience100** [MIT-LCP/mimic-code#769]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello, 
When looking at the creatinine values from chartevents and pivoted_vital I observed values that must correspond to different untis of measurement. The majority are given in mg/dL, but some are given in micromol/L. The valueuom field is empty in chartevents, and the unitname field is empty in d_items. In pivoted_lab the creatinine column was created deleting the values  >  150 for mg/dL, but this is an impossible value in mg/dL  (normal around 0.7 mg/dL to 1.2 mg/dL)  and possible in micromol/L. The loinc_code says it is measured in mg/dL, but some values are probably in micromol/L. I don´t know how to detect that and make the conversion if the units of measurement are not given. 
Thank you.

**Comment by alistairewj** [comment]
The unit of measure should always be mg/dL. The `> 150` filter is an extremely loose threshold meant to remove physiologically impossible data. There's no additional information about the unit beyond what you've found, so it's just a matter of checking the data. If you think the threshold can be lowered from your exploration I'd be happy to merge a PR.
