### ISSUE TITLE
Requesting SAPS-II for MIMIC-II

### ISSUE THREAD

**Issue by mihurtado** [MIT-LCP/mimic-code#77]
I'm looking for a code to get the SAPS-II score over MIMIC2v26. 
I know that SAPS-I score is already precalculated, but I need to perform operations using SAPS-II
I'll be really grateful if someone has the code and share it with me.
Thanks!

**Comment by alistairewj** [comment]
It's not available for MIMIC2v26. It is available for MIMIC-III though, check the severity scores subfolder:

https://github.com/MIT-LCP/mimic-code/tree/master/severityscores

It's probably pretty not too tough to port it to MIMIC2v26, if you really need it there. But you'd also need to port all the materialized views in the https://github.com/MIT-LCP/mimic-code/tree/master/etc subfolder.
