### ISSUE TITLE
Notes and data not in MIMIC-III

### ISSUE THREAD

**Issue by cshivade** [MIT-LCP/mimic-code#771]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hello, 

I am interested in determining if the data (notes and tables) necessary for writing a Discharge Summary for a hospital stay is available in the MIMIC-III database. From this [issue](https://github.com/MIT-LCP/mimic-code/issues/547#issuecomment-482403282) the NOTEEVENTS table seems to have the following notes

| Row | ICU status  | Notes available in NOTEEVENTS in MIMIC-III |
| --- | ----------- | ---------------------------------- |
|  1  | in ICU	    | All notes						   |
| 2   | outside ICU  | radiology, echo, ECG, Discharge Summary |

A patient will typically stay in the hospital beyond the ICU and finally get discharged. The patient will also be in the hospital (either in the ED or otherwise) before being admitted in the ICU. There will be progress notes, etc. written for the patient during this period. But these notes (except in row 2 above) are not available under the NOTEVENTS table in MIMIC-III. Is that right? 
(Based on the discussion here I am happy to submit a PR for the `Table Purpose` stated [here](https://github.com/MIT-LCP/mimic-website/blob/master/content/mimictables/noteevents.md))

Does a similar logic apply to the tabular data as well?

**Comment by alistairewj** [comment]
Yes, you have it right. We don't have the care provider notes from their hospital stay unless they are in the ICU. Happy for a PR!

It depends on the tabular data. Labs are hospital wide, but chartevents is ICU only. Hopefully the table specific documentation mentions this, but if they don't anywhere feel free to raise it or make a PR to fix.
