### ISSUE TITLE
How to extract rejection data of renal transplantation

### ISSUE THREAD

**Issue by VivilLhuiyao** [MIT-LCP/mimic-code#772]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I would like to ask a question, can I screen the subject_id of a specific surgical patient, such as a kidney transplant patient. I looked through the information, but I couldn't find the detailed operation information,only the major categories of surgery, such as urinary system surgery. In addition, whether there is a record of renal transplant rejection, I did not find it in the description.

**Comment by alistairewj** [comment]
You'll have to look up the specific ICD-9 codes corresponding to kidney transplants. There are also codes for transplants with mention of rejection.
