### ISSUE TITLE
Fluid Balance within 48h after ICU admission

### ISSUE THREAD

**Issue by Zheng7AI310** [MIT-LCP/mimic-code#774]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
*How to extract **fluid balance (FB)** status within 48 h after ICU admission (≥or < 0 ml/kg/48 h)
  thanks！

**Comment by alistairewj** [comment]
Fluid balance can be calculated by summing up all the inputs in inputevents_cv/inputevents_mv and subtracting all the outputs in outputevents.
