### ISSUE TITLE
What does the valuenum mean for itemid 223849 --- Ventilator Mode in the chartevents? 

### ISSUE THREAD

**Issue by Yanjiayork** [MIT-LCP/mimic-code#778]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I don't quite understand  valuenum for "Ventilator Mode" in the chartevents, for example, 

itemid         value                                     valuenum
223849    CMV/ASSIST/AutoFlow          49

In this case, I am not sure 49 is a categorical represent for the ventilator Mode value or it is some continuous value?  If so, will 48 be meaningful  for the ventilator Mode?  Where can I find the description for the 'Ventilator Mode'?

Thanks

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
The `valuenum` does not have any physical meaning in this case. It's just an integer that represents the text string. You'll find that every `value` of 'CMV/ASSIST/AutoFlow' is associated with the `valuenum` of 49.

**Comment by Yanjiayork** [comment]
Thank you for the clear explanation. Very helpful!
