### ISSUE TITLE
Gestational age is a range

### ISSUE THREAD

**Issue by gbf1112** [MIT-LCP/mimic-code#779]
Dear  everyone 
      I'd like to do  some  study  about  newborns in  mimic, I find  gestional  age in mimiciii.chartevents : 26-29ges  or  30-32 PMA ,but  I want to know Specific Numbers,  for example  30weeks.

**Comment by alistairewj** [comment]
We won't be able to provide any more data regarding individual patients - if that's the only documentation of gestational age then we won't be able to tell you more.
