### ISSUE TITLE
OASIS 

### ISSUE THREAD

**Issue by rahuldebsarkar** [MIT-LCP/mimic-code#783]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

Can I have some help please in identifying the table in MIMIC-III that contains the OASIS score for each patient? Somehow I cannot find this.

Thanks

Rahul

**Comment by tompollard** [comment]
@rahuldebsarkar OASIS is severity of illness score that is derived from the raw data. If you are using BigQuery, an OASIS table can be found in the `mimic_derived` dataset. If you are running a local version of MIMIC, the table can be generated with https://github.com/MIT-LCP/mimic-code/blob/master/concepts/severityscores/oasis.sql

**Comment by rahuldebsarkar** [comment]
Thanks very much
