### ISSUE TITLE
can't find waveforms

### ISSUE THREAD

**Issue by irivor** [MIT-LCP/mimic-code#785]
hi, 
I'm started to work with MIMIC
with BigQuery I found id_patients which have "shock" in d_icd_diagnoses
I want to do some analysis with their numeric waveforms 
But I can't find they in ATM
There aren't nesessary date in https://physionet.org/content/mimic3wdb-matched/1.0/#files-panel
How can I find numeric waveforms in ATM https://archive.physionet.org/cgi-bin/atm/ATM?

**Comment by alistairewj** [comment]
I'm not familiar enough with the ATM to give you advice there. But not all patients have waveforms - you shouldn't expect to find every patient in the waveform database.  Waveforms are aligned to subjects using the subject identifier and the date, e.g. `p000030-2172-10-16-12-22.hea` is `subject_id` = 30 and the waveform record starts on 2172-10-16 12:22.

**Comment by irivor** [comment]
thanks
I try
