### ISSUE TITLE
Which courses in CITI training are required to access MIMIC data?

### ISSUE THREAD

**Issue by qingerVT** [MIT-LCP/mimic-code#786]
FYI

**Comment by alistairewj** [comment]
See the [requesting access page](https://mimic.physionet.org/gettingstarted/access/).

> ### Complete the required training course
>
> Prior to requesting access to MIMIC, you will need to complete the CITI “Data or Specimens Only Research” course:
> 
> - First register on the CITI program website, selecting “Massachusetts Institute of Technology Affiliates” as your affiliation (_**not** "independent learner"_): https://www.citiprogram.org/index.cfm?pageID=154&icat=0&ac=0
> - Follow the links to add a Massachusetts Institute of Technology Affiliates course. In the Human Subjects training category, select the “Data or Specimens Only Research” course
> - Complete the course and save a copy of your completion report.  The completion report lists all modules completed, with dates and scores.
