### ISSUE TITLE
run concepts/echo_data.sql with sql error

### ISSUE THREAD

**Issue by gaoliming123** [MIT-LCP/mimic-code#787]
I install postgresql and import data successfully. But when I run the file in the directory of concepts will get the following error:

mimic=# \i D:/mimic-code/concepts/echo_data.sql
psql:D:/mimic-code/concepts/echo_data.sql:46: error:  syntax error near "`" or at line
36 FROM `physionet-data.mimiciii_notes.noteevents` ne 

and I run the  postgres_checks.sql is no problem, what's wrong with me ?

**Comment by tompollard** [comment]
> what's wrong with me ?

Nothing wrong with you, it's the code :) The error is showing some BigQuery syntax (\`physionet-data.mimiciii_notes.noteevents\`), so it looks like you are trying to run a BigQuery script in Postgres (the syntax differs slightly between the two database systems).

**Comment by bugaosu** [comment]
so how to change the syntax?--TAT
