### ISSUE TITLE
Multiple cgids for electrolyte inputevents 

### ISSUE THREAD

**Issue by MousaGhannam** [MIT-LCP/mimic-code#788]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, so I was looking through inputevents_cv table at the electrolytes, and I noticed that sometimes the same event would have 2-3 different caregivers, resulting in 2-3 different rows with each unique cgid respectively. I found this out by finding all the distinct rows, after querying for Potassium repletions. 

I am doing an analysis that requires me to know which provider performed a given repletion event.

Do you know why there are there multiple caregivers for the same event? On a similar note, the mimic website says the cgid corresponds to the person that validated a given measurement. Do you know how I might discern which provider _repleted_ a given medication, or who made the call for that electrolyte to be repleted? 

Thank you, I appreciate any advice and insight you can spare on the matter!

**Comment by alistairewj** [comment]
Interesting. Can you give an example query demonstrating multiple rows due to multiple `cgid` and only one repletion event?

**Comment by alistairewj** [comment]
Please feel free to re-open if you come up with an example query.
