### ISSUE TITLE
Generating patient logs

### ISSUE THREAD

**Issue by joel1391** [MIT-LCP/mimic-code#79]
Is there a code that can be used to generate logs in MIMIC-III like the logs that were made for MIMC-II? I believe there is a file already made for each MIMIC-II patient but I don't know which version of MIMIC-II it was used in. Here are a couple of links to the logs I'm referring to: 

**sample annotated log** - https://physionet.org/physiobank/database/mimic2cdb-ps/sample/
**actual patient log (from public subset)** - https://physionet.org/physiobank/database/mimic2cdb-ps/s00439/

**Comment by alistairewj** [comment]
The code must be kicking around somewhere, though I haven't seen it. If you
don't mind my asking, what's the use case for the data in this form? Is it
more convenient for some software packages?

**Comment by joel1391** [comment]
We've identified an event specific to each patient, and we're looking to explore parameters that are available before and after that event, and the times at which the measurements were made. It's currently more for exploratory purposes. 

As a beginner I liked the logs because they displayed a clear timeline of events for each patient and thought that maybe I could eventually mine them for text/data of interest.

**Comment by alistairewj** [comment]
If you ever ended up building something to do this a PR is welcome - I never found the code to do it.
