### ISSUE TITLE
follow up time calculation

### ISSUE THREAD

**Issue by liuenqian** [MIT-LCP/mimic-code#792]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
if I want to calculate survival days when the endpoints were 30-day and 90-day all-cause mortality from the date of ICU admission. 
the death time how to choose for example admisson table has deathtime, patients table has dod, dod_hospital, and dod_ssn.

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Something like

```
SELECT DATE_DIFF(CAST(DEATHTIME AS DATE), CAST(ADMITTIME AS DATE), DAY) AS time_to_death FROM `physionet-data.mimiciii_clinical.admissions`
```

would work! For the difference between the DOD columns check the patients documentation: https://mimic.physionet.org/mimictables/patients/
Usually you want to use `DOD`.
