### ISSUE TITLE
Finding out when patient had CT with contrast

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#795]
Hello,
I'm trying to find out what is the best way to sample if **and when** a patient had a CT (or other) **with contrast**.
My last resort is parsing the noteevent.

Can I maybe get this from the CPT/ICD-9 procedure?
Maybe somewhere else?

🙏🏾

**Comment by alistairewj** [comment]
Hmm honestly the most reliable method might be parsing the note. But they are very consistently organized - check out the [echo data query](https://github.com/MIT-LCP/mimic-code/blob/ce51c15fbdd0f46e9d9dec7f61c89731ee7368cb/concepts/echo_data.sql) for an example of a regex on the echo reports. It ends up being pretty simple most of the time:

https://github.com/MIT-LCP/mimic-code/blob/ce51c15fbdd0f46e9d9dec7f61c89731ee7368cb/concepts/echo_data.sql#L40

You could probably adapt something like that for the radiology reports. Also check out the MIMIC-CXR repo as I wrote some code that parses the note into sections, and you might be able to use that: https://github.com/MIT-LCP/mimic-cxr/tree/master/txt

The radiology reports almost always have an exam type in the header which is fairly well coded and mentions contrast if it's used.

**Comment by arielhasidim** [comment]
Pleasure as always.
Thank you very much!
