### ISSUE TITLE
icu stays with RN events and no corresponding notes from the same RNs

### ISSUE THREAD

**Issue by sbrossette** [MIT-LCP/mimic-code#797]
As a physician, I find it odd that so many ICU stays have input, output, procedure and vital signs events by RNs that leave no note.  For a number of stays, there are no event RNs that leave nursing notes... none.  This does not seem clinically plausible.  What's going on? Below is some code to illustrate the issue.  If this is the case, for the stays where the cgid are discrepant, are the event cgid or the note cgid more reliable?  --Thanks

SELECT e.icustay_id
	,COUNT(distinct e.cgid) n_eventRN
	,count(distinct n.cgid) n_eventRN_withNotes
	,COUNT(distinct e.row_id) n_events
FROM 
(SELECT row_id, icustay_id, itemid, starttime, cgid 
FROM mimiciii.inputevents_mv -- input, output, vitals (heart rate), and procedure events
	UNION SELECT row_id, icustay_id, itemid, charttime as starttime, cgid from mimiciii.outputevents
	UNION SELECT row_id, icustay_id, itemid, starttime, cgid from mimiciii.procedureevents_mv
	UNION SELECT row_id, icustay_id, itemid, charttime as starttime, cgid from mimiciii.chartevents_12 where itemid = 220045 -- heart rate
) e
JOIN mimiciii.icustays s on s.icustay_id = e.icustay_id
JOIN -- caregivers
	mimiciii.caregivers cg on cg.cgid = e.cgid
LEFT JOIN -- notes; look for notes from event cgid at any time during the stay
	mimiciii.noteevents n on n.hadm_id = s.hadm_id and cg.cgid = n.cgid and n.charttime between s.intime and s.outtime
WHERE cg.description = 'RN' and s.first_careunit = 'MICU' and s.dbsource = 'metavision'
GROUP BY e.icustay_id
ORDER BY n_eventRN_withNotes, n_eventRN desc

**Comment by alistairewj** [comment]
Yep so unfortunately there is a gap in the collection of nursing/physician notes for patients. It only impacts Metavision patients and impacts patients randomly. Studies which absolutely require the notes filter to the subset of patients with at least 1 note to avoid this issue.

**Comment by sbrossette** [comment]
Thanks Alistair.  Appreciate that quick response.

Steve

**Comment by alistairewj** [comment]
No worries!

**Comment by sbrossette** [comment]
Does mimic-iv have the same issue with metavision notes?
