### ISSUE TITLE
Error in HOSPITAL_EXPIRE_FLAG column linking to DOD_HOSP in PATIENTS table

### ISSUE THREAD

**Issue by vjm261** [MIT-LCP/mimic-code#8]
Loading the raw PATIENTS_DATA_TABLE.csv into RStudio, sorting by DOD_HOSP and filtering by HOSPITAL_EXPIRE_FLAG == 'N' finds many, many cases (~4160) where the DOD_HOSP is specified but wrongly linked to the FLAG field.

Examples shown below:
![image](https://cloud.githubusercontent.com/assets/14168103/10401117/d4969380-6e8a-11e5-9905-45b5ef8ebc29.png)

Bug-fix for the next build.

**Comment by alistairewj** [comment]
Indeed - good catch. This is due to setting the `HOSPITAL_EXPIRE_FLAG` using `DISCHARGE_LOCATION` rather than `DEATHTIME`. `DISCHARGE_LOCATION` usually specifies death, but for these 4160 patients it did not, even though they died before discharge. This will be fixed in the next release.

**Comment by alistairewj** [comment]
A new version, MIMIC-III v1.2, has been released. This bug is fixed in that version and I recommend you update your data if you haven't already. Thanks for the report!
