### ISSUE TITLE
regarding comorbidity: why not convert ICD9_CODE from a VARCHAR to a CHAR(5) in latest version?

### ISSUE THREAD

**Issue by AINIVERSHERRY** [MIT-LCP/mimic-code#800]
I remember that previous code includes following sql:

with
icd as
(
  select hadm_id, seq_num
    , cast(icd9_code as char(5)) as icd9_code
  from diagnoses_icd
)

But current code does not contain sql above. Do I need to add them when running "elixhauser-ahrq-v37.sql"?

thanks!

**Comment by alistairewj** [comment]
I rewrote a lot of the code to not rely on icd9_code being a CHAR. So it's
ok to omit it now. But it's always good to double check what I've done!

**Comment by AINIVERSHERRY** [comment]
> I rewrote a lot of the code to not rely on icd9_code being a CHAR. So it's ok to omit it now. But it's always good to double check what I've done!

Thanks for your reply! I test the number of hadm_id where valvular_disease equals  1 in SQL1 and SQL2, SQL1 convert icd9_code to CHAR(5) whereas SQL2 does not. Even though current version has add DRG information into SQL above, the test result still shows difference that comes from the change of data type. So I keep the 'convert' in my SQL now.

**Comment by alistairewj** [comment]
You're right, I rewrote the version proposed by Quan et al. but I did not rewrite the AHRQ version. Needs a fix!

**Comment by alistairewj** [comment]
OK! Easy fix in the end I think, some of the codes had spaces which needed to be removed. Can you compare the new version?

**Comment by AINIVERSHERRY** [comment]
> OK! Easy fix in the end I think, some of the codes had spaces which needed to be removed. Can you compare the new version?

Great! 

SQL1: convert ICD9_CODE from a VARCHAR to a CHAR(5)
SQL3: remove spaces in icd9_code

I test the number of hadm_id where valvular_disease equals 1 in SQL1 and SQL3 which both derive from "elixhauser-ahrq-v37". The test result matches now.

**Comment by alistairewj** [comment]
Thanks for the report!
