### ISSUE TITLE
Unable to unzip CHARTEVENTS.csv.gz

### ISSUE THREAD

**Issue by derek-y-lee** [MIT-LCP/mimic-code#801]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I noticed there was an issue earlier regarding difficulty copying CHARTEVENTS to postgres (https://github.com/MIT-LCP/mimic-code/issues/362). I am having a problem where I can't event unzip the CHARTEVENTS.csv file before I can successfully run the makefile. The error I get while unzipping is "Unable to expand "CHARTEVENTS.csv.gz" (Error 32 - Broken pipe.) 

Any suggestions for what to do besides partitioning from BigQuery into 28 separate csv files to store on my local machine? BigQuery can only partition 1 GB max per table and querying CHARTEVENTS is almost 28 GB.

Thanks in advance!

**Comment by alistairewj** [comment]
That issue is probably unrelated. Broken pipe could be a number of things, but a likely suspect is running out of hard drive space. Your unzip tool might use a temporary file to store chartevents, which could take up ~50 GB. You shouldn't have to unzip chartevents though: try the gzip or the 7zip build versions.

**Comment by derek-y-lee** [comment]
Thanks! I finally got it to work for the postgres build after having numerous other issues with CHARTEVENTS. My recommendation for anyone in the future is to not use the zip file but to download each individual file instead since the CHARTEVENTS.csv.gz in the zipfile was a bit problematic for me.
