### ISSUE TITLE
pivoted_bg.sql is not working

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-code#803]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

I was trying to run the query to creat pivoted_bg to get pivoted_sofa. However the query can not be executed because one table referred does not exist:
Line 206, 
from `physionet-data.mimiciii_derived` bg

**Comment by yugangjia** [comment]
I created a derived_bg and then the code works.

**Comment by chendazhang** [comment]
dear author, could  you  tell  me  how to create the  derived_bg table ,thank you very much！

**Comment by yugangjia** [comment]
Hi, what does bg mean here?
