### ISSUE TITLE
where to find the code which created mimic_derived.icustay_hours

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-code#804]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

This table is referenced in the pivoted_sofa.sql, but I can not find the code which created that table from code repository

**Comment by alistairewj** [comment]
Check the demographics folder!

**Comment by yugangjia** [comment]
Thanks.
I wrote my own one for mimiciv as well

select ihr.STAY_ID, hr , 
DATETIME_TRUNC(DATETIME_ADD(ihr.intime, interval hr+1 hour), hour) as endtime 
from (
select i.STAY_ID,i.los, (
select GENERATE_ARRAY(-24,DATETIME_DIFF(i.outtime,i.intime, hour),1)) as hra,i.intime 
from `physionet-data.mimic_icu.icustays` as i) as ihr, unnest(hra) as hr
order by ihr.STAY_ID
