### ISSUE TITLE
starttime greater than endtime in weight_durations

### ISSUE THREAD

**Issue by kqhv** [MIT-LCP/mimic-code#805]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Reference
https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/weight_durations.sql

### Questions
1. Are all records whose starttime > endtime in the weight_durations.sql a result of code error (and not data error) which should have been corrected as described below?
2. Is my fix (described below) correct or could there be any potential issues with this fix?

### Observation Summary:
- There are records in weight_durations whose starttime > endtime and they seem to be the result of using the "ICUSTAYS.outtime" to produce the endtime while the starttime comes from either "CHARTEVENTS.charttime" or "NOTEEVENTS..charttime".
- The hypothesis is that in these cases, a patient's weight was measured after he/she had moved out of that icu-stay (the associated outtime used for producing endtime).

### The Fix
- I tried replacing the "outtime" part in the code with "GREATEST(starttime, outtime)", which is Bigquery version of max(x1, x2) function, and the aforementioned issue disappeared. The replacement was done specifically at lines 124 and 208 in https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/weight_durations.sql
- But then, these weight measurements might not be associated with those icustay-ids anymore.

### Sample code
- Line 124: `DATETIME_ADD(GREATEST(starttime, outtime), INTERVAL '2' HOUR)`
- Line 208: `, coalesce(el.endtime, DATETIME_ADD(GREATEST(el.starttime, el.outtime), INTERVAL '2' HOUR)) as endtime`

**Comment by alistairewj** [comment]
Good catch - I'll add those fixes!

**Comment by kqhv** [comment]
Looks good, thanks!

There is this minor thing where I would take the condition from line 124 and place it in the nested query at line 104, but it's not a big problem for me anyway.
