### ISSUE TITLE
About dealing with time

### ISSUE THREAD

**Issue by Yuz998** [MIT-LCP/mimic-code#811]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I am using PostgreSQL 12.2, and I tried to run the conceptual sql files (such as oasis.sql, sapsii.sql, etc.), but for the time (such as DATETIME_ADD, DATETIMEDIFF, DATETIME_SUB, etc. functions) statements processing errors, the display is not Support this syntax. What is the version of PostgreSQL running these sql files? Or is there another syntax?

Hope for your help, thanks!

**Comment by alistairewj** [comment]
The queries are written in BigQuery. We have a script that defines postgres functions that you need to run before the queries: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/postgres-functions.sql
