### ISSUE TITLE
Can a mysql script directory be created under the concepts directory

### ISSUE THREAD

**Issue by wsaibaiyun** [MIT-LCP/mimic-code#813]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
We'd be happy to accept PRs for concept code in different SQL dialects!
