### ISSUE TITLE
Linking between databases (MIMIC 3 and MIMIC 4)

### ISSUE THREAD

**Issue by aliforgetti** [MIT-LCP/mimic-code#815]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Just wanted to know if the `subject_id`s and `hadm_id`s are consistent in both mimic iii and mimic iv. Is it possible to link between the two (through a crosswalk maybe)?
Also since mimic iii ends in 2012 and mimic iv starts in 2008 what is the possibility of overlap of subjects between these two?

**Comment by alistairewj** [comment]
The identifiers are different and the databases cannot be linked - however as you point out they do overlap and contain some of the same patients. As such I wouldn't recommend merging the databases as of now. We intend to release a new version of MIMIC-III to make it easier for researchers to combine the two. For now just get used to MIMIC-IV :)

**Comment by jingge326** [comment]
> 

Thank you! I wonder if the new version of MIMIC3 is available now? We are deperately look forward to extracting the overlap of MIMIC3 and MIMIC4. And then we will work on MIMIC3 & 4 as a whole.

**Comment by alistairewj** [comment]
This is pretty low priority for us ... it wouldn't be a huge lift, but what would likely happen is we would make a new project on PhysioNet with just the CareVue patients.
