### ISSUE TITLE
Time of Cardiac Arrest

### ISSUE THREAD

**Issue by Lauramoffat** [MIT-LCP/mimic-code#817]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including: I need help determine time of cardiac arrest.  I am using the ICD-9 code to find all cardiac arrest, but my project is attempting to predict cardiac arrest within four hours of the event based on our 6 candidate predictors.  My team is not able to determine time of first cardiac arrest.  Any suggestions would be very much appreciated.

* what you have tried- looked in GitHub and reviewed previously published studies using MIMIC-III and cardiac arrest prediction.
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
You could try to create a definition based on troponin, something like in the hospital for at least X hours, and then a troponin is measured which is above the threshold for MI.
