### ISSUE TITLE
Calculation of LOS 

### ISSUE THREAD

**Issue by riarungta** [MIT-LCP/mimic-code#818]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

How is the LOS (in table ICUSTAYS) calculated? Is the length of stay only counted till the time the call out is initiated (CREATETIME)? Or does it include the additional time the patient spends in the ICU (until the OUTCOMETIME when the callout outcome is discharged)? Thank you

**Comment by alistairewj** [comment]
It is calculated as the number of days between the `outtime` and `intime`. The callout table is not used in the calculation - it's closest to the actual time spent in the ICU.
