### ISSUE TITLE
what are ANCHOR_AGE and ANCHOR_YEAR and ANCHOR_YEAR_SHIGTED

### ISSUE THREAD

**Issue by parisaetemadinejad** [MIT-LCP/mimic-code#819]
I want to use the age of the patient for my project but I can't understand that :
1. how to calculate the age of patient because mimic iv says "_it is necessary to account for the number of years between ANCHOR_YEAR_SHIFTED and their hospital admission time"_
2- whare are them in the dataset? I can't find it 
can I use just anchor_age?
thank you

**Comment by alistairewj** [comment]
Please raise this at https://github.com/MIT-LCP/mimic-iv which is the repo for MIMIC-IV.
