### ISSUE TITLE
Failing to import some tables data to PostgreSQL

### ISSUE THREAD

**Issue by danro9685** [MIT-LCP/mimic-code#82]
Three tables fail to import to PostgreSQL. 

The table CHARTEVENTS gives the following error: 
<img width="889" alt="chartevents" src="https://cloud.githubusercontent.com/assets/5859159/13327431/1ac7b682-dbea-11e5-8a7e-118e2e2056bb.png">

The table D_ICD_DIAGNOSES gives the following error: 
<img width="771" alt="d_icd_diagnoses" src="https://cloud.githubusercontent.com/assets/5859159/13327440/252566f6-dbea-11e5-8033-c99c411641ca.png">

The archive where the MICROBIOLOGYEVENTS table is saved seems to be corrupted and it fails to unzip.

**Comment by tompollard** [comment]
> The archive where the MICROBIOLOGYEVENTS table is saved seems to be corrupted and it fails to unzip.

What method are you using to decompress the file?

**Comment by danro9685** [comment]
Hi, 

I had a problem with the way I unzipped it, but now I fixed this and it is not an issue anymore. 
I still have troubles with the CHARTEVENTS and the D_ICD_DIAGNOSES tables. 

Thanks,
Daniele

**Comment by tompollard** [comment]
The D_ICD_DIAGNOSES error ("duplicate key") sounds like you're trying to copy data into a table that is already populated with data. Are you sure the table is empty?

**Comment by danro9685** [comment]
I repeated all the procedure to import the data and this time it worked on both tables. I guess it was just a problem in unzipping the files.
