### ISSUE TITLE
the topic of cardiac arrest

### ISSUE THREAD

**Issue by zhonglei12** [MIT-LCP/mimic-code#821]
We're interested in the topic of cardiac arrest. The aim of our study is to evaluate the associations between xxx and neurologic outcomes after cardiac arrest treated by hypothermic targeted temperature management.
Good neurological outcomes were defined as cerebral performance categories (CPC) scores of 1–2, while poor neurological outcomes were defined as CPC scores of 3–5.
1.	We wondered whether the MIMIC database has the cerebral performance
categories (CPC) scores, such as the Glasgow Pittsburgh Coma Scale. If not, is there any other score to investigate the neurologic outcomes in post-cardiac arrest patients. 2. We didn't know how to judge the indicator of hypothermic targeted temperature management. Thank you very much for your help.

**Comment by alistairewj** [comment]
I've never seen that score documented so I am not sure it exists but you can check `d_items` for variations of the name to confirm. For targeted temperature management I'd recommend finding a patient who has an Arctic Silver (the device they use) and just going through their individual record to see what type of concepts are documented during their treatment.
