### ISSUE TITLE
Prescription Table and ICU stay ID

### ISSUE THREAD

**Issue by vwan1022** [MIT-LCP/mimic-code#823]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

Hello,

I was wondering what the meaning is behind certain lines in the prescription dataset not having an associated ICU stay ID. Were these medications prescribed to be taken outpatient or were some of the medications simply not tagged with an ICU stay ID in the dataset? There are many patients with multiple ICU stays and I am wondering if I can trust the ICU stay ID tags without having to cross reference based on date of admission/prescription.

**Comment by alistairewj** [comment]
These medications will have been prescribed within the hospital but outside the ICU. All the rows in prescriptions should have an `hadm_id`. They will only have `icustay_id` if they overlap with an ICU stay (plus 12 hours on either side, if I remember correctly).
