### ISSUE TITLE
Any changes to icustay_detail table from last year?

### ISSUE THREAD

**Issue by Ak784** [MIT-LCP/mimic-code#824]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello Everyone,

I remember seeing the `Admission_type` column in the `ICUSTAY_DETAIL` table during Nov/Dec of last year 2019.

Q1) Has there been any update to the tables now in bigquery because I don't see the column `Admission_type` anymore. 

Because I have a query (part of a larger query) as below which was written last year. So, I have used the `Admission_type` column but now the query doesn't work due to missing column `Admission_type`. Curious to know whether I made a mistake in query or was tables updated? I ask because if it was updated, then I will have to verify all my queries, etc. I might have used an incorrect column too (but wanted to check once with you before I conclude that I used incorrect column)

`icu as (select icustay_id, hadm_id,subject_id, gender,ethnicity,admission_age as age,intime,outtime,los_icu,los_hospital,hospital_expire_flag as expire_flag from physionet-data.mimiciii_derived.icustay_detail where admission_type in ('EMERGENCY','URGENT'))`

Q2) Where can I find out what are the tables (derived/clinical) tables which are updated in mimic?

Thanks
Ak

**Comment by yinet** [comment]
![Uploading snipaste20201117_223309.png…]()

I think you are right, the table 'icustay_detail' was modified on 2020-6-10

**Comment by Ak784** [comment]
Thanks @yinet  for your help

**Comment by alistairewj** [comment]
We try to update the BigQuery tables with every GitHub release of this repo. You might want to look at an earlier release for older code. In this case `admission_type` was pulled directly from the *admissions* table, so you can certainly grab it from there.
