### ISSUE TITLE
Missing creatinine measurements 

### ISSUE THREAD

**Issue by SAlkh90** [MIT-LCP/mimic-code#825]
Hi 

I have noticed that more than 3000 unique patients in MIMIC III do not have any creatinine measurements within their ICU stay based on “intime” and “outtime” in “icustays” table.

I am extracting the creatinine measurement from table “labevents” with itemid = 50912 based on the script in https://github.com/MIT-LCP/mimic-code/blob/master/concepts/organfailure/kdigo_creatinine.sql .

If this assertion is incorrect, where could the mistake lie?
If the assertion is correct, what reasons lie behind so many patients not having creatinine measurements

Thank you

**Comment by alistairewj** [comment]
Not all patients receive all measurements. It's as simple as that!
