### ISSUE TITLE
Course requirement "Data or Specimens Only Research" does not exist.

### ISSUE THREAD

**Issue by AndreasMadsen** [MIT-LCP/mimic-code#827]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

The instructions say to apply for the "Data or Specimens Only Research" course. However, this course does not appear to exist on https://www.citiprogram.org/index.cfm?pageID=154&icat=0&ac=0.

![All courses in the category "human subject research"](https://user-images.githubusercontent.com/505333/99821812-c48fc080-2b52-11eb-932d-8cb9fd7bc278.png)

**Comment by tompollard** [comment]
The course appears in the list for me when following the instructions at: https://mimic.physionet.org/gettingstarted/access/

Please could you confirm that you are following this step?

> First register on the CITI program website, selecting “Massachusetts Institute of Technology Affiliates” as your affiliation (not “independent learner”):

**Comment by AndreasMadsen** [comment]
> First register on the CITI program website, selecting “Massachusetts Institute of Technology Affiliates” as your affiliation (not “independent learner”):

I did read that, but I do not have a Massachusetts Institute of Technology email address as requested later.

**Comment by tompollard** [comment]
There is no requirement for an MIT email address, so I'm not sure what is happening here. Perhaps you are missing the "Affiliates" when selecting the affiliation.

**Comment by AndreasMadsen** [comment]
@tompollard Thanks for the help. I managed to solve it. There is a step where it requests an MIT email address. But you can just put in a gmail.com address, even though it explicitly asks you not to use a gmail address.

**Comment by tompollard** [comment]
Glad you sorted it out, thanks for the update. We'll look into this and will update the instructions if necessary. I don't see the place where it requests an MIT address:

<img width="653" alt="Screen Shot 2020-11-20 at 13 41 05" src="https://user-images.githubusercontent.com/822601/99837773-1d9d2b80-2b36-11eb-9cdb-546bd940367a.png">

Is this the page that you are referring to or is the address requested elsewhere?
