### ISSUE TITLE
Corticosteroids

### ISSUE THREAD

**Issue by dplecko** [MIT-LCP/mimic-code#829]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi,

I was looking at treatment with corticosteroids in the dataset. I use the following strings for matching with different items

```
c(
  "methasone", "predniso", "triamicinolone", "celestone", "orapred", "prelone",
  "dexa", "cortisone", "cortef", "celestone", "ethamethasoneb", "medrol",
  "hydrocortisone", "cortef", "intensol", "cort", "prelone", "kenalog", 
  "aristospan", "dexpak", "florinef"
)
```

Item IDs that appear in `chartevents` are usually in very low counts, so I removed those from the results. Here is the final result:
```
> corts
    item                 name          table count
12 44585   Methylprednisolone inputevents_cv   118
18 42655   METHYLPREDNISOLONE inputevents_cv    42
20 44089     Methylprednisone inputevents_cv    30
21 45023   methylprednisolone inputevents_cv    25
24 42060 METHYLPREDNISONE GTT inputevents_cv    14
25 42689     METHYLPREDNISONE inputevents_cv    14
40 30069           Solumedrol inputevents_cv  2619
47 42240      SOLUMEDROL DRIP inputevents_cv    42
49 42526       SOLUMEDROL GTT inputevents_cv    41
52 43700 Solumedrol mg/kg/min inputevents_cv    27
55 44096 solumedrol 10575/500 inputevents_cv    22
57 42514     SOLUMEDROL DRIP. inputevents_cv    20
61 42126       Solumedrol gtt inputevents_cv    16
62 44366          SOLU-MEDROL inputevents_cv    16
63 42563  SOLUMEDROL MG/KG/HR inputevents_cv    16
64 42422 SOLUMEDROL DRIPMG/HR inputevents_cv    15
65 42163      solumedrol drip inputevents_cv    15
> sum(corts$count)
[1] 3092
```

My questions are:

1) Am I missing some very important item names (I get no matches for `metavision` at all which is definitely surprising)
2) Is it possible that corticosteroids are not recorded in the data?

Thanks,
Drago

**Comment by alistairewj** [comment]
The inputs allowed in MetaVision are from a fixed list. Unfortunately, methylprednisone is not on this list, and therefore they don't document it. You'll have to use the prescriptions table in order to track administrations.
