### ISSUE TITLE
Reason for ICU stay and etiology of a disease - Mimic III and Mimic IV

### ISSUE THREAD

**Issue by Ak784** [MIT-LCP/mimic-code#831]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello mimic team,

I am participating in SG datathon 2020. I would like to know whether MIMIC III or IV has reason for ICU stay admission?

Is there any column in mimic tables that can help us find out the below

a) Reason for ICU admission
b) Etiology of a disease
c) Smoking status
Can help please

**Comment by alistairewj** [comment]
Unfortunately there are not structured entries describing the reason for ICU admission or disease phenotype. They are described in the notes however.

Smoking status is often charted in the ICU information system, so I'd look in `chartevents` and `d_items`.
