### ISSUE TITLE
MIMIC-CXR dataset trained on Google colab!

### ISSUE THREAD

**Issue by nnajeh** [MIT-LCP/mimic-code#836]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
to train my own developed model on MIMIC-CXR, should i use Cloud AI Platform Notebook or is it possible with google colab?

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
Yes you can use all Google services with the dataset. I highly recommend using the Cloud AI Platform Notebook as it won't incur data egress if you use it within the same region where the data are located.

**Comment by nnajeh** [comment]
I don't have a cloud AI platform account, but i'm asking if i can build my own model with MIMIC-CXR based on just google collab?

**Comment by alistairewj** [comment]
It's possible but each time you run Google Colab you'll have to redownload the dataset so it can be a bit slow. There are also extra steps you have to take to save the model during training as Colab will kick you out after 8 hours or so.
