### ISSUE TITLE
Caregiver assignment

### ISSUE THREAD

**Issue by faaizT** [MIT-LCP/mimic-code#837]
### Description

I have the following question about the dataset:
Are caregivers assigned randomly to patients? 
I am doing an analysis to measure each Caregiver's performance in terms of the outcome for patients, and therefore this question is central to my analysis.

**Comment by lceli** [comment]
There is no one caregiver assigned to a patient in the ICU. A primary care database or a surgical database is what you need. 
    On Saturday, December 12, 2020, 12:53:54 PM EST, Faaiz Taufiq <notifications@github.com> wrote:  
 
 


Description

I have the following question about the dataset:
Are caregivers assigned randomly to patients?
I am doing an analysis to measure each Caregiver's performance in terms of the outcome for patients, and therefore this question is central to my analysis.

**Comment by faaizT** [comment]
I understand a patient may be assigned to different caregivers at different time points. But my question is, is this assignment at each time point random?

**Comment by alistairewj** [comment]
No what @lceli is saying is that multiple caregivers provide for a patient simultaneously. The `cgid` in the database is the caregiver who documents data. It's not a valid assumption to make that they are the only provider for the patient. The assignment is not random as caregivers work in shifts but there are entire groups of caregivers (consulting physicians, attending physicians, residents) who never appear as a `cgid` as they do not document in CareVue/MetaVision.

**Comment by faaizT** [comment]
Okay that makes sense. Thank you
