### ISSUE TITLE
Access to an older version of MIMIC-III

### ISSUE THREAD

**Issue by dalgu90** [MIT-LCP/mimic-code#839]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Dear maintainers,

I'm working on clinical NLP and many of the works in this area also rely on NOTEEVENTS of the MIMIC-III database. Thanks for the dataset.
I'm currently working on reproducing a work ([link](https://github.com/clips/clinspell/issues/5)) and I confirmed that the authors used an older version of MIMIC-III (v1.3) in their work.
However, it seems that only the latest version (v1.4) is available on both the current website and the archived one.
Is there any way to have access to `NOTEEVENTS.csv` of MIMIC-III v1.3?

Thanks,

**Comment by alistairewj** [comment]
We don't make older versions available but the changelog is available here: https://mimic.physionet.org/about/releasenotes/

It depends on what exactly they did - the only two fixes for noteevents were (1) the description column was modified for addendums and (2) the date within the scrubbed date entities was updated. It's very likely there's no impact on the work you'd like to reproduce.

**Comment by dalgu90** [comment]
Hello Alistair. Thanks for the quick response.
I think that does depend, actually. They didn't process the file as a table, but just as a text file. I will ask for the data from the authors and try to make it work for the latest version for other researchers.
