### ISSUE TITLE
loading data into SQL Server

### ISSUE THREAD

**Issue by johnpaulcook** [MIT-LCP/mimic-code#84]
I'd like to load the MIMIC III data into SQL Server (which is free to students through [Dreamspark](https://www.dreamspark.com/Product/Product.aspx?productid=83)) because that's what I know best. The problem with the csv files is that some fields contain commas as part of the data. It would be far easier to work with a unique delimiter instead of trying to implement workarounds for comma data inside csv files. I've searched all of the MIMIC III csv files and the following characters are never used:

Ⅎ ❶ ① ↘

If the data could be extracted into flat files using a delimiter that never appears in the data, it would make it trivial to load the data into SQL Server. Using an alternate, well chosen delimiter character is a far more robust solution to the problem than continually implementing workarounds for commas in csv files.

**Comment by tompollard** [comment]
The current CSVs conform to the [RFC 4180 specification](https://tools.ietf.org/html/rfc4180), which is as close as CSVs get to a formal standard.

![figure1](https://cloud.githubusercontent.com/assets/822601/13555699/747c89a2-e395-11e5-8878-d1e644e7035b.jpg)

> Using an alternate, well chosen delimiter character is a far more robust solution to the problem than continually implementing workarounds for commas in csv files. 

Commas within strings are handled by the RC4180, so this seems like a reasonable solution. Does SQL server not support the RFC 4180 spec?

**Comment by elfeto** [comment]
Hi, 

I just tested it on Windows 10 using SQL Server 2014 Import and Export Wizard and it worked perfectly.

<img width="888" alt="screen shot 2016-05-05 at 5 59 55 pm" src="https://cloud.githubusercontent.com/assets/3857286/15058642/64e046ac-12eb-11e6-9ded-9a8ee9f2d37e.png">
<img width="891" alt="screen shot 2016-05-05 at 5 59 44 pm" src="https://cloud.githubusercontent.com/assets/3857286/15058643/64e10b28-12eb-11e6-9fc3-cf58fa6d9128.png">

**Comment by tompollard** [comment]
Thanks for your time in looking into this @elfeto. I'll close this issue for now then. @johnpaulcook please reopen the issue if you are still unable to build MIMIC in SQL Server using the CSVs. 

It would be great if anyone working in SQL Server could contribute build scripts back to the MIMIC community at: https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic
