### ISSUE TITLE
Problem to load：

### ISSUE THREAD

**Issue by notreashes** [MIT-LCP/mimic-code#840]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

the info：
mimic=# \i D:/mimic-code-1.4.2/buildmimic/postgres/postgres_load_data.sql
psql:D:/mimic-code-1.4.2/buildmimic/postgres/postgres_load_data.sql:31: 错误:  无效的整数类型输入语法: "2184-01-06 11:51:00"
背景:  COPY admissions, line 2, column hadm_id: "2184-01-06 11:51:00"
mimic=#
the chinese means：Invalid integer type input syntax

PG：9.6 and 10.15 have been tried.

How can I get through it？
thanks a lot

**Comment by notreashes** [comment]
It seems that PG couldnot tell the difference between “Time” and “number”.

**Comment by notreashes** [comment]
well，its the version，between mimic and code.
but then comes to：

mimic=# \set ON_ERROR_STOP 1
mimic=# \set mimic_data_dir 'D:/mimic'
mimic=# \i D:/mimic-iv-1.1.0/buildmimic/postgres/load.sql
COPY 524520
COPY 383220
COPY 2192963
psql:D:/mimic-iv-1.1.0/buildmimic/postgres/load.sql:19: 错误:  编码"GBK"的字符0x0x93 0x20在编码"UTF8"没有相对应值
背景:  COPY d_hcpcs, line 88856

**Comment by notreashes** [comment]
found：
\encoding UTF8

**Comment by foneone** [comment]
I also met this problem.The official  offers three ways to load data.You can change a way to load data.

**Comment by alistairewj** [comment]
All of the data in MIMIC comes as UTF-8. Maybe by default, in your locale, the database is not UTF-8? If so you'd have to do drop the database and do something like: `CREATE DATABASE mimic ENCODING 'UTF-8';`

**Comment by notreashes** [comment]
thanks a lot
I am going to try again @alistairewj

**Comment by notreashes** [comment]
BTW
Is that the "mimic-iv-master" wrote for PG9.x or 10.x?  or both?

**Comment by alistairewj** [comment]
I've tested it on 9.4 onward if you use the original create tables script. There is create tables script version for pg10 and onward. I'd recommend using at least pg10 as it supports parallel querying.

Good luck!

**Comment by wang4321** [comment]
I met this problem too. how to solve it?

**Comment by dewgong2** [comment]
Hi I came into the problem. 

at line: mimic=# \i postgres_load_data.sql

postgres=# CREATE DATABASE mimic OWNER postgres;
CREATE DATABASE
postgres=# \c mimic;
You are now connected to database "mimic" as user "postgres".
mimic=# CREATE SCHEMA mimiciii;
CREATE SCHEMA
mimic=# set search_path to mimiciii;
SET
mimic=# \i postgres_create_tables.sql
postgres_create_tables.sql: No such file or directory
mimic=# \set ON_ERROR_STOP 1
mimic=# \set mimic_data_dir 'D:/mimic/v1_4'
mimic=# \i postgres_load_data.sql
postgres_load_data.sql: No such file or directory


THanks~!

**Comment by alistairewj** [comment]
@dewgong2 that is a separate issue. You simply do not have the load data file in the folder you are running `psql` in.

**Comment by alistairewj** [comment]
@notreashes did you solve your original issue?

**Comment by notreashes** [comment]
> @notreashes did you solve your original issue? I just realized that perhaps you are mixing the MIMIC-III and MIMIC-IV build scripts? They are not interchangeable.

Yes.You are right.That was the point.
