### ISSUE TITLE
In mimic-iii,why some patients' icd9_code on the diagnoses_icd table is not find on the d_icd_diagnoses table?

### ISSUE THREAD

**Issue by foneone** [MIT-LCP/mimic-code#841]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
I used the following SQL query,
`select *
FROM diagnoses_icd as dia LEFT JOIN d_icd_diagnoses as dd on dia.icd9_code=dd.icd9_code
where dd.row_id is null `
Then I found some icd9_code on the diagnoses_icd table are not on the  d_icd_diagnoses.Look like the query results below.

row_id | subject_id | hadm_id | seq_num | icd9_code | row_id(1) | icd9_code(1) | short_title | long_title
1524 | 117 | 140784 | 2 | 7895 |   |   |   |  
1529 | 117 | 140784 | 7 | 2765 |   |   |   |  
1537 | 117 | 164853 | 6 | 5118 |   |   |   |  
1635 | 126 | 176860 | 4 | 7793 |   |   |   |  

From my perspective,I think the d_icd_diagnoses is like a dictionary,and all the icd9_code are include.But the results is not that.Why?How can I handle the icd9_code not on the d_icd_diagnoses?

**Comment by alistairewj** [comment]
From what I remember, the main reason this happened was the use of obsolete ICD-9 codes. Our dictionary for MIMIC-III only contained the latest ICD-9 codes. For MIMIC-IV, the *d_icd_diagnoses* table contains the obsolete codes as well, so you won't run into this issue.

We won't be updating MIMIC-III to fix this issue, though. It's hopefully small enough that you can manage it manually within your study (or upgrade to MIMIC-IV).
