### ISSUE TITLE
Interpreting vasopressors doses (amount vs rate)

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#844]
Hello,
I'm trying to understand the relationship between `vaso_rate` and `vaso_amout` -

This example is extracted from `dobutamine_dose`(relevant to all vasopressors), I added the four columns on the right . I would expect that the duration of administration multiplied by the rate would give me the amount. following #642, I tried multiplying rate with hours or minutes - nothing equal to the amount.

**What Am I missing?**

To make my issue clearer, I want to sum amounts in a given time interval, and I'm not sure which column should I use - amount or rate.

| icustay_id | starttime           | endtime             | vaso_rate   | vaso_amount | dur_hours | dur_minutes | duration_times_rate_hours | duration_times_rate_minutes | 
|------------|---------------------|---------------------|-------------|-------------|-----------|-------------|---------------------------|-----------------------------| 
| 200030     | 2150-11-13T19:30:00 | 2150-11-13T20:00:00 | 8           | 0           | 0.5       | 30          | 4                         | 240                         | 
| 200030     | 2150-11-13T20:00:00 | 2150-11-14T18:30:00 | 5           | 777.0240402 | 22.5      | 1350        | 112.5                     | 6750                        | 
| 200030     | 2150-11-14T19:00:00 | 2150-11-14T22:00:00 | 5           | 85.20000458 | 3         | 180         | 15                        | 900                         | 
| 200030     | 2150-11-14T22:00:00 | 2150-11-15T08:00:00 | 2.5         | 187.4400101 | 10        | 600         | 25                        | 1500                        | 
| 200095     | 2113-10-31T00:00:00 | 2113-10-31T03:21:00 | 20.06098548 | 250.0000011 | 3.35      | 201         | 67.20430137               | 4032.258082                 |

**Comment by Lauramoffat** [comment]
Hello,
Rate does not tell you about the amount given.  This will take an extra calculation.  You will need to know the following:

  1.  Medication form (dopamine comes in 80mg/100mL, 160mg/mL and 320mg/mL)
  2.  Ordered dose: Low dose: 0.5-5 mcg/kg/min, Intermediate dose: 5-15 mcg/kg/min, High dose: 20-50 mcg/kg/min
  3.  The patient’s weight.

Typically the infusion is increased by 1-4 mcg/kg/min every 15 min until optimum response is achieved.

This is an example of a calculation from https://www.upstate.edu/hr/document/med_calculations.pdf where the nurse has the order, med strength, pt weight and has to determine the rate.

C. When the order is written as unit of mcg/kg/min.
Example: Dopamine order: 5 mcg/kg/min. Bag is labeled:. Dopamine 400 mg in 250ml
NS. Pt weight= 63 kg.
Dose ordered x weight (if weight based) x volume x time
Have (dose of drug you have; must match units in dose ordered)
** Remember that pumps deliver ml/hr, so drips that deliver per minute need to have
time conversion factored in (60 min/1 hr); those drips that are delivered per hour do not
need this time conversion

1. Desired (dose ordered) = 5 mcg/kg/min x (pt weight) 63 kg
2. Have = 400 mg Dopamine; must convert to mcg by multiplying by 1000
3. Volume = 250 ml (volume in IV bag)
4. Also include time conversion of 60 min/hr

5 mcg/kg/min x 63 kg x 250 ml x 60 min/hr = 4725000
400,000 mcg (400 mg x 1000 mcg/1 mg) 400,000

Answer: 11.8 ml/hr----this is what the pump must be set at (-round up to 12ml/hr)
Order: Dopamine 20 mcg/Kg/minute. The bag is labeled Dopamine 100 mg/50 ml.
The patient weighs 88 lbs. How fast will the IV run to give the dose?
1. Must convert pounds to kg 88 ÷ 2.2 = 40kg
Dose ordered x weight (if weight based) x volume x time
Have (dose of drug you have; must match units in dose ordered)
20 mcg/kg/min x40 kg x50 ml x 60 min = 2400000 = 24 ml /hr
100,000 mcg/ml 100,000


Hope this helps,
Laura



Laura M Moffat, MSN, MSK, APRN, AGCNS-BC, CMSRN
Clinical Assistant Professor, DNP Candidate
School of Nursing

[cid:image001.png@01D6DF4D.99956930]

**Comment by arielhasidim** [comment]
I really appreciate your detailed explanation, thank you.

I understand from #642 that rates are in mcg/kg/min except vasopressin which is in units/hr, what units are used for the amount?

**Comment by Lauramoffat** [comment]
Vasopressin IV solution comes as 20 units/mL (1 mL and 10 mL),  The adult IV infusion concentration is typically 50 units in 500 mL (concentration 0.1 units/ml) or 100 units in 100 mL (concentration 1 unit/ml) in D5W or Normal Saline (NS).  However the route and dosage depends on the intended use:
abdominal distention 5 units intramuscular injection (note, not IV)
diabetes insipidus 5-10 units intramuscular injection (note this is not an IV)
GI hemorrhage 0.2-0.4 units/min IV may increase to 0.8 unit/min
Shock: 0.01-0.04 units/min IV
IV preparation is typically dilute to 0.1-1 unit/mL with NS or D5W.

You may find this website helpful: https://www.drugs.com/dosage/vasopressin.html
Laura

**Comment by Lauramoffat** [comment]
[cid:image002.jpg@01D6DF6B.58CC7F60]


Vasopressin is supplied in this manner - Laura

**Comment by lceli** [comment]
Vasopressin is typically only used for shock. (Octreotide is the equivalent that we use for variceal bleeding.) There are only 3 doses of vasopressin: 1.2 units/hr, 1.8 units/hr and 2.4 units/hr. It is not weight-based. We typically shut it off when blood pressure is improved; it is not weaned compared to norepinephrine or phenylephrine.Leo
    On Thursday, December 31, 2020, 11:49:14 AM EST, Laura Moffat <notifications@github.com> wrote:  
 
 

Vasopressin IV solution comes as 20 units/mL (1 mL and 10 mL), The adult IV infusion concentration is typically 50 units in 500 mL (concentration 0.1 units/ml) or 100 units in 100 mL (concentration 1 unit/ml) in D5W or Normal Saline (NS). However the route and dosage depends on the intended use:
abdominal distention 5 units intramuscular injection (note, not IV)
diabetes insipidus 5-10 units intramuscular injection (note this is not an IV)
GI hemorrhage 0.2-0.4 units/min IV may increase to 0.8 unit/min
Shock: 0.01-0.04 units/min IV
IV preparation is typically dilute to 0.1-1 unit/mL with NS or D5W.

You may find this website helpful: https://www.drugs.com/dosage/vasopressin.html
Laura

**Comment by arielhasidim** [comment]
> I really appreciate your detailed explanation, thank you.
> 
> I understand from #642 that rates are in mcg/kg/min except vasopressin which is in units/hr, **what units are used for the amount?**

@alistairewj 
Can you please clarify in what units is the amount column in `vasopressors doses` tables?
(please forgive my for tagging)

**Comment by alistairewj** [comment]
No worries - I can tell you that the units for vasopressin are... "units"!

More specifically the initial research on vasopressin involved using a pituitary hormone from oxen which they set as the reference standard. So 1 unit of vasopressin is equivalent to a fixed amount of that hormone. From my memory this also happened with heparin and whichever animal they were using for that research, so heparin doses are also measured in "units", even though it's a different reference. In the end it's a historical standard but most numeric ranges in medicine are pretty arbitrary anyway so everyone has gotten used to it.

**Comment by arielhasidim** [comment]
> No worries - I can tell you that the units for vasopressin are... "units"!
> 
> More specifically the initial research on vasopressin involved using a pituitary hormone from oxen which they set as the reference standard. So 1 unit of vasopressin is equivalent to a fixed amount of that hormone. From my memory this also happened with heparin and whichever animal they were using for that research, so heparin doses are also measured in "units", even though it's a different reference. In the end it's a historical standard but most numeric ranges in medicine are pretty arbitrary anyway so everyone has gotten used to it.

That is very cool to know, thank you!
About the other vasopressors (epinephrine, nor, dobutamine etc) I belive that the amount in mcg?

**Comment by alistairewj** [comment]
They are usually in mcg/kg/hour or mcg. I think dopamine is different (ml/hour?) but it's been a while!

**Comment by lceli** [comment]
Norepinephrine, phenylephrine, dobutamine and dopamine are in mcg/kg/min.
 
 
  On Mon, Jan 4, 2021 at 11:00 AM, Alistair Johnson<notifications@github.com> wrote:   


They are usually in mcg/kg/hour or mcg. I think dopamine is different (ml/hour?) but it's been a while!

**Comment by arielhasidim** [comment]
> Norepinephrine, phenylephrine, dobutamine and dopamine are in mcg/kg/min. On Mon, Jan 4, 2021 at 11:00 AM, Alistair Johnson<notifications@github.com> wrote: They are usually in mcg/kg/hour or mcg. I think dopamine is different (ml/hour?) but it's been a while! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry for insisting-
The `** vaso_rate**` is in mcg/kg/hour, but in the `vaso_amount` there is a total sum of the drug (see the table at the first post), so it's probably an absolute value and not per kg and min right?

**Comment by alistairewj** [comment]
> Sorry for insisting-
> The ** vaso_rate** is in mcg/kg/hour, but in the vaso_amount there is a total sum of the drug (see the table at the first post), so it's probably an absolute value and not per kg and min right?

Yes, correct.
