### ISSUE TITLE
Can MIMIC-III be used for de-identification tasks? 

### ISSUE THREAD

**Issue by guilhermenoronha** [MIT-LCP/mimic-code#845]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello. I'm not sure if I can pose this question here, so my apologies if not.

I'm looking for a clinical corpus for de-identification task. MIMIC-III is one of few available for free. So I'd like to know if I can use it to address this problem.

I looked into the documentation but couldn't find the answer.  The kind of corpus I'm looking for has: (1) pseudonymized unstructured data (or free text structured data) with PHI fields. Is there some kind of data in MIMIC-III?

Thanks in advance. With best regards, 

Guilherme.

**Comment by alistairewj** [comment]
MIMIC-III is de-identified - if you are using the strict definition of pseudonymized then yes it is pseudonymized. You could use it for de-identification research but you would have to re-insert synthetic PHI where we have removed it. Just note that attempting to identify any patient in MIMIC violates the DUA.
