### ISSUE TITLE
how to dertermine the sql files to get sepsis dataset

### ISSUE THREAD

**Issue by wangzihuixmu** [MIT-LCP/mimic-code#849]
Hi, I want to do some research of Early Recognition of Sepsis, and I have get MIMIC-3 dataset and install  postgresql, but I don’t know how to determine the order of sql file to get the sepsis dataset.
Thank you very much!!!!!

​

**Comment by alistairewj** [comment]
There is no official sepsis dataset, but you may want to investigate the BigQuery derived views (`mimiciii_derived`) as they contain a number of tables related to sepsis (including a first day sepsis-3 definition IIRC).
