### ISSUE TITLE
cookbook/postgres/mortality.sql is not working in Mimic III

### ISSUE THREAD

**Issue by vedanuj** [MIT-LCP/mimic-code#85]
ERROR:  relation "mimic2v30.admissions" does not exist
LINE 5: from mimic2v30.admissions adm

Changing database to mimiciii solves this issue however next the datetime integer addition has error.

ERROR:  operator does not exist: timestamp without time zone + integer
LINE 18: , round( sum(case when dod < admittime+30 then 1 else 0 end)...
                                               ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by tompollard** [comment]
Thanks for highlighting this Harry (/@vedanuj). It looks like all of the [cookbook scripts](https://github.com/MIT-LCP/mimic-code/tree/master/cookbook/postgres) need to be updated for MIMIC-III.

I have added header information to the scripts to make it clear that they are intended for a different version of MIMIC. If you have time to update them for MIMIC-III, we would welcome your contribution.

**Comment by alistairewj** [comment]
I just re-wrote all the cookbook scripts. Let us know if you have any more issues!
