### ISSUE TITLE
unable to load data

### ISSUE THREAD

**Issue by dewgong2** [MIT-LCP/mimic-code#851]
Hello lovely people, 

I got stuck at one of the parts. 

mimic=# \set ON_ERROR_STOP 1
mimic=# \set mimic_data_dir 'D:/mimic/v1_4'
mimic=# \i postgres_load_data.sql
postgres_load_data.sql: No such file or directory

I cannot load my data even though I have set it up accordingly. 

any advise on what needs to be done? 

<first time coder>

**Comment by alistairewj** [comment]
You do not have the `postgres_load_data.sql` file in the folder you used to launch `psql`.

**Comment by dewgong2** [comment]
ok so where do I find this 'postgres_load_data.sql'? 

sorry am completely new to coding so I'm not entirely familiar with what you are asking

**Comment by alistairewj** [comment]
No worries! You'll need a few files to load the data into a local database, and they're all located here: https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/postgres

Be sure to download the file itself and now an HTML version of the file (by clicking the "raw" button at the top right when you browse to the file).

You presumably have already ran the `postgres_create_tables.sql` script to create the tables. The next step would be to load the data with one of the three load_data scripts present there. It's probably easiest if you download all of those scripts, then follow along with this tutorial: https://mimic.physionet.org/tutorials/install-mimic-locally-ubuntu/
