### ISSUE TITLE
Note events demo data

### ISSUE THREAD

**Issue by faviehma** [MIT-LCP/mimic-code#852]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Is there a source for note event dummy data that can be used for illustrational purposes in a publication? Unfortunately the Demo Dataset does not contain any note events.

**Comment by alistairewj** [comment]
Nothing exists as of now. I think it's a good opportunity for synthetic data, but we've never added it to the demo to avoid confusion.
