### ISSUE TITLE
Use of MIMIC-III in Data Science Course

### ISSUE THREAD

**Issue by hildeweerts** [MIT-LCP/mimic-code#853]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
This February I will be teaching an undergraduate course on responsible data science. I am considering using the MIMIC-III for a group project.
* Most of the students have a background in computer science and are not as well-versed in medical data. In a perfect world, I would have involved an expert in the medical domain who can assist the students with in-depth questions. Unfortunately, we currently do not have the resources to arrange this. Are you aware of common prediction tasks for which MIMIC-III is suitable that are relatively well-defined? 
* The course has ~100 students. To avoid overburdening you with many simultaneous access requests, I was wondering whether it is possible to arrange some sort of batch processing. My suggestion would be that I consolidate the students' completion reports in a single request.

Any help would be greatly appreciated!

**Comment by hildeweerts** [comment]
FYI: I have just explored related repositories and it seems the data set provided by [MIMIC-Extract](https://github.com/MLforHealth/MIMIC_Extract) might be exactly what I am looking for!

My question re. consolidating completion reports still remains, of course.

**Comment by tompollard** [comment]
Hi @hildeweerts, thanks for reaching out. 

> Are you aware of common prediction tasks for which MIMIC-III is suitable that are relatively well-defined?

A common prediction task is in-hospital mortality, so this would be one option. There is a summary of approaches that people have used in http://proceedings.mlr.press/v68/johnson17a/johnson17a.pdf.

> The course has ~100 students. To avoid overburdening you with many simultaneous access requests, I was wondering whether it is possible to arrange some sort of batch processing. My suggestion would be that I consolidate the students' completion reports in a single request.

Please contact us using the address at: https://physionet.org/about/#contact to discuss this. We should be able to take a list of course participants to help speed up the process.

**Comment by hildeweerts** [comment]
Thanks!
