### ISSUE TITLE
Authentication errors on Ubuntu when building mimic-iii Postgres database

### ISSUE THREAD

**Issue by bluemonk482** [MIT-LCP/mimic-code#854]
I am building a mimic-iii postgres database on a Ubuntu server following the instruction provided in https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/postgres. However I keep getting authentication errors:

`psql (PostgreSQL) 13.1 (Ubuntu 13.1-1.pgdg18.04+1)`

```
$ sudo make create-user mimic datadir="/mnt/sdb/Data/mimiciii/data"
psql: error: FATAL:  Peer authentication failed for user "postgres"
/usr/bin/test: missing argument after ‘100000’
-------------------------------------
-- Creating user, database, schema --
-------------------------------------

MIMIC_USER="postgres" MIMIC_DB="mimic" MIMIC_PASSWORD="postgres" MIMIC_SCHEMA="mimiciii" DBHOST="" DBPORT="" ./create_mimic_user.sh
MIMIC_PASSWORD is set
MIMIC_DB is set to 'mimic'
User is set to 'postgres'
Not logged in as postgres user. Script will require sudo.
*** Ignore any warnings of the form: 'could not change directory to...' ***
These indicate you are running the script in a folder that the postgres user does not have access to.
The script will still work - so these warnings can be safely ignored.
DROP DATABASE
CREATE DATABASE

-----------------------
-- Checking for data --
-----------------------

Data path:  /mnt/sdb/Data/mimiciii/data/
All data present!

------------------------
-- Building MIMIC-III --
------------------------

---------------------
-- Creating schema --
---------------------

psql "dbname=mimic user=postgres password=postgres options=--search_path=mimiciii" -v ON_ERROR_STOP=1 -c "DROP SCHEMA IF EXISTS mimiciii; CREATE SCHEMA mimiciii;"
psql: error: FATAL:  Peer authentication failed for user "postgres"
Makefile:131: recipe for target 'mimic-build' failed
make: *** [mimic-build] Error 2
```

I have changed `local all postgres peer` to `local all postgres md5` in `/etc/postgresql/10/main/pg_hba.conf`, and used the command below:

`sudo make create-user mimic datadir="/mnt/sdb/Data/mimiciii/data" DBUSER="$USER"`

However now, the default password, i.e. "postgres" does not seem to be working :

```
psql: error: FATAL:  Peer authentication failed for user "bowang"
/usr/bin/test: missing argument after ‘100000’
-------------------------------------
-- Creating user, database, schema --
-------------------------------------

MIMIC_USER="bowang" MIMIC_DB="mimic" MIMIC_PASSWORD="postgres" MIMIC_SCHEMA="mimiciii" DBHOST="" DBPORT="" ./create_mimic_user.sh
MIMIC_PASSWORD is set
MIMIC_DB is set to 'mimic'
User is set to 'bowang'
Password for user postgres:
Password for user postgres:
psql: error: FATAL:  password authentication failed for user "postgres"
Password for user postgres:
psql: error: FATAL:  password authentication failed for user "postgres"
Password for user postgres:
psql: error: FATAL:  password authentication failed for user "postgres"
Makefile:76: recipe for target 'create-user' failed
make: *** [create-user] Error 2
```

**Comment by alistairewj** [comment]
It looks like it's still attempting peer authentication for your user. This means your OS username must be `bowang` exactly so double check that. Otherwise you can run the commands as the postgres user by prefixing the shell commands with `sudo -u postgres`, but I wouldn't recommend this in general because it gets tedious. Best to solve the peer authentication using the operating system.

Note that because it's still attempting peer authentication when you have changed the `pg_hba.conf` to use md5 auth (password), the configuration probably hasn't been adopted by postgres. This might be because the service needs to be restarted in order for changes to take effect: `systemctl restart postgresql-13` or `systemctl restart postgresql-13.service`.

**Comment by alistairewj** [comment]
Please feel free to re-open if you are still having difficulty!
