### ISSUE TITLE
Default FiO2 values and null values in pivoted_fio2

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#855]
I am trying to recored _fio2_ for patients in two points of time along the ICU stay. Some of the patients don't have previous valid fio2 value.

**Can I safely assume fio2 is 21% by default in the following:**

1. No previous fio2 recored for this patient in this point in time along icustay
2. Only previous 'Null' values for this patient in this point in time along icustay

(Lets say "safely" means 90-95% of the times)

**Comment by alistairewj** [comment]
Probably not! A lot of patients receive oxygen therapy which will increase their effective FiO2. I would look towards a rule that combines FiO2 with oxygen flow rate. If you incorporate o2 flow then you should be OK to assume 21%..

**Comment by arielhasidim** [comment]
Just to be sure and maybe leave a detailed answer for the future:
Would you say these both queries would make it?
```
SELECT * FROM `physionet-data.mimiciii_clinical.d_labitems`   
where lower(LABEL) like '%oxy%'
or lower(LABEL) like '%o2%'
```
AND
```
SELECT * FROM `physionet-data.mimiciii_clinical.d_items` 
where lower(LABEL) like '%oxy%'
or lower(LABEL) like '%o2%'
```

**Comment by alistairewj** [comment]
Those cover a lot more concepts than just oxygen flow - almost all oxygen flow will be documented in the two `itemid` with something like "O2 Flow" or "Oxygen Flow" as the label (one of CareVue, one for MetaVision).
