### ISSUE TITLE
Waveform labels

### ISSUE THREAD

**Issue by fmenegui** [MIT-LCP/mimic-code#857]
I have been trying to understand the meaning of each waveform in the MIMIC III waveform database. I have come across waveforms labeled as "ART", "ABP", "PLETH", and "PLETH R". Using the documentation from MIMIC II (https://archive.physionet.org/mimic2/mimic2_waveform_overview.shtml), I could understand that both "ART" and "ABP" are blood pressure signals. Using the same documentation, it is easy to see that "PLETH" refers to the photoplethysmography signals, however, what is the difference between "PLETH" and "PLETH R" ?

Thank you.

**Comment by alistairewj** [comment]
It's likely as simple as the right hand is used for the PLETH. You may find
this list useful: https://archive.physionet.org/physiobank/signals.shtml
