### ISSUE TITLE
Linking an order to the id of the provider that made the order 

### ISSUE THREAD

**Issue by MousaGhannam** [MIT-LCP/mimic-code#861]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi MIMIC Team, 
Just wanted to start off by saying thank you for building this amazing resource! 

I am trying to analyze the decision-making patterns of ICU providers ordering certain medications. I just wanted to confirm that although the `cgid` column exists for the `inputevents_MV` table, that this refers to caregivers that validated this measurement, and not to those that made the original order. Is there any way to link the order made by a given provider with their respective `cgid`?  

I have noticed that in MIMIC-IV, you have added an "ordertime" variable to the `poe` table. This is also very useful information, but we still only get the date the provider made the order, and not the provider's ID, right? 

I just wanted to make sure that I've exhausted all of the possibilities here! Thanks again, I appreciate any insight you can offer on this matter. 

Best,
Mousa

**Comment by alistairewj** [comment]
> I am trying to analyze the decision-making patterns of ICU providers ordering certain medications. I just wanted to confirm that although the cgid column exists for the inputevents_MV table, that this refers to caregivers that validated this measurement, and not to those that made the original order.

Correct.

> Is there any way to link the order made by a given provider with their respective cgid?

Not that I'm aware of.

> I have noticed that in MIMIC-IV, you have added an "ordertime" variable to the poe table. This is also very useful information, but we still only get the date the provider made the order, and not the provider's ID, right?

Correct. Care provider information is low priority for adding to MIMIC-IV unfortunately.

**Comment by MousaGhannam** [comment]
Great to know! Thank you for taking the time to respond. :)
