### ISSUE TITLE
The patients table

### ISSUE THREAD

**Issue by bluetareqqq** [MIT-LCP/mimic-code#862]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/ [x]
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q= [x]

### Description

Description of the issue, including:

in your documentation "**The patients table**" in the following link
https://mimic.physionet.org/mimictables/patients/
"DOB
DOB is the date of birth of the given patient. Patients who are older than 89 years old at any time in the database have had their date of birth shifted to obscure their age and comply with HIPAA. The shift process was as follows: the patient’s age at their first admission was determined. The date of birth was then set to exactly 300 years before their first admission."

I think on the last page, instead of "The date of birth was then set to exactly 300 years"
It should be
"The age was then set to exactly 300 years"

**Comment by alistairewj** [comment]
It's awkward wording but the sentence is correct: we set their date of birth to exactly 300 years before their first admission. So their age is also 300 years at their first admission - but it can be higher on subsequent admissions.
