### ISSUE TITLE
The description of "icustaysTable" is duplicated in  buildmimic/aws-athena/mimic-iii-athena.yaml 

### ISSUE THREAD

**Issue by vbnshin** [MIT-LCP/mimic-code#866]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi MIMIC Team,
The description of "icustaysTable" is duplicated in  [buildmimic/aws-athena/mimic-iii-athena.yaml](https://github.com/MIT-LCP/mimic-code/blob/1dd6637f47c83fe685176534b770e37b7fb48ef9/buildmimic/aws-athena/mimic-iii-athena.yaml)

Codes in L526-L564 and L566-L604 are exactly the same, as shown below.
https://github.com/MIT-LCP/mimic-code/blob/1dd6637f47c83fe685176534b770e37b7fb48ef9/buildmimic/aws-athena/mimic-iii-athena.yaml#L526-L604
By using this [CloudFormation template](https://github.com/MIT-LCP/mimic-code/blob/1dd6637f47c83fe685176534b770e37b7fb48ef9/buildmimic/aws-athena/mimic-iii-athena.yaml), I was able to successfully deploy an environment for analyzing MIMIC3. However, I think this code duplication should be fixed to improve maintainability of the program.

Best regards, Thank you

**Comment by alistairewj** [comment]
Glad you're able to still run it - thanks for the catch - fixed in https://github.com/MIT-LCP/mimic-code/commit/f5ffa1407b45c26faa944d3301981f97271aecc0
