### ISSUE TITLE
hadm_id with mimic_cxr

### ISSUE THREAD

**Issue by rohankhera** [MIT-LCP/mimic-code#867]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Thanks for the incredible contribution to science. We are trying to merge some of the CXR data with MIMICIV, but can only find the ability to link at a subject_id level, rather than a hadm_id level. I was wondering if that was possible.

Thanks,
Rohan

**Comment by alistairewj** [comment]
Answered in https://github.com/MIT-LCP/mimic-iv/issues/108
