### ISSUE TITLE
D-dimer assays in the MIMIC III.

### ISSUE THREAD

**Issue by zhidehu** [MIT-LCP/mimic-code#869]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

Hi, I performed a study to investigate the prognostic value of D-Dimer in critical illness. Two reviewers asked to report the assay(s) used to determine plasm D-Dimer in my manuscript. It seems that the D-Dimer assay is not indicated in the MIMIC III database (version 1.4).
My question is, therefore, how to get the information of the D-Dimer assay?

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
If the data are not in `d_labitems` then there is no way to acquire it. However I can find d-dimer in the lab table, you might double check your query:

```sql
select * from mimiciii_clinical.d_labitems where lower(label) like '%dimer%'
```

If the problem is low number of observations, again we can't do anything as the table includes all labs collected.

**Comment by zhidehu** [comment]
Hi, alistairewj.
Thank you for your kind reply.
It seems that there is a misunderstanding due to my vague statement in the original post.
I have collected the D-dimer results from the MIMIC database and analyzed the prognostic value of D-dimer. The manuscript of this work is now in revising stage. The reviewers asked me to add the test method (instrument, reagent, assay used for blood D-dimer measurement) for D-dimer in the revised manuscript. I have checked the table named lab_items but failed to find the test method for D-dimer.

**Comment by alistairewj** [comment]
Ah, I clearly misunderstood! My apologies. Here is some info on the specific assay:

> HemosIL D-Dimer HS 500 is an automated latex enhanced immunoassay for the quantitative determination of D-Dimer in human citrated plasma, which can be run on the ACL TOP analyzer. The reagent contains latex particles coated with monoclonal antibodies (F(ab’)2 fragment) that are highly specific for the D-Dimer domain. In the presence of D-Dimer, the latex particles will agglutinate. The degree of agglutination is directly proportional to the concentration of D-Dimer in the sample and is determined by measuring the decrease of the transmitted light caused by the aggregates (turbidimetric immunoassay).

**Comment by zhidehu** [comment]
Hi, alistairewj.
Thank you for your kindly response.
This information is really useful for me.
BTW, can i thank you in the acknowledgement section of my manuscript?

**Comment by alistairewj** [comment]
Sure, good luck! :)
