### ISSUE TITLE
Date-shifting in noteevents text files

### ISSUE THREAD

**Issue by joel1391** [MIT-LCP/mimic-code#87]
I'm looking at the text from notes in the noteevents table and trying to link it up with parts of the rest of the database, but the times have been shifted differently within the text of the notes compared to every other table. 

Is there any way to shift it back on my end so that it fits the rest of the database?

**Comment by tompollard** [comment]
Hi Joel, this is a known issue. There is no simple way of correcting the shift on your side, but the notes have been fixed for the next release. We should have the new version on PhysioNet within 6 weeks.

**Comment by alistairewj** [comment]
MIMIC-III v1.4 has just been released and this issue is fixed in it.
