### ISSUE TITLE
Prescriptions don't have frequency or duration

### ISSUE THREAD

**Issue by henry-feldman** [MIT-LCP/mimic-code#870]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
These prescriptions (which are really medication orders, since prescriptions the patient self-administers, while the nurses administer the orders) include a time span but not a frequency or duration. For instance was the drug given daily, BID, TID, Q8h? and for how many doses (yes with frequency I can calculate that for the time span). I know it is in the original data (I am a doc at BIDMC)

Description of the issue, including:
Not relevant (missing column in schema)

**Comment by alistairewj** [comment]
There's actually quite a bit of information missing from the MIMIC-III prescriptions. We won't be adding any new data to MIMIC-III. Instead we'd recommend switching over to MIMIC-IV, which has an entirely new table (*pharmacy*) which has a lot of this missing info.  https://physionet.org/content/mimiciv/
