### ISSUE TITLE
CGID null frequently on NoteEvents

### ISSUE THREAD

**Issue by henry-feldman** [MIT-LCP/mimic-code#871]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
On the noteevents table the CGID is null for a large percentage of the notes (314501 to be exact). Obviously the EMR does not have unattributed notes in it, so not sure why these are all null. This is a problem if you want to analyze patterns in note content by author (like is this weird notation just one resident's issue or is it common across a class of authors?).

* what you have tried: nothing to do (since you can't know what is unknowable)
* references to similar issues (didn't see this exact issue)
* queries demonstrating your question (if applicable)
SELECT * FROM `noteevents` WHERE `CGID` IS NULL;

**Comment by alistairewj** [comment]
The original source data we received did not have caregiver for the hospital level notes, so we were only able to include it for the ICU derived notes. Not many people analyzed the care provider information historically so it's low priority and I don't think the information will be added any time soon (it requires a lot of work in the background - de-duplicating records, doing record linkage, etc).
