### ISSUE TITLE
date sequence among hadm_ids for a given subject_id

### ISSUE THREAD

**Issue by AshCher51** [MIT-LCP/mimic-code#872]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

My goal is to predict future icd 9 code diagnoses for a given subject using the given subject's history of icd 9 codes, using the diagnoses_icd and admissions tables. However, after looking at the document about time on the MIMIC website, I don't think this is a correct approach because the year/month/exact date is randomized (while I thought the internal order of dates would be preserved for each patient despite the shifting, this doesn't seem to be the case). 

Is there a way to order hadm_ids by time for a given patient?

**Comment by briangow** [comment]
Any difference in time between a given patient (`subject_id`) is the true difference.  Please see the following:

https://github.com/MIT-LCP/mimic-code/issues/690
https://mimic.mit.edu/mimicdata/time/
