### ISSUE TITLE
Many (around 11%) of the rows in the NOTEEVENTS has HADM_ID value as NULL. Why is that? I need to find the Prescriptions related to the NOTEEVENTS. But with HADM_ID as null, how can I do that?

### ISSUE THREAD

**Issue by analognahid** [MIT-LCP/mimic-code#873]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
> Many (around 11%) of the rows in the NOTEEVENTS has HADM_ID value as NULL. Why is that?

The note is documented outside a hospitalization.
