### ISSUE TITLE
Death in ICU

### ISSUE THREAD

**Issue by Yuz998** [MIT-LCP/mimic-code#874]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, 
     I am working on a project that needs to know the deaths of patients during the ICU. In the intensive care unit, how do I calculate the death sign of a patient?
Thanks

**Comment by briangow** [comment]
Are you looking for `DOD` from the `patients` table? https://mimic.physionet.org/mimictables/patients/

**Comment by Yuz998** [comment]
No, The `DOD` include both deaths within the hospital (`DOD_HOSP`) and deaths identified by matching the patient to the social security master death index (`DOD_SSN`).  I want to know if the patient died during ICU?  How to judge?

**Comment by briangow** [comment]
You can use SQL `JOIN` commands to join information across the tables based on shared columns (`subject_id` for example).  In this case you could join the `ICUSTAYS` table (https://mimic.physionet.org/mimictables/icustays/) with the `PATIENTS` table (https://mimic.physionet.org/mimictables/patients/).  If the `DOD` in the `PATIENTS` table occurs between the `INTIME` and `OUTTIME` for a given ICU stay then you can conclude that the patient died in the ICU.

**Comment by Edelwiess** [comment]
deathtime < outtime ?

**Comment by alistairewj** [comment]
`outtime` is administratively recorded so I'd add some approximation.

You can also use the *transfers* table: if the last ward in the hospital was the ICU, and they died during the hospital discharge, then it's reasonable to infer they died within the ICU.

**Comment by Yuz998** [comment]
Thank you for the response. Much appreciated
