### ISSUE TITLE
what the difference between "Arterial BP #2 [Systolic]" and "arterial BP [Systolic] "

### ISSUE THREAD

**Issue by Edelwiess** [MIT-LCP/mimic-code#875]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

I want to extract the ABP informations from MIMIC, but I found there were 2 types of itemids for one kind of ABP in CV database.
As for ABPs, 51 with label  "Arterial BP #2 [Systolic]" , but  6701 with "arterial BP [Systolic] ",
As for ABPd, 8555 with label like "Arterial BP #2 [Diastolic]", but 8368 with label like "Arterial BP [Diastolic]".
The meanings of these itemids are similar but indeed the itemid is different.

I wanna figure out what the difference between those two types of itemids.
I'v searched the documents and the GitHub, there is no similar questions and answers.
Thanks.

 
* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by briangow** [comment]
Assuming the difference isn't invasive versus non invasive blood 
pressure, it is probably related to the different systems (monitors) 
that were used to collect the data.  These resources provide more 
information regarding this and how it can relate to `itemid`:

https://github.com/MIT-LCP/mimic-code/issues/848
https://mimic.physionet.org/mimicdata/metavision/

**Comment by Edelwiess** [comment]
Thank you very much. But I'v already read it. Both these two itemids belong to CV monitor/system. So the difference is still very unclear.
![1](https://user-images.githubusercontent.com/20700559/111976007-15abc300-8af9-11eb-992e-d55d6c2e33b0.png)

**Comment by Edelwiess** [comment]
I hope you also can show me how you query or how you figure out the difference. Thank you!!!

**Comment by alistairewj** [comment]
There are two documentation patterns in CareVue to be aware of in the context of multiple `itemid` for a similar concept

1. Nurses are able to add new `itemid` by typing in a new label. Thus you end up with many "one-off" `itemid` used for only a handful of patients.
2. Multiple ongoing processes to be aware of (e.g. oxygen device 1 and 2 for multiple oxygen devices, invasive line 1-6 for multiple invasive lines).

In this case, these `itemid` are a result of the second option. The patient likely has multiple arterial lines, or an arterial line + IABP, or some other source of arterial blood pressure.

**Comment by Edelwiess** [comment]
Thank you very much! It's so kind of you!!!

**Comment by Edelwiess** [comment]
close
