### ISSUE TITLE
ICD code and discharge summary discrepancy 

### ISSUE THREAD

**Issue by joel1391** [MIT-LCP/mimic-code#88]
I'm trying to identify a subset of patients with a certain disease. So far I've searched for patients with a certain icd diagnosis code (in the diagnoses_icd table), and then tried searching discharge summaries (from noteevents table) for the same diagnosis, but I'm getting very different results. I get around 10% more results using the icd search but I thought it should be the other way around (thinking that the text search would have more false positives).

At first I thought it could be an issue with the text phrases I'm searching for, so I started reading the discharge summaries. I am noticing that a lot of the extra patients picked up in the icd query don't actually have any mention of the disease at all in any of the notes for that patient. I read through the discharge summaries, the nurses notes, physician notes, reports, but none of them suggest presence of the disease specific to that icd code.

That brings me to a few questions - 
1. Is it possible that the icd i'm searching for has been wrongly coded, and in that many patients?
2. Do the coders have access to extra information that wouldn't be in the notes that we have? 
3. Do the discharge summaries contain all information regarding diagnoses and complications with an admission?
4. Ultimately, what is the best method for determining any diagnoses for an individual patient? The main reason I ask this is because querying through 50000 patients is much easier just using an icd code, but if the discharge summary is more correct - I'd prefer to incorporate that in to queries for correctly identifying our patient subset.

**Comment by tompollard** [comment]
@joel1391 please could you provide a script that demonstrates this issue?

**Comment by alistairewj** [comment]
Yes - very interesting - would love to see some examples.

**Comment by alistairewj** [comment]
Going to close this issue with some recommendations for other users:

* ICD-9 codes can *only* be assigned if there is a signed note from a physician detailing a diagnosis.
* ICD-9 codes are primarily for billing, and the lack of an ICD-9 code for a diagnosis does *not* imply that the patient does not have the diagnosis (i.e., ICD-9 codes do not have high specificity).
* In general, when searching for diagnoses or conditions, the most robust definition will cross-reference multiple possible definitions (e.g. structured data in CHARTEVENTS, ICD-9 codes, free-text searches in discharge summaries). Any statistical analysis done later on may benefit from sensitivity analyses around the definition of the cohort.

**Comment by manashty** [comment]
@alistairewj 
Just for clarification, are ICD-9 codes assigned for a patient who just admitted into hospital or when released?
Assuming a patient was diagnosed with disease A, but later on, with more tests, it became clear that he actually had disease B, not A:
1. Do ICD-9 codes represent disease A (best guess when admitted) or B (confirmed, discharge notes)? 
2. Between ICD-9 codes and "Diagnosis" in the discharge note (free-text), which one is assumed more accurate discharge diagnosis of a patient?

I am interested in predicting the actual diagnosis of a patient using the prior data. So I was wondering whether the Discharge notes contains the most updated information or not.

Thanks!

**Comment by alistairewj** [comment]
The ICD-9 codes are assigned on hospital discharge, and they are assigned based on a review of the patient's chart by professional coders. They can only assign an ICD-9 code if there is a signed note by a physician which states that diagnosis - though they will often contact physicians and ask them to clarify ambiguity.

The free-text discharge note is highly variable - it's a quickly written one or two word guess done on admission. I recall there being ~28,000 unique "diagnoses" for 35,000 admissions. Anecdotally, I've seen patients whose primary ICD-9 diagnosis on discharge being infection/sepsis, while their admission diagnosis was syncope. I wouldn't recommend using the admission diagnosis.

Overall, for your proposed task, the ICD-9 diagnoses make the most sense. Good luck!

**Comment by alistairewj** [comment]
I'd also add, I recently added a mapping of ICD-9 diagnosis codes to CCS topics, which are meant to be a more clinically useful grouping of ICD-9 codes. You can find it here: https://github.com/MIT-LCP/mimic-code/tree/master/concepts/diagnosis

**Comment by manashty** [comment]
@alistairewj
Thanks a lot for the explanation! It made things clearer for me.

I faced the same problem with high number of unique diagnosis! They are simply too many to train a model even using this dataset. I also appreciate the grouping code. It is really helpful. Thanks again for prompt reply!
