### ISSUE TITLE
The gcsfirstday View Throws Several Syntax Errors

### ISSUE THREAD

**Issue by mjs2600** [MIT-LCP/mimic-code#89]
Postgres is complaining about the syntax on lines 26, 84, and 129 of `gcs-first-day.sql`.

**Comment by mjs2600** [comment]
@alistairewj is this view done?

**Comment by tompollard** [comment]
This question is referring to the following scripts: https://github.com/MIT-LCP/mimic-code/blob/master/etc/firstday/gcs-first-day.sql

It runs for me. Do you have more detail about the error? @alistairewj's guess when we briefly chatted about this earlier is that your problem relates to the schema definition (mimiciii), which appears three times in the script.

**Comment by alistairewj** [comment]
Yeah that's my guess, I just removed all the schema names because they shouldn't really be there anyway. Let us know if that was the issue.

**Comment by mjs2600** [comment]
It looks like the issue was caused by the way IntelliJ was reading in the SQL. Feeding it directly to `psql` or concatenating it into a single line fixes the problem. Thanks!
