### ISSUE TITLE
I want to download the MIMIC-II dataset but I can't find it.

### ISSUE THREAD

**Issue by SephiHorse** [MIT-LCP/mimic-code#898]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I want to download the MIMIC-II dataset but I can't find it. I have tried the https://physionet.org/works/MIMICIIClinicalDatabase/ and https://physionet.org/physiobank/database/mimic2cdb/  , but both with 404 Not Found.

**Comment by tompollard** [comment]
@SephiHorse MIMIC-II is no longer available, because we do not have the capacity to support older versions of the MIMIC database. MIMIC-II is a subset of MIMIC-III, so any studies using MIMIC-II should be reproducible on MIMIC-III. 

You would just need to limit the analysis to patients on the "CareVue" system. The MIMIC-III database is available from: https://doi.org/10.13026/C2XW26

**Comment by SephiHorse** [comment]
> @SephiHorse MIMIC-II is no longer available because we do not have the capacity to support older versions of the MIMIC database. MIMIC-II is a subset of MIMIC-III, so any studies using MIMIC-II should be reproducible on MIMIC-III.
> 
> You would just need to limit the analysis to patients on the "CareVue" system. The MIMIC-III database is available from: https://doi.org/10.13026/C2XW26

Thank you very much! By the way, I have downloaded the MIMIC-III successfully and found some issues. The existing works which have experimented on MIMIC-III claimed there are more than 8000 unique ICD9 codes appearing in the DIAGNOSES_ICD table, but I only counted 6985 unique ICD9 codes from the one I downloaded. Was there a recent update which remove some of the records in DIAGNOSES_ICD or else? Looking forward to getting replied, thx!

**Comment by tompollard** [comment]
> The existing works which have experimented on MIMIC-III claimed there are more than 8000 unique ICD9 codes appearing in the DIAGNOSES_ICD table, but I only counted 6985 unique ICD9 codes from the one I downloaded. 

I'm not sure which works you are referring to in particular, but I don't think this is anything to worry about. It's possible that `DIAGNOSES_ICD` contained codes that were not mapped to any patients and so they were removed at some point. You could check the MIMIC changelog to see if anything is mentioned there.

**Comment by st--** [comment]
Hi, it took me a while to come to the same conclusion - would it be possible for you to add a notification box to the top and/or bottom of https://physionet.org/content/mimic-ii/2.6.0/ (where it currently just says "When using this resource, please cite ..." and "The files for this project are no longer available.") to clarify that MIMIC-II is no longer supported, and how to access the MIMIC-II subset of MIMIC-III?
