### ISSUE TITLE
Import Data

### ISSUE THREAD

**Issue by ZML0113** [MIT-LCP/mimic-code#899]
I want to import the MIMIC Ⅲ data into the Postgresql with Github code. I have imported the data for nearly about 17 hours,but nothing changed and happened in the Postgresql.

**Comment by briangow** [comment]
Depending on your setup (computer hardware, etc) the import can take a long time.  If the import fails, please provide details about your setup, and exactly what you have done (the link to the Github code you are using and the commands you issued to run it) along with any error messages you've received.

You may also want to consider using BigQuery, which provides access to MIMIC in the cloud: https://mimic.physionet.org/gettingstarted/cloud/ .

**Comment by Erinaceida** [comment]
From what I know, the SQL code for building the database hasn't been updated yet to the latest version of MIMIC

**Comment by briangow** [comment]
For the latest version of MIMIC, IV 1.0, please see the mimic-iv repo: https://github.com/MIT-LCP/mimic-iv .  We do plan to move the mimic-iv repo under mimic-code eventually.

**Comment by ZML0113** [comment]
When I tried importing the MIMIC data into Postgresql,it didn't display any error and mistake.It has kept rendering the interface as shown in the picture without any changes


















At 2021-03-30 02:47:48, "Brian Gow" ***@***.***> wrote:

Depending on your setup (computer hardware, etc) the import can take a long time. If the import fails, please provide details about your setup, and exactly what you have done (the link to the Github code you are using and the commands you issued to run it) along with any error messages you've received.

You may also want to consider using BigQuery, which provides access to MIMIC in the cloud: https://mimic.physionet.org/gettingstarted/cloud/ .

**Comment by briangow** [comment]
I can't see the image you posted. Please provide details about your setup (computer hardware and operating system info), and exactly what you have done (the link to the Github code you are using and the commands you issued to run it).  As mentioned the installation can take a long time.  Please see this thread for more details regarding this: https://github.com/MIT-LCP/mimic-code/issues/181 .

**Comment by ZML0113** [comment]
Hi！Thanks for your reply at first.
I'm trying to load the MIMIC-III data into a local postgres database by following instructions from this link:
https://mimic.physionet.org/tutorials/install-mimic-locally-windows/
So far despite leaving it overnight, it consistently hangs at this stage:
COPY 58976
COPY 34499
COPY 7567
Here's the configuration of my machine
XiaoXin-131ML 2020 (13-inch, October 2020)
Processor: Inter(R) Core(TM)i5-10210U CPU@ 1.60 GHz  2.11GHz 
Memory: 8 GB,512G
I have seen the link that you given me.I saw that  you said I'll need around 90GB of free space for the database.I want to make sure if this is true.And I also see that the Github Code updated on March 23.I also want to know if I should use the new Github Code.Besides, we run the PosrgreSQL 9.6 with SQL files.Why did the script file named make_concepts become SH file?


I look forward to your guidance on this. Thanks!










At 2021-04-07 22:58:30, "Brian Gow" ***@***.***> wrote:

I can't see the image you posted. Please provide details about your setup (computer hardware and operating system info), and exactly what you have done (the link to the Github code you are using and the commands you issued to run it). As mentioned the installation can take a long time. Please see this thread for more details regarding this: #181 .

**Comment by briangow** [comment]
Did you issue this command as suggested in the tutorial: `\set ON_ERROR_STOP 1`?

Since you are on Windows you may be running into this bug in Postgres (versions 11 - 13): https://stackoverflow.com/questions/53523051/error-could-not-stat-file-xx-csv-unknown-error .  As you can see in the thread there may be a few potential workarounds:

- Downgrade Postgres to v10 if you don't need a recent version.  It may be possible to simply downgrade the psql / pgadmin tools. 
- Keep the files zipped during import as discussed in the tutorial.
- Wait for the fix for this bug, which is scheduled to released in v14 of Postgres.

**Comment by ZML0113** [comment]
Hi! I am so sorry to bother you,but I faced a new problem that I couldn't solve.
I have transpotred all the data into the PostgreSQL,but I couldn't open the software 'pgAdmin4'.It said that"pgAdmin 4  the application server could not be contant".I want to ask for your help to solve this problem.
Thank you very much.
















At 2021-04-10 01:45:17, "Brian Gow" ***@***.***> wrote:

Did you issue this command as suggested in the tutorial: \set ON_ERROR_STOP 1?

Since you are on Windows you may be running into this bug in Postgres (versions 11 - 13): https://stackoverflow.com/questions/53523051/error-could-not-stat-file-xx-csv-unknown-error . As you can see in the thread there may be a few potential workarounds:

Downgrade Postgres to v10 if you don't need a recent version. It may be possible to simply downgrade the psql / pgadmin tools.
Keep the files zipped during import as discussed in the tutorial.
Wait for the fix for this bug, which is scheduled to released in v14 of Postgres.

**Comment by briangow** [comment]
This appears to be a problem with Postgres, not the MIMIC dataset.  I'd suggest posting to a Postgres specific forum if you can not figure it out.  However, a quick search revealed this, perhaps it's related: https://stackoverflow.com/questions/43211296/pgadmin4-postgresql-application-server-could-not-be-contacted .
