### ISSUE TITLE
Link to the step-by-step tutorial for building MIMIC-III with PostgreSQL is outdated on physionet.org

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [MIT-LCP/mimic-code#90]
On https://physionet.org/works/MIMICIIIClinicalDatabase/files/, the link in 

> A step-by-step tutorial for building MIMIC-III with PostgreSQL is available on the [MIMIC website](http://mimic.physionet.org/tutorials/install_mimic_locally/).

is outdated.

**Comment by tompollard** [comment]
I've fixed the link on PhysioNet - thanks for picking this up Franck.

**Comment by Franck-Dernoncourt** [comment]
Thanks! I was wandering there I was looking for [previous versions of MIMIC-III](http://opendata.stackexchange.com/q/7362/1652).
