### ISSUE TITLE
Why the rate of suspected infection is different?

### ISSUE THREAD

**Issue by ChenXJ295** [MIT-LCP/mimic-code#900]
We have run the code, and get the different result below. The main difference is in the "exclusion_early_suspicion" and "exclusion_late_suspicion".  Is anyone has this question and can help?
PS: We have checked the version of the dataset is v1.4.
The true result:
Cohort - initial size: 61532 ICU stays
  15056 (24.47%) - exclusion_secondarystay
   8109 (13.18%) - exclusion_nonadult
   7343 (11.93%) - exclusion_csurg
  37912 (61.61%) - exclusion_carevue
 **7343 (11.93%) - exclusion_early_suspicion
   3914 (6.36%) - exclusion_late_suspicion**
    491 (0.80%) - exclusion_bad_data
Final cohort size: 11791.0 ICU stays (19.16%).

Our result:
Cohort - initial size: 61532 ICU stays
  15056 (24.47%) - exclusion_secondarystay
   8109 (13.18%) - exclusion_nonadult
   7343 (11.93%) - exclusion_csurg
  37912 (61.61%) - exclusion_carevue
   **9550 (15.52%) - exclusion_early_suspicion
   2808 (4.56%) - exclusion_late_suspicion**
    491 (0.80%) - exclusion_bad_data
Final cohort size: 11325.0 ICU stays (18.41%).

**Comment by alistairewj** [comment]
It's likely related to how the medications are determined. This probably makes more sense to raise in the sepsis-3 repository: https://github.com/alistairewj/sepsis3-mimic
