### ISSUE TITLE
Load the data into the tables when install mimic

### ISSUE THREAD

**Issue by Bella39** [MIT-LCP/mimic-code#901]
in the process of installing mimic, I have difficulty in loading the data into the tables when install mimic. after code
"mimic=# \i D:/mimic/mimic-code-master/buildmimic/postgres/postgres_load_data.sql
COPY 58976
COPY 34499
COPY 7567
psql:D:/mimic/mimic-code-master/buildmimic/postgres/postgres_load_data.sql:49: 错误: 无法取文件 "CHARTEVENTS.csv" 的状态: value too large"
I want someone could give me advice in this case.

**Comment by SichengH** [comment]
What is the version of your Postgres?

**Comment by Bella39** [comment]
postgresql-13.2-1-windows-x64

**Comment by alistairewj** [comment]
This is likely the same error as #493 - and is related to a bug in PostgreSQL. Versions 11 and higher cannot load files larger than 4 GB. Two options:

1. (recommended) keep chartevents compressed (as a gzip or 7z file), and use one of the compressed loading methods
2. split chartevents into multiple files during import
