### ISSUE TITLE
Pre requisits

### ISSUE THREAD

**Issue by a2ztests** [MIT-LCP/mimic-code#902]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

I am a data engineer at a hmo. If I pass all the Prerequisites to use Mimic, am I allowed to prepare data for the use of researchers that did not act on the Mimic  Prerequisites?

**Comment by briangow** [comment]
As indicated on the MIMIC website and in the data use agreement you can not share your access to MIMIC with others.  Anyone using MIMIC needs to go through the process for requesting access: https://mimic.physionet.org/gettingstarted/access/ .
