### ISSUE TITLE
make concepts.sql

### ISSUE THREAD

**Issue by zyh1996007** [MIT-LCP/mimic-code#904]
do you delate this .sql?
how to use make concepts now,thank you very much

**Comment by zyh1996007** [comment]
“make concepts.sql”is still in my computer. Can I continue to use them? Is there any difference between them？

**Comment by briangow** [comment]
This README gives information on concepts: https://github.com/MIT-LCP/mimic-code/tree/master/concepts .  If the information here does not allow you to achieve what you need could you please describe your issue in more detail.

**Comment by alistairewj** [comment]
We stopped using the `make-concepts.sql` and started using a shell script (`make-concepts.sh`) when we converted all the syntax to BigQuery. It's still possible to create the concepts in PostgreSQL but it does take a little extra doing, and the instructions are in the README @briangow linked.
