### ISSUE TITLE
Ambiguity in ECG Lead Label "V" and "MCL" in MIMIC-III Waveform Dataset

### ISSUE THREAD

**Issue by maxxu05** [MIT-LCP/mimic-code#907]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello,
I am working with the MIMIC-III waveform data, specifically the ECG data. Within the header file, most of the signals are described by their precise lead, e.g. AVL or AVR, however, many waveforms are labeled more ambiguously as V or MCL. Can you all please clarify what the V and the MCL label mean? Does the V label designate a bucket that includes the V1 and V2 lead? Does the MCL label designate just the MCL1 lead, or a bucket that includes the MCL1 and the MCL6 lead?

Thank you,
Max

**Comment by briangow** [comment]
With monitoring (as opposed to diagnostic) ECG’s little attention is paid to the exact position of the leads. A V5 position will usually give a high amplitude QRS and a V2 position is good for picking up RBBB and some VPBs. In Holter recordings 2 chest leads are used: one in roughly the V5 area and the other V2. Therefore you cannot assume an exact position for the V or MCL leads during monitoring.
