### ISSUE TITLE
Ethical issue

### ISSUE THREAD

**Issue by zhonglei12** [MIT-LCP/mimic-code#908]
To apply for access to the MIMIC-III database, I passed the Protecting Human Research Participants exam and obtained a certificate. However, I encountered a problem while submitting a manuscript.  Journal Editorial Office requires me to provide a proof of ethics approval. How should I provide a proof of ethical approval? 

Thank you very much for your help!

**Comment by alistairewj** [comment]
MIMIC-III is a deidentified dataset. Under HIPAA, this means research using it does *not* constitute human subjects research, and as a result you do not need IRB approval for your specific study. Most studies include a statement to this effect.

**Comment by zhonglei12** [comment]
Thank you for your answer!!!

**Comment by zhonglei12** [comment]
Thank you for your answer!!!

**Comment by zhonglei12** [comment]
The MIMIC-IV includes comprehensive and high-quality data of patients admitted to intensive care units (ICUs) at the Beth Israel Deaconess Medical Center (BIDMC) between 2008 and 2019, developed by the computational physiology laboratory of Massachusetts Institute of Technology (MIT) and approved by the institutional review boards of MIT and BIDMC. After passing the “Protecting Human Research Participants” exam on the website of the National Institutes of Health (NIH), the author was approved to extract data from this database.
When we publish article using this database, does it require all authors to grant access to the database?
I appreciate your solicitude, expect that is your to reply!

**Comment by tompollard** [comment]
@zhonglei12 thanks for checking! Anyone who accesses the data must have been formally granted access to the data via PhysioNet. For MIMIC-IV (https://physionet.org/content/mimiciv/), this means that anyone working with the data must have:

- completed the CITI training (https://physionet.org/settings/training/)
- completed the credentialing process (https://physionet.org/settings/credentialing/)
- signed the Data Use Agreement.

**Comment by zhonglei12** [comment]
Thank you for your answer!

**Comment by zhonglei12** [comment]
> @zhonglei12 thanks for checking! Anyone who accesses the data must have been formally granted access to the data via PhysioNet. For MIMIC-IV (https://physionet.org/content/mimiciv/), this means that anyone working with the data must have:
> 
>     * completed the CITI training (https://physionet.org/settings/training/)
> 
>     * completed the credentialing process (https://physionet.org/settings/credentialing/)
> 
>     * signed the Data Use Agreement.

Thank you for your answer!!
