### ISSUE TITLE
Missing values with Elixhauser query

### ISSUE THREAD

**Issue by danro9685** [MIT-LCP/mimic-code#91]
Hi, 

I have updated my local instance of MIMICIII to the latest one. 

On this, I run the queries to extract Elixhauser (the ones provided in the repository) and I group the patients per year (from 1 to 12). 

Done this, I notice that I get all missing values for for the patients in the second half of the years (from 6 to 12). 

Could you please check if there is any problem with the data files for Elixhauser? 

Thanks,
Daniele

**Comment by alistairewj** [comment]
I can run Elixhauser fine on my PC and don't have any weird issues. Are you sure you are using the most up to date version of Elixhauser? Can you perhaps provide more detail on what "missing values" means?

**Comment by danro9685** [comment]
Hi Alistair, 

I am running the query and then grouping the results accordingly to the year any patient was admitted in the hospital/icu. 

Then, when plotting the trends, I get 10 full years (excluding the first and the last year of MIMIC3 which are not complete) for all the other covariates. Instead for Elixhauser (both the normal one and the 28 days adjusted), I get everything good from year 1 to 6. Instead all the values from year 7 to 10 are not available. 

I did the same analysis on an other project with the previous version of MIMICIII and everything worked well. 

So my question is: (i) are there any issue with the latest version of MIMICIII or (ii) is there any change in the tables structures that could explain such a problem? 

Thank you! 
Daniele

**Comment by tompollard** [comment]
I just rebuilt the Elixhauser table using the script at: https://github.com/MIT-LCP/mimic-code/blob/master/comorbidity/postgres/elixhauser-ahrq-v37-with-drg.sql

...then I ran a few variations on following script, using a personal mapping table:

```
select a.admityear, sum(e.congestive_heart_failure)
from elixhauser_ahrq e
left join admityearmap a
on e.hadm_id = a.hadm_id
group by a.admityear
order by a.admityear;
```

There are comorbidities present for patients over the entire MIMIC period, so I don't see the issue described either. Try rebuilding your tables Daniele and if you still have problems then please reopen the issue.
