### ISSUE TITLE
MIMIC-IV documentation issue - stay_id in microbiology

### ISSUE THREAD

**Issue by edward-data-sci** [MIT-LCP/mimic-code#912]
In the microbiologyevents table documentation, stay_id is mentioned as a field, but it doesn't seem to exist in the db

**Comment by SichengH** [comment]
Not all microbiology events happened in the ICU, please use hadm_id or subject_id to link them with patients.

**Comment by briangow** [comment]
We will update the website to remove the mention of stay_id in microbiologyevents.

**Comment by edward-data-sci** [comment]
Thanks everyone!
