### ISSUE TITLE
Different patient number in mimic_core.patients between v1.0 and v0.4

### ISSUE THREAD

**Issue by AINIVERSHERRY** [MIT-LCP/mimic-code#915]
Hi Alistair. v1.0 has 382278 patients in mimic_core.patients, but v0.4 has 383220 patients in mimic_core.patients. (delta = 942). It makes me confusing , and I find a clue below, is the reason of decline?

<img width="773" alt="截屏2021-05-06 上午1 55 14" src="https://user-images.githubusercontent.com/49436429/117187565-a1aa4d80-ae0e-11eb-918d-dfd95c258d79.png">

**Comment by alistairewj** [comment]
Yes, correct, we cleaned up some of the data pulls before the v1.0 release. I forgot to mention that it also reduces the number of patients in the database.
