### ISSUE TITLE
NULL aki_stage in the kdigo_stages table

### ISSUE THREAD

**Issue by Qinyu-Allen-Zhao** [MIT-LCP/mimic-code#917]
Hi,

I'm working on MIMIC-IV on the Google BigQuery platform. In the kdigo_stages table, I found there are many records with numbers in the aki_stage_creat column and NULL entries in the aki_stage column.

```
SELECT * FROM `physionet-data.mimic_derived.kdigo_stages` 

WHERE aki_stage_creat > 0

AND aki_stage IS NULL

LIMIT 20
```

![image](https://user-images.githubusercontent.com/71951741/116770343-b46efc00-aa75-11eb-9672-8db5b5376589.png)

I suppose aki_stage is the combination of creatinine and urine output criteria. It should be NULL if there are entries in aki_stage_creat.

**Comment by SichengH** [comment]
Here is the script for generating derived tables. https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/concepts/organfailure

NULL in the  "aki_stage" means there is no record.

Please let us know if you have further questions.

**Comment by Qinyu-Zhao0522** [comment]
Hi!

I'm not sure about that. Could you check the results of my query?
These patients have serum creatinine records,  and they were diagnosed as AKI according to the creatinine criteria. However, they had NULL in the AKI_stage column. Patients had AKI_stage only when they both had creatinine and urine output.
Is there anything wrong?

**Comment by tompollard** [comment]
@Qinyu-Zhao0522 From the [kdigo stages query](https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iv/concepts/organfailure/kdigo_stages.sql), it looks like `aki_stage` is the max of (aki_stage_creat, uo.aki_stage_uo)

https://github.com/MIT-LCP/mimic-code/blob/0edce4cea6e3b6ffc4062b64f5b4a32c376b8918/mimic-iv/concepts/organfailure/kdigo_stages.sql#L81-L82

It seems that `GREATEST(cr.aki_stage_creat, uo.aki_stage_uo)` returns null if either of the values is null. I'd need to investigate, but I think this is a bug. 

In cases where one value is null, I assume we would want `aki_stage` to return max of the alternative value. e.g. `GREATEST(1, null)` should probably return 1 not null.

**Comment by tompollard** [comment]
The BigQuery [documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#greatest) notes that Greatest "Returns the largest value among X1,...,XN according to the < comparison. If any parts of X1,...,XN are NULL, the return value is NULL.". 

One solution is to wrap the values in `IFNULL`:

```
SELECT GREATEST(IFNULL(NULL,0), 1)

-- returns 1
```

So assuming there isn't a good reason to return null for these cases, line 82 can be changed to:

```
GREATEST(IFNULL(cr.aki_stage_creat,0), IFNULL(uo.aki_stage_uo,0) AS aki_stage
```

We can then regenerate the derived table on BigQuery.

**Comment by Qinyu-Zhao0522** [comment]
Thank you for your careful reply!

I suppose it's a difference between Postgres and BigQuery. I learned a lot.

**Comment by tompollard** [comment]
Thanks @Qinyu-Zhao0522, I now realise that COALESCE is probably a better option for the code repo than ISNULL, because COALESCE is supported by both Postgres and BigQuery. I'll update the repo shortly and bigquery tables shortly.
