### ISSUE TITLE
Diagnosis timestamp

### ISSUE THREAD

**Issue by cynthiazeng** [MIT-LCP/mimic-code#918]
Hi,

I'm wondering if there is a way to find out the specific datetime (or date) when a patient is diagnosed with a disease? In addition, is there a way to find the comorbidities (pre-existing conditions) of a patient? 

Thank you!

**Comment by alistairewj** [comment]
The *mimic_hosp.diagnosis_icd* table is created by trained coders after the patient is discharged. It takes some time after discharge, but the earliest time you can consider these diagnoses as being documented is the `dischtime` column in *mimic_core.admissions*, i.e. the diagnoses are available once the patient is discharged.

Comorbidities are often defined using ICD-9 / ICD-10 codes using one of a number of algorithms (Charlson, Elixhauser, etc) - I think we have one or two implemented so far: https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/concepts/comorbidity

(P.S. might be easier in the future to raise two issues for two separate questions so the questions are easier for others to find in the search).

**Comment by alistairewj** [comment]
The best approach for admission diagnosis is the corresponding section in the discharge summary.

Discharge summaries won't be available for MIMIC-IV until later this summer - but they will be identical in format to those of MIMIC-III. You could start with the MIMIC-III discharge summaries and you would very quickly be able to switch over to the MIMIC-IV notes when they are out.

**Comment by PSSF23** [comment]
@alistairewj Thanks for the reply! And could we assume that the stay IDs are consistent in `mimic-iii` and `mimic-iv`?

**Comment by alistairewj** [comment]
No they are not consistent. You'd only be able to port the code. Most patients in MIMIC-III aren't in MIMIC-IV anyway.

**Comment by PSSF23** [comment]
@alistairewj okay, so the same `hadm_id` will be referring to different people in `iii` and `iv`?

**Comment by alistairewj** [comment]
Correct.
