### ISSUE TITLE
blood gas specimen type all null

### ISSUE THREAD

**Issue by shu98** [MIT-LCP/mimic-code#923]
The `specimen` column in the `bg` table appears to be all null. Possibly as a consequence, the `specimen_pred` column only contains ART and nulls. 

The following query to count the number of specimens for a given specimen type returns only one row: (null, 561212). 
```
select specimen, count(*) 
from `physionet-data.mimic_derived.bg` 
group by specimen
```

Furthermore, when looking at the possible values for the `specimen` column, the result is 0. 
```
select count(distinct specimen)
from `physionet-data.mimic_derived.bg`
```

When counting the number of specimens per specimen type in the `specimen_pred` column, we get two rows: (null, 77197), (ART., 484015).
```
select specimen_pred, count(*) 
from `physionet-data.mimic_derived.bg` 
group by specimen_pred
```

I recall in the previous version of MIMIC IV, the `specimen` and `specimen_pred` columns could have any of the following values: ART., VEN., MIX., CENTRAL VENOUS., GV, null and believe there may be a bug in the way that the `specimen` is being extracted.

**Comment by cuiruixia** [comment]
What does 'ART.' mean?  Why calculate specimen_pred?  itemid 52033 indicate specimen.
