### ISSUE TITLE
MIMIC documentation

### ISSUE THREAD

**Issue by Erinaceida** [MIT-LCP/mimic-code#926]
As much as I love and appreciate MIMIC as an excellent (AND FREE!) resource, I have to say the way the resources are made available is extremely confusing, at least to me. 

Why is there more than one MIMIC repository that discusses code? There is MIMIC-IV, but there is also MIMIC-code. Both discuss building mimic, but one is updated, the other one doesn't? 
To add to the confusion, this website contains details of what the MIMIC database is: https://mimic.physionet.org/  but is not up to date, has serious documentation issues and links it has don't direct users to appropriate locations (most up to date ones, at least). This is very confusing, as this is the first website we get to after getting access to the database! 
Then, there is this website that includes documentation and seems up to date: https://mimic-iv.mit.edu/  but it also has documentation issues and the only way I found to access it, is through a link in a comment in this issue: https://github.com/MIT-LCP/mimic-code/issues/856#issuecomment-800744217_  
Not to mention it's quite difficult to get an option to download the latest MIMIC version, because the documentation from this website (https://mimic.physionet.org/) gives you this link https://physionet.org/content/mimiciii/  , which actually is a link to version https://physionet.org/content/mimiciii/1.4/ (1.4 (??)), which is not the most up to date one! 

Could we please have either these things updated or at least an overview of the resources available and to which MIMIC version they refer to? Or am I making some very silly mistakes and this is not the way to approach this? 

Thank you!

**Comment by alistairewj** [comment]
Everything is reorganized now (thanks @briangow) - all code is in this repo and all documentation is at https://mimic.mit.edu (or https://mimic.physionet.org). Documentation is version controlled at https://github.com/MIT-LCP/mimic-website. The other websites (e.g. https://mimic-iv.mit.edu) now redirect to the primary one. Anyway have a go and if there are any issues related to navigation feel free to reopen this or open a new specific issue.
