### ISSUE TITLE
DNR status on admission

### ISSUE THREAD

**Issue by danro9685** [MIT-LCP/mimic-code#93]
Hi, 

I'm looking to extract from MIMIC the DNR status on admission for a group of patients. Where can I find it? 

Thanks, 
Daniele

**Comment by alistairewj** [comment]
Look for "code status".

**Comment by danro9685** [comment]
Hi, 

could you also tell me on which table? 

Thanks, 
Daniele

**Comment by alistairewj** [comment]
Look for "code status" in D_ITEMS. The "linksto" column will then tell you what table the data is stored in... here it's CHARTEVENTS.

```sql
select * from d_items
where lower(label) like '%code status%';
```
 row_id | itemid |    label    | abbreviation |  dbsource  |   linksto   | category | unitname | param_type | conceptid 
-------- | -------- | ------------- | -------------- | ------------ | ------------- | ---------- | ---------- | ------------ | -----------
    131 |    128 | Code Status |              | carevue    | chartevents |          |          |            |          
  12754 | 223758 | Code Status | Code Status  | metavision |             | General  |          | Text       |          
(2 rows)
