### ISSUE TITLE
Clinical Notes

### ISSUE THREAD

**Issue by austinhag** [MIT-LCP/mimic-code#940]
Will MIMIC-IV have clinical notes (diagnosis notes, etc.)?  I've been digging through the documentation and data set but haven't been able to find references to clinical notes.

**Comment by Diego999** [comment]
@tompollard By curiosity, do you have kind of an idea when? (e.g., summer, fall, winter)

**Comment by tompollard** [comment]
Sorry for the delay. We have learnt not to commit to dates because we juggle this work alongside our other research commitments, and several parts of the process are not entirely under our control. I'd guess that there will be a set of notes released around Winter time, but it is only a guess!

**Comment by jplasser** [comment]
Any news for clinical notes?

**Comment by SaynaEbrahimi** [comment]
I haven't been able to find the clinical notes in mimic-iv. Were they ever released? Thanks!

**Comment by harmbuisman** [comment]
They are in a separate dataset: https://www.physionet.org/content/mimic-iv-note/2.2/

**Comment by AyeshaCamran** [comment]
Hi, Is there any documentation for MIMIC IV Clinical notes?

**Comment by alistairewj** [comment]
It's not super well maintained but there is some documentation here: https://mimic.mit.edu/docs/iv/modules/note/

**Comment by KevinKloiber** [comment]
Given the documentation, I expected to find information about the author of the clinical note in the `````discharge_detail```` dataset, but all values are missing. Is there a way to identify notes that are written by the same physician?

**Comment by alistairewj** [comment]
We haven't deidentified the author yet. No immediate plans to either.

P.S. If you could please make a new issue / new discussion thread for new questions.
