### ISSUE TITLE
Data in MIMIC-IV has only three modules while the documentation lists six modules. "Note module not to be seen".

### ISSUE THREAD

**Issue by Reshma-U** [MIT-LCP/mimic-code#946]
The MIMIC-IV data downloaded from https://physionet.org/ includes only three modules namely core, hosp, and ICU, while the MIMIC-IV website https://mimic-iv.mit.edu/docs/datasets/ contains six modules listed with ED, CXR, and Note appended in it. While ED is still not made publicly available, CXR can be accessed with a data use agreement but the Note module that contains free-text notes from EHRs is not to be seen anywhere for download. 

Could you please provide the means to access the Notes data?

**Comment by burgersmoke** [comment]
I see a note about notes being available in August (2021?).  Have the MIMIC-IV notes been made available yet?  I know they are not in the MIMIC-IV files.

Are they available anywhere else like Google or Amazon cloud?

**Comment by arielhasidim** [comment]
@burgersmoke you can the cloud options: AWS and BiqQuery. [MIMIC-IV is currently available only on BiqQuery](https://mimic.mit.edu/docs/gettingstarted/cloud/). There are two tutorial for that for some reason:

- https://mimic.mit.edu/docs/gettingstarted/cloud/bigquery/
- https://mimic.mit.edu/docs/iv/tutorials/bigquery/
