### ISSUE TITLE
MIMIC ICD9 to SNOMED 

### ISSUE THREAD

**Issue by mghassem** [MIT-LCP/mimic-code#95]
For mapping ICD9 codes to SNOMEDCT ids there is the approach outlined in https://www.cms.gov/Medicare/Quality-Initiatives-Patient-Assessment-Instruments/HospitalQualityInits/Downloads/HospitalAppendix_F.pdf which is also in the MIMIC documentation: https://mimic.physionet.org/mimictables/diagnoses_icd/.

However, the UMLS ICD9-SNOMED mapping does not have mapping for all the ICD9 codes (mappings for only ~9.5k codes but there are ~13k ICD9 codes). Looking at the actual codes that are used in the MIMIC III data:
- 1235/6841 diagnoses codes don't have UMLS ICD9-SNOMEDCT mappings
- 1364/2016 procedure codes don't have UMLS ICD9-SNOMEDCT mappings

Examples of codes that don’t have the mapping: V44.51, V13.69, V31.00, E814.0, E006.9, E869.4, 795.52, 795.51, 203.12, E943.3, 764.99

Is there some other system people use for alternative mapping?

**Comment by vojtechhuser** [comment]
OMOP mapping can be used here
