### ISSUE TITLE
hadm_id in MIMIC-CXR for MIMIC-IV

### ISSUE THREAD

**Issue by rohankhera** [MIT-LCP/mimic-code#953]
This was posted in MIMIC-III issues, but I realize that this is likely more appropriate for MIMIC-IV.  I appreciate the incredible contribution to science by the group. 

We are trying to merge some of the CXR data with MIMICIV, but can only find the ability to link at a subject_id level, rather than a hadm_id level. I was wondering if that was possible.

Thanks,
Rohan

Link to original post: https://github.com/MIT-LCP/mimic-code/issues/867#issue-829446858

**Comment by jf-11** [comment]
> MIMIC-CXR has datetime fields available in the DICOM header. Using `subject_id` and these datetimes you can assign an `hadm_id`, but since many x-rays are in the ED (just before the hospitalization) this can be a bit fuzzy and needs some care. There is an already processed extraction of the MIMIC-CXR file names with the dates in the MIMIC-CXR-JPG repo: https://physionet.org/content/mimic-cxr-jpg/

Can you provide a bit more information on how to do this?
