### ISSUE TITLE
Missing ICD9 codes from d_icd_diagnoses (that are in diagnoses_icd)

### ISSUE THREAD

**Issue by mghassem** [MIT-LCP/mimic-code#96]
There are some icd9_codes in diagnoses_icd are not in d_icd_diagnoses (144 out of 6985) and things in procedures_icd are not in d_icd_procedures (16 out of 2032).

> SELECT count(t1.icd9_code)
> FROM (select distinct icd9_code from diagnoses_icd) t1
> LEFT JOIN d_icd_diagnoses t2 
>   ON t2.icd9_code = t1.icd9_code
> WHERE t2.icd9_code IS NULL;
> ## count 
> 
>    144

If you look at one of those codes from diagnoses_icd:
**mimic=# select \* from diagnoses_icd where icd9_code = '6009';**
 row_id | subject_id | hadm_id | seq_num | icd9_code 
--------+------------+---------+---------+-----------
 256059 |      22983 |  138085 |       8 | 6009
(1 row)

**mimic=# select \* from d_icd_diagnoses where icd9_code = '6009';**
 row_id | icd9_code | short_title | long_title 
--------+-----------+-------------+------------
(0 rows)

**Comment by tompollard** [comment]
Thanks for highlighting this @mghassem.

The dictionaries (d_icd_diagnoses and d_icd_procedures) were sourced from: https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/codes.html. 

A direct link to the dictionaries is: https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/Downloads/ICD-9-CM-v32-master-descriptions.zip

We'll investigate why some of the codes don't appear in them.

**Comment by snovaisg** [comment]
Problem still persists

**Comment by alistairewj** [comment]
We won't be able to fix this as they're not valid codes. For example 600.9 is a non-billable code for prostate cancer. The actual billable codes are 600.90 or 600.91.

**Comment by snovaisg** [comment]
Some of them are valid codes. The most frequent code that is missing from the icd9 table actually is a valid code: 5185


<img width="1094" alt="Screenshot 2020-12-02 at 13 31 12" src="https://user-images.githubusercontent.com/24900912/100888784-621db500-34ae-11eb-89d4-e0983d88c363.png">

**Comment by alistairewj** [comment]
Interesting! I'll take a look but we don't plan on releasing new versions for MIMIC-III. Any fixes would be in MIMIC-IV.

**Comment by snovaisg** [comment]
Would it be beneficial to MIMIC-IV if I added a commit to write the remaining valid codes here?

**Comment by alistairewj** [comment]
I think identifying if the issue exists in MIMIC-IV and highlighting it over there would be very useful: https://github.com/MIT-LCP/mimic-iv/

For this repository - this would only (potentially) impact the comorbidity scores so that's where contributions would be useful.

**Comment by alistairewj** [comment]
similar to https://github.com/MIT-LCP/mimic-code/issues/841

this should be fixed in the latest version of mimic-iv - if it's not please feel free to raise a new issue!
