### ISSUE TITLE
vitals-first-day.sql script does not populate the corresponding view

### ISSUE THREAD

**Issue by kperros** [MIT-LCP/mimic-code#97]
The view [vitalsfirstday](https://github.com/MIT-LCP/mimic-code/blob/master/etc/firstday/vitals-first-day.sql) does not contain any rows after running the corresponding script. Other similar scripts such as gcs-first-day.sql seem to work fine.

OS: Mac OS X 10.11.5
Database: PostgreSQL 9.5.2

The mimic data were loaded in the database as per the instructions of the tutorial https://mimic.physionet.org/tutorials/install-mimic-locally-ubuntu/ .

**Comment by tompollard** [comment]
Hi @kperros, I have just rebuilt the [vitalsfirstday](https://github.com/MIT-LCP/mimic-code/blob/master/etc/firstday/vitals-first-day.sql) view using the script. It seems fine:

```sql
SELECT count(*)
FROM vitalsfirstday;

-- returns:
-- 
-- count 
-- -------
-- 59726
```

Are you using the latest version (v1.3) of MIMIC-III? If not, you should begin with an update.

**Comment by kperros** [comment]
Thanks for the response. You are right, there was an issue with the Chartevents table. After I loaded it again, the vitalsfirstday view was computed.
