### ISSUE TITLE
Bug in association: Linking “MIMIC II Waveform Matched database” with “MIMIC III Clinical database”

### ISSUE THREAD

**Issue by yoon100** [MIT-LCP/mimic-code#98]
I am trying to associate the “MIMIC II Waveform Matched database” to the “MIMIC III Clinical database”, but my results are suspicious.

According to the documentation, the “sNNNN” identifier of the matched waveform database should be the same as the SUBJECT_ID of the Clinical database.

Citation from the documentation:

> …Each subdirectory of this directory contains one or more MIMIC II Waveform Database records that have been matched with a single subject (whose MIMIC II Clinical Database Subject_ID is the name of the subdirectory). The name of each mimic2wdb/matchedwaveform record is of the form sNNNNN/sNNNNN-YYYY-MM-DD-hh-mm where NNNNN is the matching MIMIC II Clinical Database Subject_ID, and YYYY, MM, DD, hh, and mm are the surrogate year, month (01-12), and day (01-31), and the real hour (00-23) and minute (00-59), derived from the starting date and time of day of themimic2wdb/matched record. The surrogate dates match those of the corresponding MIMIC II Clinical Database version 2.6 (or later) records; note that surrogate dates in previous versions of the MIMIC II Clinical Database differ from those in version 2.6 and later. …

However, doing so produces suspicious results. For example:

The first two patients (in them of numerical ordering) of the waveform matched dataset are “s00001” and “s00020”. The first two patients of the clinical dataset are “2” and “3”.
The first patient "in common" in the two databases is the patient “20” (s00020 = 20). However, the record dates are not matching: The record of patient “20” starts at “2567-03-30 17:47:00” for the matched waveform dataset, while it starts at “2183-04-28 09:45:00” for the clinical dataset.
Any idea how to solve the problem?

Thanks,

Link to the documentation:

MIMIC II Waveform Matched database: http://www.physionet.org/physiobank/database/mimic2wdb/matched/

MIMIC-III Clinical Database https://physionet.org/works/MIMICIIIClinicalDatabase/files/

**Comment by tompollard** [comment]
MIMIC-III is essentially a complete rebuild of the MIMIC database and is significantly different from MIMIC-II, so we do not recommend attempting to link the old waveform database with the new (MIMIC-III) clinical data. 

> I am trying to associate the “MIMIC II Waveform Matched database” to the “MIMIC III Clinical database”

One key difference between MIMIC-II and MIMIC-III is the patient level date shifts that were applied, which explains the issue you are seeing.

> Any idea how to solve the problem?

Work to develop a waveform matched database for MIMIC-III is underway. Please see the following webpage for updates: http://mimic.physionet.org/mimicdata/waveforms/

**Comment by yoon100** [comment]
Thank you. Just one more question about this. 

If I am attempting to link between “MIMIC II Waveform Matched database” to the “MIMIC II Clinical database”, can I link regardless of versions within MIMIC II? (i.e. Clinical database being 2ver6 and waveform 2ver2)?

**Comment by tompollard** [comment]
Thanks @yoon100 

> If I am attempting to link between “MIMIC II Waveform Matched database” to the “MIMIC II Clinical database”, can I link regardless of versions within MIMIC II? (i.e. Clinical database being 2ver6 and waveform 2ver2)?

Yes, I believe this is correct.

**Comment by yoon100** [comment]
Thank you so much!
