### ISSUE TITLE
subject_ids between mimic iii and mimic iv

### ISSUE THREAD

**Issue by aliforgetti** [MIT-LCP/mimic-code#994]
Just wanted to know if the subject_ids are consistent in both mimic iii and mimic iv. Is it possible to link between the two?
Also since mimic iii ends in 2012 and mimic iv starts in 2008 what is the possibility of overlap of subjects between these two?

**Comment by jingge326** [comment]
@alistairewj Thank you! I wonder if the new version of MIMIC3 is available now? We are deperately look forward to extracting the overlap of MIMIC3 and MIMIC4. And then we will work on MIMIC3 & 4 as a whole.
